// LOTE 3 — CIÊNCIAS · Anos Iniciais e 6º ano. Conteúdo original do LUMI.
import type { GameWord } from '../../types'
import { block, eqsPt, fill, lesson, match, mc, open, order, SRC, tf } from '../dsl'

const FONTES = [SRC.bncc('Ciências da Natureza — Anos Iniciais e Finais'), SRC.autoral()]
const w = (word: string, clue: string, difficulty: 1 | 2 | 3 = 1): GameWord => ({ word, clue, difficulty })

export const estadosMateria = lesson({
  id: 'cie-estados-materia', subject: 'ciencias', title: 'Estados físicos da matéria', levels: ['fund1', 'fund2'], grade: '4º ao 6º ano',
  topic: 'Matéria e energia', subtopic: 'Sólido, líquido, gasoso e mudanças de estado',
  aliases: ['estados fisicos', 'estados fisicos da materia', 'solido liquido gasoso', 'mudancas de estado', 'fusao', 'solidificacao', 'vaporizacao', 'ebulicao', 'sublimacao', 'materia'],
  summary: 'Conheça os estados sólido, líquido e gasoso e as mudanças de estado que acontecem quando a matéria esquenta ou esfria.',
  intro: 'Gelo, água e vapor são a mesma substância! O que muda é a temperatura.',
  objective: 'Diferenciar os estados sólido, líquido e gasoso pela forma e pelo volume e nomear as mudanças de estado (fusão, solidificação, vaporização, condensação e sublimação).',
  next: ['cie-misturas-separacao', 'cie-ciclo-da-agua'],
  skills: { materia: 'O que é matéria', estados: 'Sólido, líquido e gasoso', aquecer: 'Mudanças ao aquecer', esfriar: 'Mudanças ao esfriar' },
  blocks: [
    block('materia', 'O que é matéria',
      'Matéria é tudo o que tem massa e ocupa lugar no espaço: a água, o ar, uma pedra, o seu corpo. A matéria é formada por partículas minúsculas que estão sempre se movendo.',
      'Um balão cheio de ar pesa um pouco mais que um balão vazio: o ar também é matéria.',
      'Matéria é tudo o que ocupa espaço e tem massa.',
      'Até o ar que você não vê é matéria: sinta o vento na mão.',
      '1. Pergunte: isso ocupa espaço?\n2. Pergunte: tem massa (peso)?\n3. Se sim, é matéria.',
      'Luz e som não são matéria: não ocupam lugar como uma pedra ou a água.'),
    block('estados', 'Os três estados',
      'No estado sólido, as partículas ficam bem juntas e presas: a forma e o volume são fixos (gelo, pedra). No líquido, elas deslizam umas sobre as outras: o volume é fixo, mas a forma muda conforme o recipiente (água, suco). No gasoso, ficam soltas e afastadas: a forma e o volume mudam e o gás ocupa todo o espaço (vapor, ar).',
      'Suco na garrafa tem a forma da garrafa; no copo, tem a forma do copo.',
      'Sólido tem forma própria; líquido pega a forma do pote; gás se espalha.',
      'O cheiro do bolo chega na sala porque o gás se espalha pelo ambiente.',
      '1. Tem forma própria? Sólido.\n2. Toma a forma do recipiente, mas não se espalha? Líquido.\n3. Se espalha por todo o espaço? Gasoso.',
      'Imagine alunos: no sólido estão sentados em fila; no líquido andam pela sala; no gasoso correm pelo pátio.'),
    block('aquecer', 'Quando a matéria esquenta',
      'Ao receber calor, as partículas se agitam mais. Fusão é a passagem de sólido para líquido (gelo derretendo). Vaporização é a passagem de líquido para gasoso: pode ser lenta (evaporação, roupa secando) ou rápida, com bolhas (ebulição, água fervendo). Sublimação é a passagem direta de sólido para gasoso (naftalina, gelo-seco).',
      'Sorvete derrete no sol (fusão); água da chaleira ferve a 100 °C ao nível do mar (ebulição).',
      'Esquentar: sólido → líquido → gás.',
      'Uma poça some depois de um dia de sol: a água evaporou.',
      '1. Veja o estado inicial e o final.\n2. Sólido → líquido: fusão.\n3. Líquido → gás: vaporização (evaporação ou ebulição).\n4. Sólido → gás direto: sublimação.',
      'Evaporação acontece em qualquer temperatura, na superfície; ebulição acontece numa temperatura certa, com bolhas por todo o líquido.'),
    block('esfriar', 'Quando a matéria esfria',
      'Ao perder calor, as partículas se aproximam. Condensação (ou liquefação) é a passagem de gás para líquido (gotas na tampa da panela). Solidificação é a passagem de líquido para sólido (água virando gelo no congelador, a 0 °C).',
      'O espelho do banheiro embaça depois do banho: o vapor condensou no vidro frio.',
      'Esfriar: gás → líquido → sólido.',
      'Fazer picolé: o suco líquido solidifica no congelador.',
      '1. Veja o estado inicial e o final.\n2. Gás → líquido: condensação.\n3. Líquido → sólido: solidificação.',
      'Fusão e solidificação são opostas, como subir e descer a mesma escada.'),
  ],
  questions: [
    mc(1, 'estados', 'Qual é o estado físico do gelo?', ['sólido', 'líquido', 'gasoso', 'nenhum'], 0, ['Tem forma própria?', 'Sim.', 'Sólido.'], 'Sólido.'),
    mc(1, 'aquecer', 'O gelo derretendo é um exemplo de:', ['solidificação', 'fusão', 'condensação', 'sublimação'], 1, ['Sólido vira…', '…líquido.', 'Fusão.'], 'Fusão.'),
    tf(1, 'materia', 'O ar é matéria.', true, ['O ar ocupa espaço?', 'Tem massa?', 'Sim, é matéria.'], 'Verdadeiro: o ar ocupa espaço e tem massa.'),
    fill(1, 'esfriar', 'A passagem do líquido para o sólido se chama ___.', ['solidificação', 'solidificacao'], ['Água vira gelo.', 'Fica sólido.', 'Solidi…'], 'Solidificação.'),
    match(2, 'aquecer', 'Ligue cada mudança de estado ao exemplo.', [['fusão', 'sorvete derretendo'], ['ebulição', 'água fervendo na panela'], ['condensação', 'espelho embaçado no banho'], ['sublimação', 'naftalina sumindo no armário']], ['Sólido → líquido.', 'Líquido → gás com bolhas.', 'Gás → líquido; sólido → gás.'], 'fusão · ebulição · condensação · sublimação.'),
    mc(2, 'estados', 'Qual estado tem volume fixo, mas toma a forma do recipiente?', ['sólido', 'líquido', 'gasoso', 'todos'], 1, ['Pense no suco no copo.', 'Não se espalha pelo ar.', 'Líquido.'], 'Líquido.'),
    mc(2, 'esfriar', 'Por que se formam gotas por fora de um copo de água gelada?', ['A água atravessa o vidro', 'O vapor do ar condensa no copo frio', 'O vidro derrete', 'O gelo evapora'], 1, ['De onde vem a água?', 'Do ar em volta.', 'Condensação.'], 'O vapor do ar esfria no copo e condensa.'),
    order(2, 'aquecer', 'Ordene o que acontece ao aquecer um cubo de gelo por bastante tempo.', ['gelo (sólido)', 'água líquida', 'vapor de água'], ['Primeiro derrete.', 'Depois ferve.', 'Vira vapor.'], 'sólido → líquido → gasoso.'),
    mc(3, 'aquecer', 'Qual é a diferença entre evaporação e ebulição?', ['Não há diferença', 'Evaporação é lenta, na superfície; ebulição é rápida, com bolhas, numa temperatura certa', 'Ebulição acontece no frio', 'Evaporação só acontece a 100 °C'], 1, ['A roupa seca a 100 °C?', 'Não; é lento.', 'Ebulição forma bolhas.'], 'Evaporação: lenta; ebulição: rápida, com bolhas.'),
    open(3, 'estados', 'Explique, usando as partículas, por que o gás se espalha pelo ambiente e o sólido não.', 'No sólido as partículas estão bem juntas e presas umas às outras, por isso ele mantém a forma. No gás as partículas estão muito afastadas e se movem livremente e rápido, então ocupam todo o espaço disponível.', ['particulas', 'juntas', 'afastadas', 'movem', 'espaco'], ['Como ficam as partículas no sólido?', 'E no gás?', 'Relacione com a forma.'], 'Sólido: partículas presas; gás: partículas soltas e afastadas.'),
  ],
  review: ['Matéria: tem massa e ocupa espaço', 'Sólido (forma fixa) · líquido (forma do recipiente) · gasoso (se espalha)', 'Aquecer: fusão, vaporização (evaporação/ebulição), sublimação', 'Esfriar: condensação, solidificação'],
  relatedQuestions: ['quais são os estados físicos da matéria', 'o que é fusão', 'diferença entre evaporação e ebulição'],
  equivalentQuestions: eqsPt(['estados físicos da matéria', 'mudanças de estado'], ['sólido líquido e gasoso', 'o que é fusão', 'o que é solidificação', 'o que é sublimação', 'o que é ebulição', 'diferença entre evaporação e ebulição', 'por que o gelo derrete', 'o que é matéria', 'o ar é matéria', 'por que o espelho embaça']),
  commonErrors: ['Achar que o ar não é matéria.', 'Confundir condensação com evaporação.', 'Achar que a evaporação só acontece quando a água ferve.'],
  sources: FONTES,
  games: { words: [w('sólido', 'estado com forma própria'), w('líquido', 'toma a forma do recipiente'), w('gasoso', 'se espalha por todo o espaço'), w('fusão', 'sólido vira líquido', 2), w('ebulição', 'líquido fervendo, com bolhas', 2), w('sublimação', 'sólido vira gás direto', 3), w('vapor', 'água no estado gasoso')] },
})

export const misturasSeparacao = lesson({
  id: 'cie-misturas-separacao', subject: 'ciencias', title: 'Misturas e separação de misturas', levels: ['fund1', 'fund2'], grade: '5º e 6º ano',
  topic: 'Matéria e energia', subtopic: 'Misturas homogêneas e heterogêneas; filtração, decantação, evaporação',
  aliases: ['misturas', 'mistura homogenea', 'mistura heterogenea', 'separacao de misturas', 'filtracao', 'decantacao', 'destilacao', 'catacao', 'peneiracao', 'substancia pura', 'imantacao'],
  summary: 'Diferencie misturas homogêneas e heterogêneas e aprenda como separar seus componentes.',
  intro: 'Café coado, feijão catado, sal tirado da água do mar: todos são jeitos de separar misturas.',
  objective: 'Classificar misturas em homogêneas e heterogêneas e escolher o método adequado de separação (catação, peneiração, imantação, filtração, decantação, evaporação e destilação).',
  prerequisites: ['cie-estados-materia'], next: ['cie-preservacao-ambiente'],
  skills: { tipos: 'Homogênea e heterogênea', solidos: 'Separando sólidos', liquidos: 'Separando sólido de líquido', dissolvido: 'Separando o que está dissolvido' },
  blocks: [
    block('tipos', 'Tipos de mistura',
      'Mistura é a reunião de duas ou mais substâncias. Na mistura homogênea não dá para ver os componentes separados: ela tem uma só fase (água com sal dissolvido, ar). Na heterogênea dá para ver dois ou mais componentes: ela tem duas ou mais fases (água e óleo, areia e pedras).',
      'Água com açúcar bem mexida: homogênea. Água com óleo: heterogênea (o óleo fica por cima).',
      'Homogênea: parece uma coisa só. Heterogênea: dá para ver as partes.',
      'Salada de frutas é heterogênea; suco em pó bem dissolvido é homogêneo.',
      '1. Olhe a mistura.\n2. Dá para ver partes diferentes? Heterogênea.\n3. Parece uma coisa só? Homogênea.\n4. Conte as fases (camadas visíveis).',
      '“Homo” quer dizer igual; “hetero” quer dizer diferente.'),
    block('solidos', 'Separando sólidos',
      'Catação: separar com as mãos ou uma pinça (tirar pedrinhas do feijão). Peneiração: usar uma peneira para separar grãos de tamanhos diferentes (areia fina e pedrinhas). Imantação: usar um ímã para retirar o ferro (limalha de ferro misturada à areia).',
      'Na construção, peneira-se a areia para tirar as pedras maiores.',
      'Mão, peneira ou ímã: depende do que você quer separar.',
      'Reciclagem: ímãs gigantes separam latas de aço do resto do lixo.',
      '1. Os pedaços são grandes e poucos? Catação.\n2. Têm tamanhos diferentes? Peneiração.\n3. Um deles é atraído por ímã? Imantação.',
      'A peneira separa pelo tamanho; o ímã separa pelo material.'),
    block('liquidos', 'Separando sólido de líquido',
      'Filtração: passar a mistura por um filtro que segura o sólido e deixa o líquido passar (coar o café, filtro de água). Decantação: deixar a mistura em repouso para o sólido mais pesado ir ao fundo e depois retirar o líquido de cima (água barrenta). A decantação também separa líquidos que não se misturam, como água e óleo.',
      'Coar o café: o pó fica no filtro, o café passa.',
      'Filtro segura o sólido; na decantação, o pesado desce sozinho.',
      'Estações de tratamento usam decantação e filtração para limpar a água.',
      '1. O sólido não se dissolveu?\n2. Quer separar rápido? Filtração.\n3. Pode esperar o sólido descer? Decantação.',
      'A decantação é como deixar o suco natural parado: a polpa vai para o fundo.'),
    block('dissolvido', 'Separando o que está dissolvido',
      'Quando o sólido está dissolvido (mistura homogênea), o filtro não resolve. Evaporação: aquece-se a mistura até o líquido virar vapor e o sólido fica (é assim nas salinas, que tiram sal da água do mar). Destilação: aquece-se a mistura e o vapor é resfriado e recolhido, recuperando o líquido puro também.',
      'Nas salinas, o sol evapora a água do mar e o sal fica no chão.',
      'Dissolveu? Tem que evaporar ou destilar.',
      'Destilação é usada para obter água destilada, usada em laboratórios.',
      '1. A mistura é homogênea (sólido dissolvido)?\n2. Só quer o sólido? Evaporação.\n3. Quer o líquido também? Destilação.',
      'Evaporação “joga fora” o líquido no ar; destilação “guarda” o líquido condensando o vapor.'),
  ],
  questions: [
    mc(1, 'tipos', 'Água e óleo formam uma mistura:', ['homogênea', 'heterogênea', 'pura', 'gasosa'], 1, ['Dá para ver as partes?', 'O óleo fica por cima.', 'Heterogênea.'], 'Heterogênea.'),
    mc(1, 'liquidos', 'Coar o café é um exemplo de:', ['catação', 'filtração', 'imantação', 'destilação'], 1, ['O pó fica no…', '…filtro.', 'Filtração.'], 'Filtração.'),
    tf(1, 'solidos', 'Um ímã serve para separar limalha de ferro da areia.', true, ['O ímã atrai o quê?', 'Ferro.', 'Imantação.'], 'Verdadeiro (imantação).'),
    fill(1, 'solidos', 'Tirar as pedrinhas do feijão com as mãos é a ___.', ['catação', 'catacao'], ['Com as mãos…', 'Cata-se.', 'Cata…'], 'Catação.'),
    match(2, 'dissolvido', 'Ligue cada situação ao método de separação.', [['sal da água do mar nas salinas', 'evaporação'], ['areia fina e pedrinhas', 'peneiração'], ['água barrenta em repouso', 'decantação'], ['obter água pura para laboratório', 'destilação']], ['O sol evapora a água.', 'Tamanhos diferentes.', 'Repouso; vapor recolhido.'], 'evaporação · peneiração · decantação · destilação.'),
    mc(2, 'tipos', 'Qual é uma mistura homogênea?', ['água e areia', 'água com sal dissolvido', 'salada de frutas', 'água e óleo'], 1, ['Parece uma coisa só?', 'O sal sumiu na água.', 'Uma fase.'], 'Água com sal dissolvido.'),
    mc(2, 'dissolvido', 'Por que a filtração NÃO separa o sal dissolvido na água?', ['O sal é muito grande', 'O sal dissolvido passa pelo filtro junto com a água', 'O filtro derrete', 'A água não passa no filtro'], 1, ['O sal está em partículas minúsculas.', 'Elas atravessam o filtro.', 'Precisa evaporar.'], 'O sal dissolvido atravessa o filtro.'),
    order(2, 'liquidos', 'Ordene os passos da decantação da água barrenta.', ['Colocar a mistura num recipiente', 'Deixar em repouso', 'Esperar a terra ir para o fundo', 'Retirar com cuidado a água de cima'], ['Primeiro o recipiente.', 'Depois o repouso.', 'Por fim retira a água.'], 'recipiente → repouso → fundo → retirar.'),
    mc(3, 'dissolvido', 'Você quer recuperar a água E o sal de uma mistura de água salgada. O melhor método é:', ['filtração', 'decantação', 'destilação', 'catação'], 2, ['Evaporar perde a água.', 'É preciso recolher o vapor.', 'Destilação.'], 'Destilação: recupera o sal e a água.'),
    open(3, 'tipos', 'Explique a diferença entre mistura homogênea e heterogênea e dê um exemplo de cada.', 'Na mistura homogênea os componentes não podem ser vistos separados, ela tem uma única fase, como água com açúcar dissolvido. Na heterogênea é possível ver os componentes, ela tem duas ou mais fases, como água e óleo.', ['fase', 'homogenea', 'heterogenea', 'ver', 'exemplo'], ['O que dá para ver em cada uma?', 'Quantas fases?', 'Um exemplo de cada.'], 'Homogênea: 1 fase · heterogênea: 2+ fases.'),
  ],
  review: ['Homogênea (1 fase) × heterogênea (2+ fases)', 'Sólidos: catação, peneiração, imantação', 'Sólido + líquido: filtração, decantação', 'Dissolvido: evaporação, destilação'],
  relatedQuestions: ['o que é mistura homogênea', 'métodos de separação de misturas', 'o que é decantação'],
  equivalentQuestions: eqsPt(['misturas', 'separação de misturas'], ['mistura homogênea e heterogênea', 'o que é filtração', 'o que é decantação', 'o que é destilação', 'o que é catação', 'o que é peneiração', 'o que é imantação', 'como separar sal da água', 'como separar água e óleo', 'como funcionam as salinas']),
  commonErrors: ['Achar que filtração separa sal dissolvido.', 'Confundir evaporação com destilação.', 'Classificar mistura pelo número de substâncias em vez do número de fases.'],
  sources: FONTES,
  games: { words: [w('filtração', 'o filtro segura o sólido'), w('decantação', 'o sólido desce em repouso', 2), w('catação', 'separar com as mãos'), w('peneira', 'separa grãos por tamanho'), w('ímã', 'atrai o ferro'), w('destilação', 'recolhe o líquido evaporado', 3), w('salinas', 'onde se tira sal da água do mar', 2)] },
})

export const seresVivos = lesson({
  id: 'cie-seres-vivos', subject: 'ciencias', title: 'Seres vivos e sua classificação', levels: ['fund1', 'fund2'], grade: '4º ao 7º ano',
  topic: 'Vida e evolução', subtopic: 'Características dos seres vivos e os reinos',
  aliases: ['seres vivos', 'caracteristicas dos seres vivos', 'reinos dos seres vivos', 'classificacao dos seres vivos', 'seres vivos e nao vivos', 'fungos', 'bacterias', 'protozoarios', 'reino animal', 'reino vegetal', 'componentes bioticos e abioticos'],
  summary: 'Descubra o que diferencia um ser vivo de um não vivo e como os cientistas organizam a vida em grupos.',
  intro: 'Uma pedra, uma árvore e um cogumelo: quais estão vivos? E por quê?',
  objective: 'Identificar as características dos seres vivos (células, nutrição, respiração, reprodução, reação a estímulos, ciclo de vida) e reconhecer os grandes grupos: bactérias, protozoários e algas, fungos, plantas e animais.',
  next: ['cie-animais-classificacao', 'cie-plantas', 'bio-celula'],
  skills: { caracteristicas: 'Características dos seres vivos', ciclo: 'Ciclo de vida', grupos: 'Grandes grupos', fungos: 'Fungos e microrganismos' },
  blocks: [
    block('caracteristicas', 'O que todo ser vivo tem',
      'Seres vivos são formados por células, precisam de energia (se alimentam), a maioria respira, crescem, reagem ao ambiente (estímulos) e se reproduzem. Pedra, água e ar são componentes não vivos (abióticos), mas são essenciais para a vida.',
      'A planta se vira para a luz (reage a estímulo); a pedra não reage a nada.',
      'Ser vivo: tem células, se alimenta, cresce, reage e se reproduz.',
      'Um fogo “cresce” e “consome”, mas não tem células nem se reproduz: não é vivo.',
      '1. É formado por células?\n2. Se alimenta e cresce?\n3. Reage a estímulos?\n4. Se reproduz?\nSe sim, é ser vivo.',
      'Um carro se move e “consome” combustível, mas não nasce, não cresce e não se reproduz: não é vivo.'),
    block('ciclo', 'O ciclo de vida',
      'Todo ser vivo passa por um ciclo de vida: nasce, cresce, pode se reproduzir e morre. Em alguns animais há grandes mudanças no caminho, a metamorfose: a borboleta é ovo, lagarta, pupa (casulo) e adulta; o sapo é ovo, girino e adulto.',
      'Feijão: semente → germinação → planta jovem → planta adulta com flores e vagens → novas sementes.',
      'Nascer, crescer, reproduzir e morrer.',
      'Na horta da escola, dá para ver o ciclo completo do feijão em poucas semanas.',
      '1. Identifique a fase inicial (ovo, semente).\n2. Veja o crescimento.\n3. Veja a reprodução.\n4. O ciclo recomeça com os descendentes.',
      'A metamorfose é como uma “troca de fantasia” completa: a lagarta e a borboleta são o mesmo ser em fases diferentes.'),
    block('grupos', 'Como os seres vivos são agrupados',
      'Os cientistas agrupam os seres vivos por semelhanças. Grandes grupos: bactérias (uma célula, sem núcleo), protozoários e algas (uma ou poucas células, com núcleo), fungos (cogumelos, bolores, leveduras), plantas (fazem fotossíntese) e animais (se alimentam de outros seres e, em geral, se locomovem).',
      'Samambaia é planta; cogumelo é fungo; ameba é protozoário; lactobacilo do iogurte é bactéria.',
      'Grupos: bactérias, protozoários/algas, fungos, plantas e animais.',
      'O fermento do pão é um fungo (levedura) — é um ser vivo!',
      '1. Tem uma célula só, sem núcleo? Bactéria.\n2. Faz fotossíntese? Planta ou alga.\n3. Absorve alimento do ambiente e não faz fotossíntese? Fungo.\n4. Come outros seres? Animal.',
      'Classificar é como organizar uma biblioteca: livros parecidos ficam na mesma prateleira.'),
    block('fungos', 'Fungos e microrganismos',
      'Fungos não são plantas: não têm clorofila e absorvem nutrientes do ambiente, muitas vezes decompondo restos de outros seres. Microrganismos são seres tão pequenos que só se vê com microscópio: muitos são úteis (iogurte, pão, decomposição) e alguns causam doenças.',
      'O bolor verde no pão velho é um fungo decompondo o alimento.',
      'Fungo não é planta: não faz fotossíntese.',
      'Sem fungos e bactérias decompositores, folhas e restos se acumulariam para sempre.',
      '1. Veja se o ser tem cor verde e faz fotossíntese.\n2. Se não faz e vive de decompor, pode ser fungo.\n3. Se é invisível a olho nu, é microrganismo.',
      'Os decompositores são o “serviço de reciclagem” da natureza: devolvem os nutrientes ao solo.'),
  ],
  questions: [
    mc(1, 'caracteristicas', 'Qual destes é um ser vivo?', ['pedra', 'água', 'cogumelo', 'areia'], 2, ['Qual tem células?', 'Qual cresce e se reproduz?', 'O cogumelo.'], 'O cogumelo (fungo).'),
    mc(1, 'fungos', 'O cogumelo pertence ao grupo dos:', ['plantas', 'animais', 'fungos', 'bactérias'], 2, ['Ele faz fotossíntese?', 'Não.', 'Fungos.'], 'Fungos.'),
    tf(1, 'caracteristicas', 'Todo ser vivo é formado por células.', true, ['A menor unidade da vida…', '…é a célula.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'ciclo', 'As grandes mudanças na vida da borboleta (lagarta → casulo → adulta) se chamam ___.', ['metamorfose'], ['Meta…', 'Transformação.', 'Metamorfose.'], 'Metamorfose.'),
    match(2, 'grupos', 'Ligue cada ser ao grupo.', [['samambaia', 'planta'], ['bolor do pão', 'fungo'], ['ameba', 'protozoário'], ['lactobacilo do iogurte', 'bactéria']], ['Faz fotossíntese.', 'Decompõe alimento.', 'Uma célula com núcleo; sem núcleo.'], 'planta · fungo · protozoário · bactéria.'),
    mc(2, 'caracteristicas', 'O fogo “cresce” e “consome” madeira. Por que ele NÃO é um ser vivo?', ['Porque é quente', 'Porque não tem células nem se reproduz', 'Porque é laranja', 'Porque apaga com água'], 1, ['Lembre das características.', 'Tem células?', 'Não.'], 'Não tem células nem se reproduz.'),
    mc(2, 'fungos', 'Por que os fungos não são classificados como plantas?', ['Porque são pequenos', 'Porque não fazem fotossíntese', 'Porque vivem no chão', 'Porque têm cor'], 1, ['Plantas têm clorofila.', 'Fungos não.', 'Não fazem fotossíntese.'], 'Fungos não fazem fotossíntese.'),
    order(1, 'ciclo', 'Ordene o ciclo de vida da borboleta.', ['ovo', 'lagarta', 'pupa (casulo)', 'borboleta adulta'], ['Começa pelo ovo.', 'Depois a lagarta.', 'Casulo e adulta.'], 'ovo → lagarta → pupa → adulta.'),
    mc(3, 'fungos', 'Qual seria a consequência se todos os decompositores sumissem?', ['Nada mudaria', 'Restos de seres vivos se acumulariam e os nutrientes não voltariam ao solo', 'As plantas cresceriam mais', 'Haveria mais oxigênio'], 1, ['O que os decompositores fazem?', 'Devolvem nutrientes.', 'Sem eles, acúmulo.'], 'Restos se acumulariam e o solo ficaria pobre.'),
    open(3, 'caracteristicas', 'Um robô se move, “come” energia da tomada e reage a sons. Ele é um ser vivo? Justifique.', 'Não. Embora se mova e reaja, o robô não é formado por células, não cresce sozinho, não tem ciclo de vida e não se reproduz. Essas características são essenciais para um ser vivo.', ['celulas', 'reproduz', 'cresce', 'ciclo', 'nao'], ['Ele tem células?', 'Ele se reproduz?', 'Tem ciclo de vida?'], 'Sem células, crescimento e reprodução, não é vivo.'),
  ],
  review: ['Seres vivos: células, nutrição, crescimento, reação, reprodução', 'Ciclo de vida e metamorfose', 'Grupos: bactérias, protozoários/algas, fungos, plantas, animais', 'Fungos não são plantas · decompositores reciclam nutrientes'],
  relatedQuestions: ['características dos seres vivos', 'quais são os reinos', 'fungo é planta'],
  equivalentQuestions: eqsPt(['seres vivos', 'classificação dos seres vivos'], ['características dos seres vivos', 'quais são os reinos dos seres vivos', 'fungo é planta', 'cogumelo é planta', 'o que é metamorfose', 'ciclo de vida da borboleta', 'o que são microrganismos', 'o que são decompositores', 'diferença entre ser vivo e não vivo', 'bactérias são seres vivos']),
  commonErrors: ['Achar que fungos são plantas.', 'Achar que tudo que se move é vivo.', 'Pensar que todo microrganismo causa doença.'],
  sources: FONTES,
  games: { words: [w('célula', 'unidade básica da vida'), w('fungo', 'grupo do cogumelo'), w('bactéria', 'uma célula sem núcleo', 2), w('metamorfose', 'transformação da lagarta em borboleta', 3), w('lagarta', 'fase da borboleta antes do casulo'), w('girino', 'fase jovem do sapo', 2), w('decompositor', 'recicla restos de seres vivos', 3)] },
})

export const animaisClassificacao = lesson({
  id: 'cie-animais-classificacao', subject: 'ciencias', title: 'Animais vertebrados e invertebrados', levels: ['fund1', 'fund2'], grade: '4º ao 7º ano',
  topic: 'Vida e evolução', subtopic: 'Mamíferos, aves, répteis, anfíbios, peixes e invertebrados',
  aliases: ['vertebrados', 'invertebrados', 'mamiferos', 'aves', 'repteis', 'anfibios', 'peixes', 'insetos', 'classificacao dos animais', 'grupos de animais', 'animais ovíparos', 'oviparos e viviparos'],
  summary: 'Separe os animais em vertebrados e invertebrados e conheça as características de cada grupo.',
  intro: 'Baleia é peixe? Morcego é ave? A classificação dos animais tem algumas surpresas.',
  objective: 'Diferenciar vertebrados de invertebrados e classificar vertebrados em peixes, anfíbios, répteis, aves e mamíferos pelas suas características (cobertura do corpo, respiração, reprodução).',
  prerequisites: ['cie-seres-vivos'], next: ['bio-cadeias-alimentares'],
  skills: { coluna: 'Vertebrados e invertebrados', agua: 'Peixes e anfíbios', terra: 'Répteis e aves', mamiferos: 'Mamíferos' },
  blocks: [
    block('coluna', 'Com ou sem coluna vertebral',
      'Vertebrados têm coluna vertebral e crânio (esqueleto interno): peixes, anfíbios, répteis, aves e mamíferos. Invertebrados não têm coluna: insetos, aranhas, minhocas, caramujos, estrelas-do-mar, águas-vivas. A maioria dos animais do planeta é invertebrada!',
      'Cachorro: vertebrado. Formiga: invertebrado (tem um esqueleto externo, a carapaça).',
      'Tem “espinha” nas costas? Vertebrado.',
      'Passe a mão nas suas costas: os “ossinhos” que você sente são as vértebras.',
      '1. O animal tem esqueleto interno com coluna?\n2. Sim: vertebrado.\n3. Não: invertebrado.',
      'A coluna é como o “mastro” de uma barraca: sustenta o corpo por dentro.'),
    block('agua', 'Peixes e anfíbios',
      'Peixes vivem na água, respiram por brânquias, em geral têm escamas e nadadeiras. Anfíbios (sapo, rã, perereca, salamandra) têm pele fina e úmida, nascem na água respirando por brânquias (girinos) e, adultos, respiram por pulmões e pela pele.',
      'Tubarão e sardinha são peixes; a rã é anfíbio.',
      'Peixe: brânquias a vida toda. Anfíbio: começa na água, depois vai para a terra.',
      '“Anfíbio” quer dizer “vida dupla”: na água e na terra.',
      '1. Vive sempre na água e respira por brânquias? Peixe.\n2. Tem pele úmida e passa por girino? Anfíbio.',
      'O girino é como um “peixinho” que depois ganha pernas e pulmões.'),
    block('terra', 'Répteis e aves',
      'Répteis (cobras, lagartos, jacarés, tartarugas) têm pele seca com escamas ou placas, respiram por pulmões e, em geral, põem ovos com casca. Aves têm penas, bico sem dentes, asas, respiram por pulmões e põem ovos. Nem toda ave voa: pinguim e avestruz não voam.',
      'Tartaruga-marinha é réptil, mesmo vivendo no mar: respira por pulmões.',
      'Réptil: escamas secas. Ave: penas.',
      'Morcego voa, mas não é ave: tem pelos e amamenta, é mamífero.',
      '1. Tem penas? Ave.\n2. Tem escamas secas ou placas e pulmões? Réptil.',
      'O que define a ave são as penas, não o voo.'),
    block('mamiferos', 'Mamíferos',
      'Mamíferos têm pelos, respiram por pulmões e as fêmeas produzem leite para amamentar os filhotes (glândulas mamárias). A maioria se desenvolve dentro da mãe (vivíparos). Baleia, golfinho e morcego são mamíferos. O ser humano também!',
      'A baleia vive no mar, mas sobe à superfície para respirar e amamenta os filhotes: é mamífero.',
      'Mamífero: pelos e amamentação.',
      'O ornitorrinco é um mamífero raro que põe ovos, mas amamenta.',
      '1. A mãe amamenta os filhotes?\n2. Tem pelos?\n3. Se sim, é mamífero.',
      'Baleia parece peixe por fora, mas por dentro é “prima” da vaca: pulmões, leite e sangue quente.'),
  ],
  questions: [
    mc(1, 'coluna', 'Qual destes animais é invertebrado?', ['cachorro', 'minhoca', 'sapo', 'pardal'], 1, ['Qual não tem coluna?', 'Corpo mole, sem ossos.', 'Minhoca.'], 'Minhoca.'),
    mc(1, 'mamiferos', 'A baleia é:', ['peixe', 'mamífero', 'anfíbio', 'réptil'], 1, ['Ela amamenta?', 'Sim.', 'Mamífero.'], 'Mamífero.'),
    tf(1, 'terra', 'Toda ave voa.', false, ['Pense no pinguim.', 'E no avestruz.', 'Não voam.'], 'Falso: pinguim e avestruz não voam.'),
    fill(1, 'agua', 'Os peixes respiram por ___.', ['brânquias', 'branquias', 'guelras'], ['Não são pulmões.', 'Ficam na cabeça.', 'Brân…'], 'Brânquias.'),
    match(2, 'terra', 'Ligue cada animal ao grupo.', [['jacaré', 'réptil'], ['perereca', 'anfíbio'], ['morcego', 'mamífero'], ['pinguim', 'ave']], ['Escamas secas.', 'Pele úmida.', 'Pelos; penas.'], 'réptil · anfíbio · mamífero · ave.'),
    mc(2, 'terra', 'O que define uma ave?', ['voar', 'ter penas', 'viver em árvores', 'ter asas grandes'], 1, ['Pinguim é ave e não voa.', 'O que todas têm?', 'Penas.'], 'Ter penas.'),
    mc(2, 'agua', 'Por que o sapo é chamado de anfíbio?', ['Porque é verde', 'Porque vive parte da vida na água e parte na terra', 'Porque pula', 'Porque tem escamas'], 1, ['Anfíbio = vida dupla.', 'Girino na água.', 'Adulto na terra.'], 'Vive na água (girino) e na terra (adulto).'),
    order(2, 'agua', 'Ordene o ciclo de vida do sapo.', ['ovo na água', 'girino com brânquias', 'girino com pernas', 'sapo adulto com pulmões'], ['Começa no ovo.', 'Depois girino.', 'Ganha pernas e pulmões.'], 'ovo → girino → girino com pernas → adulto.'),
    mc(3, 'mamiferos', 'Morcego voa, e golfinho nada. O que os coloca no MESMO grupo?', ['ambos voam', 'ambos têm pelos e amamentam os filhotes', 'ambos têm penas', 'ambos têm brânquias'], 1, ['O que os mamíferos têm?', 'Pelos e leite.', 'Mamíferos.'], 'Ambos são mamíferos: pelos e amamentação.'),
    open(3, 'coluna', 'Explique a diferença entre vertebrados e invertebrados e dê dois exemplos de cada.', 'Vertebrados têm coluna vertebral e crânio, como o cachorro e o sapo. Invertebrados não têm coluna vertebral, como a formiga e a minhoca.', ['coluna', 'vertebral', 'vertebrados', 'invertebrados', 'exemplo'], ['O que os vertebrados têm?', 'Invertebrados não têm…', 'Dê exemplos.'], 'Vertebrados: com coluna · invertebrados: sem coluna.'),
  ],
  review: ['Vertebrados (com coluna) × invertebrados (sem coluna)', 'Peixes (brânquias) · anfíbios (pele úmida, girino)', 'Répteis (escamas secas) · aves (penas)', 'Mamíferos (pelos, amamentação) — baleia e morcego incluídos'],
  relatedQuestions: ['o que são vertebrados', 'baleia é peixe', 'características dos mamíferos'],
  equivalentQuestions: eqsPt(['vertebrados', 'invertebrados', 'grupos de animais'], ['baleia é peixe ou mamífero', 'morcego é ave', 'características dos répteis', 'características dos anfíbios', 'características das aves', 'características dos mamíferos', 'como os peixes respiram', 'pinguim é ave', 'exemplos de invertebrados', 'o que é animal vivíparo']),
  commonErrors: ['Achar que baleia e golfinho são peixes.', 'Achar que morcego é ave.', 'Definir ave pelo voo em vez das penas.'],
  sources: FONTES,
  games: { words: [w('mamífero', 'tem pelos e amamenta'), w('réptil', 'pele seca com escamas', 2), w('anfíbio', 'vida na água e na terra', 2), w('penas', 'o que toda ave tem'), w('brânquias', 'órgão de respiração dos peixes', 2), w('vértebra', 'osso da coluna', 3), w('baleia', 'mamífero que vive no mar')] },
})

export const plantas = lesson({
  id: 'cie-plantas', subject: 'ciencias', title: 'As plantas e suas partes', levels: ['fund1', 'fund2'], grade: '3º ao 7º ano',
  topic: 'Vida e evolução', subtopic: 'Raiz, caule, folha, flor, fruto, semente e germinação',
  aliases: ['partes da planta', 'plantas', 'raiz caule folha', 'flor fruto semente', 'germinacao', 'polinizacao', 'reproducao das plantas', 'funcao da raiz', 'funcao do caule', 'funcao da folha'],
  summary: 'Conheça as partes das plantas, suas funções e como elas se reproduzem.',
  intro: 'Cenoura é raiz, batata é caule, e o tomate é fruto! Cada parte da planta tem uma função.',
  objective: 'Identificar as partes das plantas (raiz, caule, folha, flor, fruto e semente), suas funções, e descrever polinização e germinação.',
  prerequisites: ['cie-seres-vivos'], next: ['cie-fotossintese'],
  skills: { raiz: 'Raiz e caule', folha: 'Folha', flor: 'Flor e polinização', semente: 'Fruto, semente e germinação' },
  blocks: [
    block('raiz', 'Raiz e caule',
      'A raiz fixa a planta no solo e absorve água e sais minerais. O caule sustenta a planta e transporta a água das raízes até as folhas e o alimento produzido nas folhas para o resto da planta. Algumas raízes e caules guardam reservas: cenoura e mandioca são raízes; batata-inglesa é um caule.',
      'Tronco de árvore é caule; cenoura é uma raiz que guarda alimento.',
      'Raiz segura e bebe; caule sustenta e transporta.',
      'Quando você rega o vaso, a água é absorvida pela raiz e sobe pelo caule.',
      '1. Fica embaixo da terra e absorve água? Raiz.\n2. Sustenta e liga raiz às folhas? Caule.\n3. Lembre: tem “olhinhos” (gemas), como a batata? É caule.',
      'O caule funciona como os canos de uma casa: leva a água para cima e o alimento para baixo.'),
    block('folha', 'A folha',
      'A folha é onde acontece a maior parte da fotossíntese: ela capta a luz, recebe gás carbônico pelos estômatos e produz o alimento da planta. Também é pela folha que a planta perde vapor de água (transpiração).',
      'Folhas largas captam muita luz; folhas do cacto viraram espinhos para perder menos água.',
      'Folha = “cozinha” da planta.',
      'Plantas dentro de casa se inclinam para a janela: as folhas buscam luz.',
      '1. Veja a cor verde (clorofila).\n2. Lembre que ali se capta luz.\n3. Conclua: é onde a planta produz alimento.',
      'Os estômatos são como “janelinhas” que abrem e fecham para trocar gases.'),
    block('flor', 'Flor e polinização',
      'A flor é a parte da reprodução em muitas plantas. Ela produz o pólen. Polinização é o transporte do pólen de uma flor para outra, feito pelo vento, pela água ou por animais polinizadores (abelhas, borboletas, beija-flores, morcegos). Depois disso pode se formar o fruto com as sementes.',
      'A abelha pousa numa flor para buscar néctar, se suja de pólen e o leva para a próxima flor.',
      'Polinizar é levar o pólen de flor em flor.',
      'Sem abelhas, muitas frutas que comemos (maçã, melancia, morango) quase não se formariam.',
      '1. A flor produz pólen.\n2. Um agente (vento, abelha…) leva o pólen a outra flor.\n3. A flor é fecundada e forma fruto e sementes.',
      'O polinizador é como um carteiro que leva “cartas” (pólen) de uma flor para outra — e recebe néctar como pagamento.'),
    block('semente', 'Fruto, semente e germinação',
      'O fruto se desenvolve da flor e protege as sementes; muitos são comidos por animais, que espalham as sementes. A semente guarda o embrião de uma nova planta e uma reserva de alimento. Germinação é quando a semente, com água, ar e temperatura adequada, começa a crescer e forma uma nova planta.',
      'Feijão no algodão molhado germina em poucos dias: primeiro sai a raiz, depois o caule e as folhas.',
      'Semente + água + ar + calor = germinação.',
      'Tomate, pepino e abóbora são frutos, porque têm sementes e vieram da flor.',
      '1. Fruto: veio da flor e tem sementes.\n2. Semente: tem o embrião.\n3. Germinação: precisa de água, ar e temperatura adequada.',
      'A semente é como uma “marmita com um bebê dentro”: traz a planta e o lanche para os primeiros dias.'),
  ],
  questions: [
    mc(1, 'raiz', 'Qual parte da planta absorve água do solo?', ['folha', 'flor', 'raiz', 'fruto'], 2, ['Fica embaixo da terra.', 'Fixa a planta.', 'Raiz.'], 'A raiz.'),
    mc(1, 'folha', 'Em que parte da planta acontece a maior parte da fotossíntese?', ['raiz', 'folha', 'semente', 'caule subterrâneo'], 1, ['É verde e capta luz.', 'Tem estômatos.', 'Folha.'], 'Na folha.'),
    tf(1, 'semente', 'O tomate é um fruto.', true, ['Veio da flor?', 'Tem sementes?', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'flor', 'O transporte do pólen de uma flor para outra se chama ___.', ['polinização', 'polinizacao'], ['Pólen…', 'Poliniza…', 'Polinização.'], 'Polinização.'),
    match(2, 'raiz', 'Ligue cada parte à função.', [['raiz', 'fixa e absorve água'], ['caule', 'sustenta e transporta'], ['folha', 'produz o alimento'], ['flor', 'reprodução']], ['Embaixo da terra.', 'Os “canos”.', 'A cozinha; a reprodução.'], 'raiz · caule · folha · flor.'),
    mc(2, 'raiz', 'A batata-inglesa é:', ['raiz', 'caule', 'fruto', 'folha'], 1, ['Ela tem “olhinhos” (gemas).', 'Gemas são de caule.', 'Caule.'], 'Caule (tubérculo).'),
    mc(2, 'semente', 'Do que uma semente precisa para germinar?', ['só de luz', 'água, ar e temperatura adequada', 'só de terra', 'de adubo químico'], 1, ['Feijão germina no algodão.', 'Sem terra!', 'Água, ar e calor.'], 'Água, ar e temperatura adequada.'),
    order(1, 'semente', 'Ordene a germinação do feijão.', ['semente absorve água', 'sai a raiz', 'surge o caule', 'aparecem as primeiras folhas'], ['A semente incha.', 'Primeiro a raiz.', 'Depois caule e folhas.'], 'água → raiz → caule → folhas.'),
    mc(3, 'flor', 'Se as abelhas desaparecessem, o que aconteceria com muitas plantas?', ['Cresceriam mais', 'Teriam menos polinização e formariam menos frutos e sementes', 'Fariam mais fotossíntese', 'Nada mudaria'], 1, ['O que as abelhas fazem?', 'Polinizam.', 'Menos frutos.'], 'Menos polinização, menos frutos e sementes.'),
    open(3, 'semente', 'Por que muitas plantas produzem frutos doces e coloridos?', 'Porque atraem animais que comem os frutos e espalham as sementes para longe da planta-mãe, ajudando a planta a se espalhar e colonizar novos lugares.', ['animais', 'sementes', 'espalham', 'atraem', 'dispersao'], ['Quem come frutos?', 'O que acontece com as sementes?', 'Qual a vantagem?'], 'Atraem animais que espalham as sementes.'),
  ],
  review: ['Raiz: fixa e absorve · caule: sustenta e transporta', 'Folha: fotossíntese e transpiração', 'Flor: pólen e polinização (vento, abelhas, aves…)', 'Fruto protege sementes · germinação: água, ar e calor'],
  relatedQuestions: ['partes da planta e funções', 'o que é polinização', 'como a semente germina'],
  equivalentQuestions: eqsPt(['partes da planta', 'germinação', 'polinização'], ['função da raiz', 'função do caule', 'função da folha', 'função da flor', 'tomate é fruto', 'batata é raiz ou caule', 'cenoura é raiz', 'como as abelhas ajudam as plantas', 'do que a semente precisa para germinar', 'como as plantas se reproduzem']),
  commonErrors: ['Achar que a planta se alimenta de terra.', 'Chamar batata de raiz.', 'Achar que tomate e pepino são legumes (botanicamente são frutos).'],
  sources: FONTES,
  games: { words: [w('raiz', 'absorve água do solo'), w('caule', 'sustenta e transporta'), w('folha', 'onde ocorre a fotossíntese'), w('pólen', 'levado de flor em flor', 2), w('semente', 'guarda o embrião'), w('germinação', 'semente começa a crescer', 2), w('abelha', 'famosa polinizadora'), w('fruto', 'protege as sementes')] },
})

export const alimentacaoNutrientes = lesson({
  id: 'cie-alimentacao-nutrientes', subject: 'ciencias', title: 'Alimentação saudável e nutrientes', levels: ['fund1', 'fund2'], grade: '4º ao 8º ano',
  topic: 'Vida e evolução', subtopic: 'Carboidratos, proteínas, gorduras, vitaminas, sais minerais e ultraprocessados',
  aliases: ['nutrientes', 'alimentacao saudavel', 'carboidratos', 'proteinas', 'lipidios', 'gorduras', 'vitaminas', 'sais minerais', 'fibras', 'alimentos ultraprocessados', 'piramide alimentar', 'guia alimentar'],
  summary: 'Entenda para que serve cada nutriente e como montar um prato equilibrado.',
  intro: 'Comida não é só energia: cada nutriente tem um trabalho no corpo.',
  objective: 'Relacionar os nutrientes (carboidratos, proteínas, gorduras, vitaminas, sais minerais, fibras e água) às suas funções e diferenciar alimentos in natura, processados e ultraprocessados.',
  next: ['cie-sistema-digestorio'],
  skills: { energia: 'Carboidratos e gorduras', construtores: 'Proteínas', reguladores: 'Vitaminas, minerais, fibras e água', prato: 'Prato equilibrado e ultraprocessados' },
  blocks: [
    block('energia', 'Nutrientes que dão energia',
      'Carboidratos são a principal fonte de energia do corpo: arroz, pão, macarrão, batata, mandioca, frutas. Gorduras (lipídios) também dão energia, guardam reserva e ajudam a absorver algumas vitaminas: azeite, castanhas, abacate, manteiga. Em excesso, ambos podem prejudicar a saúde.',
      'Um prato de arroz e feijão antes do treino dá energia para jogar bola.',
      'Carboidrato e gordura = combustível.',
      'Correr uma maratona sem se alimentar deixa o corpo sem “gasolina”.',
      '1. Veja se o alimento é rico em amido ou açúcar: carboidrato.\n2. Rico em óleo ou gordura: lipídio.\n3. Ambos fornecem energia.',
      'Carboidrato é como lenha que queima rápido; gordura é como carvão: queima devagar e guarda mais energia.'),
    block('construtores', 'Proteínas: os construtores',
      'Proteínas constroem e reparam o corpo: músculos, pele, cabelo, unhas, anticorpos. São encontradas em carnes, ovos, leite, peixes e também em feijão, lentilha, grão-de-bico e soja.',
      'Arroz com feijão juntos formam uma combinação de proteínas muito completa.',
      'Proteína constrói e conserta o corpo.',
      'Quando você cresce ou machuca o joelho, as proteínas ajudam a formar tecido novo.',
      '1. Veja se o alimento é de origem animal ou uma leguminosa (feijões).\n2. Esses são ricos em proteína.\n3. Lembre a função: construção e reparo.',
      'Se o corpo fosse uma casa, as proteínas seriam os tijolos.'),
    block('reguladores', 'Vitaminas, sais minerais, fibras e água',
      'Vitaminas e sais minerais regulam o funcionamento do corpo, em pequenas quantidades: vitamina C (laranja, acerola) ajuda a defesa; cálcio (leite) forma ossos e dentes; ferro (feijão, carne, folhas escuras) ajuda o sangue a levar oxigênio. Fibras (frutas, verduras, grãos integrais) ajudam o intestino. A água é essencial para todas as funções.',
      'Falta de ferro pode causar anemia, deixando a pessoa cansada.',
      'Vitaminas e minerais = reguladores; fibras = intestino; água = tudo.',
      'Um prato colorido costuma ter mais vitaminas e minerais diferentes.',
      '1. Frutas, verduras e legumes: vitaminas, minerais e fibras.\n2. Leite e derivados: cálcio.\n3. Feijão e folhas escuras: ferro.\n4. Beba água ao longo do dia.',
      'As vitaminas são como os “mecânicos” do corpo: não são o combustível, mas mantêm o motor funcionando.'),
    block('prato', 'Prato equilibrado e ultraprocessados',
      'O Guia Alimentar para a População Brasileira recomenda basear a alimentação em alimentos in natura ou minimamente processados (arroz, feijão, frutas, legumes, ovos, carnes) e evitar ultraprocessados (refrigerantes, salgadinhos de pacote, biscoitos recheados, macarrão instantâneo), que têm muito açúcar, sal, gordura e aditivos.',
      'Prato equilibrado: metade com verduras e legumes, arroz e feijão, uma proteína e uma fruta de sobremesa.',
      'Prefira comida de verdade; evite ultraprocessados.',
      'Trocar o refrigerante pela água ou por um suco natural sem açúcar é um bom primeiro passo.',
      '1. Leia a lista de ingredientes: muitos nomes estranhos? Provavelmente ultraprocessado.\n2. Monte o prato com variedade e cores.\n3. Beba água.',
      'Uma laranja é um alimento in natura; o suco de caixinha com açúcar e aromatizante é ultraprocessado.'),
  ],
  questions: [
    mc(1, 'energia', 'Qual alimento é rico em carboidratos?', ['arroz', 'ovo', 'queijo', 'peixe'], 0, ['Fonte de energia.', 'Tem amido.', 'Arroz.'], 'Arroz.'),
    mc(1, 'construtores', 'A principal função das proteínas é:', ['dar sabor', 'construir e reparar o corpo', 'só dar energia', 'limpar o intestino'], 1, ['Músculos, pele…', 'Tijolos do corpo.', 'Construção.'], 'Construir e reparar o corpo.'),
    tf(1, 'prato', 'Refrigerante e salgadinho de pacote são ultraprocessados.', true, ['Muitos aditivos.', 'Muito açúcar e sal.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'reguladores', 'O mineral do leite importante para ossos e dentes é o ___.', ['cálcio', 'calcio'], ['Ossos fortes.', 'Começa com c.', 'Cálcio.'], 'Cálcio.'),
    match(2, 'reguladores', 'Ligue o nutriente à função.', [['ferro', 'ajuda o sangue a levar oxigênio'], ['fibras', 'ajudam o intestino'], ['vitamina C', 'ajuda a defesa do corpo'], ['carboidrato', 'principal fonte de energia']], ['Anemia é falta de ferro.', 'Grãos integrais.', 'Acerola; arroz e pão.'], 'ferro · fibras · vitamina C · carboidrato.'),
    mc(2, 'construtores', 'Qual alimento de origem vegetal é rico em proteína?', ['alface', 'feijão', 'maçã', 'arroz branco'], 1, ['Leguminosa.', 'Faz dupla com o arroz.', 'Feijão.'], 'Feijão.'),
    mc(2, 'prato', 'Qual prato é mais equilibrado?', ['macarrão instantâneo e refrigerante', 'arroz, feijão, salada, frango e uma fruta', 'só salada', 'biscoito recheado e suco de caixinha'], 1, ['Variedade.', 'Comida de verdade.', 'Arroz, feijão, salada…'], 'Arroz, feijão, salada, frango e fruta.'),
    order(2, 'prato', 'Ordene do MENOS para o MAIS processado.', ['milho in natura', 'milho em lata', 'salgadinho de milho de pacote'], ['Natural primeiro.', 'Conserva no meio.', 'Ultraprocessado por último.'], 'in natura → processado → ultraprocessado.'),
    mc(3, 'reguladores', 'Uma pessoa se sente sempre cansada e o médico diz que falta ferro no sangue. O que ela deve incluir na alimentação?', ['refrigerante', 'feijão, carnes e folhas verde-escuras', 'doces', 'só frutas cítricas'], 1, ['Onde há ferro?', 'Feijão e carnes.', 'Folhas escuras também.'], 'Alimentos ricos em ferro: feijão, carnes, folhas escuras.'),
    open(3, 'prato', 'Por que o Guia Alimentar recomenda evitar ultraprocessados?', 'Porque eles costumam ter muito açúcar, sal, gordura e aditivos, poucos nutrientes e fibras, e seu consumo frequente está ligado a obesidade, diabetes e outras doenças. O ideal é basear a alimentação em alimentos in natura ou minimamente processados.', ['acucar', 'sal', 'gordura', 'aditivos', 'doencas', 'in natura'], ['O que eles têm em excesso?', 'O que falta neles?', 'Quais os riscos?'], 'Excesso de açúcar, sal, gordura e aditivos.'),
  ],
  review: ['Energia: carboidratos e gorduras', 'Construção: proteínas (carne, ovo, feijão)', 'Reguladores: vitaminas e minerais · fibras · água', 'Prefira in natura; evite ultraprocessados'],
  relatedQuestions: ['quais são os nutrientes', 'para que servem as proteínas', 'o que são ultraprocessados'],
  equivalentQuestions: eqsPt(['nutrientes', 'alimentação saudável'], ['para que servem os carboidratos', 'para que servem as proteínas', 'para que servem as vitaminas', 'alimentos ricos em ferro', 'alimentos ricos em cálcio', 'o que são alimentos ultraprocessados', 'o que é alimento in natura', 'como montar um prato saudável', 'o que é anemia', 'guia alimentar para a população brasileira']),
  commonErrors: ['Achar que toda gordura é ruim.', 'Achar que proteína só vem de carne.', 'Confundir alimento processado com ultraprocessado.'],
  sources: [SRC.bncc('Ciências da Natureza — Anos Iniciais e Finais'), SRC.web('Guia Alimentar para a População Brasileira', 'https://www.gov.br/saude/pt-br/assuntos/saude-brasil/publicacoes-para-promocao-a-saude/guia_alimentar_populacao_brasileira_2ed.pdf', 'Ministério da Saúde', 'instituicao'), SRC.autoral()],
  games: { words: [w('proteína', 'constrói e repara o corpo'), w('vitamina', 'regula o funcionamento do corpo'), w('cálcio', 'mineral dos ossos', 2), w('ferro', 'falta dele causa anemia', 2), w('fibras', 'ajudam o intestino'), w('carboidrato', 'principal fonte de energia', 2), w('água', 'essencial para todas as funções')] },
})

export const luaFases = lesson({
  id: 'cie-lua-fases', subject: 'ciencias', title: 'A Lua: fases e eclipses', levels: ['fund1', 'fund2'], grade: '5º ao 8º ano',
  topic: 'Terra e Universo', subtopic: 'Fases da Lua, movimentos, eclipses e marés',
  aliases: ['fases da lua', 'lua cheia', 'lua nova', 'quarto crescente', 'quarto minguante', 'eclipse', 'eclipse solar', 'eclipse lunar', 'mares', 'por que a lua muda'],
  summary: 'Entenda por que a Lua muda de forma no céu, como acontecem os eclipses e a relação da Lua com as marés.',
  intro: 'A Lua não muda de verdade: o que muda é a parte iluminada que conseguimos ver.',
  objective: 'Explicar as fases da Lua pela posição relativa entre Sol, Terra e Lua, diferenciar eclipse solar de lunar e relacionar a Lua às marés.',
  prerequisites: ['cie-sistema-solar'], next: ['cie-estacoes-ano'],
  skills: { luz: 'A Lua reflete a luz do Sol', fases: 'As quatro fases', eclipses: 'Eclipses', mares: 'Lua e marés' },
  blocks: [
    block('luz', 'A Lua não tem luz própria',
      'A Lua é o satélite natural da Terra. Ela não produz luz: reflete a luz do Sol. Metade da Lua está sempre iluminada pelo Sol, mas, conforme ela gira ao redor da Terra (cerca de 29,5 dias), vemos partes diferentes dessa metade iluminada.',
      'Uma bola iluminada por uma lanterna mostra um lado claro e outro escuro, dependendo de onde você olha.',
      'A Lua é um “espelho” da luz do Sol.',
      'O “luar” é luz do Sol refletida na Lua.',
      '1. Lembre: o Sol ilumina metade da Lua.\n2. A Lua gira ao redor da Terra.\n3. Da Terra, vemos mais ou menos da parte iluminada.',
      'É como andar ao redor de um amigo iluminado por um poste: você vê o rosto dele mais ou menos iluminado conforme sua posição.'),
    block('fases', 'As quatro fases principais',
      'Lua nova: a Lua está entre a Terra e o Sol, e a face voltada para nós está escura. Quarto crescente: vemos metade iluminada, e a parte clara aumenta a cada noite. Lua cheia: a Terra está entre o Sol e a Lua, e vemos toda a face iluminada. Quarto minguante: vemos metade iluminada, diminuindo. Um ciclo completo leva cerca de 29,5 dias.',
      'Lua nova → crescente → cheia → minguante → nova de novo.',
      'Nova (escura), crescente (aumenta), cheia (toda clara), minguante (diminui).',
      'O calendário de muitos povos, e o de algumas festas, é baseado nas fases da Lua.',
      '1. A Lua some do céu? Nova.\n2. Metade clara e crescendo? Quarto crescente.\n3. Redonda e toda clara? Cheia.\n4. Metade clara e diminuindo? Quarto minguante.',
      'A fase não depende da sombra da Terra (isso é eclipse): depende só do ângulo de onde olhamos a parte iluminada.'),
    block('eclipses', 'Eclipses',
      'Eclipse solar: a Lua passa entre o Sol e a Terra e esconde o Sol (acontece na lua nova). Eclipse lunar: a Terra fica entre o Sol e a Lua, e a sombra da Terra cobre a Lua, que pode ficar avermelhada (acontece na lua cheia). Eles não ocorrem todo mês porque a órbita da Lua é um pouco inclinada.',
      'No eclipse lunar total, a Lua fica cor de cobre: a “Lua de sangue”.',
      'Solar: Lua tapa o Sol. Lunar: sombra da Terra tapa a Lua.',
      'Nunca olhe um eclipse solar diretamente: use óculos com filtro certificado.',
      '1. Quem está no meio?\n2. Lua no meio: eclipse solar.\n3. Terra no meio: eclipse lunar.',
      'É como passar a mão na frente de uma lanterna (solar) ou ficar na frente dela e fazer sombra na parede (lunar).'),
    block('mares', 'A Lua e as marés',
      'A gravidade da Lua (e, em menor grau, a do Sol) puxa a água dos oceanos, causando as marés: o nível do mar sobe (maré alta) e desce (maré baixa), geralmente duas vezes por dia. Nas luas nova e cheia, Sol e Lua se alinham e as marés ficam mais fortes.',
      'Pescadores e surfistas consultam a tábua de marés antes de ir ao mar.',
      'A Lua “puxa” o mar: marés alta e baixa.',
      'Em algumas praias, na maré baixa aparecem piscinas naturais entre as pedras.',
      '1. Lembre: a Lua atrai a Terra e seus oceanos.\n2. A água “sobe” no lado mais puxado.\n3. Com o giro da Terra, cada praia passa por marés alta e baixa.',
      'É como um ímã fraco passando sobre um prato de água: a água se levanta um pouquinho onde ele passa.'),
  ],
  questions: [
    mc(1, 'luz', 'A luz da Lua vem:', ['dela mesma', 'do Sol, refletida', 'da Terra', 'das estrelas'], 1, ['A Lua é estrela?', 'Não.', 'Reflete o Sol.'], 'Do Sol, refletida.'),
    mc(1, 'fases', 'Na lua cheia, vemos:', ['a Lua escura', 'metade iluminada', 'toda a face iluminada', 'só uma pontinha'], 2, ['Cheia = completa.', 'Redonda.', 'Toda clara.'], 'Toda a face iluminada.'),
    tf(1, 'eclipses', 'No eclipse solar, a Lua passa entre o Sol e a Terra.', true, ['A Lua tapa o Sol.', 'Ela fica no meio.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'mares', 'O sobe e desce do nível do mar causado principalmente pela Lua se chama ___.', ['maré', 'mare', 'marés', 'mares'], ['Alta e baixa.', 'Ma…', 'Maré.'], 'Maré.'),
    match(2, 'fases', 'Ligue a fase à descrição.', [['lua nova', 'face voltada para nós escura'], ['quarto crescente', 'metade clara, aumentando'], ['lua cheia', 'face toda iluminada'], ['quarto minguante', 'metade clara, diminuindo']], ['Não aparece.', 'Crescendo.', 'Redonda; diminuindo.'], 'nova · crescente · cheia · minguante.'),
    mc(2, 'eclipses', 'O eclipse lunar acontece quando:', ['a Lua está entre o Sol e a Terra', 'a Terra está entre o Sol e a Lua', 'o Sol está entre a Terra e a Lua', 'é lua nova'], 1, ['Sombra da Terra na Lua.', 'Terra no meio.', 'Na lua cheia.'], 'A Terra fica entre o Sol e a Lua.'),
    mc(2, 'luz', 'Por que vemos a Lua com formas diferentes ao longo do mês?', ['Ela encolhe', 'A sombra da Terra a cobre toda noite', 'Vemos partes diferentes da metade iluminada conforme ela gira ao redor da Terra', 'Nuvens a escondem'], 2, ['Não é a sombra da Terra.', 'Depende da posição.', 'Ângulo de visão.'], 'Vemos partes diferentes da face iluminada.'),
    order(1, 'fases', 'Ordene as fases da Lua a partir da lua nova.', ['lua nova', 'quarto crescente', 'lua cheia', 'quarto minguante'], ['Começa escura.', 'Cresce até cheia.', 'Depois diminui.'], 'nova → crescente → cheia → minguante.'),
    mc(3, 'mares', 'Por que as marés ficam mais fortes nas luas nova e cheia?', ['A Lua fica maior', 'Sol e Lua estão alinhados e somam suas atrações', 'Chove mais', 'A Terra para de girar'], 1, ['O Sol também atrai.', 'Alinhados, somam.', 'Marés de sizígia.'], 'Sol e Lua alinhados somam a atração.'),
    open(3, 'fases', 'Um colega diz que as fases da Lua são causadas pela sombra da Terra. Explique o erro.', 'A sombra da Terra só cobre a Lua durante um eclipse lunar. As fases acontecem porque, conforme a Lua gira ao redor da Terra, vemos de ângulos diferentes a metade dela que está sempre iluminada pelo Sol.', ['sombra', 'eclipse', 'angulo', 'iluminada', 'gira', 'metade'], ['Quando a sombra da Terra aparece na Lua?', 'O que muda nas fases?', 'A posição de quem observa.'], 'Fases: ângulo de visão · sombra da Terra: eclipse.'),
  ],
  review: ['A Lua reflete a luz do Sol; metade está sempre iluminada', 'Fases: nova, crescente, cheia, minguante (≈29,5 dias)', 'Eclipse solar (Lua no meio) × lunar (Terra no meio)', 'Marés: gravidade da Lua (e do Sol)'],
  relatedQuestions: ['por que a lua muda de forma', 'quais são as fases da lua', 'diferença entre eclipse solar e lunar'],
  equivalentQuestions: eqsPt(['fases da lua', 'eclipse'], ['por que a lua muda de forma', 'a lua tem luz própria', 'o que é lua nova', 'o que é lua cheia', 'o que é quarto crescente', 'diferença entre eclipse solar e lunar', 'como acontece o eclipse', 'o que causa as marés', 'lua de sangue', 'quanto tempo dura o ciclo da lua']),
  commonErrors: ['Achar que as fases são causadas pela sombra da Terra.', 'Achar que a Lua tem luz própria.', 'Confundir eclipse solar com lunar.'],
  sources: [SRC.bncc('Ciências da Natureza — Anos Iniciais e Finais'), SRC.web('Moon — Phases and Eclipses', 'https://science.nasa.gov/moon/', 'NASA', 'instituicao'), SRC.autoral()],
  games: { words: [w('eclipse', 'um astro esconde o outro'), w('satélite', 'o que a Lua é para a Terra', 2), w('maré', 'sobe e desce do mar'), w('crescente', 'fase em que a parte clara aumenta', 2), w('minguante', 'fase em que a parte clara diminui', 2), w('cheia', 'fase com a face toda iluminada')] },
})

export const preservacaoAmbiente = lesson({
  id: 'cie-preservacao-ambiente', subject: 'ciencias', title: 'Lixo, reciclagem e preservação do ambiente', levels: ['fund1', 'fund2'], grade: '3º ao 7º ano',
  topic: 'Vida e ambiente', subtopic: 'Os 3 Rs, coleta seletiva, poluição e consumo consciente',
  aliases: ['reciclagem', 'coleta seletiva', 'lixo', 'tres rs', '3 rs', 'reduzir reutilizar reciclar', 'poluicao', 'preservacao ambiental', 'meio ambiente', 'compostagem', 'cores da coleta seletiva', 'residuos solidos'],
  summary: 'Aprenda a reduzir o lixo, separar para a reciclagem e entender os impactos da poluição.',
  intro: 'Uma garrafa plástica pode levar centenas de anos para se decompor. O que fazemos com o lixo importa!',
  objective: 'Aplicar os 3 Rs (reduzir, reutilizar, reciclar), reconhecer as cores da coleta seletiva, entender a compostagem e relacionar ações humanas à poluição da água, do ar e do solo.',
  prerequisites: ['cie-misturas-separacao'], next: ['cie-energia-fontes'],
  skills: { tres: 'Os 3 Rs', coleta: 'Coleta seletiva', organico: 'Lixo orgânico e compostagem', poluicao: 'Poluição e consumo consciente' },
  blocks: [
    block('tres', 'Reduzir, reutilizar, reciclar',
      'Reduzir é consumir menos e gerar menos lixo (o mais importante). Reutilizar é dar novo uso a um objeto sem transformá-lo (pote de vidro virando porta-lápis). Reciclar é transformar o material descartado em matéria-prima para um novo produto (latinhas viram novas latinhas).',
      'Levar uma garrafinha própria em vez de comprar água em garrafa descartável é reduzir.',
      'Primeiro reduzir, depois reutilizar, por último reciclar.',
      'Doar roupas que não servem mais é reutilizar.',
      '1. Dá para não gerar esse lixo? Reduza.\n2. Dá para usar de novo? Reutilize.\n3. Não dá? Separe para reciclar.',
      'Reciclar gasta energia na fábrica; reduzir não gasta nada — por isso vem primeiro.'),
    block('coleta', 'Coleta seletiva e suas cores',
      'Na coleta seletiva, o lixo é separado por tipo de material. Cores usadas no Brasil (Resolução CONAMA 275/2001): azul para papel, vermelho para plástico, verde para vidro, amarelo para metal e marrom para orgânico. Os recicláveis devem estar limpos e secos.',
      'Caixa de papelão no azul; garrafa PET no vermelho; pote de vidro no verde; latinha no amarelo; casca de fruta no marrom.',
      'Azul papel, vermelho plástico, verde vidro, amarelo metal, marrom orgânico.',
      'Cooperativas de catadores separam e vendem os recicláveis, gerando renda.',
      '1. Identifique o material.\n2. Limpe restos de comida.\n3. Coloque na cor certa.',
      'Frase para lembrar: “PAPEL no céu (azul), PLÁSTICO no fogo (vermelho), VIDRO na mata (verde), METAL no sol (amarelo)”.'),
    block('organico', 'Lixo orgânico e compostagem',
      'Lixo orgânico são restos de alimentos, cascas e folhas. Na compostagem, fungos, bactérias e minhocas decompõem esse material e o transformam em adubo (composto), que volta para a terra. Isso reduz o lixo enviado aos aterros.',
      'Uma composteira doméstica transforma cascas de frutas e borra de café em adubo para a horta.',
      'Compostagem: resto de comida vira adubo.',
      'Na escola, uma composteira pode adubar a horta dos alunos.',
      '1. Separe cascas e restos (sem carne nem gordura em composteiras simples).\n2. Misture com folhas secas ou serragem.\n3. Espere os decompositores trabalharem.\n4. Use o adubo.',
      'A compostagem imita a natureza: na floresta, folhas caídas viram adubo sozinhas.'),
    block('poluicao', 'Poluição e consumo consciente',
      'Poluição é a presença de substâncias ou resíduos que prejudicam o ambiente e a saúde: esgoto e lixo nos rios (água), fumaça de carros e fábricas (ar), lixões e agrotóxicos em excesso (solo). O plástico no mar é engolido por tartarugas e aves. Consumo consciente é pensar antes de comprar: preciso mesmo? Quanto lixo isso gera?',
      'Óleo de cozinha jogado na pia polui a água: um litro pode contaminar milhares de litros. O certo é guardar e levar a um ponto de coleta.',
      'Poluir é sujar a água, o ar ou o solo com o que faz mal.',
      'Uma sacola plástica no mar pode ser confundida com água-viva por uma tartaruga.',
      '1. Identifique a fonte da poluição.\n2. Pense em quem é afetado.\n3. Proponha uma ação: reduzir, descartar certo, cobrar tratamento de esgoto.',
      'Lixão é depósito a céu aberto que contamina o solo; aterro sanitário é preparado com proteção e tratamento.'),
  ],
  questions: [
    mc(1, 'coleta', 'Na coleta seletiva, o lixo de papel vai na lixeira:', ['vermelha', 'azul', 'verde', 'amarela'], 1, ['Papel no céu…', 'Cor do céu.', 'Azul.'], 'Azul.'),
    mc(1, 'tres', 'Transformar um pote de vidro em porta-lápis é:', ['reduzir', 'reutilizar', 'reciclar', 'poluir'], 1, ['Não foi transformado na fábrica.', 'Novo uso.', 'Reutilizar.'], 'Reutilizar.'),
    tf(1, 'organico', 'Na compostagem, restos de comida viram adubo.', true, ['Decompositores trabalham.', 'Resultado: composto.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'coleta', 'Latinhas de metal vão na lixeira de cor ___.', ['amarela', 'amarelo'], ['Metal no sol.', 'Cor do sol.', 'Amarela.'], 'Amarela.'),
    match(2, 'coleta', 'Ligue o material à cor da lixeira.', [['garrafa PET', 'vermelho'], ['pote de vidro', 'verde'], ['caixa de papelão', 'azul'], ['casca de banana', 'marrom']], ['Plástico no fogo.', 'Vidro na mata.', 'Papel no céu; orgânico na terra.'], 'vermelho · verde · azul · marrom.'),
    mc(2, 'tres', 'Qual dos 3 Rs é o mais importante?', ['reciclar', 'reutilizar', 'reduzir', 'todos são iguais'], 2, ['Qual evita gerar lixo?', 'Não gasta energia.', 'Reduzir.'], 'Reduzir.'),
    mc(2, 'poluicao', 'Qual é o destino correto do óleo de cozinha usado?', ['pia', 'vaso sanitário', 'guardar numa garrafa e levar a um ponto de coleta', 'jogar na terra'], 2, ['Óleo polui a água.', 'Nunca na pia.', 'Ponto de coleta.'], 'Guardar e levar a um ponto de coleta.'),
    order(2, 'tres', 'Ordene as atitudes da mais para a menos prioritária.', ['reduzir o consumo', 'reutilizar objetos', 'reciclar materiais'], ['Evitar gerar lixo primeiro.', 'Depois dar novo uso.', 'Por fim reciclar.'], 'reduzir → reutilizar → reciclar.'),
    mc(3, 'poluicao', 'Qual é a diferença entre lixão e aterro sanitário?', ['Não há diferença', 'O lixão é a céu aberto e contamina; o aterro tem proteção do solo e tratamento', 'O aterro fica no mar', 'O lixão recicla tudo'], 1, ['Um é preparado, o outro não.', 'Proteção do solo.', 'Aterro sanitário.'], 'Aterro tem proteção e tratamento; lixão contamina.'),
    open(3, 'tres', 'Dê um exemplo de cada um dos 3 Rs no seu dia a dia.', 'Reduzir: levar a própria garrafinha para não comprar água em garrafa descartável. Reutilizar: usar um pote de sorvete para guardar brinquedos. Reciclar: separar latinhas e garrafas PET para a coleta seletiva.', ['reduzir', 'reutilizar', 'reciclar', 'exemplo'], ['Como gerar menos lixo?', 'Como dar novo uso?', 'O que separar para reciclar?'], 'Um exemplo para cada R.'),
  ],
  review: ['3 Rs: reduzir (1º), reutilizar, reciclar', 'Cores: azul papel · vermelho plástico · verde vidro · amarelo metal · marrom orgânico', 'Compostagem: orgânico vira adubo', 'Poluição da água, do ar e do solo · consumo consciente'],
  relatedQuestions: ['cores da coleta seletiva', 'o que são os 3 Rs', 'o que é compostagem'],
  equivalentQuestions: eqsPt(['reciclagem', 'coleta seletiva', 'os 3 Rs'], ['cores da coleta seletiva', 'lixeira azul é de quê', 'lixeira vermelha é de quê', 'diferença entre reciclar e reutilizar', 'o que é compostagem', 'como descartar óleo de cozinha', 'o que é consumo consciente', 'diferença entre lixão e aterro', 'plástico no mar', 'tipos de poluição']),
  commonErrors: ['Confundir reutilizar com reciclar.', 'Colocar recicláveis sujos de comida na coleta.', 'Jogar óleo de cozinha na pia.'],
  sources: [SRC.bncc('Ciências da Natureza — Anos Iniciais e Finais'), SRC.web('Resolução CONAMA nº 275/2001 — código de cores para a coleta seletiva', 'https://conama.mma.gov.br/', 'Conselho Nacional do Meio Ambiente (CONAMA)', 'instituicao'), SRC.autoral()],
  games: { words: [w('reciclar', 'transformar em novo produto'), w('reduzir', 'o R mais importante'), w('reutilizar', 'dar novo uso', 2), w('compostagem', 'orgânico vira adubo', 3), w('aterro', 'destino preparado para o lixo', 2), w('poluição', 'o que suja água, ar e solo'), w('orgânico', 'lixo da lixeira marrom', 2)] },
})
