// LOTE 3 — CIÊNCIAS · Anos Finais (6º ao 9º ano). Conteúdo original do LUMI.
import type { GameWord } from '../../types'
import { block, eqsPt, fill, lesson, match, mc, open, order, SRC, tf } from '../dsl'

const FONTES = [SRC.bncc('Ciências da Natureza — Anos Finais'), SRC.autoral()]
const w = (word: string, clue: string, difficulty: 1 | 2 | 3 = 1): GameWord => ({ word, clue, difficulty })

export const estacoesAno = lesson({
  id: 'cie-estacoes-ano', subject: 'ciencias', title: 'Estações do ano', levels: ['fund1', 'fund2'], grade: '5º ao 8º ano',
  topic: 'Terra e Universo', subtopic: 'Inclinação do eixo, solstícios e equinócios',
  aliases: ['estacoes do ano', 'por que existem estacoes', 'solsticio', 'equinocio', 'inclinacao da terra', 'eixo da terra', 'verao e inverno', 'primavera outono'],
  summary: 'Descubra por que existem as estações do ano e por que é verão no Brasil quando é inverno na Europa.',
  intro: 'Não é a distância do Sol que causa o verão! O segredo está na inclinação da Terra.',
  objective: 'Explicar as estações do ano pela inclinação do eixo da Terra durante a translação, reconhecer solstícios e equinócios e as estações opostas nos dois hemisférios.',
  prerequisites: ['cie-sistema-solar'], next: ['cie-terra-camadas'],
  skills: { eixo: 'Inclinação do eixo', estacoes: 'As quatro estações', marcos: 'Solstícios e equinócios', hemisferios: 'Hemisférios opostos' },
  blocks: [
    block('eixo', 'A Terra é inclinada',
      'O eixo de rotação da Terra é inclinado cerca de 23,5° em relação ao plano da sua órbita. Durante a translação, essa inclinação faz com que cada hemisfério receba a luz do Sol de forma mais direta em uma época do ano e mais inclinada em outra. Luz mais direta aquece mais e dá dias mais longos.',
      'Uma lanterna apontada reto para a mesa faz um círculo pequeno e forte; inclinada, faz uma mancha maior e fraca.',
      'A Terra é torta: por isso existem estações.',
      'No verão, o Sol do meio-dia fica mais alto no céu e as sombras são mais curtas.',
      '1. Lembre a inclinação de ≈23,5°.\n2. Veja qual hemisfério está “virado” para o Sol.\n3. Esse hemisfério tem verão; o outro, inverno.',
      'Se a Terra não fosse inclinada, quase não haveria estações: o clima de cada lugar seria parecido o ano todo.'),
    block('estacoes', 'As quatro estações',
      'Verão: dias mais longos e temperaturas mais altas. Outono: temperaturas diminuindo, dias encurtando. Inverno: dias mais curtos e frios. Primavera: temperaturas subindo e dias alongando. Perto da linha do Equador, as estações são pouco marcadas; perto dos polos, são muito marcadas.',
      'Em Porto Alegre as estações são bem definidas; em Belém, a diferença é mais entre período chuvoso e seco.',
      'Verão quente, inverno frio, e duas estações de transição.',
      'Nos polos, no verão o Sol quase não se põe (sol da meia-noite).',
      '1. Dias longos e calor? Verão.\n2. Dias curtos e frio? Inverno.\n3. Esfriando? Outono.\n4. Esquentando? Primavera.',
      'A distância Terra-Sol muda pouco: a Terra está até um pouco mais perto do Sol em janeiro — verão no Sul e inverno no Norte ao mesmo tempo.'),
    block('marcos', 'Solstícios e equinócios',
      'Solstícios marcam o início do verão e do inverno: no de verão temos o dia mais longo do ano; no de inverno, o dia mais curto. Equinócios marcam o início da primavera e do outono: o dia e a noite têm duração quase igual em toda a Terra. No Hemisfério Sul, o solstício de verão é por volta de 21 de dezembro e o de inverno por volta de 21 de junho.',
      'Equinócio de primavera no Brasil: por volta de 22 ou 23 de setembro.',
      'Solstício = dia mais longo ou mais curto. Equinócio = dia e noite iguais.',
      '“Equinócio” vem do latim e quer dizer “noite igual”.',
      '1. Dia mais longo do ano? Solstício de verão.\n2. Dia mais curto? Solstício de inverno.\n3. Dia e noite iguais? Equinócio.',
      'Solstícios são os “extremos”; equinócios são os “meios” do caminho.'),
    block('hemisferios', 'Estações opostas',
      'Como os hemisférios ficam inclinados em sentidos opostos, as estações são invertidas: quando é verão no Hemisfério Sul (Brasil, dezembro a março), é inverno no Hemisfério Norte (Europa, Estados Unidos). Por isso o Natal é no verão aqui e na neve em muitos países do norte.',
      'Em julho, é inverno em São Paulo e verão em Paris.',
      'Sul e Norte têm estações trocadas.',
      'Quem viaja em janeiro do Brasil para o Canadá sai do calor e chega na neve.',
      '1. Veja o mês.\n2. Descubra a estação no seu hemisfério.\n3. No outro hemisfério, é a oposta.',
      'É como uma gangorra: quando um lado sobe (verão), o outro desce (inverno).'),
  ],
  questions: [
    mc(1, 'eixo', 'O que causa as estações do ano?', ['a distância da Terra ao Sol', 'a inclinação do eixo da Terra', 'as fases da Lua', 'as nuvens'], 1, ['Não é a distância!', 'A Terra é…', '…inclinada.'], 'A inclinação do eixo da Terra.'),
    mc(1, 'hemisferios', 'Em dezembro, no Brasil, é:', ['inverno', 'verão', 'outono', 'primavera'], 1, ['Natal no calor.', 'Hemisfério Sul.', 'Verão.'], 'Verão (começa por volta de 21/12).'),
    tf(1, 'marcos', 'No equinócio, o dia e a noite têm duração quase igual.', true, ['Equinócio = noite igual.', 'Iguais.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'marcos', 'O dia mais longo do ano acontece no ___ de verão.', ['solstício', 'solsticio'], ['Não é equinócio.', 'Sols…', 'Solstício.'], 'Solstício.'),
    match(2, 'estacoes', 'Ligue a estação à característica.', [['verão', 'dias longos e quentes'], ['inverno', 'dias curtos e frios'], ['outono', 'temperaturas diminuindo'], ['primavera', 'temperaturas subindo']], ['Calor.', 'Frio.', 'Esfriando; esquentando.'], 'verão · inverno · outono · primavera.'),
    mc(2, 'hemisferios', 'Em julho, é inverno no Brasil. Na Europa, é:', ['inverno', 'verão', 'outono', 'primavera'], 1, ['Hemisférios opostos.', 'Inverno aqui…', 'verão lá.'], 'Verão.'),
    mc(2, 'estacoes', 'Por que as estações são pouco marcadas perto da linha do Equador?', ['Lá não há Sol', 'Lá a luz do Sol chega de forma direta o ano todo', 'Lá a Terra não gira', 'Lá sempre neva'], 1, ['Pense na lanterna reta.', 'Luz direta o ano inteiro.', 'Pouca variação.'], 'A luz chega bem direta o ano todo.'),
    order(2, 'estacoes', 'Ordene as estações no Brasil a partir de dezembro.', ['verão', 'outono', 'inverno', 'primavera'], ['Dezembro: verão.', 'Março: outono.', 'Junho: inverno; setembro: primavera.'], 'verão → outono → inverno → primavera.'),
    mc(3, 'eixo', 'A Terra está mais perto do Sol em janeiro. Por que isso NÃO explica o verão?', ['Porque em janeiro é inverno no Hemisfério Norte ao mesmo tempo', 'Porque o Sol esfria em janeiro', 'Porque a Terra para em janeiro', 'Porque a distância é igual o ano todo'], 0, ['Se fosse a distância, seria verão em todo lugar.', 'Mas no Norte é inverno.', 'É a inclinação.'], 'É inverno no Norte ao mesmo tempo: a causa é a inclinação.'),
    open(3, 'eixo', 'Explique por que existem as estações do ano.', 'Porque o eixo da Terra é inclinado cerca de 23,5°. Durante a translação ao redor do Sol, cada hemisfério recebe a luz de forma mais direta em uma parte do ano (verão, mais calor e dias longos) e mais inclinada em outra (inverno).', ['inclinado', 'eixo', 'translacao', 'direta', 'hemisferio'], ['O que é inclinado?', 'Que movimento a Terra faz?', 'Luz direta ou inclinada?'], 'Inclinação do eixo + translação.'),
  ],
  review: ['Causa: inclinação do eixo (≈23,5°), não a distância', 'Verão, outono, inverno, primavera', 'Solstícios (extremos) e equinócios (dia = noite)', 'Hemisférios têm estações opostas'],
  relatedQuestions: ['por que existem estações do ano', 'o que é solstício', 'o que é equinócio'],
  equivalentQuestions: eqsPt(['estações do ano', 'solstício', 'equinócio'], ['por que existem estações do ano', 'por que é verão no brasil e inverno na europa', 'quando começa o verão', 'quando começa o inverno', 'dia mais longo do ano', 'inclinação do eixo da terra', 'por que faz calor no verão', 'a distância do sol causa o verão', 'estações no hemisfério sul', 'por que no equador não tem estações']),
  commonErrors: ['Achar que o verão acontece porque a Terra fica mais perto do Sol.', 'Confundir solstício com equinócio.', 'Achar que é verão no mundo todo ao mesmo tempo.'],
  sources: FONTES,
  games: { words: [w('solstício', 'dia mais longo ou mais curto', 2), w('equinócio', 'dia e noite iguais', 2), w('verão', 'estação de dias longos'), w('inverno', 'estação de dias curtos'), w('eixo', 'a Terra gira em torno dele'), w('outono', 'estação que vem depois do verão'), w('primavera', 'estação das flores')] },
})

export const terraCamadas = lesson({
  id: 'cie-terra-camadas', subject: 'ciencias', title: 'Estrutura da Terra e rochas', levels: ['fund2'], grade: '6º e 7º ano',
  topic: 'Terra e Universo', subtopic: 'Crosta, manto, núcleo, placas tectônicas e tipos de rocha',
  aliases: ['camadas da terra', 'estrutura da terra', 'crosta manto nucleo', 'placas tectonicas', 'terremotos', 'vulcoes', 'tipos de rochas', 'rochas magmaticas', 'rochas sedimentares', 'rochas metamorficas', 'fosseis'],
  summary: 'Conheça as camadas da Terra, o movimento das placas e os três tipos de rochas.',
  intro: 'Se a Terra fosse um pêssego, a crosta seria só a casquinha!',
  objective: 'Descrever as camadas da Terra (crosta, manto e núcleo), relacionar placas tectônicas a terremotos e vulcões e classificar as rochas em magmáticas, sedimentares e metamórficas.',
  prerequisites: ['cie-estacoes-ano'], next: [],
  skills: { camadas: 'Camadas da Terra', placas: 'Placas tectônicas', rochas: 'Tipos de rochas', fosseis: 'Fósseis e solo' },
  blocks: [
    block('camadas', 'As camadas da Terra',
      'Crosta: camada mais externa e fina, onde vivemos (continentes e fundo dos oceanos). Manto: camada intermediária, muito quente, com rochas que se deformam lentamente; é de lá que vem o magma. Núcleo: parte central, formada principalmente de ferro e níquel, dividida em núcleo externo (líquido) e interno (sólido), com temperaturas acima de 5.000 °C.',
      'A maior perfuração já feita (na Rússia) chegou a cerca de 12 km: nem atravessou a crosta continental.',
      'Crosta fina por fora, manto no meio, núcleo no centro.',
      'Um ovo cozido: casca (crosta), clara (manto) e gema (núcleo).',
      '1. Lembre a ordem de fora para dentro: crosta, manto, núcleo.\n2. Crosta: fina e sólida.\n3. Manto: quente, pastoso em partes.\n4. Núcleo: ferro e níquel, muito quente.',
      'Quanto mais fundo, maior a temperatura e a pressão.'),
    block('placas', 'Placas tectônicas',
      'A crosta e a parte de cima do manto formam a litosfera, dividida em grandes blocos: as placas tectônicas. Elas se movem poucos centímetros por ano sobre o manto. Nas bordas das placas acontecem terremotos, vulcões e a formação de cordilheiras, como os Andes e o Himalaia.',
      'O Japão e o Chile ficam em bordas de placas: por isso têm muitos terremotos.',
      'A crosta é um “quebra-cabeça” de placas que se mexem devagar.',
      'América do Sul e África se encaixam como peças: um dia foram unidas (Pangeia).',
      '1. Localize o lugar no mapa de placas.\n2. Está na borda? Mais terremotos e vulcões.\n3. No meio da placa (como o Brasil)? Mais estável.',
      'As placas se movem mais ou menos na velocidade em que as unhas crescem.'),
    block('rochas', 'Os três tipos de rochas',
      'Magmáticas (ígneas): formadas pelo resfriamento do magma (granito, basalto). Sedimentares: formadas pelo acúmulo e compactação de sedimentos (arenito, calcário); podem conter fósseis. Metamórficas: formadas quando outras rochas sofrem muito calor e pressão e se transformam (mármore vem do calcário; ardósia, do argilito). As rochas se transformam umas nas outras no ciclo das rochas.',
      'O granito da pia da cozinha é magmático; o mármore do piso é metamórfico.',
      'Magma esfriou: magmática. Sedimentos grudaram: sedimentar. Calor e pressão transformaram: metamórfica.',
      'A Serra Gaúcha tem muito basalto, de antigos derrames de lava.',
      '1. Veio do magma ou lava? Magmática.\n2. Tem camadas e grãos grudados? Sedimentar.\n3. Foi transformada por calor e pressão? Metamórfica.',
      'Pense em bolo: a massa assando é a magmática; farelos prensados são a sedimentar; o bolo reassado e amassado é a metamórfica.'),
    block('fosseis', 'Fósseis e formação do solo',
      'Fósseis são restos ou marcas de seres vivos antigos preservados, geralmente, em rochas sedimentares (ossos, conchas, pegadas). O solo se forma pelo intemperismo: a rocha é desgastada lentamente pela chuva, vento, variação de temperatura e seres vivos, e se mistura a restos orgânicos.',
      'No Brasil, a Chapada do Araripe (CE) é famosa por fósseis de peixes e pterossauros.',
      'Fóssil = marca de vida antiga na rocha. Solo = rocha desgastada + matéria orgânica.',
      'Leva centenas de anos para formar poucos centímetros de solo: por isso ele deve ser protegido.',
      '1. Fóssil: procure em rochas sedimentares.\n2. Solo: rocha → desgaste (intemperismo) → mistura com matéria orgânica.',
      'Fósseis são como fotografias em pedra: mostram como era a vida há milhões de anos.'),
  ],
  questions: [
    mc(1, 'camadas', 'A camada mais externa da Terra, onde vivemos, é:', ['núcleo', 'manto', 'crosta', 'magma'], 2, ['É a “casca”.', 'Fina.', 'Crosta.'], 'A crosta.'),
    mc(1, 'rochas', 'O granito é uma rocha:', ['sedimentar', 'magmática', 'metamórfica', 'fóssil'], 1, ['Veio do magma.', 'Esfriou.', 'Magmática.'], 'Magmática.'),
    tf(1, 'placas', 'As placas tectônicas se movem poucos centímetros por ano.', true, ['Devagar.', 'Como as unhas crescem.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'camadas', 'A camada central da Terra, rica em ferro e níquel, é o ___.', ['núcleo', 'nucleo'], ['No centro.', 'Muito quente.', 'Núcleo.'], 'Núcleo.'),
    match(2, 'rochas', 'Ligue a rocha ao tipo.', [['basalto', 'magmática'], ['arenito', 'sedimentar'], ['mármore', 'metamórfica'], ['calcário com conchas', 'sedimentar com fósseis']], ['Lava resfriada.', 'Areia compactada.', 'Calcário transformado; restos de vida.'], 'magmática · sedimentar · metamórfica · sedimentar com fósseis.'),
    mc(2, 'placas', 'Por que o Japão tem muitos terremotos?', ['Porque é uma ilha', 'Porque fica na borda de placas tectônicas', 'Porque chove muito', 'Porque é frio'], 1, ['Onde ocorrem terremotos?', 'Nas bordas das placas.', 'Japão está numa borda.'], 'Fica na borda de placas tectônicas.'),
    mc(2, 'fosseis', 'Em que tipo de rocha é mais comum encontrar fósseis?', ['magmática', 'sedimentar', 'metamórfica', 'nenhuma'], 1, ['O magma destruiria o fóssil.', 'Camadas de sedimentos cobrem os restos.', 'Sedimentar.'], 'Sedimentar.'),
    order(1, 'camadas', 'Ordene as camadas de fora para dentro.', ['crosta', 'manto', 'núcleo externo', 'núcleo interno'], ['Casca primeiro.', 'Manto no meio.', 'Núcleo no centro.'], 'crosta → manto → núcleo externo → núcleo interno.'),
    mc(3, 'rochas', 'Um calcário é submetido a muito calor e pressão no interior da crosta. Ele pode se transformar em:', ['granito', 'mármore', 'arenito', 'basalto'], 1, ['Calor e pressão = metamórfica.', 'Calcário → …', 'Mármore.'], 'Mármore (metamórfica).'),
    open(3, 'placas', 'Por que o formato da costa da América do Sul “encaixa” no da África?', 'Porque os dois continentes já estiveram unidos num supercontinente (Pangeia) e se separaram pelo movimento lento das placas tectônicas ao longo de milhões de anos.', ['placas', 'unidos', 'pangeia', 'separaram', 'milhoes'], ['Os continentes sempre estiveram onde estão?', 'O que move os continentes?', 'Pangeia.'], 'Estiveram unidos e se separaram pelas placas.'),
  ],
  review: ['Crosta (fina) · manto (quente) · núcleo (ferro e níquel)', 'Placas tectônicas: terremotos, vulcões, montanhas nas bordas', 'Rochas: magmáticas, sedimentares, metamórficas', 'Fósseis em rochas sedimentares · solo por intemperismo'],
  relatedQuestions: ['quais são as camadas da terra', 'tipos de rochas', 'o que são placas tectônicas'],
  equivalentQuestions: eqsPt(['camadas da Terra', 'placas tectônicas', 'tipos de rochas'], ['crosta manto e núcleo', 'o que é o manto', 'do que é feito o núcleo da terra', 'por que acontecem terremotos', 'como se formam os vulcões', 'o que é rocha magmática', 'o que é rocha sedimentar', 'o que é rocha metamórfica', 'o que são fósseis', 'o que é pangeia']),
  commonErrors: ['Achar que o manto é todo líquido.', 'Confundir rochas sedimentares com metamórficas.', 'Achar que o Brasil tem muitos terremotos fortes (está no meio da placa).'],
  sources: [SRC.bncc('Ciências da Natureza — Anos Finais'), SRC.web('Serviço Geológico do Brasil — conceitos de geologia', 'https://www.sgb.gov.br/', 'Serviço Geológico do Brasil (SGB/CPRM)', 'instituicao'), SRC.autoral()],
  games: { words: [w('crosta', 'camada externa da Terra'), w('manto', 'camada intermediária'), w('núcleo', 'centro da Terra'), w('magma', 'rocha derretida no interior', 2), w('fóssil', 'marca de vida antiga', 2), w('mármore', 'rocha metamórfica', 3), w('vulcão', 'por onde sai a lava')] },
})

export const sistemaRespiratorio = lesson({
  id: 'cie-sistema-respiratorio', subject: 'ciencias', title: 'Sistema respiratório', levels: ['fund2'], grade: '8º ano',
  topic: 'Corpo humano', subtopic: 'Vias respiratórias, pulmões, trocas gasosas e cuidados',
  aliases: ['sistema respiratorio', 'respiracao', 'pulmoes', 'alveolos', 'traqueia', 'bronquios', 'diafragma', 'inspiracao', 'expiracao', 'trocas gasosas', 'hematose', 'cigarro e pulmao'],
  summary: 'Siga o caminho do ar, entenda a troca de gases nos pulmões e como cuidar da respiração.',
  intro: 'Você respira cerca de 20 mil vezes por dia sem pensar nisso!',
  objective: 'Descrever o caminho do ar pelas vias respiratórias, explicar inspiração e expiração pelo diafragma, as trocas gasosas nos alvéolos e identificar prejuízos do cigarro e da poluição.',
  prerequisites: ['cie-sistema-digestorio'], next: ['cie-sistema-circulatorio'],
  skills: { caminho: 'Caminho do ar', movimentos: 'Inspiração e expiração', trocas: 'Trocas gasosas', cuidados: 'Cuidados e doenças' },
  blocks: [
    block('caminho', 'O caminho do ar',
      'O ar entra pelo nariz (que filtra, aquece e umedece o ar), passa pela faringe, laringe (onde estão as pregas vocais), traqueia, brônquios e bronquíolos, até chegar aos alvéolos, dentro dos pulmões.',
      'Nariz → faringe → laringe → traqueia → brônquios → bronquíolos → alvéolos.',
      'O ar faz um caminho de tubos cada vez mais finos até os pulmões.',
      'Respirar pelo nariz é melhor que pela boca: os pelos e o muco filtram poeira.',
      '1. Comece no nariz.\n2. Desça pela faringe e laringe.\n3. Traqueia se divide em dois brônquios.\n4. Bronquíolos terminam nos alvéolos.',
      'Os brônquios parecem uma árvore de cabeça para baixo: a traqueia é o tronco e os bronquíolos são os galhos finos.'),
    block('movimentos', 'Inspiração e expiração',
      'Na inspiração, o diafragma (músculo abaixo dos pulmões) se contrai e desce, as costelas sobem, a caixa torácica aumenta e o ar entra. Na expiração, o diafragma relaxa e sobe, a caixa torácica diminui e o ar sai.',
      'Coloque a mão na barriga e respire fundo: ela sobe porque o diafragma desceu.',
      'Inspirar: ar entra. Expirar: ar sai. Quem comanda é o diafragma.',
      'O soluço é uma contração involuntária do diafragma.',
      '1. Diafragma contrai e desce → espaço aumenta → ar entra.\n2. Diafragma relaxa e sobe → espaço diminui → ar sai.',
      'É como uma seringa: puxar o êmbolo faz o ar entrar; empurrar faz sair.'),
    block('trocas', 'Trocas gasosas nos alvéolos',
      'Os alvéolos são saquinhos minúsculos cercados de vasos sanguíneos. Neles ocorre a hematose: o oxigênio do ar passa para o sangue, e o gás carbônico do sangue passa para o ar, que será expirado. O sangue leva o oxigênio para as células, que o usam para obter energia (respiração celular).',
      'O ar que você expira tem menos oxigênio e mais gás carbônico do que o ar que inspira.',
      'Nos alvéolos o sangue pega oxigênio e larga gás carbônico.',
      'Os pulmões têm milhões de alvéolos: juntos, eles ocupam uma área parecida com a de uma quadra de tênis.',
      '1. O ar chega aos alvéolos.\n2. O oxigênio passa para o sangue.\n3. O gás carbônico passa do sangue para o alvéolo.\n4. O ar é expirado.',
      'Respiração pulmonar (trocar gases) e respiração celular (usar o oxigênio para liberar energia) são etapas ligadas, mas diferentes.'),
    block('cuidados', 'Cuidados com a respiração',
      'O cigarro (inclusive o eletrônico) e a poluição irritam as vias respiratórias e prejudicam os alvéolos, aumentando o risco de bronquite, enfisema, asma e câncer de pulmão. Atividade física, ambientes arejados e vacinação ajudam a proteger o sistema respiratório.',
      'No enfisema, os alvéolos se rompem e a pessoa fica sem fôlego com pouco esforço.',
      'Cigarro e poluição fazem mal aos pulmões.',
      'Cobrir a boca com o braço ao tossir evita espalhar vírus respiratórios.',
      '1. Evite fumar e ambientes com fumaça.\n2. Mantenha ambientes ventilados.\n3. Pratique atividade física.\n4. Mantenha as vacinas em dia.',
      'O cigarro eletrônico também libera substâncias tóxicas e nicotina, que causa dependência.'),
  ],
  questions: [
    mc(1, 'trocas', 'Onde acontecem as trocas gasosas?', ['traqueia', 'alvéolos', 'nariz', 'laringe'], 1, ['Saquinhos nos pulmões.', 'Cercados de vasos.', 'Alvéolos.'], 'Nos alvéolos.'),
    mc(1, 'movimentos', 'Qual músculo é o principal responsável pela respiração?', ['coração', 'diafragma', 'bíceps', 'estômago'], 1, ['Fica abaixo dos pulmões.', 'Sobe e desce.', 'Diafragma.'], 'Diafragma.'),
    tf(1, 'caminho', 'O nariz filtra, aquece e umedece o ar.', true, ['Pelos e muco.', 'Aquece o ar frio.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'trocas', 'Nos alvéolos, o sangue recebe ___ e libera gás carbônico.', ['oxigênio', 'oxigenio', 'o2'], ['O gás que precisamos.', 'O₂.', 'Oxigênio.'], 'Oxigênio.'),
    match(2, 'caminho', 'Ligue cada estrutura à função.', [['laringe', 'tem as pregas vocais'], ['traqueia', 'tubo que leva o ar aos brônquios'], ['alvéolos', 'trocas gasosas'], ['diafragma', 'músculo da respiração']], ['A voz.', 'Tubo com anéis.', 'Saquinhos; músculo.'], 'laringe · traqueia · alvéolos · diafragma.'),
    mc(2, 'movimentos', 'Na inspiração, o diafragma:', ['relaxa e sobe', 'contrai e desce', 'fica parado', 'sai do lugar'], 1, ['O espaço aumenta.', 'Ele desce.', 'Contrai.'], 'Contrai e desce.'),
    mc(2, 'cuidados', 'Por que o cigarro prejudica a respiração?', ['Melhora a filtragem do ar', 'Irrita as vias e danifica os alvéolos, aumentando o risco de doenças', 'Aumenta os alvéolos', 'Não faz mal'], 1, ['Fumaça tóxica.', 'Alvéolos danificados.', 'Doenças.'], 'Irrita as vias e danifica os alvéolos.'),
    order(1, 'caminho', 'Ordene o caminho do ar.', ['nariz', 'faringe', 'laringe', 'traqueia', 'brônquios', 'alvéolos'], ['Entra pelo nariz.', 'Laringe antes da traqueia.', 'Termina nos alvéolos.'], 'nariz → faringe → laringe → traqueia → brônquios → alvéolos.'),
    mc(3, 'trocas', 'Comparando o ar inspirado com o expirado, o expirado tem:', ['mais oxigênio', 'mais gás carbônico e menos oxigênio', 'a mesma composição', 'só gás carbônico'], 1, ['O sangue pegou oxigênio.', 'E largou gás carbônico.', 'Menos O₂, mais CO₂.'], 'Mais gás carbônico e menos oxigênio.'),
    open(3, 'trocas', 'Explique a relação entre o sistema respiratório e as células do corpo.', 'O sistema respiratório leva o oxigênio do ar até os alvéolos, onde ele passa para o sangue. O sangue leva o oxigênio para as células, que o usam na respiração celular para liberar energia dos nutrientes; o gás carbônico produzido volta pelo sangue e é eliminado na expiração.', ['oxigenio', 'sangue', 'celulas', 'energia', 'gas carbonico'], ['Para onde vai o oxigênio?', 'O que as células fazem com ele?', 'E o gás carbônico?'], 'Oxigênio → sangue → células (energia) → CO₂ expirado.'),
  ],
  review: ['Caminho: nariz, faringe, laringe, traqueia, brônquios, bronquíolos, alvéolos', 'Diafragma: contrai (inspiração) e relaxa (expiração)', 'Hematose: O₂ entra no sangue, CO₂ sai', 'Cigarro e poluição prejudicam; vacinas e ar puro protegem'],
  relatedQuestions: ['caminho do ar no corpo', 'o que são alvéolos', 'como funciona o diafragma'],
  equivalentQuestions: eqsPt(['sistema respiratório', 'respiração'], ['órgãos do sistema respiratório', 'caminho do ar no corpo', 'o que são alvéolos', 'o que é hematose', 'o que é diafragma', 'diferença entre inspiração e expiração', 'como acontece a troca gasosa', 'o que o cigarro faz no pulmão', 'função da traqueia', 'função dos brônquios']),
  commonErrors: ['Achar que só o oxigênio entra e nada sai.', 'Confundir respiração pulmonar com respiração celular.', 'Achar que o cigarro eletrônico não faz mal.'],
  sources: FONTES,
  games: { words: [w('pulmão', 'órgão da respiração'), w('alvéolo', 'onde ocorrem as trocas gasosas', 2), w('traqueia', 'tubo que leva o ar', 2), w('diafragma', 'músculo da respiração', 2), w('laringe', 'tem as pregas vocais', 3), w('brônquios', 'ramos da traqueia', 3), w('oxigênio', 'gás que entra no sangue')] },
})

export const sistemaCirculatorio = lesson({
  id: 'cie-sistema-circulatorio', subject: 'ciencias', title: 'Sistema circulatório', levels: ['fund2'], grade: '8º ano',
  topic: 'Corpo humano', subtopic: 'Coração, vasos sanguíneos, sangue e circulação',
  aliases: ['sistema circulatorio', 'sistema cardiovascular', 'coracao', 'sangue', 'arterias', 'veias', 'capilares', 'hemacias', 'globulos brancos', 'plaquetas', 'pequena e grande circulacao', 'pressao arterial'],
  summary: 'Conheça o coração, os vasos e o sangue, e como a circulação leva oxigênio e nutrientes a todo o corpo.',
  intro: 'Seu coração bate mais de 100 mil vezes por dia, sem descanso!',
  objective: 'Descrever a estrutura do coração, diferenciar artérias, veias e capilares, reconhecer os componentes do sangue e explicar a pequena e a grande circulação.',
  prerequisites: ['cie-sistema-respiratorio'], next: ['cie-sistema-nervoso'],
  skills: { coracao: 'O coração', vasos: 'Vasos sanguíneos', sangue: 'Componentes do sangue', circulacao: 'Pequena e grande circulação' },
  blocks: [
    block('coracao', 'O coração',
      'O coração é um músculo do tamanho aproximado de uma mão fechada, que bombeia o sangue. Ele tem quatro cavidades: dois átrios (em cima, recebem o sangue) e dois ventrículos (embaixo, bombeiam o sangue para fora). Válvulas impedem que o sangue volte.',
      'O “tum-tá” que o médico ouve é o som das válvulas se fechando.',
      'O coração é uma bomba com 4 “salas”: 2 átrios e 2 ventrículos.',
      'Durante a corrida, o coração bate mais rápido para levar mais oxigênio aos músculos.',
      '1. Átrios: recebem sangue.\n2. Ventrículos: bombeiam sangue.\n3. Lado direito: sangue pobre em oxigênio. Lado esquerdo: rico em oxigênio.',
      'O coração é como uma casa de dois andares: átrios em cima (portas de entrada), ventrículos embaixo (portas de saída).'),
    block('vasos', 'Artérias, veias e capilares',
      'Artérias levam o sangue do coração para o corpo; têm paredes grossas e elásticas e sentem a pressão (é nelas que medimos o pulso). Veias trazem o sangue de volta ao coração; têm paredes mais finas e válvulas. Capilares são vasos finíssimos onde acontecem as trocas entre o sangue e as células.',
      'O pulso no punho é a artéria radial “batendo” a cada batimento do coração.',
      'Artéria sai do coração; veia volta ao coração; capilar troca.',
      'As veias “azuladas” que aparecem no braço estão levando sangue de volta ao coração.',
      '1. O vaso sai do coração? Artéria.\n2. Chega ao coração? Veia.\n3. É microscópico e faz trocas com as células? Capilar.',
      'Artérias são as avenidas de saída; veias, as de volta; capilares, as ruazinhas que chegam em cada casa.'),
    block('sangue', 'O que tem no sangue',
      'O sangue é formado por plasma (parte líquida com água, nutrientes, sais e hormônios) e por células: hemácias (glóbulos vermelhos, levam oxigênio graças à hemoglobina), leucócitos (glóbulos brancos, defendem o corpo) e plaquetas (ajudam na coagulação, fechando machucados).',
      'Um machucado para de sangrar porque as plaquetas formam uma “rolha” (coágulo).',
      'Hemácias levam oxigênio; leucócitos defendem; plaquetas coagulam.',
      'Doar sangue salva vidas: o corpo repõe o volume doado em poucas semanas.',
      '1. Transporte de oxigênio? Hemácias.\n2. Defesa contra micróbios? Leucócitos.\n3. Parar sangramento? Plaquetas.\n4. Parte líquida? Plasma.',
      'O sangue é como uma cidade em movimento: caminhões de entrega (hemácias), polícia (leucócitos) e equipe de reparos (plaquetas).'),
    block('circulacao', 'Pequena e grande circulação',
      'Pequena circulação (pulmonar): coração (ventrículo direito) → pulmões, onde o sangue pega oxigênio → volta ao coração (átrio esquerdo). Grande circulação (sistêmica): coração (ventrículo esquerdo) → corpo todo, levando oxigênio e nutrientes → volta ao coração (átrio direito) com gás carbônico. O sangue passa duas vezes pelo coração em cada volta completa.',
      'O sangue que sai do ventrículo esquerdo pela aorta vai até os pés e volta pelas veias cavas.',
      'Pequena: coração-pulmão-coração. Grande: coração-corpo-coração.',
      'O circulatório trabalha junto com o respiratório (oxigênio) e o digestório (nutrientes).',
      '1. Pequena circulação: vai ao pulmão buscar oxigênio.\n2. Grande circulação: leva oxigênio ao corpo.\n3. Juntas formam a circulação dupla.',
      'É como um ônibus que passa pela “estação pulmão” para abastecer de oxigênio e depois faz a linha pelo “bairro corpo”.'),
  ],
  questions: [
    mc(1, 'vasos', 'Os vasos que levam o sangue do coração para o corpo são:', ['veias', 'artérias', 'capilares', 'brônquios'], 1, ['Saem do coração.', 'Paredes grossas.', 'Artérias.'], 'Artérias.'),
    mc(1, 'sangue', 'Qual componente do sangue transporta oxigênio?', ['plaquetas', 'hemácias', 'leucócitos', 'plasma'], 1, ['Glóbulos vermelhos.', 'Têm hemoglobina.', 'Hemácias.'], 'Hemácias.'),
    tf(1, 'coracao', 'O coração tem quatro cavidades: dois átrios e dois ventrículos.', true, ['Duas em cima, duas embaixo.', '4.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'sangue', 'As células do sangue que ajudam na coagulação são as ___.', ['plaquetas'], ['Fecham o machucado.', 'Pla…', 'Plaquetas.'], 'Plaquetas.'),
    match(2, 'sangue', 'Ligue o componente à função.', [['hemácias', 'levam oxigênio'], ['leucócitos', 'defendem o corpo'], ['plaquetas', 'coagulação'], ['plasma', 'parte líquida do sangue']], ['Glóbulos vermelhos.', 'Glóbulos brancos.', 'Rolha; líquido.'], 'hemácias · leucócitos · plaquetas · plasma.'),
    mc(2, 'circulacao', 'Na pequena circulação, o sangue vai do coração para:', ['o cérebro', 'os pulmões', 'os pés', 'o estômago'], 1, ['Pega oxigênio.', 'Circulação pulmonar.', 'Pulmões.'], 'Os pulmões.'),
    mc(2, 'vasos', 'Onde acontecem as trocas entre o sangue e as células?', ['nas artérias grandes', 'nos capilares', 'no coração', 'nas veias cavas'], 1, ['Vasos finíssimos.', 'Chegam em cada célula.', 'Capilares.'], 'Nos capilares.'),
    order(2, 'circulacao', 'Ordene a pequena circulação.', ['ventrículo direito', 'artérias pulmonares', 'pulmões', 'veias pulmonares', 'átrio esquerdo'], ['Sai do ventrículo direito.', 'Vai ao pulmão.', 'Volta ao átrio esquerdo.'], 'VD → artéria pulmonar → pulmões → veias pulmonares → AE.'),
    mc(3, 'circulacao', 'Por que a circulação humana é chamada de dupla?', ['porque temos dois corações', 'porque o sangue passa duas vezes pelo coração em cada volta completa', 'porque há dois tipos de sangue', 'porque o sangue vai e volta pelo mesmo vaso'], 1, ['Pequena + grande.', 'Duas passagens.', 'Pelo coração.'], 'O sangue passa duas vezes pelo coração.'),
    open(3, 'circulacao', 'Explique como o sistema circulatório trabalha junto com o respiratório.', 'Na pequena circulação, o sangue vai aos pulmões, onde recebe oxigênio e libera gás carbônico nos alvéolos. Na grande circulação, esse sangue oxigenado é levado a todas as células, e o sangue com gás carbônico volta ao coração e depois aos pulmões para ser eliminado.', ['pulmoes', 'oxigenio', 'gas carbonico', 'celulas', 'alveolos', 'circulacao'], ['O que o sangue faz nos pulmões?', 'Para onde ele leva o oxigênio?', 'E o gás carbônico?'], 'Pulmões oxigenam; circulação distribui.'),
  ],
  review: ['Coração: 2 átrios (recebem) e 2 ventrículos (bombeiam)', 'Artérias (saem) · veias (voltam) · capilares (trocas)', 'Sangue: plasma, hemácias, leucócitos, plaquetas', 'Circulação dupla: pequena (pulmões) e grande (corpo)'],
  relatedQuestions: ['como funciona o coração', 'diferença entre artéria e veia', 'componentes do sangue'],
  equivalentQuestions: eqsPt(['sistema circulatório', 'coração', 'sangue'], ['diferença entre artéria e veia', 'o que são capilares', 'o que são hemácias', 'o que são leucócitos', 'o que são plaquetas', 'pequena e grande circulação', 'quantas cavidades tem o coração', 'o que é átrio e ventrículo', 'por que a circulação é dupla', 'como o sangue leva oxigênio']),
  commonErrors: ['Achar que veias sempre levam sangue pobre em oxigênio (as veias pulmonares levam sangue oxigenado).', 'Confundir hemácias com leucócitos.', 'Achar que o sangue passa uma única vez pelo coração.'],
  sources: FONTES,
  games: { words: [w('coração', 'bomba do sangue'), w('artéria', 'vaso que sai do coração', 2), w('veia', 'vaso que volta ao coração'), w('hemácia', 'glóbulo vermelho', 2), w('plaquetas', 'fazem a coagulação', 2), w('ventrículo', 'cavidade que bombeia o sangue', 3), w('capilar', 'vaso finíssimo de trocas', 3)] },
})

export const sistemaNervoso = lesson({
  id: 'cie-sistema-nervoso', subject: 'ciencias', title: 'Sistema nervoso e sentidos', levels: ['fund2'], grade: '6º e 8º ano',
  topic: 'Corpo humano', subtopic: 'Encéfalo, medula, neurônios, atos reflexos e órgãos dos sentidos',
  aliases: ['sistema nervoso', 'cerebro', 'encefalo', 'neuronio', 'medula espinhal', 'ato reflexo', 'cinco sentidos', 'orgaos dos sentidos', 'visao', 'audicao', 'tato', 'olfato', 'paladar', 'cerebelo'],
  summary: 'Entenda como o sistema nervoso recebe informações, decide e comanda o corpo, e como funcionam os sentidos.',
  intro: 'Tirar a mão de uma panela quente acontece antes mesmo de você pensar. Como?',
  objective: 'Identificar as partes do sistema nervoso central e periférico, explicar a função dos neurônios, diferenciar ato voluntário de ato reflexo e relacionar os órgãos dos sentidos aos estímulos que captam.',
  prerequisites: ['cie-sistema-circulatorio'], next: [],
  skills: { central: 'Sistema nervoso central', neuronio: 'Neurônios e nervos', reflexo: 'Atos voluntários e reflexos', sentidos: 'Os sentidos' },
  blocks: [
    block('central', 'Encéfalo e medula',
      'O sistema nervoso central (SNC) é formado pelo encéfalo (protegido pelo crânio) e pela medula espinhal (protegida pela coluna). No encéfalo, o cérebro controla pensamento, memória, linguagem e movimentos voluntários; o cerebelo coordena o equilíbrio e os movimentos; o tronco encefálico controla funções vitais, como respiração e batimentos.',
      'Andar de bicicleta sem cair depende muito do cerebelo.',
      'Encéfalo e medula são a “central de comando”.',
      'Capacete protege o encéfalo em quedas de bicicleta e skate.',
      '1. Pensar, lembrar, falar? Cérebro.\n2. Equilíbrio e coordenação? Cerebelo.\n3. Respiração e batimentos? Tronco encefálico.\n4. Ligação encéfalo-corpo e reflexos? Medula.',
      'O SNC é como a central de uma empresa: recebe relatórios, decide e envia ordens.'),
    block('neuronio', 'Neurônios e nervos',
      'Neurônios são as células do sistema nervoso; transmitem mensagens na forma de impulsos nervosos (sinais elétricos e químicos). Nervos são feixes de prolongamentos de neurônios que ligam o SNC a todo o corpo e formam o sistema nervoso periférico (SNP): nervos sensitivos levam informações ao SNC; nervos motores levam ordens aos músculos.',
      'Ao pisar numa pedrinha, nervos sensitivos avisam o encéfalo; nervos motores fazem você levantar o pé.',
      'Neurônio manda mensagem; nervo é o “cabo” que leva a mensagem.',
      'Lesões na medula podem cortar a comunicação entre o encéfalo e as pernas.',
      '1. Estímulo é captado.\n2. Nervo sensitivo leva ao SNC.\n3. SNC decide.\n4. Nervo motor leva a ordem ao músculo.',
      'Os nervos são como fios elétricos de uma casa ligando cada cômodo ao quadro de luz.'),
    block('reflexo', 'Atos voluntários e reflexos',
      'Ato voluntário é aquele que decidimos fazer (pegar um lápis), comandado pelo cérebro. Ato reflexo é uma resposta rápida e involuntária, que muitas vezes é coordenada pela medula espinhal, sem esperar o cérebro decidir (tirar a mão do fogo, piscar quando algo se aproxima do olho).',
      'O médico bate no joelho com um martelinho e a perna chuta sozinha: reflexo patelar.',
      'Voluntário: você decide. Reflexo: acontece sozinho, rápido.',
      'O reflexo protege o corpo: tirar a mão de algo quente evita uma queimadura maior.',
      '1. Você decidiu fazer? Voluntário.\n2. Foi automático e muito rápido? Reflexo.\n3. Lembre: reflexos costumam passar pela medula.',
      'O reflexo é um “atalho”: a medula resolve antes de a mensagem chegar ao cérebro.'),
    block('sentidos', 'Os órgãos dos sentidos',
      'Os sentidos captam estímulos do ambiente e enviam ao encéfalo: visão (olhos, luz), audição (orelhas, som; a orelha interna também ajuda no equilíbrio), olfato (nariz, cheiros), gustação ou paladar (língua, sabores: doce, salgado, azedo, amargo e umami) e tato (pele, pressão, dor, calor e frio). Olfato e paladar trabalham juntos no sabor dos alimentos.',
      'Com o nariz entupido, a comida parece sem gosto: parte do sabor vem do cheiro.',
      'Cinco sentidos: visão, audição, olfato, paladar e tato.',
      'Usar fones em volume muito alto pode danificar a audição de forma permanente.',
      '1. Identifique o estímulo (luz, som, cheiro, sabor, toque).\n2. Relacione ao órgão.\n3. Lembre: quem interpreta é o encéfalo.',
      'Os órgãos dos sentidos são como sensores; o encéfalo é o computador que interpreta os sinais.'),
  ],
  questions: [
    mc(1, 'central', 'Qual parte do encéfalo coordena o equilíbrio?', ['cérebro', 'cerebelo', 'medula', 'estômago'], 1, ['Andar de bicicleta.', 'Coordenação.', 'Cerebelo.'], 'Cerebelo.'),
    mc(1, 'reflexo', 'Tirar a mão rapidamente de uma panela quente é um ato:', ['voluntário', 'reflexo', 'pensado', 'digestivo'], 1, ['Você pensou antes?', 'Foi automático.', 'Reflexo.'], 'Reflexo.'),
    tf(1, 'neuronio', 'Neurônios são as células do sistema nervoso.', true, ['Transmitem impulsos.', 'Células nervosas.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'sentidos', 'O sentido que percebe sons é a ___.', ['audição', 'audicao'], ['Pelas orelhas.', 'Ouvir.', 'Audição.'], 'Audição.'),
    match(2, 'sentidos', 'Ligue o órgão ao sentido.', [['olhos', 'visão'], ['pele', 'tato'], ['língua', 'paladar'], ['nariz', 'olfato']], ['Luz.', 'Toque.', 'Sabor; cheiro.'], 'visão · tato · paladar · olfato.'),
    mc(2, 'central', 'O sistema nervoso central é formado por:', ['nervos e músculos', 'encéfalo e medula espinhal', 'coração e pulmões', 'olhos e orelhas'], 1, ['Central de comando.', 'Crânio e coluna protegem.', 'Encéfalo e medula.'], 'Encéfalo e medula espinhal.'),
    mc(2, 'sentidos', 'Por que a comida parece sem gosto quando estamos gripados e com nariz entupido?', ['A língua para de funcionar', 'Parte do sabor depende do olfato', 'A comida muda', 'O estômago fica cheio'], 1, ['Sentidos juntos.', 'Cheiro + gosto.', 'Olfato.'], 'Parte do sabor vem do olfato.'),
    order(2, 'neuronio', 'Ordene o caminho de uma resposta a um estímulo.', ['estímulo captado pelo órgão do sentido', 'nervo sensitivo leva a informação', 'sistema nervoso central processa', 'nervo motor leva a ordem ao músculo'], ['Começa no estímulo.', 'Sobe pelo nervo sensitivo.', 'Volta pelo nervo motor.'], 'estímulo → nervo sensitivo → SNC → nervo motor.'),
    mc(3, 'reflexo', 'Por que o ato reflexo é mais rápido que o voluntário?', ['Porque usa músculos mais fortes', 'Porque a resposta é coordenada pela medula, sem esperar a decisão do cérebro', 'Porque não usa neurônios', 'Porque vem do coração'], 1, ['Atalho.', 'Medula responde.', 'Sem passar pela decisão do cérebro.'], 'A medula responde antes do cérebro decidir.'),
    open(3, 'central', 'Por que é importante usar capacete ao andar de bicicleta ou skate?', 'Porque o capacete protege o encéfalo, que controla funções essenciais como pensamento, movimentos, equilíbrio, respiração e batimentos. Lesões no encéfalo podem ser graves e permanentes.', ['encefalo', 'protege', 'lesao', 'funcoes', 'cerebro'], ['O que fica dentro do crânio?', 'O que ele controla?', 'Lesões podem ser graves.'], 'Protege o encéfalo, central do corpo.'),
  ],
  review: ['SNC: encéfalo (cérebro, cerebelo, tronco) + medula', 'Neurônios e nervos (sensitivos e motores) · SNP', 'Voluntário (cérebro) × reflexo (medula, rápido)', 'Sentidos: visão, audição, olfato, paladar, tato'],
  relatedQuestions: ['partes do sistema nervoso', 'o que é ato reflexo', 'quais são os cinco sentidos'],
  equivalentQuestions: eqsPt(['sistema nervoso', 'ato reflexo', 'cinco sentidos'], ['o que é neurônio', 'função do cérebro', 'função do cerebelo', 'função da medula espinhal', 'diferença entre ato reflexo e voluntário', 'o que é sistema nervoso central', 'o que é sistema nervoso periférico', 'órgãos dos sentidos', 'como funciona o paladar', 'o que são nervos']),
  commonErrors: ['Achar que todo movimento passa pela decisão do cérebro.', 'Confundir cérebro com encéfalo.', 'Achar que o paladar funciona sozinho, sem o olfato.'],
  sources: FONTES,
  games: { words: [w('neurônio', 'célula do sistema nervoso', 2), w('cérebro', 'pensamento e memória'), w('cerebelo', 'equilíbrio', 2), w('medula', 'coordena reflexos', 2), w('reflexo', 'resposta rápida e automática'), w('olfato', 'sentido dos cheiros'), w('audição', 'sentido dos sons')] },
})

export const microrganismosVacinas = lesson({
  id: 'cie-microrganismos-vacinas', subject: 'ciencias', title: 'Microrganismos, doenças e vacinas', levels: ['fund1', 'fund2'], grade: '4º ao 7º ano',
  topic: 'Vida e evolução', subtopic: 'Vírus, bactérias, fungos, protozoários, prevenção e vacinação',
  aliases: ['microrganismos', 'microbios', 'virus', 'bacterias', 'vacinas', 'como funciona a vacina', 'antibiotico', 'doencas', 'prevencao de doencas', 'higiene', 'dengue', 'sistema imunologico'],
  summary: 'Conheça os microrganismos úteis e os que causam doenças, e entenda como as vacinas nos protegem.',
  intro: 'Nem todo micróbio é vilão — e as vacinas ensinam o corpo a se defender dos que são.',
  objective: 'Reconhecer vírus, bactérias, fungos e protozoários, citar usos benéficos e doenças que causam, explicar como as vacinas funcionam e indicar medidas de prevenção.',
  prerequisites: ['cie-seres-vivos'], next: [],
  skills: { tipos: 'Tipos de microrganismos', uteis: 'Microrganismos úteis', vacinas: 'Como as vacinas funcionam', prevencao: 'Prevenção e antibióticos' },
  blocks: [
    block('tipos', 'Quem são os microrganismos',
      'Microrganismos são seres tão pequenos que só podem ser vistos ao microscópio. Bactérias são células simples, sem núcleo. Fungos microscópicos incluem leveduras e bolores. Protozoários são seres de uma célula com núcleo. Os vírus são ainda menores e não têm células: só se multiplicam dentro de células de outros seres.',
      'Gripe e covid-19 são causadas por vírus; tuberculose, por bactéria; micose, por fungo; malária e doença de Chagas, por protozoários.',
      'Vírus, bactérias, fungos e protozoários: pequenos demais para ver a olho nu.',
      'Uma gota de água de lagoa ao microscópio mostra dezenas de protozoários nadando.',
      '1. Tem célula? Se não, é vírus.\n2. Célula sem núcleo? Bactéria.\n3. Célula com núcleo, vida livre e se move? Protozoário.\n4. Bolor ou levedura? Fungo.',
      'O vírus é como um “pen drive pirata”: sozinho não faz nada, mas dentro de uma célula a obriga a fazer cópias dele.'),
    block('uteis', 'Micróbios do bem',
      'Muitos microrganismos são úteis: bactérias transformam leite em iogurte e queijo; leveduras (fungos) fazem o pão crescer; decompositores reciclam nutrientes no solo; bactérias do intestino ajudam na digestão e na defesa. Alguns são usados para produzir medicamentos, como antibióticos e insulina.',
      'O fermento biológico do pão é formado por leveduras vivas que produzem gás carbônico e fazem a massa crescer.',
      'Muitos micróbios ajudam: iogurte, pão, solo e intestino.',
      'A penicilina, primeiro antibiótico, foi descoberta a partir de um bolor (fungo).',
      '1. Pense em alimentos fermentados.\n2. Pense na decomposição.\n3. Pense na flora intestinal.\n4. Pense em remédios.',
      'A maioria das bactérias não causa doença: é como dizer que todo cachorro morde — não é verdade.'),
    block('vacinas', 'Como a vacina protege',
      'A vacina apresenta ao sistema imunológico uma parte do micróbio ou o micróbio enfraquecido ou inativado, que não causa a doença. O corpo produz anticorpos e cria uma “memória”. Se a pessoa entrar em contato com o micróbio de verdade, a defesa é rápida. Quando muita gente se vacina, o micróbio circula menos e protege também quem não pode se vacinar.',
      'Graças à vacinação em massa, a varíola foi erradicada do mundo e a poliomielite foi eliminada do Brasil.',
      'A vacina ensina o corpo a reconhecer o micróbio antes da doença.',
      'O Brasil tem o Programa Nacional de Imunizações, que oferece vacinas gratuitas pelo SUS.',
      '1. A vacina mostra ao corpo uma parte do micróbio.\n2. O corpo produz anticorpos.\n3. Fica a memória.\n4. No contato real, a defesa é rápida.',
      'É como um treino de simulado: o corpo “estuda” o inimigo antes da prova de verdade.'),
    block('prevencao', 'Prevenção e antibióticos',
      'Medidas de prevenção: lavar as mãos, higienizar alimentos, beber água tratada, ter saneamento básico, cobrir a boca ao tossir, manter vacinas em dia e eliminar água parada (que cria mosquitos como o Aedes aegypti, transmissor da dengue). Antibióticos combatem bactérias, mas NÃO funcionam contra vírus; devem ser usados só com receita médica e pelo tempo indicado.',
      'Tomar antibiótico para gripe não adianta, pois a gripe é causada por vírus.',
      'Higiene, saneamento e vacina previnem; antibiótico só contra bactéria.',
      'Virar garrafas e limpar calhas evita água parada e o mosquito da dengue.',
      '1. Lave as mãos com água e sabão.\n2. Elimine água parada.\n3. Mantenha as vacinas em dia.\n4. Antibiótico só com receita.',
      'Usar antibiótico sem necessidade ajuda a criar bactérias resistentes, como treinar o inimigo contra o remédio.'),
  ],
  questions: [
    mc(1, 'tipos', 'A gripe é causada por:', ['bactéria', 'vírus', 'fungo', 'protozoário'], 1, ['Não tem célula.', 'Influenza.', 'Vírus.'], 'Vírus.'),
    mc(1, 'uteis', 'O que faz a massa do pão crescer?', ['bactérias do intestino', 'leveduras (fungos)', 'vírus', 'protozoários'], 1, ['Fermento biológico.', 'Fungo microscópico.', 'Leveduras.'], 'Leveduras (fungos).'),
    tf(1, 'prevencao', 'Antibióticos funcionam contra vírus.', false, ['Antibiótico combate…', '…bactérias.', 'Não funciona contra vírus.'], 'Falso: antibióticos combatem bactérias.'),
    fill(1, 'vacinas', 'Depois da vacina, o corpo produz ___, que ajudam a combater o micróbio.', ['anticorpos', 'anticorpo'], ['Defesa.', 'Anti…', 'Anticorpos.'], 'Anticorpos.'),
    match(2, 'tipos', 'Ligue a doença ao causador.', [['gripe', 'vírus'], ['tuberculose', 'bactéria'], ['micose', 'fungo'], ['malária', 'protozoário']], ['Influenza.', 'Bacilo.', 'Pele; mosquito transmite.'], 'vírus · bactéria · fungo · protozoário.'),
    mc(2, 'vacinas', 'Como a vacina protege o corpo?', ['Mata todos os micróbios do corpo', 'Ensina o sistema imunológico a reconhecer o micróbio, criando memória', 'Substitui o sangue', 'Funciona como antibiótico'], 1, ['Treino do corpo.', 'Memória imunológica.', 'Anticorpos.'], 'Cria memória imunológica.'),
    mc(2, 'prevencao', 'Qual atitude ajuda a combater a dengue?', ['tomar antibiótico', 'eliminar água parada', 'deixar pneus no quintal', 'abrir as janelas à noite'], 1, ['O mosquito se reproduz…', '…em água parada.', 'Eliminar focos.'], 'Eliminar água parada.'),
    order(2, 'vacinas', 'Ordene como a vacina funciona.', ['vacina apresenta parte do micróbio', 'corpo produz anticorpos', 'corpo guarda memória', 'no contato real, a defesa é rápida'], ['Primeiro a apresentação.', 'Depois os anticorpos.', 'Memória e defesa.'], 'apresentação → anticorpos → memória → defesa.'),
    mc(3, 'vacinas', 'Por que vacinar muitas pessoas protege também quem não pode se vacinar?', ['Porque a vacina passa pelo ar', 'Porque o micróbio circula menos na população', 'Porque os não vacinados ficam imunes sozinhos', 'Não protege'], 1, ['Menos pessoas doentes…', '…menos transmissão.', 'Proteção coletiva.'], 'O micróbio circula menos (proteção coletiva).'),
    open(3, 'uteis', 'Um colega diz que “todo micróbio faz mal”. Dê dois exemplos que mostram que ele está errado.', 'Leveduras são fungos microscópicos que fazem o pão crescer, e bactérias transformam o leite em iogurte. Além disso, decompositores reciclam nutrientes no solo e bactérias do intestino ajudam na digestão.', ['levedura', 'iogurte', 'pao', 'decompositores', 'intestino', 'bacterias'], ['Pense em alimentos.', 'Pense no solo.', 'Pense no intestino.'], 'Pão, iogurte, decomposição, flora intestinal.'),
  ],
  review: ['Vírus (sem célula), bactérias, fungos, protozoários', 'Micróbios úteis: iogurte, pão, decomposição, intestino, remédios', 'Vacina: anticorpos e memória · proteção coletiva', 'Prevenção: higiene, saneamento, sem água parada · antibiótico só contra bactéria'],
  relatedQuestions: ['como funciona a vacina', 'antibiótico funciona contra vírus', 'microrganismos úteis'],
  equivalentQuestions: eqsPt(['microrganismos', 'vacinas', 'vírus e bactérias'], ['como funciona a vacina', 'diferença entre vírus e bactéria', 'antibiótico funciona contra vírus', 'microrganismos úteis', 'o que são anticorpos', 'como prevenir a dengue', 'doenças causadas por bactérias', 'doenças causadas por vírus', 'por que tomar vacina', 'o que é imunidade de rebanho']),
  commonErrors: ['Achar que antibiótico cura gripe.', 'Achar que todo micróbio causa doença.', 'Pensar que vacina causa a doença que previne.'],
  sources: [SRC.bncc('Ciências da Natureza — Anos Iniciais e Finais'), SRC.web('Programa Nacional de Imunizações — Vacinação', 'https://www.gov.br/saude/pt-br/vacinacao', 'Ministério da Saúde', 'instituicao'), SRC.autoral()],
  games: { words: [w('vírus', 'não tem célula'), w('bactéria', 'célula sem núcleo', 2), w('vacina', 'ensina o corpo a se defender'), w('anticorpo', 'proteína de defesa', 2), w('levedura', 'fungo do fermento', 3), w('dengue', 'transmitida pelo Aedes aegypti'), w('antibiótico', 'remédio contra bactérias', 3)] },
})

export const energiaFontes = lesson({
  id: 'cie-energia-fontes', subject: 'ciencias', title: 'Fontes de energia', levels: ['fund1', 'fund2'], grade: '5º ao 8º ano',
  topic: 'Matéria e energia', subtopic: 'Renováveis e não renováveis, transformações de energia e uso consciente',
  aliases: ['fontes de energia', 'energia renovavel', 'energia nao renovavel', 'energia solar', 'energia eolica', 'hidreletrica', 'combustiveis fosseis', 'petroleo', 'biomassa', 'transformacao de energia', 'economia de energia'],
  summary: 'Compare fontes de energia renováveis e não renováveis, veja como a energia se transforma e como economizá-la.',
  intro: 'A luz da sua casa pode ter vindo da água de um rio, do vento ou do Sol!',
  objective: 'Classificar fontes de energia em renováveis e não renováveis, descrever transformações de energia em usinas e aparelhos e propor atitudes de uso consciente.',
  prerequisites: ['cie-preservacao-ambiente'], next: ['cie-circuitos-eletricos'],
  skills: { renovaveis: 'Fontes renováveis', naorenovaveis: 'Fontes não renováveis', transformacao: 'Transformações de energia', consumo: 'Uso consciente' },
  blocks: [
    block('renovaveis', 'Energias renováveis',
      'Fontes renováveis se renovam na natureza e não se esgotam na escala humana: hidráulica (força da água nas hidrelétricas), solar (painéis que captam a luz do Sol), eólica (vento girando turbinas), biomassa (bagaço de cana, lenha de reflorestamento) e geotérmica (calor do interior da Terra). No Brasil, a maior parte da eletricidade vem de fontes renováveis, principalmente hidrelétricas.',
      'Itaipu, no Rio Paraná, é uma das maiores hidrelétricas do mundo. O Nordeste tem grandes parques eólicos.',
      'Renovável: vem do Sol, do vento, da água, que não acabam.',
      'Placas solares no telhado podem gerar parte da eletricidade de uma casa.',
      '1. A fonte se repõe naturalmente (Sol, vento, água, plantas)?\n2. Sim: renovável.',
      'Renovável não quer dizer sem impacto: hidrelétricas alagam grandes áreas e afetam rios e comunidades.'),
    block('naorenovaveis', 'Energias não renováveis',
      'Fontes não renováveis existem em quantidade limitada e levam milhões de anos para se formar: petróleo (gasolina, diesel), carvão mineral e gás natural (combustíveis fósseis), e urânio (usinas nucleares). A queima de combustíveis fósseis libera gás carbônico e poluentes, aumentando o efeito estufa e o aquecimento global.',
      'Usinas termelétricas queimam carvão ou gás para produzir eletricidade.',
      'Não renovável: pode acabar e costuma poluir mais.',
      'O petróleo se formou de restos de seres marinhos soterrados há milhões de anos.',
      '1. A fonte vem de dentro da Terra e leva milhões de anos para se formar?\n2. Sim: não renovável.\n3. Lembre: fósseis liberam gás carbônico ao queimar.',
      'Usar petróleo é como gastar uma poupança antiga: o que se gasta não volta tão cedo.'),
    block('transformacao', 'A energia se transforma',
      'A energia não é criada do nada: ela se transforma de uma forma em outra. Na hidrelétrica, a energia de movimento da água gira turbinas e vira energia elétrica. No painel solar, energia luminosa vira elétrica. Na lâmpada, a elétrica vira luminosa e térmica. No nosso corpo, a energia química dos alimentos vira movimento e calor.',
      'Ventilador: energia elétrica → energia de movimento (e um pouco de calor e som).',
      'A energia muda de forma, não some.',
      'Ao pedalar um dínamo de bicicleta, sua energia de movimento acende a lanterna.',
      '1. Veja a energia que entra no aparelho.\n2. Veja a que sai.\n3. Escreva: entrada → saída.',
      'É como trocar dinheiro de moeda: o valor passa de uma forma para outra.'),
    block('consumo', 'Uso consciente da energia',
      'Economizar energia reduz a conta e o impacto ambiental. Atitudes: apagar luzes ao sair, usar lâmpadas LED, tirar da tomada aparelhos que não estão em uso, abrir janelas para aproveitar a luz natural, tomar banhos mais curtos (o chuveiro elétrico gasta muito) e escolher aparelhos com selo Procel de eficiência.',
      'Trocar uma lâmpada incandescente por uma LED de mesma luminosidade gasta muito menos energia.',
      'Economizar é apagar, desligar e escolher aparelhos eficientes.',
      'O selo Procel A indica os aparelhos mais econômicos.',
      '1. Descubra os maiores gastos (chuveiro, geladeira, ar-condicionado).\n2. Reduza o tempo de uso.\n3. Prefira aparelhos eficientes.',
      'Energia que não é gasta é a mais limpa de todas.'),
  ],
  questions: [
    mc(1, 'renovaveis', 'Qual é uma fonte de energia renovável?', ['petróleo', 'carvão mineral', 'energia solar', 'gás natural'], 2, ['Vem do Sol.', 'Não acaba.', 'Solar.'], 'Energia solar.'),
    mc(1, 'naorenovaveis', 'O petróleo é uma fonte:', ['renovável', 'não renovável', 'solar', 'eólica'], 1, ['Levou milhões de anos.', 'Pode acabar.', 'Não renovável.'], 'Não renovável.'),
    tf(1, 'renovaveis', 'A maior parte da eletricidade do Brasil vem de hidrelétricas.', true, ['Muitos rios.', 'Itaipu.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'renovaveis', 'A energia gerada pelo vento se chama energia ___.', ['eólica', 'eolica'], ['Éolo, deus dos ventos.', 'Eó…', 'Eólica.'], 'Eólica.'),
    match(2, 'transformacao', 'Ligue o aparelho à transformação principal.', [['painel solar', 'luminosa → elétrica'], ['lâmpada', 'elétrica → luminosa'], ['ventilador', 'elétrica → movimento'], ['hidrelétrica', 'movimento da água → elétrica']], ['Capta o Sol.', 'Acende.', 'Gira; turbina.'], 'painel · lâmpada · ventilador · hidrelétrica.'),
    mc(2, 'naorenovaveis', 'Qual problema está mais ligado à queima de combustíveis fósseis?', ['aumento do efeito estufa', 'mais chuva de granizo', 'fim das marés', 'terremotos'], 0, ['Libera gás carbônico.', 'Aquecimento global.', 'Efeito estufa.'], 'Aumento do efeito estufa.'),
    mc(2, 'consumo', 'Qual atitude economiza mais energia elétrica numa casa comum?', ['deixar a TV ligada sem ninguém', 'tomar banhos mais curtos no chuveiro elétrico', 'abrir a geladeira várias vezes', 'usar lâmpadas incandescentes'], 1, ['O chuveiro gasta muito.', 'Menos tempo.', 'Banho curto.'], 'Tomar banhos mais curtos.'),
    order(2, 'transformacao', 'Ordene as transformações de energia numa hidrelétrica até a sua casa.', ['água da represa acumulada', 'água em movimento desce pelos tubos', 'turbina e gerador giram', 'energia elétrica chega pelos fios'], ['Começa na represa.', 'Água desce.', 'Gerador e fios.'], 'represa → movimento → gerador → eletricidade.'),
    mc(3, 'renovaveis', 'Por que se diz que renovável não significa “sem impacto”?', ['Porque painéis poluem o ar', 'Porque hidrelétricas, por exemplo, alagam áreas e afetam rios e comunidades', 'Porque o vento acaba', 'Porque o Sol vai se apagar amanhã'], 1, ['Pense numa represa.', 'Alagamento.', 'Impactos ambientais e sociais.'], 'Hidrelétricas alagam áreas e afetam rios e pessoas.'),
    open(3, 'consumo', 'Cite três atitudes para economizar energia em casa e explique por que isso ajuda o ambiente.', 'Apagar as luzes ao sair do cômodo, trocar lâmpadas comuns por LED e tomar banhos mais curtos. Consumindo menos energia, menos usinas precisam produzir, o que diminui impactos como alagamentos, queima de combustíveis e emissão de gás carbônico.', ['apagar', 'led', 'banho', 'menos', 'impacto', 'usinas'], ['Pense nas luzes.', 'Pense no chuveiro.', 'Menos consumo, menos produção.'], 'Economizar reduz a produção e seus impactos.'),
  ],
  review: ['Renováveis: hidráulica, solar, eólica, biomassa, geotérmica', 'Não renováveis: petróleo, carvão, gás natural, urânio', 'Energia se transforma (movimento → elétrica → luz…)', 'Uso consciente: apagar, LED, banho curto, selo Procel'],
  relatedQuestions: ['fontes de energia renováveis', 'diferença entre renovável e não renovável', 'como economizar energia'],
  equivalentQuestions: eqsPt(['fontes de energia', 'energia renovável'], ['o que é energia renovável', 'o que é energia não renovável', 'exemplos de energia renovável', 'como funciona uma hidrelétrica', 'o que é energia eólica', 'o que é energia solar', 'o que é biomassa', 'combustíveis fósseis', 'como economizar energia em casa', 'transformação de energia exemplos']),
  commonErrors: ['Achar que energia renovável não tem nenhum impacto.', 'Confundir energia elétrica com fonte de energia.', 'Achar que a energia “some” depois de usada (ela se transforma).'],
  sources: [SRC.bncc('Ciências da Natureza — Anos Iniciais e Finais'), SRC.web('Balanço Energético Nacional', 'https://www.epe.gov.br/', 'Empresa de Pesquisa Energética (EPE)', 'instituicao'), SRC.autoral()],
  games: { words: [w('solar', 'energia do Sol'), w('eólica', 'energia do vento', 2), w('petróleo', 'combustível fóssil', 2), w('biomassa', 'energia de restos vegetais', 3), w('turbina', 'gira para gerar eletricidade', 2), w('hidrelétrica', 'usina movida pela água', 3), w('carvão', 'combustível fóssil sólido')] },
})

export const circuitosEletricos = lesson({
  id: 'cie-circuitos-eletricos', subject: 'ciencias', title: 'Eletricidade e circuitos elétricos', levels: ['fund2'], grade: '8º ano',
  topic: 'Matéria e energia', subtopic: 'Circuito simples, condutores e isolantes, consumo e segurança',
  aliases: ['circuito eletrico', 'circuitos', 'eletricidade', 'condutores e isolantes', 'corrente eletrica', 'pilha', 'bateria', 'interruptor', 'consumo de energia', 'kwh', 'choque eletrico', 'seguranca eletrica', 'circuito em serie e paralelo'],
  summary: 'Monte um circuito simples, diferencie condutores de isolantes, calcule consumo e aprenda a evitar choques.',
  intro: 'Para a lâmpada acender, a eletricidade precisa de um caminho fechado.',
  objective: 'Identificar os componentes de um circuito elétrico simples, diferenciar circuito aberto e fechado, condutores e isolantes, circuitos em série e em paralelo, calcular o consumo em kWh e adotar cuidados de segurança.',
  prerequisites: ['cie-energia-fontes'], next: [],
  skills: { circuito: 'Circuito simples', materiais: 'Condutores e isolantes', ligacoes: 'Série e paralelo', consumo: 'Consumo e segurança' },
  blocks: [
    block('circuito', 'O circuito elétrico',
      'Um circuito simples tem: uma fonte (pilha, bateria ou tomada), fios condutores, um receptor (lâmpada, motor) e, muitas vezes, um interruptor. A corrente elétrica só passa se o caminho estiver fechado. Circuito aberto: interrompido, a lâmpada apaga. Circuito fechado: completo, a lâmpada acende.',
      'O interruptor da parede abre e fecha o circuito da lâmpada do quarto.',
      'Caminho fechado: acende. Aberto: apaga.',
      'Uma lanterna tem pilhas (fonte), lâmpada ou LED (receptor), contatos metálicos (condutores) e botão (interruptor).',
      '1. Identifique a fonte.\n2. Siga o fio até o receptor e de volta à fonte.\n3. Há algum ponto interrompido? Circuito aberto.',
      'O circuito é como uma pista de corrida em volta: se houver um buraco, os carros não completam a volta.'),
    block('materiais', 'Condutores e isolantes',
      'Condutores deixam a corrente elétrica passar com facilidade: metais como cobre, alumínio e ferro, e também a água com sais (incluindo o corpo humano). Isolantes dificultam a passagem: borracha, plástico, vidro, madeira seca. Por isso os fios são de cobre por dentro e cobertos de plástico por fora.',
      'O cabo do alicate de eletricista é de borracha grossa para isolar a mão.',
      'Condutor deixa passar; isolante bloqueia.',
      'Mexer em aparelho elétrico com a mão molhada é perigoso: a água facilita a passagem da corrente pelo corpo.',
      '1. É metal? Provavelmente condutor.\n2. É borracha, plástico ou vidro? Isolante.\n3. Água com sais conduz: cuidado com as mãos molhadas.',
      'O fio elétrico é como uma mangueira: o cobre é o “cano” por onde passa a corrente, e o plástico é a capa que protege.'),
    block('ligacoes', 'Circuitos em série e em paralelo',
      'Em série, os componentes ficam um depois do outro num único caminho: se uma lâmpada queima, todas apagam (como certos pisca-piscas antigos). Em paralelo, cada componente tem seu próprio caminho: se uma lâmpada queima, as outras continuam acesas. As instalações das casas são em paralelo.',
      'Na sua casa, desligar a luz da cozinha não apaga a da sala: as ligações são em paralelo.',
      'Série: um caminho só. Paralelo: vários caminhos.',
      'Pisca-piscas modernos usam ligações que evitam que tudo apague por uma lâmpada só.',
      '1. Siga o caminho da corrente.\n2. Só um caminho passando por todos? Série.\n3. Caminhos separados para cada um? Paralelo.',
      'Série é como uma fila única: se alguém trava, todos param. Paralelo é como várias filas: uma travada não afeta as outras.'),
    block('consumo', 'Consumo e segurança',
      'A potência de um aparelho é medida em watts (W). O consumo de energia é calculado por: energia (kWh) = potência (kW) × tempo (h). A conta de luz cobra pelos kWh consumidos. Segurança: nunca mexer em tomadas com objetos metálicos ou com as mãos molhadas, não sobrecarregar tomadas com benjamins, não soltar pipas perto da rede elétrica e desligar o disjuntor antes de consertos.',
      'Um chuveiro de 5.000 W (5 kW) ligado por 0,5 h consome 5 × 0,5 = 2,5 kWh.',
      'Consumo = potência × tempo. E cuidado com choques!',
      'Pipa com linha presa em fio de alta tensão pode causar choque grave: solte pipas em campos abertos.',
      '1. Converta a potência para kW (divida W por 1.000).\n2. Multiplique pelo tempo em horas.\n3. O resultado é o consumo em kWh.',
      'A potência é a “velocidade” com que o aparelho gasta energia; o tempo diz por quanto tempo ele gastou.'),
  ],
  questions: [
    mc(1, 'circuito', 'Para a lâmpada acender, o circuito precisa estar:', ['aberto', 'fechado', 'molhado', 'desligado da pilha'], 1, ['Caminho completo.', 'Sem interrupção.', 'Fechado.'], 'Fechado.'),
    mc(1, 'materiais', 'Qual material é isolante?', ['cobre', 'alumínio', 'borracha', 'ferro'], 2, ['Não é metal.', 'Cabo do alicate.', 'Borracha.'], 'Borracha.'),
    tf(1, 'ligacoes', 'As instalações elétricas das casas são, em geral, em paralelo.', true, ['Apagar a cozinha apaga a sala?', 'Não.', 'Paralelo.'], 'Verdadeiro.'),
    fill(2, 'consumo', 'Um aparelho de 2 kW ligado por 3 horas consome ___ kWh.', ['6'], ['Potência × tempo.', '2 × 3.', '6.'], '2 kW × 3 h = 6 kWh.'),
    match(2, 'circuito', 'Ligue o componente à função.', [['pilha', 'fonte de energia'], ['fio de cobre', 'conduz a corrente'], ['lâmpada', 'receptor'], ['interruptor', 'abre e fecha o circuito']], ['Fornece energia.', 'Caminho.', 'Usa a energia; controla.'], 'fonte · condutor · receptor · interruptor.'),
    mc(2, 'ligacoes', 'Em um circuito em série com 3 lâmpadas, uma queima. O que acontece?', ['as outras continuam acesas', 'todas apagam', 'as outras brilham mais', 'nada muda'], 1, ['Um único caminho.', 'Caminho interrompido.', 'Todas apagam.'], 'Todas apagam.'),
    mc(2, 'materiais', 'Por que não se deve mexer em aparelhos elétricos com as mãos molhadas?', ['A água isola a corrente', 'A água com sais facilita a passagem da corrente pelo corpo', 'O aparelho enferruja na hora', 'A água apaga a luz'], 1, ['Água com sais conduz.', 'Corpo vira caminho.', 'Risco de choque.'], 'A água facilita a corrente pelo corpo: choque.'),
    order(2, 'consumo', 'Ordene os passos para calcular o consumo de um aparelho.', ['anotar a potência em watts', 'converter para quilowatts', 'multiplicar pelo tempo em horas', 'obter o consumo em kWh'], ['Comece pela potência.', 'Divida por 1.000.', 'Multiplique pelo tempo.'], 'potência → kW → × tempo → kWh.'),
    mc(3, 'consumo', 'Um chuveiro de 5.500 W fica ligado 20 minutos por dia. Quanto ele consome por dia, aproximadamente?', ['1,8 kWh', '110 kWh', '5,5 kWh', '0,5 kWh'], 0, ['5.500 W = 5,5 kW.', '20 min = 1/3 h.', '5,5 ÷ 3 ≈ 1,8.'], '5,5 kW × 1/3 h ≈ 1,8 kWh.'),
    open(3, 'ligacoes', 'Por que as lâmpadas de uma casa são ligadas em paralelo, e não em série?', 'Porque em paralelo cada lâmpada tem seu próprio caminho: podemos ligar e desligar cada uma separadamente e, se uma queimar, as outras continuam funcionando. Em série, uma lâmpada queimada ou desligada apagaria todas.', ['paralelo', 'caminho', 'separadamente', 'queimar', 'serie', 'apagaria'], ['O que acontece em série se uma queima?', 'E em paralelo?', 'Pense em ligar cada luz sozinha.'], 'Paralelo: independência entre as lâmpadas.'),
  ],
  review: ['Circuito: fonte, fios, receptor, interruptor · aberto × fechado', 'Condutores (metais, água com sais) × isolantes (borracha, plástico)', 'Série (um caminho) × paralelo (vários caminhos)', 'Consumo (kWh) = potência (kW) × tempo (h) · segurança elétrica'],
  relatedQuestions: ['o que é circuito elétrico', 'condutores e isolantes', 'como calcular o consumo de energia'],
  equivalentQuestions: eqsPt(['circuito elétrico', 'condutores e isolantes', 'consumo de energia'], ['o que é circuito aberto', 'o que é circuito fechado', 'diferença entre circuito em série e paralelo', 'como calcular kwh', 'o que é potência elétrica', 'materiais condutores', 'materiais isolantes', 'como evitar choque elétrico', 'por que o fio tem capa de plástico', 'como funciona o interruptor']),
  commonErrors: ['Achar que a corrente passa com o circuito aberto.', 'Esquecer de converter watts para quilowatts.', 'Achar que a água pura da torneira é isolante (ela contém sais e conduz).'],
  formulas: [{ name: 'Consumo de energia elétrica', expression: 'E = P × Δt', variables: [{ symbol: 'E', meaning: 'energia consumida (kWh)' }, { symbol: 'P', meaning: 'potência (kW)' }, { symbol: 'Δt', meaning: 'tempo de uso (h)' }] }],
  sources: [SRC.bncc('Ciências da Natureza — Anos Finais'), SRC.web('Dicas de segurança com a energia elétrica', 'https://www.gov.br/aneel/pt-br', 'Agência Nacional de Energia Elétrica (ANEEL)', 'instituicao'), SRC.autoral()],
  games: { words: [w('circuito', 'caminho da corrente'), w('pilha', 'fonte de energia'), w('isolante', 'bloqueia a corrente', 2), w('condutor', 'deixa a corrente passar', 2), w('interruptor', 'abre e fecha o circuito', 3), w('paralelo', 'ligação das casas', 3), w('cobre', 'metal dos fios')] },
})
