import type { Lesson } from '../../types'

const BNCC = { title: 'Base Nacional Comum Curricular (BNCC) — Ciências da Natureza', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' } as const
const AUTORAL = { title: 'Conteúdo autoral LUMI', kind: 'autoral' } as const

export const fotossintese: Lesson = {
  id: 'cie-fotossintese',
  subject: 'ciencias',
  title: 'Fotossíntese',
  levels: ['fund1', 'fund2', 'medio'],
  grade: '6º e 7º ano',
  aliases: ['fotossintese', 'clorofila', 'cloroplasto', 'como as plantas se alimentam', 'plantas produzem alimento'],
  summary: 'Descubra como as plantas fabricam o próprio alimento usando luz, água e gás carbônico.',
  intro: 'As plantas não comem como nós. Elas fabricam o próprio alimento — e ainda liberam o oxigênio que respiramos.',
  skills: { conceito: 'O que é fotossíntese', ingredientes: 'O que a planta usa', produtos: 'O que a planta produz', importancia: 'Importância para a vida' },
  blocks: [
    {
      id: 'b1', skill: 'conceito', title: 'O que é fotossíntese',
      text: 'Fotossíntese é o processo em que plantas, algas e algumas bactérias usam a energia da luz para produzir o próprio alimento. "Foto" quer dizer luz e "síntese" quer dizer produção.',
      example: 'Uma planta num vaso perto da janela cresce usando a luz do sol. Sem luz, ela fica fraca e amarelada.',
      variants: {
        simples: 'A planta é como uma cozinha movida a luz do sol: ela pega luz e faz a própria comida.',
        exemplo: 'Por isso colocamos as plantas perto da janela. Se deixarmos um vaso num armário escuro por semanas, a planta enfraquece porque não consegue fazer a fotossíntese.',
        outra: 'Nós precisamos comer para ter energia. A planta não: ela transforma a energia da luz em energia guardada num açúcar, e usa esse açúcar para viver e crescer.',
        detalhado: 'A fotossíntese acontece em duas etapas: na fase clara, a energia luminosa é captada pela clorofila e a água é quebrada, liberando oxigênio; na fase escura (que não precisa de luz diretamente), o gás carbônico é fixado e transformado em glicose.',
      },
    },
    {
      id: 'b2', skill: 'ingredientes', title: 'Os ingredientes',
      text: 'A planta precisa de água (absorvida pelas raízes), gás carbônico (que entra pelas folhas, por pequenas aberturas chamadas estômatos) e luz. Quem capta a luz é a clorofila, um pigmento verde que fica dentro dos cloroplastos.',
      example: 'É por causa da clorofila que a maioria das folhas é verde.',
      variants: {
        simples: 'A receita da planta: água + gás carbônico do ar + luz do sol. A parte verde da folha (clorofila) é quem "pega" a luz.',
        exemplo: 'Quando você rega uma planta, a água sobe da raiz até a folha. Ao mesmo tempo, a folha "puxa" gás carbônico do ar. Com a luz do sol, está tudo pronto.',
        outra: 'Pense numa fábrica: a água chega por um cano (raiz), o gás carbônico entra pelas janelas (estômatos), e a clorofila é o painel solar que liga as máquinas.',
        detalhado: 'Os cloroplastos são organelas presentes principalmente nas células das folhas. A clorofila absorve bem luz vermelha e azul e reflete o verde. A água é transportada pelo xilema, e a abertura dos estômatos controla a entrada de CO₂ e a perda de água.',
      },
    },
    {
      id: 'b3', skill: 'produtos', title: 'O que a planta produz',
      text: 'O resultado da fotossíntese é a glicose (um açúcar que é o alimento da planta) e o gás oxigênio, que é liberado no ar. Resumindo: gás carbônico + água + luz → glicose + oxigênio.',
      example: 'Parte da glicose vira amido e fica guardada, como na batata e na mandioca.',
      variants: {
        simples: 'A planta faz duas coisas: açúcar para ela comer e oxigênio, que ela solta no ar para a gente respirar.',
        exemplo: 'A batata que você come é a reserva de alimento que a planta guardou depois de fazer fotossíntese.',
        outra: 'Entra: gás carbônico e água. Sai: açúcar (glicose) e oxigênio. A luz é a energia que faz essa troca acontecer.',
        detalhado: 'A equação geral é 6 CO₂ + 6 H₂O → C₆H₁₂O₆ + 6 O₂, na presença de luz e clorofila. O oxigênio liberado vem da quebra das moléculas de água. Lembre que as plantas também respiram: usam oxigênio para quebrar a glicose e liberar energia, dia e noite.',
      },
    },
    {
      id: 'b4', skill: 'importancia', title: 'Por que isso importa para todos',
      text: 'A fotossíntese produz grande parte do oxigênio da atmosfera e é a base das cadeias alimentares: as plantas são produtoras e todos os outros seres dependem delas, direta ou indiretamente.',
      example: 'O capim faz fotossíntese, o boi come o capim e nós comemos alimentos que vêm dessa cadeia.',
      variants: {
        simples: 'Sem as plantas, faltaria oxigênio para respirar e comida para os animais.',
        exemplo: 'Uma lagarta come a folha, um passarinho come a lagarta. Tudo começou com a energia da luz que a folha guardou.',
        outra: 'As plantas são o "primeiro elo" da corrente: elas transformam luz em alimento, e o resto da natureza vai passando essa energia adiante.',
        detalhado: 'Por serem autótrofos, os seres fotossintetizantes são produtores. As algas marinhas (fitoplâncton) respondem por boa parte do oxigênio produzido no planeta. A fotossíntese também retira CO₂ da atmosfera, o que se relaciona com o controle do efeito estufa.',
      },
    },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'conceito', prompt: 'A fotossíntese é o processo em que as plantas:', options: ['Absorvem comida do solo', 'Produzem o próprio alimento usando luz', 'Dormem durante a noite', 'Liberam gás carbônico para crescer'], answer: 1, hints: ['"Foto" significa luz.', '"Síntese" significa produção.', 'Produção com luz.'], explanation: 'Na fotossíntese, a planta produz o próprio alimento (glicose) usando a energia da luz.' },
    { id: 'q2', type: 'tf', difficulty: 1, skill: 'produtos', prompt: 'A fotossíntese libera gás oxigênio.', answer: true, hints: ['Pense no que respiramos.', 'A planta produz açúcar e mais uma coisa.', 'Essa outra coisa vai para o ar.'], explanation: 'Verdadeiro. O oxigênio é um dos produtos da fotossíntese.' },
    { id: 'q3', type: 'fill', difficulty: 1, skill: 'ingredientes', prompt: 'O pigmento verde que capta a luz se chama ________.', answers: ['clorofila'], hints: ['É ele que deixa a folha verde.', 'Começa com "cloro".', 'Cloro + fila.'], explanation: 'A clorofila é o pigmento verde que absorve a luz.' },
    { id: 'q4', type: 'mc', difficulty: 2, skill: 'ingredientes', prompt: 'Qual destes NÃO é usado pela planta para fazer fotossíntese?', options: ['Luz', 'Água', 'Gás carbônico', 'Gás oxigênio'], answer: 3, hints: ['Separe o que entra do que sai.', 'Entra: luz, água e gás carbônico.', 'Um dos itens é um produto, não um ingrediente.'], explanation: 'O oxigênio é produzido (sai), não é usado para fazer fotossíntese.' },
    { id: 'q5', type: 'mc', difficulty: 2, skill: 'ingredientes', prompt: 'Em que parte da planta a fotossíntese acontece principalmente?', options: ['Raiz', 'Folhas', 'Flores', 'Sementes'], answer: 1, hints: ['Onde fica a maior parte da clorofila?', 'É a parte que mais recebe luz.', 'É verde e larga.'], explanation: 'Nas folhas, onde há muitos cloroplastos com clorofila.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'produtos', prompt: 'Qual açúcar a planta produz na fotossíntese?', options: ['Sacarose', 'Glicose', 'Lactose', 'Frutose'], answer: 1, hints: ['É o mesmo açúcar que nosso corpo usa como energia.', 'Começa com "gli".', 'Gli + cose.'], explanation: 'A glicose é o açúcar produzido; parte dela pode ser guardada como amido.' },
    { id: 'q7', type: 'match', difficulty: 2, skill: 'ingredientes', prompt: 'Ligue cada ingrediente ao seu papel.', pairs: [['Água', 'Absorvida pelas raízes'], ['Gás carbônico', 'Entra pelas folhas'], ['Luz', 'Fornece a energia'], ['Clorofila', 'Capta a luz']], hints: ['Pense por onde cada um chega.', 'A raiz fica no solo, que é úmido.', 'A clorofila é o "painel solar".'], explanation: 'Água pela raiz, gás carbônico pelas folhas (estômatos), a luz dá energia e a clorofila a capta.' },
    { id: 'q8', type: 'tf', difficulty: 2, skill: 'conceito', prompt: 'As plantas fazem fotossíntese no escuro total.', answer: false, hints: ['Qual é a fonte de energia da fotossíntese?', 'Sem ela, o processo para.', 'No escuro não há luz.'], explanation: 'Falso. Sem luz, a planta não capta energia e a fotossíntese não acontece.' },
    { id: 'q9', type: 'fill', difficulty: 3, skill: 'ingredientes', prompt: 'A organela onde ocorre a fotossíntese é o ________.', answers: ['cloroplasto', 'cloroplastos'], hints: ['É onde a clorofila fica guardada.', 'Começa igual a clorofila.', 'Cloro + plasto.'], explanation: 'O cloroplasto é a organela que contém a clorofila.' },
    { id: 'q10', type: 'mc', difficulty: 3, skill: 'importancia', prompt: 'Por que a fotossíntese é importante para os animais?', options: ['Porque aquece o planeta', 'Porque produz oxigênio e é a base das cadeias alimentares', 'Porque produz água', 'Porque elimina todos os gases'], answer: 1, hints: ['Pense no que os animais respiram.', 'E no que os animais comem.', 'As plantas são produtoras.'], explanation: 'Ela libera oxigênio e é o início das cadeias alimentares.' },
    { id: 'q11', type: 'tf', difficulty: 3, skill: 'produtos', prompt: 'As plantas também respiram, consumindo oxigênio.', answer: true, hints: ['Toda célula viva precisa liberar energia.', 'Isso acontece dia e noite.', 'É a respiração celular.'], explanation: 'Verdadeiro. As plantas respiram o tempo todo; de dia, a fotossíntese costuma produzir mais oxigênio do que elas consomem.' },
    { id: 'q12', type: 'open', difficulty: 3, skill: 'importancia', prompt: 'O que aconteceria com os animais se todas as plantas parassem de fazer fotossíntese?', modelAnswer: 'Faltaria alimento, porque as plantas são a base das cadeias alimentares, e o oxigênio do ar diminuiria com o tempo. Os animais não conseguiriam sobreviver.', keywords: ['oxigenio', 'alimento', 'comida', 'cadeia', 'morrer', 'sobreviver'], hints: ['Pense em duas coisas que vêm das plantas.', 'Uma delas respiramos.', 'A outra está no começo da cadeia alimentar.'], explanation: 'Os animais perderiam a fonte de alimento e, aos poucos, o oxigênio.' },
  ],
  review: ['Fotossíntese = produzir alimento com luz', 'Usa: água, gás carbônico e luz (clorofila capta)', 'Produz: glicose e oxigênio', 'Base das cadeias alimentares'],
  sources: [BNCC, AUTORAL],
}

export const sistemaSolar: Lesson = {
  id: 'cie-sistema-solar',
  subject: 'ciencias',
  title: 'Sistema Solar',
  levels: ['fund1', 'fund2'],
  grade: '3º ao 6º ano',
  aliases: ['sistema solar', 'planetas', 'sol', 'rotacao', 'translacao', 'movimentos da terra', 'astronomia'],
  summary: 'Conheça o Sol, os oito planetas e os movimentos da Terra.',
  intro: 'Vamos fazer uma viagem pelo espaço, começando pela nossa estrela: o Sol.',
  skills: { sol: 'O Sol', planetas: 'Os planetas', tipos: 'Planetas rochosos e gasosos', movimentos: 'Movimentos da Terra' },
  blocks: [
    {
      id: 'b1', skill: 'sol', title: 'O Sol, nossa estrela',
      text: 'O Sol é uma estrela: uma enorme bola de gases muito quentes que produz luz e calor. Ele fica no centro do Sistema Solar, e tudo gira ao redor dele.',
      example: 'As estrelas que vemos à noite também são sóis, só que estão muito mais longe.',
      variants: {
        simples: 'O Sol é uma estrela. Ele dá luz e calor para a Terra.',
        exemplo: 'Sem o Sol não haveria dia, as plantas não cresceriam e a Terra seria gelada.',
        outra: 'Imagine uma fogueira gigante no meio de uma roda. Os planetas ficam dando voltas ao redor dela. Essa fogueira é o Sol.',
        detalhado: 'O Sol concentra mais de 99% da massa do Sistema Solar. Sua gravidade mantém os planetas em órbita. Plutão, que já foi chamado de planeta, hoje é classificado como planeta anão.',
      },
    },
    {
      id: 'b2', skill: 'planetas', title: 'Os oito planetas',
      text: 'Em ordem, a partir do Sol: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno. A Terra é o terceiro planeta, e Júpiter é o maior de todos.',
      example: 'Uma frase para lembrar: "Minha Vó Tem Muitas Joias, Só Usa No Natal".',
      variants: {
        simples: 'São 8 planetas. O mais perto do Sol é Mercúrio. A Terra é o 3º. O maior é Júpiter.',
        exemplo: 'Se o Sol fosse do tamanho de uma porta, a Terra seria do tamanho de uma moeda pequena, e Júpiter de uma bola de tênis.',
        outra: 'Use as iniciais: M-V-T-M-J-S-U-N. Cada palavra da frase "Minha Vó Tem Muitas Joias, Só Usa No Natal" começa com a letra de um planeta.',
        detalhado: 'Os planetas giram em órbitas quase circulares. Quanto mais longe do Sol, mais tempo leva para dar uma volta: Mercúrio leva cerca de 88 dias, a Terra cerca de 365, e Netuno cerca de 165 anos terrestres.',
      },
    },
    {
      id: 'b3', skill: 'tipos', title: 'Rochosos e gasosos',
      text: 'Os quatro primeiros (Mercúrio, Vênus, Terra e Marte) são rochosos: têm superfície sólida. Os quatro últimos (Júpiter, Saturno, Urano e Netuno) são gigantes gasosos, muito maiores e formados principalmente por gases.',
      example: 'Um robô pode pousar em Marte. Em Júpiter, não haveria chão para pousar.',
      variants: {
        simples: 'Os 4 mais perto do Sol são de pedra. Os 4 mais longe são enormes e feitos de gás.',
        exemplo: 'A Terra tem montanhas e chão. Saturno é uma bola gigante de gás com anéis ao redor.',
        outra: 'Pense em dois times: o time pequeno e duro (rochosos) perto do Sol, e o time gigante e "fofo" (gasosos) lá longe.',
        detalhado: 'Os gasosos são formados principalmente por hidrogênio e hélio; Urano e Netuno também são chamados de gigantes de gelo. Todos os gasosos possuem anéis, embora os de Saturno sejam os mais visíveis.',
      },
    },
    {
      id: 'b4', skill: 'movimentos', title: 'Os movimentos da Terra',
      text: 'A Terra gira em torno de si mesma (rotação), e isso leva cerca de 24 horas, formando o dia e a noite. Ela também dá uma volta ao redor do Sol (translação), que leva cerca de 365 dias: um ano.',
      example: 'Quando é dia no Brasil, é noite no Japão, porque cada lado da Terra está virado para o Sol em momentos diferentes.',
      variants: {
        simples: 'Girando em volta de si mesma: dia e noite (24 horas). Girando em volta do Sol: um ano (365 dias).',
        exemplo: 'Gire uma bola perto de uma lanterna: o lado iluminado é o dia, o lado escuro é a noite. Agora ande com a bola em volta da lanterna: isso é a translação.',
        outra: 'Rotação = Roda em si mesma. Translação = Trajeto ao redor do Sol.',
        detalhado: 'A translação leva cerca de 365 dias e 6 horas — por isso, a cada 4 anos, somamos um dia (ano bissexto). A inclinação do eixo da Terra, combinada com a translação, causa as estações do ano.',
      },
    },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'sol', prompt: 'O Sol é:', options: ['Um planeta', 'Uma estrela', 'Um satélite', 'Um cometa'], answer: 1, hints: ['Ele produz luz própria.', 'Os planetas não produzem luz.', 'As que brilham à noite são do mesmo tipo.'], explanation: 'O Sol é uma estrela: produz luz e calor.' },
    { id: 'q2', type: 'fill', difficulty: 1, skill: 'planetas', prompt: 'Quantos planetas existem no Sistema Solar? (número)', answers: ['8', 'oito'], hints: ['Lembre da frase da vó.', 'Conte as palavras de "Minha Vó Tem Muitas Joias, Só Usa No Natal".', 'São menos que 10.'], explanation: 'São 8 planetas.' },
    { id: 'q3', type: 'mc', difficulty: 1, skill: 'planetas', prompt: 'Qual planeta fica mais perto do Sol?', options: ['Terra', 'Vênus', 'Mercúrio', 'Marte'], answer: 2, hints: ['É o primeiro da lista.', 'A frase começa com "Minha".', 'Começa com M e não é Marte.'], explanation: 'Mercúrio é o primeiro planeta a partir do Sol.' },
    { id: 'q4', type: 'tf', difficulty: 1, skill: 'movimentos', prompt: 'O dia e a noite acontecem por causa da rotação da Terra.', answer: true, hints: ['Qual movimento leva 24 horas?', 'É a Terra girando em si mesma.', 'Rotação = roda em si mesma.'], explanation: 'Verdadeiro. A rotação faz cada lado da Terra ficar virado para o Sol em momentos diferentes.' },
    { id: 'q5', type: 'mc', difficulty: 2, skill: 'planetas', prompt: 'Qual é o maior planeta do Sistema Solar?', options: ['Saturno', 'Júpiter', 'Netuno', 'Terra'], answer: 1, hints: ['É um gigante gasoso.', 'É o quinto planeta.', 'Começa com J.'], explanation: 'Júpiter é o maior planeta.' },
    { id: 'q6', type: 'match', difficulty: 2, skill: 'movimentos', prompt: 'Ligue cada item à sua descrição.', pairs: [['Rotação', 'Forma o dia e a noite'], ['Translação', 'Volta ao redor do Sol'], ['Lua', 'Satélite natural da Terra'], ['Sol', 'Estrela no centro']], hints: ['Rotação: roda em si mesma.', 'Translação: trajeto ao redor do Sol.', 'A Lua gira ao redor da Terra.'], explanation: 'Rotação → dia e noite; Translação → ano; Lua → satélite; Sol → estrela.' },
    { id: 'q7', type: 'tf', difficulty: 2, skill: 'tipos', prompt: 'Júpiter é um planeta rochoso.', answer: false, hints: ['Onde Júpiter fica na lista?', 'Os 4 últimos são de um tipo.', 'Os últimos são gasosos.'], explanation: 'Falso. Júpiter é um gigante gasoso.' },
    { id: 'q8', type: 'mc', difficulty: 2, skill: 'tipos', prompt: 'Quais são os planetas rochosos?', options: ['Júpiter, Saturno, Urano e Netuno', 'Mercúrio, Vênus, Terra e Marte', 'Terra, Marte, Júpiter e Saturno', 'Só a Terra'], answer: 1, hints: ['São os mais próximos do Sol.', 'São os 4 primeiros.', 'A Terra está entre eles.'], explanation: 'Os rochosos são os quatro primeiros: Mercúrio, Vênus, Terra e Marte.' },
    { id: 'q9', type: 'fill', difficulty: 2, skill: 'movimentos', prompt: 'A translação da Terra dura cerca de ____ dias.', answers: ['365', '365 dias'], hints: ['É o tempo de um ano.', 'Um ano tem mais de 300 dias.', '3-6-5.'], explanation: 'Cerca de 365 dias — um ano.' },
    { id: 'q10', type: 'mc', difficulty: 3, skill: 'planetas', prompt: 'Qual é a posição da Terra a partir do Sol?', options: ['Primeira', 'Segunda', 'Terceira', 'Quarta'], answer: 2, hints: ['Mercúrio é o 1º.', 'Vênus é o 2º.', 'Quem vem depois de Vênus?'], explanation: 'A Terra é o terceiro planeta.' },
    { id: 'q11', type: 'tf', difficulty: 3, skill: 'sol', prompt: 'Plutão é considerado um planeta anão.', answer: true, hints: ['Plutão já foi chamado de planeta.', 'Em 2006 a classificação mudou.', 'Hoje é de uma categoria menor.'], explanation: 'Verdadeiro. Desde 2006, Plutão é classificado como planeta anão.' },
    { id: 'q12', type: 'mc', difficulty: 3, skill: 'movimentos', prompt: 'Quanto tempo dura, aproximadamente, a rotação da Terra?', options: ['12 horas', '24 horas', '7 dias', '365 dias'], answer: 1, hints: ['A rotação forma o dia e a noite.', 'Um dia completo inclui a noite.', 'Quantas horas tem um dia?'], explanation: 'Cerca de 24 horas: um dia completo.' },
  ],
  review: ['O Sol é uma estrela', '8 planetas: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano, Netuno', 'Rochosos (4 primeiros) × gasosos (4 últimos)', 'Rotação = dia/noite (24 h) · Translação = ano (365 dias)'],
  sources: [BNCC, AUTORAL],
}

export const celula: Lesson = {
  id: 'bio-celula',
  subject: 'biologia',
  title: 'Célula',
  levels: ['fund2', 'medio'],
  grade: '6º ano e 1ª série',
  aliases: ['celula', 'celulas', 'organelas', 'mitocondria', 'citologia', 'celula animal', 'celula vegetal', 'procarionte', 'eucarionte'],
  summary: 'A célula é a unidade básica da vida. Conheça suas partes e organelas.',
  intro: 'Todo ser vivo é formado por células — de uma bactéria a uma baleia. Vamos olhar lá dentro.',
  skills: { conceito: 'Célula como unidade da vida', tipos: 'Procariontes e eucariontes', estruturas: 'Membrana, citoplasma e núcleo', organelas: 'Organelas e funções', animal_vegetal: 'Célula animal × vegetal' },
  blocks: [
    {
      id: 'b1', skill: 'conceito', title: 'A unidade da vida',
      text: 'A célula é a menor unidade viva. Alguns seres têm uma só célula (unicelulares, como bactérias); outros têm trilhões (pluricelulares, como nós).',
      example: 'O corpo humano tem cerca de 30 trilhões de células.',
      variants: {
        simples: 'Assim como uma casa é feita de tijolos, os seres vivos são feitos de células.',
        exemplo: 'Uma bactéria é uma célula sozinha fazendo tudo. Você é um "time" enorme de células trabalhando juntas.',
        outra: 'Se você dividir um ser vivo em partes cada vez menores, a menor parte que ainda está viva é a célula.',
        detalhado: 'A teoria celular afirma que todos os seres vivos são formados por células, que a célula é a unidade estrutural e funcional da vida, e que toda célula surge de outra célula preexistente. Vírus não têm células.',
      },
    },
    {
      id: 'b2', skill: 'estruturas', title: 'As três partes básicas',
      text: 'Toda célula tem membrana plasmática (que envolve e controla o que entra e sai), citoplasma (o interior, onde ficam as organelas) e material genético (DNA). Nas células eucariontes, o DNA fica dentro do núcleo.',
      example: 'A membrana funciona como o portão de um condomínio: decide quem entra e quem sai.',
      variants: {
        simples: 'Membrana = a "pele" da célula. Citoplasma = o recheio. Núcleo = o "chefe", que guarda as instruções.',
        exemplo: 'Como um ovo: a casca lembra a membrana, a clara lembra o citoplasma e a gema lembra o núcleo. (É só uma comparação!)',
        outra: 'Pense numa fábrica: os muros (membrana), o galpão com as máquinas (citoplasma) e a sala com os projetos (núcleo com o DNA).',
        detalhado: 'A membrana plasmática é formada por uma bicamada de fosfolipídios com proteínas e tem permeabilidade seletiva. O núcleo é delimitado pela carioteca, e o citoplasma contém o citosol e as organelas.',
      },
    },
    {
      id: 'b3', skill: 'tipos', title: 'Procariontes e eucariontes',
      text: 'Células procariontes não têm núcleo organizado: o DNA fica solto no citoplasma. É o caso das bactérias. Células eucariontes têm núcleo delimitado por membrana e várias organelas. É o caso de animais, plantas e fungos.',
      example: '"Pro" lembra "primeiro": as procariontes são células mais simples.',
      variants: {
        simples: 'Procarionte: sem núcleo (bactérias). Eucarionte: com núcleo (animais, plantas, fungos).',
        exemplo: 'A bactéria que estraga o leite é procarionte. As células da sua pele são eucariontes.',
        outra: 'É como uma casa sem quartos (tudo junto num cômodo só) e uma casa com quartos separados. A eucarionte é a com quartos.',
        detalhado: 'Procariontes têm ribossomos, mas não possuem organelas membranosas como mitocôndrias. O DNA fica numa região chamada nucleoide. Eucariontes surgiram depois e têm compartimentos internos especializados.',
      },
    },
    {
      id: 'b4', skill: 'organelas', title: 'Organelas e suas funções',
      text: 'Mitocôndria: libera energia (respiração celular). Ribossomo: produz proteínas. Cloroplasto: faz fotossíntese (só em plantas e algas). Núcleo: guarda o DNA e controla a célula.',
      example: 'Células dos músculos têm muitas mitocôndrias porque precisam de muita energia.',
      variants: {
        simples: 'Mitocôndria = usina de energia. Ribossomo = fábrica de proteínas. Cloroplasto = painel solar da planta.',
        exemplo: 'Quando você corre, as mitocôndrias dos músculos trabalham muito para liberar energia a partir da glicose.',
        outra: 'Cada organela é como um setor de uma empresa: um produz (ribossomo), outro gera energia (mitocôndria), outro guarda os documentos (núcleo).',
        detalhado: 'Na mitocôndria ocorre a respiração celular aeróbica, que produz ATP. Ribossomos podem estar livres ou no retículo endoplasmático rugoso. O complexo golgiense modifica e empacota substâncias, e os lisossomos fazem a digestão intracelular.',
      },
    },
    {
      id: 'b5', skill: 'animal_vegetal', title: 'Célula animal × vegetal',
      text: 'A célula vegetal tem parede celular (de celulose), cloroplastos e um grande vacúolo. A célula animal não tem essas estruturas. As duas têm membrana, citoplasma, núcleo e mitocôndrias.',
      example: 'A parede celular é o que deixa o talo de uma planta mais firme.',
      variants: {
        simples: 'Planta tem três coisas a mais: parede, cloroplasto e um vacúolo grande. O resto é parecido.',
        exemplo: 'Uma folha de alface é crocante por causa da parede celular e da água no vacúolo.',
        outra: 'A célula vegetal é como a animal usando uma "armadura" (parede celular) e "painéis solares" (cloroplastos).',
        detalhado: 'A parede celular fica por fora da membrana plasmática e dá sustentação. Células animais têm centríolos e lisossomos mais evidentes. As células vegetais também têm mitocôndrias, pois precisam liberar energia pela respiração.',
      },
    },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'conceito', prompt: 'Qual é a unidade básica da vida?', options: ['O átomo', 'A célula', 'O órgão', 'O tecido'], answer: 1, hints: ['É a menor parte que ainda está viva.', 'Os seres vivos são feitos delas.', 'Como tijolos de uma casa.'], explanation: 'A célula é a menor unidade viva.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'organelas', prompt: 'Qual organela libera energia para a célula?', options: ['Ribossomo', 'Mitocôndria', 'Núcleo', 'Membrana'], answer: 1, hints: ['É chamada de "usina de energia".', 'Nela acontece a respiração celular.', 'Começa com M e não é membrana.'], explanation: 'A mitocôndria realiza a respiração celular e libera energia.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'tipos', prompt: 'As bactérias são seres procariontes.', answer: true, hints: ['Bactérias têm núcleo organizado?', 'Não têm.', 'Sem núcleo = procarionte.'], explanation: 'Verdadeiro. As bactérias não têm núcleo organizado.' },
    { id: 'q4', type: 'fill', difficulty: 2, skill: 'estruturas', prompt: 'A estrutura que envolve a célula e controla o que entra e sai é a membrana ________.', answers: ['plasmatica', 'plasmática'], hints: ['É como o portão de um condomínio.', 'Toda célula tem uma.', 'Membrana plas…'], explanation: 'A membrana plasmática tem permeabilidade seletiva.' },
    { id: 'q5', type: 'mc', difficulty: 2, skill: 'tipos', prompt: 'O que diferencia uma célula procarionte de uma eucarionte?', options: ['A procarionte não tem núcleo organizado', 'A procarionte não tem membrana', 'A eucarionte não tem DNA', 'A eucarionte não tem citoplasma'], answer: 0, hints: ['As duas têm membrana, citoplasma e DNA.', 'A diferença está em onde o DNA fica.', 'Na procarionte o DNA fica solto.'], explanation: 'A procarionte não tem núcleo delimitado por membrana; o DNA fica no citoplasma.' },
    { id: 'q6', type: 'match', difficulty: 2, skill: 'organelas', prompt: 'Ligue cada organela à sua função.', pairs: [['Mitocôndria', 'Respiração celular'], ['Ribossomo', 'Produção de proteínas'], ['Cloroplasto', 'Fotossíntese'], ['Núcleo', 'Guarda o DNA']], hints: ['Mitocôndria = energia.', 'Cloroplasto tem clorofila.', 'O "chefe" guarda as instruções.'], explanation: 'Mitocôndria → respiração; Ribossomo → proteínas; Cloroplasto → fotossíntese; Núcleo → DNA.' },
    { id: 'q7', type: 'mc', difficulty: 2, skill: 'animal_vegetal', prompt: 'Qual destas estruturas existe na célula vegetal, mas não na animal?', options: ['Membrana plasmática', 'Parede celular', 'Ribossomo', 'Mitocôndria'], answer: 1, hints: ['A planta tem uma "armadura".', 'Ela é feita de celulose.', 'Fica por fora da membrana.'], explanation: 'A parede celular de celulose é exclusiva da célula vegetal (entre as opções).' },
    { id: 'q8', type: 'tf', difficulty: 2, skill: 'animal_vegetal', prompt: 'As células animais possuem cloroplastos.', answer: false, hints: ['Cloroplasto serve para quê?', 'Animais fazem fotossíntese?', 'Não fazem.'], explanation: 'Falso. Cloroplastos existem em plantas e algas.' },
    { id: 'q9', type: 'fill', difficulty: 3, skill: 'organelas', prompt: 'A organela responsável pela produção de proteínas é o ________.', answers: ['ribossomo', 'ribossomos'], hints: ['Está presente até nas bactérias.', 'É a "fábrica de proteínas".', 'Ribo…'], explanation: 'O ribossomo produz proteínas.' },
    { id: 'q10', type: 'tf', difficulty: 3, skill: 'animal_vegetal', prompt: 'As células vegetais também possuem mitocôndrias.', answer: true, hints: ['A planta precisa liberar energia?', 'Plantas também respiram.', 'A respiração celular ocorre na mitocôndria.'], explanation: 'Verdadeiro. Plantas fazem fotossíntese e também respiração celular.' },
    { id: 'q11', type: 'mc', difficulty: 3, skill: 'estruturas', prompt: 'Nas células eucariontes, onde fica a maior parte do DNA?', options: ['Na membrana', 'No núcleo', 'Na parede celular', 'No vacúolo'], answer: 1, hints: ['Eucarionte = núcleo verdadeiro.', 'O núcleo é o "chefe".', 'Ele guarda as instruções.'], explanation: 'No núcleo, delimitado pela carioteca.' },
    { id: 'q12', type: 'open', difficulty: 3, skill: 'organelas', prompt: 'Por que as células dos músculos têm muitas mitocôndrias?', modelAnswer: 'Porque os músculos precisam de muita energia para se movimentar, e as mitocôndrias são as organelas que liberam energia pela respiração celular.', keywords: ['energia', 'respiracao', 'movimento', 'contracao', 'esforco'], hints: ['O que o músculo faz o tempo todo?', 'Movimento gasta o quê?', 'Quem libera isso na célula?'], explanation: 'Músculos gastam muita energia, e a mitocôndria é quem a libera.' },
  ],
  review: ['Célula = unidade da vida', 'Membrana, citoplasma e DNA (no núcleo nas eucariontes)', 'Procarionte (sem núcleo) × eucarionte (com núcleo)', 'Mitocôndria = energia · Ribossomo = proteínas · Cloroplasto = fotossíntese', 'Vegetal tem parede celular, cloroplasto e vacúolo grande'],
  sources: [{ title: 'Base Nacional Comum Curricular (BNCC) — Ciências da Natureza', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' }, AUTORAL],
}
