import { block, fill, lesson, mc, tf } from '../dsl'
const F: any[] = []

export const fisica = lesson({id:'fis-mov',subject:'fisica',title:'Movimento',levels:['medio'],grade:'9º',topic:'Física',subtopic:'Cinemática',aliases:['velocidade','distância','tempo'],summary:'v=d/t',intro:'Movimento.',objective:'Velocidade.',next:[],skills:{v:'Vel'},blocks:[block('v','Velocidade','v=distância/tempo. 100km em 2h = 50km/h.','-Fórmula simples.','Proporção.','Básico.','1. Como calcular?'),],questions:[mc(1,'v','100km 2h=?',['50km/h','100km/h','200km/h'],0,[]),tf(1,'v','MU=velocidade constante',true,[]),fill(1,'v','v=distância÷___.',['tempo'],[]),],review:['v=d/t','Proporção','Km/h'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const quimica = lesson({id:'qui-atomo',subject:'quimica',title:'Átomos',levels:['medio'],grade:'9º',topic:'Química',subtopic:'Estrutura',aliases:['próton','elétron','nêutron'],summary:'Próton(+) Elétron(-) Nêutron(0)',intro:'Dentro do átomo.',objective:'Estrutura atômica.',next:[],skills:{a:'Átomo'},blocks:[block('a','Átomo','Próton(+). Elétron(-). Nêutron(0). Núcleo=próton+nêutron. Eletrosfera=elétron.','Oxigênio: 8 prótons.','Z=número atômico=prótons.','Estável.','1. Próton onde?'),],questions:[mc(1,'a','Próton=?',['negativo','positivo','neutro'],1,[]),tf(1,'a','Elétron negativo',true,[]),fill(1,'a','Z=número ___.',['atômico'],[]),],review:['Próton +','Elétron -','Nêutron 0','Z=prótons'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const biologia = lesson({id:'bio-celula',subject:'biologia',title:'Célula',levels:['medio'],grade:'8º',topic:'Biologia',subtopic:'Celular',aliases:['procariota','eucariota','núcleo','mitocôndria'],summary:'Procariota vs Eucariota',intro:'Unidade vida.',objective:'Célula.',next:[],skills:{c:'Célula'},blocks:[block('c','Célula','Procariota: sem núcleo (bactéria). Eucariota: com núcleo (animal, planta). Mitocôndria: energia.','Você: eucariota.','Bactéria: procariota.','Dois tipos.','1. Diferença?'),],questions:[mc(1,'c','Procariota=?',['com núcleo','sem núcleo'],1,[]),tf(1,'c','Humano eucariota',true,[]),fill(1,'c','Mitocôndria: ___.',['energia'],[]),],review:['Procariota','Eucariota','Mitocôndria','Núcleo'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const literatura = lesson({id:'lit-modern',subject:'literatura',title:'Modernismo',levels:['medio'],grade:'9º',topic:'Literatura',subtopic:'Escolas',aliases:['1922','macunaíma','mário de andrade','semana arte moderna'],summary:'1922: ruptura.',intro:'Semana Arte Moderna.',objective:'Modernismo.',next:[],skills:{m:'Mod'},blocks:[block('m','Modernismo','1922: Semana Arte Moderna (SP). Mário de Andrade. Rompeu realismo. Macunaíma (1928). Liberdade forma.','1922=ruptura Brasil.','Identidade nacional.','Novo.','1. Qual ano?'),],questions:[mc(1,'m','Ano?',['1822','1900','1922'],2,[]),tf(1,'m','Mário de Andrade',true,[]),fill(1,'m','Macunaíma: ___.',['Mário de Andrade'],[]),],review:['1922','Semana Arte Moderna','Macunaíma','Liberdade formal'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const filosofia = lesson({id:'fil-socrates',subject:'filosofia',title:'Sócrates',levels:['medio'],grade:'9º',topic:'Filosofia',subtopic:'Antigos',aliases:['atenas','maiêutica','virtude','conhecimento'],summary:'Só sei que nada sei.',intro:'Método perguntas.',objective:'Sócrates.',next:[],skills:{s:'Soc'},blocks:[block('s','Sócrates','Atenas. Maiêutica: perguntas→verdade. "Só sei que nada sei". Virtude=conhecimento. 399 aC: morte.','Dialogava praça.','Humildade intelectual.','Questionamento.','1. Qual método?'),],questions:[mc(1,'s','Onde?',['Esparta','Atenas'],1,[]),tf(1,'s','Maiêutica=perguntas',true,[]),fill(1,'s','Virtude=___.',['conhecimento'],[]),],review:['Atenas','Maiêutica','Conhecimento','Humildade'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const sociologia = lesson({id:'soc-trabalho',subject:'sociologia',title:'Trabalho',levels:['medio'],grade:'9º',topic:'Sociologia',subtopic:'Sociedade',aliases:['emprego','classe','exploração','salário'],summary:'Trabalho: atividade.',intro:'O que é trabalho?',objective:'Conceito trabalho.',next:[],skills:{t:'Trab'},blocks:[block('t','Trabalho','Atividade produtiva. Emprego≠trabalho. Classes: patrão, assalariado, autônomo. Exploração: recebe<produz.','Relação produção.','Capital.','Desigualdade.','1. Qual diferença emprego/trabalho?'),],questions:[mc(1,'t','Trabalho=?',['game','atividade produtiva','hobby'],1,[]),tf(1,'t','Emprego=contrato',true,[]),fill(1,'t','Exploração: ganho <___.',['produzido'],[]),],review:['Atividade','Emprego vs trabalho','Classes','Exploração'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})
