import { block, fill, lesson, mc, tf } from '../dsl'
const F: any[] = []

export const astronomia = lesson({id:'ast-universo',subject:'astronomia',title:'Astronomia Básica',levels:['fund1'],grade:'6º',topic:'Ciências',subtopic:'Espaço',aliases:['sol','lua','planeta','estrela','galaxia'],summary:'Sistema solar e universo.',intro:'O que está lá em cima?',objective:'Conhecer espaço.',next:[],skills:{s:'Sistema',u:'Universo'},blocks:[block('s','Sistema','Sol: estrela (energia). Planetas: 8 (Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano, Netuno). Lua: satélite Terra. Órbita: movimento.','Ordem distância.','Tamanhos diferentes.','Movimento ordenado.','Qual planeta?'),block('u','Universo','Bilhões galaxias. Bilhões estrelas cada. Via Láctea: nossa galáxia (200B estrelas). Ano-luz: distância. Big Bang (origem). Infinito?','Escala cósmica.','Humano minúsculo.','Perspectiva.','Qual tamanho?'),],questions:[mc(1,'s','3º planeta do Sol?',['Terra','Marte','Vênus'],0,['Nossa casa.','Órbita.','Vida.']),tf(1,'u','Universo: bilhões galaxias',true,['Sim.','Escala.','Infinito praticamente.']),fill(1,'s','___ é satélite da Terra.',['Lua'],['Órbita.','Noite.','Influencia marés.']),mc(2,'u','Via Láctea: quantas estrelas?',['200 bilhões','2 trilhões','20 bilhões'],0,['Nossa galaxia.','Estimativa.','Cálculo.']),],review:['8 planetas','Sistema solar','Via Láctea','Ano-luz'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const meioambiente = lesson({id:'env-ambiente',subject:'meioambiente',title:'Meio Ambiente e Sustentabilidade',levels:['fund1'],grade:'7º',topic:'Ciências',subtopic:'Ecologia',aliases:['ecosistema','poluição','desmatamento','sustentabilidade','reciclagem'],summary:'Proteção do planeta.',intro:'Como preservar a Terra?',objective:'Consciência ambiental.',next:[],skills:{e:'Ecossistema',a:'Ações'},blocks:[block('e','Ecossistema','Seres vivos + ambiente. Produtor (planta), consumidor (animal), decompositor (bactéria). Ciclos: carbono, nitrogênio, água. Equilíbrio.','Interconectado.','Depende todos.','Perturbação cascata.','Como funciona?'),block('a','Ações','Reduzir: consumir menos. Reutilizar: 2ª vida. Reciclar: matéria prima. Desmatamento: ⬇ Carbono armazenado. Poluição: ar, água, solo. Energias limpas: solar, eólica.','Escolhas importam.','Individual + coletivo.','Futuro depende.','Qual ação?'),],questions:[mc(1,'e','Produtor no ecossistema?',['plant','animal','fungo'],0,['Fotossíntese.','Energia solar.','Base cadeia.']),tf(1,'a','Reciclagem: reduz lixo',true,['Sim.','Reutiliza.','Sustentável.']),fill(1,'e','Ciclo ___ : CO2↔biosfera.',['carbono'],['Respiração.','Fotossíntese.','Equilíbrio.']),mc(2,'a','Energias limpas: qual?',['carvão','solar/eólica','petróleo'],1,['Renovável.','Sem emissão.','Futuro.']),],review:['Ecossistema','Ciclos','Reciclagem','Energia limpa'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const genetica = lesson({id:'gen-heranca',subject:'genetica',title:'Genética e Hereditariedade',levels:['medio'],grade:'9º',topic:'Ciências',subtopic:'Biologia',aliases:['DNA','cromossomo','gene','alelo','herança'],summary:'Como transmitem características?',intro:'De pais para filhos.',objective:'Entender genética.',next:[],skills:{d:'DNA',h:'Herança'},blocks:[block('d','DNA','Molécula vida. Cromossomo: DNA +proteína. Gene: segmento DNA → proteína → característica. Alelo: versão gene (dominante/recessivo). Dupla hélice.','Código genético.','4 bases (A-T, G-C).','Instrução.','O que é gene?'),block('h','Herança','Mendel: leis hereditariedade. Dominante sobre recessivo. 50% DNA cada pai. Filho recebe mix genética (menos raro genético idêntico). Mutação: mudança DNA.','Probabilidade.','Mistura genética.','Sem blending.','Qual herança?'),],questions:[mc(1,'d','DNA forma: qual?',['hélice linear','dupla hélice','tripla hélice'],1,['Watson-Crick.','Torção.','Estável.']),tf(1,'h','Filho: 50% DNA cada pai',true,['Sim.','Segregação.','Alelo.']),fill(1,'d','___ : segmento DNA → característica.',['Gene'],['Unidade.','Herança.','Proteína.']),mc(2,'h','Mendel: estudou?',['macaco','ervilha','mosca'],1,['Plantas.','Híbridos.','Proporções.']),],review:['DNA/Cromossomo','Gene/Alelo','Herança Mendel','Mutação'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const corphumano = lesson({id:'bio-corpo',subject:'corphumano',title:'Corpo Humano: Sistemas',levels:['fund1'],grade:'8º',topic:'Ciências',subtopic:'Anatomia',aliases:['digestivo','nervoso','circulatório','respiratório','muscular'],summary:'11 sistemas funcionam juntos.',intro:'Como funciona você?',objective:'Conhecer corpo.',next:[],skills:{d:'Digestivo',c:'Circulatório'},blocks:[block('d','Digestivo','Boca→esôfago→estômago→intestino delgado→intestino grosso. Absorção nutrientes. Fígado, pâncreas: apoio. Defecação: dejeto. pH e enzimas quebram comida.','Energia entrada.','Processamento.','Tempo ~30h.','Qual órgão?'),block('c','Circulatório','Coração: bomba. Artérias: sangue oxigenado. Veias: sangue desoxigenado. Circulação: pulmões↔corpo. Pressão arterial. 60-100 bpm repouso.','Transporte oxigênio.','Distribuição nutrientes.','Contínuo.','Quanto bate?'),],questions:[mc(1,'d','Absorção nutrientes: onde?',['estômago','intestino delgado','intestino grosso'],1,['Delgado = absorção.','Nutrientes.','Principal.']),tf(1,'c','Coração é uma bomba',true,['Sim.','Propulsão.','Sangue.']),fill(1,'d','___ quebra comida em pedaços pequenos.',['Enzima'],['Proteína.','Catálise.','Digestão.']),mc(2,'c','Artéria leva sangue __?',['desoxigenado','oxigenado','misto'],1,['Do coração.','Corpo todo.','Vermelho.']),],review:['Digestão','Circulação','Órgãos','Sistemas integrados'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})
