// Curso de Espanhol do LUMI — A1 · Unidade 1 (¡Hola! ¿Qué tal?). Conteúdo original.
import { blank, block, dialogue, eqsLang, esSources, fill, lesson, match, mc, mci, order, tf, v, words } from '../dsl'

const ALL = ['fund1', 'fund2', 'medio'] as const

export const esSaludos = lesson({
  id: 'esp-a1-saludos', subject: 'espanhol', title: 'Saludos y presentaciones', levels: [...ALL], grade: 'A partir do 5º ano',
  topic: 'Espanhol A1 — Primeros pasos', subtopic: 'Cumprimentos, despedidas e cortesia',
  aliases: ['saludos', 'cumprimentos em espanhol', 'hola', 'buenos dias', 'como se apresentar em espanhol', 'mucho gusto', 'que tal', 'despedidas em espanhol', 'tu e usted'],
  summary: 'Cumprimente conforme o período do dia, apresente-se, use tú e usted e despeça-se em espanhol.',
  intro: '¡Hola! Em espanhol, como em português, o cumprimento muda com o período do dia e com o grau de formalidade.',
  objective: 'Cumprimentar conforme o período do dia, se apresentar, perguntar como a pessoa está, escolher entre tú e usted e se despedir com educação.',
  next: ['esp-a1-ser-llamarse'],
  skills: { v_saludos: 'Cumprimentos pelo período do dia', s_presentar: 'Apresentar-se e responder (mucho gusto, encantado/a)', g_tu_usted: 'Tú (informal) × usted (formal)', v_despedidas: 'Despedidas e cortesia' },
  blocks: [
    block('v_saludos', '¡Hola! ¿Buenos días?',
      'Hola serve a qualquer hora. Para marcar o período: buenos días (de manhã, até o almoço), buenas tardes (depois do almoço até escurecer) e buenas noches (à noite — tanto para chegar quanto para sair). Atenção ao plural: buenos días, buenas tardes, buenas noches.',
      '¡Hola, Marta! · Buenos días, profesor. · Buenas noches, señora López.',
      'Hola = oi/olá. Buenos días = bom dia. Buenas tardes = boa tarde. Buenas noches = boa noite.',
      'Chegando à escola às 8h: “¡Buenos días, profesora!”. À noite, numa festa: “¡Buenas noches a todos!”.',
      '1. Veja o horário. 2. Manhã → buenos días; tarde → buenas tardes; noite → buenas noches. 3. Com amigos, um “¡Hola!” basta.',
      'Em espanhol os cumprimentos vêm no plural (buenos días), diferente do português (bom dia). E “buenas noches”, como “boa noite”, serve para chegar e para sair.'),
    block('s_presentar', 'Me llamo… · Mucho gusto',
      'Para se apresentar: Me llamo + nome (literalmente “eu me chamo”) ou Soy + nome. Ao conhecer alguém: Mucho gusto ou Encantado (se quem fala é homem) / Encantada (se é mulher). Para perguntar como a pessoa está: ¿Qué tal? (informal) ou ¿Cómo estás? / ¿Cómo está usted?',
      '— Hola, me llamo Lucía. — Mucho gusto, Lucía. Yo soy Pablo. — ¡Encantada!',
      'Me llamo = eu me chamo. Mucho gusto = muito prazer. ¿Qué tal? = tudo bem?',
      'Primeiro dia de curso: “Hola, me llamo Ana. Soy de Brasil. ¿Y tú?”',
      '1. Cumprimente: ¡Hola! 2. Diga seu nome: Me llamo… 3. Responda ao outro: Mucho gusto / Encantado(a).',
      '“Encantado/a” concorda com quem fala: Pablo diz encantado, Lucía diz encantada. “Mucho gusto” não muda.'),
    block('g_tu_usted', 'Tú ou usted?',
      'Tú é o tratamento informal (amigos, família, pessoas da mesma idade). Usted é formal (pessoas mais velhas, desconhecidos, situações profissionais) e usa o verbo na 3ª pessoa, como “o senhor / a senhora”. No plural, a maior parte da América Latina usa ustedes para os dois casos; na Espanha, vosotros é o plural informal.',
      '¿Cómo estás? (tú) · ¿Cómo está usted? (usted) · ¿Cómo están ustedes? (plural)',
      'Tú = você (amigo). Usted = o senhor / a senhora.',
      'Com o colega: “¿Cómo estás, Leo?”. Com o diretor da escola: “Buenos días, ¿cómo está usted?”.',
      '1. A pessoa é próxima ou da sua idade? Use tú. 2. É mais velha, desconhecida ou em situação formal? Use usted. 3. Com usted, o verbo fica igual ao de él/ella (está).',
      'Usted parece “você”, mas funciona como “o senhor”: é formal e pede verbo na 3ª pessoa.'),
    block('v_despedidas', 'Adiós, hasta luego…',
      'Despedidas: adiós (tchau/adeus), chao (informal, muito usado na América do Sul), hasta luego (até logo), hasta mañana (até amanhã), nos vemos (a gente se vê). Cortesia: por favor, gracias (obrigado/a), de nada, perdón / disculpe (desculpe), con permiso (com licença).',
      '— ¡Muchas gracias! — De nada. · ¡Hasta mañana, chicos!',
      'Adiós = tchau. Hasta luego = até logo. Gracias = obrigado. De nada = de nada.',
      'Saindo da aula: “¡Hasta mañana, profe!”. Pedindo passagem no ônibus: “Con permiso.”',
      '1. Vai embora? Adiós / Hasta luego. 2. Recebeu ajuda? Gracias. 3. Agradeceram? De nada.',
      '“Gracias” é igual para homens e mulheres — diferente do português “obrigado/obrigada”.'),
  ],
  questions: [
    mc(1, 'v_saludos', 'São 9h da manhã. Qual cumprimento combina?', ['Buenas noches', 'Buenos días', 'Buenas tardes', 'Adiós'], 1, ['Pense no período do dia.', 'Nove horas é de manhã.', 'Día = dia.'], 'Buenos días é o cumprimento da manhã.'),
    tf(1, 'v_saludos', 'Em espanhol se diz “buen día” como forma mais comum de cumprimento na Espanha.', false, ['Observe o número (singular/plural).', 'Na Espanha e na maior parte dos países usa-se o plural.', 'Buen día existe em alguns países, como a Argentina.'], 'Falso: o mais comum é “buenos días” (plural). “Buen día” é usado em alguns países, como a Argentina.'),
    fill(1, 's_presentar', 'Complete: “Hola, me ___ Pedro.”', ['llamo'], ['Verbo llamarse.', 'Com “me”…', 'Me llamo.'], 'Me llamo Pedro = eu me chamo Pedro.'),
    mc(1, 's_presentar', 'Lucía conhece alguém e quer dizer “prazer”. Ela pode dizer:', ['Encantado', 'Encantada', 'De nada', 'Hasta luego'], 1, ['Quem fala é mulher.', 'Encantado/a concorda com quem fala.', 'Feminino termina em -a.'], 'Lucía diz “encantada” (ou “mucho gusto”).'),
    match(2, 'v_despedidas', 'Ligue cada expressão ao significado.', [['Gracias', 'Obrigado(a)'], ['De nada', 'Não há de quê'], ['Hasta mañana', 'Até amanhã'], ['Con permiso', 'Com licença']], ['Gracias agradece.', 'Mañana = amanhã.', 'Permiso = licença.'], 'Gracias · De nada · Hasta mañana · Con permiso.'),
    mc(2, 'g_tu_usted', 'Você fala com o avô de um amigo, que acabou de conhecer. Qual pergunta é mais adequada?', ['¿Cómo estás?', '¿Cómo está usted?', '¿Qué pasa, tío?', '¿Y tú?'], 1, ['Pessoa mais velha e desconhecida.', 'Situação pede formalidade.', 'Usted + verbo na 3ª pessoa.'], '“¿Cómo está usted?” é a forma formal.'),
    mc(2, 'g_tu_usted', 'Com “usted”, o verbo estar fica:', ['estás', 'está', 'estoy', 'estamos'], 1, ['Usted funciona como “o senhor”.', 'Mesma forma de él/ella.', 'Está.'], 'Usted está (3ª pessoa).'),
    order(2, 's_presentar', 'Coloque a conversa em ordem.', ['¡Hola! ¿Cómo te llamas?', 'Me llamo Sara. ¿Y tú?', 'Yo soy Iván. Mucho gusto.', '¡Encantada!'], ['Primeiro a pergunta do nome.', 'Depois a resposta e a pergunta de volta.', 'Por fim, o prazer.'], 'Pergunta → resposta → apresentação → encantada.'),
    mc(3, 'v_despedidas', 'Você esbarrou em alguém na rua. O mais natural é dizer:', ['¡Perdón!', 'De nada.', 'Buenas tardes.', 'Hasta luego.'], 0, ['Você precisa se desculpar.', 'Não é agradecimento.', 'Perdón / disculpe.'], '“Perdón” ou “disculpe” pedem desculpas.'),
    tf(3, 'v_despedidas', '“Gracias” muda para “graciasa” quando quem fala é mulher.', false, ['Gracias concorda com quem fala?', 'Não, é invariável.', 'Diferente de obrigado/obrigada.'], 'Falso: “gracias” é igual para todos.'),
  ],
  review: ['Buenos días / buenas tardes / buenas noches (plural)', 'Me llamo… · Mucho gusto · Encantado/a', 'Tú (informal) × usted (formal, verbo na 3ª pessoa)', 'Adiós, hasta luego, gracias, de nada, perdón, con permiso'],
  relatedQuestions: ['como cumprimentar em espanhol', 'como se apresentar em espanhol', 'diferença entre tú e usted'],
  equivalentQuestions: eqsLang('espanhol', ['cumprimentos', 'saludos'], ['como dizer bom dia em espanhol', 'como dizer oi em espanhol', 'o que significa mucho gusto', 'como responder qué tal', 'diferença entre tú e usted', 'como dizer obrigado em espanhol', 'como se despedir em espanhol', 'encantado ou encantada', 'buenas noches serve para chegar', 'como dizer com licença em espanhol']),
  commonDoubts: [{ q: 'Posso usar “buenas noches” para chegar?', a: 'Sim. Como “boa noite” em português, serve para chegar e para sair.' }, { q: 'Usted é falta de intimidade?', a: 'É sinal de respeito. Use com pessoas mais velhas, desconhecidas e em situações formais.' }],
  commonErrors: ['Dizer “buenos día” (falta o plural).', 'Usar tú com uma autoridade ou pessoa mais velha que você não conhece.', 'Dizer “encantado” sendo mulher (o certo é encantada).'],
  english: {
    cefr: 'A1', unit: 'es-a1-u1', order: 1, area: 'vocabulary', focus: ['vocabulary', 'speaking', 'listening'],
    vocabulary: [
      v('hola', 'oi, olá', 'interjection', 'saludo para cualquier momento del día', '¡Hola, Marta! ¿Qué tal?', 1, { pronunciation: 'o “h” é mudo: “ola”' }),
      v('buenos días', 'bom dia', 'phrase', 'saludo de la mañana', 'Buenos días, profesor.', 1),
      v('buenas tardes', 'boa tarde', 'phrase', 'saludo después del mediodía', 'Buenas tardes, señora.', 1),
      v('buenas noches', 'boa noite', 'phrase', 'saludo o despedida de la noche', 'Buenas noches a todos.', 1),
      v('adiós', 'tchau, adeus', 'interjection', 'palabra para despedirse', '¡Adiós, hasta mañana!', 1, { synonyms: ['chao'] }),
      v('hasta luego', 'até logo', 'phrase', 'despedida cuando vas a ver a la persona otra vez', 'Me voy. ¡Hasta luego!', 1),
      v('gracias', 'obrigado(a)', 'interjection', 'palabra para agradecer', 'Muchas gracias por la ayuda.', 1),
      v('de nada', 'de nada', 'phrase', 'respuesta a “gracias”', '— Gracias. — De nada.', 1),
      v('por favor', 'por favor', 'phrase', 'palabra para pedir algo con educación', 'Un agua, por favor.', 1),
      v('perdón', 'desculpe', 'interjection', 'palabra para pedir disculpas', '¡Perdón! No te vi.', 1, { synonyms: ['disculpe'] }),
      v('mucho gusto', 'muito prazer', 'phrase', 'lo que dices al conocer a alguien', '— Soy Pablo. — Mucho gusto.', 2, { synonyms: ['encantado', 'encantada'] }),
      v('usted', 'o senhor, a senhora', 'pronoun', 'forma formal de “tú”', '¿Cómo está usted?', 2),
    ],
    grammar: {
      name: 'Tú × usted', when: 'Para escolher o tratamento informal ou formal.',
      structure: 'tú + verbo na 2ª pessoa (estás) · usted + verbo na 3ª pessoa (está)',
      affirmative: ['Tú estás bien.', 'Usted está bien.'], negative: ['Tú no estás cansado.', 'Usted no está cansado.'], interrogative: ['¿Cómo estás?', '¿Cómo está usted?'],
      compare: 'Em português “você” e “o senhor”; em espanhol “tú” e “usted” — mas usted usa o verbo como él/ella.',
      context: 'No hotel, a recepcionista diz: “Buenas tardes, ¿cómo está usted?”.',
    },
    listening: {
      title: 'Primer día de clase', kind: 'dialogo', rate: 0.9,
      script: ['Profesora: ¡Buenos días a todos!', 'Diego: Buenos días. Perdón, ¿es la clase de español?', 'Profesora: Sí. ¿Cómo te llamas?', 'Diego: Me llamo Diego. Soy nuevo.', 'Profesora: Mucho gusto, Diego. Yo soy la profesora Ruiz.', 'Diego: Encantado.'],
      questions: [
        mci(1, 'Em que período do dia acontece a conversa?', ['De manhã', 'À tarde', 'À noite', 'De madrugada'], 0, 'Eles dizem “buenos días”.'),
        mci(1, 'Como se chama o aluno?', ['Daniel', 'Diego', 'Ruiz', 'David'], 1, 'Ele diz “me llamo Diego”.'),
        mci(2, 'Por que Diego diz “perdón”?', ['Para se desculpar e chamar a atenção antes de perguntar', 'Para se despedir', 'Para agradecer', 'Para dizer o nome'], 0, 'Perdón também serve para chamar a atenção antes de uma pergunta.'),
        mci(2, 'Por que Diego diz “encantado” e não “encantada”?', ['Porque ele é homem', 'Porque é de manhã', 'Porque a professora é mulher', 'Porque é formal'], 0, 'Encantado/a concorda com quem fala.'),
      ],
    },
    speaking: {
      situation: 'Você chegou a uma turma nova de espanhol e quer se apresentar.', vocabulary: ['hola', 'me llamo', 'mucho gusto', '¿qué tal?'],
      phrases: ['¡Hola! Me llamo…', 'Mucho gusto.', '¿Qué tal?', 'Bien, gracias. ¿Y tú?'],
      example: '¡Hola! Me llamo Ana. Mucho gusto. ¿Qué tal?', challenge: 'Diga um cumprimento + seu nome + “mucho gusto” + uma pergunta.', expected: ['hola', 'llamo', 'gusto', 'qué'],
    },
    writing: {
      prompt: 'Escreva uma mensagem curta se apresentando para um colega de intercâmbio.', criteria: ['Tem cumprimento', 'Diz o seu nome', 'Faz uma pergunta', 'Termina com despedida'],
      model: '¡Hola! Me llamo Ana. Mucho gusto. ¿Qué tal? ¡Hasta luego!', keywords: ['hola', 'llamo', 'gusto', 'hasta'], minWords: 8,
    },
    challenge: 'Cumprimente três pessoas hoje em espanhol, cada uma de um jeito (buenos días, hola, ¿qué tal?).',
    tips: ['Cumprimentos no plural: buenos días, buenas tardes.', 'O “h” de “hola” não se pronuncia.'],
  },
  games: {
    blanks: [
      blank(1, '___ días, profesor.', ['Buenos', 'Buenas', 'Bueno', 'Buena'], 0, 'Días é masculino plural: buenos días.'),
      blank(1, 'Hola, me ___ Laura.', ['llamo', 'llama', 'soy llamo', 'llamas'], 0, 'Com “yo”: me llamo.'),
      blank(2, '— Gracias. — De ___.', ['nada', 'gusto', 'luego', 'favor'], 0, 'Responde-se a “gracias” com “de nada”.'),
      blank(2, '¿Cómo ___ usted?', ['está', 'estás', 'estoy', 'están'], 0, 'Usted pede o verbo na 3ª pessoa: está.'),
      blank(3, 'Un café, por ___.', ['favor', 'gracias', 'nada', 'perdón'], 0, 'Por favor = por favor.'),
    ],
    dialogues: [
      dialogue(1, 'Conhecendo alguém', ['Ana: ¡Hola! Me llamo Ana.', 'Leo: Hola, Ana. Yo soy Leo.', 'Ana: Mucho gusto, Leo.', 'Leo: Encantado.'], 3, ['Encantado.', 'De nada.', 'Buenas noches.', 'Por favor.'], 0, 'Leo é homem: “encantado”.'),
      dialogue(2, 'Na recepção do hotel', ['Recepcionista: Buenas tardes. ¿Cómo está usted?', 'Señor Gómez: Muy bien, gracias. ¿Y usted?', 'Recepcionista: Bien, gracias. ¿Su nombre, por favor?', 'Señor Gómez: Andrés Gómez.'], 1, ['Muy bien, gracias. ¿Y usted?', '¡Hola, tío!', 'De nada.', 'Hasta mañana.'], 0, 'Situação formal: responde-se e devolve-se a pergunta com usted.'),
    ],
    sequences: [
      words(1, 'Hola me llamo Ana', 'Me llamo + nome.', 'Organize a frase · Ordena la frase'),
      words(2, 'Mucho gusto en conocerte', 'Mucho gusto en conocerte = prazer em te conhecer.', 'Organize a frase · Ordena la frase'),
    ],
  },
  sources: esSources(),
})

export const esSerLlamarse = lesson({
  id: 'esp-a1-ser-llamarse', subject: 'espanhol', title: 'Ser y llamarse', levels: [...ALL], grade: 'A partir do 5º ano',
  topic: 'Espanhol A1 — Primeros pasos', subtopic: 'Pronomes pessoais, ser e llamarse',
  aliases: ['verbo ser em espanhol', 'llamarse', 'pronomes pessoais em espanhol', 'yo tu el', 'conjugacao do verbo ser espanhol', 'soy eres es', 'como te llamas'],
  summary: 'Use os pronomes pessoais e conjugue ser e llamarse para dizer quem você é e o nome das pessoas.',
  intro: '¿Quién eres? Para falar de você e dos outros, precisamos dos pronomes e de dois verbos essenciais: ser e llamarse.',
  objective: 'Usar os pronomes pessoais do espanhol, conjugar ser e llamarse no presente e fazer e responder perguntas sobre nome, profissão e características.',
  prerequisites: ['esp-a1-saludos'], next: ['esp-a1-alfabeto-numeros'],
  skills: { g_pronombres: 'Pronomes pessoais', g_ser: 'Verbo ser no presente', g_llamarse: 'Verbo llamarse', s_preguntas: 'Perguntar e responder sobre alguém' },
  blocks: [
    block('g_pronombres', 'Yo, tú, él, ella…',
      'Pronomes pessoais: yo (eu), tú (você/tu), él (ele), ella (ela), usted (o senhor/a senhora), nosotros/nosotras (nós), vosotros/vosotras (vocês, informal — Espanha), ellos/ellas (eles/elas), ustedes (vocês). Em espanhol o pronome é muitas vezes omitido, porque o verbo já mostra a pessoa: “Soy Ana” em vez de “Yo soy Ana”.',
      'Yo soy brasileña. · Ella es Marta. · Nosotros somos amigos.',
      'Yo = eu · tú = você · él/ella = ele/ela · nosotros = nós · ellos/ellas = eles/elas.',
      'Numa foto da turma: “Ella es Sofía, él es Mateo y nosotros somos de 7º año.”',
      '1. Veja quem faz a ação. 2. Escolha o pronome. 3. Muitas vezes você pode omiti-lo, porque o verbo já indica a pessoa.',
      '“Nosotros” e “vosotros” têm feminino (nosotras, vosotras) quando o grupo é só de mulheres.'),
    block('g_ser', 'O verbo ser',
      'Ser no presente: yo soy, tú eres, él/ella/usted es, nosotros somos, vosotros sois, ellos/ellas/ustedes son. Usamos ser para identidade, nome, origem, profissão e características: Soy Pablo. Eres de Chile. Es profesora. Son simpáticos.',
      'Soy estudiante. · ¿Eres de Argentina? · Somos hermanos.',
      'Soy = sou · eres = é/és (tú) · es = é · somos = somos · son = são.',
      'Apresentando a família: “Mi madre es médica y mi padre es profesor.”',
      '1. Identifique a pessoa. 2. Use a forma certa: soy, eres, es, somos, sois, son. 3. Complete com nome, origem, profissão ou característica.',
      'Cuidado: em espanhol “eres” é a forma de “tú”. “Usted” usa “es”, como él/ella.'),
    block('g_llamarse', 'Llamarse: me llamo, te llamas…',
      'Llamarse (chamar-se) é um verbo pronominal: me llamo, te llamas, se llama, nos llamamos, os llamáis, se llaman. Para perguntar: ¿Cómo te llamas? (tú) · ¿Cómo se llama usted? · ¿Cómo se llama él/ella?',
      '— ¿Cómo te llamas? — Me llamo Inés. · Mi hermano se llama Tomás.',
      'Me llamo = eu me chamo · te llamas = você se chama · se llama = ele/ela se chama.',
      'No primeiro dia: “¿Cómo se llama la profesora?” — “Se llama Carmen.”',
      '1. Escolha o pronome reflexivo: me, te, se, nos, os, se. 2. Conjugue llamar: llamo, llamas, llama… 3. Junte: me llamo.',
      '“Me llamo Ana” e “Soy Ana” dizem a mesma coisa; “¿Cómo te llamas?” é o jeito mais comum de perguntar o nome.'),
    block('s_preguntas', 'Perguntas sobre alguém',
      'Perguntas úteis: ¿Quién es? (Quem é?), ¿Cómo te llamas? (Como você se chama?), ¿De dónde eres? (De onde você é?), ¿Qué haces? / ¿A qué te dedicas? (O que você faz?). Em espanhol escrito, a pergunta começa com ¿ e termina com ?.',
      '— ¿Quién es ella? — Es mi prima Laura. Es de Uruguay.',
      '¿Quién? = quem? · ¿De dónde? = de onde? · Os pontos de interrogação vêm no começo e no fim.',
      'Mostrando uma foto: “¿Quién es? — Es mi amigo Juan. Es estudiante.”',
      '1. Escolha a palavra interrogativa (quién, cómo, de dónde). 2. Escreva ¿ no início e ? no fim. 3. Use o verbo na pessoa certa.',
      'Os sinais invertidos (¿ ¡) avisam desde o início que a frase é pergunta ou exclamação — por isso a entonação já começa certa.'),
  ],
  questions: [
    mc(1, 'g_ser', 'Complete: “Yo ___ estudiante.”', ['es', 'soy', 'eres', 'son'], 1, ['Com “yo”…', 'Primeira pessoa do singular.', 'Soy.'], 'Yo soy estudiante.'),
    mc(1, 'g_pronombres', 'Qual pronome corresponde a “ela”?', ['él', 'ella', 'usted', 'ellos'], 1, ['“Él” com acento = ele.', 'Feminino.', 'Ella.'], 'Ella = ela.'),
    fill(1, 'g_llamarse', 'Complete: “¿Cómo te ___?”', ['llamas'], ['Pergunta para tú.', 'Llamarse com te…', 'Te llamas.'], '¿Cómo te llamas? = Como você se chama?'),
    tf(1, 'g_ser', '“Usted” usa a mesma forma do verbo que “él” e “ella”: usted es.', true, ['Usted é 3ª pessoa?', 'Funciona como “o senhor”.', 'Sim.'], 'Verdadeiro: usted es.'),
    match(2, 'g_ser', 'Ligue o pronome à forma do verbo ser.', [['yo', 'soy'], ['tú', 'eres'], ['nosotros', 'somos'], ['ellos', 'son']], ['Primeira pessoa: soy.', 'Tú: eres.', 'Nós e eles.'], 'yo soy · tú eres · nosotros somos · ellos son.'),
    mc(2, 'g_llamarse', 'Como se diz “Minha mãe se chama Rosa”?', ['Mi madre me llama Rosa.', 'Mi madre se llama Rosa.', 'Mi madre te llamas Rosa.', 'Mi madre llamo Rosa.'], 1, ['Ela = 3ª pessoa.', 'Reflexivo da 3ª pessoa: se.', 'Se llama.'], 'Mi madre se llama Rosa.'),
    mc(2, 's_preguntas', 'Qual pergunta está escrita corretamente em espanhol?', ['De dónde eres?', '¿De dónde eres?', '¿De dónde eres', 'De dónde eres¿'], 1, ['Em espanhol há dois sinais.', 'Um invertido no início.', '¿ … ?'], 'Escreve-se ¿De dónde eres?'),
    order(2, 's_preguntas', 'Coloque o diálogo em ordem.', ['¿Quién es él?', 'Es mi hermano.', '¿Cómo se llama?', 'Se llama Bruno.'], ['Primeiro “quem é”.', 'Depois a resposta.', 'Então o nome.'], 'Quién es → es mi hermano → cómo se llama → se llama Bruno.'),
    mc(3, 'g_pronombres', 'Em “Somos de Brasil”, quem fala?', ['eu', 'você', 'nós', 'eles'], 2, ['Somos é de qual pessoa?', 'Nosotros.', 'Nós.'], 'Somos = nosotros (nós); o pronome foi omitido.'),
    tf(3, 'g_pronombres', 'Em espanhol, é obrigatório sempre usar o pronome antes do verbo (Yo soy, Tú eres…).', false, ['O verbo já indica a pessoa?', 'Sim, a terminação mostra.', 'O pronome pode ser omitido.'], 'Falso: o pronome costuma ser omitido (Soy Ana).'),
  ],
  review: ['Pronomes: yo, tú, él, ella, usted, nosotros, vosotros, ellos, ustedes', 'Ser: soy, eres, es, somos, sois, son', 'Llamarse: me llamo, te llamas, se llama…', 'Perguntas com ¿ … ? : ¿Quién es? ¿De dónde eres?'],
  relatedQuestions: ['conjugação do verbo ser em espanhol', 'como perguntar o nome em espanhol', 'pronomes pessoais em espanhol'],
  equivalentQuestions: eqsLang('espanhol', ['verbo ser', 'llamarse', 'pronomes pessoais'], ['soy eres es', 'como se diz eu sou em espanhol', 'como perguntar o nome em espanhol', 'o que significa cómo te llamas', 'por que o ponto de interrogação invertido', 'diferença entre él e el', 'o que é vosotros', 'pronome usted', 'me llamo ou soy', 'conjugação de llamarse']),
  commonErrors: ['Usar “eres” com usted (o certo é “usted es”).', 'Esquecer o “¿” no início da pergunta.', 'Dizer “mi madre me llama” em vez de “se llama”.'],
  english: {
    cefr: 'A1', unit: 'es-a1-u1', order: 2, area: 'grammar', focus: ['grammar', 'speaking', 'reading'],
    vocabulary: [
      v('yo', 'eu', 'pronoun', 'la persona que habla', 'Yo soy de Brasil.', 1),
      v('tú', 'você, tu', 'pronoun', 'la persona con quien hablas (informal)', '¿Tú eres Marta?', 1),
      v('él', 'ele', 'pronoun', 'un hombre o un niño', 'Él es mi amigo.', 1, { pronunciation: 'com acento = pronome; sem acento (el) = artigo' }),
      v('ella', 'ela', 'pronoun', 'una mujer o una niña', 'Ella es profesora.', 1, { pronunciation: 'o “ll” soa parecido com o “i” de “iate” (ou com “j”, na Argentina)' }),
      v('nosotros', 'nós', 'pronoun', 'yo y otras personas', 'Nosotros somos amigos.', 1),
      v('ellos', 'eles', 'pronoun', 'varias personas (grupo masculino o mixto)', 'Ellos son de Perú.', 1),
      v('estudiante', 'estudante', 'noun', 'persona que estudia', 'Soy estudiante de español.', 1),
      v('hermano', 'irmão', 'noun', 'hijo de los mismos padres que tú', 'Mi hermano se llama Luis.', 1, { related: ['hermana'] }),
      v('amigo', 'amigo', 'noun', 'persona que quieres y con quien pasas tiempo', 'Ella es mi mejor amiga.', 1),
      v('quién', 'quem', 'pronoun', 'palabra para preguntar por una persona', '¿Quién es él?', 1),
    ],
    grammar: {
      name: 'Verbo ser e llamarse no presente', when: 'Para dizer nome, identidade, origem, profissão e características.',
      structure: 'ser: soy, eres, es, somos, sois, son · llamarse: me llamo, te llamas, se llama, nos llamamos, os llamáis, se llaman',
      affirmative: ['Soy Ana.', 'Ella se llama Rosa.'], negative: ['No soy de España.', 'Él no se llama Juan.'], interrogative: ['¿Eres de Brasil?', '¿Cómo se llama ella?'],
      compare: 'Na negação, “no” vem antes do verbo (e antes do pronome reflexivo): “No me llamo Pedro”.',
      context: 'Ficha de inscrição: “Me llamo Bruno, soy brasileño y soy estudiante.”',
    },
    reading: {
      title: 'Mi grupo de estudio', genre: 'mensagem',
      text: '¡Hola! Me llamo Valeria y soy de Bogotá, en Colombia. Soy estudiante. En mi grupo de estudio somos cuatro: Martín es de México y es muy simpático; Ana y Lucía son hermanas y son de Chile. ¿Y tú? ¿Cómo te llamas? ¿De dónde eres?',
      questions: [
        mci(1, 'De onde é Valeria?', ['Do México', 'Da Colômbia', 'Do Chile', 'Do Brasil'], 1, 'Ela é de Bogotá, na Colômbia.'),
        mci(1, 'Quantas pessoas há no grupo?', ['Duas', 'Três', 'Quatro', 'Cinco'], 2, '“Somos cuatro”.'),
        mci(2, 'O que Ana e Lucía são?', ['Primas', 'Irmãs', 'Professoras', 'Mexicanas'], 1, '“Son hermanas”.'),
        mci(2, 'Para que Valeria faz perguntas no final?', ['Para conhecer quem lê a mensagem', 'Para pedir ajuda', 'Para se despedir', 'Para reclamar'], 0, 'Ela quer saber o nome e a origem de quem lê.'),
      ],
    },
    speaking: {
      situation: 'Você mostra uma foto e apresenta duas pessoas da sua família.', vocabulary: ['es', 'se llama', 'mi hermano', 'mi madre'],
      phrases: ['Ella es mi madre.', 'Se llama…', 'Él es mi hermano.', 'Es de…'],
      example: 'Ella es mi madre. Se llama Rosa. Él es mi hermano. Se llama Leo.', challenge: 'Apresente duas pessoas usando “es” e “se llama”.', expected: ['es', 'llama', 'mi'],
    },
    writing: {
      prompt: 'Escreva três frases sobre você: nome, origem e uma característica.', criteria: ['Usa me llamo ou soy', 'Diz a origem com “soy de”', 'Usa uma característica'],
      model: 'Me llamo Bruno. Soy de Brasil. Soy simpático y estudioso.', keywords: ['llamo', 'soy'], minWords: 8,
    },
    challenge: 'Escreva o nome de três pessoas da sua família com “se llama”.',
    tips: ['Pergunta tem ¿ no início.', '“Eres” é só para tú.'],
  },
  games: {
    blanks: [
      blank(1, 'Tú ___ mi amigo.', ['eres', 'es', 'soy', 'son'], 0, 'Tú eres.'),
      blank(1, 'Nosotros ___ hermanos.', ['somos', 'son', 'sois', 'es'], 0, 'Nosotros somos.'),
      blank(2, 'Mi padre ___ llama Jorge.', ['se', 'me', 'te', 'nos'], 0, 'Ele: se llama.'),
      blank(2, 'Ellos ___ de Perú.', ['son', 'somos', 'es', 'eres'], 0, 'Ellos son.'),
    ],
    dialogues: [
      dialogue(1, 'Na sala de aula', ['Inés: ¿Quién es él?', 'Raúl: Es Tomás, el nuevo estudiante.', 'Inés: ¿De dónde es?', 'Raúl: Es de Argentina.'], 3, ['Es de Argentina.', 'Me llamo Raúl.', 'Somos amigos.', 'De nada.'], 0, '“¿De dónde es?” pede a origem.'),
      dialogue(2, 'Conhecendo a família', ['Leo: ¿Cómo se llama tu hermana?', 'Sara: Se llama Elena.', 'Leo: ¿Y es estudiante?', 'Sara: No, es médica.'], 1, ['Se llama Elena.', 'Me llamo Elena.', 'Te llamas Elena.', 'Soy Elena.'], 0, 'A irmã é 3ª pessoa: se llama.'),
    ],
    sequences: [
      words(1, 'Ella se llama Marta', 'Se llama = ela se chama.', 'Organize a frase · Ordena la frase'),
      words(2, 'Nosotros somos de Brasil', 'Nosotros somos + de + país.', 'Organize a frase · Ordena la frase'),
    ],
  },
  sources: esSources(),
})

export const esAlfabetoNumeros = lesson({
  id: 'esp-a1-alfabeto-numeros', subject: 'espanhol', title: 'El alfabeto y los números', levels: [...ALL], grade: 'A partir do 5º ano',
  topic: 'Espanhol A1 — Primeros pasos', subtopic: 'Alfabeto, sons do espanhol e números de 0 a 100',
  aliases: ['alfabeto em espanhol', 'numeros em espanhol', 'como soletrar em espanhol', 'letra ñ', 'contar em espanhol', 'pronuncia do espanhol', 'jota', 'erre'],
  summary: 'Conheça o alfabeto e os sons mais diferentes do português, soletre seu nome e conte de 0 a 100.',
  intro: 'A, be, ce… O alfabeto espanhol tem 27 letras — incluindo o famoso ñ.',
  objective: 'Reconhecer as letras e os sons do espanhol que diferem do português (j, g, ll, ñ, h, rr, z/c), soletrar e usar os números de 0 a 100.',
  prerequisites: ['esp-a1-ser-llamarse'], next: ['esp-a1-paises'],
  skills: { v_alfabeto: 'Letras e soletração', p_sonidos: 'Sons diferentes do português', v_numeros: 'Números de 0 a 20', v_decenas: 'Dezenas até 100' },
  blocks: [
    block('v_alfabeto', 'El alfabeto',
      'O alfabeto espanhol tem 27 letras: as 26 do português + ñ (eñe). Os nomes de algumas letras: a, be, ce, de, e, efe, ge, hache, i, jota, ka, ele, eme, ene, eñe, o, pe, cu, erre, ese, te, u, uve, uve doble, equis, ye, zeta. Para soletrar: ¿Cómo se escribe? (Como se escreve?).',
      '— ¿Cómo se escribe tu nombre? — Jota, u, a, ene: Juan.',
      'Ñ = eñe, como o “nh”: España. J = jota. H = hache (muda).',
      'Ao fazer uma reserva por telefone: “Mi apellido es Peña: pe, e, eñe, a.”',
      '1. Pergunte: ¿Cómo se escribe? 2. Diga letra por letra pelo nome (be, ce, jota…). 3. Atenção ao ñ.',
      'O “ñ” corresponde ao “nh” do português: España = “Espanha”, mañana = “manhã”.'),
    block('p_sonidos', 'Sons que enganam',
      'Alguns sons mudam em relação ao português: J (e G antes de e/i) soa como um “rr” forte do fundo da garganta (jamón, gente). H é muda (hola = “ola”). LL soa parecido com o “i” de “iate” (em muitos lugares; na Argentina, mais perto de “j/x”). RR e R inicial são vibrados com a ponta da língua (perro, Roma). Z e C antes de e/i soam como “s” na América Latina e como o “th” inglês na maior parte da Espanha. V e B soam iguais, como um “b” suave.',
      'jamón · gente · hola · llave · perro · zapato · vaca/baca',
      'J = som de garganta. H = muda. LL ≈ “i”. RR = vibrado. V = B.',
      'Pedindo no restaurante: “Un jugo de naranja, por favor” — o “j” de “jugo” sai da garganta.',
      '1. Veja a letra. 2. J/G(e,i): som de garganta. 3. H: não pronuncie. 4. RR: vibre a língua. 5. V: diga como b.',
      'Não leia o espanhol como português: “gente” não é “jente”, e “hola” não tem o som de “h” aspirado.'),
    block('v_numeros', 'Números de 0 a 20',
      '0 cero, 1 uno, 2 dos, 3 tres, 4 cuatro, 5 cinco, 6 seis, 7 siete, 8 ocho, 9 nueve, 10 diez, 11 once, 12 doce, 13 trece, 14 catorce, 15 quince, 16 dieciséis, 17 diecisiete, 18 dieciocho, 19 diecinueve, 20 veinte. De 16 a 19 escreve-se numa palavra só.',
      'Tengo doce años. · Mi número es el siete.',
      'Uno, dos, tres, cuatro, cinco… diez, once, doce… veinte.',
      'Dizendo a idade: “Tengo trece años.” (em espanhol, a idade se diz com tener).',
      '1. Decore 0–15. 2. De 16 a 19: dieci + número (dieciséis). 3. 20 = veinte.',
      'Atenção: “siete” (7) e “diez” (10) têm “ie”; “once” é 11 (e não “onze” com z).'),
    block('v_decenas', 'Dezenas até 100',
      '21 a 29 numa palavra: veintiuno, veintidós, veintitrés… De 30 em diante usa-se “y”: treinta y uno, cuarenta y cinco. Dezenas: 30 treinta, 40 cuarenta, 50 cincuenta, 60 sesenta, 70 setenta, 80 ochenta, 90 noventa, 100 cien.',
      '35 = treinta y cinco · 72 = setenta y dos · 100 = cien',
      'De 30 em diante: dezena + y + unidade.',
      'No mercado: “Son cuarenta y ocho pesos.”',
      '1. Diga a dezena (treinta, cuarenta…). 2. Acrescente “y”. 3. Diga a unidade.',
      'Diferente do português, o “y” só aparece entre dezena e unidade a partir de 31; de 21 a 29 tudo vira uma palavra (veintiocho).'),
  ],
  questions: [
    mc(1, 'v_alfabeto', 'Quantas letras tem o alfabeto espanhol?', ['26', '27', '28', '30'], 1, ['Tem as do português…', '…e mais uma.', 'O ñ.'], '27 letras (com o ñ).'),
    mc(1, 'v_numeros', 'Como se diz 15 em espanhol?', ['cinco', 'quince', 'cincuenta', 'quinze'], 1, ['Começa com “q”.', 'Parecido com o português.', 'Quince.'], '15 = quince.'),
    tf(1, 'p_sonidos', 'Em “hola”, o “h” não é pronunciado.', true, ['O h é mudo?', 'Como em “hoje”.', 'Sim.'], 'Verdadeiro: o h é mudo.'),
    fill(1, 'v_numeros', 'Escreva por extenso: 20 = ___', ['veinte'], ['Começa com “v”.', 'Vein…', 'Veinte.'], '20 = veinte.'),
    match(2, 'v_decenas', 'Ligue o número à escrita.', [['30', 'treinta'], ['45', 'cuarenta y cinco'], ['60', 'sesenta'], ['100', 'cien']], ['Trinta = treinta.', 'Dezena + y + unidade.', 'Cem = cien.'], '30 treinta · 45 cuarenta y cinco · 60 sesenta · 100 cien.'),
    mc(2, 'p_sonidos', 'Em qual palavra o som é de garganta, parecido com um “rr” forte?', ['hola', 'jamón', 'llave', 'zapato'], 1, ['Pense no “j”.', 'Jota.', 'Jamón.'], 'O “j” de jamón é um som de garganta.'),
    mc(2, 'v_decenas', 'Como se escreve 27?', ['veinte y siete', 'veintisiete', 'veinte siete', 'vintisiete'], 1, ['De 21 a 29…', '…numa palavra só.', 'Veinti + siete.'], '27 = veintisiete.'),
    order(1, 'v_numeros', 'Coloque em ordem crescente.', ['tres', 'siete', 'doce', 'diecinueve'], ['Três é o menor.', 'Depois sete.', 'Doze e dezenove.'], '3 → 7 → 12 → 19.'),
    mc(3, 'v_alfabeto', 'Uma pessoa soletra: “pe, e, eñe, a”. Que palavra é?', ['Pena', 'Peña', 'Pana', 'Pella'], 1, ['Eñe = ñ.', 'P-e-ñ-a.', 'Peña.'], 'Peña.'),
    tf(3, 'p_sonidos', 'Em espanhol, “vaca” e “baca” são pronunciadas do mesmo jeito.', true, ['V e B têm som diferente?', 'No espanhol, não.', 'Ambos soam como b.'], 'Verdadeiro: v e b têm o mesmo som.'),
  ],
  review: ['27 letras: as do português + ñ', 'J/G(e,i) de garganta · H muda · LL ≈ “i” · RR vibrado · V = B', '0–20: cero… quince… veinte', '21–29 numa palavra; 31+ com “y”; 100 = cien'],
  relatedQuestions: ['números em espanhol de 1 a 100', 'como se pronuncia o j em espanhol', 'alfabeto espanhol'],
  equivalentQuestions: eqsLang('espanhol', ['alfabeto', 'números', 'pronúncia'], ['como contar até 100 em espanhol', 'como se escreve 15 em espanhol', 'como soletrar em espanhol', 'o que é a letra ñ', 'como pronunciar o j em espanhol', 'o h é mudo em espanhol', 'como pronunciar ll', 'diferença entre v e b em espanhol', 'como dizer a idade em espanhol', 'veintiuno ou veinte y uno']),
  commonErrors: ['Pronunciar o “h” (hola).', 'Escrever “veinte y cinco” (o certo é veinticinco).', 'Ler “gente” como no português.'],
  english: {
    cefr: 'A1', unit: 'es-a1-u1', order: 3, area: 'pronunciation', focus: ['vocabulary', 'listening', 'speaking'],
    vocabulary: [
      v('cero', 'zero', 'number', 'el número 0', 'Cero más uno es uno.', 1),
      v('cinco', 'cinco', 'number', 'el número 5', 'Tengo cinco libros.', 1),
      v('diez', 'dez', 'number', 'el número 10', 'Son las diez.', 1),
      v('quince', 'quinze', 'number', 'el número 15', 'Tengo quince años.', 1),
      v('veinte', 'vinte', 'number', 'el número 20', 'Hay veinte alumnos.', 1),
      v('treinta', 'trinta', 'number', 'el número 30', 'El mes tiene treinta días.', 2),
      v('cien', 'cem', 'number', 'el número 100', 'Cien por ciento.', 2),
      v('letra', 'letra', 'noun', 'cada signo del alfabeto', 'La ñ es una letra española.', 1),
      v('deletrear', 'soletrar', 'verb', 'decir las letras de una palabra una por una', '¿Puedes deletrear tu nombre?', 2),
      v('apellido', 'sobrenome', 'noun', 'nombre de la familia', 'Mi apellido es García.', 2, { pronunciation: 'o “ll” soa parecido com o “i” de “iate”' }),
    ],
    grammar: {
      name: 'Números: unidades, dezenas e o “y”', when: 'Para contar, dizer idade, preços, telefones e datas.',
      structure: '0–15 formas próprias · 16–29 numa palavra (dieciséis, veintiuno) · 31–99: dezena + y + unidade · 100 = cien',
      affirmative: ['Tengo veintidós años.', 'Son cuarenta y cinco euros.'], negative: ['No tengo veinte años, tengo diecinueve.'], interrogative: ['¿Cuántos años tienes?', '¿Cuánto cuesta?'],
      compare: 'Português: “vinte e cinco”; espanhol: “veinticinco” (sem “y”). Mas “trinta e cinco” = “treinta y cinco”.',
      context: 'Na feira: “—¿Cuánto cuestan las naranjas? —Treinta pesos el kilo.”',
    },
    listening: {
      title: 'Números de teléfono', kind: 'frase', rate: 0.85,
      script: ['Mi número es seis, dos, ocho, cuatro, uno, nueve, cero, siete.', 'Tengo catorce años.', 'La clase es en el aula treinta y dos.'],
      questions: [
        mci(1, 'Qual é a idade da pessoa?', ['4', '14', '40', '24'], 1, '“Catorce” = 14.'),
        mci(2, 'Em que sala é a aula?', ['23', '32', '30', '42'], 1, '“Treinta y dos” = 32.'),
        mci(2, 'Como começa o telefone?', ['6, 2, 8…', '2, 6, 8…', '6, 8, 2…', '8, 2, 6…'], 0, '“Seis, dos, ocho…”.'),
      ],
    },
    speaking: {
      situation: 'Você precisa soletrar seu nome e dizer seu telefone numa recepção.', vocabulary: ['se escribe', 'mi número es', 'jota', 'eñe'],
      phrases: ['Mi nombre se escribe…', 'Mi número es…', '¿Puede repetir, por favor?'],
      example: 'Mi nombre se escribe: be, erre, u, ene, o. Mi número es nueve, ocho, siete…', challenge: 'Soletre seu nome e diga um número de telefone.', expected: ['escribe', 'número'],
    },
    writing: {
      prompt: 'Escreva por extenso a sua idade e três números importantes para você.', criteria: ['Usa “tengo … años”', 'Escreve os números por extenso corretamente'],
      model: 'Tengo trece años. Mi número favorito es el siete. Mi casa es el número cuarenta y dos.', keywords: ['tengo', 'años', 'número'], minWords: 10,
    },
    challenge: 'Conte em voz alta de 10 em 10 até cien.',
    tips: ['De 16 a 29: uma palavra só.', 'O ñ é o nosso “nh”.'],
  },
  games: {
    words: [{ word: 'quince', clue: '15', difficulty: 1 }, { word: 'veinte', clue: '20', difficulty: 1 }, { word: 'treinta', clue: '30', difficulty: 2 }, { word: 'cuarenta', clue: '40', difficulty: 2 }, { word: 'cien', clue: '100', difficulty: 1 }, { word: 'siete', clue: '7', difficulty: 1 }, { word: 'nueve', clue: '9', difficulty: 1 }],
    blanks: [
      blank(1, 'Tengo ___ años. (13)', ['trece', 'tres', 'treinta', 'tresce'], 0, '13 = trece.'),
      blank(2, '45 = cuarenta ___ cinco', ['y', 'e', 'i', '—'], 0, 'De 31 em diante usa-se “y”.'),
      blank(2, 'La “___” es la letra de “España”.', ['ñ', 'n', 'ny', 'nh'], 0, 'España se escreve com ñ.'),
    ],
    sequences: [{ prompt: 'Coloque as dezenas em ordem.', difficulty: 2, items: ['treinta', 'cuarenta', 'cincuenta', 'sesenta', 'setenta'], explanation: '30 → 40 → 50 → 60 → 70.' }],
  },
  sources: esSources(),
})

export const esPaises = lesson({
  id: 'esp-a1-paises', subject: 'espanhol', title: 'Países y nacionalidades', levels: [...ALL], grade: 'A partir do 5º ano',
  topic: 'Espanhol A1 — Primeros pasos', subtopic: 'Países hispânicos, nacionalidades e origem',
  aliases: ['paises em espanhol', 'nacionalidades em espanhol', 'paises que falam espanhol', 'de donde eres', 'brasileno', 'gentilicos em espanhol'],
  summary: 'Diga de onde você é, conheça os países que falam espanhol e use as nacionalidades no masculino e no feminino.',
  intro: 'O espanhol é língua oficial em 21 países. ¿De dónde eres?',
  objective: 'Perguntar e dizer a origem com “ser de”, reconhecer países onde o espanhol é língua oficial e flexionar nacionalidades em gênero e número.',
  prerequisites: ['esp-a1-ser-llamarse'], next: ['esp-a1-familia-tener'],
  skills: { s_origen: 'Perguntar e dizer a origem', v_paises: 'Países hispânicos', g_nacionalidad: 'Nacionalidade: masculino, feminino e plural', r_lenguas: 'Línguas e países' },
  blocks: [
    block('s_origen', '¿De dónde eres?',
      'Para perguntar a origem: ¿De dónde eres? (tú) · ¿De dónde es usted? Para responder: Soy de + cidade/país (Soy de Brasil, soy de Recife) ou Soy + nacionalidade (Soy brasileño/brasileña). Também: Vivo en… (moro em…).',
      '— ¿De dónde eres? — Soy de Brasil, de Salvador. Pero vivo en Madrid.',
      '¿De dónde eres? = de onde você é? · Soy de… = sou de…',
      'Num intercâmbio: “Soy brasileña, soy de Porto Alegre y vivo en Buenos Aires.”',
      '1. Pergunte: ¿De dónde eres? 2. Responda: Soy de + lugar. 3. Se quiser, diga onde mora: Vivo en…',
      '“Ser de” indica origem; “vivir en” indica onde a pessoa mora agora — podem ser lugares diferentes.'),
    block('v_paises', 'Onde se fala espanhol',
      'O espanhol é língua oficial em 21 países: Espanha (Europa), Guiné Equatorial (África) e, na América, México, Guatemala, Honduras, El Salvador, Nicarágua, Costa Rica, Panamá, Cuba, República Dominicana, Porto Rico (território dos EUA), Colômbia, Venezuela, Equador, Peru, Bolívia, Paraguai, Chile, Argentina e Uruguai. O país com mais falantes nativos é o México.',
      'México, Colombia, Argentina, España, Perú, Chile…',
      'Quase toda a América do Sul fala espanhol — exceto Brasil, Guiana, Suriname e Guiana Francesa.',
      'O Brasil faz fronteira com sete países onde se fala espanhol: Uruguai, Argentina, Paraguai, Bolívia, Peru, Colômbia e Venezuela.',
      '1. Lembre o continente. 2. Na América do Sul, só Brasil, Guiana, Suriname e Guiana Francesa não têm o espanhol como língua oficial. 3. Na Europa: Espanha; na África: Guiné Equatorial.',
      'O espanhol tem variações (como o português do Brasil e de Portugal): vocabulário e sotaque mudam entre os países, mas todos se entendem.'),
    block('g_nacionalidad', 'Brasileño, brasileña…',
      'Nacionalidades concordam em gênero e número. Terminadas em -o: brasileño/brasileña, mexicano/mexicana. Terminadas em consoante: español/española, francés/francesa (ganham -a no feminino). Terminadas em -e ou -a costumam ser iguais: canadiense, estadounidense. Plural: + s (vocal) ou + es (consoante): brasileños, españoles.',
      'Él es mexicano; ella es mexicana. · Ellos son españoles; ellas son españolas.',
      'Masculino -o, feminino -a. Consoante + a no feminino. Plural com -s ou -es.',
      'Na Copa: “Los jugadores argentinos y las jugadoras argentinas.”',
      '1. Veja o gênero da pessoa. 2. Troque -o por -a, ou acrescente -a depois da consoante. 3. No plural, + s ou + es.',
      'Em espanhol, nacionalidades e nomes de línguas se escrevem com letra minúscula: “soy brasileño”, “hablo español”.'),
    block('r_lenguas', 'Línguas e países',
      'Para falar de línguas: hablo + língua (hablo portugués, hablo un poco de español). Os nomes das línguas também são minúsculos: español, portugués, inglés, francés. Pergunta útil: ¿Qué idiomas hablas?',
      '— ¿Qué idiomas hablas? — Hablo portugués, inglés y un poco de español.',
      'Hablo = eu falo. ¿Qué idiomas hablas? = que línguas você fala?',
      'Num perfil de aplicativo de intercâmbio: “Soy brasileño. Hablo portugués y aprendo español.”',
      '1. Use hablar: hablo, hablas, habla. 2. Escreva a língua com minúscula. 3. Use “un poco de” se ainda estiver aprendendo.',
      'Em espanhol a língua também se chama “castellano”, nome muito usado na Espanha e em vários países da América.'),
  ],
  questions: [
    mc(1, 's_origen', '— ¿De dónde eres? — ________', ['Soy de Brasil.', 'Me llamo Ana.', 'Tengo doce años.', 'Muy bien, gracias.'], 0, ['A pergunta é sobre origem.', 'De dónde = de onde.', 'Soy de…'], 'Soy de Brasil.'),
    mc(1, 'g_nacionalidad', 'Ana é do México. Ela é:', ['mexicano', 'mexicana', 'mexicanos', 'mexicanas'], 1, ['Ana é mulher.', 'Singular.', 'Termina em -a.'], 'Ana es mexicana.'),
    tf(1, 'v_paises', 'O espanhol é língua oficial no Chile.', true, ['O Chile fica na América do Sul.', 'Fala-se espanhol lá?', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'r_lenguas', 'Complete: “Yo ___ portugués.” (falar)', ['hablo'], ['Verbo hablar.', 'Com “yo”…', 'Hablo.'], 'Yo hablo portugués.'),
    match(2, 'g_nacionalidad', 'Ligue o masculino ao feminino.', [['español', 'española'], ['francés', 'francesa'], ['argentino', 'argentina'], ['canadiense', 'canadiense (igual)']], ['Consoante + a.', 'Francés perde o acento: francesa.', 'Termina em -e: igual.'], 'española · francesa · argentina · canadiense.'),
    mc(2, 'v_paises', 'Qual destes países da América do Sul NÃO tem o espanhol como língua oficial?', ['Uruguai', 'Peru', 'Brasil', 'Bolívia'], 2, ['No Brasil fala-se…', '…português.', 'Brasil.'], 'Brasil (português).'),
    mc(2, 'g_nacionalidad', 'Como fica o plural de “español”?', ['españols', 'españoles', 'españoes', 'español'], 1, ['Termina em consoante.', 'Plural com -es.', 'Españoles.'], 'Españoles.'),
    order(2, 's_origen', 'Organize a apresentação.', ['Hola, me llamo Pedro.', 'Soy brasileño.', 'Soy de Recife.', 'Hablo portugués y un poco de español.'], ['Primeiro o nome.', 'Depois nacionalidade e cidade.', 'Por fim as línguas.'], 'Nome → nacionalidade → cidade → línguas.'),
    mc(3, 'g_nacionalidad', 'Qual frase está correta em espanhol?', ['Soy Brasileña.', 'Soy brasileña.', 'Soy brasilera.', 'Soy de brasileña.'], 1, ['Nacionalidade com maiúscula?', 'Não: minúscula.', 'Soy brasileña.'], '“Soy brasileña” — nacionalidades se escrevem com minúscula.'),
    tf(3, 's_origen', '“Soy de Lima, pero vivo en Santiago” significa que a pessoa nasceu em Santiago.', false, ['Ser de = origem.', 'Vivir en = moradia.', 'Ela é de Lima.'], 'Falso: ela é de Lima e mora em Santiago.'),
  ],
  review: ['¿De dónde eres? — Soy de… / Vivo en…', '21 países com espanhol oficial (México tem mais falantes)', 'Nacionalidades: -o/-a, consoante + a, plural -s/-es, minúsculas', 'Hablo + língua (minúscula)'],
  relatedQuestions: ['como dizer de onde sou em espanhol', 'nacionalidades em espanhol', 'quais países falam espanhol'],
  equivalentQuestions: eqsLang('espanhol', ['países', 'nacionalidades'], ['como dizer sou brasileiro em espanhol', 'brasileño ou brasilero', 'quais países falam espanhol', 'quantos países falam espanhol', 'o que significa de dónde eres', 'feminino de español', 'plural de español', 'nacionalidade com letra maiúscula em espanhol', 'como dizer que língua eu falo em espanhol', 'o que é castellano']),
  commonErrors: ['Escrever nacionalidades e línguas com maiúscula.', 'Dizer “soy de brasileño” (é “soy brasileño” ou “soy de Brasil”).', 'Confundir “ser de” (origem) com “vivir en” (moradia).'],
  english: {
    cefr: 'A1', unit: 'es-a1-u1', order: 4, area: 'vocabulary', focus: ['vocabulary', 'reading', 'speaking'],
    vocabulary: [
      v('país', 'país', 'noun', 'territorio con su propio gobierno', 'México es un país muy grande.', 1),
      v('brasileño', 'brasileiro', 'adjective', 'persona o cosa de Brasil', 'Soy brasileño, de São Paulo.', 1, { related: ['brasileña'] }),
      v('español', 'espanhol', 'adjective', 'de España; también el nombre de la lengua', 'Hablo español.', 1, { synonyms: ['castellano'] }),
      v('mexicano', 'mexicano', 'adjective', 'persona o cosa de México', 'La comida mexicana es deliciosa.', 1),
      v('argentino', 'argentino', 'adjective', 'persona o cosa de Argentina', 'Mi profesor es argentino.', 1),
      v('idioma', 'idioma, língua', 'noun', 'lengua que habla un pueblo', '¿Qué idiomas hablas?', 1, { synonyms: ['lengua'] }),
      v('hablar', 'falar', 'verb', 'decir palabras, comunicarse', 'Hablo un poco de español.', 1),
      v('vivir', 'morar, viver', 'verb', 'tener tu casa en un lugar', 'Vivo en Buenos Aires.', 1),
      v('ciudad', 'cidade', 'noun', 'lugar grande con muchas casas y personas', 'Soy de la ciudad de Lima.', 1),
    ],
    grammar: {
      name: 'Gênero e número das nacionalidades', when: 'Para dizer a nacionalidade de homens, mulheres e grupos.',
      structure: '-o → -a (mexicano/mexicana) · consoante + a (español/española) · -e/-a iguais (canadiense) · plural + s / + es',
      affirmative: ['Ella es colombiana.', 'Ellos son peruanos.'], negative: ['No soy español, soy brasileño.'], interrogative: ['¿Eres argentina?', '¿Son ustedes chilenos?'],
      compare: 'Português: “brasileiro”; espanhol: “brasileño” (na Argentina também se ouve “brasilero”).',
      context: 'Na lista de um time internacional: “dos jugadoras colombianas y un jugador español”.',
    },
    reading: {
      title: 'Clase de intercambio', genre: 'texto informativo',
      text: 'En la clase de intercambio hay estudiantes de muchos países. Sofía es uruguaya y vive en Montevideo. Kenji es japonés, pero vive en Lima, en Perú. Pierre y Claire son franceses. Todos hablan un poco de español. La profesora es española, de Sevilla.',
      questions: [
        mci(1, 'Onde Kenji mora?', ['No Japão', 'Em Lima', 'Em Montevideo', 'Em Sevilha'], 1, '“Vive en Lima”.'),
        mci(1, 'De onde é a professora?', ['Da Espanha', 'Do Uruguai', 'Da França', 'Do Peru'], 0, 'Ela é espanhola, de Sevilha.'),
        mci(2, 'Por que “franceses” está no plural?', ['Porque fala de Pierre e Claire juntos', 'Porque são mulheres', 'Porque moram na França', 'Porque falam francês'], 0, 'São duas pessoas: plural.'),
        mci(3, 'O que os alunos têm em comum?', ['Todos são do Peru', 'Todos falam um pouco de espanhol', 'Todos são franceses', 'Todos moram em Sevilha'], 1, '“Todos hablan un poco de español”.'),
      ],
    },
    speaking: {
      situation: 'Você está num encontro de estudantes de vários países e se apresenta.', vocabulary: ['soy de', 'soy brasileño/a', 'vivo en', 'hablo'],
      phrases: ['Soy de…', 'Soy brasileño / brasileña.', 'Vivo en…', 'Hablo portugués y un poco de español.'],
      example: 'Soy brasileña, de Fortaleza. Vivo en Fortaleza. Hablo portugués y un poco de español.', challenge: 'Diga sua nacionalidade, cidade, onde mora e que línguas fala.', expected: ['soy', 'vivo', 'hablo'],
    },
    writing: {
      prompt: 'Escreva um pequeno perfil para um site de intercâmbio.', criteria: ['Diz a nacionalidade (minúscula)', 'Diz a cidade', 'Diz que línguas fala'],
      model: 'Me llamo Lucas. Soy brasileño, de Belém. Hablo portugués, inglés y un poco de español.', keywords: ['soy', 'hablo'], minWords: 12,
    },
    challenge: 'Escreva a nacionalidade de três pessoas famosas no masculino ou no feminino corretamente.',
    tips: ['Nacionalidade e língua: minúscula.', 'Ser de = origem; vivir en = moradia.'],
  },
  games: {
    blanks: [
      blank(1, 'Ella es ___. (Colombia)', ['colombiana', 'colombiano', 'colombianas', 'Colombiana'], 0, 'Mulher: colombiana (minúscula).'),
      blank(2, 'Ellos son ___. (España)', ['españoles', 'españols', 'españolas', 'español'], 0, 'Masculino plural: españoles.'),
      blank(2, 'Soy de Brasil, pero ___ en Chile.', ['vivo', 'soy', 'hablo', 'llamo'], 0, 'Vivir en = morar em.'),
      blank(3, '¿Qué idiomas ___?', ['hablas', 'eres', 'vives', 'llamas'], 0, 'Hablar idiomas.'),
    ],
    dialogues: [
      dialogue(1, 'No aeroporto', ['Agente: ¿De dónde es usted?', 'Turista: Soy de Brasil.', 'Agente: ¿Habla español?', 'Turista: Sí, un poco.'], 1, ['Soy de Brasil.', 'Me llamo Brasil.', 'Vivo bien.', 'De nada.'], 0, 'Responde-se à origem com “soy de”.'),
      dialogue(2, 'Novo colega', ['Mía: ¿Eres argentino?', 'Joaquín: No, soy uruguayo. Pero vivo en Buenos Aires.', 'Mía: ¡Qué bien! Yo soy chilena.', 'Joaquín: Encantado.'], 1, ['No, soy uruguayo. Pero vivo en Buenos Aires.', 'No, me llamo Joaquín.', 'Sí, tengo doce años.', 'Hablo bien.'], 0, 'Ele corrige a nacionalidade e diz onde mora.'),
    ],
    sequences: [words(1, 'Soy de Brasil y vivo en Recife', 'Soy de (origem) + vivo en (moradia).', 'Organize a frase · Ordena la frase')],
    map: {
      map: 'america-sul', prompt: 'Encontre os países onde se fala espanhol (fronteiras atuais).',
      targets: [
        { id: 'Argentina', label: 'Argentina', clue: 'capital: Buenos Aires', difficulty: 1 },
        { id: 'Uruguay', label: 'Uruguai', clue: 'capital: Montevidéu', difficulty: 2 },
        { id: 'Paraguay', label: 'Paraguai', clue: 'também tem o guarani como língua oficial', difficulty: 2 },
        { id: 'Chile', label: 'Chile', clue: 'país longo e estreito no oceano Pacífico', difficulty: 1 },
        { id: 'Peru', label: 'Peru', clue: 'onde fica Machu Picchu', difficulty: 2 },
        { id: 'Colombia', label: 'Colômbia', clue: 'tem litoral no Pacífico e no Caribe', difficulty: 3 },
      ],
    },
  },
  sources: esSources(),
})
