// Física 1º Médio — LUMI. Cinemática básica.
import { block, fill, lesson, mc, order, tf, SRC, words } from '../dsl'

export const cinemáticaBásica = lesson({
  id: 'fis-1med-cinemática', subject: 'fisica', title: 'Cinemática Básica', levels: ['medio'], grade: '1º Ensino Médio',
  topic: 'Física 1º Médio — Movimento', subtopic: 'Posição, velocidade, aceleração',
  aliases: ['cinemática', 'movimento', 'velocidade', 'aceleração', 'deslocamento'],
  summary: 'Aprenda conceitos fundamentais de movimento: posição, velocidade e aceleração.',
  intro: 'Um carro que viaja a 100 km/h está em movimento. Mas qual é sua posição? Sua velocidade? Como descrevemos tudo isso?',
  objective: 'Entender posição, velocidade média, aceleração e suas fórmulas básicas.',
  prerequisites: [], next: [],
  skills: { g_pos: 'Posição e deslocamento', g_vel: 'Velocidade média', g_acel: 'Aceleração' },
  blocks: [
    block('g_pos', 'Posição e deslocamento',
      'Posição (s) é onde o objeto está. Deslocamento (Δs) é a mudança: Δs = s_final − s_inicial.',
      'Você em casa: s=0 m. Na padaria: s=300 m. Deslocamento: Δs = 300 m.',
      'Posição define localização',
      'Exemplo: carro no km 100, vai ao km 250, volta ao km 100. Deslocamento = 0 km.',
      'Deslocamento é diferença, distância é caminho'),
    block('g_vel', 'Velocidade média',
      'Velocidade média = deslocamento / tempo. Fórmula: v_m = Δs / Δt. Unidades: m/s ou km/h.',
      'Se Δs=100 m e Δt=10 s, então v_m = 10 m/s.',
      'Velocidade é razão entre espaço e tempo',
      'Um carro percorre 120 km em 2 horas: v_m = 60 km/h.',
      'Média não significa velocidade em cada instante'),
    block('g_acel', 'Aceleração',
      'Aceleração = mudança de velocidade / tempo. Fórmula: a = Δv / Δt. Unidade: m/s².',
      'Se v_i=10 m/s, v_f=30 m/s, Δt=5 s, então a = 4 m/s².',
      'Aceleração mede como velocidade muda',
      'Carro acelerando de 0 a 20 m/s em 4 s: a = 5 m/s².',
      'Aceleração negativa = desaceleração (freio)'),
  ],
  questions: [
    mc(1, 'g_pos', 'Um objeto sai de s=50 m e vai a s=150 m. Qual é o deslocamento?', ['50 m', '100 m', '150 m', '200 m'], 1, ['Δs = s_final − s_inicial', 'Δs = 150 − 50 = 100 m', 'Deslocamento é diferença de posição'], '100 m'),
    fill(1, 'g_vel', 'A fórmula de velocidade média é: v_m = Δs / ___', ['Δt'], ['Tempo decorrido', 'Intervalo de tempo', 'Mudança no tempo'], 'v_m = Δs / Δt'),
    mc(1, 'g_acel', 'Um carro acelera de 0 a 30 m/s em 6 segundos. Qual é a aceleração?', ['5 m/s²', '6 m/s²', '36 m/s²', '30 m/s²'], 0, ['a = Δv / Δt', 'a = 30/6 = 5 m/s²', 'Aceleração é mudança de velocidade por tempo'], 'a = 5 m/s²'),
    tf(1, 'g_pos', 'Deslocamento e distância percorrida são sempre iguais.', false, ['Deslocamento é vetorial', 'Distância é sempre positiva', 'Em trajetória com voltas, diferem'], 'Falso: podem ser diferentes.'),
    mc(2, 'g_vel', '90 km/h em m/s é quantos metros por segundo?', ['25 m/s', '30 m/s', '35 m/s', '45 m/s'], 0, ['Dividir por 3,6 para converter', '90 / 3,6 = 25 m/s', 'km/h → m/s divide por 3,6'], '25 m/s'),
    tf(2, 'g_acel', 'Aceleração negativa significa que o objeto está parado.', false, ['Aceleração negativa = desaceleração', 'Ainda há movimento', 'Só significa que velocidade diminui'], 'Falso: ainda há movimento.'),
    order(2, 'g_vel', 'Organize: velocidade média = deslocamento dividido por tempo', ['velocidade', 'média', '=', 'deslocamento', 'dividido', 'por', 'tempo'], ['Ordem lógica', 'Sujeito + verbo + complemento', 'Estrutura correta'], 'velocidade média = deslocamento dividido por tempo'),
    mc(3, 'g_acel', 'Um objeto em repouso tem aceleração de:', ['0 m/s²', 'indefinida', 'infinita', '1 m/s²'], 0, ['Repouso = sem mudança de velocidade', 'Δv = 0, então a = 0', 'Aceleração nula em repouso'], '0 m/s²'),
  ],
  review: ['Posição (s) é localização. Deslocamento (Δs) é mudança.', 'Velocidade média = Δs / Δt', 'Aceleração = Δv / Δt', 'Conversão: ÷3,6 (km/h → m/s)'],
  relatedQuestions: [],
  equivalentQuestions: [],
  commonErrors: ['Confundir deslocamento com distância', 'Usar posição no lugar de deslocamento na fórmula', 'Não converter unidades corretamente'],
  games: {
    pairs: [
      { a: 'posição', b: 'localização no espaço', difficulty: 1 },
      { a: 'deslocamento', b: 'mudança de posição', difficulty: 1 },
      { a: 'velocidade média', b: 'Δs / Δt', difficulty: 2 },
      { a: 'aceleração', b: 'mudança de velocidade / tempo', difficulty: 2 },
    ],
    sequences: [
      words(1, 'Deslocamento é a diferença entre posição final e inicial', 'Δs = s_final − s_inicial'),
      words(2, 'Velocidade média divide deslocamento por tempo', 'v_m = Δs / Δt'),
      words(3, 'Aceleração mede a mudança de velocidade no tempo', 'a = Δv / Δt'),
    ],
  },
  sources: [SRC.bncc('Ciências da Natureza'), SRC.autoral()],
})
