import { block, eqsPt, fill, lesson, mc, tf } from '../dsl'
const F: any[] = []

export const frA2 = lesson({id:'fr-a2',subject:'frances',title:'Français A2',levels:['medio'],grade:'7º',topic:'Français A2',subtopic:'Intermédiaire',aliases:['français','a2','intermédiaire'],summary:'A2: conversations simples.',intro:'Parler couramment.',objective:'Français A2.',next:[],skills:{f:'Fr'},blocks:[block('f','A2','Présent composé. Imparfait. Passé récent. Futur proche. Descriptions au passé. Habitudes. Événements.','-Temps variés.','Narratif.','Melhoria.','1. Qual tempo?'),],questions:[mc(1,'f','Passé?',['composé','simple','próximo'],0,['Avoir/être.','Participe.','Recente']),tf(1,'f','Imparfait: hábitos',true,['Sim.','Repetição','Passado']),fill(1,'f','Futur proche: ___+inf.',['aller'],['Ir.','Próximo','Planejado']),],review:['Temps variés','Narratif','Conversations','Événements'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const frB1 = lesson({id:'fr-b1',subject:'frances',title:'Français B1',levels:['medio'],grade:'8º',topic:'Français B1',subtopic:'Indépendant',aliases:['français','b1','indépendant'],summary:'B1: independent speaker.',intro:'Parler avec confiance.',objective:'Français B1.',next:[],skills:{f:'Fr'},blocks:[block('f','B1','Subjonctif. Conditionnel. Discours indirect. Arguments. Opinions. Débats. Nuances.','-Structures complexes.','Arguments.','Débat.','1. Que estructura?'),],questions:[mc(1,'f','Subjonctif après?',['peur','croyance','désir'],2,['Croire.','Douter.','Vouloir']),tf(1,'f','Conditionnel: hypothèse',true,['Sim.','Si.','Possível']),fill(1,'f','Discours indirect: elle dit que ___.',['elle'],['Pronome.','Transformação','Indirect']),],review:['Subjonctif','Conditionnel','Arguments','Débats'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const frB2 = lesson({id:'fr-b2',subject:'frances',title:'Français B2',levels:['avancado'],grade:'9º',topic:'Français B2',subtopic:'Avancé',aliases:['français','b2','avancé'],summary:'B2: fluent user.',intro:'Maîtriser la langue.',objective:'Français B2.',next:[],skills:{f:'Fr'},blocks:[block('f','B2','Subjonctif passé. Conditionnel passé. Gérondif. Participes. Registros formais. Textos complexos.','-Structurés.','Formels.','Avancé.','1. Qual registro?'),],questions:[mc(1,'f','Subjonctif passé?',['avoir/être+pp','avoir+participe','être+pp'],0,['Anterior.','Passé.','Composé']),tf(1,'f','Gérondif: simultanéité',true,['Sim.','Même temps','Action']),fill(1,'f','En ___ nous parlons.',['gerund'],['En+verb-ing.','Ação.','Simultanée']),],review:['Formes complexes','Registros','Textos','Fluidité'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const frC1 = lesson({id:'fr-c1',subject:'frances',title:'Français C1',levels:['avancado'],grade:'9º',topic:'Français C1',subtopic:'Maîtrise',aliases:['français','c1','maîtrise'],summary:'C1: mastery.',intro:'Expertise totale.',objective:'Français C1.',next:[],skills:{f:'Fr'},blocks:[block('f','C1','Nuances semantiques. Registros hautement sophistiqués. Textos critiques. Rhétorique. Littérature. Style.','-Profond.','Expert.','Maîtrise.','1. O que é C1?'),],questions:[mc(1,'f','Niveau C1?',['Fluent','Maître','Expert'],2,['Complète.','Élégance.','Expertise']),tf(1,'f','C1: textos literários',true,['Sim.','Complexe','Profond']),fill(1,'f','Rhétorique: art de ___.',['persuader'],['Convaincre.','Argumenter','Élegant']),],review:['Maîtrise','Élégance','Littérature','Expertise'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})
