import { block, eqsPt, fill, lesson, mc, order, tf } from '../dsl'
const F: any[] = []

export const coordenadas = lesson({id:'geo-coord',subject:'geografia',title:'Coordenadas Geográficas',levels:['fund1'],grade:'6º',topic:'Geografia',subtopic:'Mapas',aliases:['latitude','longitude','equador','meridiano'],summary:'Latitude + Longitude = localização exata.',intro:'Como GPS funciona?',objective:'Usar coordenadas.',next:[],skills:{v:'Linhas',g:'Coord'},blocks:[block('v','Linhas','Equador: 0° latitude. Meridiano Greenwich: 0° longitude. Paralelos (0-90° N/S). Meridianos (0-180° L/O).','Equador: entre hemisférios.','Latitude: N/S. Longitude: L/O.','Imagina rede.','1. Qual 0°?'),block('g','Coord','Latitude: onde está (norte/sul). Longitude: onde está (leste/oeste). Rio: 22°S 43°O. São Paulo: 23°S 46°O.','Coordenadas = GPS.','Cada lugar único.','Precisão global.','1. Como ler?'),],questions:[mc(1,'v','Equador?',['latitude','longitude','altitude'],0,['Latitude.','0°.','Linha.']),tf(1,'g','Greenwich: 0°',true,['Sim.','Meridiano.','Referência.']),fill(1,'v','Latitude: 0-90° ___.',['N/S'],['Norte.','Sul.','Hemisférios.']),mc(2,'g','Rio: qual?',['22°S','23°N','20°O'],0,['Coordenadas.','Sul.','Oeste.']),order(2,'v','Ordem importância.',['Equador','Meridiano','Paralelos'],['Essencial.','Mapa.','Localização.']),],review:['Equador 0° lat','Greenwich 0° lon','Latitude N/S','Longitude L/O'],relatedQuestions:[],equivalentQuestions:eqsPt(['coordenadas'],[]),commonErrors:[],sources:F,
})

export const continentes = lesson({id:'geo-cont',subject:'geografia',title:'Continentes',levels:['fund1'],grade:'6º',topic:'Geografia',subtopic:'Terra',aliases:['américa','europa','ásia','áfrica','oceania','antártida'],summary:'6 continentes. Âsia maior.',intro:'Qual continente maior?',objective:'Conhecer continentes.',next:[],skills:{v:'Continentes',g:'Océanos'},blocks:[block('v','Continentes','Ásia (44M km²): maior. América (43M). África (30M). Antártida (14M). Europa (10M). Oceania (9M). Brasil: América do Sul.','Ásia: gigante.','América: 2 partes.','Población desigual.','1. Qual maior?'),block('g','Océanos','Pacífico (165M km²): maior. Atlântico (82M). Índico (70M). Ártico (14M). Antártico (20M). Brasil banha: Atlântico.','Pacífico = metade água.','Oceanos cobrem 71%.','Salgada toda.','1. Qual maior?'),],questions:[mc(1,'v','Ásia tamanho?',['44M','30M','20M'],0,[]),tf(1,'g','Pacífico maior',true,[]),fill(1,'v','Brasil: América do ___.',['Sul'],[]),mc(2,'g','Brasil qual oceano?',['Pacífico','Atlântico','Índico'],1,[]),order(2,'v','Tamanho.',['Ásia','América','África'],[],[]),],review:['Ásia maior','Brasil América Sul','Pacífico maior','6 continentes'],relatedQuestions:[],equivalentQuestions:eqsPt(['continentes'],[]),commonErrors:[],sources:F,
})

export const relevo = lesson({id:'geo-relevo',subject:'geografia',title:'Relevo e Biomas',levels:['fund1'],grade:'7º',topic:'Geografia',subtopic:'Terra',aliases:['montanha','planície','planalto','bioma','floresta','cerrado'],summary:'Relevo = forma. Bioma = vida.',intro:'Por que varia tanto?',objective:'Entender relevo+bioma.',next:[],skills:{v:'Relevo',g:'Bioma'},blocks:[block('v','Relevo','Montanha: >1500m. Planalto: 300-1500m. Planície: <300m. Brasil: planaltos+planícies. Altitude reduz temperatura 1° a cada 100m.','Everest: 8848m.','Pico Brasil: Pico da Neblina 3000m.','Relevante tudo.','1. Diferença?'),block('g','Bioma','Tropical: quente+úmido→floresta. Árido: seco→deserto. Temperado: variação→mata. Polar: gelo. Brasil: Amazônia (tropical). Cerrado (tropical seco).','Bioma = clima+flora+fauna.','50% especies mundiais: Brasil.','Interdependência.','1. Qual bioma?'),],questions:[mc(1,'v','Montanha >?',['300m','1500m','3000m'],1,[]),tf(1,'g','Bioma = clima+flora',true,[]),fill(1,'v','Planície: <___ m.',['300'],[]),mc(2,'g','Brasil bioma principal?',['Amazônia','Cerrado','Caatinga'],0,[]),order(2,'v','Altitude.',['Montanha','Planalto','Planície'],[],[]),],review:['Montanha >1500m','Bioma depende clima','Brasil 50% especies','Amazônia tropical'],relatedQuestions:[],equivalentQuestions:eqsPt(['relevo'],[]),commonErrors:[],sources:F,
})

export const populacao = lesson({id:'geo-pop',subject:'geografia',title:'População',levels:['fund1'],grade:'7º',topic:'Geografia',subtopic:'Demografia',aliases:['densidade','censo','migrante','população','urbano'],summary:'8B pessoas. Concentradas.',intro:'Onde mais gente?',objective:'Entender população.',next:[],skills:{v:'Censo',g:'Densidade'},blocks:[block('v','Censo','Censo: contagem cada 10 anos. IBGE Brasil. Pop Brasil: 215M. Taxa crescimento: 1.6% (lenta). Envelhecimento.','2020: último censo Brasil.','Dados importantes.','Planejamento.','1. O que é?'),block('g','Densidade','Densidade: pop/km². Brasil 25 hab/km². São Paulo 1000. Amazonas 2. Mônaco 19000. 90% Brasil: litoral+Sudeste.','Desigual distribuição.','Emprego: atrai.','Oportunidade geográfica.','1. Cálculo?'),],questions:[mc(1,'v','Brasil população?',['150M','215M','250M'],1,[]),tf(1,'g','São Paulo denso',true,[]),fill(1,'v','Densidade = pop ÷ ___.',['área'],[]),mc(2,'g','90% Brasil onde?',['Norte','Litoral','Centro-Oeste'],1,[]),order(2,'v','Densidade.',['Mônaco','São Paulo','Amazonas'],[],[]),],review:['215M Brasil','Censo 10 anos','Densidade 25/km²','90% litoral'],relatedQuestions:[],equivalentQuestions:eqsPt(['população'],[]),commonErrors:[],sources:F,
})
