import { block, eqsPt, fill, lesson, match, mc, order, tf } from '../dsl'

const FONTES = [{ title: 'BNCC Geografia', url: 'http://basenacionalcomum.mec.gov.br/', author: 'MEC', kind: 'instituicao' as const }]

export const coordenadas = lesson({
  id: 'geo-coordenadas', subject: 'geografia', title: 'Coordenadas geográficas', levels: ['fund1'], grade: '4º ano',
  topic: 'Geografia', subtopic: 'Localização e mapas',
  aliases: ['coordenadas', 'latitude longitude', 'equador', 'mapa'],
  summary: 'Aprenda a localizar qualquer lugar da Terra usando linhas imaginárias.',
  intro: 'Linha do Equador, meridianos, paralelos — como funcionam?',
  objective: 'Identificar latitude, longitude e localizar lugares no mapa.',
  next: [],
  skills: { v_linhas: 'Linhas imaginárias', g_coord: 'Latitude e longitude' },
  blocks: [
    block('v_linhas', 'Linhas que dividem o planeta', 'Equador: divide em norte/sul. Meridiano de Greenwich: divide em leste/oeste. Trópicos: Câncer (norte) e Capricórnio (sul).', 'Equador passa pelo Brasil.', 'Hemisfério = metade.', 'Imagine linhas de cebola ao redor da Terra.', '1. Qual é o Equador? 2. Onde fica Greenwich?'),
    block('g_coord', 'Latitude e longitude — coordenadas', 'Latitude: 0° (Equador) até 90° N/S. Longitude: 0° (Greenwich) até 180° L/O. Juntas: endereço exato. Rio: 22°S, 43°O.', 'São Paulo: -23°, -46°.', 'Latitude = norte/sul. Longitude = leste/oeste.', 'Como um GPS do planeta.', '1. O que é latitude? 2. Como ler -23°, -46°?'),
    block('v_linhas', 'Como usar o mapa', 'Escala: 1cm no mapa = quanto na realidade? Rosa-dos-ventos: N, S, L, O. Legenda: símbolos.', '1:100.000 = 1cm = 1km.', 'Escala = proporção.', 'Mapa é versão reduzida.', '1. Que significa escala? 2. Qual é rosa-dos-ventos?'),
  ],
  questions: [
    mc(1, 'v_linhas', 'Qual linha divide norte/sul?', ['Meridiano de Greenwich', 'Equador', 'Trópico', 'Fossa'], 1, ['Divisão norte-sul.', 'Equador.'], 'Equador.'),
    tf(1, 'v_linhas', 'Trópico de Capricórnio passa pelo Brasil.', true, ['Onde passa?', 'Verdadeiro.'], 'Verdadeiro.'),
    fill(1, 'g_coord', 'A medida de norte/sul chama-se ___.', ['latitude'], ['De 0° a 90°.'], 'Latitude.'),
    mc(2, 'g_coord', 'Qual é o meridiano de referência?', ['Equador', 'Greenwich', 'Trópico', 'Pólo'], 1, ['Começa onde?', 'Greenwich.'], 'Greenwich.'),
    match(2, 'v_linhas', 'Ligue cada termo.', [['Escala', 'Proporção'], ['Legenda', 'Símbolos'], ['Rosa-dos-ventos', 'Direções']], ['Cada um ajuda.'], 'Escala-proporção, Legenda-símbolos, Rosa-direções.'),
    mc(1, 'v_linhas', 'Escala 1:100.000, 1cm=?', ['10km', '1km', '100km'], 1, ['Calcule.'], '1km.'),
    order(2, 'v_linhas', 'Ordene N→S.', ['Ártico', 'Câncer', 'Equador', 'Capricórnio'], ['Do norte.'], 'Ártico→Câncer→Equador→Capricórnio.'),
  ],
  review: ['Equador: 0° latitude', 'Greenwich: 0° longitude', 'Latitude 0-90° N/S', 'Longitude 0-180° L/O'],
  relatedQuestions: ['como usar gps', 'qual é meridiano de greenwich'],
  equivalentQuestions: eqsPt(['coordenadas'], ['latitude longitude', 'como localizar mapa', 'equador trópico']),
  commonErrors: ['Confundir latitude com longitude.'],
  sources: FONTES,
})

export const continentes = lesson({
  id: 'geo-continentes', subject: 'geografia', title: 'Continentes e oceanos', levels: ['fund1'], grade: '4º ano',
  topic: 'Geografia', subtopic: 'Divisão da Terra',
  aliases: ['continentes', 'oceanos', 'américa', 'europa', 'ásia'],
  summary: 'Conheça os 6 continentes e 5 oceanos.',
  intro: 'Como a Terra é dividida?',
  objective: 'Identificar continentes e oceanos.',
  next: [],
  skills: { v_cont: 'Continentes', g_oceanos: 'Oceanos' },
  blocks: [
    block('v_cont', 'Os 6 continentes', 'América, Europa, Ásia, África, Oceania, Antártida. Ásia é maior. Brasil na América do Sul.', 'Ásia: 44M km².', 'Continente = terra grande.', 'Ásia é gigante.', '1. Quantos? 2. Qual maior?'),
    block('g_oceanos', 'Os 5 oceanos', 'Pacífico, Atlântico, Índico, Ártico, Antártico. Pacífico é maior (165M km²).', 'Pacífico = 50% água.', 'Oceano = água salgada.', 'Pacífico enorme.', '1. Quantos oceanos? 2. Qual maior?'),
    block('v_cont', 'Brasil no mundo', 'América do Sul. Oceano Atlântico leste. 215 milhões pessoas. Amazônia norte.', 'Maior floresta tropical.', 'Tropical = quente úmido.', 'Brasil privilegiado.', '1. Qual oceano? 2. Qual rio?'),
  ],
  questions: [
    mc(1, 'v_cont', 'Qual continente é maior?', ['Europa', 'América', 'Ásia'], 2, ['Qual maior?'], 'Ásia.'),
    tf(1, 'v_cont', 'Antártida tem cidades.', false, ['Alguém vive?'], 'Falso.'),
    fill(1, 'g_oceanos', 'Maior oceano: ___.', ['Pacífico'], ['165M km².'], 'Pacífico.'),
    mc(2, 'g_oceanos', 'Quantos oceanos?', ['3', '4', '5'], 2, ['Conte.'], '5.'),
    match(2, 'v_cont', 'Ligue.', [['Ásia', 'Maior'], ['Antártida', 'Congelada'], ['Brasil', 'Amazônia']], ['Cada característica.'], 'Ásia-maior, Antártida-congelada, Brasil-Amazônia.'),
    mc(1, 'v_cont', 'Brasil banha em qual oceano?', ['Pacífico', 'Atlântico', 'Índico'], 1, ['Leste?'], 'Atlântico.'),
    order(2, 'v_cont', 'Ordene por tamanho.', ['Ásia', 'América', 'Europa'], ['Maior primeiro.'], 'Ásia→América→Europa.'),
  ],
  review: ['6 continentes: Ásia maior', '5 oceanos: Pacífico maior', 'Brasil: América do Sul, Atlântico'],
  relatedQuestions: ['qual continente maior'],
  equivalentQuestions: eqsPt(['continentes'], ['oceanos', 'brasil mapa']),
  commonErrors: ['Confundir América do Norte com Brasil.'],
  sources: FONTES,
})

export const relevo = lesson({
  id: 'geo-relevo', subject: 'geografia', title: 'Relevo e biomas', levels: ['fund1'], grade: '5º ano',
  topic: 'Geografia', subtopic: 'Formas da Terra',
  aliases: ['relevo', 'montanha', 'planície', 'bioma', 'floresta'],
  summary: 'Entenda relevo e biomas.',
  intro: 'Por que uma região tem montanhas e outra é plana?',
  objective: 'Identificar tipos de relevo e biomas.',
  next: [],
  skills: { v_relevo: 'Relevo', g_clima: 'Clima-bioma' },
  blocks: [
    block('v_relevo', 'Formas da Terra', 'Montanha: >1500m. Planalto: 300-1500m. Planície: <300m. Brasil: planaltos e planícies.', 'Everest: 8848m.', 'Altitude = altura.', 'Bolo com saliências.', '1. Diferença montanha/planalto?'),
    block('g_clima', 'Clima e bioma', 'Tropical→floresta. Árido→deserto. Temperado→mata. Altitude fria.', 'Equador quente, montanha fria.', 'Clima cria bioma.', 'Se muda clima, muda bioma.', '1. Qual clima→deserto?'),
    block('v_relevo', 'Biomas brasileiros', 'Amazônia: floresta tropical norte. Cerrado: savana centro-oeste. 50% espécies mundiais.', 'Cerrado 40% biodiversidade Brasil.', 'Bioma = ecossistema.', 'Brasil tem 2 principais.', '1. Qual bioma norte?'),
  ],
  questions: [
    mc(1, 'v_relevo', 'Montanha tem altitude>?', ['300m', '1500m', '5000m'], 1, ['Qual altura?'], '>1500m.'),
    tf(1, 'v_relevo', 'Everest na Ásia.', true, ['Qual continente?'], 'Verdadeiro.'),
    fill(1, 'g_clima', 'Região tropical quente: clima ___.', ['tropical'], ['Quente úmido.'], 'Tropical.'),
    mc(2, 'g_clima', 'Por que montanha fria?', ['Não virada', 'Altitude reduz temp', 'Sol não chega'], 1, ['Altitude causa frio.'], 'Altitude.'),
    match(2, 'v_relevo', 'Ligue.', [['Tropical', 'Floresta'], ['Deserto', 'Seco'], ['Temperado', 'Mata']], ['Cada clima.'], 'Tropical-floresta, Deserto-seco, Temperado-mata.'),
    mc(1, 'v_relevo', 'Bioma norte Brasil?', ['Cerrado', 'Floresta tropical', 'Caatinga'], 1, ['Amazônia.'], 'Floresta tropical.'),
    order(2, 'v_relevo', 'Ordene altitude.', ['Montanha', 'Planalto', 'Planície'], ['Maior primeiro.'], 'Montanha→Planalto→Planície.'),
  ],
  review: ['Relevo: forma Terra', 'Clima: temp+chuva→bioma', 'Brasil: Amazônia+Cerrado', 'Altitude reduz temperatura'],
  relatedQuestions: ['maior montanha brasil'],
  equivalentQuestions: eqsPt(['relevo'], ['bioma', 'altitude']),
  commonErrors: ['Confundir relevo com clima.'],
  sources: FONTES,
})

export const populacao = lesson({
  id: 'geo-populacao', subject: 'geografia', title: 'População e densidade', levels: ['fund1'], grade: '5º ano',
  topic: 'Geografia', subtopic: 'Demografia',
  aliases: ['população', 'densidade', 'censo', 'hab/km2'],
  summary: 'Aprenda sobre população e densidade demográfica.',
  intro: '8 bilhões de pessoas. Como estão espalhadas?',
  objective: 'Calcular densidade e entender distribuição.',
  next: [],
  skills: { v_pop: 'População', g_densidade: 'Densidade' },
  blocks: [
    block('v_pop', 'Como contar pessoas?', 'Censo: contagem oficial a cada 10 anos. Brasil: IBGE. Taxa crescimento: quanto cresce/ano. Brasil: 1.6% (lento).', 'Brasil: 215M pessoas.', 'Censo = contagem.', 'Vital para cidades.', '1. O que é censo?'),
    block('g_densidade', 'Densidade = pessoas/km²', 'Densidade: população÷área. Brasil: 25 hab/km². São Paulo: 1000 hab/km² (denso). Amazonas: 2 hab/km² (vazio).', 'Mônaco: 19000 hab/km².', 'Hab/km² = densidade.', 'Alta=congestionado.', '1. Como calcular?'),
    block('v_pop', 'Por que aglomeram?', 'Emprego atrai. Água. Clima. Brasil: 90% litoral (emprego, clima). 10% interior (vazio, sem oportunidade).', 'Migração = mudança lugar.', 'Êxodo rural = saída campo.', 'Pessoas buscam oportunidade.', '1. Por que litoral?'),
  ],
  questions: [
    mc(1, 'v_pop', 'O que é censo?', ['Mapa', 'Contagem população', 'Votação'], 1, ['Como contam?'], 'Contagem população.'),
    tf(1, 'g_densidade', 'São Paulo denso (1000 hab/km²).', true, ['Quantas pessoas?'], 'Verdadeiro.'),
    fill(1, 'g_densidade', 'Densidade = ___ ÷ área.', ['população'], ['Quantas pessoas.'], 'População.'),
    mc(2, 'v_pop', 'Fator MAIS atrai população?', ['Frio', 'Emprego', 'Deserto'], 1, ['Onde vão?'], 'Emprego.'),
    match(2, 'v_pop', 'Ligue.', [['Litoral', 'Emprego'], ['SP', 'Economia'], ['Amazonas', 'Vazio']], ['Cada região.'], 'Litoral-emprego, SP-economia, Amazonas-vazio.'),
    mc(1, 'v_pop', '90% população Brasil onde?', ['Interior', 'Norte', 'Litoral+Sudeste'], 2, ['Onde tem gente?'], 'Litoral+Sudeste.'),
    order(2, 'g_densidade', 'Ordene densidade.', ['Mônaco', 'Brasil', 'Groenlândia'], ['Mais denso.'], 'Mônaco→Brasil→Groenlândia.'),
  ],
  review: ['Censo: contagem 10 em 10 anos', 'Densidade: pop÷km² (São Paulo 1000, Brasil 25)', '90% população: litoral+sudeste', 'Emprego atrai; falta água afasta'],
  relatedQuestions: ['população brasil'],
  equivalentQuestions: eqsPt(['população'], ['densidade', 'censo']),
  commonErrors: ['Confundir população total com densidade.'],
  sources: FONTES,
})
