import { block, eqsPt, fill, lesson, mc, order, tf } from '../dsl'
const F: any[] = []

export const climas = lesson({id:'geo-climas',subject:'geografia',title:'Climas do Mundo',levels:['fund1'],grade:'7º',topic:'Geografia',subtopic:'Clima',aliases:['tropical','árido','temperado','polar','subtropical'],summary:'5 tipos clima principais.',intro:'Por que climas variam?',objective:'Conhecer climas mundiais.',next:[],skills:{c:'Clima',t:'Tipos'},blocks:[block('c','Clima','Temperatura + precipitação. Latitude afeta (tropicais=quentes, polares=frios). Altitude afeta (sobe 1km, desce 6°C). Maritimidade afeta (oceano modera).','Clima≠tempo.','Padrão 30 anos.','Múltiplos fatores.','Qual clima?'),block('t','Tipos','Tropical: 25°C+ quente úmido. Árido: <250mm chuva seco. Temperado: 4 estações variação. Subtropical: verão quente inverno suave. Polar: -30°C frio seco. Brasil: tropical + subtropical + árido.','5 tipos principais.','Gradientes latitudinais.','Geografia produz.','Qual existe BR?'),],questions:[mc(1,'c','Latitude alta = ?',['quente','frio','médio'],1,['Polar.','Distante equador.','Eixo terra.']),tf(1,'t','Tropical: úmido quente',true,['Sim.','Equador.','Tipo.']),fill(1,'c','Clima: temperatura + ___.',['precipitação'],['Chuva.','Umidade.','Padrão.']),mc(2,'t','Árido: chuva?',['<100mm','<250mm','<500mm'],1,['Muito seco.','Deserto.','Pouca água.']),order(2,'c','Latitude.',['Polar','Temperado','Tropical'],['Norte/Sul','Equador','Distância.']),],review:['5 climas','Tropical úmido','Árido seco','Latitude+altitude'],relatedQuestions:[],equivalentQuestions:eqsPt(['climas'],[]),commonErrors:[],sources:F,
})

export const recursosnaturais = lesson({id:'geo-recursos',subject:'geografia',title:'Recursos Naturais',levels:['fund1'],grade:'7º',topic:'Geografia',subtopic:'Recursos',aliases:['petróleo','minério','água','floresta','renováveis'],summary:'Renováveis vs não-renováveis.',intro:'O que a Terra oferece?',objective:'Exploração sustentável.',next:[],skills:{r:'Recursos',s:'Sustentabilidade'},blocks:[block('r','Recursos','Renováveis: água, madeira, agricultura (se manejado). Não-renováveis: petróleo, carvão, minério, gás (bilhões anos formar). Ciclos: solar, água, nutrientes.','Finito vs infinito?','Escala humana importa.','Futuro gerações.','Qual tipo?'),block('s','Sustentabilidade','Uso moderado. Recuperação ecossistema. Brasil: Amazônia (renovável se protegida). Biodiversidade. Aquíferos (água doce). Esgotamento risco. Reciclagem mitiga.','Equilíbrio ecológico.','Responsabilidade.','Escolhas hoje.','Como sustentar?'),],questions:[mc(1,'r','Petróleo: qual?',['renovável','não-renovável','inesgotável'],1,['Fóssil.','Bilhões anos.','Fim certo.']),tf(1,'s','Floresta: recurso renovável se protegido',true,['Sim.','Regeneração.','Sustentável.']),fill(1,'r','___ renováveis: água, madeira, agro.',['Recursos'],['Natureza.','Cicla.','Humano respeita.']),mc(2,'s','Amazônia representa?',['irresponsabilidade','destruição','biodiversidade & sustentabilidade'],2,['Brasil.','Vital.','Proteção.']),order(2,'r','Tempo formação.',['Agricultura','Minério','Petróleo'],['Rápido/lento','Renovável','Fóssil.']),],review:['Renováveis/não-renováveis','Petróleo','Floresta','Sustentabilidade'],relatedQuestions:[],equivalentQuestions:eqsPt(['recursos'],[]),commonErrors:[],sources:F,
})

export const economia = lesson({id:'geo-economia',subject:'geografia',title:'Economia e Desenvolvimento',levels:['fund1'],grade:'8º',topic:'Geografia',subtopic:'Economia',aliases:['PIB','desenvolvimento','país rico','país pobre','indústria'],summary:'Economia divide países.',intro:'Por que alguns são ricos?',objective:'Geografias econômicas.',next:[],skills:{d:'Desenvolvimento',i:'Indicadores'},blocks:[block('d','Desenvolvimento','Países desenvolvidos (GDP alto, tecnologia, educação, infraestrutura). Países em desenvolvimento (renda média, industrialização em progresso). Países subdesenvolvidos (GDP baixo, dependência, recursos explorados).','Desigualdade global.','Colonialismo legado.','Acesso tecnologia.','Qual seu país?'),block('i','Indicadores','GDP: renda total país. IDH: desenvolvimento humano (educação+saúde+renda). Industrialização: manufatura%. Urbanização: cidades%. Brasil: em desenvolvimento, IDH médio-alto.','Medição bem-estar.','Comparação internacional.','Progresso mensurável.','Qual indicador?'),],questions:[mc(1,'d','Países desenvolvidos: qual?',['EUA','Brasil','Índia'],0,['GDP alto.','Tecnologia.','Educação.']),tf(1,'i','IDH mede: educação+saúde+renda',true,['Sim.','Desenvolvimento humano.','Holístico.']),fill(1,'d','___ em desenvolvimento: Brasil, México, China.',['Países'],['Renda média.','Industrialização.','Progresso.']),mc(2,'i','GDP= produto ___.',['interno','externo','nacional'],0,['Dentro país.','Bruto.','Anual.']),order(2,'d','Riqueza crescente.',['Subdesenvolvido','Desenvolvimento','Desenvolvido'],['Renda.','GDP.','Progresso.']),],review:['3 categorias país','GDP','IDH','Indicadores desenvolvimento'],relatedQuestions:[],equivalentQuestions:eqsPt(['economia'],[]),commonErrors:[],sources:F,
})

export const cidades = lesson({id:'geo-cidades',subject:'geografia',title:'Urbanização e Cidades',levels:['fund1'],grade:'8º',topic:'Geografia',subtopic:'Urbanização',aliases:['cidade','metrópole','megacidade','favelização','mobilidade'],summary:'Mundo cada vez urbano.',intro:'Mais gente nas cidades.',objective:'Desafios urbanos.',next:[],skills:{u:'Urbanização',c:'Cidades'},blocks:[block('u','Urbanização','1800: 5% urbano. 2024: 56% urbano. Êxodo rural. Concentração grandes cidades. Brasil: 87% urbano. Metrópole (>2M). Megacidade (>10M).','Crescimento acelerado.','Histórico recente.','Fenômeno moderno.','Qual % sua região?'),block('c','Cidades','Oportunidades: emprego, educação, serviços. Desafios: trânsito, poluição, favela, crime, saneamento. São Paulo: 22M. Rio: 13M. Brasília: capital planejada. Sustentabilidade urbana.','Complexidade social.','Planejamento urbano.','Qualidade vida.','Como melhorar?'),],questions:[mc(1,'u','% urbano Brasil hoje?',['45%','65%','87%'],2,['Maioria.','Cidades.','Desenvolvido.']),tf(1,'c','Metrópole: >2M habitantes',true,['Sim.','Definição.','Grande.']),fill(1,'u','Êxodo ___: campo→cidade.',['rural'],['Migração.','Agricultura muda.','Industrialização.']),mc(2,'c','Desafio urbano: qual?',['educação','trânsito+poluição','inovação'],1,['Transporte.','Ar.','Mobilidade.']),order(2,'u','Urbanização histórica.',['1800 (5%)','1900 (14%)','2024 (56%)'],['Crescimento.','Aceleração.','Exponencial.']),],review:['56% urbano','Êxodo rural','Metrópoles','Desafios urbanos'],relatedQuestions:[],equivalentQuestions:eqsPt(['urbanização'],[]),commonErrors:[],sources:F,
})
