import { block, eqsPt, fill, lesson, mc, order, tf } from '../dsl'
const F: any[] = []

export const renascenca = lesson({id:'his-renascenca',subject:'historia',title:'Renascença',levels:['fund1'],grade:'8º',topic:'História',subtopic:'Idade Moderna',aliases:['1300','itália','arte','leonardo','michelangelo'],summary:'1300-1600: retorno à antiguidade.',intro:'Arte, ciência, humanismo.',objective:'Entender Renascença.',next:[],skills:{a:'Arte',h:'Humanismo'},blocks:[block('a','Arte','Pintura: Leonardo, Michelangelo. Escultura: Donatello. Arquitetura: Brunelleschi. Perspectiva linear. Realismo. Proporção.','Realismo novo.','Técnica avançada.','Beleza humana.','Qual pintor?'),block('h','Humanismo','Homem centro universo. Educação clássica. Literatura grega/romana. Renascimento = reflorescência. Fé menos + razão mais.','Antropocentrismo.','Clássicos revistos.','Individuo.','Qual mudança?'),],questions:[mc(1,'a','Leonardo: qual obra?',['Mona Lisa','David','Sistina'],0,['Quadro.','Itália.','Famosa.']),tf(1,'h','Renascença: homem centro',true,['Sim.','Humanismo.','Mudança.']),fill(1,'a','Michelangelo: ___.',['David'],['Escultura.','Itália.','Beleza.']),mc(2,'h','Quando começa?',['1300','1400','1500'],0,['Aproximado.','Itália.','Século 14.']),order(2,'a','Cronologia.',['Leonardo','Michelangelo','Renascença'],['Tempo.','Artistas.','Período.']),],review:['1300-1600','Leonardo/Michelangelo','Humanismo','Realismo'],relatedQuestions:[],equivalentQuestions:eqsPt(['renascença'],[]),commonErrors:[],sources:F,
})

export const iluminismo = lesson({id:'his-iluminismo',subject:'historia',title:'Iluminismo',levels:['fund1'],grade:'8º',topic:'História',subtopic:'Idade Moderna',aliases:['1600','razão','filosofia','voltaire','montesquieu','rousseau'],summary:'1600-1789: Século das Luzes.',intro:'Razão sobre tudo.',objective:'Entender Iluminismo.',next:[],skills:{r:'Razão',f:'Filósofos'},blocks:[block('r','Razão','Razão como verdade. Ciência acima tudo. Método científico. Deus racional (deísmo). Crítica à superstição.','Iluminação mental.','Esclarecimento.','Progresso.','O que ilumina?'),block('f','Filósofos','Voltaire: liberdade expressão. Montesquieu: separação poderes. Rousseau: vontade povo. Diderot: enciclopédia. Descartes: pienso luego existo.','Franceses principalmente.','Ideias novas.','Mudança política.','Qual ideias?'),],questions:[mc(1,'r','Iluminismo: valor?',['fé','razão','tradição'],1,['Ciência.','Método.','Tudo.']),tf(1,'f','Voltaire: liberdade expressão',true,['Sim.','Filósofo.','Crítica.']),fill(1,'r','Método ___: verdade.',['científico'],['Observação.','Experimento.','Prova.']),mc(2,'f','Separação poderes: quem?',['Voltaire','Montesquieu','Rousseau'],1,['3 poderes.','Democracia.','França.']),order(2,'f','Cronologia.',['Descartes','Voltaire','Rousseau'],['Tempo.','Século.','Filosofia.']),],review:['1600-1789','Razão/Ciência','4 filósofos','Ideias políticas'],relatedQuestions:[],equivalentQuestions:eqsPt(['iluminismo'],[]),commonErrors:[],sources:F,
})

export const revolucaoindustrial = lesson({id:'his-revind',subject:'historia',title:'Revolução Industrial',levels:['fund1'],grade:'8º',topic:'História',subtopic:'Idade Contemporânea',aliases:['1760','máquinas','fábricas','trabalho','steam','vapor'],summary:'1760-1840: mecanização.',intro:'Máquinas transformam tudo.',objective:'Entender Revolução Industrial.',next:[],skills:{m:'Máquinas',s:'Sociedade'},blocks:[block('m','Máquinas','Máquina a vapor (Watt). Tecelagem automatizada. Siderurgia. Ferrovias. Produção em série. Fábricas grandes.','Produção explode.','Trabalho muda.','Velocidade nova.','Qual invenção?'),block('s','Sociedade','Êxodo rural: campo→cidade. Proletariado urbano. Jornadas 16h. Crianças trabalham. Cidades poluem. Burguesia cresce. Classe operária nasce.','Urbanização rápida.','Pobreza urbana.','Conflito classe.','Como mudou?'),],questions:[mc(1,'m','Vapor: inventor?',['Watt','Newton','Galileu'],0,['Escocês.','Motor.','Mecânico.']),tf(1,'s','Crianças trabalham nas fábricas',true,['Sim.','Exploração.','Realidade.']),fill(1,'m','Máquina a ___ revoluciona.',['vapor'],['Combustível.','Motor.','Energia.']),mc(2,'s','Êxodo rural = ?',['cidade←campo','fábrica←cidade','campo←fábrica'],0,['Migração.','Campo abandona.','Urbanização.']),order(2,'m','Invenções.',['Máquina a vapor','Tecelagem','Ferrovias'],['Tempo.','Indústria.','Transporte.']),],review:['1760-1840','Máquina a vapor','Industrialização','Proletariado'],relatedQuestions:[],equivalentQuestions:eqsPt(['revolução industrial'],[]),commonErrors:[],sources:F,
})

export const guerrasxxx = lesson({id:'his-guerras',subject:'historia',title:'Contexto das Guerras Mundiais',levels:['fund1'],grade:'9º',topic:'História',subtopic:'Idade Contemporânea',aliases:['1900','imperialismo','nacionalismo','tensão','colonialismo'],summary:'Pré-1914: mundo tenso.',intro:'Rivalidades crescem.',objective:'Entender contexto de guerras.',next:[],skills:{i:'Imperialismo',n:'Nacionalismo'},blocks:[block('i','Imperialismo','Potências européias conquistam colônias (África, Ásia). Recursos. Poder. Rivalidade Europa vs Alemanha. Corrida armamentista. Tensão colonial.','Competição global.','Domínio território.','Riqueza recursos.','Por quê?'),block('n','Nacionalismo','Orgulho nação. Competição entre nações. Militarismo: exército forte. Alianças: Tríplice Aliança (Alemanha-Itália-Áustria) vs Tríplice Entente (França-Rússia-UK).','Fervor patriótico.','Exército & honra.','Blocos opostos.','Qual aliança?'),],questions:[mc(1,'i','Imperialismo: busca?',['colônias','tecnologia','conhecimento'],0,['Recursos.','Poder.','Domínio.']),tf(1,'n','Nacionalismo = orgulho nação',true,['Sim.','Patriotismo.','Potência.']),fill(1,'i','Corrida ___: construir armas.',['armamentista'],['Armas.','Competição.','Militarismo.']),mc(2,'n','Tríplice Entente: qual?',['França-Rússia-UK','Alemanha-Itália-Áustria','Suécia-Noruega-Dinamarca'],0,['Aliança.','Vencedora.','Anti-Alemanha.']),order(2,'i','Tensão crescente.',['Imperialismo','Nacionalismo','1914'],['Sequência.','Competição.','Guerra.']),],review:['Imperialismo','Nacionalismo','Alianças','Conflito europeu'],relatedQuestions:[],equivalentQuestions:eqsPt(['contexto guerras'],[]),commonErrors:[],sources:F,
})
