import { block, eqsPt, fill, lesson, mc, order, tf } from '../dsl'
const F: any[] = []

export const revfrancesa = lesson({id:'his-revfrancesa',subject:'historia',title:'Revolução Francesa',levels:['fund1'],grade:'7º',topic:'História',subtopic:'Revoluções',aliases:['1789','frança','revolução','robespierre','maria antonieta'],summary:'1789: mudou o mundo.',intro:'Bastilha, Liberdade, Igualdade.',objective:'Entender Revolução Francesa.',next:[],skills:{v:'Causas',g:'Eventos'},blocks:[block('v','Causas','Fome. Dívida. Rainha gasta. Povo sem direitos. Iluminismo (igualdade). Ideias de Voltaire, Rousseau.','-1789: povo revoltar.','Causas: econômicas + ideológicas.','Explosão social.','1. Qual causa?'),block('g','Eventos','Bastilha: 14 Jul 1789 (prisão assaltada). Declaração Direitos Humano. Robespierre terror. Napoleão sobe.','-1794: Robespierre guilhotinado.','Terror: 40k mortes.','Mudou Europa.','1. Que foi Robespierre?'),],questions:[mc(1,'v','Ano?',['1789','1776','1815'],0,['1789 França.','Bastilha.','Revolução.']),tf(1,'g','Robespierre: vilão?',true,['Sim.','Terror.','Guilhotina.']),fill(1,'v','Povo queria ___.',['igualdade'],['Direitos.','Liberdade.','Igualdade.']),mc(2,'v','Causa economia ou ideologia?',['economia','ambas'],1,['Ambas.','Fome+ideias.','Iluminismo.']),order(2,'g','Ordem.',['Bastilha','Terror','Napoleão'],['Cronologia.','Sequência.','Tempo.']),],review:['1789 Bastilha','Robespierre terror','Direitos Humanos','Napoleão'],relatedQuestions:[],equivalentQuestions:eqsPt(['revolução'],[]),commonErrors:[],sources:F,
})

export const brasilcolonia = lesson({id:'his-brasilcolonia',subject:'historia',title:'Brasil Colônia',levels:['fund1'],grade:'7º',topic:'História',subtopic:'Brasil',aliases:['1500','cabral','engenho','escravidão','capitanias'],summary:'1500-1822: Brasil português.',intro:'Cabral, engenhos, escravos.',objective:'Entender Brasil Colônia.',next:[],skills:{v:'Descobrimento',g:'Economia'},blocks:[block('v','Descobrimento','1500: Cabral chega. Portugal coloniza. Indígenas + Escravos africanos trabalham. 322 anos colônia.','Cabral: navegador português.','1500 = começo.','Ocupação gradual.','1. Qual ano?'),block('g','Economia','Açúcar: moeda. Engenhos no Nordeste. Escravidão: 5M africanos trazidos. Jesuítas catequizam.','Açúcar: riqueza colonial.','Jesuítas: educação + doutrina.','Exploração brutal.','1. Como gerava renda?'),],questions:[mc(1,'v','Ano chegada?',['1500','1492','1520'],0,['1500.','Cabral.','Descobrimento.']),tf(1,'g','Escravos africanos trabalhavam',true,['Sim.','5M.','Brutal.']),fill(1,'v','___ coloniza Brasil.',['Portugal'],['Metrópole.','Europeu.','Colonizador.']),mc(2,'g','Principal produto?',['ouro','açúcar','café'],1,['Açúcar.','Engenhos.','Nordeste.']),order(2,'v','Ordem.',['Cabral','Engenhos','Jesuítas'],['Tempo.','Sequência.','Cronologia.']),],review:['1500: Cabral','Açúcar: economia','5M escravos','Jesuítas'],relatedQuestions:[],equivalentQuestions:eqsPt(['brasil'],[]),commonErrors:[],sources:F,
})

export const independencia = lesson({id:'his-independencia',subject:'historia',title:'Independência Brasil',levels:['fund1'],grade:'7º',topic:'História',subtopic:'Brasil',aliases:['1822','7 setembro','dom pedro i','grito ipiranga'],summary:'1822: Brasil independente.',intro:'Grito: Independência ou morte!',objective:'Entender independência.',next:[],skills:{v:'Causas',g:'Processo'},blocks:[block('v','Causas','Ideias americanas (USA 1776). França revolucionária. Burguesia brasileira quer poder. Portugal enfraquece. Revoluções e descontentamento.','-Inconfidência Mineira (1789): conspiração.','Ideias iluministas.','Ouro português não chegava.','1. Qual influência?'),block('g','Processo','1821: Dom João retorna Lisboa. Dom Pedro fica regente. 7 Set 1822: Grito Ipiranga. Brasil: Império. Monarquia +Escravidão (até 1888).','-7 Set = data oficial.','Grito simbólico.','Monarquia 67 anos.','1. Quem foi regente?'),],questions:[mc(1,'v','Influência?',['francesa','americana','inglesa'],1,['Revolução.','Ideias.','França.']),tf(1,'g','7 setembro: independência',true,['Sim.','Ipiranga.','Grito.']),fill(1,'g','Grito: Independência ou ___.',['morte'],['Ou morte.','Liberdade.','Dom Pedro.']),mc(2,'v','Quem conspirou 1789?',['Mineiros','Paulistas','Cariocas'],0,['Minas.','Inconfidência.','1789.']),order(2,'g','Cronologia.',['1821','1822','1888'],['Tempo.','Sequência.','Período.']),],review:['1822: independência','Dom Pedro I','7 setembro','Escravidão até 1888'],relatedQuestions:[],equivalentQuestions:eqsPt(['brasil'],[]),commonErrors:[],sources:F,
})

export const segundaguerra = lesson({id:'his-segundaguerra',subject:'historia',title:'Segunda Guerra Mundial',levels:['fund1'],grade:'8º',topic:'História',subtopic:'Século XX',aliases:['1939','hitler','holocausto','aliados','eixo'],summary:'1939-1945: guerra total.',intro:'Hitler, Mussolini, Hirohito.',objective:'Entender WWII.',next:[],skills:{v:'Causas',g:'Consequências'},blocks:[block('v','Causas','Revanchismo Alemanha (Versalhes 1919). Hitler sobe (1933). Fascismo Itália+Japão. Eixo (Alemanha-Itália-Japão) vs Aliados (EUA-URSS-Reino Unido-França).','Hitler: vingança.','Fascismo = totalitarismo.','Expansão territorial.','1. Qual conflito?'),block('g','Consequências','Holocausto: 6M judeus mortos. 80M mortos total. Bomba atômica: Hiroshima+Nagasaki (1945). ONU fundada. Mundo dividido: Guerra Fria.','1945: Alemanha+Japão rendem.','Holocausto: maior genocídio.','Mundo muda.','1. Quantos morreram?'),],questions:[mc(1,'v','Ano início?',['1939','1945','1933'],0,['1939.','Guerra.','Eixo.']),tf(1,'g','Holocausto: 6M judeus',true,['Sim.','Genocídio.','Nazi.']),fill(1,'v','___ + Itália + Japão = Eixo.',['Alemanha'],['Potências.','Fascismo.','Aliança.']),mc(2,'g','Bomba atômica?',['Hitler','Japão','Itália'],1,['Hiroshima.','1945.','EUA.']),order(2,'v','Cronologia.',['Versalhes','Hitler','WWII'],['Tempo.','Sequência.','Período.']),],review:['1939-1945 WWII','Eixo vs Aliados','Holocausto 6M','Bomba atômica'],relatedQuestions:[],equivalentQuestions:eqsPt(['guerra'],[]),commonErrors:[],sources:F,
})
