// Curso de História — Acervo (Lote 4). Aulas estruturadas com HistoryInfo. Conteúdo original.
import { block, eqsPt, fill, lesson, match, mc, order, tf } from '../dsl'

const ALL = ['fund1', 'fund2', 'medio'] as const

// ═══════════════════ Revolução Francesa ═══════════════════
export const revolucaoFrancesa = lesson({
  id: 'his-revolucao-francesa', subject: 'historia', title: 'A Revolução Francesa (1789–1799)', levels: [...ALL], grade: 'A partir do 7º ano',
  topic: 'História — Revoluções', subtopic: 'Revolução Francesa, iluminismo e mudanças sociais',
  aliases: ['revolução francesa', '1789', 'bastiha', 'napoleão', 'maria antonieta', 'queda da bastilha'],
  summary: 'Conheça o movimento que transformou a Europa: as causas, os principais eventos, as figuras centrais e o impacto na história.',
  intro: 'Em 1789, a França vivia uma crise. O povo estava farto de impostos, fome e falta de liberdade. Uma revolução explodiu — e mudou o mundo.',
  objective: 'Entender as causas da Revolução Francesa, identificar seus principais eventos e personagens, e reconhecer seu impacto na história moderna.',
  next: ['his-brasil-colonia'],
  skills: { v_causas: 'Causas da revolução', g_eventos: 'Fases e eventos principais', s_figuras: 'Personagens centrais', v_impacto: 'Legado e impactos' },
  blocks: [
    block('v_causas', 'Por que a revolução aconteceu?',
      'A França do século XVIII era controlada pela nobreza e clero, enquanto povo (99%) pagava impostos altos e passava fome. O Iluminismo (Voltaire, Rousseau, Montesquieu) espalhava ideias de igualdade, liberdade e justiça. A dívida do Estado era imenso. O povo pediu mudança.',
      'Voltaire: "Todos são iguais". Rousseau: "Poder vem do povo". O povo francês: "Queremos pão e liberdade".',
      'Iluminismo = movimento das ideias. Nobreza = aristocracia que governa. Clero = Igreja que também tinha poder e riqueza.',
      'Imagine uma escola onde 1% dos alunos governa, 99% paga tudo, e um livro novo diz que todos devem ter voz. O que aconteceria?',
      '1. Veja a injustiça. 2. Conheça as ideias novas. 3. Entenda o desespero do povo.',
      'O Iluminismo plantou a semente, mas a fome e os impostos fizeram a revolução crescer.'),
    block('g_eventos', 'Os grandes eventos: 1789 a 1799',
      '1789: Queda da Bastilha (prisão atacada pelo povo — símbolo do poder real). Declaração dos Direitos do Homem: "liberdade, igualdade, fraternidade". 1792: Monarquia acabada. 1793: Execução de Luís XVI e Maria Antonieta (guilhotina). 1794: "Terror" (perseguição aos adversários). 1799: Napoleão sobe ao poder e encerra a revolução.',
      'Bastilha → Declaração → Monarquia cai → Rei e rainha executados → Terror → Napoleão',
      'Bastilha = fortaleza-prisão. Guilhotina = máquina de execução. Revolução = mudança radical de governo e sociedade.',
      'Cada grande evento mudou quem tinha poder: primeiro tirou o poder real absoluto, depois o da nobreza, depois entrou o Terror.',
      '1. 1789: Povo ataca e conquista. 2. 1792: Sem rei. 3. 1793: Morte do rei. 4. 1799: Novo líder (Napoleão) toma o poder.',
      'A revolução durou 10 anos e passou por fases muito diferentes — do otimismo inicial ao Terror muito violento.'),
    block('s_figuras', 'Quem foi quem?',
      'Voltaire e Rousseau (filósofos do Iluminismo): espalharam ideias. Luís XVI (rei): fraco, deixou a situação piorar. Maria Antonieta (rainha): vista como luxuosa e fria enquanto povo sofria. Robespierre: líder durante o Terror, executou milhares. Napoleão Bonaparte: militar que tomou poder e reorganizou a França.',
      'Voltaire: "A perfeição é inimiga do bem." Rousseau: "O homem nasce livre." Robespierre: "Virtude sem terror é fraca." Napoleão: "Sou o destino da França."',
      'Filósofo = pensador. Aristocrata = nobre. General = militar. Ditador = governa sozinho, sem democracia.',
      'Voltaire criticava a Igreja e a injustiça desde antes da revolução. Napoleão usou o caos para se tornar poder absoluto (irônico).',
      '1. Filósofos preparam as ideias. 2. Rei e rainha falham em governar. 3. Robespierre leva violência ao extremo. 4. Napoleão aproveita e toma tudo.',
      'Robespierre é controverso: combateu a injustiça mas matou inocentes. Napoleão é admirado estrategista mas também ditador.'),
    block('v_impacto', 'Que legado deixou?',
      'Ideias: "liberdade, igualdade, fraternidade" mudou o mundo — inspirou revoluções em outros países. Fim da monarquia absoluta (gradualmente). Fim do feudalismo na Europa. Direitos do Homem: conceito novo, radical na época. Educação: começou a ser vista como direito, não privilégio. Cultura: música, arte, literatura refletem o espírito revolucionário.',
      'Revolução Francesa → inspirou EUA, América do Sul, Europa inteira. Hoje: direitos humanos, constituições, voto — tudo tem raiz aqui.',
      'Monarquia absoluta = rei tem poder total, sem limite. Direitos Humanos = conjunto de garantias básicas para todo ser humano.',
      'A Revolução Francesa é o ponto de virada: antes dela, o mundo era de reis; depois dela, as ideias de igualdade não morreram mais.',
      '1. Novas ideias espalharam. 2. Outros países se inspiraram. 3. Sociedade mudou para sempre.',
      'Mesmo com seus extremos (o Terror), a Revolução Francesa foi um divisor de águas — marcou o fim da Idade Moderna e o começo do mundo contemporâneo.'),
  ],
  questions: [
    mc(1, 'v_causas', 'Qual foi a PRINCIPAL razão para a revolução?', ['Invasão estrangeira', 'Crise econômica, fome e falta de liberdade', 'Morte do rei', 'Volta da peste negra'], 1, ['Pense no que o povo sofria.', 'Injustiça, impostos altos, fome.', 'Crise econômica.'], 'A crise econômica e a injustiça social.'),
    tf(1, 'v_causas', 'O Iluminismo foi uma causa direta da Revolução Francesa.', true, ['As ideias novas prepararam o caminho.', 'Voltaire e Rousseau inspiraram o povo.', 'Mas sozinho não teria bastado — era preciso fome também.'], 'Verdadeiro: sem as ideias do Iluminismo, provavelmente não haveria revolução.'),
    fill(1, 'g_eventos', 'A queda da ___ em 1789 foi o primeiro grande evento da Revolução.', ['Bastilha'], ['Fortaleza-prisão atacada pelo povo.', 'Símbolo do poder real.', 'Bastilha.'], 'Bastilha = prisão real, símbolo de opressão.'),
    mc(2, 'g_eventos', 'Em que ano o rei Luís XVI foi executado?', ['1789', '1792', '1793', '1799'], 2, ['Depois que a monarquia caiu (1792).', 'Na fase do Terror.', '1793.'], '1793 — durante o período conhecido como "Terror".'),
    match(2, 's_figuras', 'Ligue cada pessoa ao seu papel.', [['Voltaire', 'Filósofo do Iluminismo'], ['Luís XVI', 'Rei fraco'], ['Robespierre', 'Líder do Terror'], ['Napoleão', 'Militar que tomou o poder']], ['Personagens centrais na revolução.', 'Cada um teve um papel diferente.', 'Combine corretamente.'] as const, 'Voltaire-filósofo, Luís XVI-rei, Robespierre-terror, Napoleão-poder.'),
    mc(2, 'v_impacto', 'Qual foi o maior legado da Revolução Francesa para o mundo?', ['Napoleão conquistou toda a Europa', 'As ideias de liberdade, igualdade e direitos humanos', 'A França virou rica', 'Todos ficaram felizes'], 1, ['Algo que mudou a história.', 'Uma ideia que permaneceu.', 'Direitos Humanos.'], 'As ideias de liberdade e direitos humanos — que inspiraram o mundo.'),
    mc(3, 's_figuras', 'Por que Napoleão é controverso na história?', ['Porque era francês', 'Porque trouxe ordem mas também era ditador', 'Porque inventou a guilhotina', 'Porque era amigo de Robespierre'], 1, ['Ele foi heroico e vilão.', 'Parou o Terror mas governou sozinho.', 'É complicado.'], 'Napoleão era estrategista brilhante, mas também impôs um governo ditatorial.'),
    order(2, 'g_eventos', 'Coloque os eventos em ordem cronológica.', ['Queda da Bastilha (1789)', 'Execução do rei (1793)', 'Fim da monarquia (1792)', 'Napoleão sobe ao poder (1799)'], ['1789 é quando começa.', 'Depois vem 1792, 1793, 1799.', 'Do começo ao fim.'], '1789 → 1792 → 1793 → 1799.'),
    tf(3, 'v_impacto', 'A Revolução Francesa foi o fim da Idade Moderna e marca o começo do mundo contemporâneo.', true, ['Marcou um ponto de virada na história.', 'Antes: reis. Depois: direitos humanos.', 'Verdadeiro.'], 'Verdadeiro: historiadores marcam a Revolução Francesa como divisor de águas.'),
  ],
  review: ['Causas: injustiça, impostos, fome, Iluminismo', 'Eventos: 1789 Bastilha → 1792 sem rei → 1793 execução → 1799 Napoleão', 'Figuras: Voltaire (ideias), Luís XVI (rei fraco), Robespierre (Terror), Napoleão (ordem ditatorial)', 'Legado: direitos humanos, fim do feudalismo, inspirou revoluções mundo afora'],
  relatedQuestions: ['por que a revolução francesa começou', 'quem foi napoleão', 'o que é iluminismo', 'quando terminou a revolução francesa'],
  equivalentQuestions: eqsPt(['revolução francesa', '1789', 'bastilha'], ['por que a francesa teve revolução', 'qual era a vida do povo na frança', 'o que voltaire pensava', 'maria antonieta foi justa', 'por que guilhotina', 'quando começou a revolução', 'como terminou a revolução', 'napoleão foi bom ou ruim']),
  commonErrors: ['Achar que Napoleão era lado bom da revolução (foi, mas depois virou ditador).', 'Confundir Revolução Francesa com Revolução Americana.', 'Não entender que o Terror era parte dela.'],
  games: {
    blanks: [
      { difficulty: 1, sentence: 'A ___ foi atacada e destruída em 1789.', options: ['Bastilha', 'Catedral', 'Palácio', 'Ponte'], answer: 0, explanation: 'Bastilha era o símbolo do poder do rei.' },
      { difficulty: 1, sentence: 'A Declaração dos ___ proclamava liberdade, igualdade e fraternidade.', options: ['Deuses', 'Direitos do Homem', 'Reis', 'Soldados'], answer: 1, explanation: 'Direitos do Homem foi o documento fundamental.' },
      { difficulty: 2, sentence: '___ foi o filósofo que criticava a Igreja e defendia liberdade de pensamento.', options: ['Voltaire', 'Napoleão', 'Robespierre', 'Luís XVI'], answer: 0, explanation: 'Voltaire foi um dos maiores críticos da Igreja.' },
      { difficulty: 2, sentence: 'O ___ foi o período mais violento da revolução, com execuções em massa.', options: ['Renascença', 'Terror', 'Iluminismo', 'Romantismo'], answer: 1, explanation: 'O Terror (1793-1794) foi liderado por Robespierre.' },
      { difficulty: 3, sentence: '___ terminou a Revolução Francesa e se tornou Imperador.', options: ['Voltaire', 'Robespierre', 'Napoleão', 'Maria Antonieta'], answer: 2, explanation: 'Napoleão tomou o poder em 1799 (18 Brumário).' },
    ],
  },
  sources: [
    { title: 'Revolução Francesa', url: 'https://pt.wikipedia.org/wiki/Revolu%C3%A7%C3%A3o_Francesa', author: 'Wikipédia', kind: 'instituicao' },
    { title: 'O Iluminismo', url: 'https://www.britannica.com/event/Enlightenment', author: 'Britannica', kind: 'instituicao' },
  ],
})

export const brasilColonia = lesson({
  id: 'his-brasil-colonia', subject: 'historia', title: 'Brasil Colônia (1500–1822)', levels: [...ALL], grade: 'A partir do 6º ano',
  topic: 'História — Período Colonial', subtopic: 'Descobrimento, exploração e vida colonial',
  aliases: ['brasil colonia', '1500', 'pedro alvares cabral', 'ciclo do açúcar', 'escravidão no brasil', 'indios brasil', 'jesuitas'],
  summary: 'Dos primeiros europeus até a independência: como o Brasil era explorado, quem vivia aqui, e como terminou a colonização.',
  intro: 'Em 1500, Cabral chegou ao Brasil. O que veio depois? Séculos de exploração, escravidão e transformação. Uma história que ainda nos marca.',
  objective: 'Entender o período colonial: exploração de recursos, escravidão, conflitos com indígenas, e como a colônia virou nação.',
  prerequisites: [],
  next: ['his-independencia-brasil'],
  skills: { v_descobrimento: 'Primeiros contatos europeus', g_economia: 'Ciclos econômicos (açúcar, ouro, café)', s_sociedade: 'Vida colonial e desigualdade', v_fim: 'Caminhos para a independência' },
  blocks: [
    block('v_descobrimento', 'Descobrimento ou invasão?',
      '1500: Pedro Álvares Cabral chega. "Descobrimento" do ponto de vista europeu. Mas indígenas já viviam aqui há milhares de anos! Inicialmente, contato relativamente pacífico. Depois, conflitos, doenças, escravização. A palavra "descobrimento" é controversa — seria "invasão" ou "encontro"?',
      'Cabral desembarca em Porto Seguro. Indígenas chegam em canoas, curiosos. Europeus veem ouro, madeira, trocam miçangas por ouro.',
      'Indígenas = povos originários. Colonizadores = europeus. Descobrimento = termo eurocêntrico (ponto de vista europeu).',
      'Quando você "descobre" um lugar já habitado, é descobrimento para quem?',
      '1. Quem estava aqui primeiro? 2. O que os europeus encontraram? 3. Como era a vida indígena antes?',
      'O termo "descobrimento" reflete a perspectiva europeia. Historiadores modernos preferem "encontro" ou "invasão" para ser mais justo.'),
    block('g_economia', 'Ciclos econômicos: o que explorava cada época',
      'Século XVI: Pau-brasil (madeira valiosa na Europa). Século XVII–XVIII: Açúcar (grandes plantações, trabalho escravo). Século XVIII: Ouro (Minas Gerais, muita riqueza). Século XIX: Café (São Paulo, maior ciclo). Cada ciclo deixava escravizados, devastação ambiental e desigualdade.',
      'Pau-brasil → Açúcar → Ouro → Café. Cada um enriquecia Portugal e donos de terras, mas escravizava africanos e indígenas.',
      'Ciclo = período de produção de um produto. Escravidão = o maior custo humano de cada ciclo.',
      'O Brasil era colônia para europeus ficar ricos. Os lucros iam para Portugal, os custos (sofrimento, morte) ficavam aqui.',
      '1. Qual era o principal produto? 2. Quem lucrava? 3. Quem sofria?',
      'A economia colonial era extrativista — tirava recursos, não desenvolveu indústria local. Por isso o Brasil continuou pobre e desigual mesmo sendo rico em recursos.'),
    block('s_sociedade', 'A pirâmide social colonial',
      'No topo: Coroa portuguesa e padres. Depois: colonos ricos (donos de fazendas, engenhos de açúcar). Depois: pequenos agricultores, artesãos. Na base: indígenas escravizados, africanos escravizados (trazidos em navios negreiros). A maioria do Brasil era escravizada. Mulatos e mestiços ocupavam posições intermediárias mas com direitos limitados.',
      'Dona do engenho de açúcar: toma todo o lucro. Escravizado de origem africana: trabalha até morrer. Diferença brutal.',
      'Escravidão = trabalho forçado sem direitos. Negreiros = navios que traziam escravizados da África.',
      'Uma sociedade onde 90% era escravizada ou semi-livre é o contrário de justiça.',
      '1. Quem era no topo? 2. Quem estava na base? 3. Como vivia quem era escravizado?',
      'A sociedade colonial era extremamente desigual. Isso deixou cicatrizes que o Brasil carrega até hoje (racismo, desigualdade).'),
    block('v_fim', 'Como acabou a colonização?',
      'Portugal enfraquecia (Napoleão invadiu). Brasil ganhava importância (ouro, café). 1808: Corte portuguesa se muda para o Rio. 1821: Rei volta a Portugal, deixa filho aqui. 1822: Dom Pedro I declara independência. Mas atenção: independência não significou fim da escravidão (continuou até 1888) nem democracia — virou império depois república.',
      '1808: Corte chega. 1821: Rei vai embora, filho fica. 1822: "Independência ou morte!" — Brasil fica livre politicamente mas não socialmente.',
      'Independência = liberdade política de colonizador. Mas escravizados continuaram escravizados — essa é a contradição do Brasil.',
      'Imagine virar "independente" mas seus vizinhos continuarem escravizados. É isto o Brasil em 1822.',
      '1. Qual foi o gatilho? 2. Quem declarou? 3. O que mudou realmente?',
      'A independência brasileira foi política, não social. A escravidão, o preconceito, a desigualdade continuaram — por isso o Brasil tem essas feridas até hoje.'),
  ],
  questions: [
    mc(1, 'v_descobrimento', 'Em que ano Cabral chegou ao Brasil?', ['1498', '1500', '1510', '1520'], 1, ['Primeiros anos do século XVI.', 'Virada de século.', '1500.'], '1500 — marcado como o ano do "descobrimento".'),
    tf(1, 'v_descobrimento', '"Descobrimento" é o termo mais justo para chamar a chegada dos europeus ao Brasil.', false, ['Do ponto de vista de quem?', 'Indígenas já estavam aqui.', 'Seria "invasão" ou "encontro" mais justo.'], 'Falso: o termo "descobrimento" reflete visão eurocêntrica. Hoje preferimos "invasão" ou "encontro".'),
    fill(1, 'g_economia', 'O primeiro ciclo econômico da colônia foi o do ___-brasil.', ['pau'], ['Madeira valiosa.', 'Século XVI.', 'Pau-brasil.'], 'Pau-brasil foi explorado massivamente no século XVI.'),
    mc(2, 'g_economia', 'Qual ciclo econômico trouxe mais riqueza mas também escravidão massiva?', ['Pau-brasil', 'Açúcar', 'Ouro', 'Café'], 1, ['Maior escravidão foi no século XVII-XVIII.', 'Ciclo que virou engenho.', 'Açúcar.'], 'Açúcar: com ele vieram os engenhos, os escravizados e a riqueza.'),
    match(2, 's_sociedade', 'Ligue cada grupo ao seu papel na colônia.', [['Coroa portuguesa', 'Toma as decisões do topo'], ['Donos de engenho', 'Ficam ricos com trabalho escravo'], ['Indígenas e africanos', 'Escravizados, trabalham até morrer'], ['Padres jesuitas', 'Catequizam indígenas']], ['Quem manda?', 'Quem lucra?', 'Quem sofre?', 'Quem converte?'], 'Coroa-manda, Donos-lucram, Escravizados-sofrem, Jesuitas-catequizam.'),
    mc(2, 's_sociedade', 'Qual era o grupo MAIS numeroso na sociedade colonial?', ['Europeus livres', 'Africanos livres', 'Escravizados de origem africana e indígena', 'Padres'], 2, ['Quem era maioria?', '90% da população.', 'Escravizados.'], 'Escravizados: 90% da população colonial era escravizada ou semi-livre.'),
    mc(3, 'v_fim', 'O que evento em 1822 marca o fim da colônia?', ['Morte do rei', 'Independência declarada por Dom Pedro I', 'Abolição da escravidão', 'Proclamação da república'], 1, ['Mudança política.', 'Brasil deixa de ser colônia.', '1822.'], 'Declaração de independência de Dom Pedro I — "Independência ou morte!".'),
    tf(3, 'v_fim', 'Após 1822, a escravidão acabou imediatamente.', false, ['Independência significou liberdade para escravizados?', 'Não, continuou até 1888.', 'Falso.'], 'Falso: escravidão continuou até 1888. Independência política ≠ liberdade social.'),
    order(2, 'g_economia', 'Coloque os ciclos econômicos em ordem.', ['Pau-brasil', 'Açúcar', 'Ouro', 'Café'], ['Século XVI.', 'XVII-XVIII.', 'XVIII.', 'XIX.'], 'Pau-brasil (XVI) → Açúcar (XVII-XVIII) → Ouro (XVIII) → Café (XIX).'),
  ],
  review: ['1500: Cabral chega; indígenas já viviam aqui há milhares de anos', 'Ciclos econômicos: pau-brasil → açúcar → ouro → café', 'Sociedade: Coroa e padres no topo, escravizados na base (90% da população)', '1822: Independência política, mas escravidão continuou até 1888'],
  relatedQuestions: ['quem descobriu o brasil', 'por que havia escravidão no brasil', 'como era a vida no brasil colônia', 'quando o brasil virou independente'],
  equivalentQuestions: eqsPt(['brasil colonia', '1500', 'cabral'], ['o que cabral fez no brasil', 'como era a escravidão no brasil', 'qual era a economia da colônia', 'por que havia portugueses no brasil', 'quem era indígena', 'quando entrou africano no brasil', 'por que brasil virou rico e pobre ao mesmo tempo']),
  commonErrors: ['Achar que 1822 acabou com escravidão (continuou até 1888).', 'Chamar "descobrimento" sem questionar (invasão é mais justo).', 'Não entender que desigualdade colonial vira desigualdade moderna.'],
  english: {
    cefr: '—', unit: 'his-u1', order: 2, area: 'history',
    vocabulary: [
      { word: 'colonia', translation: 'colony', pos: 'noun', definition: 'território sob controle de outro país', example: 'Brasil foi colônia de Portugal por 322 anos.', difficulty: 1 },
      { word: 'escravizado', translation: 'enslaved person', pos: 'noun', definition: 'pessoa forçada a trabalhar sem direitos ou liberdade', example: 'Milhões de africanos foram escravizados no Brasil.', difficulty: 2 },
      { word: 'engenho', translation: 'sugar mill', pos: 'noun', definition: 'fábrica de açúcar com terras ao redor', example: 'O engenho era o coração da economia.', difficulty: 2 },
      { word: 'ciclo econômico', translation: 'economic cycle', pos: 'phrase', definition: 'período em que um produto domina a economia', example: 'O ciclo do café durou um século.', difficulty: 2 },
      { word: 'navio negreiro', translation: 'slave ship', pos: 'phrase', definition: 'embarcação que trazia escravizados da África', example: 'Navios negreiros causaram morte de milhões.', difficulty: 2 },
    ],
    history: {
      period: '1500–1822',
      timeline: [
        { date: '1500', event: 'Pedro Álvares Cabral chega; "descobrimento"' },
        { date: '1504', event: 'Primeiros europeus começam exploração do pau-brasil' },
        { date: '1532', event: 'Primeira vila (São Vicente); início de colonização sistemática' },
        { date: '1580', event: 'Portugal enfraquece; Brasil ameaçado por invasores' },
        { date: '1630–1654', event: 'Holandeses invadem Pernambuco' },
        { date: '1693', event: 'Ouro descoberto em Minas Gerais; novo ciclo econômico' },
        { date: '1750–1850', event: 'Café substitui ouro como principal produto' },
        { date: '1822', event: 'Dom Pedro I declara independência' },
        { date: '1888', event: 'Abolição da escravidão' },
      ],
    },
  },
})

export const independenciaBrasil = lesson({
  id: 'his-independencia-brasil', subject: 'historia', title: 'Independência do Brasil (1808–1822)', levels: [...ALL], grade: 'A partir do 7º ano',
  topic: 'História — Período de Transição', subtopic: 'Movimentos de independência, Dom Pedro I e formação do Estado',
  aliases: ['independência brasil', 'dom pedro', '1822', 'grito do ipiranga', 'josé bonifácio', 'portugal brasil'],
  summary: 'Como o Brasil saiu do controle português: os eventos, os personagens e as consequências de 1822.',
  intro: '1822: "Independência ou morte!" — com essa frase, Dom Pedro I separa o Brasil de Portugal. Mas como chegamos até aqui?',
  objective: 'Entender como e por que o Brasil se tornou independente, quem foram os personagens centrais, e o que mudou após 1822.',
  prerequisites: ['his-brasil-colonia'],
  next: [],
  skills: { v_contexto: 'Contexto europeu e situação do Brasil', g_atores: 'Dom Pedro I, José Bonifácio e outros', s_processo: 'Processo de separação', v_impacto: 'Monarquia, escravidão e desigualdade após 1822' },
  blocks: [
    block('v_contexto', 'Por que Portugal perdeu o Brasil?',
      'Portugal enfraquecia na Europa. Napoleão invadia. 1808: Corte portuguesa foge para o Brasil (único vice-reino que recebeu a Coroa real). Brasil fica importante. 1814: Napoleão cai, mas Corte não volta. 1821: Rei volta a Lisboa, deixa filho. Brasileiro: por que continuamos colônia se a Corte saiu? Europeu: por que pays imposto se temos liberdade? Conflito.',
      'João VI foge em 1808 com 15 mil pessoas. Deixa filho Dom Pedro em 1821. Filho quer independência, pai quer colônia de novo.',
      'Vice-reino = território governado por vice-rei no lugar do rei. Napoleão = invasor francês que mexeu com toda a Europa.',
      'Se a Coroa vivia aqui, por que continuávamos colônia? A lógica não fazia mais sentido.',
      '1. Por que Portugal ficou fraco? 2. O que mudou quando Corte saiu? 3. Por que conflito?',
      'A fuga da Corte para o Brasil foi o ponto de virada — tornou o Brasil importante demais para continuar colônia.'),
    block('g_atores', 'Os personagens da independência',
      'Dom Pedro I (herdeiro do trono): jovem, casado com Leopoldina (filha de príncipe austríaco), influenciado por ideia de independência. José Bonifácio de Andrada e Silva (político e cientista): conselheiro de Dom Pedro, verdadeiro estrategista da independência. Leopoldina: apoiava Dom Pedro. Maria Leopoldina: mãe de Dom Pedro I que influenciou. Abdicação de João VI em Dom Pedro ofereceu legitimidade monárquica à independência.',
      'José Bonifácio: "Olhe para a Europa, Dom Pedro. Seu pai quer te prender a colônia. Você pode ser imperador aqui."',
      'Herdeiro = príncipe. Estrategista = quem planeja. Legitimidade = direito reconhecido de governar.',
      'Dom Pedro tinha poder, Bonifácio tinha ideia. Juntos conseguiram independência sem guerra civil como em outras américas.',
      '1. Quem era Dom Pedro? 2. Quem o aconselhou? 3. Por que conseguiram fazer isso sem muito derramamento de sangue?',
      'Diferente de outras independências na América, Brasil separou-se de Portugal sem revolução violenta — o príncipe herdeiro simplesmente declarou.'),
    block('s_processo', 'Como aconteceu a separação?',
      '1821: Rei volta para Portugal, deixa Dom Pedro como "Príncipe Regente". Cortes Portuguesas exigem que Brasil volta ao status de colônia. Brasil quer liberdade. Setembro de 1822: Carta de João VI chega, ordenando Dom Pedro voltar a Portugal. 7 de setembro: Dom Pedro, às margens do Rio Ipiranga, rasga a carta. "Independência ou morte!" Grito do Ipiranga — nascimento do Brasil independente.',
      'Carta real → Dom Pedro rasga → Grito do Ipiranga → Brasil independente. Tudo em dias.',
      'Cortes Portuguesas = assembleia que governava Portugal. Príncipe Regente = representa o rei. Grito do Ipiranga = momento simbólico.',
      'Sete de setembro é quase que um teatro político — mas foi o ponto de virada real.',
      '1. Qual foi o gatilho? 2. O que Dom Pedro fez? 3. Por que funcionou?',
      'Grito do Ipiranga é teatral, sim, mas funcionou porque Brasil inteiro (elites, não povo) queria independência.'),
    block('v_impacto', 'O que mudou após 1822?',
      'Mudou: Brasil virou Império (Dom Pedro I como Imperador), teve Constituição, virou monarquia constitucional (teoricamente, rei com limites — na prática, dom Pedro fez o que queria). Não mudou: escravidão continuou (até 1888), indígenas continuaram marginalizados, desigualdade permaneceu. Brasil ficou independente politicamente mas dependente economicamente de Portugal e Inglaterra (café, dívidas). O grande problema: independência sem libertação social. Elites ficaram ricas, povo continuou escravizado.',
      'Dom Pedro I: imperador de um país que continuava a escravizar. Um país que havia proclamado "liberdade" mas mantinha 90% da população como propriedade.',
      'Império = reino com imperador. Constituição = lei que governa. Monarquia constitucional = rei tem poder mas dentro de limites (na teoria).',
      'Independência política sem justiça social é como sair de uma prisão para abrir outra — liberdade parcial.',
      '1. O que virou? 2. O que permaneceu? 3. Por que não libertou escravizados?',
      'A ironia do Brasil: declarava liberdade em 1822 mas mantinha escravidão até 1888. Essa contradição marca a história brasileira.'),
  ],
  questions: [
    mc(1, 'v_contexto', 'Por que a Corte Portuguesa veio para o Brasil em 1808?', ['Férias do rei', 'Fuga de Napoleão', 'Procurar ouro', 'Visitar colônia'], 1, ['Europa estava em perigo.', 'Napoleão invadiu Portugal.', 'Fuga.'], '1808: João VI foge de Napoleão com toda a Corte.'),
    tf(1, 'v_contexto', 'Após a Corte chegar ao Brasil, a situação política ficou mais clara: definitivamente era colônia.', false, ['Ou ficou mais confusa?', 'Coroa aqui, mas colônia? Não fazia sentido.', 'Conflito.'], 'Falso: ficou mais confusa e tensa. Coroa vivia aqui, então por quê colônia?'),
    fill(1, 'g_atores', '___ foi o conselheiro que influenciou Dom Pedro para a independência.', ['José Bonifácio'], ['Andrada e Silva.', 'Estrategista.', 'José Bonifácio.'], 'José Bonifácio: o verdadeiro arquiteto da independência.'),
    mc(2, 'g_atores', 'Qual era o papel de Leopoldina (esposa de Dom Pedro I)?', ['Rainha de Portugal', 'Apoiadora da independência', 'Guerreira', 'Dona de engenho'], 1, ['Influência política.', 'Apoiadora.', 'Leopoldina.'], 'Leopoldina apoiava Dom Pedro e influenciava suas decisões.'),
    match(2, 's_processo', 'Ligue cada evento à data.', [['Rei volta a Portugal', '1821'], ['Dom Pedro rasga carta', '7 de setembro de 1822'], ['Grito do Ipiranga', '7 de setembro de 1822'], ['Brasil se declara independente', '1822']], ['1821 ou 1822?', 'Rei saiu 1821.', 'Dom Pedro agiu em 1822.'], '1821-Rei saiu, 1822-Grito, 1822-Independência.'),
    mc(2, 's_processo', 'O que Dom Pedro gritou à beira do Rio Ipiranga?', ['"Viva a Coroa Portuguesa!"', '"Independência ou morte!"', '"Viva o café!"', '"Volta, pai!"'], 1, ['Frase icônica.', 'Desafio.', '"Independência ou morte!"'], '"Independência ou morte!" — frase que marca o nascimento do Brasil.'),
    mc(3, 'v_impacto', 'O que NÃO mudou após a independência de 1822?', ['Governo do Brasil', 'A escravidão', 'A moeda', 'A língua'], 1, ['O que continuou igual?', 'Escravizados continuaram escravizados.', 'Escravidão.'], 'Escravidão continuou — só ended em 1888.'),
    tf(3, 'v_impacto', 'A independência do Brasil foi uma revolução social completa, libertando escravizados e indígenas.', false, ['Realmente?', 'Apenas política, não social.', 'Falso.'], 'Falso: independência foi política, não social. Escravidão durou mais 66 anos.'),
    order(2, 's_processo', 'Coloque os eventos em ordem.', ['Corte de Portugal chega (1808)', 'Rei retorna a Portugal (1821)', 'Dom Pedro rasga carta (1822)', 'Brasil declara independência (1822)'], ['8, 21, 22, 22.', 'Cronológico.'], '1808 → 1821 → 1822.'),
  ],
  review: ['1808: Corte foge de Napoleão para Brasil', '1821: Rei volta, Dom Pedro fica', '7 de setembro 1822: Grito do Ipiranga', 'Independência política, mas escravidão e desigualdade permaneceram até 1888+'],
  relatedQuestions: ['quem foi dom pedro i', 'o que foi o grito do ipiranga', 'por que brasil não teve guerra de independência', 'quando brasil aboliu escravidão'],
  equivalentQuestions: eqsPt(['independência brasil', '1822', 'dom pedro'], ['como brasil saiu de portugal', 'o que significou grito do ipiranga', 'dom pedro era herói ou vilão', 'por que brasil continua desigual', 'quando escravidão acabou de verdade']),
  commonErrors: ['Achar que Grito do Ipiranga foi guerra (foi apenas gesto político).', 'Confundir Dom Pedro I com Pedro Álvares Cabral.', 'Achar que independência libertou escravizados (não, durou 66 anos mais).'],
  english: {
    cefr: '—', unit: 'his-u1', order: 3, area: 'history',
    vocabulary: [
      { word: 'independência', translation: 'independence', pos: 'noun', definition: 'liberdade de um país em se auto-governar', example: 'Brasil declarou independência em 1822.', difficulty: 1 },
      { word: 'príncipe regente', translation: 'prince regent', pos: 'phrase', definition: 'príncipe que governa em lugar do rei', example: 'Dom Pedro era príncipe regente do Brasil.', difficulty: 2 },
      { word: 'grito do ipiranga', translation: 'Ipiranga Cry', pos: 'phrase', definition: 'momento simbólico em que Dom Pedro rasga carta real e declara independência', example: 'Grito do Ipiranga é celebrado todo 7 de setembro.', difficulty: 2 },
      { word: 'monarquia constitucional', translation: 'constitutional monarchy', pos: 'phrase', definition: 'regime onde rei governa dentro de limites impostos por constituição', example: 'Brasil tinha monarquia constitucional após 1822.', difficulty: 3 },
    ],
    history: {
      period: '1808–1822',
      timeline: [
        { date: '1808', event: 'Corte Portuguesa foge para Brasil; cidade do Rio fica centro do Império Português' },
        { date: '1815', event: 'Brasil elevado a "Reino Unido com Portugal e Algarves"' },
        { date: '1821', event: 'João VI retorna para Portugal; Dom Pedro fica como Príncipe Regente' },
        { date: '7-SET-1822', event: 'Grito do Ipiranga — Dom Pedro rasga carta real e declara independência' },
        { date: '1823', event: 'Primeira Constituição do Brasil' },
        { date: '1831', event: 'Dom Pedro I abdica; Dom Pedro II assume' },
        { date: '1888', event: 'Abolição da escravidão (Lei Áurea)' },
      ],
    },
  },
})

export const segundaGuerra = lesson({
  id: 'his-segunda-guerra', subject: 'historia', title: 'Segunda Guerra Mundial (1939–1945)', levels: ['medio'], grade: 'A partir do 8º ano',
  topic: 'História — Era Contemporânea', subtopic: 'Segunda Guerra, Nazismo, Holocausto, fim do conflito',
  aliases: ['segunda guerra', '1939', 'hitler', 'holocausto', 'nazismo', 'mussolini', 'japão axis'],
  summary: 'O maior conflito da história: causas, potências em guerra, o Holocausto, e como terminou.',
  intro: '1939–1945: 70 milhões de mortos, Holocausto, armas nucleares. A Segunda Guerra mudou o mundo para sempre.',
  objective: 'Entender as causas da Segunda Guerra, seus principais eventos, o Holocausto, e as consequências até hoje.',
  prerequisites: [],
  next: [],
  skills: { v_causas: 'Causas do conflito global', g_potencias: 'Potências Aliadas e Eixo', s_holocausto: 'O Holocausto', v_fim: 'Fim da guerra e novo mundo' },
  blocks: [
    block('v_causas', 'Por que explodiu a guerra?',
      'Consequências da Primeira Guerra: Alemanha humilhada, endividada, raivosa. Nazismo de Hitler cresce promettendo revanche. 1933: Hitler sobe ao poder. Ideologia: supremacia ariana, expansionismo, culpa dos judeus. Contexto: depressão econômica, desemprego, nacionalismo extremo. Ninguém freava porque alguns países ganhariam com guerra. 1939: Hitler invade Polônia. Pronto, guerra global.',
      'Hitler: "Alemanha será grande novamente." Povo alemão, humilhado, acredita. Economia cresce com produção de armas. Mas o preço é ditadura, perseguição, genocídio.',
      'Nazismo = ideologia de Hitler: racismo, totalitarismo, expansão territorial. Ariana = fictícia "raça superior" que Hitler inventou para justificar genocídio.',
      'Primeira Guerra deixou Alemanha tão humilhada que ficou fácil alguém vir e prometer vingança — mesmo que o preço fosse monstro moral.',
      '1. Como a 1ª Guerra plantou as sementes? 2. Como Hitler usou raiva? 3. Por que mundo permitiu?',
      'Segunda Guerra não apareceu do nada — foi resultado direto de como Primeira terminou, combinado com ideologia extrema.'),
    block('g_potencias', 'Aliados vs. Eixo',
      'Eixo: Alemanha (Hitler), Itália (Mussolini), Japão (expansionista no Pacífico). Aliados: GB (Churchill), URSS (Stalin, depois que Alemanha invadiu), EUA (Roosevelt, depois ataque a Pearl Harbor). Brasil: declarou guerra aos nazis em 1942 (após afundar navios brasileiros). Diferentes ideologias mas mesmo inimigo: Nazismo era tão ameaça que capitalistas e comunistas viraram aliados improvável.',
      'Churchill + Roosevelt + Stalin = improvável amigos. Mas Hitler era pior inimigo comum.',
      'Eixo = aliança de ditaduras. Aliados = mistura de democracia (GB, EUA) e ditadura (URSS) contra fascismo.',
      'Às vezes o inimigo do meu inimigo se torna meu aliado — mesmo que depois virem inimigos (EUA e URSS viraram frios após guerra).)',
      '1. Quem era Eixo? 2. Quem era Aliados? 3. Por que tão estranho, aliança EUA-URSS?',
      'Alianças internacionais não são sobre amizade — são sobre interesses. Quando interesses mudam, aliados viram rivais.'),
    block('s_holocausto', 'O Holocausto — genocídio planejado',
      'Hitler culpava judeus por derrota na 1ª Guerra (mentira). Planejou eliminar judeus, ciganos, deficientes, homossexuais, prisioneiros políticos. 1941: nazistas começam assassinatos em massa. 1942: criar campos de concentração com câmaras de gás. Auschwitz, Treblinka, Dachau — fábricas de morte. 6 milhões de judeus mortos, 5 milhões de outros. Maioria europeia. Crianças. Inteligência. Cultura. Apagada.',
      'Anne Frank: garota que escreveu diário enquanto se escondia. Presa, morre em Auschwitz. Seu diário é testemunho que história não esqueça.',
      'Holocausto = palavra grega para sacrifício pelo fogo. Mas foi crime contra humanidade planejado e industrial. Sem precedentes.',
      'Seis milhões é número abstrato. Pense em cada pessoa — cada uma tinha nome, família, sonhos. Nazismo apagou seis milhões de vidas.',
      '1. Como acontecia? 2. Quantos morreram? 3. Por que "Holocausto"?',
      'Holocausto não é apenas capítulo triste de história — é advertência: ideologia de ódio racista pode virar industrialização de morte. Nunca esquecer.'),
    block('v_fim', 'Como terminou?',
      '1944: Aliados invadem Normandia (D-Day). Alemanha recua. Soviéticos avançam do leste. 1945: Alemanha rende-se. Hitler suicida. Maio: Guerra na Europa termina. Mas Japão continua. Agosto: EUA lança bombas atômicas em Hiroshima (70 mil mortos) e Nagasaki (40 mil mortos). Japão rende-se. Setembro 1945: Segunda Guerra termina. Novo mundo: ONU criada, Alemanha dividida, frio começa entre EUA-URSS, Israel criado, descolonização acelerada.',
      'Bomba atômica: arma que pode destruir cidades. Medo nuclear passou a dominar política. Até hoje.',
      'D-Day = operação de desembarque em Normandia. Bomba atômica = arma nuclear. Renda incondicional = Japão aceita perder tudo.',
      'Segunda Guerra trouxe arma que pode exterminar humanidade. Desde então, política é dominada por medo nuclear (que continua hoje).',
      '1. Como Aliados ganharam? 2. Por que bombas atômicas? 3. Que mundo nasceu?',
      'Fim da Segunda Guerra plantou sementes de novo conflito: Guerra Fria. Vitória dos Aliados em 1945 foi início de 45 anos de tensão nuclear.'),
  ],
  questions: [
    mc(1, 'v_causas', 'Qual foi a PRINCIPAL razão de Alemanha estar pronta para guerra?', ['Sucesso econômico', 'Humilhação da 1ª Guerra + Depressão + Ideologia nazista', 'Ganância por colônias', 'Aliança com Japão'], 1, ['Combinação de fatores.', 'Humilhação + ideologia + economia.'], 'Combinação: Alemanha humilhada, economicamente destituída, e Hitler oferecia revanche.'),
    tf(1, 'v_causas', 'Hitler foi o único culpado pela Segunda Guerra.', false, ['Responsável? Sim. Único? Não.', 'Contexto permitiu.', 'Mundo também falhou ao permitir rise.'], 'Falso: Hitler foi responsável mas não único. Contexto, apatia política, falha da Liga das Nações também culpadas.'),
    fill(1, 'g_potencias', 'O ___ foi o líder da Alemanha Nazista durante a Segunda Guerra.', ['Hitler'], ['Adolf Hitler.', 'Nazista.', 'Hitler.'], 'Hitler: responsável pelo Holocausto e pela Segunda Guerra.'),
    mc(2, 'g_potencias', 'Qual era a aliança principal entre Aliados?', ['EUA e Japão', 'EUA, GB e URSS', 'Alemanha e Itália', 'Brasil e EUA'], 1, ['Quem se uniu contra Eixo?', 'Potências ocidentais + comunista.', 'EUA, GB, URSS.'], 'Aliança dos "Três Grandes": EUA, GB e URSS contra Eixo.'),
    match(2, 's_holocausto', 'Ligue cada termo.', [['Anne Frank', 'Garota que escreveu diário em Auschwitz'], ['Auschwitz', 'Maior campo de concentração'], ['Holocausto', 'Genocídio de judeus e outros'], ['6 milhões', 'Número de judeus mortos']], ['Anne Frank: testemunha.', 'Auschwitz: morte industrial.', 'Holocausto: crime.', 'Morte: escala.'], 'Anne-diário, Auschwitz-campo, Holocausto-genocídio, 6M-mortos.'),
    mc(2, 's_holocausto', 'Em que ano os nazistas começaram o Holocausto em escala industrial?', ['1939', '1941', '1942', '1945'], 2, ['Quando ganhou escala de morte?', 'Campos de gás apareceram 1942.'], '1942: campos de concentração com câmaras de gás começaram operações de morte em massa.'),
    mc(3, 'v_fim', 'Qual evento marcou o final da guerra na Europa?', ['Invasão de Pearl Harbor', 'Bomba atômica em Hiroshima', 'Rendição incondicional da Alemanha (Maio 1945)', 'Criação da ONU'], 2, ['Quando Europa parou de lutar?', 'Maio de 1945.', 'Rendição alemã.'], 'Maio de 1945: Alemanha rende-se incondicionalmente. Europa em paz.'),
    tf(3, 'v_fim', 'A Segunda Guerra terminou com paz duradoura.', false, ['Ou começou novo conflito?', 'Guerra Fria começou logo.', 'Falso.'], 'Falso: paz foi ilusória. EUA-URSS entraram em Guerra Fria que durou 45 anos.'),
    order(2, 'v_fim', 'Coloque os eventos em ordem.', ['D-Day (Normandia)', 'Rendição alemã', 'Bombas atômicas', 'Rendição japonesa'], ['1944, 1945 maio, 1945 agosto, 1945 set.', 'Cronológico.'], 'Junho 1944 → Maio 1945 → Agosto 1945 → Setembro 1945.'),
  ],
  review: ['Causas: humilhação alemã + depressão + nazismo', 'Potências: Eixo (Alemanha, Itália, Japão) vs. Aliados (EUA, GB, URSS)', 'Holocausto: 6 milhões judeus + 5 milhões outros mortos em genocídio planejado', 'Fim: Alemanha 1945 maio, Japão 1945 set. Bomba atômica. Guerra Fria começa.'],
  relatedQuestions: ['quem venceu segunda guerra', 'por que holocausto', 'como guerra terminou', 'o que é bomba atômica'],
  equivalentQuestions: eqsPt(['segunda guerra', '1939', 'hitler'], ['como segunda guerra começou', 'quem foi hitler', 'quantos morreram segunda guerra', 'por que japão lutava', 'o que é guerra fria', 'como mundo ficou depois segunda guerra']),
  commonErrors: ['Achar que Segunda Guerra terminou em paz (começou Guerra Fria).', 'Confundir bomba atômica com bomba convencional.', 'Não saber dimensão do Holocausto.'],
  english: {
    cefr: '—', unit: 'his-u1', order: 4, area: 'history',
    vocabulary: [
      { word: 'nazismo', translation: 'Nazism', pos: 'noun', definition: 'ideologia de Hitler baseada em racismo e totalitarismo', example: 'Nazismo causou Segunda Guerra e Holocausto.', difficulty: 2 },
      { word: 'holocausto', translation: 'Holocaust', pos: 'noun', definition: 'genocídio de judeus e outros grupos durante Segunda Guerra', example: 'Holocausto foi crime contra humanidade.', difficulty: 2 },
      { word: 'bomba atômica', translation: 'atomic bomb', pos: 'phrase', definition: 'arma nuclear que destrói cidades em segundos', example: 'EUA lançou bombas atômicas em Hiroshima e Nagasaki.', difficulty: 2 },
      { word: 'eixo', translation: 'Axis', pos: 'noun', definition: 'aliança de Alemanha, Itália e Japão', example: 'Eixo lutava contra os Aliados.', difficulty: 2 },
    ],
  },
})
