import type { Lesson } from '../../types'

const AUTORAL = { title: 'Conteúdo autoral LUMI', kind: 'autoral' } as const
const BNCC_HIS = { title: 'Base Nacional Comum Curricular (BNCC) — História', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' } as const
const BNCC_GEO = { title: 'Base Nacional Comum Curricular (BNCC) — Geografia', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' } as const

export const brasilColonia: Lesson = {
  id: 'his-brasil-colonia',
  subject: 'historia',
  title: 'Brasil Colônia',
  levels: ['fund2', 'medio'],
  grade: '7º ano',
  aliases: ['brasil colonia', 'periodo colonial', 'descobrimento do brasil', 'chegada dos portugueses', 'capitanias hereditarias', 'governo geral', 'pau brasil', 'ciclo do acucar', 'engenho'],
  summary: 'Da chegada dos portugueses em 1500 às capitanias, ao governo-geral e à economia do açúcar.',
  intro: 'Em 1500, navios portugueses chegaram a uma terra que já era habitada por milhões de indígenas. Começava o período colonial.',
  skills: { chegada: 'A chegada dos portugueses', capitanias: 'Capitanias hereditárias', governo: 'Governo-geral', economia: 'Economia colonial e escravidão' },
  blocks: [
    { id: 'b1', skill: 'chegada', title: 'A chegada em 1500', text: 'Em abril de 1500, a esquadra de Pedro Álvares Cabral chegou ao litoral da atual Bahia. A terra já era habitada por muitos povos indígenas. Nos primeiros anos, Portugal explorou principalmente o pau-brasil, árvore usada para tingir tecidos.', example: 'O nome "Brasil" vem do pau-brasil, cuja madeira tem cor de brasa.' },
    { id: 'b2', skill: 'capitanias', title: 'As capitanias hereditárias (1534)', text: 'Para ocupar e defender a terra, o rei Dom João III dividiu o território em faixas chamadas capitanias hereditárias, entregues a donatários que deviam povoá-las e explorá-las por conta própria. Passavam de pai para filho.', example: 'Pernambuco e São Vicente prosperaram; a maioria das outras fracassou por falta de recursos e conflitos.' },
    { id: 'b3', skill: 'governo', title: 'O governo-geral (1549)', text: 'Como as capitanias não deram certo em geral, Portugal criou o governo-geral para centralizar a administração. O primeiro governador, Tomé de Sousa, chegou em 1549 e fundou Salvador, primeira capital do Brasil.', example: 'Com Tomé de Sousa vieram os primeiros jesuítas, liderados por Manuel da Nóbrega.' },
    { id: 'b4', skill: 'economia', title: 'Açúcar e escravidão', text: 'A principal atividade econômica foi a produção de açúcar nos engenhos do Nordeste, feita com o trabalho de africanos escravizados trazidos à força. Indígenas também foram escravizados. A escravidão marcou profundamente a sociedade brasileira.', example: 'O engenho reunia a casa-grande, a senzala, a moenda e os canaviais.' },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'chegada', prompt: 'Em que ano a esquadra de Cabral chegou ao Brasil?', options: ['1492', '1500', '1822', '1534'], answer: 1, hints: ['É o começo do século XVI.', 'Um número "redondo".', 'Mil e quinhentos.'], explanation: 'Em 1500.' },
    { id: 'q2', type: 'tf', difficulty: 1, skill: 'chegada', prompt: 'Quando os portugueses chegaram, a terra já era habitada por povos indígenas.', answer: true, hints: ['Estava vazia?', 'Havia milhões de pessoas.', 'Os povos originários.'], explanation: 'Verdadeiro.' },
    { id: 'q3', type: 'mc', difficulty: 1, skill: 'chegada', prompt: 'O primeiro produto explorado pelos portugueses foi:', options: ['Ouro', 'Café', 'Pau-brasil', 'Borracha'], answer: 2, hints: ['Deu nome ao país.', 'É uma árvore.', 'Pau-…'], explanation: 'O pau-brasil.' },
    { id: 'q4', type: 'fill', difficulty: 2, skill: 'capitanias', prompt: 'As capitanias hereditárias foram criadas em ____.', answers: ['1534'], hints: ['Foi na década de 1530.', 'Antes do governo-geral (1549).', '15-3-4.'], explanation: 'Em 1534.' },
    { id: 'q5', type: 'mc', difficulty: 2, skill: 'governo', prompt: 'Quem foi o primeiro governador-geral do Brasil?', options: ['Pedro Álvares Cabral', 'Tomé de Sousa', 'Dom Pedro I', 'Martim Afonso'], answer: 1, hints: ['Chegou em 1549.', 'Fundou Salvador.', 'Tomé…'], explanation: 'Tomé de Sousa.' },
    { id: 'q6', type: 'match', difficulty: 2, skill: 'governo', prompt: 'Ligue cada fato ao ano.', pairs: [['Chegada de Cabral', '1500'], ['Capitanias hereditárias', '1534'], ['Chegada de Tomé de Sousa e fundação de Salvador', '1549']], hints: ['A chegada é a mais antiga.', 'As capitanias vieram antes do governo-geral.', 'Salvador foi fundada no fim da década de 1540.'], explanation: '1500 → 1534 → 1549.' },
    { id: 'q7', type: 'tf', difficulty: 2, skill: 'capitanias', prompt: 'A maioria das capitanias hereditárias prosperou.', answer: false, hints: ['Por que Portugal criou o governo-geral?', 'Porque o sistema não funcionou bem.', 'Poucas deram certo.'], explanation: 'Falso. Só algumas, como Pernambuco e São Vicente, prosperaram.' },
    { id: 'q8', type: 'mc', difficulty: 3, skill: 'economia', prompt: 'Qual foi a principal base de trabalho nos engenhos de açúcar?', options: ['Trabalhadores assalariados europeus', 'Africanos escravizados', 'Máquinas a vapor', 'Colonos voluntários'], answer: 1, hints: ['Pessoas trazidas à força.', 'Vinham de outro continente.', 'Da África.'], explanation: 'O trabalho de africanos escravizados.' },
    { id: 'q9', type: 'fill', difficulty: 3, skill: 'governo', prompt: 'A primeira capital do Brasil foi a cidade de ________.', answers: ['salvador'], hints: ['Fica na Bahia.', 'Foi fundada por Tomé de Sousa.', 'Salva…'], explanation: 'Salvador.' },
    { id: 'q10', type: 'open', difficulty: 3, skill: 'capitanias', prompt: 'Por que Portugal criou o governo-geral depois das capitanias?', modelAnswer: 'Porque a maioria das capitanias fracassou por falta de recursos, isolamento e conflitos com indígenas. O governo-geral centralizou a administração para defender e organizar melhor a colônia.', keywords: ['fracass', 'centraliz', 'organizar', 'defender', 'recursos', 'administracao'], hints: ['As capitanias funcionaram?', 'O que faltava a elas?', 'O governo-geral juntou o poder num só lugar.'], explanation: 'Para centralizar a administração após o fracasso da maioria das capitanias.' },
  ],
  review: ['1500: chegada de Cabral; terra já habitada', 'Pau-brasil: primeira exploração', '1534: capitanias hereditárias', '1549: governo-geral, Tomé de Sousa, Salvador', 'Açúcar + trabalho escravizado'],
  sources: [BNCC_HIS, { title: 'Toda Matéria — Capitanias Hereditárias', url: 'https://www.todamateria.com.br/capitanias-hereditarias/', kind: 'site' }, AUTORAL],
}

export const independenciaBrasil: Lesson = {
  id: 'his-independencia-brasil',
  subject: 'historia',
  title: 'Independência do Brasil',
  levels: ['fund1', 'fund2', 'medio'],
  grade: '8º ano',
  aliases: ['independencia do brasil', '7 de setembro', 'grito do ipiranga', 'dom pedro i', 'dia do fico', '1822', 'primeiro reinado'],
  summary: 'Os caminhos até 1822, o 7 de setembro e o reconhecimento da independência.',
  intro: 'O 7 de setembro é feriado nacional. Mas a independência foi um processo — não aconteceu num dia só.',
  skills: { contexto: 'Antecedentes', dia_do_fico: 'Dia do Fico', proclamacao: '7 de setembro de 1822', reconhecimento: 'Guerras e reconhecimento' },
  blocks: [
    { id: 'b1', skill: 'contexto', title: 'A família real no Brasil', text: 'Em 1808, fugindo das tropas de Napoleão, a família real portuguesa veio para o Rio de Janeiro. O Brasil ganhou importância: portos abertos, novas instituições e, em 1815, virou Reino Unido a Portugal e Algarves.', example: 'Nessa época surgiram o Banco do Brasil e o Jardim Botânico do Rio.' },
    { id: 'b2', skill: 'dia_do_fico', title: 'O Dia do Fico (1822)', text: 'Dom João VI voltou a Portugal em 1821 e deixou seu filho, Dom Pedro, como príncipe regente. As cortes portuguesas exigiram que ele também voltasse. Em 9 de janeiro de 1822, ele decidiu ficar: foi o Dia do Fico.', example: 'A frase atribuída a ele: "Diga ao povo que fico".' },
    { id: 'b3', skill: 'proclamacao', title: 'O 7 de setembro', text: 'Em 7 de setembro de 1822, às margens do riacho Ipiranga, em São Paulo, Dom Pedro proclamou a independência. Em dezembro, foi coroado Dom Pedro I, primeiro imperador do Brasil. O país virou uma monarquia.', example: 'O episódio ficou conhecido como "Grito do Ipiranga".' },
    { id: 'b4', skill: 'reconhecimento', title: 'Guerras e reconhecimento', text: 'Tropas portuguesas resistiram em províncias como Bahia, Maranhão e Pará, e houve guerras de independência. A Bahia só se libertou em 2 de julho de 1823. Portugal reconheceu a independência em 1825, pelo Tratado do Rio de Janeiro, mediante indenização paga pelo Brasil.', example: 'O 2 de Julho é a grande data cívica da Bahia.' },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'proclamacao', prompt: 'Em que data comemoramos a Independência do Brasil?', options: ['15 de novembro', '7 de setembro', '21 de abril', '1º de janeiro'], answer: 1, hints: ['É feriado nacional.', 'Tem desfile cívico.', 'Setembro.'], explanation: '7 de setembro (de 1822).' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'proclamacao', prompt: 'Quem proclamou a independência?', options: ['Dom João VI', 'Dom Pedro', 'Tiradentes', 'Deodoro da Fonseca'], answer: 1, hints: ['Era o príncipe regente.', 'Virou o primeiro imperador.', 'Dom…'], explanation: 'Dom Pedro, depois Dom Pedro I.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'proclamacao', prompt: 'Depois da independência, o Brasil virou uma república.', answer: false, hints: ['Quem passou a governar?', 'Um imperador.', 'Imperador = monarquia.'], explanation: 'Falso. Virou um império (monarquia); a república veio só em 1889.' },
    { id: 'q4', type: 'fill', difficulty: 2, skill: 'contexto', prompt: 'A família real portuguesa chegou ao Brasil em ____.', answers: ['1808'], hints: ['Fugia de Napoleão.', 'Início do século XIX.', '18-0-8.'], explanation: 'Em 1808.' },
    { id: 'q5', type: 'mc', difficulty: 2, skill: 'dia_do_fico', prompt: 'O que foi o Dia do Fico?', options: ['A volta de Dom João VI a Portugal', 'A decisão de Dom Pedro de permanecer no Brasil', 'A coroação de Dom Pedro I', 'O fim da escravidão'], answer: 1, hints: ['"Diga ao povo que fico."', 'Ele ficaria onde?', 'No Brasil.'], explanation: 'Em 9/1/1822, Dom Pedro decidiu ficar no Brasil.' },
    { id: 'q6', type: 'match', difficulty: 2, skill: 'reconhecimento', prompt: 'Ligue cada fato à data.', pairs: [['Chegada da família real', '1808'], ['Proclamação da independência', '1822'], ['Independência na Bahia', '1823'], ['Reconhecimento por Portugal', '1825']], hints: ['A chegada da família real é a mais antiga.', 'A Bahia lutou depois do 7 de setembro.', 'O reconhecimento é a mais recente.'], explanation: '1808 → 1822 → 1823 → 1825.' },
    { id: 'q7', type: 'tf', difficulty: 2, skill: 'reconhecimento', prompt: 'Portugal reconheceu a independência imediatamente, em 1822.', answer: false, hints: ['Houve guerras depois.', 'O reconhecimento veio por tratado.', 'Três anos depois.'], explanation: 'Falso. Só em 1825, pelo Tratado do Rio de Janeiro.' },
    { id: 'q8', type: 'mc', difficulty: 3, skill: 'reconhecimento', prompt: 'Em qual província houve forte resistência portuguesa, encerrada em 2 de julho de 1823?', options: ['São Paulo', 'Bahia', 'Rio Grande do Sul', 'Minas Gerais'], answer: 1, hints: ['É uma data cívica estadual.', 'Fica no Nordeste.', 'Capital: Salvador.'], explanation: 'Na Bahia.' },
    { id: 'q9', type: 'fill', difficulty: 3, skill: 'proclamacao', prompt: 'A independência foi proclamada às margens do riacho ________.', answers: ['ipiranga'], hints: ['Fica em São Paulo.', '"Grito do …"', 'Ipi…'], explanation: 'Ipiranga.' },
    { id: 'q10', type: 'open', difficulty: 3, skill: 'contexto', prompt: 'Por que a vinda da família real em 1808 ajudou no caminho da independência?', modelAnswer: 'Porque o Brasil passou a ser a sede do governo português, ganhou instituições, portos abertos e depois virou Reino Unido. Com isso, a elite local não aceitou voltar a ser uma simples colônia quando Portugal tentou recolonizá-lo.', keywords: ['sede', 'governo', 'instituicoes', 'portos', 'reino unido', 'colonia', 'importancia', 'autonomia'], hints: ['O que o Brasil ganhou com a corte aqui?', 'Virou o quê em 1815?', 'Por que não aceitaria voltar a ser colônia?'], explanation: 'O Brasil ganhou autonomia e importância e não aceitou voltar a ser colônia.' },
  ],
  review: ['1808: família real no Rio', '9/1/1822: Dia do Fico', '7/9/1822: proclamação; Dom Pedro I imperador', '1823: Bahia (2 de Julho) · 1825: reconhecimento por Portugal'],
  sources: [BNCC_HIS, { title: 'Arquivo Nacional — Reconhecimento da Independência do Brasil por Portugal', url: 'https://historialuso.an.gov.br/index.php?option=com_content&view=article&id=3869%3Areconhecimento-da-independencia-do-brasil-por-port&catid=149&Itemid=215', kind: 'instituicao' }, AUTORAL],
}

export const segundaGuerra: Lesson = {
  id: 'his-segunda-guerra',
  subject: 'historia',
  title: 'Segunda Guerra Mundial',
  levels: ['fund2', 'medio'],
  grade: '9º ano e 3ª série',
  aliases: ['segunda guerra mundial', 'segunda guerra', '2 guerra', 'nazismo', 'holocausto', 'hitler', 'feb', 'forca expedicionaria brasileira', 'aliados e eixo'],
  summary: 'Causas, lados, principais fatos, o Holocausto e a participação do Brasil (1939–1945).',
  intro: 'Foi o maior conflito da história. Vamos entender por que começou e como terminou.',
  skills: { causas: 'Causas', lados: 'Eixo e Aliados', fatos: 'Principais acontecimentos', brasil: 'O Brasil na guerra' },
  blocks: [
    { id: 'b1', skill: 'causas', title: 'Por que começou', text: 'Após a Primeira Guerra, a crise econômica e o descontentamento favoreceram regimes totalitários, como o nazismo na Alemanha (Hitler) e o fascismo na Itália (Mussolini). A guerra começou em 1º de setembro de 1939, com a invasão da Polônia pela Alemanha.', example: 'O Tratado de Versalhes impôs duras punições à Alemanha, o que os nazistas usaram na propaganda.' },
    { id: 'b2', skill: 'lados', title: 'Os dois lados', text: 'O Eixo reunia principalmente Alemanha, Itália e Japão. Os Aliados reuniam Reino Unido, França, União Soviética (a partir de 1941) e Estados Unidos (a partir de 1941), entre outros.', example: 'Os EUA entraram na guerra após o ataque japonês a Pearl Harbor, em dezembro de 1941.' },
    { id: 'b3', skill: 'fatos', title: 'Fatos marcantes e o Holocausto', text: 'O regime nazista perseguiu e assassinou cerca de 6 milhões de judeus, além de ciganos, pessoas com deficiência e outros grupos: o Holocausto. Em 1944 os Aliados desembarcaram na Normandia (Dia D). A guerra terminou na Europa em maio de 1945 e, após as bombas atômicas em Hiroshima e Nagasaki, o Japão se rendeu em setembro de 1945.', example: 'Após a guerra foi criada a ONU (1945), para tentar evitar novos conflitos mundiais.' },
    { id: 'b4', skill: 'brasil', title: 'O Brasil na guerra', text: 'O Brasil declarou guerra ao Eixo em 1942, após navios brasileiros serem afundados. A Força Expedicionária Brasileira (FEB), com mais de 25 mil militares, lutou na Itália. A tomada de Monte Castelo, em 21 de fevereiro de 1945, é sua vitória mais lembrada.', example: 'O símbolo da FEB era uma cobra fumando — resposta a quem dizia que era "mais fácil uma cobra fumar" do que o Brasil ir à guerra.' },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'causas', prompt: 'Em que período aconteceu a Segunda Guerra Mundial?', options: ['1914–1918', '1939–1945', '1789–1799', '1964–1985'], answer: 1, hints: ['Começou no fim da década de 1930.', 'Terminou em meados dos anos 1940.', 'Termina em 1945.'], explanation: 'De 1939 a 1945.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'causas', prompt: 'Qual fato marcou o início da guerra, em 1939?', options: ['Ataque a Pearl Harbor', 'Invasão da Polônia pela Alemanha', 'Bomba de Hiroshima', 'Dia D'], answer: 1, hints: ['Foi na Europa.', 'Foi a Alemanha que atacou.', 'Um país vizinho da Alemanha a leste.'], explanation: 'A invasão da Polônia, em 1º de setembro de 1939.' },
    { id: 'q3', type: 'match', difficulty: 2, skill: 'lados', prompt: 'Ligue cada país ao lado em que lutou.', pairs: [['Alemanha', 'Eixo'], ['Estados Unidos', 'Aliados'], ['Japão', 'Eixo (Ásia)'], ['Reino Unido', 'Aliados (Europa)']], hints: ['Hitler governava a Alemanha.', 'O Japão atacou os EUA.', 'Reino Unido lutou contra a Alemanha.'], explanation: 'Alemanha e Japão: Eixo · EUA e Reino Unido: Aliados.' },
    { id: 'q4', type: 'tf', difficulty: 1, skill: 'fatos', prompt: 'O Holocausto foi a perseguição e o assassinato de milhões de judeus e outros grupos pelo regime nazista.', answer: true, hints: ['Aconteceu durante a guerra.', 'Foi promovido pelos nazistas.', 'Cerca de 6 milhões de judeus.'], explanation: 'Verdadeiro.' },
    { id: 'q5', type: 'fill', difficulty: 2, skill: 'brasil', prompt: 'A sigla da força militar brasileira que lutou na Itália é ____.', answers: ['feb'], hints: ['Força Expedicionária…', 'Brasileira.', 'Três letras.'], explanation: 'FEB — Força Expedicionária Brasileira.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'lados', prompt: 'Por que os Estados Unidos entraram na guerra em 1941?', options: ['Por causa do Dia D', 'Por causa do ataque japonês a Pearl Harbor', 'Por causa da invasão da Polônia', 'Por causa da criação da ONU'], answer: 1, hints: ['Foram atacados.', 'Pelo Japão.', 'Numa base no Havaí.'], explanation: 'Após o ataque a Pearl Harbor, em dezembro de 1941.' },
    { id: 'q7', type: 'mc', difficulty: 2, skill: 'brasil', prompt: 'A vitória mais lembrada da FEB foi a tomada de:', options: ['Normandia', 'Monte Castelo', 'Stalingrado', 'Berlim'], answer: 1, hints: ['Fica na Itália.', 'Foi em fevereiro de 1945.', 'Monte…'], explanation: 'Monte Castelo, 21/2/1945.' },
    { id: 'q8', type: 'tf', difficulty: 3, skill: 'fatos', prompt: 'A guerra terminou no mesmo dia na Europa e na Ásia.', answer: false, hints: ['A Alemanha se rendeu primeiro.', 'O Japão resistiu mais alguns meses.', 'Maio × setembro de 1945.'], explanation: 'Falso. Europa: maio de 1945; Japão: setembro de 1945.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'fatos', prompt: 'Qual organização foi criada em 1945 para tentar evitar novas guerras mundiais?', options: ['OTAN', 'ONU', 'União Europeia', 'Mercosul'], answer: 1, hints: ['Reúne quase todos os países.', 'Sede em Nova York.', 'Organização das Nações Unidas.'], explanation: 'A ONU.' },
    { id: 'q10', type: 'open', difficulty: 3, skill: 'causas', prompt: 'Cite fatores que ajudaram os regimes totalitários a chegarem ao poder antes da guerra.', modelAnswer: 'A crise econômica, o desemprego, o descontentamento com os resultados da Primeira Guerra e com o Tratado de Versalhes, e o medo de revoluções favoreceram líderes autoritários como Hitler e Mussolini, que usavam propaganda e nacionalismo.', keywords: ['crise', 'economica', 'desemprego', 'versalhes', 'primeira guerra', 'nacionalismo', 'propaganda'], hints: ['Como estava a economia?', 'O que o Tratado de Versalhes impôs?', 'Fale de crise e descontentamento.'], explanation: 'Crise econômica, Versalhes e nacionalismo fortaleceram o nazifascismo.' },
  ],
  review: ['1939–1945; começou com a invasão da Polônia', 'Eixo (Alemanha, Itália, Japão) × Aliados', 'Holocausto; Dia D (1944); fim em 1945', 'Brasil: FEB na Itália, Monte Castelo'],
  sources: [BNCC_HIS, { title: 'Blog do Exército Brasileiro — A tomada de Monte Castello pela FEB', url: 'https://eblog.eb.mil.br/en/w/a-tomada-de-monte-castello-pela-for%C3%A7a-expedicion%C3%A1ria-brasileira-feb-em-21-de-fevereiro-de-1945', kind: 'instituicao' }, AUTORAL],
}

export const biomas: Lesson = {
  id: 'geo-biomas-brasileiros',
  subject: 'geografia',
  title: 'Biomas brasileiros',
  levels: ['fund1', 'fund2', 'medio'],
  grade: '4º ao 7º ano',
  aliases: ['biomas', 'biomas brasileiros', 'amazonia', 'cerrado', 'mata atlantica', 'caatinga', 'pampa', 'pantanal', 'vegetacao do brasil'],
  summary: 'Conheça os seis biomas do Brasil e o que torna cada um especial.',
  intro: 'O Brasil tem florestas, savanas, sertão, campos e áreas alagadas. São seis biomas diferentes.',
  skills: { conceito: 'O que é bioma', florestas: 'Amazônia e Mata Atlântica', outros: 'Cerrado, Caatinga, Pampa e Pantanal', preservacao: 'Ameaças e preservação' },
  blocks: [
    { id: 'b1', skill: 'conceito', title: 'O que é um bioma', text: 'Bioma é uma grande região com clima, vegetação e animais parecidos. Segundo o IBGE, o Brasil tem seis: Amazônia, Cerrado, Mata Atlântica, Caatinga, Pampa e Pantanal.', example: 'A Amazônia é o maior, com cerca de 49,5% do território; o Pantanal é o menor, com cerca de 1,8%.', variants: { simples: 'Bioma é um grande "tipo de paisagem" com seu clima, plantas e bichos. O Brasil tem seis.' } },
    { id: 'b2', skill: 'florestas', title: 'As florestas', text: 'A Amazônia é uma floresta tropical quente e úmida, com enorme biodiversidade e a maior bacia hidrográfica do mundo. A Mata Atlântica acompanha o litoral; é um dos biomas mais devastados, pois ali se concentram grandes cidades.', example: 'Onças-pintadas e botos vivem na Amazônia; o mico-leão-dourado é símbolo da Mata Atlântica.', variants: { simples: 'Amazônia: a maior floresta, muito quente e úmida. Mata Atlântica: floresta perto do mar, que perdeu muita área.' } },
    { id: 'b3', skill: 'outros', title: 'Cerrado, Caatinga, Pampa e Pantanal', text: 'Cerrado: savana do Brasil Central, com árvores de troncos retorcidos e muitas nascentes. Caatinga: bioma semiárido do Nordeste, o único exclusivamente brasileiro. Pampa: campos do sul do Rio Grande do Sul. Pantanal: maior área úmida continental do planeta, que alaga em parte do ano.', example: 'O mandacaru é típico da Caatinga; o tuiuiú é símbolo do Pantanal.', variants: { simples: 'Cerrado tem árvores tortinhas. Caatinga é seca. Pampa é campo. Pantanal alaga.' } },
    { id: 'b4', skill: 'preservacao', title: 'Ameaças e preservação', text: 'Desmatamento, queimadas, expansão agropecuária sem controle e poluição ameaçam os biomas. Unidades de conservação, fiscalização e uso sustentável ajudam a protegê-los.', example: 'Parques nacionais, como o da Chapada dos Veadeiros (Cerrado), protegem áreas naturais.' },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'conceito', prompt: 'Quantos biomas o Brasil tem, segundo o IBGE?', options: ['4', '5', '6', '8'], answer: 2, hints: ['Amazônia, Cerrado, Mata Atlântica…', '…Caatinga, Pampa e Pantanal.', 'Conte.'], explanation: 'São 6 biomas.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'florestas', prompt: 'Qual é o maior bioma brasileiro?', options: ['Cerrado', 'Amazônia', 'Pantanal', 'Caatinga'], answer: 1, hints: ['É uma floresta.', 'Fica no Norte.', 'Tem o rio mais volumoso do mundo.'], explanation: 'A Amazônia, com cerca de 49,5% do território.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'outros', prompt: 'A Caatinga é o único bioma exclusivamente brasileiro.', answer: true, hints: ['Fica no Nordeste.', 'Não aparece em outros países.', 'É 100% brasileira.'], explanation: 'Verdadeiro.' },
    { id: 'q4', type: 'match', difficulty: 2, skill: 'outros', prompt: 'Ligue cada bioma à sua característica.', pairs: [['Cerrado', 'Árvores de troncos retorcidos'], ['Caatinga', 'Clima semiárido'], ['Pantanal', 'Maior área úmida continental'], ['Pampa', 'Campos do sul do Brasil']], hints: ['Semiárido = pouca chuva.', 'Área úmida alaga.', 'Campos = Pampa.'], explanation: 'Cerrado: troncos retorcidos · Caatinga: semiárido · Pantanal: alagado · Pampa: campos.' },
    { id: 'q5', type: 'fill', difficulty: 2, skill: 'conceito', prompt: 'O menor bioma do Brasil é o ________.', answers: ['pantanal'], hints: ['Ocupa cerca de 1,8% do país.', 'É uma área alagada.', 'Fica em MT e MS.'], explanation: 'O Pantanal.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'florestas', prompt: 'Por que a Mata Atlântica é um dos biomas mais devastados?', options: ['Porque fica no deserto', 'Porque ali se concentram grandes cidades e ocupação humana antiga', 'Porque não tem árvores', 'Porque é o maior bioma'], answer: 1, hints: ['Onde ela fica?', 'No litoral.', 'Onde vive a maior parte da população.'], explanation: 'A ocupação humana e as cidades se concentram no litoral.' },
    { id: 'q7', type: 'tf', difficulty: 2, skill: 'outros', prompt: 'O Pampa aparece no Brasil apenas no Rio Grande do Sul.', answer: true, hints: ['É um bioma do extremo sul.', 'Estende-se ao Uruguai e à Argentina.', 'No Brasil, só em um estado.'], explanation: 'Verdadeiro.' },
    { id: 'q8', type: 'mc', difficulty: 3, skill: 'outros', prompt: 'Qual bioma é chamado de "berço das águas" por ter muitas nascentes de rios importantes?', options: ['Pampa', 'Cerrado', 'Caatinga', 'Mata Atlântica'], answer: 1, hints: ['Fica no Brasil Central.', 'Tem árvores retorcidas.', 'Savana brasileira.'], explanation: 'O Cerrado.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'preservacao', prompt: 'Qual destas ações ajuda a preservar os biomas?', options: ['Queimadas para limpar o terreno', 'Criação de unidades de conservação', 'Desmatamento para pastagem', 'Descarte de lixo nos rios'], answer: 1, hints: ['Três opções causam danos.', 'Procure uma forma de proteger áreas.', 'Parques e reservas.'], explanation: 'Unidades de conservação protegem áreas naturais.' },
    { id: 'q10', type: 'open', difficulty: 3, skill: 'preservacao', prompt: 'Escolha um bioma brasileiro e explique uma ameaça que ele sofre.', modelAnswer: 'A Amazônia sofre com o desmatamento e as queimadas para abrir áreas de pasto e garimpo, o que destrói habitats, reduz a biodiversidade e afeta o clima.', keywords: ['desmatamento', 'queimada', 'garimpo', 'pasto', 'poluicao', 'biodiversidade', 'agropecuaria'], hints: ['Escolha um bioma.', 'O que as pessoas fazem que o prejudica?', 'Fale de desmatamento ou queimadas.'], explanation: 'Desmatamento e queimadas estão entre as principais ameaças.' },
  ],
  review: ['6 biomas: Amazônia, Cerrado, Mata Atlântica, Caatinga, Pampa, Pantanal', 'Amazônia é o maior (~49,5%); Pantanal, o menor (~1,8%)', 'Caatinga: exclusiva do Brasil', 'Ameaças: desmatamento e queimadas'],
  sources: [BNCC_GEO, { title: 'IBGE Educa — Os biomas brasileiros', url: 'https://educa.ibge.gov.br/jovens/materias-especiais/21592-os-biomas-brasileiros.html', kind: 'instituicao' }, AUTORAL],
}

export const regioesBrasil: Lesson = {
  id: 'geo-regioes-brasil',
  subject: 'geografia',
  title: 'Regiões do Brasil',
  levels: ['fund1', 'fund2'],
  grade: '4º e 7º ano',
  aliases: ['regioes do brasil', 'regioes brasileiras', 'estados e capitais', 'divisao regional', 'norte nordeste sudeste sul centro oeste', 'ibge regioes'],
  summary: 'As cinco regiões do IBGE, seus estados e características principais.',
  intro: 'O Brasil é enorme: para estudar melhor, o IBGE o dividiu em cinco regiões.',
  skills: { divisao: 'A divisão do IBGE', estados: 'Estados de cada região', caracteristicas: 'Características das regiões' },
  blocks: [
    { id: 'b1', skill: 'divisao', title: 'Cinco regiões', text: 'O Brasil tem 26 estados e o Distrito Federal, onde fica Brasília, a capital do país. O IBGE agrupa os estados em cinco regiões: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.', example: 'A divisão atual está em vigor desde 1988, quando Tocantins foi criado.', variants: { simples: 'O Brasil tem 5 regiões: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.' } },
    { id: 'b2', skill: 'estados', title: 'Quem está em cada região', text: 'Norte: AM, PA, AC, RO, RR, AP, TO. Nordeste: MA, PI, CE, RN, PB, PE, AL, SE, BA. Centro-Oeste: MT, MS, GO e DF. Sudeste: SP, RJ, MG, ES. Sul: PR, SC, RS.', example: 'Santa Catarina fica na Região Sul; a Bahia, no Nordeste.', variants: { simples: 'O Nordeste tem mais estados (9). O Sul tem menos (3): Paraná, Santa Catarina e Rio Grande do Sul.' } },
    { id: 'b3', skill: 'caracteristicas', title: 'Cada região tem seu jeito', text: 'O Norte é a maior região e abriga grande parte da Amazônia. O Nordeste tem o maior número de estados e um litoral extenso. O Centro-Oeste se destaca na agropecuária. O Sudeste é a região mais populosa e industrializada. O Sul tem clima subtropical, com invernos mais frios.', example: 'São Paulo, no Sudeste, é a cidade mais populosa do país.', variants: { simples: 'Norte: maior e com floresta. Sudeste: mais gente. Sul: mais frio.' } },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'divisao', prompt: 'Em quantas regiões o IBGE divide o Brasil?', options: ['3', '4', '5', '27'], answer: 2, hints: ['Norte, Nordeste…', '…Centro-Oeste, Sudeste, Sul.', 'Conte.'], explanation: 'Cinco regiões.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'estados', prompt: 'Santa Catarina fica em qual região?', options: ['Sudeste', 'Sul', 'Nordeste', 'Centro-Oeste'], answer: 1, hints: ['É uma das regiões mais frias.', 'Tem só 3 estados.', 'Junto com Paraná e RS.'], explanation: 'Região Sul.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'divisao', prompt: 'Brasília, a capital do país, fica no Distrito Federal.', answer: true, hints: ['O DF não é um estado comum.', 'É onde fica a capital.', 'Região Centro-Oeste.'], explanation: 'Verdadeiro.' },
    { id: 'q4', type: 'fill', difficulty: 2, skill: 'divisao', prompt: 'O Brasil tem ____ estados, além do Distrito Federal.', answers: ['26', 'vinte e seis'], hints: ['São 27 unidades da federação ao todo.', 'Tire o DF.', '27 − 1.'], explanation: '26 estados + DF.' },
    { id: 'q5', type: 'match', difficulty: 2, skill: 'caracteristicas', prompt: 'Ligue cada região à característica.', pairs: [['Norte', 'Maior região, com grande parte da Amazônia'], ['Sudeste', 'Mais populosa e industrializada'], ['Nordeste', 'Maior número de estados'], ['Sul', 'Clima subtropical, invernos frios']], hints: ['A floresta fica no Norte.', 'São Paulo está no Sudeste.', 'O Nordeste tem 9 estados.'], explanation: 'Norte: Amazônia · Sudeste: população · Nordeste: 9 estados · Sul: frio.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'estados', prompt: 'Qual região tem mais estados?', options: ['Norte', 'Nordeste', 'Sudeste', 'Sul'], answer: 1, hints: ['São nove estados.', 'Inclui Bahia e Pernambuco.', 'Nord…'], explanation: 'O Nordeste, com 9 estados.' },
    { id: 'q7', type: 'tf', difficulty: 2, skill: 'estados', prompt: 'Minas Gerais fica na Região Centro-Oeste.', answer: false, hints: ['MG faz divisa com SP e RJ.', 'Está na região mais populosa.', 'Sudeste.'], explanation: 'Falso. Minas Gerais fica no Sudeste.' },
    { id: 'q8', type: 'mc', difficulty: 3, skill: 'estados', prompt: 'Quais estados formam a Região Sudeste?', options: ['SP, RJ, MG e ES', 'SP, PR, SC e RS', 'MG, GO, MT e MS', 'RJ, BA, ES e SP'], answer: 0, hints: ['São quatro estados.', 'Inclui o Espírito Santo.', 'Não inclui Paraná.'], explanation: 'São Paulo, Rio de Janeiro, Minas Gerais e Espírito Santo.' },
    { id: 'q9', type: 'fill', difficulty: 3, skill: 'estados', prompt: 'O estado criado em 1988, que hoje faz parte da Região Norte, é o ________.', answers: ['tocantins'], hints: ['Foi desmembrado de Goiás.', 'Capital: Palmas.', 'Toca…'], explanation: 'Tocantins.' },
    { id: 'q10', type: 'mc', difficulty: 3, skill: 'caracteristicas', prompt: 'A Região Centro-Oeste se destaca principalmente por:', options: ['Pesca em alto-mar', 'Agropecuária (soja, milho e gado)', 'Clima frio com neve', 'Maior população do país'], answer: 1, hints: ['Tem grandes áreas planas no Cerrado.', 'Produz muitos grãos.', 'E cria gado.'], explanation: 'Agropecuária: soja, milho e gado.' },
  ],
  review: ['26 estados + DF; 5 regiões do IBGE', 'Nordeste: 9 estados · Sul: 3', 'Norte: maior · Sudeste: mais populoso', 'Centro-Oeste: agropecuária · Sul: subtropical'],
  sources: [BNCC_GEO, { title: 'IBGE Educa — Divisão Territorial', url: 'https://educa.ibge.gov.br/jovens/conheca-o-brasil/territorio/19637-divisao-territorial.html', kind: 'instituicao' }, AUTORAL],
}
