// Curso de Inglês do LUMI — nível A1 (Iniciante). Conteúdo original.
import { block, blank, dialogue, enSources, eqs, fill, lesson, match, mc, mci, order, tf, v, words } from '../dsl'

const ALL = ['fund1', 'fund2', 'medio'] as const

// ═══════════════════ Unidade 1 · Hello, I'm… ═══════════════════
export const greetings = lesson({
  id: 'ing-a1-greetings', subject: 'ingles', title: 'Greetings and introductions', levels: [...ALL], grade: 'A partir do 3º ano',
  topic: 'Inglês A1 — Primeiros passos', subtopic: 'Cumprimentos e apresentações',
  aliases: ['greetings', 'cumprimentos em ingles', 'saudacoes em ingles', 'hello', 'good morning', 'como se apresentar em ingles', 'nice to meet you', 'how are you'],
  summary: 'Cumprimente, se apresente, pergunte como a pessoa está e despeça-se em inglês.',
  intro: 'Hello! Toda conversa começa com um cumprimento. Vamos aprender os mais usados — e quando usar cada um.',
  objective: 'Cumprimentar conforme o período do dia, dizer o próprio nome, perguntar como a pessoa está e se despedir com educação.',
  next: ['ing-a1-alphabet-numbers'],
  skills: { v_greet: 'Cumprimentos pelo período do dia', g_intro: 'Apresentar-se (I\'m… / My name is…)', s_ask: 'Perguntas iniciais (How are you? What\'s your name?)', v_bye: 'Despedidas e palavras de cortesia' },
  blocks: [
    block('v_greet', 'Hello, hi, good morning…',
      'Para cumprimentar usamos Hello (neutro) e Hi (mais informal, entre amigos). Para marcar o período do dia: Good morning (de manhã), Good afternoon (à tarde) e Good evening (à noite, ao chegar). Atenção: Good night não é cumprimento — é usado para se despedir à noite ou antes de dormir.',
      'Hi, Ana! · Good morning, teacher! · Good evening, everyone.',
      'Hello e Hi = oi/olá. Good morning = bom dia. Good afternoon = boa tarde. Good evening = boa noite (quando você chega).',
      'Entrando na sala às 8h: “Good morning, teacher!”. Encontrando um amigo no intervalo: “Hi, Leo!”.',
      '1. Veja o horário. 2. Manhã → Good morning; tarde → Good afternoon; noite, chegando → Good evening. 3. Com amigos, pode usar só Hi.',
      'Em português, “boa noite” serve para chegar e para sair. Em inglês são duas expressões: Good evening (chegando) e Good night (saindo ou indo dormir).'),
    block('g_intro', 'I\'m… / My name is…',
      'Para se apresentar: I\'m + nome (forma curta de I am) ou My name is + nome. Quando alguém se apresenta, respondemos Nice to meet you (Prazer em conhecer você). A resposta costuma ser Nice to meet you, too.',
      '— Hi, I\'m Carla. — Hello, Carla. My name is Pedro. Nice to meet you. — Nice to meet you, too!',
      'I\'m Carla = Eu sou a Carla. My name is Pedro = Meu nome é Pedro. Nice to meet you = Prazer!',
      'No primeiro dia de aula: “Hi, I\'m Júlia. I\'m new here.”',
      '1. Cumprimente: Hi! 2. Diga seu nome: I\'m… 3. Quando a pessoa se apresentar, responda: Nice to meet you.',
      '“I\'m Pedro” e “My name is Pedro” dizem a mesma coisa. I\'m é o mais comum na conversa; My name is soa um pouco mais formal.'),
    block('s_ask', 'How are you? What\'s your name?',
      'Perguntas básicas: What\'s your name? (Qual é o seu nome?), How are you? (Como você está?) e Where are you from? (De onde você é?). Respostas comuns para How are you?: I\'m fine, thanks. / I\'m good. / Not bad. E, para devolver a pergunta: And you?',
      '— How are you? — I\'m fine, thanks. And you? — I\'m good!',
      'What\'s your name? = Qual é seu nome? How are you? = Tudo bem? I\'m fine, thanks = Estou bem, obrigado(a).',
      'Encontrando a vizinha: “Hi, Mrs. Silva! How are you?” — “I\'m good, thanks. And you?”',
      '1. Pergunte: How are you? 2. Ouça a resposta. 3. Quando perguntarem a você: I\'m fine, thanks. And you?',
      'What\'s your name? pergunta o nome; Where are you from? pergunta a origem; How are you? pergunta como a pessoa está — cada pergunta pede um tipo de resposta.'),
    block('v_bye', 'Goodbye e palavras de cortesia',
      'Para se despedir: Bye (informal), Goodbye, See you later / See you tomorrow (até mais / até amanhã) e Have a nice day (tenha um bom dia). Palavras de cortesia: please (por favor), thank you / thanks (obrigado/a), you\'re welcome (de nada), sorry (desculpe) e excuse me (com licença).',
      '— Thank you! — You\'re welcome. · Excuse me, where is the library? · See you tomorrow!',
      'Bye = tchau. Thank you = obrigado. You\'re welcome = de nada. Sorry = desculpa. Excuse me = com licença.',
      'Saindo da escola: “Bye, see you tomorrow!”. Pedindo passagem no ônibus: “Excuse me.”',
      '1. Vai embora? Bye / See you. 2. Recebeu ajuda? Thank you. 3. Agradeceram a você? You\'re welcome.',
      'Sorry é para pedir desculpas (esbarrou em alguém). Excuse me é para pedir licença ou chamar a atenção antes de perguntar algo.'),
  ],
  questions: [
    mc(1, 'v_greet', 'São 9 horas da manhã e você chega à escola. Qual cumprimento combina?', ['Good night', 'Good morning', 'Good evening', 'Goodbye'], 1, ['Pense no período do dia.', 'Nove horas é de manhã.', 'Morning = manhã.'], 'Good morning é o cumprimento da manhã.'),
    tf(1, 'v_bye', '“Good night” é usado para cumprimentar alguém que acabou de chegar à noite.', false, ['Good night é para chegar ou para sair?', 'Pense em “boa noite, vou dormir”.', 'Para chegar à noite há outra expressão.'], 'Falso. Ao chegar à noite: Good evening. Good night é despedida.'),
    fill(1, 'g_intro', 'Complete: “Hi! ___ name is Lucas.”', ['My'], ['Falta a palavra “meu”.', 'É um possessivo.', 'Começa com M.'], 'My name is Lucas = Meu nome é Lucas.'),
    mc(1, 's_ask', '— How are you? — ________', ['I\'m fine, thanks.', 'I\'m Lucas.', 'I\'m from Brazil.', 'Nice to meet you.'], 0, ['A pergunta é sobre como você está.', 'Não é sobre nome nem origem.', 'Fine = bem.'], '“I\'m fine, thanks” responde como você está.'),
    match(2, 'v_bye', 'Ligue cada expressão ao seu significado.', [['Thank you', 'Obrigado(a)'], ['You\'re welcome', 'De nada'], ['Excuse me', 'Com licença'], ['See you later', 'Até mais']], ['Welcome aparece na resposta a um agradecimento.', 'Excuse me é usado antes de pedir algo.', 'Later = mais tarde.'], 'Thank you = obrigado · You\'re welcome = de nada · Excuse me = com licença · See you later = até mais.'),
    mc(2, 'g_intro', 'Alguém diz: “Hi, I\'m Sofia. Nice to meet you.” Qual é a resposta mais natural?', ['Nice to meet you, too.', 'Good night.', 'You\'re welcome.', 'I\'m fine.'], 0, ['A pessoa disse “prazer em conhecer você”.', 'Devolvemos a mesma frase.', 'Com “too” no final.'], 'Respondemos “Nice to meet you, too”.'),
    order(2, 's_ask', 'Coloque o diálogo na ordem.', ['Hi! What\'s your name?', 'I\'m Rafa. And you?', 'I\'m Bia. Nice to meet you.', 'Nice to meet you, too!'], ['Primeiro alguém pergunta o nome.', 'Depois vem a resposta e a pergunta de volta.', 'O “too” sempre vem na resposta.'], 'Pergunta → resposta → apresentação → Nice to meet you, too.'),
    mc(2, 'v_bye', 'Você esbarrou sem querer em alguém no corredor. O que diz?', ['Sorry!', 'You\'re welcome.', 'Good morning.', 'See you later.'], 0, ['Você precisa se desculpar.', 'Não é agradecimento nem despedida.', 'Desculpa = …'], 'Sorry pede desculpas por algo que já aconteceu.'),
    mc(3, 'v_greet', 'Às 20h você chega a uma festa e, às 23h, vai embora. O que diz em cada momento?', ['Good evening… Good night.', 'Good night… Good evening.', 'Good afternoon… Goodbye.', 'Good morning… See you.'], 0, ['São dois momentos: chegar e sair.', 'Chegar à noite tem uma expressão; sair tem outra.', 'Evening = chegada; night = saída.'], 'Chegando: Good evening. Saindo: Good night.'),
    tf(3, 'g_intro', 'Em “I\'m Carla”, “I\'m” é a forma curta de “I am”.', true, ['O apóstrofo indica uma letra que sumiu.', 'I + am juntos.', 'Qual letra saiu?'], 'Verdadeiro: I\'m = I am (a letra “a” saiu).'),
  ],
  review: ['Good morning / afternoon / evening para chegar; Good night para sair', 'I\'m… / My name is… · Nice to meet you (too)', 'How are you? — I\'m fine, thanks. And you?', 'Please, thank you, you\'re welcome, sorry, excuse me'],
  relatedQuestions: ['como cumprimentar em inglês', 'como se apresentar em inglês', 'como dizer bom dia em inglês'],
  equivalentQuestions: eqs(['cumprimentos em inglês', 'greetings'], ['como dizer oi em inglês', 'como falar meu nome é em inglês', 'qual a diferença entre good evening e good night', 'o que significa nice to meet you', 'como responder how are you', 'como dizer obrigado em inglês', 'como dizer de nada em inglês', 'diferença entre sorry e excuse me']),
  commonDoubts: [{ q: 'Posso dizer Good night quando chego?', a: 'Não. Ao chegar à noite diga Good evening. Good night é para se despedir ou antes de dormir.' }, { q: 'Hi é falta de educação?', a: 'Não. Hi é informal, ótimo com amigos e colegas. Em situações formais, prefira Hello ou Good morning.' }],
  commonErrors: ['Usar Good night para cumprimentar ao chegar.', 'Responder “Nice to meet you” sem o “too” quando a outra pessoa já disse a frase.', 'Confundir sorry (desculpa) com excuse me (com licença).'],
  english: {
    cefr: 'A1', unit: 'a1-u1', order: 1, area: 'vocabulary', focus: ['vocabulary', 'speaking', 'listening'],
    vocabulary: [
      v('hello', 'olá', 'interjection', 'a word you say when you meet someone', 'Hello, my name is Ana.', 1, { pronunciation: 'rê-LÔU', synonyms: ['hi'] }),
      v('hi', 'oi', 'interjection', 'an informal way to say hello', 'Hi, Leo! How are you?', 1, { synonyms: ['hello'] }),
      v('morning', 'manhã', 'noun', 'the part of the day from sunrise to noon', 'Good morning, teacher!', 1, { collocations: ['good morning', 'this morning'] }),
      v('afternoon', 'tarde', 'noun', 'the part of the day after noon and before evening', 'Good afternoon, everyone.', 1),
      v('evening', 'noite (início)', 'noun', 'the part of the day from the end of the afternoon until night', 'Good evening, welcome to the party.', 2),
      v('goodbye', 'adeus / tchau', 'interjection', 'what you say when you leave', 'Goodbye! See you tomorrow.', 1, { synonyms: ['bye'], antonyms: ['hello'] }),
      v('please', 'por favor', 'adverb', 'a polite word you use when you ask for something', 'Can I have water, please?', 1),
      v('thanks', 'obrigado(a)', 'interjection', 'an informal way to say thank you', 'Thanks for the help!', 1, { synonyms: ['thank you'] }),
      v('sorry', 'desculpe', 'adjective', 'a word to say you feel bad about something you did', 'Sorry, I\'m late.', 1),
      v('welcome', 'de nada / bem-vindo', 'adjective', 'used in “you\'re welcome” as an answer to thank you', '— Thank you! — You\'re welcome.', 2),
      v('name', 'nome', 'noun', 'the word people use to call you', 'What\'s your name?', 1),
      v('fine', 'bem', 'adjective', 'healthy and happy; OK', 'I\'m fine, thanks.', 1, { synonyms: ['good', 'well'] }),
    ],
    grammar: {
      name: 'Apresentações: I\'m / My name is / What\'s your name?', when: 'Para dizer quem você é e perguntar o nome de alguém.',
      structure: 'I\'m + nome · My name is + nome · What\'s your name?',
      affirmative: ['I\'m Carla.', 'My name is Pedro.'], negative: ['I\'m not Carla. I\'m Carol.', 'My name isn\'t Pedro.'], interrogative: ['What\'s your name?', 'Are you Pedro?', 'How are you?'],
      compare: 'What\'s your name? (qual é o seu nome?) × How are you? (como você está?) — perguntas diferentes, respostas diferentes.',
      context: 'Primeiro dia num curso: “Hi, I\'m Leo. What\'s your name?”',
    },
    listening: {
      title: 'Primeiro dia de aula', kind: 'dialogo', rate: 0.9,
      script: ['Teacher: Good morning, everyone!', 'Tom: Good morning! Excuse me, is this room five?', 'Teacher: Yes, it is. What\'s your name?', 'Tom: My name is Tom. I\'m new here.', 'Teacher: Nice to meet you, Tom. I\'m Mrs. Lee.', 'Tom: Nice to meet you, too.'],
      questions: [
        mci(1, 'Em que período do dia acontece a conversa?', ['De manhã', 'À tarde', 'À noite', 'De madrugada'], 0, 'Eles dizem “Good morning”.'),
        mci(1, 'Qual é o nome do aluno?', ['Tim', 'Tom', 'Lee', 'Ted'], 1, 'Ele diz “My name is Tom”.'),
        mci(2, 'Por que Tom diz “Excuse me”?', ['Para pedir desculpas', 'Para pedir licença antes de perguntar', 'Para se despedir', 'Para agradecer'], 1, 'Excuse me chama a atenção antes de uma pergunta.'),
        mci(2, 'Quem é Mrs. Lee?', ['A professora', 'A mãe de Tom', 'Uma aluna nova', 'A diretora'], 0, 'Ela fala como “Teacher” no diálogo.'),
      ],
    },
    speaking: {
      situation: 'Você chegou numa turma nova de inglês e quer se apresentar.', vocabulary: ['hello', 'my name is', 'nice to meet you', 'how are you'],
      phrases: ['Hi! My name is…', 'Nice to meet you.', 'How are you?', 'I\'m fine, thanks. And you?'],
      example: 'Hi! My name is Ana. Nice to meet you. How are you?', challenge: 'Diga: um cumprimento + seu nome + “nice to meet you” + uma pergunta.', expected: ['hi', 'name', 'nice', 'meet', 'how'],
    },
    writing: {
      prompt: 'Escreva uma mensagem curta se apresentando para um novo colega de turma.', criteria: ['Tem cumprimento', 'Diz o seu nome', 'Faz uma pergunta', 'Termina com despedida'],
      model: 'Hi! My name is Ana. Nice to meet you. How are you? See you tomorrow!', keywords: ['hi', 'name', 'nice', 'how', 'see'], minWords: 10,
    },
    challenge: 'Cumprimente três pessoas hoje em inglês, cada vez com uma expressão diferente (Good morning, Hi, How are you?).',
    tips: ['Good night é despedida, não cumprimento.', 'Nice to meet you só se diz na primeira vez que você conhece alguém.'],
  },
  games: {
    blanks: [
      blank(1, '___ morning, teacher!', ['Good', 'Hello', 'Nice', 'Fine'], 0, 'Good morning = bom dia.'),
      blank(1, 'Nice to ___ you.', ['meet', 'see', 'know', 'look'], 0, 'Nice to meet you = prazer em conhecer você.'),
      blank(2, '— Thank you! — You\'re ___.', ['welcome', 'sorry', 'fine', 'please'], 0, 'You\'re welcome = de nada.'),
      blank(2, '— How are you? — I\'m ___, thanks.', ['fine', 'name', 'Tom', 'from'], 0, 'I\'m fine = estou bem.'),
      blank(3, '___ me, where is the bathroom?', ['Excuse', 'Sorry', 'Please', 'Thank'], 0, 'Excuse me pede licença antes de uma pergunta.'),
    ],
    dialogues: [
      dialogue(1, 'Conhecendo alguém', ['Ana: Hi! I\'m Ana.', 'Leo: Hello, Ana. I\'m Leo.', 'Ana: Nice to meet you, Leo.', 'Leo: Nice to meet you, too.'], 3, ['Nice to meet you, too.', 'Good night.', 'You\'re welcome.', 'I\'m from Brazil.'], 0, 'A resposta a “Nice to meet you” é “Nice to meet you, too”.'),
      dialogue(2, 'Na escola', ['Teacher: Good morning, Rafa. How are you?', 'Rafa: I\'m good, thanks. And you?', 'Teacher: I\'m fine. Is this your pen?', 'Rafa: Yes! Thank you!', 'Teacher: You\'re welcome.'], 1, ['I\'m good, thanks. And you?', 'My name is Rafa.', 'Good night!', 'Excuse me.'], 0, 'Depois de “How are you?”, dizemos como estamos e devolvemos a pergunta.'),
      dialogue(3, 'Hora de ir embora', ['Bia: It\'s late. I have to go.', 'Caio: OK! Have a nice evening.', 'Bia: Thanks! See you tomorrow.', 'Caio: Bye! Good night!'], 2, ['Thanks! See you tomorrow.', 'Nice to meet you.', 'Good morning!', 'I\'m fine.'], 0, 'Agradecemos o “have a nice evening” e nos despedimos.'),
    ],
    sequences: [
      words(1, 'My name is Ana', 'Em inglês: My name is + nome.'),
      words(2, 'Nice to meet you too', 'É a resposta quando alguém diz “Nice to meet you”.'),
      words(2, 'How are you today', 'Pergunta: How + are + you.'),
    ],
  },
  sources: enSources(),
})

export const alphabetNumbers = lesson({
  id: 'ing-a1-alphabet-numbers', subject: 'ingles', title: 'Alphabet, spelling and numbers', levels: [...ALL], grade: 'A partir do 3º ano',
  topic: 'Inglês A1 — Primeiros passos', subtopic: 'Alfabeto, soletrar e números',
  aliases: ['alfabeto em ingles', 'alphabet', 'soletrar em ingles', 'spelling', 'numeros em ingles', 'numbers', 'how do you spell', 'contar em ingles'],
  summary: 'Aprenda o alfabeto, soletre seu nome, diga números de 0 a 100 e informe idade e telefone.',
  intro: 'A, B, C… Em inglês as letras têm outros nomes. Vamos soletrar e contar!',
  objective: 'Soletrar nomes e palavras, entender letras soletradas, dizer números de 0 a 100, a idade e um número de telefone.',
  prerequisites: ['ing-a1-greetings'], next: ['ing-a1-countries'],
  skills: { p_letters: 'Nome das letras', s_spell: 'Soletrar (How do you spell…?)', v_num: 'Números de 0 a 20', v_tens: 'Dezenas e números até 100' },
  blocks: [
    block('p_letters', 'The alphabet',
      'O alfabeto inglês tem as mesmas 26 letras, mas o nome delas é diferente. As que mais confundem os brasileiros: A (êi), E (í), I (ái), G (dji), J (djêi), H (êitch), R (ár), W (dâbou-iú) e Y (uái). Dizer bem essas letras evita erros ao soletrar nomes e e-mails.',
      'A (êi) · E (í) · I (ái) · G (dji) · J (djêi)',
      'As letras são as mesmas, só o nome muda. A se diz “êi”, E se diz “í” e I se diz “ái”.',
      'Seu e-mail tem “g”? Ao ditar, diga “dji” — se disser “gê”, a pessoa pode escrever “j”.',
      '1. Ouça o nome da letra. 2. Repita. 3. Treine primeiro as vogais: A, E, I, O, U = êi, í, ái, ou, iú.',
      'Em português, E se diz “é” e I se diz “i”. Em inglês é como se fossem trocados: E = “í” e I = “ái”.'),
    block('s_spell', 'How do you spell it?',
      'Para pedir que alguém soletre: How do you spell your name? ou Can you spell that, please? Soletramos letra por letra. Letras repetidas podem ser ditas como “double”: “double L” = LL.',
      '— How do you spell your name? — B-E-L-L-A. (B, E, double L, A)',
      'Soletrar = dizer as letras uma por uma. Double L = duas letras L seguidas.',
      'Ao se inscrever num curso online, a atendente pergunta: “How do you spell your last name?”',
      '1. Ouça a pergunta: How do you spell…? 2. Diga as letras uma por uma. 3. Letras repetidas: “double”.',
      'Em português, dizemos “dois L” ou “L, L”. Em inglês é comum “double L”.'),
    block('v_num', 'Numbers 0–20',
      '0 zero · 1 one · 2 two · 3 three · 4 four · 5 five · 6 six · 7 seven · 8 eight · 9 nine · 10 ten · 11 eleven · 12 twelve · 13 thirteen · 14 fourteen · 15 fifteen · 16 sixteen · 17 seventeen · 18 eighteen · 19 nineteen · 20 twenty. De 13 a 19 os números terminam em -teen. Para a idade: I\'m 12 (years old).',
      'I\'m eleven. · My brother is fifteen.',
      'Um, dois, três = one, two, three. De 13 a 19 todos terminam em “teen”.',
      'Perguntaram sua idade: “How old are you?” — “I\'m thirteen.”',
      '1. Decore de 1 a 12 (são diferentes). 2. De 13 a 19: número + teen. 3. Para a idade: I\'m + número.',
      'Cuidado: thirteen (13) × thirty (30); fifteen (15) × fifty (50). No -teen, a força da voz fica no final: thir-TEEN; no -ty, no começo: THIR-ty.'),
    block('v_tens', 'Tens and numbers to 100',
      'Dezenas: 20 twenty · 30 thirty · 40 forty · 50 fifty · 60 sixty · 70 seventy · 80 eighty · 90 ninety · 100 one hundred. Os outros números juntam dezena + unidade com hífen: 21 twenty-one, 45 forty-five, 99 ninety-nine. Telefones são ditos número por número; o 0 pode ser “oh”.',
      '34 thirty-four · 58 fifty-eight · phone: 9-8-7-oh-5…',
      'Dezenas terminam em -ty. 21 = twenty-one (vinte + um).',
      'Preço de um livro: “It\'s forty-five reais.”',
      '1. Diga a dezena (forty). 2. Um hífen. 3. Diga a unidade (five): forty-five.',
      'Forty se escreve SEM u (não é “fourty”), mesmo vindo de four.'),
  ],
  questions: [
    mc(1, 'p_letters', 'Como se diz a letra E em inglês?', ['é', 'í', 'ái', 'êi'], 1, ['É diferente do português.', 'Parece o nosso I.', 'Soa como “í”.'], 'E se diz “í”.'),
    mc(1, 'v_num', 'Qual é o número “twelve”?', ['2', '11', '12', '20'], 2, ['Não termina em -teen.', 'Vem logo depois de eleven.', 'Eleven = 11.'], 'Twelve = 12.'),
    fill(1, 'v_num', 'Escreva em inglês o número 3.', ['three'], ['Começa com th.', 'Rima com free.', 'th-r-e-e.'], '3 = three.'),
    tf(1, 's_spell', 'Para pedir que alguém soletre o nome, perguntamos “How do you spell your name?”', true, ['Spell = soletrar.', 'A pergunta começa com How.', 'É exatamente essa a pergunta.'], 'Verdadeiro.'),
    match(2, 'v_tens', 'Ligue cada número à escrita correta.', [['30', 'thirty'], ['13', 'thirteen'], ['40', 'forty'], ['15', 'fifteen']], ['-teen = de 13 a 19.', '-ty = dezenas.', 'Forty não tem u.'], '30 thirty · 13 thirteen · 40 forty · 15 fifteen.'),
    mc(2, 'v_tens', 'Como se escreve 45?', ['fourty-five', 'forty-five', 'fourteen-five', 'forty five teen'], 1, ['Primeiro a dezena, depois a unidade.', 'Forty se escreve sem u.', 'Com hífen.'], '45 = forty-five.'),
    mc(2, 's_spell', 'A pessoa soletra: “M, A, double R, Y”. Qual é o nome?', ['Mary', 'Marry', 'Marey', 'Mari'], 1, ['Double R = duas letras R.', 'Conte as letras: M, A, R, R, Y.', 'São 5 letras.'], 'M-A-R-R-Y = Marry.'),
    mc(2, 'p_letters', 'Ao soletrar um e-mail, você diz “dji”. Que letra é?', ['J', 'G', 'D', 'Z'], 1, ['É uma letra que o brasileiro costuma trocar.', 'Não é J (djêi).', 'É a letra de “good”.'], '“dji” é o nome da letra G.'),
    order(3, 'v_tens', 'Coloque os números em ordem crescente.', ['thirteen', 'nineteen', 'thirty', 'fifty-two', 'ninety'], ['-teen são menores que as dezenas.', 'Thirteen (13) vem antes de nineteen (19).', 'Depois vêm 30, 52 e 90.'], '13, 19, 30, 52, 90.'),
    mc(3, 'v_num', 'Alguém diz “I\'m fif-TEEN”, com força no final. Qual é a idade?', ['50', '15', '5', '16'], 1, ['Força no final = -teen.', '-teen = de 13 a 19.', 'Fif + teen.'], 'Força no final indica -teen: 15.'),
  ],
  review: ['Vogais: A êi · E í · I ái · O ou · U iú', 'How do you spell…? · double L', '13–19 terminam em -teen; dezenas em -ty', 'Forty (sem u) · 21 = twenty-one'],
  relatedQuestions: ['alfabeto em inglês', 'como soletrar em inglês', 'números em inglês de 1 a 100'],
  equivalentQuestions: eqs(['alfabeto em inglês', 'números em inglês'], ['como falar as letras em inglês', 'como soletrar meu nome em inglês', 'como se escreve 40 em inglês', 'diferença entre thirteen e thirty', 'como dizer minha idade em inglês', 'como falar telefone em inglês', 'o que significa double l', 'como se diz a letra g em inglês']),
  commonErrors: ['Escrever “fourty” em vez de forty.', 'Confundir thirteen (13) com thirty (30).', 'Dizer as vogais com o som do português ao soletrar.'],
  english: {
    cefr: 'A1', unit: 'a1-u1', order: 2, area: 'pronunciation', focus: ['vocabulary', 'listening', 'speaking'],
    vocabulary: [
      v('spell', 'soletrar', 'verb', 'to say the letters of a word one by one', 'How do you spell your name?', 1),
      v('letter', 'letra', 'noun', 'one of the signs of the alphabet', 'A is the first letter.', 1),
      v('number', 'número', 'noun', 'a word or sign like 1, 2 or 3', 'What\'s your phone number?', 1),
      v('three', 'três', 'number', 'the number 3', 'I have three cats.', 1),
      v('twelve', 'doze', 'number', 'the number 12', 'My sister is twelve.', 1),
      v('thirteen', 'treze', 'number', 'the number 13', 'I\'m thirteen years old.', 2, { related: ['thirty'] }),
      v('thirty', 'trinta', 'number', 'the number 30', 'There are thirty students.', 2, { related: ['thirteen'] }),
      v('forty', 'quarenta', 'number', 'the number 40', 'The book costs forty reais.', 2),
      v('fifty', 'cinquenta', 'number', 'the number 50', 'Fifty people came.', 2),
      v('hundred', 'cem / centena', 'number', 'the number 100', 'One hundred days.', 2),
      v('old', 'velho / de idade', 'adjective', 'used to talk about age', 'How old are you?', 1),
      v('phone', 'telefone', 'noun', 'a device to call people', 'My phone number is 9-8-7-6.', 1),
    ],
    listening: {
      title: 'Ficha de inscrição', kind: 'dialogo', rate: 0.85,
      script: ['Woman: Hello! What\'s your name, please?', 'Boy: Daniel Brooks.', 'Woman: How do you spell Brooks?', 'Boy: B, R, double O, K, S.', 'Woman: Thank you. How old are you, Daniel?', 'Boy: I\'m fourteen.', 'Woman: And your phone number?', 'Boy: It\'s nine, eight, oh, three, five, two.'],
      questions: [
        mci(1, 'Qual é o sobrenome do menino?', ['Brokes', 'Brooks', 'Broks', 'Bruks'], 1, 'B-R-double O-K-S = Brooks.'),
        mci(2, 'Quantos anos ele tem?', ['4', '14', '40', '15'], 1, 'Ele diz “fourteen”.'),
        mci(2, 'O que significa “oh” no telefone?', ['A letra O', 'O número zero', 'Uma exclamação', 'O número 1'], 1, 'Ao dizer números de telefone, o 0 pode ser “oh”.'),
      ],
    },
    speaking: {
      situation: 'Você está se inscrevendo numa competição online e precisa soletrar seu nome e dizer sua idade.', vocabulary: ['spell', 'double', 'years old'],
      phrases: ['My name is…', 'It\'s spelled…', 'I\'m … years old.'], example: 'My name is Bella. B, E, double L, A. I\'m twelve years old.',
      challenge: 'Soletre seu nome completo e diga sua idade em inglês.', expected: ['name', 'old'],
    },
    writing: {
      prompt: 'Escreva, por extenso em inglês, a sua idade, a idade de duas pessoas da família e o número da sua casa.', criteria: ['Números por extenso', 'Dezenas com hífen', 'Frases com I\'m / is'],
      model: 'I\'m thirteen. My mother is forty-two. My brother is nine. My house number is fifty-five.', keywords: ['is', 'my', 'years'], minWords: 10,
    },
    challenge: 'Leia em inglês, em voz alta, os números de uma página de revista ou os preços de um folheto.',
    tips: ['Força no final (-TEEN) = 13 a 19; força no começo (TH-ir-ty) = dezenas.', 'Treine as vogais em inglês: êi, í, ái, ou, iú.'],
  },
  games: {
    words: [{ word: 'spell', clue: 'soletrar', difficulty: 1 }, { word: 'letter', clue: 'letra', difficulty: 1 }, { word: 'twelve', clue: '12', difficulty: 1 }, { word: 'thirteen', clue: '13', difficulty: 2 }, { word: 'forty', clue: '40', difficulty: 2 }, { word: 'hundred', clue: '100', difficulty: 3 }, { word: 'seven', clue: '7', difficulty: 1 }],
    blanks: [
      blank(1, 'How do you ___ your name?', ['spell', 'say', 'write', 'call'], 0, 'Spell = soletrar.'),
      blank(1, '— How ___ are you? — I\'m ten.', ['old', 'many', 'much', 'age'], 0, 'How old are you? pergunta a idade.'),
      blank(2, '45 = ___-five', ['forty', 'fourty', 'fourteen', 'fifty'], 0, 'Forty sem u.'),
      blank(2, '13 = ___', ['thirteen', 'thirty', 'three-ten', 'threeteen'], 0, '13 = thirteen.'),
      blank(3, 'M, A, ___ R, Y — Marry', ['double', 'two', 'twice', 'pair'], 0, 'Letras repetidas: double.'),
    ],
    pairs: [{ a: '50', b: 'fifty', difficulty: 1 }, { a: '15', b: 'fifteen', difficulty: 2 }, { a: '90', b: 'ninety', difficulty: 2 }, { a: '19', b: 'nineteen', difficulty: 2 }],
    sequences: [{ prompt: 'Coloque em ordem crescente · From smallest to biggest', items: ['eight', 'eleven', 'eighteen', 'eighty', 'one hundred'], difficulty: 2, explanation: '8, 11, 18, 80, 100.' }],
  },
  sources: enSources(),
})

export const countries = lesson({
  id: 'ing-a1-countries', subject: 'ingles', title: 'Countries and nationalities', levels: [...ALL], grade: 'A partir do 4º ano',
  topic: 'Inglês A1 — Primeiros passos', subtopic: 'Países, nacionalidades e idiomas',
  aliases: ['paises em ingles', 'nacionalidades em ingles', 'countries', 'nationalities', 'where are you from', 'idiomas em ingles', 'brazilian'],
  summary: 'Diga de onde você é, fale países, nacionalidades e idiomas e descubra onde o inglês é falado.',
  intro: 'Where are you from? Vamos viajar pelo mapa aprendendo países e nacionalidades.',
  objective: 'Perguntar e dizer de onde alguém é, diferenciar país, nacionalidade e idioma e escrevê-los com letra maiúscula.',
  prerequisites: ['ing-a1-greetings'], next: ['ing-verb-to-be'],
  skills: { s_from: 'Where are you from? / I\'m from…', v_nation: 'Nacionalidades', v_lang: 'Idiomas e letra maiúscula', r_world: 'Onde o inglês é falado' },
  blocks: [
    block('s_from', 'Where are you from?',
      'Para perguntar a origem: Where are you from? A resposta: I\'m from + país (I\'m from Brazil). Para outra pessoa: Where is she from? — She\'s from Canada.',
      '— Where are you from? — I\'m from Brazil. And you? — I\'m from Portugal.',
      'Where are you from? = De onde você é? I\'m from Brazil = Eu sou do Brasil.',
      'Num jogo online, alguém escreve: “Where are you from?”. Você responde: “I\'m from Brazil!”',
      '1. Pergunta: Where + are + you + from? 2. Resposta: I\'m from + país.',
      'Em português, “de onde você é?” começa com “de”. Em inglês o “from” vai para o FINAL da pergunta: Where are you from?'),
    block('v_nation', 'Nationalities',
      'A nacionalidade descreve a pessoa: I\'m Brazilian. Muitas terminam em -an/-ian (Brazilian, American, Canadian, Mexican), outras em -ish (British, Spanish, English, Irish) ou -ese (Japanese, Chinese, Portuguese); algumas são irregulares (French, Greek).',
      'Brazil → Brazilian · Spain → Spanish · Japan → Japanese · France → French',
      'País = lugar (Brazil). Nacionalidade = quem é de lá (Brazilian).',
      '“I\'m from Brazil. I\'m Brazilian.” As duas frases estão certas e dizem quase a mesma coisa.',
      '1. Saiba o país. 2. Veja a terminação: -ian, -ish, -ese ou irregular. 3. Use: I\'m + nacionalidade.',
      'Diga “I\'m from Brazil” (from + país) ou “I\'m Brazilian” (sem from + nacionalidade). “I\'m from Brazilian” está errado.'),
    block('v_lang', 'Languages and capital letters',
      'Muitos idiomas têm o mesmo nome da nacionalidade: English, Spanish, French, Japanese. No Brasil falamos Portuguese. Em inglês, países, nacionalidades e idiomas SEMPRE começam com letra maiúscula.',
      'People in Brazil speak Portuguese. · She speaks English and French.',
      'Idioma: English (inglês), Portuguese (português). Sempre com letra maiúscula.',
      'Numa rede social: “I speak Portuguese and a little English.”',
      '1. Idioma quase sempre = nacionalidade. 2. Letra maiúscula. 3. Use com speak: I speak…',
      'Em português escrevemos “brasileiro” e “inglês” com minúscula. Em inglês é obrigatório: Brazilian, English.'),
    block('r_world', 'English around the world',
      'O inglês é idioma oficial ou principal em muitos países, como Estados Unidos (the United States), Reino Unido (the United Kingdom), Canadá, Austrália, Irlanda, Nova Zelândia e África do Sul, e é idioma oficial na Índia e na Nigéria, entre outros. Por isso ele é tão usado para viagens, estudos e internet.',
      'English is spoken in Canada, Australia and Ireland.',
      'O inglês é falado em vários países do mundo, em quase todos os continentes.',
      'Um canal de ciência da Austrália e uma série dos Estados Unidos: os dois em inglês, com sotaques diferentes.',
      '1. Pense em países de vários continentes. 2. Muitos têm o inglês como idioma oficial. 3. Os sotaques mudam, o idioma é o mesmo.',
      'Assim como o português é falado no Brasil, em Portugal, em Angola e em Moçambique, o inglês é falado em muitos países — com sotaques diferentes.'),
  ],
  questions: [
    mc(1, 's_from', '— Where are you from? — ________', ['I\'m from Brazil.', 'I\'m Brazil.', 'I\'m twelve.', 'I\'m fine.'], 0, ['A pergunta é sobre origem.', 'Use from + país.', 'I\'m from…'], 'I\'m from Brazil.'),
    mc(1, 'v_nation', 'Qual é a nacionalidade de quem nasceu no Japão (Japan)?', ['Japanish', 'Japanese', 'Japanian', 'Japaner'], 1, ['A terminação é -ese.', 'Igual a Chinese.', 'Japan + ese.'], 'Japan → Japanese.'),
    tf(1, 'v_lang', 'Em inglês, “english” se escreve com letra minúscula, como em português.', false, ['Idiomas em inglês…', '…sempre com maiúscula.', 'English.'], 'Falso. English, Portuguese, Brazilian: sempre maiúscula.'),
    fill(1, 'v_nation', 'Complete: I\'m from Brazil. I\'m ________.', ['Brazilian'], ['É a nacionalidade.', 'Termina em -ian.', 'Brazil + ian.'], 'Brazil → Brazilian.'),
    match(2, 'v_nation', 'Ligue o país à nacionalidade.', [['Spain', 'Spanish'], ['Canada', 'Canadian'], ['France', 'French'], ['Portugal', 'Portuguese']], ['Spain termina em -ish.', 'Canada em -ian.', 'France é irregular.'], 'Spanish · Canadian · French · Portuguese.'),
    mc(2, 's_from', 'Qual pergunta está correta?', ['From where you are?', 'Where are you from?', 'Where you are from?', 'Where from are you?'], 1, ['A palavra de pergunta vem primeiro.', 'Depois o verbo to be.', 'From fica no final.'], 'Where are you from?'),
    mc(2, 'v_lang', 'Em qual país o idioma principal NÃO é o inglês?', ['Australia', 'Ireland', 'Mexico', 'New Zealand'], 2, ['Três desses países falam inglês.', 'Pense na América Latina.', 'Lá se fala espanhol.'], 'No México a língua principal é o espanhol.'),
    mc(2, 'r_world', 'Qual é o nome em inglês do Reino Unido?', ['the United States', 'the United Kingdom', 'the England Union', 'the British States'], 1, ['Kingdom = reino.', 'States = estados.', 'The United Kingdom.'], 'Reino Unido = the United Kingdom (UK).'),
    mc(3, 'v_nation', 'Qual frase está correta?', ['She\'s from Brazilian.', 'She\'s Brazil.', 'She\'s from Brazil.', 'She\'s from brazil.'], 2, ['From vem com o país.', 'Sem from vem a nacionalidade.', 'E sempre maiúscula.'], 'She\'s from Brazil. (ou She\'s Brazilian.)'),
    tf(3, 'r_world', 'O inglês é idioma oficial em países de mais de um continente.', true, ['Pense na Austrália.', 'E no Canadá.', 'Oceania, América, Europa, África…'], 'Verdadeiro: EUA, Canadá, Reino Unido, Irlanda, Austrália, Nova Zelândia, África do Sul, Índia…'),
  ],
  review: ['Where are you from? — I\'m from Brazil.', 'Nacionalidade: -ian, -ish, -ese ou irregular', 'Países, nacionalidades e idiomas com letra maiúscula', 'O inglês é falado em vários continentes'],
  relatedQuestions: ['como dizer de onde eu sou em inglês', 'nacionalidades em inglês', 'países que falam inglês'],
  equivalentQuestions: eqs(['nacionalidades em inglês', 'países em inglês'], ['como se diz brasileiro em inglês', 'como responder where are you from', 'como escrever japonês em inglês', 'quais países falam inglês', 'como dizer eu falo português em inglês', 'diferença entre brazil e brazilian', 'idiomas em inglês têm letra maiúscula']),
  commonErrors: ['Dizer “I\'m from Brazilian”.', 'Escrever nacionalidades e idiomas com letra minúscula.', 'Começar a pergunta com “From where”.'],
  english: {
    cefr: 'A1', unit: 'a1-u1', order: 3, area: 'vocabulary', focus: ['vocabulary', 'reading', 'writing'],
    vocabulary: [
      v('country', 'país', 'noun', 'a nation with its own land and government', 'Brazil is a big country.', 1),
      v('Brazilian', 'brasileiro(a)', 'adjective', 'from Brazil', 'I\'m Brazilian.', 1),
      v('English', 'inglês (idioma)', 'noun', 'the language of the UK, the US and other countries', 'I speak English.', 1),
      v('Spanish', 'espanhol', 'adjective', 'from Spain; the language of Spain and many countries', 'She speaks Spanish.', 1),
      v('French', 'francês', 'adjective', 'from France; the language of France', 'He\'s French.', 2),
      v('Japanese', 'japonês', 'adjective', 'from Japan; the language of Japan', 'My friend is Japanese.', 2),
      v('Canadian', 'canadense', 'adjective', 'from Canada', 'They are Canadian.', 2),
      v('Portuguese', 'português', 'noun', 'the language of Brazil and Portugal', 'People in Brazil speak Portuguese.', 1),
      v('speak', 'falar (idioma)', 'verb', 'to use a language', 'Do you speak English?', 1),
      v('from', 'de (origem)', 'preposition', 'used to say where someone was born or lives', 'I\'m from Recife.', 1),
    ],
    reading: {
      title: 'New pen pals', genre: 'mensagens de apresentação',
      text: 'Hi! I\'m Aiko. I\'m from Japan and I\'m twelve. I speak Japanese and a little English.\n\nHello! My name is Lucas. I\'m Brazilian. I live in Salvador. I speak Portuguese and English.\n\nHi, everyone! I\'m Emma. I\'m from Canada. I speak English and French.',
      questions: [
        mci(1, 'De onde é Aiko?', ['China', 'Japan', 'Canada', 'Brazil'], 1, 'Ela diz “I\'m from Japan”.'),
        mci(1, 'Que idiomas Lucas fala?', ['Portuguese and English', 'Only Portuguese', 'Spanish and English', 'French'], 0, '“I speak Portuguese and English.”'),
        mci(2, 'Quem fala francês?', ['Aiko', 'Lucas', 'Emma', 'Ninguém'], 2, 'Emma: “I speak English and French.”'),
        mci(3, 'Qual informação NÃO aparece no texto?', ['A idade de Aiko', 'A cidade de Lucas', 'A idade de Emma', 'O país de Emma'], 2, 'Só Aiko diz a idade.'),
      ],
    },
    speaking: {
      situation: 'Um intercambista pergunta de onde você é e que idiomas fala.', vocabulary: ['from', 'Brazilian', 'speak', 'Portuguese'],
      phrases: ['I\'m from Brazil.', 'I\'m Brazilian.', 'I speak Portuguese and a little English.'], example: 'I\'m from Brazil. I\'m Brazilian and I speak Portuguese.',
      challenge: 'Diga de onde você é, sua nacionalidade e os idiomas que você fala.', expected: ['from', 'brazil', 'speak', 'portuguese'],
    },
    writing: {
      prompt: 'Escreva um perfil curto para um site de amigos por correspondência: nome, país, nacionalidade e idiomas.', criteria: ['Nome', 'País com from', 'Nacionalidade', 'Idiomas com letra maiúscula'],
      model: 'Hi! My name is Carla. I\'m from Brazil. I\'m Brazilian. I speak Portuguese and English.', keywords: ['name', 'from', 'speak', 'brazil'], minWords: 12,
    },
    challenge: 'Escolha três países no mapa e diga, em inglês, a nacionalidade de quem nasce em cada um.',
  },
  games: {
    blanks: [
      blank(1, 'Where are you ___?', ['from', 'of', 'in', 'to'], 0, 'Where are you from?'),
      blank(1, 'I\'m from Spain. I\'m ___.', ['Spanish', 'Spain', 'Spanian', 'Spaniese'], 0, 'Spain → Spanish.'),
      blank(2, 'People in Brazil speak ___.', ['Portuguese', 'Brazilian', 'Spanish', 'Brazil'], 0, 'No Brasil falamos português.'),
      blank(2, 'She\'s from Canada. She\'s ___.', ['Canadian', 'Canadese', 'Canadish', 'Canada'], 0, 'Canada → Canadian.'),
      blank(3, 'Do you ___ English?', ['speak', 'talk', 'say', 'tell'], 0, 'Com idiomas usamos speak.'),
    ],
    map: {
      map: 'mundo', prompt: 'Países onde o inglês é idioma oficial ou principal · Where is English spoken?',
      targets: [
        { id: 'United States of America', label: 'the United States', clue: 'na América do Norte, ao sul do Canadá', difficulty: 1 },
        { id: 'United Kingdom', label: 'the United Kingdom', clue: 'uma ilha a noroeste da Europa', difficulty: 1 },
        { id: 'Canada', label: 'Canada', clue: 'o país mais ao norte da América', difficulty: 1 },
        { id: 'Australia', label: 'Australia', clue: 'um país-continente na Oceania', difficulty: 1 },
        { id: 'Ireland', label: 'Ireland', clue: 'a ilha a oeste do Reino Unido', difficulty: 3 },
        { id: 'New Zealand', label: 'New Zealand', clue: 'ilhas a sudeste da Austrália', difficulty: 3 },
        { id: 'South Africa', label: 'South Africa', clue: 'no extremo sul da África', difficulty: 2 },
        { id: 'India', label: 'India', clue: 'no sul da Ásia (o inglês é um dos idiomas oficiais)', difficulty: 2 },
      ],
    },
    sequences: [words(1, 'I am from Brazil', 'I + am + from + país.'), words(2, 'Where are you from', 'From fica no final da pergunta.')],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 2 · My people, my things ═══════════════════
export const family = lesson({
  id: 'ing-a1-family', subject: 'ingles', title: 'Family and possessive adjectives', levels: [...ALL], grade: 'A partir do 4º ano',
  topic: 'Inglês A1 — Primeiros passos', subtopic: 'Família e adjetivos possessivos',
  aliases: ['familia em ingles', 'family', 'membros da familia em ingles', 'possessive adjectives', 'my your his her', 'pronomes possessivos', 'genitivo', 'apostrofo s'],
  summary: 'Fale da sua família com my, your, his, her, our e their e mostre de quem é algo com ’s.',
  intro: 'This is my family! Vamos apresentar as pessoas que moram com a gente.',
  objective: 'Nomear membros da família, usar os adjetivos possessivos corretamente e indicar posse com ’s.',
  prerequisites: ['ing-verb-to-be'], next: ['ing-a1-this-that'],
  skills: { v_family: 'Membros da família', g_poss: 'My, your, his, her, its', g_poss2: 'Our e their', g_s: 'Posse com ’s' },
  blocks: [
    block('v_family', 'My family',
      'Família: mother/mom (mãe), father/dad (pai), parents (pais), sister (irmã), brother (irmão), grandmother/grandma (avó), grandfather/grandpa (avô), aunt (tia), uncle (tio), cousin (primo/prima), son (filho), daughter (filha).',
      'This is my mother. Her name is Rosa. · I have two brothers.',
      'Mother = mãe, father = pai, sister = irmã, brother = irmão.',
      'Mostrando uma foto: “This is my grandma and this is my cousin, Theo.”',
      '1. Mulheres: mother, sister, aunt, grandmother, daughter. 2. Homens: father, brother, uncle, grandfather, son. 3. Cousin serve para os dois.',
      'Cuidado com “parents”: parece “parentes”, mas significa PAI E MÃE. Parentes em geral = relatives.'),
    block('g_poss', 'My, your, his, her, its',
      'Os adjetivos possessivos vêm antes do substantivo e mostram de quem é: I → my (meu/minha), you → your (seu/sua), he → his (dele), she → her (dela), it → its (dele/dela, para coisas e animais). Eles não mudam para plural: my brothers, her cousins.',
      'This is Ana. Her brother is ten. · This is Leo. His sister is nine.',
      'My = meu/minha. Your = seu/sua. His = dele. Her = dela.',
      'Apresentando amigos: “This is Paulo. His dog is Max. This is Luna. Her cat is Mia.”',
      '1. Veja quem é o DONO. 2. Dono homem → his; dono mulher → her. 3. O possessivo vem antes da coisa.',
      'Em português, “seu irmão” pode ser dele ou dela. Em inglês você escolhe pelo dono: his brother (dele) ou her brother (dela).'),
    block('g_poss2', 'Our and their',
      'Para mais de uma pessoa: we → our (nosso/nossa) e they → their (deles/delas). Como os outros possessivos, não vão para o plural: our parents, their house.',
      'We love our grandparents. · They are my cousins. Their names are Bia and Rui.',
      'Our = nosso. Their = deles/delas.',
      'Na aula: “This is our classroom. Those are the students and their teacher.”',
      '1. Dono = nós → our. 2. Dono = eles/elas → their. 3. Nunca coloque -s no possessivo.',
      'Their (deles), there (lá) e they\'re (eles são) têm o mesmo som, mas escritas e sentidos diferentes.'),
    block('g_s', 'Possession with ’s',
      'Para dizer de quem é algo usando o nome da pessoa, colocamos ’s depois do dono: Maria\'s bag (a bolsa da Maria), my father\'s car (o carro do meu pai). Se o dono já termina em s por ser plural, só o apóstrofo: my parents\' house.',
      'This is Carlos\'s phone. · My sister\'s name is Clara.',
      'Maria\'s bag = a bolsa da Maria. O ’s mostra o dono.',
      'Achados e perdidos: “Is this Pedro\'s jacket?” — “Yes, it\'s Pedro\'s.”',
      '1. Escreva o dono. 2. Coloque ’s. 3. Depois a coisa: dono + ’s + coisa.',
      'Em português a ordem é “coisa + de + dono” (o carro do pai). Em inglês inverte: dono + ’s + coisa (Dad\'s car).'),
  ],
  questions: [
    mc(1, 'v_family', 'Como se diz “irmã” em inglês?', ['brother', 'sister', 'cousin', 'aunt'], 1, ['Brother é irmão.', 'É uma palavra feminina.', 'Começa com s.'], 'Irmã = sister.'),
    tf(1, 'v_family', '“Parents” significa “parentes”.', false, ['É um falso amigo.', 'Parents são duas pessoas específicas.', 'Pai e mãe.'], 'Falso. Parents = pai e mãe. Parentes = relatives.'),
    mc(1, 'g_poss', 'This is Ana. ___ dog is white.', ['His', 'Her', 'My', 'Its'], 1, ['O dono é a Ana.', 'Ana é mulher.', 'Possessivo feminino.'], 'O dono é mulher: her.'),
    fill(1, 'g_poss', 'Complete: I\'m Leo and this is ___ sister, Nina. (meu/minha)', ['my'], ['Possessivo de I.', 'Duas letras.', 'M…'], 'I → my.'),
    match(2, 'g_poss2', 'Ligue o pronome ao possessivo.', [['I', 'my'], ['he', 'his'], ['we', 'our'], ['they', 'their']], ['He termina com h, his também começa.', 'We → nosso.', 'They → deles.'], 'I-my · he-his · we-our · they-their.'),
    mc(2, 'g_poss', 'This is Mr. Silva. ___ son is a doctor.', ['Her', 'His', 'Their', 'Your'], 1, ['O dono é o Mr. Silva.', 'Mr. = senhor.', 'Dono homem.'], 'His son = o filho dele.'),
    mc(2, 'g_s', 'Como se diz “o carro do meu pai”?', ['the car of my father', 'my father\'s car', 'my fathers car', 'my car father\'s'], 1, ['Use o ’s.', 'Dono primeiro.', 'Dono + ’s + coisa.'], 'My father\'s car.'),
    mc(2, 'g_poss2', 'Tom and Kate are my cousins. ___ house is big.', ['Their', 'There', 'They\'re', 'Our'], 0, ['O dono são Tom e Kate.', 'É o possessivo, não “lá”.', 'Deles = …'], 'Their house = a casa deles.'),
    order(3, 'g_s', 'Organize: “O nome da irmã da Maria é Luísa.”', ['Maria\'s', 'sister\'s', 'name', 'is', 'Luísa'], ['Comece pelo primeiro dono.', 'Maria\'s sister = a irmã da Maria.', 'Depois: sister\'s name.'], 'Maria\'s sister\'s name is Luísa.'),
    mc(3, 'g_poss', 'Qual frase está correta?', ['They love theirs parents.', 'They love their parents.', 'They love there parents.', 'They love they parents.'], 1, ['Possessivo de they.', 'Não tem -s.', 'Não é “there”.'], 'They love their parents.'),
  ],
  review: ['Família: mother, father, sister, brother, grandma, cousin…', 'my, your, his (dele), her (dela), its, our, their', 'Possessivos não vão para o plural', 'Dono + ’s + coisa: Maria\'s bag'],
  relatedQuestions: ['família em inglês', 'diferença entre his e her', 'como usar apóstrofo s'],
  equivalentQuestions: eqs(['família em inglês', 'possessivos em inglês'], ['como se diz irmão em inglês', 'como se diz avó em inglês', 'parents significa parentes', 'quando usar his e her', 'diferença entre their e there', 'como dizer o carro do meu pai em inglês', 'o que é genitivo em inglês']),
  commonErrors: ['Usar his/her pelo gênero da coisa, e não do dono.', 'Achar que parents = parentes.', 'Colocar -s no possessivo (theirs parents).'],
  english: {
    cefr: 'A1', unit: 'a1-u2', order: 1, area: 'grammar', focus: ['vocabulary', 'grammar', 'writing'],
    vocabulary: [
      v('mother', 'mãe', 'noun', 'your female parent', 'My mother is a nurse.', 1, { synonyms: ['mom'] }),
      v('father', 'pai', 'noun', 'your male parent', 'My father cooks on Sundays.', 1, { synonyms: ['dad'] }),
      v('parents', 'pais (pai e mãe)', 'noun', 'your mother and father', 'My parents are at work.', 2, { related: ['relatives'] }),
      v('sister', 'irmã', 'noun', 'a girl or woman with the same parents as you', 'My sister is older than me.', 1),
      v('brother', 'irmão', 'noun', 'a boy or man with the same parents as you', 'I have one brother.', 1),
      v('cousin', 'primo(a)', 'noun', 'the child of your aunt or uncle', 'My cousin lives in Manaus.', 2),
      v('aunt', 'tia', 'noun', 'the sister of your mother or father', 'My aunt is a teacher.', 2, { related: ['uncle'] }),
      v('uncle', 'tio', 'noun', 'the brother of your mother or father', 'My uncle plays the guitar.', 2, { related: ['aunt'] }),
      v('grandmother', 'avó', 'noun', 'the mother of your mother or father', 'My grandmother makes great cakes.', 1, { synonyms: ['grandma'] }),
      v('daughter', 'filha', 'noun', 'a female child', 'They have one daughter.', 2, { related: ['son'] }),
    ],
    grammar: {
      name: 'Possessive adjectives', when: 'Para dizer de quem é algo; vêm antes do substantivo.', structure: 'my · your · his · her · its · our · their + substantivo',
      affirmative: ['This is my brother.', 'Her name is Lia.'], negative: ['That isn\'t my bag.', 'His house isn\'t big.'], interrogative: ['Is this your pen?', 'What\'s her name?'],
      compare: 'his (dono homem) × her (dono mulher) — em português “seu/sua” não mostra o dono; em inglês mostra.',
      context: 'Apresentando fotos da família para um colega estrangeiro.',
    },
    reading: {
      title: 'My family photo', genre: 'post em rede social',
      text: 'This is a photo of my family. That\'s my dad, Marcos. His job is cool: he\'s a pilot! Next to him is my mom, Júlia. Her hobby is painting. The two kids are my brother and me. Our dog, Bolt, is in the photo too. Its ears are enormous!',
      questions: [
        mci(1, 'Qual é a profissão do pai?', ['Pintor', 'Piloto', 'Professor', 'Médico'], 1, '“he\'s a pilot”.'),
        mci(2, 'A que se refere “Her hobby”?', ['Ao hobby do pai', 'Ao hobby da mãe', 'Ao hobby do irmão', 'Ao hobby do cachorro'], 1, 'Her refere-se à mãe, Júlia.'),
        mci(2, 'A quem se refere “Its ears”?', ['Ao pai', 'À foto', 'Ao cachorro Bolt', 'Ao irmão'], 2, 'Its é usado para animais e coisas: as orelhas do Bolt.'),
        mci(3, 'Quem escreveu o post?', ['A mãe', 'Um dos filhos', 'O pai', 'Um primo'], 1, 'Ele diz “my brother and me”: é um dos filhos.'),
      ],
    },
    writing: {
      prompt: 'Descreva uma foto da sua família (ou de uma família imaginária) usando pelo menos três possessivos diferentes.', criteria: ['Nomeia pelo menos 3 pessoas', 'Usa my, his/her e our/their', 'Frases curtas com is/are'],
      model: 'This is my family. My mother is Ana. Her job is teacher. My father is Rui. His hobby is soccer. Our cat is Tom.', keywords: ['my', 'his', 'her', 'our'], minWords: 18,
    },
    challenge: 'Faça uma árvore genealógica simples e escreva o nome de cada pessoa em inglês (mother, uncle, cousin…).',
  },
  games: {
    blanks: [
      blank(1, 'This is Leo. ___ sister is Ana.', ['His', 'Her', 'Their', 'Its'], 0, 'Dono homem: his.'),
      blank(1, 'My mother\'s sister is my ___.', ['aunt', 'uncle', 'cousin', 'niece'], 0, 'A irmã da mãe é a tia.'),
      blank(2, 'We love ___ grandparents.', ['our', 'we', 'us', 'ours'], 0, 'We → our.'),
      blank(2, 'This is ___ bag. (a bolsa da Maria)', ['Maria\'s', 'Marias', 'of Maria', 'Maria'], 0, 'Dono + ’s.'),
      blank(3, 'The dog is happy. ___ tail is moving.', ['Its', 'It\'s', 'His', 'Their'], 0, 'Possessivo de it: its (sem apóstrofo).'),
    ],
    sequences: [words(1, 'This is my brother', 'This is + possessivo + pessoa.'), words(2, 'Her name is Clara', 'Her vem antes do substantivo.'), words(3, 'My father\'s car is blue', 'Dono + ’s + coisa.')],
  },
  sources: enSources(),
})

export const thisThat = lesson({
  id: 'ing-a1-this-that', subject: 'ingles', title: 'This, that, plurals and a/an', levels: [...ALL], grade: 'A partir do 4º ano',
  topic: 'Inglês A1 — Primeiros passos', subtopic: 'Demonstrativos, plural e artigos',
  aliases: ['this that these those', 'demonstrativos em ingles', 'plural em ingles', 'a an', 'artigo indefinido', 'objetos da sala em ingles', 'classroom objects'],
  summary: 'Aponte e nomeie objetos com this, that, these e those, faça o plural e use a ou an.',
  intro: 'What\'s this? It\'s a pen! Vamos nomear o que tem ao nosso redor.',
  objective: 'Usar this/that/these/those pela distância e quantidade, formar plurais regulares e irregulares e escolher entre a e an pelo som.',
  prerequisites: ['ing-verb-to-be'], next: ['ing-a1-colors-adjectives'],
  skills: { g_demo: 'This, that, these, those', g_plural: 'Plural dos substantivos', g_article: 'A ou an', v_class: 'Objetos da sala de aula' },
  blocks: [
    block('g_demo', 'This, that, these, those',
      'Perto de você: this (isto/este, singular) e these (estes, plural). Longe: that (aquilo/aquele, singular) e those (aqueles, plural). Perguntas: What\'s this? / What are those?',
      'This is my pen. · Those are my friends over there.',
      'This = isto (perto). That = aquilo (longe). These e those são os plurais.',
      'Na mesa: “This is my notebook.” Apontando para a janela: “That is a bird!”',
      '1. Está perto ou longe? 2. É um ou vários? 3. Perto+um: this; perto+vários: these; longe+um: that; longe+vários: those.',
      'Pense em português: este/estes (perto) × aquele/aqueles (longe). A lógica é a mesma.'),
    block('g_plural', 'Plurals',
      'A maioria ganha -s (book → books). Terminadas em -s, -sh, -ch, -x ganham -es (box → boxes). Consoante + y vira -ies (city → cities). Alguns são irregulares: man → men, woman → women, child → children, person → people, foot → feet, tooth → teeth, mouse → mice.',
      'one book, two books · one box, three boxes · one child, four children',
      'Plural é mais de um: quase sempre é só colocar -s.',
      'Lista de material: two pencils, three notebooks, one eraser.',
      '1. Veja o final da palavra. 2. -s/-sh/-ch/-x → -es. 3. Consoante + y → -ies. 4. Decore os irregulares.',
      'Em português também temos plurais especiais (pão → pães). Em inglês, os irregulares mais usados são poucos: men, women, children, people.'),
    block('g_article', 'A or an?',
      'Usamos a ou an antes de UM substantivo contável no singular. A escolha depende do SOM que vem depois: a antes de som de consoante (a pen, a university) e an antes de som de vogal (an apple, an hour).',
      'a book · an eraser · an umbrella · a uniform',
      'A e an significam “um/uma”. An vem antes de palavras que começam com som de vogal.',
      'Na cantina: “I want an orange and a sandwich.”',
      '1. Fale a palavra em voz alta. 2. Começa com som de vogal? → an. 3. Senão → a.',
      'O que vale é o SOM, não a letra: an hour (o h é mudo) e a university (soa “iu”).'),
    block('v_class', 'Classroom objects',
      'Objetos da sala: pen (caneta), pencil (lápis), eraser (borracha), ruler (régua), notebook (caderno), book (livro), backpack (mochila), desk (carteira), board (quadro), scissors (tesoura — sempre plural), glue (cola).',
      'What\'s this? It\'s a ruler. · Those are my scissors.',
      'Pen = caneta, pencil = lápis, eraser = borracha, notebook = caderno.',
      'Pedindo emprestado: “Can I borrow your eraser, please?”',
      '1. Olhe ao redor da sala. 2. Diga o nome de cada objeto. 3. Use It\'s a/an…',
      'Scissors é sempre plural em inglês (como “óculos” em português): These are my scissors.'),
  ],
  questions: [
    mc(1, 'g_demo', 'O livro está na sua mão. Você diz: “___ is my book.”', ['This', 'That', 'These', 'Those'], 0, ['Está perto ou longe?', 'É um só livro.', 'Perto + singular.'], 'Perto e singular: this.'),
    mc(1, 'g_article', 'Qual está correto?', ['a apple', 'an apple', 'an pen', 'a eraser'], 1, ['Apple começa com som de vogal.', 'Antes de vogal usamos an.', 'An apple.'], 'An apple (som de vogal).'),
    fill(1, 'g_plural', 'Escreva o plural de “book”.', ['books'], ['É um plural regular.', 'Só acrescente uma letra.', 'Book + s.'], 'Books.'),
    tf(1, 'v_class', '“Eraser” significa borracha.', true, ['Erase = apagar.', 'O que apaga o lápis?', 'Borracha.'], 'Verdadeiro.'),
    match(2, 'g_plural', 'Ligue o singular ao plural.', [['child', 'children'], ['box', 'boxes'], ['city', 'cities'], ['man', 'men']], ['Child é irregular.', 'Box termina em x.', 'City: consoante + y.'], 'children · boxes · cities · men.'),
    mc(2, 'g_demo', 'Os pássaros estão lá no telhado. “___ are birds.”', ['This', 'These', 'That', 'Those'], 3, ['Longe.', 'Vários.', 'Longe + plural.'], 'Longe e plural: those.'),
    mc(2, 'g_article', 'Complete: “It\'s ___ hour.”', ['a', 'an', 'two', '—'], 1, ['O h de hour é pronunciado?', 'Não, é mudo.', 'Começa com som de vogal.'], 'An hour: o h é mudo.'),
    mc(2, 'g_plural', 'Qual é o plural de “person”?', ['persons', 'people', 'peoples', 'personas'], 1, ['É irregular.', 'Muito usado.', 'Começa com p-e-o.'], 'Person → people.'),
    order(3, 'g_demo', 'Organize: “Estas são as minhas canetas.”', ['These', 'are', 'my', 'pens'], ['Plural e perto: these.', 'Verbo no plural: are.', 'Possessivo antes do objeto.'], 'These are my pens.'),
    mc(3, 'g_article', 'Qual frase está correta?', ['She is an university student.', 'She is a university student.', 'She is university student.', 'She is an student.'], 1, ['University começa com vogal, mas…', '…o som é “iu”.', 'Som de consoante → a.'], 'A university: o som é “iu”, de consoante.'),
  ],
  review: ['This/these (perto) · that/those (longe)', 'Plural: -s, -es, -ies e irregulares (children, people)', 'A antes de som de consoante, an antes de som de vogal', 'Objetos: pen, pencil, eraser, ruler, notebook…'],
  relatedQuestions: ['diferença entre this e that', 'quando usar a e an', 'plural em inglês'],
  equivalentQuestions: eqs(['this e that', 'plural em inglês', 'a e an'], ['diferença entre these e those', 'plural de child', 'plural de person', 'por que é an hour', 'objetos da sala de aula em inglês', 'como se diz borracha em inglês', 'o que é artigo indefinido em inglês']),
  commonErrors: ['Usar a antes de som de vogal (a apple).', 'Esquecer os plurais irregulares (childs, persons).', 'Usar this para coisas longe.'],
  english: {
    cefr: 'A1', unit: 'a1-u2', order: 2, area: 'grammar', focus: ['grammar', 'vocabulary'],
    vocabulary: [
      v('pen', 'caneta', 'noun', 'a thing you use to write with ink', 'Can I use your pen?', 1),
      v('pencil', 'lápis', 'noun', 'a wooden thing you use to write or draw', 'This is my pencil.', 1),
      v('eraser', 'borracha', 'noun', 'a small thing that removes pencil marks', 'I need an eraser.', 1),
      v('ruler', 'régua', 'noun', 'a flat object used to measure and draw lines', 'The ruler is thirty centimeters long.', 2),
      v('notebook', 'caderno', 'noun', 'a book with blank pages to write in', 'Open your notebook, please.', 1),
      v('backpack', 'mochila', 'noun', 'a bag you carry on your back', 'My backpack is heavy.', 2),
      v('desk', 'carteira / mesa', 'noun', 'a table where you study or work', 'Put your books on the desk.', 1),
      v('scissors', 'tesoura', 'noun', 'a tool with two blades for cutting paper', 'These scissors are sharp.', 3),
      v('children', 'crianças', 'noun', 'plural of child', 'The children are in the park.', 2),
      v('people', 'pessoas', 'noun', 'plural of person', 'Many people speak English.', 2),
    ],
    grammar: {
      name: 'Demonstratives + a/an', when: 'Para apontar e nomear coisas perto ou longe.', structure: 'This/That is a/an + substantivo · These/Those are + plural',
      affirmative: ['This is a pen.', 'Those are my shoes.'], negative: ['That isn\'t my bag.', 'These aren\'t pencils.'], interrogative: ['What\'s this?', 'Are those your books?'],
      compare: 'this/these = perto · that/those = longe.', context: 'Arrumando a mochila no começo do ano.',
    },
    listening: {
      title: 'Na papelaria', kind: 'dialogo', rate: 0.9,
      script: ['Clerk: Hi! Can I help you?', 'Girl: Yes, please. How much is this ruler?', 'Clerk: It\'s three dollars.', 'Girl: And those notebooks over there?', 'Clerk: They\'re two dollars each.', 'Girl: OK. Two notebooks and an eraser, please.'],
      questions: [
        mci(1, 'Quanto custa a régua?', ['2 dólares', '3 dólares', '4 dólares', '1 dólar'], 1, '“It\'s three dollars.”'),
        mci(2, 'Por que ela diz “those notebooks”?', ['Porque estão perto', 'Porque estão longe e são vários', 'Porque é um só', 'Porque são dela'], 1, 'Those = longe + plural (“over there”).'),
        mci(2, 'O que ela compra no final?', ['Uma régua', 'Dois cadernos e uma borracha', 'Três canetas', 'Um caderno'], 1, '“Two notebooks and an eraser.”'),
      ],
    },
    challenge: 'Aponte para 5 objetos ao seu redor e diga: This is a… / That is an… / These are…',
  },
  games: {
    blanks: [
      blank(1, 'I have ___ orange.', ['an', 'a', 'two', 'these'], 0, 'Orange começa com som de vogal: an.'),
      blank(1, '___ are my shoes. (perto)', ['These', 'This', 'That', 'Those'], 0, 'Perto e plural: these.'),
      blank(2, 'Look at ___ plane in the sky!', ['that', 'this', 'these', 'those'], 0, 'Longe e singular: that.'),
      blank(2, 'There are three ___ in the park.', ['children', 'childs', 'childrens', 'child'], 0, 'Child → children.'),
      blank(3, 'He is ___ honest man.', ['an', 'a', 'the', '—'], 0, 'O h de honest é mudo: an honest.'),
    ],
    sequences: [words(1, 'This is a pencil', 'This is + a + objeto.'), words(2, 'Those are my books', 'Those + are + plural.')],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 3 · Every day ═══════════════════
export const timeDays = lesson({
  id: 'ing-a1-time-days', subject: 'ingles', title: 'Time, days and months', levels: [...ALL], grade: 'A partir do 4º ano',
  topic: 'Inglês A1 — Meu dia a dia', subtopic: 'Horas, dias da semana, meses e datas',
  aliases: ['horas em ingles', 'what time is it', 'dias da semana em ingles', 'meses em ingles', 'datas em ingles', 'days of the week', 'months', 'in on at tempo'],
  summary: 'Diga as horas, os dias da semana, os meses e as datas, com in, on e at.',
  intro: 'What time is it? Vamos organizar o tempo em inglês.',
  objective: 'Perguntar e dizer as horas, nomear dias e meses com letra maiúscula e usar at (horas), on (dias e datas) e in (meses e anos).',
  prerequisites: ['ing-a1-alphabet-numbers'], next: ['ing-simple-present'],
  skills: { v_time: 'Dizer as horas', v_days: 'Dias da semana', v_months: 'Meses e datas', g_prep: 'At, on, in para tempo' },
  blocks: [
    block('v_time', 'What time is it?',
      'Pergunta: What time is it? Resposta: It\'s + hora. Horas cheias: It\'s three o\'clock. Com minutos: It\'s three fifteen (3:15), It\'s four thirty (4:30). Também: quarter past (e quinze), half past (e meia), quarter to (quinze para). Am = manhã; pm = tarde e noite.',
      '7:00 seven o\'clock · 7:30 seven thirty / half past seven · 6:45 six forty-five / quarter to seven',
      'What time is it? = Que horas são? It\'s five o\'clock = São cinco horas.',
      'Combinando um jogo: “The game is at four thirty pm.”',
      '1. It\'s… 2. Diga a hora. 3. Diga os minutos (ou o’clock se for hora cheia).',
      'Em inglês é comum o relógio de 12 horas, com am e pm. 15h = 3 pm.'),
    block('v_days', 'Days of the week',
      'Monday (segunda), Tuesday (terça), Wednesday (quarta), Thursday (quinta), Friday (sexta), Saturday (sábado) e Sunday (domingo). Sempre com letra maiúscula. Saturday e Sunday formam o weekend (fim de semana).',
      'I have English on Monday and Wednesday.',
      'Monday = segunda-feira… Sunday = domingo. Todos terminam em -day.',
      'Sua agenda: “Soccer on Tuesday, music class on Thursday.”',
      '1. Decore em ordem, começando pela segunda. 2. Letra maiúscula. 3. Use on antes do dia.',
      'Tuesday (terça) e Thursday (quinta) confundem: Tues = “tiuz”, Thurs = “thârz”. Pense: T-U terça, T-H quinta.'),
    block('v_months', 'Months and dates',
      'January, February, March, April, May, June, July, August, September, October, November, December — com letra maiúscula. Nas datas, usamos números ordinais: first (1st), second (2nd), third (3rd), fourth (4th)… twentieth (20th), twenty-first (21st). My birthday is on March 3rd.',
      'Today is May 10th. · Christmas is on December 25th.',
      'Os meses parecem com o português: April = abril, May = maio. Datas usam first, second, third…',
      '“When is your birthday?” — “It\'s on July 21st.”',
      '1. Mês com maiúscula. 2. Dia como ordinal: 1st, 2nd, 3rd, 4th… 3. Use on antes da data.',
      'Nos Estados Unidos a data curta costuma vir mês/dia (03/10 = 10 de março); no Reino Unido, dia/mês, como no Brasil.'),
    block('g_prep', 'At, on, in (time)',
      'At para horas e momentos exatos (at 7 o\'clock, at night, at noon). On para dias e datas (on Monday, on May 5th, on my birthday). In para meses, anos, estações e partes do dia (in July, in 2025, in the summer, in the morning).',
      'I wake up at 6:30. · We have tests on Friday. · My birthday is in June.',
      'At = hora. On = dia. In = mês e ano.',
      'Convite: “The party is on Saturday, at 8 pm, in December.”',
      '1. É hora? at. 2. É dia/data? on. 3. É mês, ano ou período maior? in.',
      'Imagine uma pirâmide: in (o maior: ano, mês) → on (dia) → at (o menor: hora).'),
  ],
  questions: [
    mc(1, 'v_days', 'Qual é o dia depois de Monday?', ['Wednesday', 'Tuesday', 'Thursday', 'Sunday'], 1, ['Monday é segunda.', 'O próximo é terça.', 'Tues…'], 'Monday → Tuesday.'),
    mc(1, 'v_time', '“It\'s eight o\'clock” quer dizer:', ['São oito horas', 'São oito e meia', 'Faltam oito minutos', 'São oito e quinze'], 0, ['O\'clock = hora cheia.', 'Sem minutos.', 'Oito em ponto.'], 'Hora cheia: 8:00.'),
    fill(1, 'v_months', 'Qual mês vem depois de “January”?', ['February'], ['Segundo mês do ano.', 'Fevereiro.', 'Feb…'], 'January → February.'),
    tf(1, 'v_days', 'Em inglês, os dias da semana são escritos com letra maiúscula.', true, ['Igual aos idiomas e nacionalidades.', 'Monday, Friday…', 'Sim, sempre.'], 'Verdadeiro.'),
    match(2, 'g_prep', 'Ligue cada expressão à preposição correta.', [['7 o\'clock', 'at'], ['Monday', 'on'], ['July', 'in']], ['Hora exata: at.', 'Dia: on.', 'Mês: in.'], 'at 7 o\'clock · on Monday · in July.'),
    mc(2, 'v_time', '4:30 pode ser dito como:', ['half past four', 'half to four', 'four half', 'quarter past four'], 0, ['Trinta minutos = meia.', 'Passou da hora: past.', 'Half past.'], '4:30 = half past four (ou four thirty).'),
    mc(2, 'g_prep', 'My birthday is ___ March 3rd.', ['in', 'at', 'on', 'of'], 2, ['É uma data com dia.', 'Dia/data usa…', 'On.'], 'Datas com dia: on.'),
    mc(2, 'v_months', 'Como se escreve o ordinal de 3 (terceiro)?', ['3th', '3rd', '3nd', '3st'], 1, ['Third.', 'As duas últimas letras.', 'Th-i-r-D.'], 'Third = 3rd.'),
    order(3, 'v_days', 'Coloque os dias em ordem, começando na segunda.', ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], ['Segunda é Monday.', 'Quarta é Wednesday.', 'Quinta é Thursday.'], 'Monday, Tuesday, Wednesday, Thursday, Friday.'),
    mc(3, 'g_prep', 'Qual frase está totalmente correta?', ['I play soccer in Saturday at the morning.', 'I play soccer on Saturday in the morning.', 'I play soccer at Saturday on the morning.', 'I play soccer on Saturday at morning.'], 1, ['Dia da semana usa on.', 'Parte do dia usa in the…', 'On Saturday in the morning.'], 'On Saturday (dia) in the morning (parte do dia).'),
  ],
  review: ['What time is it? — It\'s … o\'clock / half past / quarter to', 'Dias e meses com letra maiúscula', 'Datas com ordinais: 1st, 2nd, 3rd, 4th…', 'At (hora) · on (dia/data) · in (mês/ano/período)'],
  relatedQuestions: ['como falar as horas em inglês', 'dias da semana em inglês', 'quando usar in on at'],
  equivalentQuestions: eqs(['horas em inglês', 'dias da semana em inglês', 'meses em inglês'], ['como se diz quinta-feira em inglês', 'diferença entre tuesday e thursday', 'como escrever datas em inglês', 'o que significa half past', 'quando usar on e in com datas', 'como dizer meu aniversário é em inglês', 'o que é am e pm']),
  commonErrors: ['Usar in com dias (in Monday).', 'Escrever dias e meses com minúscula.', 'Trocar Tuesday e Thursday.'],
  english: {
    cefr: 'A1', unit: 'a1-u3', order: 1, area: 'vocabulary', focus: ['vocabulary', 'listening', 'grammar'],
    vocabulary: [
      v('Monday', 'segunda-feira', 'noun', 'the day after Sunday', 'I have English on Monday.', 1),
      v('Tuesday', 'terça-feira', 'noun', 'the day after Monday', 'The test is on Tuesday.', 2, { related: ['Thursday'] }),
      v('Wednesday', 'quarta-feira', 'noun', 'the day in the middle of the week', 'We swim on Wednesday.', 2),
      v('Thursday', 'quinta-feira', 'noun', 'the day after Wednesday', 'My music class is on Thursday.', 2, { related: ['Tuesday'] }),
      v('Friday', 'sexta-feira', 'noun', 'the day before Saturday', 'I love Friday!', 1),
      v('weekend', 'fim de semana', 'noun', 'Saturday and Sunday', 'What do you do on the weekend?', 1),
      v('month', 'mês', 'noun', 'one of the twelve parts of a year', 'December is my favorite month.', 1),
      v('birthday', 'aniversário', 'noun', 'the day you were born, every year', 'My birthday is in May.', 1),
      v('clock', 'relógio (de parede)', 'noun', 'a thing that shows the time', 'The clock is on the wall.', 1),
      v('today', 'hoje', 'adverb', 'this day', 'Today is Friday.', 1, { related: ['tomorrow', 'yesterday'] }),
    ],
    listening: {
      title: 'Agenda da semana', kind: 'texto', rate: 0.9,
      script: ['Hi, this is Mia. On Monday I have swimming at four o\'clock.', 'On Wednesday I have piano at half past five.', 'On Saturday, in the morning, I visit my grandma.', 'And my birthday is on June tenth!'],
      questions: [
        mci(1, 'Em que dia Mia nada?', ['Monday', 'Wednesday', 'Saturday', 'Sunday'], 0, '“On Monday I have swimming.”'),
        mci(2, 'Que horas é a aula de piano?', ['5:00', '5:30', '4:00', '4:30'], 1, 'Half past five = 5:30.'),
        mci(2, 'Quando ela visita a avó?', ['Sábado de manhã', 'Sábado à noite', 'Domingo de manhã', 'Quarta à tarde'], 0, '“On Saturday, in the morning.”'),
        mci(3, 'Quando é o aniversário dela?', ['10 de julho', '10 de junho', '1º de junho', '20 de junho'], 1, 'June tenth = 10 de junho.'),
      ],
    },
    writing: {
      prompt: 'Escreva sua agenda da semana em inglês: três atividades, com o dia e a hora.', criteria: ['Dias com maiúscula', 'On + dia', 'At + hora'],
      model: 'On Monday I have English at 2 pm. On Wednesday I play soccer at 5 pm. On Saturday I visit my aunt in the morning.', keywords: ['on', 'at', 'monday'], minWords: 18,
    },
    challenge: 'Diga em voz alta, em inglês, que horas são agora e que dia é hoje.',
  },
  games: {
    words: [{ word: 'Monday', clue: 'segunda-feira', difficulty: 1 }, { word: 'Friday', clue: 'sexta-feira', difficulty: 1 }, { word: 'weekend', clue: 'fim de semana', difficulty: 1 }, { word: 'April', clue: 'abril', difficulty: 1 }, { word: 'clock', clue: 'relógio', difficulty: 1 }, { word: 'Thursday', clue: 'quinta-feira', difficulty: 2 }, { word: 'December', clue: 'dezembro', difficulty: 2 }, { word: 'birthday', clue: 'aniversário', difficulty: 2 }],
    blanks: [
      blank(1, 'The class starts ___ 8 o\'clock.', ['at', 'on', 'in', 'of'], 0, 'Hora: at.'),
      blank(1, 'I go to the beach ___ Sunday.', ['on', 'in', 'at', 'to'], 0, 'Dia: on.'),
      blank(2, 'We travel ___ July.', ['in', 'on', 'at', 'by'], 0, 'Mês: in.'),
      blank(2, 'What ___ is it? — It\'s ten o\'clock.', ['time', 'hour', 'day', 'clock'], 0, 'What time is it?'),
      blank(3, 'I study ___ the afternoon and sleep ___ night.', ['in / at', 'at / in', 'on / on', 'in / in'], 0, 'In the afternoon · at night.'),
    ],
    sequences: [
      { prompt: 'Coloque os meses em ordem · Put the months in order', items: ['January', 'March', 'May', 'August', 'October'], difficulty: 1, explanation: 'Jan, Mar, May, Aug, Oct.' },
      words(2, 'My birthday is on May tenth', 'On + data.'),
    ],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 4 · Home and city ═══════════════════
export const thereIs = lesson({
  id: 'ing-a1-there-is', subject: 'ingles', title: 'There is / there are at home', levels: [...ALL], grade: 'A partir do 5º ano',
  topic: 'Inglês A1 — Meu dia a dia', subtopic: 'There is/are, casa e preposições de lugar',
  aliases: ['there is there are', 'ha em ingles', 'existe em ingles', 'casa em ingles', 'comodos da casa', 'house', 'preposicoes de lugar', 'in on under next to'],
  summary: 'Descreva a casa: o que existe em cada cômodo com there is/there are e onde as coisas estão.',
  intro: 'There is a sofa in the living room… Vamos fazer um tour pela casa em inglês!',
  objective: 'Descrever o que existe num lugar com there is/there are (afirmativa, negativa e pergunta) e localizar objetos com preposições de lugar.',
  prerequisites: ['ing-a1-this-that'], next: ['ing-a1-can-directions'],
  skills: { g_there: 'There is / there are', g_thereq: 'Negativa e pergunta com there', v_house: 'Cômodos e móveis', g_place: 'Preposições de lugar' },
  blocks: [
    block('g_there', 'There is / there are',
      'There is (there\'s) = há/existe, para UMA coisa: There is a sofa in the room. There are = há/existem, para VÁRIAS: There are two beds. Com coisas incontáveis também usamos there is: There is some water in the glass.',
      'There\'s a big window in my bedroom. · There are three chairs in the kitchen.',
      'There is = tem (uma coisa). There are = tem (várias coisas).',
      'Descrevendo seu quarto para um amigo: “There\'s a bed, a desk and there are two posters.”',
      '1. Conte: é uma ou várias? 2. Uma → there is. 3. Várias → there are.',
      'Em português dizemos “tem um sofá na sala”. Em inglês não se usa “have” aqui: There is a sofa in the living room.'),
    block('g_thereq', 'Is there…? Are there…?',
      'Negativa: There isn\'t a garage. / There aren\'t any plants. Pergunta: Is there a bathroom upstairs? — Yes, there is. / No, there isn\'t. Are there any shops near here? — Yes, there are.',
      '— Is there a park near your house? — Yes, there is.',
      'Para perguntar, inverta: Is there…? Are there…?',
      'Procurando hotel: “Is there Wi-Fi in the room?”',
      '1. Negativa: isn\'t / aren\'t. 2. Pergunta: Is/Are no começo. 3. Resposta curta: Yes, there is / No, there aren\'t.',
      'Use any em perguntas e negativas no plural (Are there any…? / There aren\'t any…) e a/an no singular (Is there a…?).'),
    block('v_house', 'Rooms and furniture',
      'Cômodos: living room (sala), kitchen (cozinha), bedroom (quarto), bathroom (banheiro), dining room (sala de jantar), garage (garagem), garden/yard (jardim/quintal). Móveis: sofa, bed, table, chair, wardrobe (guarda-roupa), fridge (geladeira), stove (fogão), shower (chuveiro).',
      'The fridge is in the kitchen. · There\'s a shower in the bathroom.',
      'Kitchen = cozinha, bedroom = quarto, bathroom = banheiro, living room = sala.',
      'Anúncio de aluguel: “Two bedrooms, one bathroom, a small kitchen.”',
      '1. Pense em cada cômodo. 2. Liste o que tem nele. 3. Junte: There\'s a … in the …',
      'Bedroom = cômodo para dormir (bed + room). Bathroom = cômodo com banheira (bath + room). Muitas palavras em inglês são “juntadas” assim.'),
    block('g_place', 'In, on, under, next to…',
      'In (dentro), on (em cima, sobre), under (embaixo), next to (ao lado de), between (entre), behind (atrás de), in front of (na frente de), near (perto de).',
      'The cat is under the table. · The lamp is next to the bed. · The keys are on the desk.',
      'In = dentro. On = em cima. Under = embaixo. Next to = ao lado.',
      'Procurando o controle: “It\'s under the sofa!”',
      '1. Veja a posição do objeto. 2. Escolha a preposição. 3. Diga: It\'s + preposição + the + lugar.',
      'Em português, “na mesa” pode ser em cima (on the table) ou dentro da gaveta (in the drawer). Em inglês a preposição mostra exatamente onde.'),
  ],
  questions: [
    mc(1, 'g_there', '___ two bedrooms in my house.', ['There is', 'There are', 'It is', 'They is'], 1, ['Quantos quartos?', 'Dois = plural.', 'Plural: there are.'], 'Plural: there are.'),
    mc(1, 'v_house', 'Onde fica a geladeira (fridge) normalmente?', ['bedroom', 'kitchen', 'bathroom', 'garage'], 1, ['Onde guardamos comida?', 'Onde cozinhamos?', 'Cozinha.'], 'Na kitchen (cozinha).'),
    fill(1, 'g_place', 'O gato está embaixo da mesa: The cat is ______ the table.', ['under'], ['Embaixo = …', 'Começa com u.', 'Un…'], 'Under = embaixo de.'),
    tf(1, 'g_there', '“There is a lot of books” está correto.', false, ['Books é singular ou plural?', 'Plural pede are.', 'There are…'], 'Falso: There are a lot of books.'),
    match(2, 'v_house', 'Ligue cada cômodo ao seu significado.', [['bedroom', 'quarto'], ['bathroom', 'banheiro'], ['living room', 'sala de estar'], ['kitchen', 'cozinha']], ['Bed = cama.', 'Bath = banho.', 'Living = viver.'], 'bedroom quarto · bathroom banheiro · living room sala · kitchen cozinha.'),
    mc(2, 'g_thereq', '— ___ there a bathroom upstairs? — Yes, there is.', ['Is', 'Are', 'Does', 'Has'], 0, ['A resposta é “there is”.', 'Singular.', 'Is there…?'], 'Is there a bathroom…?'),
    mc(2, 'g_thereq', 'Complete a negativa: There ___ any chairs in the room.', ['isn\'t', 'aren\'t', 'don\'t', 'not'], 1, ['Chairs é plural.', 'Negativa de are.', 'Are + not.'], 'There aren\'t any chairs.'),
    mc(2, 'g_place', 'O abajur está ao lado da cama: The lamp is ___ the bed.', ['between', 'next to', 'behind', 'in'], 1, ['Ao lado…', 'Next = próximo.', 'Next to.'], 'Next to = ao lado de.'),
    order(3, 'g_thereq', 'Organize a pergunta: “Há alguma loja perto daqui?”', ['Are', 'there', 'any', 'shops', 'near', 'here?'], ['Pergunta no plural: Are there…', 'Any em perguntas no plural.', 'Near here no final.'], 'Are there any shops near here?'),
    mc(3, 'g_there', 'Qual frase descreve a casa corretamente em inglês?', ['Has a garden in my house.', 'There have a garden in my house.', 'There is a garden in my house.', 'It have a garden in my house.'], 2, ['Não usamos have para “existir”.', 'Singular.', 'There is…'], 'There is a garden in my house.'),
  ],
  review: ['There is (1) · there are (vários)', 'Is there…? / Are there any…? · isn\'t / aren\'t', 'Cômodos: kitchen, bedroom, bathroom, living room', 'Lugar: in, on, under, next to, between, behind'],
  relatedQuestions: ['quando usar there is e there are', 'cômodos da casa em inglês', 'preposições de lugar em inglês'],
  equivalentQuestions: eqs(['there is e there are', 'casa em inglês', 'preposições de lugar'], ['como dizer tem em inglês', 'diferença entre there is e there are', 'como perguntar se tem algo em inglês', 'como se diz cozinha em inglês', 'o que significa under', 'como dizer ao lado de em inglês', 'there is ou have']),
  commonErrors: ['Usar have para “existir” (Have a park near here).', 'There is + plural.', 'Confundir in (dentro) e on (em cima).'],
  english: {
    cefr: 'A1', unit: 'a1-u4', order: 1, area: 'grammar', focus: ['grammar', 'vocabulary', 'reading'],
    vocabulary: [
      v('kitchen', 'cozinha', 'noun', 'the room where you cook', 'Mom is in the kitchen.', 1),
      v('bedroom', 'quarto', 'noun', 'the room where you sleep', 'My bedroom is small.', 1),
      v('bathroom', 'banheiro', 'noun', 'the room with a shower and a toilet', 'Where is the bathroom?', 1),
      v('sofa', 'sofá', 'noun', 'a long soft seat for two or more people', 'The cat is on the sofa.', 1),
      v('fridge', 'geladeira', 'noun', 'a machine that keeps food cold', 'The milk is in the fridge.', 2),
      v('wardrobe', 'guarda-roupa', 'noun', 'a tall piece of furniture for clothes', 'My clothes are in the wardrobe.', 3),
      v('under', 'embaixo de', 'preposition', 'below something', 'The shoes are under the bed.', 1),
      v('next to', 'ao lado de', 'preposition', 'very near, at the side of', 'The lamp is next to the bed.', 2),
      v('between', 'entre', 'preposition', 'in the space that separates two things', 'The table is between the chairs.', 2),
      v('behind', 'atrás de', 'preposition', 'at the back of', 'The ball is behind the door.', 2),
    ],
    reading: {
      title: 'Apartment for rent', genre: 'anúncio',
      text: 'APARTMENT FOR RENT — Downtown\nThere are two bedrooms and one bathroom. There\'s a big living room with a balcony. The kitchen is small, but there is a new fridge. There isn\'t a garage, but there are bus stops next to the building. Pets are welcome!',
      questions: [
        mci(1, 'Quantos quartos há?', ['1', '2', '3', 'Nenhum'], 1, '“There are two bedrooms.”'),
        mci(2, 'O que o apartamento NÃO tem?', ['Varanda', 'Geladeira nova', 'Garagem', 'Banheiro'], 2, '“There isn\'t a garage.”'),
        mci(2, 'O que há ao lado do prédio?', ['Um parque', 'Pontos de ônibus', 'Uma garagem', 'Uma loja'], 1, '“bus stops next to the building”.'),
        mci(3, 'Uma família com um cachorro pode alugar?', ['Sim, animais são bem-vindos', 'Não, não aceitam animais', 'O texto não diz', 'Só com garagem'], 0, '“Pets are welcome!”'),
      ],
    },
    writing: {
      prompt: 'Descreva o seu quarto (ou o quarto dos sonhos) com there is/there are e duas preposições de lugar.', criteria: ['There is e there are', 'Pelo menos 4 objetos', '2 preposições de lugar'],
      model: 'In my bedroom there is a bed and a desk. There are two shelves. My backpack is under the desk and the lamp is next to the bed.', keywords: ['there', 'is', 'are', 'under', 'next'], minWords: 20,
    },
    challenge: 'Esconda um objeto em casa e dê a pista em inglês para alguém achar: “It\'s under/behind/next to…”.',
  },
  games: {
    blanks: [
      blank(1, 'There ___ a sofa in the living room.', ['is', 'are', 'am', 'be'], 0, 'Singular: there is.'),
      blank(1, 'The milk is ___ the fridge.', ['in', 'on', 'under', 'at'], 0, 'Dentro: in.'),
      blank(2, '___ there any eggs? — No, there aren\'t.', ['Are', 'Is', 'Do', 'Have'], 0, 'Plural: Are there any…?'),
      blank(2, 'The ball is ___ the chair and the table.', ['between', 'next', 'behind to', 'under of'], 0, 'Entre duas coisas: between.'),
      blank(3, 'There ___ a lot of noise in the street today.', ['is', 'are', 'have', 'has'], 0, 'Noise é incontável: there is.'),
    ],
    sequences: [words(1, 'There is a bed in my room', 'There is + a + objeto + lugar.'), words(2, 'Is there a park near here', 'Is there…? + lugar.')],
  },
  sources: enSources(),
})

export const canDirections = lesson({
  id: 'ing-a1-can-directions', subject: 'ingles', title: 'Can, imperatives and directions', levels: [...ALL], grade: 'A partir do 5º ano',
  topic: 'Inglês A1 — Meu dia a dia', subtopic: 'Can, imperativo e direções na cidade',
  aliases: ['can em ingles', 'verbo can', 'habilidade em ingles', 'imperativo em ingles', 'direcoes em ingles', 'how do i get to', 'turn left', 'lugares da cidade em ingles'],
  summary: 'Diga o que você sabe fazer com can, dê instruções no imperativo e peça e dê direções na cidade.',
  intro: 'Can you help me? Vamos nos virar na cidade em inglês.',
  objective: 'Usar can para habilidade, permissão e pedido; dar instruções com o imperativo; pedir e dar direções simples com lugares da cidade.',
  prerequisites: ['ing-a1-there-is'], next: ['ing-a2-present-continuous'],
  skills: { g_can: 'Can / can\'t', g_imp: 'Imperativo', v_city: 'Lugares da cidade', s_dir: 'Pedir e dar direções' },
  blocks: [
    block('g_can', 'Can and can\'t',
      'Can + verbo (sem to) expressa habilidade (I can swim), permissão (Can I go to the bathroom?) e pedido (Can you help me?). Negativa: can\'t (cannot). Can não muda com he/she/it: She can dance.',
      'I can speak two languages. · He can\'t cook. · Can you open the window?',
      'Can = consigo/sei/posso. Can\'t = não consigo/não posso.',
      'Na aula: “Can I borrow your pencil?” — “Sure!”',
      '1. Sujeito. 2. Can ou can\'t. 3. Verbo sem to e sem -s.',
      'Diferente do simple present, com can o verbo NÃO ganha -s: She can play (nunca “she cans plays”).'),
    block('g_imp', 'Imperatives',
      'O imperativo dá ordens, instruções e conselhos: é o verbo na forma base, sem sujeito: Open your books. Turn left. Negativo: Don\'t + verbo: Don\'t run! Para ser educado, acrescente please.',
      'Sit down, please. · Don\'t touch that! · Take the first street on the right.',
      'Imperativo = mandar ou orientar: Open! Close! Don\'t run!',
      'Receita: “Mix the eggs. Don\'t add salt.”',
      '1. Comece pelo verbo. 2. Negativo: Don\'t + verbo. 3. Educado: please.',
      'O imperativo é igual para uma ou várias pessoas: “Sit down” serve para você e para a turma inteira.'),
    block('v_city', 'Places in town',
      'Lugares: bank (banco), bakery (padaria), pharmacy/drugstore (farmácia), supermarket, hospital, library (biblioteca), museum, park, bus stop (ponto de ônibus), train station (estação), post office (correios), restaurant, school, church.',
      'The library is next to the park. · There\'s a bakery near the school.',
      'Library = biblioteca (não é livraria!). Bakery = padaria.',
      'Turista pergunta: “Is there a pharmacy near here?”',
      '1. Liste os lugares do seu bairro. 2. Diga em inglês. 3. Use there is/next to para localizá-los.',
      'Library parece “livraria”, mas é BIBLIOTECA. Livraria = bookstore.'),
    block('s_dir', 'Asking for and giving directions',
      'Para perguntar: Excuse me, where is the bank? / How do I get to the station? Para responder: Go straight (ahead) (siga em frente), Turn left/right (vire à esquerda/direita), Take the second street on the left, It\'s on the corner (na esquina), It\'s across from the park (em frente ao parque).',
      '— How do I get to the museum? — Go straight and turn right. It\'s next to the bank.',
      'Go straight = siga reto. Turn left = vire à esquerda. Turn right = vire à direita.',
      'Você explica para um turista: “Go straight, turn left at the bakery. The station is on the right.”',
      '1. Excuse me + pergunta. 2. Ouça: straight, left, right. 3. Agradeça: Thank you!',
      'Right tem dois sentidos: direita e certo. Em direções, “on the right” = à direita.'),
  ],
  questions: [
    mc(1, 'g_can', 'Qual frase está correta?', ['She can swims.', 'She cans swim.', 'She can swim.', 'She can to swim.'], 2, ['Can não muda.', 'Verbo sem -s.', 'Sem to.'], 'She can swim.'),
    mc(1, 's_dir', '“Turn left” significa:', ['Vire à direita', 'Vire à esquerda', 'Siga em frente', 'Volte'], 1, ['Left = …', 'Oposto de right.', 'Esquerda.'], 'Turn left = vire à esquerda.'),
    tf(1, 'v_city', '“Library” significa livraria.', false, ['É um falso amigo.', 'Lugar onde se pegam livros emprestados.', 'Biblioteca.'], 'Falso: library = biblioteca; livraria = bookstore.'),
    fill(1, 'g_imp', 'Complete a ordem negativa: ___ run in the corridor!', ['Don\'t', 'Do not'], ['Imperativo negativo.', 'Do + not.', 'D-o-n-\'-t.'], 'Don\'t run!'),
    match(2, 'v_city', 'Ligue o lugar ao que você faz lá.', [['bakery', 'comprar pão'], ['pharmacy', 'comprar remédio'], ['library', 'pegar livros emprestados'], ['bank', 'sacar dinheiro']], ['Bake = assar.', 'Pharmacy parece farmácia.', 'Library = biblioteca.'], 'bakery pão · pharmacy remédio · library livros · bank dinheiro.'),
    mc(2, 'g_can', 'Você quer pedir permissão para ir ao banheiro. Diga:', ['Can I go to the bathroom?', 'I can go to the bathroom.', 'Can you go to the bathroom?', 'Go to the bathroom.'], 0, ['É um pedido de permissão.', 'Pergunta começa com can.', 'Can I…?'], 'Can I go to the bathroom?'),
    mc(2, 's_dir', 'Como perguntar o caminho para a estação?', ['How do I get to the station?', 'How I get to the station?', 'Where I go station?', 'How do get I to the station?'], 0, ['Pergunta com How do I…', 'Get to = chegar a.', 'How do I get to…?'], 'How do I get to the station?'),
    mc(2, 'g_imp', 'Qual é uma instrução no imperativo?', ['You opens the book.', 'Open your book, please.', 'Opening the book.', 'To open the book.'], 1, ['Imperativo começa pelo verbo.', 'Sem sujeito.', 'Open…'], 'Open your book, please.'),
    order(3, 's_dir', 'Coloque as instruções na ordem para chegar ao museu: saia, siga reto, vire à direita no banco, o museu fica à esquerda.', ['Leave the school.', 'Go straight.', 'Turn right at the bank.', 'The museum is on the left.'], ['Primeiro você sai.', 'Depois segue reto.', 'Por último a posição do museu.'], 'Leave → go straight → turn right → on the left.'),
    mc(3, 'g_can', '“Can you speak French?” — “No, I ___.”', ['don\'t', 'can\'t', 'not', 'cannot speak it can'], 1, ['Resposta curta repete o auxiliar.', 'A pergunta usa can.', 'Negativo: can\'t.'], 'No, I can\'t.'),
  ],
  review: ['Can + verbo base (sem to, sem -s) · can\'t', 'Imperativo: Open… / Don\'t run!', 'Lugares: bakery, pharmacy, library (biblioteca), bank…', 'Direções: go straight, turn left/right, on the corner'],
  relatedQuestions: ['como usar can em inglês', 'como pedir direções em inglês', 'imperativo em inglês'],
  equivalentQuestions: eqs(['can em inglês', 'direções em inglês', 'imperativo em inglês'], ['como dizer eu sei nadar em inglês', 'como pedir licença para ir ao banheiro em inglês', 'como perguntar onde fica algo em inglês', 'o que significa turn right', 'library é livraria', 'como se diz padaria em inglês', 'como dar ordem em inglês']),
  commonErrors: ['Colocar -s ou to depois de can (she can swims, can to go).', 'Achar que library = livraria.', 'Usar sujeito no imperativo (You open the door!).'],
  english: {
    cefr: 'A1', unit: 'a1-u4', order: 2, area: 'speaking', focus: ['speaking', 'listening', 'grammar'],
    vocabulary: [
      v('bakery', 'padaria', 'noun', 'a shop that sells bread and cakes', 'I buy bread at the bakery.', 1),
      v('library', 'biblioteca', 'noun', 'a place where you can borrow books', 'The library is quiet.', 2, { related: ['bookstore'] }),
      v('pharmacy', 'farmácia', 'noun', 'a shop that sells medicine', 'Is there a pharmacy near here?', 1, { synonyms: ['drugstore'] }),
      v('station', 'estação', 'noun', 'a place where trains or buses stop', 'The train station is big.', 2),
      v('left', 'esquerda', 'noun', 'the side opposite to right', 'Turn left at the bank.', 1, { antonyms: ['right'] }),
      v('right', 'direita', 'noun', 'the side opposite to left', 'The school is on the right.', 1, { antonyms: ['left'] }),
      v('straight', 'reto / em frente', 'adverb', 'without turning', 'Go straight for two blocks.', 2),
      v('corner', 'esquina', 'noun', 'the place where two streets meet', 'The bank is on the corner.', 2),
      v('turn', 'virar', 'verb', 'to change direction', 'Turn right at the park.', 1),
      v('can', 'poder / conseguir', 'verb', 'to be able to', 'I can ride a bike.', 1),
    ],
    listening: {
      title: 'Where is the museum?', kind: 'dialogo', rate: 0.88,
      script: ['Tourist: Excuse me, how do I get to the museum?', 'Girl: Go straight for two blocks.', 'Girl: Then turn left at the bakery.', 'Girl: The museum is on the right, across from the park.', 'Tourist: Thank you so much!', 'Girl: You\'re welcome.'],
      questions: [
        mci(1, 'Para onde o turista quer ir?', ['Ao parque', 'Ao museu', 'À padaria', 'Ao banco'], 1, '“How do I get to the museum?”'),
        mci(2, 'Onde ele deve virar à esquerda?', ['No parque', 'No banco', 'Na padaria', 'Na escola'], 2, '“turn left at the bakery”.'),
        mci(3, 'Onde fica o museu?', ['À esquerda, ao lado da padaria', 'À direita, em frente ao parque', 'Na esquina do banco', 'Atrás do parque'], 1, '“on the right, across from the park”.'),
      ],
    },
    speaking: {
      situation: 'Um turista para você na rua e pergunta como chegar à biblioteca.', vocabulary: ['go straight', 'turn left', 'turn right', 'next to'],
      phrases: ['Go straight.', 'Turn left at…', 'It\'s next to…', 'It\'s on the right.'], example: 'Go straight and turn right at the bank. The library is next to the park.',
      challenge: 'Explique em inglês o caminho da sua casa até a padaria ou a escola.', expected: ['go', 'straight', 'turn', 'left', 'right'],
    },
    challenge: 'Faça uma lista de 3 coisas que você can e 3 que você can\'t fazer.',
  },
  games: {
    words: [{ word: 'bakery', clue: 'padaria', difficulty: 1 }, { word: 'library', clue: 'biblioteca', difficulty: 2 }, { word: 'bank', clue: 'banco', difficulty: 1 }, { word: 'museum', clue: 'museu', difficulty: 1 }, { word: 'left', clue: 'esquerda', difficulty: 1 }, { word: 'right', clue: 'direita', difficulty: 1 }, { word: 'corner', clue: 'esquina', difficulty: 2 }, { word: 'straight', clue: 'em frente', difficulty: 3 }],
    blanks: [
      blank(1, 'I ___ play the guitar.', ['can', 'cans', 'can to', 'am can'], 0, 'Can + verbo base.'),
      blank(1, '___ left at the bank.', ['Turn', 'Turns', 'Turning', 'To turn'], 0, 'Imperativo: verbo na forma base.'),
      blank(2, 'Excuse me, how do I ___ to the station?', ['get', 'go to', 'arrive', 'come'], 0, 'How do I get to…?'),
      blank(2, 'The bank is ___ the corner.', ['on', 'in', 'at to', 'under'], 0, 'On the corner = na esquina.'),
      blank(3, '___ touch the stove! It\'s hot.', ['Don\'t', 'Not', 'No', 'Can'], 0, 'Imperativo negativo: Don\'t.'),
    ],
    dialogues: [
      dialogue(1, 'Pedindo permissão', ['Student: Can I open the window, please?', 'Teacher: Yes, you can.', 'Student: Thank you!'], 1, ['Yes, you can.', 'Yes, I can.', 'Turn left.', 'You\'re welcome.'], 0, 'Para dar permissão: Yes, you can.'),
      dialogue(2, 'Na rua', ['Man: Excuse me, where is the pharmacy?', 'Girl: Go straight and turn right. It\'s on the corner.', 'Man: Thanks a lot!'], 1, ['Go straight and turn right. It\'s on the corner.', 'I can\'t swim.', 'It\'s eight o\'clock.', 'Nice to meet you.'], 0, 'A pergunta pede uma direção.'),
    ],
    sequences: [words(1, 'Can you help me please', 'Pedido: Can you + verbo…?'), words(2, 'Turn left at the bakery', 'Imperativo + direção + lugar.')],
  },
  sources: enSources(),
})
