// Curso de Inglês do LUMI — nível A2 (Básico). Conteúdo original.
import { block, blank, dialogue, enSources, eqs, fill, lesson, match, mc, mci, order, tf, v, words } from '../dsl'

const LV = ['fund2', 'medio'] as const

// ═══════════════════ Unidade 1 · Right now ═══════════════════
export const presentContinuous = lesson({
  id: 'ing-a2-present-continuous', subject: 'ingles', title: 'Present continuous', levels: [...LV], grade: '6º e 7º ano',
  topic: 'Inglês A2 — Agora e antes', subtopic: 'Present continuous × simple present',
  aliases: ['present continuous', 'presente continuo', 'ing em ingles', 'gerundio em ingles', 'am is are ing', 'acontecendo agora em ingles', 'present progressive'],
  summary: 'Fale do que está acontecendo agora com am/is/are + -ing e saiba quando usar o simple present.',
  intro: 'Look! It\'s raining! Vamos falar do que está acontecendo neste momento.',
  objective: 'Formar o present continuous (afirmativa, negativa e pergunta), aplicar as regras do -ing e escolher entre ele e o simple present.',
  prerequisites: ['ing-simple-present', 'ing-verb-to-be'], next: ['ing-a2-simple-past'],
  skills: { g_form: 'Formação: am/is/are + -ing', g_ing: 'Regras de ortografia do -ing', g_negq: 'Negativa e pergunta', g_vs: 'Present continuous × simple present' },
  blocks: [
    block('g_form', 'am / is / are + verb-ing',
      'O present continuous mostra uma ação em andamento agora ou nestes dias: sujeito + am/is/are + verbo com -ing. Palavras que costumam aparecer: now, right now, at the moment, today, Look!, Listen!',
      'I\'m studying now. · She\'s playing the piano. · They\'re watching a movie.',
      'É o nosso “estou fazendo”: I\'m eating = estou comendo.',
      'Mensagem para um amigo: “I\'m waiting for the bus. I\'m late!”',
      '1. Sujeito. 2. Am, is ou are (verb to be). 3. Verbo + ing.',
      'Em português: “estou + -ndo” (estou comendo). Em inglês: am + -ing (I am eating). O “estar” vira o verb to be.'),
    block('g_ing', 'Spelling: -ing',
      'Regra geral: verbo + ing (play → playing). Verbos que terminam em -e perdem o e (write → writing, dance → dancing). Verbos curtos que terminam em consoante + vogal + consoante dobram a última letra (run → running, swim → swimming, sit → sitting). Terminados em -ie viram -ying (lie → lying).',
      'make → making · stop → stopping · die → dying',
      'Quase sempre é só colocar -ing. Tire o -e do final e dobre a letra em palavras curtas como run.',
      'Legenda de foto: “Swimming in the sea!” (swim + m + ing).',
      '1. Termina em -e? Tire o e. 2. É curto com consoante-vogal-consoante? Dobre a última. 3. Senão, só -ing.',
      'Compare: hope → hoping (tira o e) × hop → hopping (dobra o p). Uma letra muda o sentido: esperar × pular.'),
    block('g_negq', 'Negative and questions',
      'Negativa: am not / isn\'t / aren\'t + -ing: He isn\'t sleeping. Pergunta: Am/Is/Are + sujeito + -ing? Is she working? — Yes, she is. / No, she isn\'t. Com palavra de pergunta: What are you doing? Where are they going?',
      '— What are you doing? — I\'m reading a comic.',
      'Negativa: isn\'t / aren\'t. Pergunta: coloque am/is/are no começo.',
      'Mãe no telefone: “Are you doing your homework?” — “Yes, I am!”',
      '1. Negativa: coloque not depois de am/is/are. 2. Pergunta: troque a ordem. 3. Resposta curta: Yes, I am / No, he isn\'t.',
      'No present continuous NÃO usamos do/does: é “Are you working?”, e não “Do you working?”.'),
    block('g_vs', 'Now or every day?',
      'Simple present = rotina, hábito, verdade (I play soccer on Sundays). Present continuous = agora, temporário (I\'m playing soccer now). Verbos de estado (like, love, want, know, need, understand) quase nunca vão para o -ing: I want pizza (e não “I\'m wanting”).',
      'She usually walks to school, but today she\'s taking the bus.',
      'Todo dia → simple present. Agora → present continuous.',
      'Status: “I usually study in the morning, but this week I\'m studying at night.”',
      '1. Procure palavras de tempo: every day, usually (rotina) × now, at the moment (agora). 2. Escolha o tempo. 3. Cuidado com verbos de estado.',
      '“I work in a bank” = é o meu emprego. “I\'m working in a bank this month” = é temporário, só agora.'),
  ],
  questions: [
    mc(1, 'g_form', 'Look! The children ___ in the park.', ['play', 'are playing', 'is playing', 'plays'], 1, ['“Look!” indica agora.', 'Children é plural.', 'Are + -ing.'], 'Agora + plural: are playing.'),
    fill(1, 'g_ing', 'Escreva o -ing de “write”.', ['writing'], ['Termina em -e.', 'Tire o e.', 'writ + ing.'], 'Write → writing.'),
    tf(1, 'g_negq', '“Do you studying now?” está correto.', false, ['No present continuous usamos do?', 'Usamos o verb to be.', 'Are you studying…?'], 'Falso: Are you studying now?'),
    mc(1, 'g_form', 'Qual frase significa “Estou comendo”?', ['I eat.', 'I\'m eating.', 'I eating.', 'I\'m eat.'], 1, ['Estou = I am.', 'Comendo = eating.', 'I\'m eating.'], 'I\'m eating.'),
    match(2, 'g_ing', 'Ligue o verbo à forma com -ing.', [['run', 'running'], ['dance', 'dancing'], ['play', 'playing'], ['lie', 'lying']], ['Run é curto: dobra.', 'Dance perde o e.', 'Lie → -ying.'], 'running · dancing · playing · lying.'),
    mc(2, 'g_negq', '— Is your sister sleeping? — No, she ___. She\'s reading.', ['isn\'t', 'doesn\'t', 'aren\'t', 'not'], 0, ['Resposta curta repete o auxiliar.', 'A pergunta usa is.', 'Is + not.'], 'No, she isn\'t.'),
    mc(2, 'g_vs', 'I usually ___ to school, but today I ___ the bus.', ['walk / am taking', 'am walking / take', 'walks / taking', 'walk / take'], 0, ['Usually = rotina.', 'Today = temporário/agora.', 'Simple present + present continuous.'], 'Rotina: walk; hoje: am taking.'),
    mc(2, 'g_vs', 'Qual frase está correta?', ['I\'m wanting a sandwich.', 'I want a sandwich.', 'I wanting a sandwich.', 'I\'m want a sandwich.'], 1, ['Want é verbo de estado.', 'Não costuma ir para -ing.', 'Simple present.'], 'I want a sandwich (want é verbo de estado).'),
    order(3, 'g_negq', 'Organize a pergunta: “O que você está fazendo?”', ['What', 'are', 'you', 'doing?'], ['Comece pela palavra de pergunta.', 'Depois o verb to be.', 'Sujeito + -ing.'], 'What are you doing?'),
    mc(3, 'g_ing', 'Qual está escrita corretamente?', ['swiming', 'swimming', 'swimeing', 'swimmming'], 1, ['Swim: consoante-vogal-consoante.', 'Dobra o m.', 'Uma vez só.'], 'Swim → swimming.'),
  ],
  review: ['am/is/are + verbo-ing = acontecendo agora', '-ing: tira o -e (writing), dobra (running), -ie → -ying', 'Negativa isn\'t/aren\'t · pergunta Are you…?', 'Rotina = simple present · agora = present continuous'],
  relatedQuestions: ['como usar o present continuous', 'diferença entre simple present e present continuous', 'regras do ing em inglês'],
  equivalentQuestions: eqs(['present continuous', 'presente contínuo'], ['como dizer estou fazendo em inglês', 'quando usar ing em inglês', 'por que running tem dois n', 'diferença entre I work e I am working', 'como perguntar o que você está fazendo em inglês', 'verbos que não vão para ing', 'o que é gerúndio em inglês']),
  commonErrors: ['Esquecer o am/is/are (I playing).', 'Usar do/does em perguntas (Do you working?).', 'Colocar verbos de estado no -ing (I\'m knowing).'],
  english: {
    cefr: 'A2', unit: 'a2-u1', order: 1, area: 'grammar', focus: ['grammar', 'listening', 'speaking'],
    vocabulary: [
      v('now', 'agora', 'adverb', 'at this moment', 'I\'m busy now.', 1),
      v('at the moment', 'no momento', 'phrase', 'now, at this time', 'She\'s working at the moment.', 2),
      v('wait', 'esperar', 'verb', 'to stay until something happens', 'I\'m waiting for the bus.', 1),
      v('rain', 'chover', 'verb', 'when water falls from the sky', 'Look! It\'s raining.', 1),
      v('cook', 'cozinhar', 'verb', 'to prepare food', 'Dad is cooking dinner.', 1),
      v('listen', 'ouvir / escutar', 'verb', 'to pay attention to a sound', 'Listen! The baby is crying.', 1),
      v('cry', 'chorar', 'verb', 'to have tears falling from your eyes', 'Why are you crying?', 2),
      v('busy', 'ocupado(a)', 'adjective', 'having a lot to do', 'I can\'t talk, I\'m busy.', 2),
    ],
    grammar: {
      name: 'Present continuous', when: 'Ações acontecendo agora ou temporárias (nestes dias).', structure: 'sujeito + am/is/are + verbo-ing',
      affirmative: ['I\'m reading.', 'She\'s cooking.', 'They\'re playing.'], negative: ['I\'m not sleeping.', 'He isn\'t working.', 'We aren\'t watching TV.'], interrogative: ['Are you listening?', 'Is it raining?', 'What are they doing?'],
      compare: 'I play (rotina) × I\'m playing (agora).', context: 'Descrevendo pelo telefone o que está acontecendo numa festa.',
    },
    listening: {
      title: 'Ligação de domingo', kind: 'dialogo', rate: 0.9,
      script: ['Grandma: Hi, sweetie! What are you doing?', 'Girl: Hi, Grandma! I\'m making a cake with Dad.', 'Grandma: Lovely! And your brother?', 'Girl: He\'s playing video games in his room.', 'Grandma: Is your mom there?', 'Girl: No, she isn\'t. She\'s running in the park.'],
      questions: [
        mci(1, 'O que a menina está fazendo?', ['Jogando videogame', 'Fazendo um bolo', 'Correndo', 'Dormindo'], 1, '“I\'m making a cake with Dad.”'),
        mci(2, 'Onde está o irmão?', ['No parque', 'No quarto', 'Na cozinha', 'Na casa da avó'], 1, '“in his room”.'),
        mci(2, 'O que a mãe está fazendo?', ['Cozinhando', 'Correndo no parque', 'Trabalhando', 'Falando ao telefone'], 1, '“She\'s running in the park.”'),
      ],
    },
    speaking: {
      situation: 'Um amigo liga e pergunta o que você e sua família estão fazendo agora.', vocabulary: ['right now', 'I\'m', 'he\'s', 'they\'re'],
      phrases: ['Right now I\'m…', 'My mom is…', 'My friends are…'], example: 'Right now I\'m studying English. My mom is cooking and my dad is watching TV.',
      challenge: 'Diga 3 frases sobre o que está acontecendo ao seu redor neste momento.', expected: ['i\'m', 'is', 'ing'],
    },
    writing: {
      prompt: 'Olhe pela janela (ou imagine uma praça) e escreva 4 frases sobre o que as pessoas estão fazendo.', criteria: ['am/is/are + -ing', 'Pelo menos 4 ações', 'Ortografia do -ing'],
      model: 'A man is walking his dog. Two kids are riding bikes. A woman is sitting on a bench. It isn\'t raining today.', keywords: ['is', 'are', 'ing'], minWords: 18,
    },
    challenge: 'Tire uma foto (ou escolha uma) e descreva em inglês o que está acontecendo nela.',
  },
  games: {
    blanks: [
      blank(1, 'Listen! Somebody ___ at the door.', ['is knocking', 'knocks', 'knock', 'are knocking'], 0, '“Listen!” = agora: is knocking.'),
      blank(1, 'We ___ a movie right now.', ['are watching', 'watch', 'is watching', 'watches'], 0, 'We + are + -ing.'),
      blank(2, 'She ___ to the radio at the moment.', ['isn\'t listening', 'doesn\'t listen', 'not listening', 'aren\'t listening'], 0, 'Negativa: isn\'t + -ing.'),
      blank(2, 'He goes to work by car, but this week he ___ the train.', ['is taking', 'takes', 'take', 'taking'], 0, 'Temporário: is taking.'),
      blank(3, 'I ___ what you mean.', ['understand', 'am understanding', 'understanding', 'am understand'], 0, 'Understand é verbo de estado.'),
    ],
    sequences: [words(1, 'She is reading a book', 'Sujeito + is + -ing + complemento.'), words(2, 'Are they playing soccer', 'Pergunta: Are + sujeito + -ing?'), words(3, 'I am not sleeping right now', 'Negativa: am not + -ing.')],
    dialogues: [
      dialogue(2, 'No telefone', ['Leo: Hi! Are you busy?', 'Ana: Yes, I\'m doing my homework.', 'Leo: OK, call me later!'], 1, ['Yes, I\'m doing my homework.', 'Yes, I do my homework.', 'Yes, I am do homework.', 'Yes, I doing homework.'], 0, 'Agora: I\'m doing.'),
      dialogue(3, 'Na praia', ['Bia: What are you doing?', 'Rui: I\'m looking for my sunglasses.', 'Bia: They\'re on your head!'], 1, ['I\'m looking for my sunglasses.', 'I look for my sunglasses every day.', 'I looking my sunglasses.', 'I\'m look for my sunglasses.'], 0, 'Present continuous: I\'m looking for.'),
    ],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 2 · Stories from the past ═══════════════════
export const simplePast = lesson({
  id: 'ing-a2-simple-past', subject: 'ingles', title: 'Simple past', levels: [...LV], grade: '7º e 8º ano',
  topic: 'Inglês A2 — Agora e antes', subtopic: 'Simple past: regulares, irregulares, did',
  aliases: ['simple past', 'passado simples', 'past simple', 'verbos irregulares', 'ed em ingles', 'did didnt', 'passado em ingles', 'was were'],
  summary: 'Conte o que aconteceu: verbos com -ed, os irregulares mais comuns, was/were e did.',
  intro: 'Yesterday I watched a great movie! Vamos contar histórias do passado.',
  objective: 'Formar o simple past de verbos regulares e irregulares, usar was/were e fazer negativas e perguntas com did.',
  prerequisites: ['ing-simple-present'], next: ['ing-a2-past-continuous'],
  skills: { g_reg: 'Verbos regulares (-ed)', g_irr: 'Verbos irregulares', g_did: 'Negativa e pergunta com did', g_was: 'Was / were' },
  blocks: [
    block('g_reg', 'Regular verbs: -ed',
      'O simple past fala de ações terminadas num momento do passado (yesterday, last week, in 2020, two days ago). Nos verbos regulares, acrescentamos -ed: play → played. Terminados em -e: só -d (dance → danced). Consoante + y: -ied (study → studied). Curtos com consoante-vogal-consoante dobram: stop → stopped.',
      'I watched TV yesterday. · She studied for the test last night.',
      'Passado regular = verbo + ed: I played = eu joguei.',
      'Contando o fim de semana: “On Saturday I visited my grandma and we cooked lunch.”',
      '1. Veja se o verbo é regular. 2. Acrescente -ed (ou -d, -ied, dobra). 3. A forma é a mesma para todas as pessoas.',
      'Diferente do presente, no passado NÃO existe -s para he/she: He played (e não “he playeds”).'),
    block('g_irr', 'Irregular verbs',
      'Muitos verbos comuns são irregulares e precisam ser memorizados: go → went, have → had, do → did, see → saw, eat → ate, make → made, get → got, come → came, take → took, buy → bought, write → wrote, say → said.',
      'We went to the beach. · I saw a shark! · She bought a new phone.',
      'Alguns verbos mudam de jeito no passado: go vira went, eat vira ate.',
      'Diário de viagem: “We took a boat, ate fish and saw dolphins.”',
      '1. Faça uma lista com os 20 irregulares mais usados. 2. Treine em frases. 3. Revise um pouco por dia.',
      'Em português também temos irregulares: “ir → fui”, “ter → tive”. Em inglês: go → went, have → had.'),
    block('g_did', 'Negative and questions with did',
      'Negativa: didn\'t + verbo na forma base: I didn\'t go (e não “didn\'t went”). Pergunta: Did + sujeito + verbo base? Did you like it? — Yes, I did. / No, I didn\'t. Com palavra de pergunta: Where did you go? What did she say?',
      '— Did you finish your homework? — No, I didn\'t.',
      'Did carrega o passado; por isso o verbo volta ao normal: Did you go?',
      'Professor pergunta: “What did you do on the weekend?”',
      '1. Negativa: didn\'t + verbo base. 2. Pergunta: Did + sujeito + verbo base. 3. Resposta: Yes, I did / No, I didn\'t.',
      'É o mesmo esquema do do/does do presente, só que tudo vira did — para todas as pessoas.'),
    block('g_was', 'Was and were',
      'O passado do verb to be: was (I, he, she, it) e were (you, we, they). Negativa: wasn\'t / weren\'t. Pergunta: Was she at school? Were they happy? Não usamos did com was/were.',
      'I was tired. · They were at the party. · Was it good? — Yes, it was.',
      'Was = era/estava (um). Were = eram/estavam (vários, e “você”).',
      'Depois do jogo: “The game was amazing! We were so happy.”',
      '1. Sujeito I/he/she/it → was. 2. You/we/they → were. 3. Pergunta: Was/Were no começo.',
      'Com o verb to be não entra did: “Were you there?” (e não “Did you were there?”).'),
  ],
  questions: [
    mc(1, 'g_reg', 'Yesterday I ___ soccer with my friends.', ['play', 'played', 'plays', 'playing'], 1, ['Yesterday = passado.', 'Play é regular.', 'Play + ed.'], 'Played.'),
    mc(1, 'g_irr', 'Qual é o passado de “go”?', ['goed', 'went', 'gone', 'goes'], 1, ['É irregular.', 'Não tem -ed.', 'W…'], 'Go → went.'),
    fill(1, 'g_reg', 'Escreva o passado de “study”.', ['studied'], ['Consoante + y.', 'O y vira i.', 'studi + ed.'], 'Study → studied.'),
    tf(1, 'g_did', '“I didn\'t went to school” está correto.', false, ['Depois de didn\'t…', '…o verbo volta à forma base.', 'Didn\'t go.'], 'Falso: I didn\'t go to school.'),
    match(2, 'g_irr', 'Ligue o verbo ao seu passado.', [['eat', 'ate'], ['see', 'saw'], ['buy', 'bought'], ['have', 'had']], ['Eat → a…', 'See → s…w', 'Buy e bring têm “ought”.'], 'ate · saw · bought · had.'),
    mc(2, 'g_was', 'They ___ at the cinema last night.', ['was', 'were', 'did', 'are'], 1, ['They → were ou was?', 'Plural.', 'Were.'], 'They were.'),
    mc(2, 'g_did', '___ you like the movie?', ['Did', 'Do', 'Were', 'Was'], 0, ['Like é verbo comum (não é to be).', 'Passado.', 'Did.'], 'Did you like the movie?'),
    mc(2, 'g_did', 'Qual pergunta está correta?', ['Where did you went?', 'Where you went?', 'Where did you go?', 'Where did you goes?'], 2, ['Did já mostra o passado.', 'Verbo na forma base.', 'Did + you + go.'], 'Where did you go?'),
    order(3, 'g_irr', 'Coloque a história na ordem.', ['Last Saturday we woke up early.', 'We took the bus to the beach.', 'We swam and ate sandwiches.', 'In the evening we came home tired.'], ['A manhã vem primeiro.', 'Depois o transporte.', 'A volta é no final.'], 'Acordar → ônibus → praia → voltar.'),
    mc(3, 'g_was', '— Was the test difficult? — No, it ___.', ['didn\'t', 'wasn\'t', 'weren\'t', 'isn\'t'], 1, ['A pergunta usa was.', 'Resposta curta repete.', 'Was + not.'], 'No, it wasn\'t.'),
  ],
  review: ['Regulares: -ed / -d / -ied / dobra (stopped)', 'Irregulares: went, had, did, saw, ate, bought…', 'didn\'t + verbo base · Did you…?', 'was (I/he/she/it) · were (you/we/they)'],
  relatedQuestions: ['como usar o simple past', 'lista de verbos irregulares', 'quando usar did em inglês'],
  equivalentQuestions: eqs(['simple past', 'passado simples em inglês'], ['como falar do passado em inglês', 'passado de go', 'passado de eat', 'por que didn\'t go e não didn\'t went', 'diferença entre was e were', 'como perguntar o que você fez no fim de semana em inglês', 'verbos irregulares mais usados']),
  commonErrors: ['Usar did + verbo no passado (didn\'t went).', 'Colocar -ed em irregulares (goed, eated).', 'Usar did com was/were.'],
  english: {
    cefr: 'A2', unit: 'a2-u2', order: 1, area: 'grammar', focus: ['grammar', 'reading', 'writing'],
    vocabulary: [
      v('yesterday', 'ontem', 'adverb', 'the day before today', 'I saw her yesterday.', 1),
      v('last', 'passado(a) / último', 'determiner', 'the one before this one', 'Last week I was sick.', 1, { collocations: ['last night', 'last year'] }),
      v('ago', 'atrás', 'adverb', 'before now (two days ago)', 'I moved here three years ago.', 2),
      v('went', 'foi / fui (go)', 'verb', 'past of go', 'We went to the zoo.', 1),
      v('saw', 'viu / vi (see)', 'verb', 'past of see', 'I saw a rainbow.', 1),
      v('bought', 'comprou (buy)', 'verb', 'past of buy', 'She bought a new bike.', 2),
      v('took', 'pegou / levou (take)', 'verb', 'past of take', 'We took a lot of photos.', 2),
      v('trip', 'viagem', 'noun', 'a journey to a place and back', 'Our trip was great.', 1),
    ],
    grammar: {
      name: 'Simple past', when: 'Ações terminadas num momento do passado.', structure: 'verbo-ed / irregular · didn\'t + base · Did + sujeito + base?',
      affirmative: ['I watched a movie.', 'She went home.'], negative: ['I didn\'t watch it.', 'She didn\'t go.'], interrogative: ['Did you watch it?', 'Where did she go?'],
      compare: 'Simple present (I play every day) × simple past (I played yesterday).', context: 'Contar uma viagem ou o fim de semana.',
    },
    reading: {
      title: 'My trip to Bonito', genre: 'relato de viagem',
      text: 'Last July, my family went to Bonito, in Mato Grosso do Sul. We stayed in a small hotel near a river. On the first day, we snorkeled in crystal-clear water and saw hundreds of fish. My little brother didn\'t want to go in the water at first, but then he loved it. On the last day it rained, so we visited a museum. It was the best trip of my life!',
      questions: [
        mci(1, 'Quando foi a viagem?', ['Julho passado', 'Junho passado', 'Ano que vem', 'Ontem'], 0, '“Last July”.'),
        mci(2, 'O que eles viram na água?', ['Tubarões', 'Centenas de peixes', 'Golfinhos', 'Tartarugas'], 1, '“saw hundreds of fish”.'),
        mci(2, 'Como o irmão se sentiu no final?', ['Continuou com medo', 'Adorou', 'Ficou doente', 'Não entrou na água'], 1, '“but then he loved it”.'),
        mci(3, 'Por que visitaram um museu no último dia?', ['Porque estava chovendo', 'Porque o hotel fechou', 'Porque o irmão pediu', 'Porque era de graça'], 0, '“it rained, so we visited a museum”.'),
      ],
    },
    writing: {
      prompt: 'Conte o seu último fim de semana em pelo menos 5 frases no simple past (use 2 verbos irregulares).', criteria: ['Marcadores de tempo (on Saturday, last…)', '2 irregulares', '1 negativa com didn\'t'],
      model: 'Last Saturday I woke up late. I went to the park with my cousin and we played basketball. We didn\'t go to the mall. In the evening I watched a movie.', keywords: ['went', 'didn\'t', 'last', 'ed'], minWords: 25,
    },
    challenge: 'Faça 3 perguntas com Did… para alguém da sua casa sobre o dia de ontem e anote as respostas em inglês.',
  },
  games: {
    blanks: [
      blank(1, 'We ___ a pizza last night.', ['ate', 'eat', 'eated', 'eats'], 0, 'Eat → ate.'),
      blank(1, 'She ___ happy yesterday.', ['was', 'were', 'did', 'is'], 0, 'She → was.'),
      blank(2, 'I ___ finish my homework.', ['didn\'t', 'don\'t', 'wasn\'t', 'not'], 0, 'Passado negativo: didn\'t.'),
      blank(2, 'What ___ you do on Sunday?', ['did', 'do', 'were', 'was'], 0, 'Pergunta no passado: did.'),
      blank(3, 'They moved to Brazil five years ___.', ['ago', 'last', 'before of', 'yesterday'], 0, 'Tempo + ago = há… (atrás).'),
    ],
    pairs: [{ a: 'go', b: 'went', difficulty: 1 }, { a: 'take', b: 'took', difficulty: 2 }, { a: 'write', b: 'wrote', difficulty: 2 }, { a: 'come', b: 'came', difficulty: 1 }, { a: 'make', b: 'made', difficulty: 1 }, { a: 'say', b: 'said', difficulty: 2 }, { a: 'think', b: 'thought', difficulty: 3 }, { a: 'teach', b: 'taught', difficulty: 3 }],
    sequences: [words(1, 'I visited my grandma yesterday', 'Sujeito + verbo-ed + complemento + tempo.'), words(2, 'Did you see the game', 'Did + sujeito + verbo base.'), words(3, 'She didn\'t buy the tickets', 'didn\'t + verbo base.')],
    dialogues: [
      dialogue(2, 'Segunda-feira de manhã', ['Kim: How was your weekend?', 'Rui: It was great! I went camping.', 'Kim: Cool! Did you see any animals?', 'Rui: Yes, I saw a fox!'], 1, ['It was great! I went camping.', 'It is great! I go camping.', 'It were great! I goed camping.', 'It was great! I go camping.'], 0, 'Passado: was + went.'),
    ],
  },
  sources: enSources(),
})

export const pastContinuous = lesson({
  id: 'ing-a2-past-continuous', subject: 'ingles', title: 'Past continuous', levels: [...LV], grade: '8º e 9º ano',
  topic: 'Inglês A2 — Agora e antes', subtopic: 'Past continuous, when e while',
  aliases: ['past continuous', 'passado continuo', 'was were ing', 'when while', 'estava fazendo em ingles', 'past progressive'],
  summary: 'Descreva o que estava acontecendo no passado e interrompa a cena com when e while.',
  intro: 'I was sleeping when the phone rang… Vamos montar cenas do passado.',
  objective: 'Formar o past continuous, usá-lo para cenas e ações em andamento no passado e combiná-lo com o simple past usando when e while.',
  prerequisites: ['ing-a2-simple-past', 'ing-a2-present-continuous'], next: ['ing-a2-future'],
  skills: { g_form: 'Was/were + -ing', g_when: 'Ação longa interrompida (when)', g_while: 'Ações simultâneas (while)', g_negq: 'Negativa e pergunta' },
  blocks: [
    block('g_form', 'was / were + verb-ing',
      'O past continuous mostra algo que estava em andamento num momento do passado: was/were + verbo-ing. At 8 pm yesterday I was having dinner. Serve para descrever o cenário de uma história.',
      'At 10 o\'clock we were playing chess. · It was raining all morning.',
      'É o nosso “estava fazendo”: I was reading = eu estava lendo.',
      'Começo de conto: “The sun was shining and the birds were singing.”',
      '1. Sujeito. 2. Was (I/he/she/it) ou were (you/we/they). 3. Verbo + ing.',
      'Present continuous (I am reading agora) → past continuous (I was reading ontem às 9h). Só o verb to be vai para o passado.'),
    block('g_when', 'Interrupted actions: when',
      'Uma ação longa (past continuous) pode ser interrompida por uma curta (simple past), geralmente com when: I was taking a shower when the lights went out. A ação curta é o “acontecimento”.',
      'She was walking home when she found a wallet.',
      'Estava fazendo algo (longa) QUANDO aconteceu outra coisa (curta).',
      'Relato: “We were watching TV when the dog started barking.”',
      '1. Qual ação durou mais? → past continuous. 2. Qual interrompeu? → simple past. 3. Ligue com when.',
      'Imagine um filme: a cena de fundo (was raining) e o acontecimento que corta a cena (the phone rang).'),
    block('g_while', 'Simultaneous actions: while',
      'Com while mostramos duas ações longas ao mesmo tempo, as duas no past continuous: While I was cooking, my sister was setting the table. While também aparece antes da ação longa: While I was studying, the phone rang.',
      'While Dad was driving, we were singing.',
      'While = enquanto. Duas coisas acontecendo juntas.',
      'Na festa: “While some people were dancing, others were eating.”',
      '1. While + ação longa. 2. Vírgula se a frase começar com while. 3. A outra ação: longa (were) ou curta (simple past).',
      'When costuma vir com a ação curta; while, com a ação longa: I was sleeping when you called / While I was sleeping, you called.'),
    block('g_negq', 'Negative and questions',
      'Negativa: wasn\'t / weren\'t + -ing: I wasn\'t listening. Pergunta: Was/Were + sujeito + -ing? What were you doing at 9 pm? — I was studying.',
      '— Were you sleeping? — No, I wasn\'t. I was reading.',
      'Negativa: wasn\'t/weren\'t. Pergunta: Was/Were no começo.',
      'Detetive: “What were you doing at eight o\'clock last night?”',
      '1. Negativa: was/were + not. 2. Pergunta: inverta. 3. Resposta: Yes, I was / No, they weren\'t.',
      'Assim como no present continuous, não usamos did: “Were you working?” e não “Did you working?”.'),
  ],
  questions: [
    mc(1, 'g_form', 'At 9 pm yesterday, I ___ TV.', ['watched', 'was watching', 'am watching', 'were watching'], 1, ['Ação em andamento num horário do passado.', 'I → was.', 'Was + -ing.'], 'I was watching TV.'),
    mc(1, 'g_form', 'They ___ soccer when it started to rain.', ['was playing', 'were playing', 'played', 'are playing'], 1, ['They → were.', 'Ação longa interrompida.', 'Were + -ing.'], 'They were playing.'),
    fill(1, 'g_negq', 'Negativa: She ___ listening. (was not)', ['wasn\'t', 'was not'], ['Contração de was not.', 'wasn…', 'wasn\'t.'], 'She wasn\'t listening.'),
    tf(1, 'g_when', 'Em “I was cooking when the doorbell rang”, a ação curta é “the doorbell rang”.', true, ['Qual durou mais?', 'Cozinhar dura mais.', 'A campainha interrompe.'], 'Verdadeiro.'),
    match(2, 'g_form', 'Ligue o sujeito à forma correta.', [['I', 'was reading'], ['you', 'were reading'], ['she', 'was sleeping'], ['they', 'were sleeping']], ['I e she usam was.', 'You e they usam were.', 'Depois o -ing.'], 'I was · you were · she was · they were.'),
    mc(2, 'g_when', 'I ___ a shower when the lights ___ out.', ['was taking / went', 'took / were going', 'was taking / was going', 'take / went'], 0, ['Banho = ação longa.', 'A luz apagou = ação curta.', 'Past continuous + simple past.'], 'was taking / went.'),
    mc(2, 'g_while', '___ I was studying, my brother was playing video games.', ['When', 'While', 'During', 'Because'], 1, ['Duas ações longas juntas.', 'Enquanto = …', 'While.'], 'While = enquanto.'),
    mc(2, 'g_negq', '— What ___ you doing at 7? — I was having dinner.', ['were', 'did', 'was', 'are'], 0, ['Pergunta no past continuous.', 'You → were.', 'Were.'], 'What were you doing?'),
    order(3, 'g_when', 'Organize: “Ela estava andando quando viu um gato.”', ['She', 'was', 'walking', 'when', 'she', 'saw', 'a', 'cat'], ['Comece pela ação longa.', 'Depois when.', 'Ação curta no simple past.'], 'She was walking when she saw a cat.'),
    mc(3, 'g_while', 'Qual frase está correta?', ['While I slept, the phone was ringing all night.', 'When I was sleeping, the phone rang.', 'While I was sleeping, the phone rang.', 'While I sleeping, the phone rang.'], 2, ['While vem com a ação longa.', 'Ação longa no past continuous.', 'Ação curta no simple past.'], 'While I was sleeping, the phone rang.'),
  ],
  review: ['was/were + -ing = estava fazendo', 'Longa (past continuous) + when + curta (simple past)', 'While + duas ações longas', 'wasn\'t/weren\'t · Were you…?'],
  relatedQuestions: ['como usar o past continuous', 'diferença entre when e while', 'diferença entre simple past e past continuous'],
  equivalentQuestions: eqs(['past continuous', 'passado contínuo'], ['como dizer eu estava fazendo em inglês', 'quando usar was e were com ing', 'when ou while', 'diferença entre past continuous e simple past', 'como contar uma história no passado em inglês', 'what were you doing']),
  commonErrors: ['Usar was com you/we/they.', 'Colocar as duas ações no past continuous quando uma interrompe a outra.', 'Usar did nas perguntas (Did you sleeping?).'],
  english: {
    cefr: 'A2', unit: 'a2-u2', order: 2, area: 'grammar', focus: ['grammar', 'reading', 'writing'],
    vocabulary: [
      v('while', 'enquanto', 'conjunction', 'during the time that', 'While I was cooking, he called.', 2),
      v('when', 'quando', 'conjunction', 'at the time that', 'I was reading when you arrived.', 1),
      v('suddenly', 'de repente', 'adverb', 'quickly and unexpectedly', 'Suddenly, the lights went out.', 2),
      v('shine', 'brilhar', 'verb', 'to give light (the sun)', 'The sun was shining.', 2),
      v('ring', 'tocar (telefone, campainha)', 'verb', 'to make a bell sound', 'The phone rang twice.', 2),
      v('noise', 'barulho', 'noun', 'a loud or strange sound', 'I heard a noise.', 1),
      v('storm', 'tempestade', 'noun', 'very bad weather with wind and rain', 'There was a big storm.', 2),
    ],
    reading: {
      title: 'The night of the storm', genre: 'conto curto',
      text: 'It was a dark night. Rain was falling and the wind was blowing hard. Mila was reading in bed while her parents were watching a movie downstairs. Suddenly, she heard a strange noise at the window. She was feeling scared when a small wet cat jumped onto her bed. The family adopted it the next day and called it Storm.',
      questions: [
        mci(1, 'O que Mila estava fazendo?', ['Assistindo a um filme', 'Lendo na cama', 'Dormindo', 'Cozinhando'], 1, '“Mila was reading in bed”.'),
        mci(2, 'O que os pais estavam fazendo ao mesmo tempo?', ['Lendo', 'Assistindo a um filme', 'Conversando', 'Dormindo'], 1, '“while her parents were watching a movie”.'),
        mci(2, 'O que interrompeu a leitura?', ['Uma ligação', 'Um barulho na janela', 'A luz apagou', 'A mãe chamou'], 1, '“she heard a strange noise at the window”.'),
        mci(3, 'Por que o gato recebeu o nome Storm?', ['Porque era bravo', 'Porque apareceu numa noite de tempestade', 'Porque era cinza', 'Porque era da vizinha'], 1, 'Ele apareceu durante a tempestade (storm).'),
      ],
    },
    writing: {
      prompt: 'Escreva o início de uma história: descreva a cena (past continuous) e um acontecimento que interrompe (when + simple past).', criteria: ['Cenário com was/were + -ing', 'Uma interrupção com when', 'Uma frase com while'],
      model: 'It was a sunny afternoon. The kids were playing in the park while their parents were talking. Suddenly, a big dog appeared when a boy was eating an ice cream.', keywords: ['was', 'were', 'when', 'while'], minWords: 25,
    },
    challenge: 'Diga o que você estava fazendo ontem às 8h, às 15h e às 21h.',
  },
  games: {
    blanks: [
      blank(1, 'We ___ dinner at 8 pm.', ['were having', 'was having', 'had having', 'are having'], 0, 'We → were + -ing.'),
      blank(2, 'She was reading ___ the phone rang.', ['when', 'while', 'during', 'so'], 0, 'Interrupção curta: when.'),
      blank(2, '___ I was walking, I listened to music.', ['While', 'When', 'Then', 'After'], 0, 'While + ação longa.'),
      blank(3, 'I ___ attention, so I didn\'t hear the question.', ['wasn\'t paying', 'didn\'t paying', 'weren\'t paying', 'not paid'], 0, 'Negativa: wasn\'t + -ing.'),
    ],
    sequences: [words(2, 'It was raining when I left home', 'Ação longa + when + ação curta.'), words(3, 'What were you doing last night', 'Pergunta: What + were + you + -ing.')],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 3 · Plans and predictions ═══════════════════
export const future = lesson({
  id: 'ing-a2-future', subject: 'ingles', title: 'Future: will and going to', levels: [...LV], grade: '8º e 9º ano',
  topic: 'Inglês A2 — Planos e comparações', subtopic: 'Will, going to e present continuous para o futuro',
  aliases: ['future', 'futuro em ingles', 'will', 'going to', 'will ou going to', 'planos em ingles', 'previsoes em ingles', 'future forms'],
  summary: 'Fale de planos, decisões, previsões e compromissos escolhendo entre will, going to e o present continuous.',
  intro: 'What are you going to do tomorrow? Vamos falar do futuro.',
  objective: 'Escolher entre will (decisão na hora, promessa, previsão por opinião), going to (plano, previsão com evidência) e present continuous (compromisso marcado).',
  prerequisites: ['ing-a2-present-continuous'], next: ['ing-a2-comparatives'],
  skills: { g_will: 'Will: decisões, promessas e previsões', g_going: 'Going to: planos e evidências', g_arr: 'Present continuous para compromissos', g_choose: 'Escolher a forma certa' },
  blocks: [
    block('g_will', 'Will',
      'Will + verbo base (I\'ll, she\'ll): decisões na hora (I\'ll have the chicken), promessas e ofertas (I\'ll help you), previsões baseadas em opinião (I think it will be fun). Negativa: won\'t (will not). Pergunta: Will you come?',
      'The phone is ringing. — I\'ll get it! · I won\'t tell anyone, I promise.',
      'Will = vou (decidido agora) / vai (acho que vai).',
      'Garçom pergunta, você decide na hora: “I\'ll have orange juice, please.”',
      '1. Decidiu agora ou prometeu? will. 2. É uma opinião sobre o futuro (I think…)? will. 3. Verbo sem to depois de will.',
      'Won\'t parece “want”, mas é a negativa de will: I won\'t go = eu não vou.'),
    block('g_going', 'Going to',
      'Am/is/are + going to + verbo: planos e intenções já decididos antes (I\'m going to study medicine) e previsões com evidência no presente (Look at those clouds! It\'s going to rain).',
      'We\'re going to visit Salvador in July. · Careful! You\'re going to fall!',
      'Going to = vou (já planejei) / vai (dá para ver que vai acontecer).',
      'Metas do ano: “I\'m going to read ten books this year.”',
      '1. Já tinha decidido? going to. 2. Há uma prova agora (nuvens, alguém tropeçando)? going to. 3. Estrutura: am/is/are + going to + verbo.',
      'Will = opinião (I think it will rain). Going to = evidência (Look at the sky! It\'s going to rain).'),
    block('g_arr', 'Present continuous for arrangements',
      'Para compromissos marcados, com hora e lugar, usamos o present continuous com sentido de futuro: I\'m meeting Ana at 5. We\'re flying to Lisbon on Friday.',
      'What are you doing tonight? — I\'m going to the cinema with Leo.',
      'Compromisso marcado na agenda → I\'m + -ing.',
      'Consulta marcada: “I\'m seeing the dentist tomorrow at 10.”',
      '1. Está marcado com alguém, com dia/hora? 2. Use am/is/are + -ing. 3. Inclua a expressão de tempo (tomorrow, on Friday).',
      'Em português também fazemos isso: “Amanhã eu viajo” (presente com sentido de futuro).'),
    block('g_choose', 'Which future?',
      'Resumo: decisão agora, promessa, oferta → will. Plano/intenção → going to. Evidência → going to. Compromisso marcado → present continuous. Horários fixos (trem, filme) → simple present: The train leaves at 7.',
      'The movie starts at 8. We\'re meeting at 7:30. I think we\'ll love it!',
      'Pergunte: decidi agora? planejei antes? tenho prova? está marcado?',
      'Planejando o sábado: “I\'m going to relax. Maybe I\'ll watch a series.”',
      '1. Identifique a situação. 2. Escolha a forma. 3. Confira a estrutura.',
      'Em muitas conversas, will e going to aparecem juntos: o plano (going to) e a decisão na hora (will).'),
  ],
  questions: [
    mc(1, 'g_will', 'The phone is ringing. — I ___ answer it!', ['\'ll', '\'m going to', '\'m answering', 'answer'], 0, ['Decisão tomada agora.', 'Ninguém planejou isso antes.', 'Will.'], 'Decisão na hora: I\'ll answer it.'),
    mc(1, 'g_going', 'Look at those black clouds! It ___ rain.', ['will', 'is going to', 'rains', 'is raining'], 1, ['Há uma evidência?', 'As nuvens são a prova.', 'Evidência → going to.'], 'Evidência: It\'s going to rain.'),
    fill(1, 'g_will', 'Negativa de will: I ___ tell anyone.', ['won\'t', 'will not'], ['Contração de will not.', 'Parece “want”, mas não é.', 'w-o-n-\'-t.'], 'I won\'t tell anyone.'),
    tf(1, 'g_going', '“We are going to visit Rio next month” fala de um plano.', true, ['Going to = plano.', 'Next month = futuro.', 'Eles já decidiram.'], 'Verdadeiro.'),
    match(2, 'g_choose', 'Ligue a situação à forma de futuro.', [['Decisão na hora', 'will'], ['Plano já decidido', 'going to'], ['Compromisso marcado', 'present continuous'], ['Horário fixo (trem)', 'simple present']], ['Resumo do bloco final.', 'Agenda com hora → -ing.', 'Tabela de horário → presente simples.'], 'decisão will · plano going to · compromisso present continuous · horário simple present.'),
    mc(2, 'g_arr', 'Já está marcado: “I ___ the dentist tomorrow at 10.”', ['will see', 'see', 'am seeing', 'saw'], 2, ['Compromisso com hora.', 'Está na agenda.', 'Present continuous.'], 'I\'m seeing the dentist tomorrow.'),
    mc(2, 'g_will', 'Qual é uma previsão baseada em opinião?', ['I think Brazil will win.', 'Look! He\'s going to fall.', 'I\'m meeting Ana at 5.', 'The train leaves at 7.'], 0, ['Procure “I think”.', 'Opinião, sem evidência.', 'Will.'], 'I think Brazil will win.'),
    mc(2, 'g_going', 'Qual frase está correta?', ['She is going to studies medicine.', 'She going to study medicine.', 'She is going to study medicine.', 'She will going to study medicine.'], 2, ['Precisa do verb to be.', 'Going to + verbo base.', 'Sem will junto.'], 'She is going to study medicine.'),
    order(3, 'g_arr', 'Organize: “O que você vai fazer hoje à noite?”', ['What', 'are', 'you', 'doing', 'tonight?'], ['Pergunta sobre compromissos.', 'Present continuous.', 'Tonight no final.'], 'What are you doing tonight?'),
    mc(3, 'g_choose', 'A: “We don\'t have any milk.” B: “Oh, really? I ___ buy some.”', ['\'ll', '\'m going to', 'buy', '\'m buying'], 0, ['B acabou de saber.', 'Decisão na hora.', 'Will.'], 'Soube agora e decidiu: I\'ll buy some.'),
  ],
  review: ['Will: decisão agora, promessa, oferta, opinião (I think…)', 'Going to: plano ou evidência (Look! It\'s going to…)', 'Present continuous: compromisso marcado', 'Horário fixo: simple present'],
  relatedQuestions: ['diferença entre will e going to', 'como falar do futuro em inglês', 'quando usar present continuous para o futuro'],
  equivalentQuestions: eqs(['futuro em inglês', 'will e going to'], ['quando usar will', 'quando usar going to', 'will ou going to para previsão', 'o que significa won\'t', 'como falar de planos em inglês', 'como dizer eu vou viajar em inglês', 'present continuous com sentido de futuro']),
  commonErrors: ['Juntar will e going to (will going to).', 'Esquecer o verb to be em going to (She going to…).', 'Usar will para planos já decididos.'],
  english: {
    cefr: 'A2', unit: 'a2-u3', order: 1, area: 'grammar', focus: ['grammar', 'listening', 'speaking'],
    vocabulary: [
      v('plan', 'plano / planejar', 'noun', 'something you decided to do', 'What are your plans for the weekend?', 1),
      v('tomorrow', 'amanhã', 'adverb', 'the day after today', 'See you tomorrow!', 1),
      v('next', 'próximo(a)', 'determiner', 'the one after this one', 'Next year I\'m going to learn Spanish.', 1),
      v('promise', 'prometer', 'verb', 'to say you will certainly do something', 'I promise I\'ll call you.', 2),
      v('probably', 'provavelmente', 'adverb', 'very likely', 'It will probably be hot.', 2),
      v('maybe', 'talvez', 'adverb', 'perhaps', 'Maybe I\'ll go to the party.', 1),
      v('tonight', 'hoje à noite', 'adverb', 'this evening or night', 'What are you doing tonight?', 1),
    ],
    grammar: {
      name: 'Future forms', when: 'Decisões, planos, previsões e compromissos.', structure: 'will + base · am/is/are going to + base · am/is/are + -ing',
      affirmative: ['I\'ll help you.', 'We\'re going to travel.', 'I\'m meeting Ana at 5.'], negative: ['I won\'t forget.', 'She isn\'t going to come.'], interrogative: ['Will you help me?', 'Are you going to study?', 'What are you doing tomorrow?'],
      compare: 'I think it will rain (opinião) × Look! It\'s going to rain (evidência).', context: 'Combinar o fim de semana com os amigos.',
    },
    listening: {
      title: 'Planos para as férias', kind: 'dialogo', rate: 0.9,
      script: ['Sam: What are you going to do in the holidays?', 'Lia: I\'m going to visit my cousins in Recife.', 'Sam: Nice! When are you leaving?', 'Lia: I\'m flying on Saturday morning.', 'Sam: I think you\'ll love the beaches there.', 'Lia: I\'m sure I will! I\'ll send you photos.'],
      questions: [
        mci(1, 'Quem Lia vai visitar?', ['Os avós', 'Os primos', 'Os tios', 'Uma amiga'], 1, '“visit my cousins”.'),
        mci(2, 'Quando ela viaja?', ['Sábado de manhã', 'Domingo à noite', 'Sexta à tarde', 'Não diz'], 0, '“I\'m flying on Saturday morning.”'),
        mci(3, 'O que ela promete?', ['Trazer um presente', 'Mandar fotos', 'Ligar todo dia', 'Voltar cedo'], 1, '“I\'ll send you photos.” (promessa com will)'),
      ],
    },
    speaking: {
      situation: 'Um colega pergunta sobre os seus planos para o próximo fim de semana.', vocabulary: ['going to', 'I\'ll', 'maybe', 'tonight'],
      phrases: ['I\'m going to…', 'Maybe I\'ll…', 'On Saturday I\'m meeting…'], example: 'On Saturday I\'m going to play soccer. Maybe I\'ll watch a movie at night.',
      challenge: 'Fale um plano (going to), uma possibilidade (maybe I\'ll) e um compromisso marcado (I\'m + -ing).', expected: ['going', 'maybe', 'will'],
    },
    challenge: 'Escreva 3 metas para o próximo mês com going to e 1 promessa com will.',
  },
  games: {
    blanks: [
      blank(1, 'I\'m tired. I think I ___ go to bed.', ['will', 'am going', 'going', 'goes'], 0, 'Decisão agora: will.'),
      blank(1, 'We ___ going to travel in July.', ['are', 'will', 'is', 'do'], 0, 'We are going to…'),
      blank(2, 'Careful! That glass ___ fall!', ['is going to', 'will to', 'falls', 'going'], 0, 'Evidência: is going to.'),
      blank(2, 'I ___ tell your secret. I promise!', ['won\'t', 'don\'t', 'am not', 'not will'], 0, 'Promessa negativa: won\'t.'),
      blank(3, 'The bus ___ at 6:15 every morning.', ['leaves', 'will leave', 'is going to leave', 'leaving'], 0, 'Horário fixo: simple present.'),
    ],
    sequences: [words(1, 'I will help you', 'Oferta: will + verbo.'), words(2, 'She is going to buy a bike', 'Plano: is going to + verbo.')],
    dialogues: [
      dialogue(2, 'No restaurante', ['Waiter: Are you ready to order?', 'Leo: Yes. I\'ll have the fish, please.', 'Waiter: Great choice!'], 1, ['Yes. I\'ll have the fish, please.', 'Yes. I\'m going to have fish every day.', 'Yes. I had the fish.', 'Yes. I have fish tomorrow.'], 0, 'Decisão na hora: I\'ll have…'),
      dialogue(3, 'Combinando', ['Bia: What are you doing on Friday?', 'Rafa: I\'m meeting my cousin at the mall.', 'Bia: Oh! Maybe I\'ll go too.'], 1, ['I\'m meeting my cousin at the mall.', 'I meet my cousin yesterday.', 'I\'ll met my cousin.', 'I going to meet cousin.'], 0, 'Compromisso marcado: present continuous.'),
    ],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 4 · Better, best ═══════════════════
export const comparatives = lesson({
  id: 'ing-a2-comparatives', subject: 'ingles', title: 'Comparatives and superlatives', levels: [...LV], grade: '7º ao 9º ano',
  topic: 'Inglês A2 — Planos e comparações', subtopic: 'Comparativos e superlativos',
  aliases: ['comparativo em ingles', 'superlativo em ingles', 'comparatives', 'superlatives', 'er than', 'the most', 'better best', 'as as'],
  summary: 'Compare pessoas, lugares e coisas com -er/more, the -est/the most, os irregulares e as…as.',
  intro: 'Which is bigger: Brazil or Argentina? Vamos comparar!',
  objective: 'Formar comparativos e superlativos de adjetivos curtos, longos e irregulares e fazer comparações de igualdade com as…as.',
  prerequisites: ['ing-a1-this-that'], next: ['ing-a2-quantifiers'],
  skills: { g_comp: 'Comparativo (-er than / more … than)', g_sup: 'Superlativo (the -est / the most)', g_irr: 'Irregulares (good, bad, far)', g_as: 'Igualdade (as … as)' },
  blocks: [
    block('g_comp', 'Comparatives',
      'Adjetivos curtos (1 sílaba) ganham -er + than: tall → taller than. Terminados em -y: -ier (happy → happier). Consoante-vogal-consoante dobra: big → bigger. Adjetivos longos (2+ sílabas, na maioria): more + adjetivo + than: more expensive than.',
      'My brother is taller than me. · This phone is more expensive than that one.',
      'Mais alto que = taller than. Mais caro que = more expensive than.',
      'Comparando cidades: “São Paulo is bigger than Curitiba.”',
      '1. Conte as sílabas. 2. Curto: -er; longo: more. 3. Termine com than.',
      'Em português sempre usamos “mais”: mais alto, mais caro. Em inglês, adjetivo curto ganha -er e não usa more: “more tall” está errado.'),
    block('g_sup', 'Superlatives',
      'O superlativo mostra o “mais” de um grupo: the + adjetivo curto + -est (the tallest), -iest (the happiest), the most + adjetivo longo (the most beautiful). Geralmente vem com in/of: the tallest in the class.',
      'Mount Everest is the highest mountain in the world. · It\'s the most interesting book I\'ve read.',
      'O mais alto = the tallest. O mais bonito = the most beautiful.',
      'Ranking: “The Amazon is the largest rainforest in the world.”',
      '1. Use the. 2. Curto: -est; longo: most. 3. Complete com in/of + grupo.',
      'Comparativo compara DOIS (taller than); superlativo destaca UM de um grupo (the tallest in the class).'),
    block('g_irr', 'Irregular forms',
      'Alguns são irregulares: good → better → the best; bad → worse → the worst; far → farther/further → the farthest/furthest; many/much → more → the most; little → less → the least.',
      'Today is better than yesterday. · This is the worst movie ever!',
      'Bom → melhor → o melhor = good → better → the best.',
      'Avaliação de restaurante: “The food was good, but the dessert was the best!”',
      '1. Decore os 4 principais: good, bad, far, many. 2. Treine em frases. 3. Nunca diga “gooder”.',
      'Igual ao português: “bom” não vira “mais bom”, vira “melhor”. Em inglês, good vira better.'),
    block('g_as', 'As … as',
      'Para igualdade: as + adjetivo + as (tão … quanto): She is as tall as her mother. Negativa: not as … as (não tão … quanto): This test isn\'t as difficult as the last one.',
      'My dog is as friendly as yours. · Winter here isn\'t as cold as in Canada.',
      'As tall as = tão alto quanto.',
      'Comparando notas: “My grade isn\'t as good as I wanted.”',
      '1. As. 2. Adjetivo na forma normal. 3. As + o que é comparado.',
      '“Not as big as” e “smaller than” dizem quase a mesma coisa — a primeira forma soa mais delicada.'),
  ],
  questions: [
    mc(1, 'g_comp', 'An elephant is ___ than a dog.', ['big', 'bigger', 'more big', 'biggest'], 1, ['Comparando dois.', 'Big é curto.', 'Dobra o g + er.'], 'Bigger than.'),
    mc(1, 'g_irr', 'Qual é o comparativo de “good”?', ['gooder', 'more good', 'better', 'best'], 2, ['É irregular.', 'Não é best (superlativo).', 'Better.'], 'Good → better.'),
    fill(1, 'g_comp', 'Complete: My sister is ______ (happy) than me.', ['happier'], ['Termina em -y.', 'Y vira i.', 'happi + er.'], 'Happy → happier.'),
    tf(1, 'g_sup', '“The most tall student” está correto.', false, ['Tall é curto ou longo?', 'Curto usa -est.', 'The tallest.'], 'Falso: the tallest student.'),
    match(2, 'g_irr', 'Ligue o adjetivo ao seu superlativo.', [['good', 'the best'], ['bad', 'the worst'], ['far', 'the farthest'], ['beautiful', 'the most beautiful']], ['Good → best.', 'Bad → worst.', 'Beautiful é longo.'], 'the best · the worst · the farthest · the most beautiful.'),
    mc(2, 'g_comp', 'This book is ___ than the movie.', ['interestinger', 'more interesting', 'most interesting', 'as interesting'], 1, ['Interesting é longo.', 'More + adjetivo.', 'Than no final.'], 'More interesting than.'),
    mc(2, 'g_sup', 'Brazil is ___ country in South America.', ['the biggest', 'bigger', 'the most big', 'biggest than'], 0, ['Um de um grupo.', 'Superlativo.', 'The + big + g + est.'], 'The biggest country.'),
    mc(2, 'g_as', 'Tom tem 1,70 m e Leo também. Tom is ___ Leo.', ['taller than', 'as tall as', 'the tallest', 'not as tall as'], 1, ['Têm a mesma altura.', 'Igualdade.', 'As … as.'], 'As tall as.'),
    order(3, 'g_sup', 'Organize: “É o pior dia da minha vida!”', ['It\'s', 'the', 'worst', 'day', 'of', 'my', 'life!'], ['Superlativo de bad.', 'The worst.', 'Of my life no final.'], 'It\'s the worst day of my life!'),
    mc(3, 'g_as', 'Qual frase tem o mesmo sentido de “My city is smaller than yours”?', ['My city is as big as yours.', 'My city isn\'t as big as yours.', 'My city is the biggest.', 'My city is bigger than yours.'], 1, ['Se é menor, não é tão grande.', 'Negativa de as…as.', 'Not as big as.'], 'Isn\'t as big as = é menor.'),
  ],
  review: ['Curto: -er than / the -est · longo: more … than / the most', 'happy → happier; big → bigger', 'good-better-best · bad-worse-worst · far-farther-farthest', 'as … as (igual) · not as … as'],
  relatedQuestions: ['como fazer comparativo em inglês', 'diferença entre comparativo e superlativo', 'better ou best'],
  equivalentQuestions: eqs(['comparativo em inglês', 'superlativo em inglês'], ['quando usar more e quando usar er', 'comparativo de good', 'superlativo de bad', 'como dizer mais alto que em inglês', 'como dizer o maior do mundo em inglês', 'o que significa as tall as', 'por que bigger tem dois g']),
  commonErrors: ['Usar more com adjetivo curto (more tall).', 'Esquecer o the no superlativo.', 'Dizer gooder/baddest.'],
  english: {
    cefr: 'A2', unit: 'a2-u4', order: 1, area: 'grammar', focus: ['grammar', 'reading', 'vocabulary'],
    vocabulary: [
      v('tall', 'alto(a) (pessoa)', 'adjective', 'having a big height', 'My dad is tall.', 1, { antonyms: ['short'] }),
      v('expensive', 'caro(a)', 'adjective', 'costing a lot of money', 'This bag is expensive.', 1, { antonyms: ['cheap'] }),
      v('cheap', 'barato(a)', 'adjective', 'not costing much money', 'The bus is cheaper than the taxi.', 1, { antonyms: ['expensive'] }),
      v('fast', 'rápido(a)', 'adjective', 'moving quickly', 'Cheetahs are the fastest animals.', 1, { antonyms: ['slow'] }),
      v('dangerous', 'perigoso(a)', 'adjective', 'able to hurt you', 'Sharks can be dangerous.', 2),
      v('large', 'grande', 'adjective', 'big', 'The Amazon is the largest rainforest.', 2, { synonyms: ['big'] }),
      v('worse', 'pior', 'adjective', 'comparative of bad', 'The traffic is worse today.', 2),
      v('best', 'o(a) melhor', 'adjective', 'superlative of good', 'She\'s my best friend.', 1),
    ],
    reading: {
      title: 'Record breakers', genre: 'texto informativo',
      text: 'The cheetah is the fastest land animal: it can run at about 100 km per hour. The blue whale is the largest animal that has ever lived — it is bigger than any dinosaur we know. The Amazon River carries more water than any other river in the world, and the Sahara is the largest hot desert on Earth.',
      questions: [
        mci(1, 'Qual é o animal terrestre mais rápido?', ['Leão', 'Guepardo (cheetah)', 'Cavalo', 'Baleia'], 1, '“The cheetah is the fastest land animal”.'),
        mci(2, 'O que o texto diz sobre a baleia-azul?', ['É menor que alguns dinossauros', 'É o maior animal que já existiu', 'É o mais rápido do mar', 'Vive no Rio Amazonas'], 1, '“the largest animal that has ever lived”.'),
        mci(3, 'Qual recorde do Rio Amazonas aparece no texto?', ['É o mais longo', 'Leva mais água que qualquer outro rio', 'É o mais frio', 'É o mais antigo'], 1, '“carries more water than any other river”.'),
      ],
    },
    writing: {
      prompt: 'Compare duas cidades, dois animais ou dois times usando comparativo, superlativo e as…as.', criteria: ['1 comparativo com than', '1 superlativo com the', '1 frase com as…as'],
      model: 'Salvador is hotter than Porto Alegre. Porto Alegre is bigger than Florianópolis, but it isn\'t as beautiful. For me, Salvador has the best food in Brazil.', keywords: ['than', 'the', 'as'], minWords: 20,
    },
    challenge: 'Faça um ranking dos 3 melhores filmes ou jogos que você conhece usando the best, better than e the most.',
  },
  games: {
    blanks: [
      blank(1, 'A car is ___ than a bike.', ['faster', 'fast', 'more fast', 'fastest'], 0, 'Fast (curto) → faster.'),
      blank(1, 'She\'s ___ student in the class.', ['the best', 'better', 'the good', 'best than'], 0, 'Superlativo de good: the best.'),
      blank(2, 'Gold is ___ than silver.', ['more expensive', 'expensiver', 'most expensive', 'as expensive'], 0, 'Expensive (longo) → more expensive.'),
      blank(2, 'My room isn\'t ___ big ___ yours.', ['as / as', 'more / than', 'so / that', 'the / of'], 0, 'Not as … as.'),
      blank(3, 'Today\'s traffic is ___ than yesterday\'s.', ['worse', 'badder', 'worst', 'more bad'], 0, 'Bad → worse.'),
    ],
    pairs: [{ a: 'big', b: 'bigger', difficulty: 1 }, { a: 'happy', b: 'happier', difficulty: 2 }, { a: 'good', b: 'better', difficulty: 1 }, { a: 'bad', b: 'worse', difficulty: 2 }, { a: 'far', b: 'farther', difficulty: 3 }],
    sequences: [words(1, 'My brother is taller than me', 'Adjetivo curto + er + than.'), words(2, 'It is the most beautiful beach', 'The most + adjetivo longo.')],
  },
  sources: enSources(),
})
