// Curso de Inglês do LUMI — níveis B2 (Intermediário avançado) e C1 (Avançado). Conteúdo original.
import { block, blank, dialogue, enSources, eqs, fill, lesson, match, mc, mci, order, tf, v, words } from '../dsl'

const LV = ['medio'] as const

// ═══════════════════ B2 · Unidade 1 · It was made… ═══════════════════
export const passive = lesson({
  id: 'ing-b2-passive', subject: 'ingles', title: 'Passive voice', levels: [...LV], grade: 'Ensino Médio',
  topic: 'Inglês B2 — Como a informação é contada', subtopic: 'Voz passiva nos principais tempos',
  aliases: ['passive voice', 'voz passiva em ingles', 'passiva', 'was made', 'is made', 'be particípio', 'by agent', 'voz passiva ingles enem'],
  summary: 'Destaque a ação ou o resultado, e não quem fez: be + particípio nos principais tempos verbais.',
  intro: 'The Mona Lisa was painted by Leonardo da Vinci. Quando o foco é o resultado, usamos a voz passiva.',
  objective: 'Transformar frases da voz ativa para a passiva nos principais tempos, decidir quando usar o agente (by…) e reconhecer a passiva em notícias e textos científicos.',
  prerequisites: ['ing-b1-present-perfect', 'ing-a2-simple-past'], next: ['ing-b2-reported-speech'],
  skills: { g_form: 'Be + particípio', g_tenses: 'A passiva em vários tempos', g_by: 'Quando usar “by”', r_use: 'A passiva em notícias e ciência' },
  blocks: [
    block('g_form', 'be + past participle',
      'Na voz ativa, o sujeito faz a ação (People speak English here). Na passiva, o foco vai para quem RECEBE a ação: o objeto vira sujeito + be (no tempo certo) + particípio (English is spoken here). O verbo be carrega o tempo; o particípio não muda.',
      'Active: Someone stole my bike. → Passive: My bike was stolen.',
      'Passiva = “foi feito”, “é feito”: The cake was made (o bolo foi feito).',
      'Aviso numa loja: “Credit cards are accepted.”',
      '1. Pegue o objeto da ativa e coloque como sujeito. 2. Use be no mesmo tempo do verbo original. 3. Coloque o particípio.',
      'Em português também temos: “O bolo foi feito pela minha avó” (passiva) × “Minha avó fez o bolo” (ativa).'),
    block('g_tenses', 'Passive in different tenses',
      'Simple present: is/are made · Simple past: was/were made · Present continuous: is/are being made · Present perfect: has/have been made · Future: will be made · Modais: can/must/should be made. Negativa e pergunta seguem o verbo be: wasn\'t made, Has it been sent?',
      'The results will be announced tomorrow. · The road is being repaired. · Three new species have been discovered.',
      'O be muda de tempo: is, was, has been, will be… o particípio fica igual.',
      'E-mail de escola: “Your application has been received and will be reviewed this week.”',
      '1. Descubra o tempo da ativa. 2. Coloque be nesse tempo. 3. Particípio.',
      'Present continuous na passiva precisa de “being”: The house is being painted (está sendo pintada).'),
    block('g_by', 'When do we use “by”?',
      'Usamos by + agente só quando quem fez é importante ou novidade: Hamlet was written by Shakespeare. Omitimos o agente quando ele é óbvio, desconhecido ou irrelevante: My phone was stolen (não sei por quem). Rice is grown in many countries (por agricultores — óbvio).',
      'The telephone was invented by Graham Bell. · The window was broken last night.',
      'By = por (quem fez). Só coloque se for importante.',
      'Manchete: “Thief arrested” (preso — pela polícia, é óbvio).',
      '1. Quem fez importa? 2. Se sim, by + agente. 3. Se é óbvio ou desconhecido, omita.',
      'Em português falamos “foi preso” sem dizer “pela polícia” pelo mesmo motivo: é óbvio.'),
    block('r_use', 'Passive in news and science',
      'A voz passiva é muito comum em notícias (manchetes costumam cortar o be: “Bridge closed after storm”) e em textos científicos e acadêmicos, que valorizam o processo e o resultado: The samples were analyzed… It is believed that… Reconhecer a passiva ajuda a entender quem fez o quê numa prova de interpretação.',
      'The data were collected in 2023. · It is estimated that 1 billion people…',
      'Notícias e ciência usam muito a passiva porque o foco é o fato.',
      'Questão de prova: “According to the text, the vaccine was developed by…” — procure o agente depois de by.',
      '1. Encontre be + particípio. 2. Pergunte: quem fez? (procure by). 3. Se não houver agente, o texto não diz quem fez.',
      '“It is said that…” (diz-se que) e “He is believed to be…” (acredita-se que ele seja) são passivas impessoais típicas de textos formais.'),
  ],
  questions: [
    mc(1, 'g_form', 'English ___ in many countries.', ['speaks', 'is spoken', 'is speaking', 'spoken'], 1, ['Quem fala não é o inglês.', 'Voz passiva.', 'Is + particípio.'], 'English is spoken…'),
    mc(1, 'g_tenses', 'The Mona Lisa ___ by Leonardo da Vinci.', ['painted', 'is painting', 'was painted', 'has painted'], 2, ['Fato do passado.', 'Passiva no passado.', 'Was + particípio.'], 'Was painted.'),
    fill(1, 'g_form', 'Complete: My bike was ___ last night. (steal)', ['stolen'], ['Particípio de steal.', 'steal-stole-…', 'Stolen.'], 'Was stolen.'),
    tf(1, 'g_by', 'Na passiva, o agente (by…) sempre precisa aparecer.', false, ['Pense em “my phone was stolen”.', 'Às vezes não sabemos quem fez.', 'Só quando é importante.'], 'Falso: omitimos quando é óbvio, desconhecido ou irrelevante.'),
    match(2, 'g_tenses', 'Ligue o tempo à forma passiva de “make”.', [['simple present', 'is made'], ['simple past', 'was made'], ['present perfect', 'has been made'], ['future (will)', 'will be made']], ['Presente: is.', 'Passado: was.', 'Perfect: has been · futuro: will be.'], 'is made · was made · has been made · will be made.'),
    mc(2, 'g_tenses', 'The road is closed because it ___.', ['is repairing', 'is being repaired', 'repairs', 'has repaired'], 1, ['Está acontecendo agora.', 'Passiva no present continuous.', 'Is being + particípio.'], 'Is being repaired.'),
    mc(2, 'g_tenses', 'Passe para a passiva: “They will announce the results tomorrow.”', ['The results will announce tomorrow.', 'The results will be announced tomorrow.', 'The results are announced tomorrow.', 'The results will been announced tomorrow.'], 1, ['Futuro com will.', 'Will be + particípio.', 'Announced.'], 'The results will be announced tomorrow.'),
    mc(2, 'r_use', 'Na manchete “Three suspects arrested in São Paulo”, o que foi omitido?', ['O verbo be (were)', 'O particípio', 'O sujeito', 'Nada'], 0, ['Manchetes cortam palavras.', 'Qual verbo falta antes de arrested?', 'Were.'], 'Manchetes cortam o be: Three suspects (were) arrested.'),
    order(3, 'g_tenses', 'Organize: “Novas espécies foram descobertas na Amazônia.”', ['New', 'species', 'have', 'been', 'discovered', 'in', 'the', 'Amazon'], ['Present perfect na passiva.', 'Have been + particípio.', 'Lugar no final.'], 'New species have been discovered in the Amazon.'),
    mc(3, 'r_use', '“It is believed that the city was founded in 1554.” O que a frase indica?', ['O autor tem certeza absoluta', 'É uma crença geral, apresentada de forma impessoal', 'O autor fundou a cidade', 'A cidade será fundada'], 1, ['“It is believed” = acredita-se.', 'Não diz quem acredita.', 'É impessoal.'], 'Passiva impessoal: acredita-se que…'),
  ],
  review: ['Passiva = be (no tempo certo) + particípio', 'is made · was made · is being made · has been made · will be made', 'By + agente só quando importa', 'Comum em notícias e textos científicos; manchetes cortam o be'],
  relatedQuestions: ['como formar a voz passiva em inglês', 'quando usar a voz passiva', 'passiva no present perfect'],
  equivalentQuestions: eqs(['voz passiva', 'passive voice'], ['como passar da ativa para a passiva em inglês', 'quando usar by na passiva', 'o que é is being made', 'passiva no futuro em inglês', 'o que significa it is believed that', 'por que manchetes não têm verbo to be', 'voz passiva no enem']),
  commonErrors: ['Esquecer o be (The cake made by my mom).', 'Usar o passado no lugar do particípio (was stole).', 'Colocar sempre o agente, mesmo óbvio.'],
  english: {
    cefr: 'B2', unit: 'b2-u1', order: 1, area: 'grammar', focus: ['grammar', 'reading'],
    vocabulary: [
      v('invent', 'inventar', 'verb', 'to create something new', 'The telephone was invented in the 19th century.', 2),
      v('discover', 'descobrir', 'verb', 'to find something for the first time', 'A new planet was discovered.', 2),
      v('arrest', 'prender (polícia)', 'verb', 'when the police take someone to the station', 'Two men were arrested.', 2),
      v('found', 'fundar', 'verb', 'to start a city or organization', 'The company was founded in 1998.', 3),
      v('announce', 'anunciar', 'verb', 'to tell people officially', 'The winner will be announced today.', 2),
      v('grow', 'cultivar / crescer', 'verb', 'to produce plants', 'Coffee is grown in Minas Gerais.', 2),
      v('survey', 'pesquisa (de opinião)', 'noun', 'a set of questions asked to many people', 'The survey was answered by 500 students.', 3),
      v('data', 'dados', 'noun', 'facts and numbers collected for analysis', 'The data were analyzed carefully.', 3),
    ],
    grammar: {
      name: 'Passive voice', when: 'Quando o foco é a ação ou o resultado, não quem fez.', structure: 'objeto → sujeito + be (tempo) + particípio (+ by agente)',
      affirmative: ['Coffee is grown here.', 'The bridge was built in 1990.', 'The results will be published.'], negative: ['The email wasn\'t sent.', 'It hasn\'t been decided yet.'], interrogative: ['Was it made in Brazil?', 'Has the package been delivered?'],
      compare: 'Active: The police arrested him (foco na polícia) × Passive: He was arrested (foco nele).', context: 'Ler notícias e artigos científicos.',
    },
    reading: {
      title: 'Ancient city found under the forest', genre: 'notícia adaptada',
      text: 'A group of ancient settlements has been identified in the Amazon rainforest. The structures were detected with laser technology from airplanes, which allowed researchers to "see" through the trees. It is estimated that the area was occupied for more than a thousand years. The findings were published in a scientific journal and will be studied by teams from several countries.',
      questions: [
        mci(2, 'Como as estruturas foram detectadas?', ['Por escavações', 'Com tecnologia a laser a partir de aviões', 'Por satélites comuns', 'Por moradores locais'], 1, '“detected with laser technology from airplanes”.'),
        mci(2, 'Por quanto tempo se estima que a área foi ocupada?', ['Menos de cem anos', 'Mais de mil anos', 'Dez mil anos exatos', 'O texto não diz'], 1, '“It is estimated that the area was occupied for more than a thousand years.”'),
        mci(3, 'O que vai acontecer com as descobertas?', ['Serão destruídas', 'Serão estudadas por equipes de vários países', 'Serão vendidas', 'Serão escondidas'], 1, '“will be studied by teams from several countries”.'),
        mci(3, 'Por que o texto usa tanto a voz passiva?', ['Porque é uma história de ficção', 'Porque o foco está nas descobertas, não em quem as fez', 'Porque é uma carta pessoal', 'Porque não há verbos'], 1, 'Textos científicos e notícias focam o fato e o processo.'),
      ],
    },
    writing: {
      prompt: 'Escreva uma pequena notícia (3 a 5 frases) sobre algo que aconteceu na sua escola ou cidade usando pelo menos 3 verbos na voz passiva.', criteria: ['Título no estilo manchete', '3 passivas em tempos diferentes', 'Agente só quando importante'],
      model: 'New library opened downtown. The library was built in two years and was opened yesterday. More than 5,000 books have been donated. Free courses will be offered next month.', keywords: ['was', 'been', 'will be', 'opened'], minWords: 30,
    },
    challenge: 'Encontre 3 exemplos de voz passiva numa notícia em inglês e diga quem fez a ação (se o texto disser).',
  },
  games: {
    blanks: [
      blank(1, 'This bread ___ every morning.', ['is baked', 'bakes', 'is baking', 'baked'], 0, 'Presente passivo: is baked.'),
      blank(2, 'The letter ___ yesterday.', ['was sent', 'is sent', 'has sent', 'sent'], 0, 'Passado passivo: was sent.'),
      blank(2, 'A new school ___ next year.', ['will be built', 'will build', 'is build', 'builds'], 0, 'Futuro passivo: will be built.'),
      blank(3, 'The house ___ at the moment.', ['is being painted', 'is painting', 'is painted being', 'has painting'], 0, 'Present continuous passivo.'),
      blank(3, 'Hamlet was written ___ Shakespeare.', ['by', 'for', 'from', 'of'], 0, 'Agente: by.'),
    ],
    sequences: [words(2, 'The window was broken last night', 'Passiva no passado sem agente.'), words(3, 'The results will be announced tomorrow', 'Passiva no futuro.')],
  },
  sources: enSources(),
})

// ═══════════════════ B2 · Unidade 2 · She said that… ═══════════════════
export const reportedSpeech = lesson({
  id: 'ing-b2-reported-speech', subject: 'ingles', title: 'Reported speech', levels: [...LV], grade: 'Ensino Médio',
  topic: 'Inglês B2 — Como a informação é contada', subtopic: 'Discurso indireto: falas, perguntas e pedidos',
  aliases: ['reported speech', 'discurso indireto em ingles', 'indirect speech', 'she said that', 'told me', 'reported questions', 'reported commands', 'say ou tell'],
  summary: 'Conte o que outra pessoa disse, perguntou ou pediu, com as mudanças de tempo, pronomes e expressões.',
  intro: '“I\'m tired,” she said. → She said she was tired. Vamos relatar falas como jornalistas.',
  objective: 'Transformar falas, perguntas e pedidos para o discurso indireto, fazendo o recuo dos tempos, as mudanças de pronomes e de expressões de tempo e usando say × tell corretamente.',
  prerequisites: ['ing-b1-present-perfect'], next: ['ing-b2-relative-clauses'],
  skills: { g_back: 'Recuo dos tempos (backshift)', g_saytell: 'Say × tell e mudanças de pronomes e tempo', g_questions: 'Perguntas relatadas', g_commands: 'Pedidos e ordens relatados' },
  blocks: [
    block('g_back', 'Backshift',
      'Quando relatamos com um verbo no passado (said, told), os tempos da fala original geralmente “recuam” um passo: present → past (“I\'m tired” → she said she was tired); present continuous → past continuous; present perfect/past → past perfect (“I saw it” → he said he had seen it); will → would; can → could. Se a fala ainda é verdade, o recuo é opcional: He said the Earth is round.',
      '“I love this song,” Ana said. → Ana said (that) she loved that song.',
      'Contando o que alguém disse, o verbo vai um passo para trás no tempo.',
      'Fofoca do intervalo: “Leo said he was going to the party.”',
      '1. Veja o tempo da fala original. 2. Recue um passo (am → was, will → would). 3. That é opcional.',
      'Em português também fazemos: “Estou cansada” → Ela disse que estava cansada. O inglês segue a mesma lógica.'),
    block('g_saytell', 'Say or tell? Pronouns and time words',
      'Say + (that) + fala: She said (that)… Tell + pessoa + (that): She told me (that)… (tell precisa de quem ouviu). Pronomes e referências mudam conforme quem conta: “I\'ll call you” → She said she would call me. Tempo e lugar: now → then, today → that day, tomorrow → the next day, yesterday → the day before, here → there, this → that.',
      '“I\'ll finish it tomorrow,” he said. → He told me he would finish it the next day.',
      'Tell sempre com a pessoa: told me, told her. Say sem a pessoa: said that.',
      'Relato: “My mom told me to be home by ten.”',
      '1. Escolha say (sem pessoa) ou tell (com pessoa). 2. Ajuste os pronomes. 3. Ajuste as palavras de tempo e lugar.',
      '“He said me” está errado. Diga “He told me” ou “He said to me” (menos comum).'),
    block('g_questions', 'Reported questions',
      'Perguntas relatadas viram frases afirmativas (sem do/did e sem inverter): “Where do you live?” → She asked me where I lived. Perguntas de sim/não usam if ou whether: “Are you coming?” → He asked if I was coming.',
      '“What time is it?” → He asked what time it was. · “Did you like it?” → She asked whether I had liked it.',
      'Pergunta relatada tem a ordem de frase normal: asked where I lived.',
      'Entrevista de emprego: “They asked me why I wanted the job.”',
      '1. Asked (+ pessoa). 2. Palavra de pergunta ou if/whether. 3. Sujeito + verbo (recuado), sem ponto de interrogação.',
      'Erro clássico: “She asked where did I live.” O certo é “She asked where I lived” — sem did.'),
    block('g_commands', 'Reported commands and requests',
      'Ordens e pedidos: tell/ask + pessoa + to + verbo: “Sit down!” → The teacher told us to sit down. “Could you help me?” → She asked me to help her. Negativo: not to: “Don\'t be late!” → He told me not to be late.',
      '“Please turn off your phones.” → They asked us to turn off our phones.',
      'Pedido relatado = asked me to + verbo. Ordem = told me to + verbo.',
      'Recado: “Your dad asked you to call him back.”',
      '1. Ordem → told; pedido → asked. 2. Pessoa. 3. To + verbo (ou not to + verbo).',
      'Não use that nas ordens: “He told me to wait” (e não “He told me that wait”).'),
  ],
  questions: [
    mc(1, 'g_back', '“I am hungry,” Tom said. → Tom said he ___ hungry.', ['is', 'was', 'has been', 'will be'], 1, ['Recuo do presente.', 'Am → …', 'Was.'], 'Am → was.'),
    mc(1, 'g_saytell', 'She ___ me that she was busy.', ['said', 'told', 'asked', 'spoke'], 1, ['Há uma pessoa depois (me).', 'Tell + pessoa.', 'Told.'], 'Told me.'),
    fill(1, 'g_back', '“I will help you.” → He said he ___ help me.', ['would'], ['Will recua para…', 'Condicional.', 'W-o-u-l-d.'], 'Will → would.'),
    tf(1, 'g_questions', '“She asked me where did I live” está correto.', false, ['Pergunta relatada tem ordem de frase.', 'Sem did.', 'Where I lived.'], 'Falso: She asked me where I lived.'),
    match(2, 'g_saytell', 'Ligue a expressão da fala original à forma relatada.', [['today', 'that day'], ['tomorrow', 'the next day'], ['yesterday', 'the day before'], ['here', 'there']], ['Hoje → aquele dia.', 'Amanhã → o dia seguinte.', 'Ontem → o dia anterior.'], 'today→that day · tomorrow→the next day · yesterday→the day before · here→there.'),
    mc(2, 'g_questions', '“Are you coming to the party?” → She asked ___ I was coming to the party.', ['that', 'if', 'what', 'did'], 1, ['Pergunta de sim/não.', 'Usa if ou whether.', 'If.'], 'She asked if I was coming.'),
    mc(2, 'g_commands', '“Don\'t touch the painting!” → The guide told us ___ the painting.', ['don\'t touch', 'not to touch', 'to not touching', 'that not touch'], 1, ['Ordem negativa.', 'Not to + verbo.', 'Not to touch.'], 'Told us not to touch.'),
    mc(2, 'g_back', '“I have finished the project,” Mia said. → Mia said she ___ the project.', ['has finished', 'had finished', 'finished have', 'was finish'], 1, ['Present perfect recua para…', 'Past perfect.', 'Had + particípio.'], 'Had finished.'),
    order(3, 'g_questions', 'Organize: “Ele me perguntou por que eu estava triste.”', ['He', 'asked', 'me', 'why', 'I', 'was', 'sad'], ['Asked + pessoa.', 'Why + sujeito + verbo.', 'Sem inversão.'], 'He asked me why I was sad.'),
    mc(3, 'g_saytell', '“I\'ll call you tomorrow,” Leo told Ana on Monday. Na quarta, Ana conta:', ['Leo said he will call you tomorrow.', 'Leo told me he would call me the next day.', 'Leo told me I would call him tomorrow.', 'Leo said me he would call.'], 1, ['Tell + me.', 'I → he; you → me.', 'Will → would; tomorrow → the next day.'], 'Leo told me he would call me the next day.'),
  ],
  review: ['Recuo: am→was · will→would · can→could · saw/have seen→had seen', 'Say (that)… · tell + pessoa (that)…', 'Perguntas: asked where I lived · asked if/whether…', 'Ordens e pedidos: told/asked me (not) to + verbo'],
  relatedQuestions: ['como usar reported speech', 'diferença entre say e tell', 'como relatar uma pergunta em inglês'],
  equivalentQuestions: eqs(['reported speech', 'discurso indireto'], ['como transformar discurso direto em indireto em inglês', 'quando usar said e told', 'o que muda no reported speech', 'como relatar ordens em inglês', 'asked if ou asked that', 'will vira would no discurso indireto', 'tomorrow vira o que no reported speech']),
  commonErrors: ['“He said me…” (o certo é told me).', 'Manter a ordem de pergunta (asked where did I live).', 'Esquecer de ajustar pronomes e expressões de tempo.'],
  english: {
    cefr: 'B2', unit: 'b2-u2', order: 1, area: 'grammar', focus: ['grammar', 'listening', 'writing'],
    vocabulary: [
      v('say', 'dizer', 'verb', 'to speak words (without the listener as object)', 'She said that she was tired.', 1),
      v('tell', 'contar / dizer (a alguém)', 'verb', 'to say something to someone', 'He told me the truth.', 1),
      v('ask', 'perguntar / pedir', 'verb', 'to put a question; to request', 'She asked me to wait.', 1),
      v('whether', 'se (em perguntas indiretas)', 'conjunction', 'used like “if” in reported questions', 'He asked whether I was ready.', 3),
      v('explain', 'explicar', 'verb', 'to make something clear', 'The teacher explained that the test was easy.', 2),
      v('complain', 'reclamar', 'verb', 'to say you are not happy with something', 'They complained that the room was cold.', 3),
      v('warn', 'avisar (de perigo)', 'verb', 'to tell someone about a danger', 'She warned us not to swim there.', 3),
      v('promise', 'prometer', 'verb', 'to say you will certainly do something', 'He promised he would come.', 2),
    ],
    listening: {
      title: 'Voice note from a friend', kind: 'texto', rate: 0.95,
      script: ['Hi Sam! I talked to Ms. Rivera today.', 'She said the test was moved to Friday.', 'She told us to review chapters four and five.', 'She also asked if anyone needed extra help,', 'and she promised she would post the answers online.'],
      questions: [
        mci(2, 'O que aconteceu com a prova?', ['Foi cancelada', 'Foi transferida para sexta', 'Será hoje', 'Ficou mais difícil'], 1, '“the test was moved to Friday”.'),
        mci(2, 'O que a professora mandou os alunos fazerem?', ['Revisar os capítulos 4 e 5', 'Ler o livro todo', 'Fazer um trabalho', 'Faltar à aula'], 0, '“told us to review chapters four and five”.'),
        mci(3, 'O que a professora prometeu?', ['Dar aula extra', 'Publicar as respostas online', 'Adiar de novo', 'Corrigir rápido'], 1, '“promised she would post the answers online”.'),
      ],
    },
    writing: {
      prompt: 'Relate uma conversa curta que você teve hoje (ou invente uma) usando say, tell e ask no discurso indireto.', criteria: ['Uma fala com said/told', 'Uma pergunta relatada', 'Um pedido ou ordem com to + verbo'],
      model: 'My friend told me she was nervous about the test. I asked her if she had studied. She said she had studied a lot. Then she asked me to help her with math.', keywords: ['told', 'said', 'asked', 'if'], minWords: 30,
    },
    challenge: 'Assista a 1 minuto de uma entrevista em inglês e relate duas coisas que a pessoa disse (He said that…).',
  },
  games: {
    blanks: [
      blank(1, '“I\'m happy.” → She said she ___ happy.', ['was', 'is', 'were', 'be'], 0, 'Am → was.'),
      blank(2, 'He ___ me to close the door.', ['asked', 'said', 'spoke', 'talked'], 0, 'Pedido: asked me to.'),
      blank(2, '“Can you swim?” → She asked me if I ___ swim.', ['could', 'can', 'will', 'do'], 0, 'Can → could.'),
      blank(3, '“Where is the station?” → He asked where the station ___.', ['was', 'is it', 'did be', 'were it'], 0, 'Ordem de frase + recuo.'),
      blank(3, 'The doctor told me ___ so much sugar.', ['not to eat', 'don\'t eat', 'to not eating', 'not eat'], 0, 'Ordem negativa: not to + verbo.'),
    ],
    sequences: [words(2, 'She told me she was tired', 'Tell + pessoa + fala recuada.'), words(3, 'He asked me where I lived', 'Pergunta relatada: ordem de frase.')],
    dialogues: [
      dialogue(3, 'Recado', ['Mom: Did your coach call?', 'Rui: Yes. He told me the game was on Sunday.', 'Mom: What else did he say?', 'Rui: He asked me to arrive early.'], 3, ['He asked me to arrive early.', 'He asked me arrive early.', 'He said me to arrive early.', 'He asked that I to arrive.'], 0, 'Pedido relatado: asked me to + verbo.'),
    ],
  },
  sources: enSources(),
})

// ═══════════════════ B2 · Unidade 3 · Piece of cake ═══════════════════
export const idioms = lesson({
  id: 'ing-b2-idioms', subject: 'ingles', title: 'Idioms', levels: [...LV], grade: 'Ensino Médio',
  topic: 'Inglês B2 — Nuances', subtopic: 'Expressões idiomáticas do dia a dia',
  aliases: ['idioms', 'expressoes idiomaticas em ingles', 'piece of cake', 'break the ice', 'under the weather', 'once in a blue moon', 'cost an arm and a leg', 'hit the nail on the head', 'girias em ingles'],
  summary: 'Entenda e use expressões idiomáticas comuns, sabendo o contexto certo — e quando evitá-las.',
  intro: 'This test was a piece of cake! Idioms dizem uma coisa com outras palavras.',
  objective: 'Reconhecer o sentido de idioms comuns pelo contexto, relacioná-los a equivalentes aproximados em português e decidir quando usá-los ou evitá-los.',
  prerequisites: ['ing-b1-phrasal-verbs', 'ing-b1-collocations'], next: ['ing-b2-modal-perfect'],
  skills: { v_what: 'O que é um idiom', v_daily: 'Idioms de situações do dia a dia', v_money: 'Idioms de dinheiro, tempo e acerto', v_when: 'Quando usar e quando evitar' },
  blocks: [
    block('v_what', 'What is an idiom?',
      'Idiom é uma expressão cujo sentido NÃO é a soma das palavras. “It\'s a piece of cake” não fala de bolo: significa que algo é muito fácil. Por isso, idioms são entendidos pelo contexto e, muitas vezes, têm um equivalente aproximado em português (não uma tradução literal).',
      'The exam was a piece of cake. = A prova foi moleza.',
      'Idiom = frase com sentido figurado. Não traduza palavra por palavra.',
      'Na série, alguém diz “Break a leg!” antes de uma peça — é “boa sorte!”, não “quebre a perna”.',
      '1. Perceba que o sentido literal não faz sentido. 2. Olhe a situação. 3. Procure o equivalente em português.',
      'O português também tem: “chutar o balde”, “pagar o pato”. Um estrangeiro também não entenderia literalmente.'),
    block('v_daily', 'Everyday idioms',
      'break the ice = quebrar o gelo (começar uma conversa num clima tenso ou novo) · under the weather = meio doente, indisposto · piece of cake = moleza, muito fácil · once in a blue moon = muito raramente (“uma vez na vida, outra na morte”) · on cloud nine = nas nuvens (muito feliz) · let the cat out of the bag = deixar escapar um segredo.',
      'I\'m a bit under the weather today. · We only eat out once in a blue moon.',
      'Under the weather = meio doente. Once in a blue moon = quase nunca.',
      'Primeiro dia no curso: o professor faz um jogo para break the ice.',
      '1. Aprenda o idiom com uma situação. 2. Diga o equivalente em português. 3. Use numa frase sua.',
      'Break the ice existe quase igual em português (“quebrar o gelo”), mas under the weather não: seria “estar meio indisposto”.'),
    block('v_money', 'Money, time and getting it right',
      'cost an arm and a leg = custar os olhos da cara · hit the nail on the head = acertar em cheio, dizer exatamente o ponto certo · beat around the bush = enrolar, fazer rodeios · call it a day = encerrar por hoje · in the same boat = no mesmo barco (na mesma situação) · the ball is in your court = agora é com você (a decisão é sua).',
      'That phone costs an arm and a leg! · You hit the nail on the head. · Let\'s call it a day.',
      'Cost an arm and a leg = muito caro. Hit the nail on the head = acertou em cheio.',
      'Reunião de grupo: “Stop beating around the bush and tell us your idea!”',
      '1. Relacione cada idiom a uma imagem mental. 2. Associe ao equivalente em português. 3. Treine com o jogo da memória.',
      'Cost an arm and a leg (inglês) × custar os olhos da cara (português): as duas línguas usam partes do corpo para falar de algo muito caro.'),
    block('v_when', 'When to use — and when not to',
      'Idioms deixam a fala natural e expressiva em conversas informais, mensagens, redes sociais e textos criativos. Em textos acadêmicos, formais ou provas de redação, prefira linguagem direta: em vez de “The plan cost an arm and a leg”, escreva “The plan was extremely expensive”. Cuidado também com idioms datados ou muito regionais.',
      'Informal: “That exam was a piece of cake!” · Formal: “The exam was not demanding.”',
      'Conversa com amigos: pode usar. Texto formal: melhor evitar.',
      'E-mail para um professor: “The task was quite easy” (e não “a piece of cake”).',
      '1. Veja com quem você fala e o tipo de texto. 2. Informal → idiom pode ajudar. 3. Formal → linguagem direta.',
      'É como no português: “foi moleza” é ótimo com colegas, mas não numa carta formal.'),
  ],
  questions: [
    mc(1, 'v_what', '“The test was a piece of cake” significa que a prova foi:', ['difícil', 'muito fácil', 'longa', 'deliciosa'], 1, ['Não é sobre comida.', 'Sentido figurado.', 'Moleza.'], 'Piece of cake = muito fácil.'),
    mc(1, 'v_daily', 'I\'m feeling ___ today, so I\'ll stay home.', ['on cloud nine', 'under the weather', 'a piece of cake', 'in the same boat'], 1, ['A pessoa vai ficar em casa.', 'Está meio doente.', 'Under the weather.'], 'Under the weather = indisposto.'),
    fill(1, 'v_daily', 'Complete: Let\'s play a game to break the ___.', ['ice'], ['Quebrar o…', 'Algo frio.', 'Ice.'], 'Break the ice.'),
    tf(1, 'v_money', '“It costs an arm and a leg” quer dizer que algo é muito caro.', true, ['Pense em “os olhos da cara”.', 'Partes do corpo.', 'Muito caro.'], 'Verdadeiro.'),
    match(2, 'v_money', 'Ligue o idiom ao equivalente aproximado em português.', [['hit the nail on the head', 'acertar em cheio'], ['beat around the bush', 'enrolar, fazer rodeios'], ['call it a day', 'encerrar por hoje'], ['in the same boat', 'na mesma situação']], ['Nail = prego: acertar o prego.', 'Bush = arbusto: dar voltas.', 'Call it a day = dar o dia por encerrado.'], 'acertar em cheio · enrolar · encerrar por hoje · na mesma situação.'),
    mc(2, 'v_daily', 'We go to the theater ___ — maybe once every two years.', ['on cloud nine', 'once in a blue moon', 'under the weather', 'a piece of cake'], 1, ['Muito raramente.', 'A cada dois anos.', 'Once in a blue moon.'], 'Once in a blue moon = muito raramente.'),
    mc(2, 'v_when', 'Em qual texto é melhor EVITAR “It cost an arm and a leg”?', ['Mensagem para um amigo', 'Post informal', 'Artigo acadêmico', 'Conversa no intervalo'], 2, ['Idioms são informais.', 'Texto formal pede linguagem direta.', 'Artigo acadêmico.'], 'Em textos acadêmicos, prefira “extremely expensive”.'),
    mc(2, 'v_money', 'Ana explicou o problema exatamente como ele era. Você diz: “You ___!”', ['hit the nail on the head', 'beat around the bush', 'let the cat out of the bag', 'broke the ice'], 0, ['Ela acertou o ponto.', 'Acertar em cheio.', 'Hit the nail on the head.'], 'Hit the nail on the head = acertou em cheio.'),
    order(3, 'v_money', 'Organize: “Agora é com você.”', ['The', 'ball', 'is', 'in', 'your', 'court'], ['A bola…', '…está na sua quadra.', 'Court no final.'], 'The ball is in your court.'),
    mc(3, 'v_daily', '“Tom let the cat out of the bag about the surprise party.” O que aconteceu?', ['Tom soltou um gato na festa', 'Tom deixou escapar o segredo da festa surpresa', 'Tom organizou a festa', 'Tom perdeu o gato'], 1, ['Sentido figurado.', 'Relacionado a um segredo.', 'Revelou sem querer.'], 'Let the cat out of the bag = deixar escapar um segredo.'),
  ],
  review: ['Idiom = sentido figurado; entenda pelo contexto', 'piece of cake · under the weather · break the ice · once in a blue moon', 'cost an arm and a leg · hit the nail on the head · beat around the bush · call it a day', 'Informal: sim · textos acadêmicos e formais: evite'],
  relatedQuestions: ['expressões idiomáticas em inglês', 'o que significa piece of cake', 'o que significa under the weather'],
  equivalentQuestions: eqs(['idioms', 'expressões idiomáticas'], ['o que significa break the ice', 'o que significa once in a blue moon', 'o que significa cost an arm and a leg', 'o que significa hit the nail on the head', 'o que significa beat around the bush', 'posso usar idioms na redação', 'o que significa break a leg']),
  commonErrors: ['Traduzir idioms palavra por palavra.', 'Usar idioms em textos acadêmicos.', 'Misturar partes de idioms diferentes.'],
  english: {
    cefr: 'B2', unit: 'b2-u3', order: 1, area: 'vocabulary', focus: ['vocabulary', 'reading', 'speaking'],
    vocabulary: [
      v('piece of cake', 'moleza', 'idiom', 'something very easy', 'The quiz was a piece of cake.', 1),
      v('break the ice', 'quebrar o gelo', 'idiom', 'to make people feel relaxed in a new situation', 'He told a joke to break the ice.', 1),
      v('under the weather', 'indisposto, meio doente', 'idiom', 'feeling a little sick', 'I\'m a bit under the weather.', 2),
      v('once in a blue moon', 'muito raramente', 'idiom', 'very rarely', 'I eat fast food once in a blue moon.', 2),
      v('cost an arm and a leg', 'custar os olhos da cara', 'idiom', 'to be very expensive', 'Concert tickets cost an arm and a leg.', 2),
      v('hit the nail on the head', 'acertar em cheio', 'idiom', 'to describe exactly the right thing', 'You hit the nail on the head.', 3),
      v('beat around the bush', 'enrolar, fazer rodeios', 'idiom', 'to avoid saying something directly', 'Don\'t beat around the bush.', 3),
      v('call it a day', 'encerrar por hoje', 'idiom', 'to stop working for the day', 'It\'s late, let\'s call it a day.', 2),
      v('on cloud nine', 'nas nuvens (muito feliz)', 'idiom', 'extremely happy', 'She was on cloud nine after the news.', 2),
      v('let the cat out of the bag', 'deixar escapar um segredo', 'idiom', 'to reveal a secret by mistake', 'Who let the cat out of the bag?', 3),
      v('in the same boat', 'na mesma situação', 'idiom', 'in the same difficult situation', 'Don\'t worry, we\'re all in the same boat.', 2),
    ],
    reading: {
      title: 'A group project', genre: 'mensagens entre colegas',
      text: 'Kai: Honestly, guys, the research part was a piece of cake. The hard part is the presentation.\nLua: I know. And the poster printing costs an arm and a leg!\nKai: Let\'s not beat around the bush: who is going to present?\nLua: I can start and break the ice with a quick question to the class.\nKai: You hit the nail on the head — that\'s a great way to start. OK, let\'s call it a day and meet tomorrow.',
      questions: [
        mci(2, 'Segundo Kai, qual parte foi fácil?', ['A apresentação', 'A pesquisa', 'A impressão do pôster', 'Nenhuma'], 1, '“the research part was a piece of cake”.'),
        mci(2, 'O que Lua diz sobre imprimir o pôster?', ['É muito caro', 'É muito fácil', 'É rápido', 'É proibido'], 0, '“costs an arm and a leg” = muito caro.'),
        mci(3, 'O que Kai quer dizer com “Let\'s not beat around the bush”?', ['Vamos sair para passear', 'Vamos direto ao ponto', 'Vamos desistir', 'Vamos adiar'], 1, 'Beat around the bush = enrolar; ele pede para ir direto ao ponto.'),
        mci(3, 'Como Lua pretende começar a apresentação?', ['Com uma piada', 'Com uma pergunta para a turma', 'Com um vídeo', 'Lendo o pôster'], 1, '“break the ice with a quick question to the class”.'),
      ],
    },
    speaking: {
      situation: 'Você conta a um amigo como foi a sua semana usando idioms.', vocabulary: ['piece of cake', 'under the weather', 'call it a day'],
      phrases: ['It was a piece of cake.', 'I was a bit under the weather.', 'After that, I called it a day.'], example: 'On Monday I was under the weather, but the math test was a piece of cake!',
      challenge: 'Use 3 idioms desta aula numa história curta sobre a sua semana.', expected: ['piece', 'cake', 'weather', 'day'],
    },
    challenge: 'Encontre um idiom novo numa série ou música e descubra o sentido pelo contexto antes de pesquisar.',
    tips: ['Aprenda idioms com uma situação real, não em listas.', 'Na dúvida sobre o nível de formalidade, prefira a linguagem direta.'],
  },
  games: {
    blanks: [
      blank(1, 'Don\'t worry about the quiz, it\'s a ___ of cake.', ['piece', 'slice', 'part', 'bit'], 0, 'Piece of cake.'),
      blank(2, 'These sneakers cost an arm and a ___!', ['leg', 'foot', 'hand', 'head'], 0, 'Cost an arm and a leg.'),
      blank(2, 'I only see my cousins once in a blue ___.', ['moon', 'sky', 'sun', 'day'], 0, 'Once in a blue moon.'),
      blank(3, 'Stop beating around the ___ and tell me the truth.', ['bush', 'tree', 'house', 'garden'], 0, 'Beat around the bush.'),
      blank(3, 'We\'re all in the same ___, so let\'s help each other.', ['boat', 'ship', 'car', 'bus'], 0, 'In the same boat.'),
    ],
    sequences: [words(2, 'Let\'s call it a day', 'Encerrar por hoje.'), words(3, 'You hit the nail on the head', 'Acertar em cheio.')],
  },
  sources: enSources(),
})

// ═══════════════════ C1 · Unidade 1 · Had I known… ═══════════════════
export const advancedConditionals = lesson({
  id: 'ing-c1-conditionals', subject: 'ingles', title: 'Third and mixed conditionals', levels: [...LV], grade: 'Ensino Médio e preparatório',
  topic: 'Inglês C1 — Hipóteses e ênfase', subtopic: 'Third conditional, mixed conditionals e inversão',
  aliases: ['third conditional', 'mixed conditional', 'condicional mista', 'had known', 'would have', 'if i had', 'had i known', 'inversao condicional', 'wish past perfect'],
  summary: 'Imagine passados diferentes e suas consequências, misture tempos nas condicionais e use a inversão formal.',
  intro: 'If I had studied more, I would have passed… Vamos falar do que poderia ter sido.',
  objective: 'Usar o third conditional para passados imaginários, os mixed conditionals para ligar passado e presente, a inversão formal (Had I known…) e expressar arrependimento com wish/if only.',
  prerequisites: ['ing-b1-conditionals', 'ing-b1-present-perfect'], next: ['ing-c1-inversion-cleft'],
  skills: { g_third: 'Third conditional', g_mixed: 'Mixed conditionals', g_inv: 'Inversão formal (Had I…, Were I…, Should you…)', g_wish: 'Wish / if only (arrependimento)' },
  blocks: [
    block('g_third', 'Third conditional',
      'Fala de um passado que NÃO aconteceu e sua consequência imaginária no passado: If + past perfect, would have + particípio. If I had left earlier, I wouldn\'t have missed the bus (mas saí tarde e perdi). Também com could have / might have para possibilidade.',
      'If she had known the answer, she would have said it. · We might have won if we had trained harder.',
      'Se eu tivesse feito, eu teria feito. Tudo no passado imaginário.',
      'Depois do jogo: “If the referee had seen the foul, he would have given a penalty.”',
      '1. If + had + particípio. 2. Vírgula. 3. Would have + particípio.',
      'Em português: “Se eu tivesse estudado, teria passado.” A estrutura é parecida: had studied = tivesse estudado; would have passed = teria passado.'),
    block('g_mixed', 'Mixed conditionals',
      'Misturam tempos. Passado imaginário → resultado no presente: If + past perfect, would + verbo: If I had taken that job, I would be in London now. Presente imaginário → resultado no passado: If + past simple, would have + particípio: If I were more organized, I wouldn\'t have lost the file.',
      'If you had slept better, you wouldn\'t be so tired now. · If he spoke English, he would have understood the tour.',
      'Uma parte fala do passado, a outra do presente (ou vice-versa).',
      'Reflexão: “If I had learned to swim as a child, I would be more confident at the beach today.”',
      '1. Identifique o tempo de cada parte (quando é a condição? quando é o resultado?). 2. Passado imaginário = had + particípio; presente imaginário = past simple. 3. Resultado agora = would + verbo; resultado no passado = would have + particípio.',
      'A palavra “now” ou “today” no resultado costuma indicar mixed conditional: …I would be rich NOW.'),
    block('g_inv', 'Formal inversion',
      'Em registro formal, podemos tirar o if e inverter: If I had known → Had I known; If I were → Were I; If you should need → Should you need. É comum em e-mails formais, contratos, discursos e textos acadêmicos.',
      'Had we received the documents, we would have replied. · Should you have any questions, please contact us.',
      'Had I known = Se eu soubesse (antes). Should you need = Caso você precise.',
      'E-mail profissional: “Should you require further information, do not hesitate to contact me.”',
      '1. Tire o if. 2. Coloque had/were/should antes do sujeito. 3. O resto da frase não muda.',
      'A inversão não muda o sentido, só o registro: “If you need help” (neutro) × “Should you need help” (formal).'),
    block('g_wish', 'Wish and if only',
      'Para arrependimentos sobre o passado: wish/if only + past perfect: I wish I had studied more (queria ter estudado mais). Para desejos sobre o presente: wish + past simple: I wish I had more time. Para irritação com algo que alguém faz: wish + would: I wish you would stop interrupting.',
      'If only I hadn\'t said that! · She wishes she lived by the sea.',
      'I wish I had… = Eu queria ter… (passado). I wish I had… (presente) = Eu queria ter agora.',
      'Depois de uma prova: “I wish I had read the question more carefully.”',
      '1. Arrependimento do passado → had + particípio. 2. Desejo no presente → passado simples. 3. If only é mais enfático.',
      'Wish não é “desejar” no sentido de “I want”: “I want a car” (quero) × “I wish I had a car” (queria ter, mas não tenho).'),
  ],
  questions: [
    mc(1, 'g_third', 'If I had studied more, I ___ the exam.', ['would pass', 'would have passed', 'will pass', 'passed'], 1, ['Passado imaginário.', 'Third conditional.', 'Would have + particípio.'], 'Would have passed.'),
    mc(1, 'g_third', 'If she ___ earlier, she wouldn\'t have missed the train.', ['left', 'had left', 'would leave', 'has left'], 1, ['Condição no passado imaginário.', 'Past perfect.', 'Had left.'], 'If she had left earlier…'),
    fill(1, 'g_inv', 'Inversão formal de “If I had known”: ___ I known, I would have helped.', ['Had'], ['Tire o if.', 'Coloque o auxiliar antes do sujeito.', 'H-a-d.'], 'Had I known…'),
    tf(1, 'g_wish', '“I wish I had studied more” expressa arrependimento sobre o passado.', true, ['Had + particípio.', 'Refere-se ao passado.', 'Arrependimento.'], 'Verdadeiro.'),
    match(2, 'g_mixed', 'Ligue cada frase ao tipo.', [['If I had taken the job, I would be in London now.', 'passado → presente'], ['If I were more careful, I wouldn\'t have broken it.', 'presente → passado'], ['If I had trained, I would have won.', 'third conditional']], ['“now” no resultado.', 'Condição permanente no presente.', 'Tudo no passado.'], 'passado→presente · presente→passado · third.'),
    mc(2, 'g_mixed', 'If I had saved money last year, I ___ a car now.', ['would have', 'would have had', 'will have', 'had'], 0, ['Resultado AGORA.', 'Mixed conditional.', 'Would + verbo.'], 'Would have (a car) now.'),
    mc(2, 'g_inv', 'Qual é a forma formal de “If you need assistance, call us”?', ['Should you need assistance, call us.', 'Need you assistance, call us.', 'Had you need assistance, call us.', 'Were you need assistance, call us.'], 0, ['Condição possível no futuro.', 'Inversão com should.', 'Should you need…'], 'Should you need assistance…'),
    mc(2, 'g_wish', 'You are late again. I wish you ___ on time for once.', ['would arrive', 'arrived yesterday', 'had arrive', 'will arrive'], 0, ['Irritação com o comportamento de alguém.', 'Wish + would.', 'Would arrive.'], 'I wish you would arrive on time.'),
    order(3, 'g_third', 'Organize: “Se nós tivéssemos treinado mais, poderíamos ter ganhado.”', ['If we', 'had trained', 'more,', 'we might', 'have won'], ['If + had + particípio.', 'Vírgula depois da condição.', 'Might have + particípio.'], 'If we had trained more, we might have won.'),
    mc(3, 'g_mixed', '“Were he a more experienced driver, he wouldn\'t have had the accident.” O que a frase sugere?', ['Ele é um motorista experiente', 'Ele não é muito experiente, e por isso aconteceu o acidente', 'O acidente não aconteceu', 'Ele vai dirigir amanhã'], 1, ['Were he = If he were (presente imaginário).', 'Resultado no passado.', 'Ele não é experiente.'], 'Mixed com inversão: ele não é experiente → sofreu o acidente.'),
  ],
  review: ['Third: if + had + particípio, would/could/might have + particípio', 'Mixed: passado→presente (had done, would be now) · presente→passado (were, would have done)', 'Inversão formal: Had I known · Were I · Should you need', 'Wish/if only + past perfect (arrependimento) · wish + would (irritação)'],
  relatedQuestions: ['como usar o third conditional', 'o que é mixed conditional', 'o que significa had I known'],
  equivalentQuestions: eqs(['third conditional', 'mixed conditional'], ['como dizer se eu tivesse estudado teria passado em inglês', 'o que significa would have', 'diferença entre second e third conditional', 'o que é inversão nas condicionais', 'o que significa should you need', 'como usar I wish I had', 'if only em inglês']),
  commonErrors: ['Usar would have nas duas partes (If I would have known…).', 'Confundir mixed com third conditional.', 'Esquecer o have depois de would (would passed).'],
  english: {
    cefr: 'C1', unit: 'c1-u1', order: 1, area: 'grammar', focus: ['grammar', 'writing', 'reading'],
    vocabulary: [
      v('regret', 'arrependimento / arrepender-se', 'noun', 'a feeling of being sorry about something you did', 'My only regret is not studying abroad.', 2),
      v('hindsight', 'visão em retrospectiva', 'noun', 'understanding a situation only after it has happened', 'In hindsight, I should have left earlier.', 3),
      v('otherwise', 'caso contrário', 'adverb', 'if not; in a different situation', 'Leave now, otherwise you\'ll miss the bus.', 3),
      v('assistance', 'assistência, ajuda', 'noun', 'help (formal)', 'Should you need assistance, call us.', 3),
      v('outcome', 'resultado', 'noun', 'the final result', 'The outcome would have been different.', 3),
      v('opportunity', 'oportunidade', 'noun', 'a chance to do something', 'I missed a great opportunity.', 2),
    ],
    reading: {
      title: 'Looking back', genre: 'crônica reflexiva',
      text: 'Ten years ago I was offered a scholarship in Portugal, but I turned it down because I was afraid of living far from my family. Had I accepted it, I might be working in Europe now — or I might have missed the chance to open my own business here. People often ask me whether I regret it. The honest answer is complicated: I sometimes wish I had been braver, but if I had left, I wouldn\'t have met most of the people who matter to me today.',
      questions: [
        mci(2, 'Por que a autora recusou a bolsa?', ['Porque era cara', 'Por medo de morar longe da família', 'Porque não gostava de Portugal', 'Porque abriu um negócio'], 1, '“because I was afraid of living far from my family”.'),
        mci(3, '“Had I accepted it” equivale a:', ['If I accepted it', 'If I had accepted it', 'If I have accepted it', 'When I accept it'], 1, 'Inversão formal do third/mixed conditional.'),
        mci(3, 'Qual é a atitude da autora sobre a decisão?', ['Arrependimento total', 'Sentimentos mistos', 'Indiferença', 'Orgulho sem dúvidas'], 1, 'Ela diz que a resposta é “complicated”: às vezes queria ter sido mais corajosa, mas valoriza o que ganhou.'),
        mci(3, 'O que “I wish I had been braver” expressa?', ['Um plano para o futuro', 'Um arrependimento sobre o passado', 'Uma ordem', 'Uma certeza'], 1, 'Wish + past perfect = arrependimento sobre o passado.'),
      ],
    },
    writing: {
      prompt: 'Escreva um parágrafo reflexivo sobre uma escolha do passado e como ela afeta o seu presente, usando third conditional, mixed conditional e wish.', criteria: ['Um third conditional', 'Um mixed conditional (passado → presente)', 'Uma frase com wish ou if only', 'Coesão entre as ideias'],
      model: 'Last year I decided to join the robotics club. If I hadn\'t joined it, I wouldn\'t have discovered my passion for programming, and I wouldn\'t be planning to study engineering now. Sometimes I wish I had started earlier, but in hindsight the timing was right.', keywords: ['hadn\'t', 'wouldn\'t have', 'would', 'wish'], minWords: 50,
    },
    challenge: 'Reescreva duas frases de um e-mail formal usando a inversão (Should you…, Had we…).',
  },
  games: {
    blanks: [
      blank(1, 'If it hadn\'t rained, we ___ to the beach.', ['would have gone', 'would go', 'will go', 'had gone'], 0, 'Third: would have + particípio.'),
      blank(2, 'If I had eaten breakfast, I ___ hungry now.', ['wouldn\'t be', 'wouldn\'t have been', 'won\'t be', 'hadn\'t been'], 0, 'Mixed: resultado agora.'),
      blank(2, '___ I known about the party, I would have come.', ['Had', 'Have', 'Did', 'Were'], 0, 'Inversão: Had I known.'),
      blank(3, 'I wish I ___ that message. It was a mistake.', ['hadn\'t sent', 'didn\'t send', 'wouldn\'t send', 'haven\'t sent'], 0, 'Arrependimento: wish + past perfect.'),
      blank(3, '___ you require further details, please let us know.', ['Should', 'Would', 'Had', 'Were'], 0, 'Inversão formal: Should you…'),
    ],
    sequences: [words(2, 'If I had known I would have helped', 'Third conditional.'), words(3, 'Had we left earlier we would be there now', 'Inversão + mixed conditional.')],
  },
  sources: enSources(),
})

// ═══════════════════ C1 · Unidade 2 · Between the lines ═══════════════════
export const readingBetweenLines = lesson({
  id: 'ing-c1-reading-between-lines', subject: 'ingles', title: 'Reading between the lines', levels: [...LV], grade: 'Ensino Médio, ENEM e vestibulares',
  topic: 'Inglês C1 — Ler e escrever como especialista', subtopic: 'Inferência, tom, ironia e intenção do autor',
  aliases: ['interpretacao de texto em ingles', 'inferencia em ingles', 'ironia em ingles', 'tom do texto', 'intencao do autor', 'reading between the lines', 'enem ingles interpretacao', 'implicit meaning'],
  summary: 'Descubra o que o texto diz sem dizer: inferências, tom, ironia, intenção do autor e a função social do texto.',
  intro: '“Oh, great. Another Monday.” Será que a pessoa está feliz? Vamos ler nas entrelinhas.',
  objective: 'Fazer inferências com base em evidências do texto, identificar tom e ironia, reconhecer a intenção do autor e distinguir fato de opinião — como é cobrado no ENEM e em vestibulares.',
  prerequisites: ['ing-b2-idioms'], next: ['ing-c1-academic-writing'],
  skills: { r_infer: 'Inferência a partir de evidências', r_tone: 'Tom e ironia', r_intent: 'Intenção do autor e função social', r_fact: 'Fato × opinião' },
  blocks: [
    block('r_infer', 'Inference: what the text suggests',
      'Inferir é tirar uma conclusão que o texto não diz diretamente, mas que as pistas sustentam. Exemplo: “She grabbed her umbrella and sighed as she looked out the window” → provavelmente está chovendo e ela não está animada. Toda inferência precisa de uma evidência no texto; se não há pista, não é inferência, é invenção.',
      '“The fridge was empty and the kids were complaining.” → Alguém precisa fazer compras.',
      'Inferir = entender algo que o texto dá a entender, usando as pistas.',
      'Questão de prova: “It can be inferred from the text that…” — procure a frase que PROVA a resposta.',
      '1. Leia a pergunta. 2. Encontre as pistas no texto. 3. Escolha a conclusão que as pistas sustentam — e descarte as que exigem imaginar demais.',
      'Opções que parecem “verdade no mundo real”, mas não estão apoiadas no texto, são armadilhas clássicas de prova.'),
    block('r_tone', 'Tone and irony',
      'Tom é a atitude do autor: enthusiastic, critical, humorous, neutral, nostalgic, sarcastic… Ironia é dizer o contrário do que se quer dizer, geralmente para criticar ou fazer humor: “Oh, wonderful, the train is late again.” Pistas de ironia: contraste entre as palavras e a situação, exageros, aspas, pontuação e emojis.',
      '“Great job, team. We lost 5–0.” → irônico (crítica).',
      'Tom = o “jeito” do texto. Ironia = dizer o oposto do que se pensa.',
      'Numa charge, um político diz “Education is our priority” ao lado de uma escola caindo: a ironia está no contraste.',
      '1. Leia as palavras. 2. Compare com a situação descrita. 3. Se houver contradição proposital, provavelmente é ironia.',
      'Em português a ironia funciona igual: “Que maravilha, choveu no dia do passeio!” O segredo é o contraste.'),
    block('r_intent', "Author's purpose and social function",
      'Pergunte: para que o texto foi escrito? Informar (notícia), persuadir (propaganda, artigo de opinião), instruir (manual, receita), entreter (conto, charge), alertar (campanha). O gênero e o público ajudam a descobrir a intenção. O ENEM costuma perguntar a função social do texto ou o objetivo do autor.',
      'Uma campanha diz “Every drop counts. Turn off the tap while brushing your teeth.” → intenção: conscientizar sobre economia de água.',
      'Intenção = o objetivo do autor ao escrever.',
      'Anúncio: “Only today! 50% off!” → persuadir a comprar agora.',
      '1. Identifique o gênero (anúncio, notícia, poema…). 2. Pense no público. 3. Pergunte o que o autor quer que o leitor faça ou pense.',
      'Um mesmo tema pode ter intenções diferentes: uma notícia sobre plástico informa; uma campanha sobre plástico quer mudar comportamento.'),
    block('r_fact', 'Fact or opinion?',
      'Fato pode ser comprovado (The bridge was built in 1974). Opinião expressa julgamento (It is the most beautiful bridge in the city). Pistas de opinião: adjetivos avaliativos (best, terrible, amazing), verbos como believe, think, seem, e modais como should. Textos argumentativos misturam os dois: o autor usa fatos para sustentar opiniões.',
      'Fact: “Over 60% of the students use the library.” Opinion: “The library should open on weekends.”',
      'Fato = dá para provar. Opinião = é o que alguém acha.',
      'Crítica de filme: “The film lasts three hours (fato) and feels endless (opinião).”',
      '1. Dá para verificar? → fato. 2. Tem julgamento ou sugestão? → opinião. 3. Veja como os fatos sustentam as opiniões.',
      'Dados podem ser apresentados de forma tendenciosa: “Only 40% agreed” e “Almost half agreed” descrevem o mesmo fato com tons diferentes.'),
  ],
  questions: [
    mc(1, 'r_tone', '“Oh, perfect. My phone died right before the exam started.” O tom é:', ['entusiasmado', 'irônico', 'neutro', 'científico'], 1, ['“Perfect” combina com a situação?', 'Há contraste.', 'Ironia.'], 'O “perfect” diz o contrário: tom irônico.'),
    mc(1, 'r_fact', 'Qual frase é uma OPINIÃO?', ['The museum opened in 1998.', 'The museum has 3 floors.', 'The museum is the most exciting place in town.', 'The museum closes at 6 pm.'], 2, ['Qual não dá para provar?', 'Procure adjetivos avaliativos.', '“most exciting”.'], '“The most exciting” é julgamento: opinião.'),
    tf(1, 'r_infer', 'Uma inferência pode ser feita sem nenhuma pista no texto.', false, ['Inferir é usar pistas.', 'Sem pista, é invenção.', 'Precisa de evidência.'], 'Falso: toda inferência precisa de evidência no texto.'),
    fill(1, 'r_intent', 'Um anúncio que diz “Buy now, only today!” tem a intenção de ______ (convencer = p…).', ['persuade', 'persuadir', 'convencer'], ['Qual é o objetivo da propaganda?', 'Fazer o leitor comprar.', 'Persuadir.'], 'Intenção: persuadir (persuade).'),
    match(2, 'r_intent', 'Ligue o gênero à intenção mais comum.', [['news report', 'informar'], ['advertisement', 'persuadir'], ['recipe', 'instruir'], ['short story', 'entreter']], ['Notícia relata fatos.', 'Propaganda vende.', 'Receita ensina a fazer.'], 'informar · persuadir · instruir · entreter.'),
    mc(2, 'r_infer', '“Mark checked his watch for the fifth time and tapped his foot on the floor.” Podemos inferir que Mark está:', ['relaxado', 'impaciente', 'dormindo', 'triste pela família'], 1, ['O que ele faz repetidamente?', 'Olhar o relógio + bater o pé.', 'Impaciente.'], 'As ações indicam impaciência.'),
    mc(2, 'r_tone', 'Qual pista mais ajuda a reconhecer ironia?', ['Números exatos', 'Contraste entre as palavras e a situação', 'Frases curtas', 'Letras maiúsculas no título'], 1, ['Ironia = dizer o contrário.', 'Compare com o contexto.', 'Contraste.'], 'O contraste entre o que se diz e a situação.'),
    mc(2, 'r_fact', '“Although only 30% of residents recycle, the new program will certainly transform the city.” A segunda parte é:', ['fato comprovado', 'opinião/previsão do autor', 'dado estatístico', 'citação'], 1, ['“Will certainly transform” pode ser provado hoje?', 'É uma previsão.', 'Opinião.'], 'É uma previsão/opinião apresentada com certeza.'),
    order(3, 'r_infer', 'Coloque os passos de uma boa inferência na ordem.', ['Ler a pergunta com atenção', 'Encontrar as pistas no texto', 'Formular a conclusão que as pistas sustentam', 'Descartar opções sem evidência'], ['Primeiro entenda o que se pede.', 'Depois busque evidências.', 'Por fim, conclua e elimine.'], 'Pergunta → pistas → conclusão → descartar opções sem evidência.'),
    mc(3, 'r_intent', 'Uma campanha mostra uma tartaruga presa num canudo com a frase “Is your drink worth it?”. A intenção é:', ['vender canudos', 'informar a temperatura do mar', 'levar o leitor a repensar o uso de plástico', 'divulgar um restaurante'], 2, ['Imagem + pergunta retórica.', 'Qual comportamento ela quer mudar?', 'Uso de plástico.'], 'Conscientizar: repensar o uso de canudos de plástico.'),
  ],
  review: ['Inferência = conclusão sustentada por pistas do texto', 'Tom e ironia: compare as palavras com a situação', 'Intenção/função social: informar, persuadir, instruir, entreter, alertar', 'Fato (comprovável) × opinião (julgamento, previsão)'],
  relatedQuestions: ['como interpretar texto em inglês', 'como identificar ironia em inglês', 'como fazer inferência em texto'],
  equivalentQuestions: eqs(['interpretação de texto em inglês', 'inferência em inglês'], ['como identificar o tom de um texto em inglês', 'o que é intenção do autor', 'diferença entre fato e opinião em inglês', 'como saber se o texto é irônico', 'o que significa it can be inferred', 'dicas de interpretação de inglês no enem', 'o que é função social do texto']),
  commonErrors: ['Escolher a opção “verdadeira no mundo” mas sem apoio no texto.', 'Ler ironia ao pé da letra.', 'Confundir opinião apresentada com segurança com fato.'],
  enem: 'Interpretação, intenção comunicativa, ironia e função social de textos verbais e não verbais.',
  english: {
    cefr: 'C1', unit: 'c1-u2', order: 1, area: 'reading', focus: ['reading', 'vocabulary', 'writing'],
    vocabulary: [
      v('infer', 'inferir', 'verb', 'to reach a conclusion from evidence', 'We can infer that he was nervous.', 3),
      v('imply', 'sugerir, dar a entender', 'verb', 'to suggest something without saying it directly', 'Her smile implied that she agreed.', 3),
      v('tone', 'tom', 'noun', 'the attitude expressed in a text', 'The tone of the article is critical.', 2),
      v('irony', 'ironia', 'noun', 'saying the opposite of what you mean, often for humor or criticism', 'The irony is that the fire station burned down.', 3),
      v('bias', 'viés, parcialidade', 'noun', 'an unfair preference for one side', 'The report shows a clear bias.', 3),
      v('claim', 'afirmação / afirmar', 'noun', 'a statement that something is true', 'The author\'s claim is not supported by data.', 3),
      v('evidence', 'evidência, prova', 'noun', 'facts that show something is true', 'There is no evidence for that.', 2),
      v('purpose', 'propósito, objetivo', 'noun', 'the reason why something is done', 'What is the purpose of this ad?', 2),
    ],
    reading: {
      title: 'The smart city that forgot its citizens', genre: 'artigo de opinião adaptado',
      text: 'The mayor proudly announced that our city is now “the smartest in the region”: traffic lights talk to phones, bins report when they are full, and an app answers questions 24 hours a day. Impressive — unless you are one of the thousands of elderly residents who do not own a smartphone. Last week, the only public service office was closed "to encourage digital access". Perhaps the next innovation will be a chatbot that explains to grandparents why they can no longer speak to a human being.',
      questions: [
        mci(2, 'Qual é a posição do autor sobre a “cidade inteligente”?', ['Totalmente favorável', 'Crítica, porque a tecnologia exclui parte da população', 'Neutra', 'Indiferente'], 1, 'O autor mostra as inovações e depois o problema dos idosos sem smartphone.'),
        mci(3, 'O trecho “Perhaps the next innovation will be a chatbot that explains to grandparents…” tem tom:', ['elogioso', 'irônico', 'científico', 'nostálgico'], 1, 'O autor sugere algo absurdo para criticar: ironia.'),
        mci(3, 'Por que “to encourage digital access” está entre aspas?', ['Para citar a justificativa oficial e mostrar desconfiança dela', 'Porque é o título', 'Porque é um termo técnico', 'Porque é uma tradução'], 0, 'As aspas marcam a fala oficial, que o autor questiona.'),
        mci(3, 'Qual é a intenção principal do texto?', ['Divulgar um aplicativo', 'Informar horários de ônibus', 'Criticar políticas que ignoram quem não tem acesso digital', 'Ensinar a usar smartphones'], 2, 'É um artigo de opinião que critica a exclusão digital.'),
      ],
    },
    writing: {
      prompt: 'Escolha um anúncio, meme ou charge e escreva um parágrafo analisando: gênero, público, intenção do autor, tom e as pistas que sustentam a sua interpretação.', criteria: ['Identifica gênero e público', 'Explica a intenção com evidências', 'Comenta o tom (e a ironia, se houver)', 'Diferencia fato de opinião'],
      model: 'This advertisement targets teenagers and aims to persuade them to download a study app. The tone is enthusiastic, and the claim that "everyone is using it" is an opinion presented as a fact, since no evidence is given.', keywords: ['tone', 'purpose', 'persuade', 'evidence', 'claim'], minWords: 45,
    },
    challenge: 'Leia uma manchete em inglês e responda: qual é o tom? Que palavra mostra isso? Há fato ou opinião?',
    tips: ['Em provas, sublinhe a frase do texto que justifica a sua resposta.', 'Desconfie de opções com “always”, “never” e “all”: raramente o texto sustenta generalizações.'],
  },
  games: {
    blanks: [
      blank(2, 'A ___ can be proved; an opinion cannot.', ['fact', 'claim', 'tone', 'bias'], 0, 'Fato pode ser comprovado.'),
      blank(2, 'The author\'s ___ is to persuade readers to recycle.', ['purpose', 'irony', 'evidence', 'bias'], 0, 'Purpose = objetivo.'),
      blank(3, 'Saying “Nice weather!” during a storm is an example of ___.', ['irony', 'evidence', 'inference', 'data'], 0, 'Dizer o contrário: ironia.'),
      blank(3, 'From his tired face, we can ___ that he didn\'t sleep well.', ['infer', 'imply to', 'claim', 'prove that'], 0, 'Tirar conclusão a partir de pistas: infer.'),
    ],
    pairs: [{ a: 'infer', b: 'inferir', difficulty: 2 }, { a: 'imply', b: 'dar a entender', difficulty: 3 }, { a: 'bias', b: 'viés', difficulty: 3 }, { a: 'claim', b: 'afirmação', difficulty: 3 }, { a: 'tone', b: 'tom', difficulty: 2 }],
  },
  sources: [...enSources(), { title: 'Matriz de Referência do ENEM — Linguagens, Códigos e suas Tecnologias', url: 'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem', author: 'INEP', kind: 'instituicao', accessedAt: '2026-09-28' }],
})
