import { block, fill, lesson, mc, tf } from '../dsl'
const F: any[] = []

// 1º Fundamental
export const inglFund1 = lesson({id:'ingl-fund-1',subject:'ingles',title:'Inglês 1º Fundamental',levels:['fund1'],grade:'1º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['alfabeto','números','cores','animais'],summary:'Alfabeto, números 0-10, cores, animais.',intro:'Aprenda o ABC em inglês.',objective:'Conhecer o alfabeto e vocabulário básico.',next:[],skills:{a:'Alphabet',n:'Numbers'},blocks:[block('a','Alphabet','A B C D E F G H I J K L M N O P Q R S T U V W X Y Z','26 letras.','Maiúsculas.','Som cada letra.','Qual vem depois D?'),block('n','Numbers','0=zero, 1=one, 2=two, 3=three, 4=four, 5=five, 6=six, 7=seven, 8=eight, 9=nine, 10=ten.','Contar até 10.','Um dígito.','Básico.','Quantos dedos?'),],questions:[mc(1,'a','C é a ___ letra.',['segunda','terceira','quarta'],1,['Terceira.','Ordem.','Alfabeto.']),tf(1,'n','Nine = 9',true,['Sim.','Número.','Dígito.']),fill(1,'a','Antes de E: ___.',['D'],['Letra.','Ordem.','Sequência.']),mc(2,'n','Depois de 7?',['8','9','10'],0,['Oito.','Sequence.','Numero.']),],review:['A-Z',  '0-10','Cores','Animais'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund2 = lesson({id:'ingl-fund-2',subject:'ingles',title:'Inglês 2º Fundamental',levels:['fund1'],grade:'2º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['família','cores','animais','números 0-20'],summary:'Família, cores, animais, números 0-20.',intro:'My family and colors.',objective:'Vocabulário: família e cores.',next:[],skills:{f:'Family',c:'Colors'},blocks:[block('f','Family','Mother=mãe, Father=pai, Sister=irmã, Brother=irmão, Grandma=avó, Grandpa=avó.','Pessoas casa.','Parentesco.','Básico.','Quem é sua mãe?'),block('c','Colors','Red=vermelho, Blue=azul, Green=verde, Yellow=amarelo, Orange=laranja, Purple=roxo, Pink=rosa, Black=preto.','8 cores.','Rainbow.','Básico.','Cor favorita?'),],questions:[mc(1,'f','Mãe=?',['mother','father','sister'],0,['Mother.','Fêmea.','Pai tem Y.']),tf(1,'c','Blue=azul',true,['Sim.','Cor.','Céu.']),fill(1,'f','___ = irmão.',['Brother'],['Masculino.','Família.','Jovem.']),mc(2,'c','Que cor é o pasto?',['Blue','Green','Yellow'],1,['Grama.','Natureza.','Não yellow.']),],review:['Mother/Father','Brother/Sister','Cores 8','Rainbow'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund3 = lesson({id:'ingl-fund-3',subject:'ingles',title:'Inglês 3º Fundamental',levels:['fund1'],grade:'3º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['comida','bebida','animais','números 0-100'],summary:'Comida, bebida, animais, números até 100.',intro:'Food and drinks.',objective:'Vocabulário: comida e bebida.',next:[],skills:{f:'Food',d:'Drinks'},blocks:[block('f','Food','Apple=maçã, Bread=pão, Cheese=queijo, Egg=ovo, Milk=leite, Rice=arroz, Meat=carne.','Alimentos.','Proteína.','Saudável.','Come pão?'),block('d','Drinks','Water=água, Juice=suco, Milk=leite, Tea=chá, Coffee=café.','Bebidas.','Líquido.','Todos dias.','Qual bebida?'),],questions:[mc(1,'f','Apple=?',['maçã','fruta','vermelha'],0,['Maçã.','Fruta.','Come.','Doce.']),tf(1,'d','Water=água',true,['Sim.','Bebida.','Líquido.']),fill(1,'f','___ = pão.',['Bread'],['Carboidrato.','Alimento.','Branco.']),mc(2,'d','Chá=?',['Tea','Coffee','Juice'],0,['Quente.','Bebida.','Diferentes folhas.']),],review:['Apple/Bread/Meat','Water/Juice/Tea','Alimentos','Bebidas'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund4 = lesson({id:'ingl-fund-4',subject:'ingles',title:'Inglês 4º Fundamental',levels:['fund1'],grade:'4º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['corpo','roupas','objetos','preposições'],summary:'Partes do corpo, roupas, objetos, preposições.',intro:'My body and clothes.',objective:'Vocabulário: corpo e roupas.',next:[],skills:{b:'Body',c:'Clothes'},blocks:[block('b','Body','Head=cabeça, Eyes=olhos, Nose=nariz, Mouth=boca, Ears=ouvidos, Arms=braços, Hands=mãos, Legs=pernas, Feet=pés.','9 partes.','Anatomia.','Você tem.','Qual é maior?'),block('c','Clothes','Shirt=camiseta, Pants=calça, Shoes=sapatos, Hat=chapéu, Jacket=jaqueta, Socks=meias.','Vestuário.','Proteção.','Diferente cada dia.','O que veste?'),],questions:[mc(1,'b','Nose=?',['nariz','olho','boca'],0,['Nariz.','Rosto.','Smells.']),tf(1,'c','Shoes=sapatos',true,['Sim.','Vestuário.','Pés.']),fill(1,'b','___ = olhos.',['Eyes'],['2 partes.','Rosto.','Ver.','Plural']),mc(2,'c','Jacket=?',['jaqueta','camiseta','calça'],0,['Quente.','Inverno.','Fora.']),],review:['9 partes corpo','Roupas 6','Vestuário','Anatomia'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund5 = lesson({id:'ingl-fund-5',subject:'ingles',title:'Inglês 5º Fundamental',levels:['fund1'],grade:'5º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['present tense','verbo to be','I am','you are'],summary:'Presente simples: to be (I am, you are, he is).',intro:'I am student.',objective:'Verbo to be no presente.',next:[],skills:{b:'Be',p:'Present'},blocks:[block('b','To be','I am, You are, He/She/It is, We are, They are.','6 conjugações.','Ser/estar.','Mais comum.','Qual é você?'),block('p','Present','I am happy. You are smart. He is tall. She is young. It is big. We are friends. They are here.','Frases.','Adjetivos.','Descrição.','Como você é?'),],questions:[mc(1,'b','He ___ tall.',['is','am','are'],0,['Singular.','3ª pessoa.','Masculino.']),tf(1,'p','I are happy',false,['Não.','I am.','Erro comum.']),fill(1,'b','You ___ student.',['are'],['Plural.','2ª pessoa.','To be.']),mc(2,'p','They ___ here.',['is','are','am'],1,['Plural.','Multiple.','There.']),],review:['To be','I am/You are/He is','Presente','Afirmativo'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund6 = lesson({id:'ingl-fund-6',subject:'ingles',title:'Inglês 6º Fundamental',levels:['fund1'],grade:'6º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['have/has','possessivo','my your his'],summary:'Have/Has e adjetivos possessivos.',intro:'I have a cat.',objective:'Posse: have/has e possessivos.',next:[],skills:{h:'Have',p:'Possessive'},blocks:[block('h','Have/Has','I have, You have, He/She/It has, We have, They have.','Posse.','Presente.','Objeto.','O que você tem?'),block('p','Possessive','My=meu, Your=seu, His=dele, Her=dela, Its=dele/dela (coisa), Our=nosso, Their=deles.','7 possessivos.','Adjetivos.','Antes nome.','De quem é?'),],questions:[mc(1,'h','She ___ a dog.',['have','has','are'],1,['Singular 3ª.','Cão.','Posse.']),tf(1,'p','My book=livro meu',true,['Sim.','Possessivo.','Ordem.']),fill(1,'h','They ___ toys.',['have'],['Plural.','Brinquedos.','Posse.']),mc(2,'p','___ name = nome dele.',['His','Her','My'],0,['3ª masc.','Possessivo.','Dele.']),],review:['Have/Has','My/Your/His/Her','Possessivo','Posse'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund7 = lesson({id:'ingl-fund-7',subject:'ingles',title:'Inglês 7º Fundamental',levels:['fund1'],grade:'7º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['present continuous','ing','está fazendo'],summary:'Present continuous: is/are + -ing.',intro:'I am studying.',objective:'Presente contínuo.',next:[],skills:{c:'Continuous',i:'-ing'},blocks:[block('c','Continuous','I am eating. You are reading. He is playing. She is working. We are learning. They are running.','Ação agora.','Temporário.','Dinâmico.','O que faz?'),block('i','-ing','Eat→eating, Read→reading, Play→playing, Work→working, Learn→learning, Run→running.','Forma ing.','Sufixo.','Presente contínuo.','Como forma?'),],questions:[mc(1,'c','She ___ eating.',['is','am','are'],0,['3ª singular.','Ação.','Agora.']),tf(1,'i','Play+ing=playing',true,['Sim.','Sufixo.','Ativo']),fill(1,'c','We ___ studying.',['are'],['Nós.','Plural.','Contínuo.']),mc(2,'i','Run+ing=?',['runing','running','runnig'],1,['Duplo n.','Running.','Regra.']),],review:['Is/Are+ing','Present Continuous','Forma -ing','Ação agora'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund8 = lesson({id:'ingl-fund-8',subject:'ingles',title:'Inglês 8º Fundamental',levels:['fund1'],grade:'8º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['past tense','was were','fiz fez'],summary:'Passado simples: was/were e regular verbs.',intro:'I was happy.',objective:'Passado simples.',next:[],skills:{p:'Past',w:'Was/Were'},blocks:[block('p','Past','I worked. You played. He studied. She read. We went. They came.','Ação acabada.','Passado simples.','Completo.','Ontem?'),block('w','Was/Were','I was, You were, He/She/It was, We were, They were.','Ser/estar passado.','Antônimo presente.','Estático.','Como era?'),],questions:[mc(1,'p','Yesterday I ___ a book.',['read','readed','reads'],0,['Past simple.','Verbo.','Ontem.']),tf(1,'w','They was here',false,['Não.','They were.','Plural.']),fill(1,'w','She ___ happy.',['was'],['3ª singular.','Passado.','Adjetivo.']),mc(2,'p','He ___ the ball yesterday.',['played','plays','playing'],0,['Past simple.','Regular.','Ontem.']),],review:['Past simple','Was/Were','Regular verbs','Ontem/passado'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglFund9 = lesson({id:'ingl-fund-9',subject:'ingles',title:'Inglês 9º Fundamental',levels:['fund1'],grade:'9º',topic:'Inglês Escolar',subtopic:'Fundamental',aliases:['future tense','will','going to'],summary:'Futuro: will e going to.',intro:'I will study.',objective:'Futuro simples.',next:[],skills:{f:'Future',w:'Will'},blocks:[block('f','Future','I will go. You will study. He will work. She will play. We will learn. They will come.','Ação futura.','Planejado.','Após presente.','Amanhã?'),block('w','Will','Will + infinitive. I will eat. You will sleep. He will run. Negativo: won\'t = will not.','Auxiliar.','Auxiliar.','Simples.','O que fará?'),],questions:[mc(1,'f','Tomorrow I ___ a test.',['will take','take','taking'],0,['Futuro.','Will.','Amanhã.']),tf(1,'w','I will not = I won\'t',true,['Sim.','Contração.','Negativo.']),fill(1,'f','She ___ happy tomorrow.',['will be'],['Futuro.','To be.','Predict.']),mc(2,'w','___ you study?',['Will','Are','Do'],0,['Futuro.','Question.','Will.']),],review:['Will+infinitive','Going to','Futuro','Amanhã/próximo'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

// Ensino Médio: 1º-3º
export const inglMed1 = lesson({id:'ingl-med-1',subject:'ingles',title:'Inglês 1º Médio',levels:['medio'],grade:'1º Médio',topic:'Inglês Escolar',subtopic:'Médio',aliases:['present perfect','have seen','já fiz'],summary:'Present perfect: have/has + past participle.',intro:'I have studied.',objective:'Presente perfeito.',next:[],skills:{p:'Perfect',h:'Have+PP'},blocks:[block('p','Perfect','I have studied. You have read. He has gone. She has eaten. We have lived. They have arrived.','Experiência até agora.','Recente/distante.','Relevância presente.','Já fez?'),block('h','Have+PP','Have/has + past participle (studied, read, gone, eaten, lived, arrived).','3 partes.','Auxiliar + verbo.','Conexão passado-presente.','Como forma?'),],questions:[mc(1,'p','I ___ English for 5 years.',['have studied','studied','am studying'],0,['Desde.','Duração.','Perfect.']),tf(1,'h','Have you went?',false,['Não.','Gone.','Past participle.']),fill(1,'p','She ___ a book.',['has read'],['3ª.','Perfect.','Completo.']),mc(2,'h','They ___ lived here.',['have','has','are'],0,['3ª plural.','Morar.','Tempo.']),],review:['Present perfect','Have/Has','Past participle','Até agora'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglMed2 = lesson({id:'ingl-med-2',subject:'ingles',title:'Inglês 2º Médio',levels:['medio'],grade:'2º Médio',topic:'Inglês Escolar',subtopic:'Médio',aliases:['conditional','if clauses','se fizesse'],summary:'Condicional: if clauses e would.',intro:'If I had time, I would study.',objective:'Condicional e if clauses.',next:[],skills:{c:'Conditional',i:'If'},blocks:[block('c','Conditional','I would go. You would study. He would work. Negativo: wouldn\'t. Contração: would\'ve, wouldn\'t\'ve.','Hipotético.','Contrário realidade.','Imaginário.','E se?'),block('i','If clauses','If + past, would + infinitive. If I had a car, I would drive. If she studied, she would pass. If we went, we would be happy.','3 tipos básicos.','Condicional 2.','Possível mas improvável.','Qual condição?'),],questions:[mc(1,'c','If I were you, I ___ go.',['would','will','am'],0,['Condicional.','Hipotético.','Wouldn\'t.']),tf(1,'i','If I had money, I would buy a house',true,['Sim.','Condicional.','Possível']),fill(1,'c','He ___ come if invited.',['would'],['Condicional.','Would.','Se chamarem.']),mc(2,'i','If she ___ hard, she would succeed.',['studied','studies','studying'],0,['Condicional 2.','Passado.','Se estudasse.']),],review:['Would+infinitive','If clauses','Condicional','Hipotético'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const inglMed3 = lesson({id:'ingl-med-3',subject:'ingles',title:'Inglês 3º Médio',levels:['medio'],grade:'3º Médio',topic:'Inglês Escolar',subtopic:'Médio',aliases:['passive voice','ser feito','by'],summary:'Passive voice: am/is/are/was/were + past participle.',intro:'The book was written.',objective:'Voz passiva.',next:[],skills:{p:'Passive',a:'Agent'},blocks:[block('p','Passive','The house was built in 1990. The letter was written by John. The windows are cleaned every week. The cake was eaten. The project will be finished tomorrow.','Sujeito recebe ação.','Agente pode aparecer.','Formal.','Quem fez?'),block('a','Agent','By+agent: by John, by the teacher, by them. Opcional na passiva.','Preposição by.','Introduz agente.','Quem realizou.','Quem fez o quê?'),],questions:[mc(1,'p','The door was ___ yesterday.',['opened','open','opening'],0,['Past participle.','Passiva.','Passado.']),tf(1,'a','The cake was eaten by Mary',true,['Sim.','Agente.','Passiva.']),fill(1,'p','The book ___ published in 2020.',['was'],['Singular.','Passada.','Livro.']),mc(2,'a','The email was sent ___ the manager.',['by','at','to'],0,['By=agent.','Quem.','Manager.']),],review:['Was/Were+PP','Passive voice','By+agent','Voz passiva'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})
