// Curso de Inglês do LUMI — nível B1 (Intermediário). Conteúdo original.
import { block, blank, dialogue, enSources, eqs, fill, lesson, match, mc, mci, order, tf, v, words } from '../dsl'

const LV = ['fund2', 'medio'] as const

// ═══════════════════ Unidade 1 · Have you ever…? ═══════════════════
export const presentPerfect = lesson({
  id: 'ing-b1-present-perfect', subject: 'ingles', title: 'Present perfect', levels: [...LV], grade: '9º ano e Ensino Médio',
  topic: 'Inglês B1 — Experiências e hipóteses', subtopic: 'Present perfect: experiências, for/since, já/ainda',
  aliases: ['present perfect', 'presente perfeito', 'have has particípio', 'for since', 'ever never', 'already yet just', 'present perfect ou simple past', 'have you ever'],
  summary: 'Fale de experiências de vida, de situações que continuam até hoje e de coisas que acabaram de acontecer.',
  intro: 'Have you ever eaten sushi? O present perfect liga o passado ao presente.',
  objective: 'Formar o present perfect com have/has + particípio, usar ever/never, for/since e already/yet/just, e escolher entre ele e o simple past.',
  prerequisites: ['ing-a2-simple-past'], next: ['ing-b1-present-perfect-continuous'],
  skills: { g_form: 'Have/has + particípio', g_exp: 'Experiências: ever / never', g_forsince: 'For e since (até hoje)', g_vs: 'Present perfect × simple past' },
  blocks: [
    block('g_form', 'have / has + past participle',
      'Estrutura: have (I, you, we, they) ou has (he, she, it) + particípio passado. Regulares: igual ao passado (worked, played). Irregulares: é a 3ª forma (go-went-gone, see-saw-seen, eat-ate-eaten, do-did-done, be-was-been, write-wrote-written). Negativa: haven\'t/hasn\'t. Pergunta: Have you…? Has she…?',
      'I\'ve finished my homework. · She hasn\'t called yet. · Have they arrived?',
      'Have/has + particípio: I have seen = eu já vi / tenho visto.',
      'Mensagem: “I\'ve sent you the file. Have you received it?”',
      '1. Sujeito. 2. Have ou has. 3. Particípio (3ª coluna da tabela de irregulares).',
      'Não confunda o have auxiliar (I have eaten) com o have de “ter” (I have a dog). No present perfect, ele só ajuda a formar o tempo.'),
    block('g_exp', 'Experiences: ever and never',
      'O present perfect fala de experiências na vida, sem dizer quando: I\'ve been to Argentina. Ever (alguma vez) aparece em perguntas: Have you ever eaten sushi? Never (nunca) na afirmativa: I\'ve never seen snow. Been to = já esteve em (e voltou).',
      '— Have you ever been to Bahia? — Yes, I have. / No, I\'ve never been there.',
      'Have you ever…? = Você já…? I\'ve never… = Eu nunca…',
      'Jogo de perguntas com amigos: “Have you ever broken a bone?”',
      '1. Pergunta: Have you ever + particípio? 2. Resposta: Yes, I have / No, I haven\'t. 3. Detalhe no simple past: “Yes! I went there in 2022.”',
      'Se você disser QUANDO (in 2022, last year), mude para o simple past: I went there in 2022. Sem data: I\'ve been there.'),
    block('g_forsince', 'For and since',
      'Para algo que começou no passado e continua até agora: For + período (for three years, for a long time). Since + ponto de início (since 2020, since Monday, since I was a child). Pergunta: How long have you lived here?',
      'I\'ve lived here for five years. · She\'s been my friend since 2019.',
      'For = há (quanto tempo). Since = desde (quando começou).',
      '“How long have you studied English?” — “For two years / Since 2023.”',
      '1. Pense na duração ou no começo. 2. Duração → for. 3. Começo → since.',
      'Em português dizemos “Moro aqui há 5 anos” (presente). Em inglês é present perfect: I\'ve lived here for 5 years — “I live here for 5 years” está errado.'),
    block('g_vs', 'Present perfect or simple past?',
      'Simple past: tempo terminado e definido (yesterday, in 2020, last week, when I was 10). Present perfect: tempo não dito ou que ainda não acabou (ever, never, today, this week, so far, already, yet, just). Already (já) e just (acabou de) na afirmativa; yet (ainda/já) em negativas e perguntas.',
      'I saw that movie last week. · I\'ve already seen that movie. · Have you finished yet?',
      'Tem data no passado? simple past. Não tem data ou continua? present perfect.',
      'Conversa: “Have you had lunch?” (hoje, não acabou) — “Yes, I had lunch at noon.” (hora definida)',
      '1. Procure a palavra de tempo. 2. Yesterday, last…, in 2020 → simple past. 3. Ever, never, yet, already, since, for → present perfect.',
      'Em português usamos “já comi” e “comi ontem” no mesmo tempo verbal. Em inglês são dois: I\'ve already eaten × I ate yesterday.'),
  ],
  questions: [
    mc(1, 'g_form', 'She ___ her keys. She can\'t open the door.', ['has lost', 'have lost', 'lost yesterday', 'is losing'], 0, ['Resultado no presente.', 'She → has.', 'Has + particípio.'], 'She has lost her keys.'),
    mc(1, 'g_exp', '— Have you ever ___ to Paris? — No, never.', ['went', 'been', 'go', 'going'], 1, ['Ever + particípio.', 'Já esteve em = been to.', 'Been.'], 'Have you ever been to Paris?'),
    fill(1, 'g_forsince', 'Complete: I\'ve lived here ___ 2018.', ['since'], ['2018 é o ponto de início.', 'Início → since.', 'Desde = …'], 'Since 2018.'),
    tf(1, 'g_form', 'O particípio de “eat” é “eaten”.', true, ['eat - ate - …', 'Terceira forma.', 'Termina em -en.'], 'Verdadeiro: eat-ate-eaten.'),
    match(2, 'g_form', 'Ligue o verbo ao particípio.', [['go', 'gone'], ['write', 'written'], ['do', 'done'], ['see', 'seen']], ['Go → g…', 'Write → written (dois t).', 'See → seen.'], 'gone · written · done · seen.'),
    mc(2, 'g_forsince', 'We\'ve been friends ___ ten years.', ['since', 'for', 'ago', 'during'], 1, ['Ten years é duração.', 'Duração → for.', 'For.'], 'For ten years.'),
    mc(2, 'g_vs', 'I ___ that movie last Saturday.', ['have seen', 'saw', 'have saw', 'seen'], 1, ['Last Saturday é data definida.', 'Tempo terminado.', 'Simple past.'], 'I saw it last Saturday.'),
    mc(2, 'g_vs', '— Have you finished your project ___? — Not yet.', ['already', 'yet', 'just', 'since'], 1, ['Pergunta.', 'Ainda/já em pergunta.', 'Yet.'], 'Have you finished yet?'),
    order(3, 'g_forsince', 'Organize: “Há quanto tempo você estuda inglês?”', ['How', 'long', 'have', 'you', 'studied', 'English?'], ['How long = quanto tempo.', 'Depois have + you.', 'Particípio.'], 'How long have you studied English?'),
    mc(3, 'g_vs', 'Qual frase está correta?', ['I have visited Rome in 2019.', 'I visited Rome in 2019.', 'I have visit Rome in 2019.', 'I visit Rome since 2019.'], 1, ['Tem data definida (2019).', 'Data definida → simple past.', 'Visited.'], 'Com “in 2019”: I visited Rome in 2019.'),
  ],
  review: ['have/has + particípio (gone, seen, eaten, done)', 'Have you ever…? · I\'ve never…', 'for + duração · since + início', 'Data definida → simple past; sem data/até hoje → present perfect'],
  relatedQuestions: ['como usar o present perfect', 'diferença entre for e since', 'present perfect ou simple past'],
  equivalentQuestions: eqs(['present perfect', 'presente perfeito'], ['quando usar have e has com particípio', 'diferença entre present perfect e simple past', 'como dizer eu moro aqui há 5 anos em inglês', 'o que significa have you ever', 'quando usar already e yet', 'particípio de go', 'been ou gone']),
  commonErrors: ['Usar present perfect com data definida (I have gone yesterday).', 'Dizer “I live here for 5 years”.', 'Usar o passado no lugar do particípio (have went).'],
  english: {
    cefr: 'B1', unit: 'b1-u1', order: 1, area: 'grammar', focus: ['grammar', 'speaking', 'reading'],
    vocabulary: [
      v('ever', 'alguma vez / já', 'adverb', 'at any time', 'Have you ever flown in a plane?', 1),
      v('never', 'nunca', 'adverb', 'not at any time', 'I\'ve never seen snow.', 1),
      v('already', 'já', 'adverb', 'before now, sooner than expected', 'I\'ve already eaten.', 2),
      v('yet', 'ainda / já (perguntas)', 'adverb', 'until now (in questions and negatives)', 'She hasn\'t replied yet.', 2),
      v('just', 'acabou de', 'adverb', 'a very short time ago', 'I\'ve just arrived.', 2),
      v('since', 'desde', 'preposition', 'from a point in the past until now', 'I\'ve known him since 2020.', 2),
      v('experience', 'experiência', 'noun', 'something that happened to you', 'It was an amazing experience.', 2),
      v('abroad', 'no exterior', 'adverb', 'in or to another country', 'Have you ever studied abroad?', 3),
    ],
    grammar: {
      name: 'Present perfect', when: 'Experiências sem data, situações que continuam até hoje e resultados no presente.', structure: 'have/has + past participle',
      affirmative: ['I\'ve been to Chile.', 'She has lived here since 2015.'], negative: ['I haven\'t seen it yet.', 'He hasn\'t called.'], interrogative: ['Have you ever tried it?', 'How long has she worked there?'],
      compare: 'I lost my phone yesterday (quando) × I\'ve lost my phone (e ainda não achei: resultado agora).', context: 'Entrevista para intercâmbio: “Have you ever lived abroad?”',
    },
    reading: {
      title: 'Adventure blog', genre: 'post de blog',
      text: 'I\'ve always loved traveling. So far, I\'ve visited twelve countries and I\'ve tried food from all of them. I\'ve never been to Asia, but I\'ve saved money for two years to go to Japan. My flight is next month! I went to Peru in 2023 and climbed to Machu Picchu — it was the hardest walk of my life.',
      questions: [
        mci(1, 'Quantos países a autora já visitou?', ['2', '10', '12', '20'], 2, '“I\'ve visited twelve countries”.'),
        mci(2, 'Que continente ela nunca visitou?', ['América do Sul', 'Ásia', 'Europa', 'África'], 1, '“I\'ve never been to Asia”.'),
        mci(2, 'Há quanto tempo ela junta dinheiro para o Japão?', ['Dois meses', 'Dois anos', 'Desde 2023', 'Um ano'], 1, '“for two years”.'),
        mci(3, 'Por que “I went to Peru” está no simple past?', ['Porque é uma experiência', 'Porque tem data definida (2023)', 'Porque ela ainda está lá', 'Porque é um plano'], 1, 'Com data definida, usamos o simple past.'),
      ],
    },
    speaking: {
      situation: 'Um jogo de “Have you ever…?” com colegas de outro país.', vocabulary: ['have you ever', 'never', 'once', 'twice'],
      phrases: ['Have you ever…?', 'Yes, I have. I … when I was…', 'No, I\'ve never…'], example: 'Have you ever been to the beach? — Yes, I have. I went to Maceió last year.',
      challenge: 'Faça 3 perguntas com Have you ever… e responda cada uma com um detalhe no simple past.', expected: ['have', 'ever', 'never', 'been'],
    },
    writing: {
      prompt: 'Escreva sobre 3 experiências que você já teve e 2 que nunca teve (e gostaria de ter).', criteria: ['Present perfect para experiências', 'Uma frase com never', 'Um detalhe com data no simple past'],
      model: 'I\'ve been to Rio twice. I\'ve seen a whale — it was in 2022, in Bahia. I\'ve never flown in a plane and I\'ve never tried sushi, but I want to!', keywords: ['have', 'never', 'been'], minWords: 25,
    },
    challenge: 'Pergunte a alguém “How long have you…?” (lived here, studied at…, known me) e anote a resposta com for ou since.',
  },
  games: {
    blanks: [
      blank(1, 'I have lived here ___ 2020.', ['for', 'since', 'during', 'from'], 1, 'Ponto de início: since.'),
      blank(1, 'Have you ever ___ sushi?', ['eaten', 'ate', 'eat', 'eating'], 0, 'Particípio: eaten.'),
      blank(2, 'She has ___ finished. Look, she\'s leaving!', ['just', 'yet', 'ever', 'since'], 0, 'Acabou de: just.'),
      blank(2, 'I ___ to London in 2019.', ['went', 'have gone', 'have been', 'go'], 0, 'Data definida: simple past.'),
      blank(3, 'They haven\'t replied to my message ___.', ['yet', 'already', 'just', 'ever'], 0, 'Negativa: yet.'),
    ],
    pairs: [{ a: 'go', b: 'gone', difficulty: 1 }, { a: 'eat', b: 'eaten', difficulty: 1 }, { a: 'write', b: 'written', difficulty: 2 }, { a: 'take', b: 'taken', difficulty: 2 }, { a: 'break', b: 'broken', difficulty: 3 }, { a: 'fly', b: 'flown', difficulty: 3 }],
    sequences: [words(1, 'I have never seen snow', 'have + never + particípio.'), words(2, 'Has she finished her homework yet', 'Pergunta: Has + she + particípio + yet.')],
    dialogues: [
      dialogue(2, 'Na festa', ['Tom: Have you ever been to Japan?', 'Aya: Yes, I have. I went there last year.', 'Tom: Wow! How was it?', 'Aya: It was amazing!'], 1, ['Yes, I have. I went there last year.', 'Yes, I have went there last year.', 'Yes, I did been there.', 'Yes, I go there last year.'], 0, 'Resposta curta com have + detalhe no simple past.'),
    ],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 2 · If… ═══════════════════
export const conditionals = lesson({
  id: 'ing-b1-conditionals', subject: 'ingles', title: 'First and second conditional', levels: [...LV], grade: '9º ano e Ensino Médio',
  topic: 'Inglês B1 — Experiências e hipóteses', subtopic: 'Zero, first e second conditional',
  aliases: ['conditionals', 'condicionais em ingles', 'first conditional', 'second conditional', 'zero conditional', 'if clauses', 'frases com if', 'would em ingles', 'if i were'],
  summary: 'Fale de verdades gerais, consequências prováveis e situações imaginárias com if.',
  intro: 'If you study, you will pass. If I were a bird, I would fly… Vamos aprender a imaginar em inglês.',
  objective: 'Usar o zero conditional para fatos, o first para consequências prováveis no futuro e o second para situações imaginárias, incluindo “If I were…”.',
  prerequisites: ['ing-a2-future', 'ing-a2-simple-past'], next: ['ing-b1-phrasal-verbs'],
  skills: { g_zero: 'Zero conditional (fatos)', g_first: 'First conditional (provável)', g_second: 'Second conditional (imaginário)', g_choose: 'Escolher a condicional' },
  blocks: [
    block('g_zero', 'Zero conditional',
      'Para verdades gerais e fatos científicos: If + simple present, simple present. If you heat ice, it melts. If também pode ser trocado por when sem mudar o sentido.',
      'If you mix blue and yellow, you get green. · Plants die if they don\'t get water.',
      'Se isso acontece, aquilo sempre acontece.',
      'Aula de ciências: “If water reaches 100 °C, it boils.”',
      '1. If + presente. 2. Vírgula (se o if vier primeiro). 3. Resultado no presente.',
      'Zero conditional = regra que sempre vale. Não é uma previsão, é um fato.'),
    block('g_first', 'First conditional',
      'Para uma condição real e provável no futuro: If + simple present, will + verbo. If it rains tomorrow, we\'ll stay home. Também: unless (a menos que) = if … not: Unless you hurry, you\'ll be late.',
      'If you study, you\'ll pass the test. · If I see her, I\'ll tell her.',
      'Se acontecer (é possível), vai acontecer isto.',
      'Mãe avisando: “If you don\'t take a coat, you\'ll get cold.”',
      '1. If + presente (NÃO will). 2. Vírgula. 3. Will + verbo.',
      'Em português dizemos “se chover amanhã” (subjuntivo futuro). Em inglês, depois de if vem o PRESENTE: If it rains — nunca “if it will rain”.'),
    block('g_second', 'Second conditional',
      'Para situações imaginárias, improváveis ou irreais no presente/futuro: If + simple past, would + verbo. If I had a million dollars, I would travel the world. Com to be, o padrão é were para todas as pessoas: If I were you, I\'d talk to her.',
      'If I lived near the beach, I would surf every day. · What would you do if you won the lottery?',
      'Se fosse assim (mas não é), seria assim.',
      'Conselho: “If I were you, I would study a little every day.”',
      '1. If + passado (imaginação). 2. Vírgula. 3. Would + verbo.',
      'O passado aqui NÃO fala do passado: “If I had time” = se eu tivesse tempo (agora). É o jeito do inglês de mostrar que é imaginário.'),
    block('g_choose', 'Which conditional?',
      'Pergunte: é sempre verdade? → zero. É possível e provável? → first. É imaginário, improvável ou impossível? → second. Compare: If I win the game, I\'ll celebrate (acho possível) × If I won the lottery, I\'d buy a house (improvável).',
      'If I get a good grade, my parents will be happy. · If I could fly, I would go to school by air.',
      'Provável → will. Imaginário → would.',
      'Duas pessoas falando do mesmo prêmio: uma acha que pode ganhar (first), a outra acha impossível (second).',
      '1. Avalie a chance. 2. Escolha o tipo. 3. Confira os tempos verbais das duas partes.',
      'A escolha mostra a OPINIÃO de quem fala: a mesma situação pode ir no first ou no second, dependendo de quanto a pessoa acredita nela.'),
  ],
  questions: [
    mc(1, 'g_zero', 'If you heat ice, it ___.', ['melts', 'will melt', 'would melt', 'melted'], 0, ['É um fato científico.', 'Zero conditional.', 'Presente + presente.'], 'If you heat ice, it melts.'),
    mc(1, 'g_first', 'If it ___ tomorrow, we\'ll stay home.', ['will rain', 'rains', 'rained', 'would rain'], 1, ['First conditional.', 'Depois de if: presente.', 'Nunca will depois de if.'], 'If it rains tomorrow…'),
    fill(1, 'g_second', 'Complete: If I ___ you, I would apologize. (to be)', ['were'], ['Second conditional com to be.', 'Forma usada para todas as pessoas.', 'W-e-r-e.'], 'If I were you…'),
    tf(1, 'g_first', '“If you will study, you will pass” está correto.', false, ['Depois de if…', '…não usamos will.', 'If you study…'], 'Falso: If you study, you\'ll pass.'),
    match(2, 'g_choose', 'Ligue cada frase ao tipo de condicional.', [['If you heat water to 100 °C, it boils.', 'zero'], ['If it rains, I\'ll take an umbrella.', 'first'], ['If I had wings, I would fly.', 'second']], ['Fato sempre verdadeiro.', 'Possível no futuro.', 'Imaginário.'], 'zero · first · second.'),
    mc(2, 'g_second', 'If I ___ a lot of money, I would buy a farm.', ['have', 'had', 'will have', 'would have'], 1, ['Situação imaginária.', 'Second conditional.', 'If + passado.'], 'If I had a lot of money…'),
    mc(2, 'g_first', 'Unless you hurry, you ___ the bus.', ['miss', 'will miss', 'would miss', 'missed'], 1, ['Unless = if not.', 'Futuro provável.', 'Will + verbo.'], 'Unless you hurry, you\'ll miss the bus.'),
    mc(2, 'g_second', 'What ___ you do if you found a wallet on the street?', ['will', 'would', 'do', 'did'], 1, ['Situação imaginária.', 'Pergunta no second.', 'Would.'], 'What would you do if…?'),
    order(3, 'g_first', 'Organize: “Se eu a vir, vou contar para ela.”', ['If', 'I', 'see', 'her,', 'I\'ll', 'tell', 'her'], ['If + presente.', 'Vírgula depois da condição.', 'I\'ll + verbo.'], 'If I see her, I\'ll tell her.'),
    mc(3, 'g_choose', 'Você acha que é praticamente impossível ser convidado para o show. Qual frase combina?', ['If they invite me, I\'ll go.', 'If they invited me, I would go.', 'If they invite me, I go.', 'If they will invite me, I\'ll go.'], 1, ['Quase impossível = imaginário.', 'Second conditional.', 'Past + would.'], 'Improvável → second: If they invited me, I would go.'),
  ],
  review: ['Zero: if + presente, presente (fatos)', 'First: if + presente, will (provável)', 'Second: if + passado, would (imaginário) · If I were you', 'Nunca will logo depois de if'],
  relatedQuestions: ['como usar if em inglês', 'diferença entre first e second conditional', 'por que if I were'],
  equivalentQuestions: eqs(['condicionais em inglês', 'conditionals'], ['quando usar would', 'por que se diz if I were e não if I was', 'o que é first conditional', 'o que é second conditional', 'posso usar will depois de if', 'o que significa unless', 'como dizer se eu fosse você em inglês']),
  commonErrors: ['Usar will depois de if.', 'Usar would nas duas partes (If I would have…).', 'Achar que o passado do second conditional fala do passado.'],
  english: {
    cefr: 'B1', unit: 'b1-u2', order: 1, area: 'grammar', focus: ['grammar', 'speaking', 'writing'],
    vocabulary: [
      v('if', 'se', 'conjunction', 'used to talk about a possible situation', 'If you want, I\'ll help you.', 1),
      v('unless', 'a menos que', 'conjunction', 'except if', 'I won\'t go unless you come too.', 3),
      v('would', 'faria / iria (condicional)', 'verb', 'used for imaginary situations', 'I would travel more.', 2),
      v('lottery', 'loteria', 'noun', 'a game where you can win money by chance', 'What would you do if you won the lottery?', 2),
      v('melt', 'derreter', 'verb', 'to change from solid to liquid', 'Ice melts in the sun.', 2),
      v('advice', 'conselho', 'noun', 'an opinion about what someone should do', 'Can I give you some advice?', 2),
      v('invite', 'convidar', 'verb', 'to ask someone to come to an event', 'If they invite me, I\'ll go.', 1),
    ],
    grammar: {
      name: 'Conditionals (0, 1, 2)', when: 'Fatos, consequências prováveis e situações imaginárias.', structure: '0: if + present, present · 1: if + present, will · 2: if + past, would',
      affirmative: ['If you heat ice, it melts.', 'If it rains, I\'ll stay home.', 'If I had time, I\'d learn guitar.'], negative: ['If you don\'t hurry, you\'ll be late.', 'If I didn\'t have homework, I\'d go out.'], interrogative: ['What will you do if it rains?', 'What would you do if you were invisible?'],
      compare: 'If I win (acho possível) × If I won (acho improvável).', context: 'Dar conselhos: “If I were you, I\'d…”',
    },
    speaking: {
      situation: 'Um amigo pergunta o que você faria em situações imaginárias.', vocabulary: ['would', 'if I were', 'if I had'],
      phrases: ['If I had…, I would…', 'If I were…, I\'d…', 'I would probably…'], example: 'If I had a superpower, I would be invisible. I\'d visit places for free!',
      challenge: 'Responda: What would you do if you won the lottery? (2 ou 3 frases).', expected: ['if', 'would', 'had'],
    },
    writing: {
      prompt: 'Escreva um pequeno texto: “If I could change one thing in my city…” usando second conditional e um first conditional sobre o futuro.', criteria: ['Second conditional (if + past, would)', 'Um first conditional (if + present, will)', 'Conclusão com opinião'],
      model: 'If I could change one thing in my city, I would build more parks. If there were more trees, people would be healthier. If the mayor listens to us, he will plant trees next year.', keywords: ['if', 'would', 'will', 'were'], minWords: 30,
    },
    challenge: 'Dê um conselho em inglês para um colega começando com “If I were you…”.',
  },
  games: {
    blanks: [
      blank(1, 'If you mix red and white, you ___ pink.', ['get', 'will got', 'would got', 'getting'], 0, 'Fato: zero conditional.'),
      blank(1, 'If I see Ana, I ___ her the news.', ['\'ll tell', 'tell', '\'d told', 'told'], 0, 'Provável: will.'),
      blank(2, 'If I ___ taller, I would play basketball.', ['were', 'am', 'will be', 'be'], 0, 'Second: were.'),
      blank(2, 'She would travel more if she ___ more money.', ['had', 'has', 'will have', 'would have'], 0, 'If + passado.'),
      blank(3, 'You won\'t pass ___ you study harder.', ['unless', 'if', 'when', 'because'], 0, 'Unless = a menos que.'),
    ],
    sequences: [words(2, 'If it rains we will stay home', 'First conditional.'), words(3, 'If I were you I would call her', 'Conselho com second conditional.')],
    dialogues: [
      dialogue(2, 'Pedindo conselho', ['Lia: I\'m always tired in class.', 'Téo: If I were you, I\'d go to bed earlier.', 'Lia: That\'s good advice!'], 1, ['If I were you, I\'d go to bed earlier.', 'If I am you, I will go to bed earlier.', 'If I was you, I go to bed.', 'If I were you, I will went to bed.'], 0, 'Conselho: If I were you, I\'d…'),
      dialogue(3, 'Sonhando acordado', ['Max: What would you do if you won a trip?', 'Bia: I would go to Iceland to see the northern lights.', 'Max: Cool! I\'d go to Japan.'], 1, ['I would go to Iceland to see the northern lights.', 'I will go to Iceland.', 'I go to Iceland.', 'I went to Iceland.'], 0, 'Resposta imaginária: would.'),
    ],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 3 · Phrasal verbs ═══════════════════
export const phrasalVerbs = lesson({
  id: 'ing-b1-phrasal-verbs', subject: 'ingles', title: 'Everyday phrasal verbs', levels: [...LV], grade: '9º ano e Ensino Médio',
  topic: 'Inglês B1 — Inglês que soa natural', subtopic: 'Phrasal verbs mais comuns',
  aliases: ['phrasal verbs', 'verbos frasais', 'give up', 'look after', 'look for', 'get up', 'find out', 'turn down', 'lista de phrasal verbs', 'verbo mais preposicao'],
  summary: 'Entenda e use 21 phrasal verbs do dia a dia pelo contexto — sem traduzir palavra por palavra.',
  intro: 'Don\'t give up! Phrasal verbs estão em todo lugar: séries, músicas e conversas.',
  objective: 'Reconhecer o significado de phrasal verbs comuns pelo contexto, usá-los em frases naturais e saber quando o objeto pode ficar no meio.',
  prerequisites: ['ing-a2-simple-past'], next: ['ing-b1-false-friends'],
  skills: { v_what: 'O que é um phrasal verb', v_daily: 'Rotina e relações (get up, get along, look after…)', v_problem: 'Problemas e decisões (give up, figure out, put off…)', g_sep: 'Separáveis e inseparáveis' },
  blocks: [
    block('v_what', 'What is a phrasal verb?',
      'Phrasal verb = verbo + partícula (up, down, out, off, on, after, over…) que forma um sentido NOVO. Look = olhar; look after = cuidar de; look for = procurar; look up = pesquisar (uma palavra). Por isso, traduzir palavra por palavra quase sempre falha: entenda pelo contexto.',
      'Can you look after my dog this weekend? · I\'m looking for my keys.',
      'Verbo + pequena palavra = um significado novo. Look after não é “olhar depois”, é “cuidar”.',
      'Numa série: “I\'ll figure it out” — o personagem vai descobrir/resolver, e não “figurar para fora”.',
      '1. Veja o verbo e a partícula juntos. 2. Leia a frase inteira. 3. Descubra o sentido pelo contexto.',
      'É como no português “dar certo”, “dar em nada”, “dar para trás”: o “dar” muda de sentido com as palavras ao lado.'),
    block('v_daily', 'Routine and relationships',
      'get up (levantar da cama), wake up (acordar), get along (with) (se dar bem com), look after (cuidar de), bring up (criar filhos / mencionar um assunto), carry on (continuar), come across (encontrar por acaso), run into (encontrar alguém por acaso), set up (montar, organizar), take off (decolar / tirar roupa).',
      'I get along well with my cousin. · I ran into my teacher at the mall. · The plane took off at 9.',
      'Get along = se dar bem. Run into = esbarrar com alguém sem esperar.',
      'Contando o dia: “I got up late, ran into Leo on the bus and we carried on talking all the way.”',
      '1. Agrupe por tema: rotina, pessoas, viagens. 2. Crie uma frase sua para cada um. 3. Revise ouvindo músicas e séries.',
      'Come across (algo por acaso: um texto, um vídeo) × run into (alguém por acaso: uma pessoa).'),
    block('v_problem', 'Problems and decisions',
      'give up (desistir), figure out (entender, resolver), find out (descobrir uma informação), look up (procurar num dicionário/internet), look forward to (aguardar com expectativa), put off (adiar), turn down (recusar / abaixar o volume), turn up (aparecer / aumentar o volume), take over (assumir o controle), work out (malhar / dar certo / calcular).',
      'Don\'t give up! · I\'m looking forward to the trip. · She turned down the job offer.',
      'Give up = desistir. Put off = deixar para depois. Find out = descobrir.',
      'Estudos: “I put off my homework, but then I figured out the answers quickly.”',
      '1. Veja o problema na frase. 2. Qual ação resolve ou atrasa? 3. Escolha o phrasal verb.',
      'Look forward to é seguido de -ing: I\'m looking forward to seeing you (e não “to see you”).'),
    block('g_sep', 'Separable or not?',
      'Alguns phrasal verbs aceitam o objeto no meio (separáveis): turn down the music / turn the music down. Se o objeto for pronome, ele DEVE ficar no meio: turn it down (nunca “turn down it”). Outros não se separam: look after the baby / look after her.',
      'Please turn it off. · Can you look after them?',
      'Com pronome (it, them, her), ele vai no meio: pick it up, turn it off.',
      'Pedindo: “The TV is loud. Can you turn it down?”',
      '1. O objeto é um pronome? 2. Se o verbo for separável, coloque o pronome no meio. 3. Na dúvida, consulte um dicionário: ele mostra “sth” no meio ou no fim.',
      'Nos dicionários, “turn sth down” indica separável; “look after sb” indica que o objeto vem depois.'),
  ],
  questions: [
    mc(1, 'v_problem', '“Don\'t give up!” significa:', ['Não desista!', 'Não levante!', 'Não entregue!', 'Não suba!'], 0, ['Alguém está quase parando de tentar.', 'É um incentivo.', 'Desistir.'], 'Give up = desistir.'),
    mc(1, 'v_daily', 'Can you ___ my cat while I travel?', ['look for', 'look after', 'look up', 'look forward'], 1, ['Alguém vai viajar.', 'O gato precisa de cuidados.', 'Cuidar de = look after.'], 'Look after = cuidar de.'),
    fill(1, 'v_problem', 'Complete: I don\'t know this word. I\'ll look it ___ in the dictionary.', ['up'], ['Pesquisar uma palavra.', 'Look + …', 'Up.'], 'Look it up = pesquisar.'),
    tf(1, 'v_what', 'Phrasal verbs podem ser traduzidos palavra por palavra.', false, ['Pense em look after.', '“Olhar depois”?', 'O sentido muda.'], 'Falso: o sentido é novo e depende do contexto.'),
    match(2, 'v_problem', 'Ligue o phrasal verb ao significado.', [['find out', 'descobrir'], ['put off', 'adiar'], ['turn down', 'recusar'], ['work out', 'malhar / dar certo']], ['Find = achar.', 'Off = para longe (no tempo).', 'Down = para baixo (dizer não).'], 'find out descobrir · put off adiar · turn down recusar · work out malhar/dar certo.'),
    mc(2, 'v_daily', 'I ___ my old teacher at the supermarket yesterday. What a surprise!', ['ran into', 'looked for', 'set up', 'took over'], 0, ['Encontro por acaso.', 'Com uma pessoa.', 'Run into.'], 'Run into = encontrar alguém por acaso.'),
    mc(2, 'g_sep', 'The music is too loud. Please ___.', ['turn down it', 'turn it down', 'turn it up down', 'down turn it'], 1, ['Pronome it.', 'Pronome vai no meio.', 'Turn it down.'], 'Turn it down.'),
    mc(2, 'v_problem', 'I\'m looking forward ___ you next week!', ['to see', 'to seeing', 'see', 'seeing to'], 1, ['Look forward to + …', 'Depois de to aqui vem -ing.', 'To seeing.'], 'Looking forward to seeing you.'),
    order(3, 'v_daily', 'Organize a rotina de viagem na ordem lógica.', ['I woke up at 5.', 'I got up and packed my bag.', 'I set off for the airport.', 'The plane took off at 8.'], ['Primeiro acordar.', 'Depois levantar e arrumar.', 'O avião decola por último.'], 'woke up → got up → set off → took off.'),
    mc(3, 'v_problem', '“We had some problems, but in the end everything worked out.” Qual é o sentido?', ['Tudo foi para a academia', 'No fim, tudo deu certo', 'Tudo foi calculado', 'Tudo saiu de casa'], 1, ['Houve problemas…', '“in the end” = no final.', 'Work out = dar certo.'], 'Work out aqui = dar certo.'),
  ],
  review: ['Verbo + partícula = sentido novo (entenda pelo contexto)', 'get up, get along, look after, run into, carry on, set up, take off', 'give up, figure out, find out, look up, put off, turn down/up, work out', 'Pronome no meio dos separáveis: turn it down'],
  relatedQuestions: ['o que são phrasal verbs', 'lista de phrasal verbs mais usados', 'o que significa give up'],
  equivalentQuestions: eqs(['phrasal verbs', 'verbos frasais'], ['o que significa look after', 'diferença entre look for e look up', 'o que significa figure out', 'o que é run into', 'por que é looking forward to seeing', 'o que significa put off', 'turn down it ou turn it down', 'como aprender phrasal verbs']),
  commonErrors: ['Traduzir palavra por palavra.', 'Colocar o pronome depois da partícula (turn off it).', 'Usar infinitivo depois de look forward to (to see).'],
  english: {
    cefr: 'B1', unit: 'b1-u3', order: 1, area: 'vocabulary', focus: ['vocabulary', 'reading', 'listening'],
    vocabulary: [
      v('get up', 'levantar (da cama)', 'phrasal verb', 'to leave your bed after sleeping', 'I get up at seven.', 1, { related: ['wake up'] }),
      v('get along', 'se dar bem', 'phrasal verb', 'to have a friendly relationship', 'I get along with my sister.', 2),
      v('give up', 'desistir', 'phrasal verb', 'to stop trying', 'Never give up on your dreams.', 1),
      v('look after', 'cuidar de', 'phrasal verb', 'to take care of', 'She looks after her grandma.', 1, { synonyms: ['take care of'] }),
      v('look for', 'procurar', 'phrasal verb', 'to try to find', 'I\'m looking for my phone.', 1),
      v('look forward to', 'aguardar ansiosamente', 'phrasal verb', 'to feel happy about something that will happen', 'I\'m looking forward to the holidays.', 3),
      v('put off', 'adiar', 'phrasal verb', 'to do something later than planned', 'Don\'t put off your homework.', 2, { synonyms: ['postpone'] }),
      v('turn down', 'recusar / abaixar', 'phrasal verb', 'to say no to an offer; to make quieter', 'He turned down the invitation.', 2),
      v('find out', 'descobrir', 'phrasal verb', 'to get information about something', 'I found out the truth.', 2),
      v('figure out', 'entender / resolver', 'phrasal verb', 'to understand or solve after thinking', 'I can\'t figure out this problem.', 2),
      v('run into', 'encontrar por acaso', 'phrasal verb', 'to meet someone by chance', 'I ran into Leo at the mall.', 2),
      v('come across', 'deparar-se com', 'phrasal verb', 'to find something by chance', 'I came across an old photo.', 3),
      v('carry on', 'continuar', 'phrasal verb', 'to continue', 'Carry on, you\'re doing great!', 2),
      v('set up', 'montar / organizar', 'phrasal verb', 'to prepare or start something', 'We set up a study group.', 2),
      v('take off', 'decolar / tirar (roupa)', 'phrasal verb', 'when a plane leaves the ground; to remove clothes', 'Take off your shoes, please.', 2),
      v('take over', 'assumir o controle', 'phrasal verb', 'to take control of something', 'A new manager took over the team.', 3),
      v('turn up', 'aparecer / aumentar o volume', 'phrasal verb', 'to arrive, often unexpectedly; to make louder', 'He turned up late.', 3),
      v('work out', 'malhar / dar certo', 'phrasal verb', 'to exercise; to end well', 'Everything worked out fine.', 2),
      v('bring up', 'criar (filhos) / mencionar', 'phrasal verb', 'to raise a child; to mention a subject', 'She brought up an interesting point.', 3),
      v('look up', 'pesquisar (palavra)', 'phrasal verb', 'to search for information', 'Look it up online.', 2),
      v('wake up', 'acordar', 'phrasal verb', 'to stop sleeping', 'I woke up late today.', 1),
    ],
    reading: {
      title: 'Messages from a group chat', genre: 'conversa de grupo',
      text: 'Ana: Guys, I found out the concert is on Saturday!\nLeo: Awesome! I\'m looking forward to it.\nBia: I can\'t go 😢 I have to look after my little brother.\nLeo: Don\'t give up yet! Maybe your aunt can help?\nBia: Good idea, I\'ll ask her. If it works out, I\'ll go!\nAna: Let\'s set up a meeting point near the entrance.',
      questions: [
        mci(1, 'O que Ana descobriu?', ['Que o show foi cancelado', 'Que o show é no sábado', 'Que Bia não vai', 'Que o ingresso acabou'], 1, '“I found out the concert is on Saturday!”'),
        mci(2, 'Por que Bia não pode ir, a princípio?', ['Porque vai trabalhar', 'Porque precisa cuidar do irmão', 'Porque está doente', 'Porque não gosta da banda'], 1, '“I have to look after my little brother.”'),
        mci(2, 'O que Leo quer dizer com “Don\'t give up yet”?', ['Não desista ainda', 'Não levante ainda', 'Não entregue ainda', 'Não saia ainda'], 0, 'Give up = desistir.'),
        mci(3, 'O que Ana propõe no final?', ['Adiar o show', 'Combinar um ponto de encontro', 'Comprar ingressos', 'Cuidar do irmão de Bia'], 1, '“set up a meeting point” = combinar um ponto de encontro.'),
      ],
    },
    listening: {
      title: 'Voice message', kind: 'texto', rate: 0.92,
      script: ['Hey, it\'s me. Sorry, I have to put off our study session.', 'My mom asked me to look after my grandpa this afternoon.', 'Can we carry on tomorrow? I still can\'t figure out exercise five.', 'Call me back when you get this!'],
      questions: [
        mci(1, 'O que a pessoa precisa fazer com o encontro de estudos?', ['Cancelar para sempre', 'Adiar', 'Antecipar', 'Mudar de lugar'], 1, 'Put off = adiar.'),
        mci(2, 'Por quê?', ['Vai malhar', 'Vai cuidar do avô', 'Vai viajar', 'Esqueceu'], 1, '“look after my grandpa”.'),
        mci(3, 'Qual é a dificuldade dela?', ['Não entende o exercício 5', 'Perdeu o caderno', 'Não achou o livro', 'Não sabe o horário'], 0, '“I still can\'t figure out exercise five.”'),
      ],
    },
    challenge: 'Escolha 5 phrasal verbs desta aula e escreva uma frase verdadeira sobre a sua vida com cada um.',
    tips: ['Aprenda phrasal verbs em frases, não em listas soltas.', 'Quando ouvir um numa série, pause e tente adivinhar o sentido pelo contexto.'],
  },
  games: {
    blanks: [
      blank(1, 'I\'m ___ my glasses. Have you seen them?', ['looking for', 'looking after', 'looking up', 'giving up'], 0, 'Procurar: look for.'),
      blank(1, 'She never ___. She always tries again.', ['gives up', 'gets up', 'turns up', 'takes off'], 0, 'Desistir: give up.'),
      blank(2, 'We need to ___ the meeting until next week.', ['put off', 'put on', 'turn up', 'run into'], 0, 'Adiar: put off.'),
      blank(2, 'I ___ an interesting article about space.', ['came across', 'looked after', 'got along', 'took over'], 0, 'Encontrar algo por acaso: come across.'),
      blank(3, 'He was offered a job in Canada, but he ___ it ___.', ['turned / down', 'turned / up', 'took / off', 'looked / after'], 0, 'Recusar: turn it down.'),
      blank(3, 'Do you ___ with your neighbors?', ['get along', 'get up', 'set up', 'carry on'], 0, 'Se dar bem: get along.'),
    ],
    sequences: [words(2, 'Please turn it down', 'Pronome no meio do phrasal verb separável.'), words(3, 'I am looking forward to seeing you', 'Look forward to + -ing.')],
  },
  sources: enSources(),
})

// ═══════════════════ Unidade 4 · Words that play tricks ═══════════════════
export const falseFriends = lesson({
  id: 'ing-b1-false-friends', subject: 'ingles', title: 'False friends', levels: [...LV], grade: '8º ano ao Ensino Médio',
  topic: 'Inglês B1 — Inglês que soa natural', subtopic: 'Falsos cognatos',
  aliases: ['false friends', 'falsos cognatos', 'falso cognato', 'actually significa', 'pretend significa', 'push significa', 'parents significa', 'library significa', 'cognatos em ingles'],
  summary: 'Evite as armadilhas: palavras parecidas com o português que significam outra coisa.',
  intro: 'Actually, “actually” não quer dizer “atualmente”! Vamos desarmar as armadilhas.',
  objective: 'Identificar os falsos cognatos mais comuns, dizer o significado real de cada um e escolher a palavra certa para o que se quer dizer.',
  prerequisites: ['ing-a1-family'], next: ['ing-b1-collocations'],
  skills: { v_what: 'O que são falsos cognatos', v_common: 'Os mais comuns (actually, pretend, push…)', v_school: 'Escola e vida (college, library, lecture…)', v_choose: 'Escolher a palavra certa' },
  blocks: [
    block('v_what', 'What are false friends?',
      'Cognatos são palavras parecidas nas duas línguas e com o mesmo sentido (hospital, animal, important). Falsos cognatos (false friends) parecem iguais, mas significam OUTRA coisa: pretend não é “pretender”, é “fingir”. Eles causam mal-entendidos em conversas e em provas.',
      'I pretend to be sick = eu finjo estar doente (e não “pretendo”).',
      'Palavra parecida com o português, mas com outro significado.',
      'Numa prova do ENEM, “eventually” pode mudar todo o sentido da frase: não é “eventualmente”, é “no fim das contas”.',
      '1. Desconfie de palavras “fáceis demais”. 2. Leia o contexto. 3. Confirme no dicionário.',
      'Cognato verdadeiro: hospital = hospital. Falso cognato: exquisite = requintado (e não “esquisito”).'),
    block('v_common', 'The most common traps',
      'actually = na verdade (atualmente = currently/nowadays) · pretend = fingir (pretender = intend) · push = empurrar (puxar = pull) · eventually = no fim, finalmente (eventualmente = occasionally) · sensible = sensato (sensível = sensitive) · realize = perceber (realizar = achieve/carry out) · attend = frequentar/comparecer (atender = answer/serve) · lunch = almoço (lanche = snack).',
      'Actually, I don\'t agree. · Push the door, don\'t pull! · She realized she was wrong.',
      'Actually = na verdade. Push = empurrar. Realize = perceber.',
      'Na porta de uma loja: PUSH (empurre). O brasileiro distraído puxa!',
      '1. Leia a palavra. 2. Lembre o significado REAL. 3. Pense na palavra que você realmente queria.',
      'Se quiser dizer “atualmente”, use currently ou nowadays. Actually serve para corrigir ou contrastar: “Actually, it\'s Tuesday.”'),
    block('v_school', 'School, work and family traps',
      'college = faculdade (colégio = school) · library = biblioteca (livraria = bookstore) · lecture = palestra/aula expositiva (leitura = reading) · parents = pais (parentes = relatives) · comprehensive = abrangente, completo (compreensivo = understanding) · exquisite = requintado (esquisito = weird) · fabric = tecido (fábrica = factory) · costume = fantasia (costume = habit).',
      'My sister is in college. · I bought a costume for the party.',
      'College = faculdade. Library = biblioteca. Costume = fantasia.',
      'Currículo em inglês: “I attended a lecture about robots” = assisti a uma palestra.',
      '1. Lembre o par: palavra inglesa → sentido real. 2. Crie uma frase-âncora. 3. Revise com o jogo da memória.',
      'Costume em inglês é a fantasia de festa; o nosso “costume” (hábito) em inglês é habit.'),
    block('v_choose', 'Choosing the right word',
      'Na hora de falar ou escrever, parta do que você quer dizer em português e escolha a palavra certa: “Eu pretendo viajar” → I intend to / I\'m planning to travel. “Ele é muito sensível” → He\'s very sensitive. “Atualmente moro em Natal” → Currently, I live in Natal. “Realizei um sonho” → I achieved / made a dream come true.',
      'I intend to study abroad. · She\'s sensitive, so be kind.',
      'Não use a palavra parecida por instinto: pense no significado.',
      'Mensagem para um professor estrangeiro: “Currently I\'m in 9th grade and I intend to study engineering.”',
      '1. O que quero dizer? 2. A palavra parecida é falso cognato? 3. Troque pela certa.',
      'Nem toda palavra parecida é armadilha: important, family, animal são cognatos verdadeiros. O truque é conhecer a lista das armadilhas.'),
  ],
  questions: [
    mc(1, 'v_common', '“Actually” significa:', ['atualmente', 'na verdade', 'rapidamente', 'finalmente'], 1, ['Falso cognato.', 'Usado para corrigir algo.', 'Na verdade.'], 'Actually = na verdade.'),
    mc(1, 'v_common', 'Na porta está escrito “PUSH”. Você deve:', ['puxar', 'empurrar', 'tocar', 'esperar'], 1, ['Push ≠ puxar.', 'Puxar = pull.', 'Empurrar.'], 'Push = empurrar.'),
    fill(1, 'v_school', 'Como se diz “livraria” (loja de livros) em inglês?', ['bookstore', 'bookshop'], ['Não é library.', 'Book + loja.', 'Book…'], 'Livraria = bookstore/bookshop; library = biblioteca.'),
    tf(1, 'v_school', '“Parents” significa “parentes”.', false, ['Falso cognato.', 'São duas pessoas.', 'Pai e mãe.'], 'Falso: parents = pais; parentes = relatives.'),
    match(2, 'v_common', 'Ligue o falso cognato ao significado real.', [['pretend', 'fingir'], ['realize', 'perceber'], ['eventually', 'no fim'], ['sensible', 'sensato']], ['Pretend ≠ pretender.', 'Realize ≠ realizar.', 'Sensible ≠ sensível.'], 'pretend fingir · realize perceber · eventually no fim · sensible sensato.'),
    mc(2, 'v_choose', 'Como dizer “Atualmente eu moro em Natal”?', ['Actually I live in Natal.', 'Currently I live in Natal.', 'Actual I live in Natal.', 'Eventually I live in Natal.'], 1, ['Actually é armadilha.', 'Atualmente = …', 'Currently.'], 'Currently / nowadays = atualmente.'),
    mc(2, 'v_school', '“My brother is in college” significa:', ['Meu irmão está no colégio.', 'Meu irmão está na faculdade.', 'Meu irmão está na biblioteca.', 'Meu irmão está na escola primária.'], 1, ['College é falso cognato.', 'Colégio = school.', 'Faculdade.'], 'College = faculdade.'),
    mc(2, 'v_common', '“He pretended to be asleep.” Ele:', ['pretendia dormir', 'fingiu estar dormindo', 'conseguiu dormir', 'dormiu cedo'], 1, ['Pretend = …', 'Não é pretender.', 'Fingir.'], 'Pretend = fingir.'),
    order(3, 'v_choose', 'Organize: “Eu pretendo estudar no exterior.”', ['I', 'intend', 'to', 'study', 'abroad'], ['Pretender = intend.', 'Intend to + verbo.', 'Abroad no final.'], 'I intend to study abroad.'),
    mc(3, 'v_common', '“After many attempts, she eventually passed the exam.” O sentido é:', ['Ela passou de vez em quando.', 'Ela eventualmente passaria.', 'Depois de muitas tentativas, ela finalmente passou.', 'Ela nunca passou.'], 2, ['Eventually é falso cognato.', 'Veja “after many attempts”.', 'Finalmente / no fim.'], 'Eventually = finalmente, no fim.'),
  ],
  review: ['actually = na verdade · currently = atualmente', 'pretend fingir · realize perceber · push empurrar · eventually no fim', 'college faculdade · library biblioteca · parents pais · costume fantasia', 'Pense no sentido, não na aparência da palavra'],
  relatedQuestions: ['o que são falsos cognatos', 'lista de falsos cognatos em inglês', 'actually significa atualmente'],
  equivalentQuestions: eqs(['falsos cognatos', 'false friends'], ['o que significa pretend', 'push é puxar ou empurrar', 'o que significa eventually', 'college é colégio', 'library é livraria', 'o que significa realize', 'o que significa sensible', 'como dizer atualmente em inglês', 'o que significa costume em inglês']),
  commonErrors: ['Usar actually como “atualmente”.', 'Dizer “I pretend to travel” querendo dizer “pretendo viajar”.', 'Confundir library (biblioteca) com livraria.'],
  english: {
    cefr: 'B1', unit: 'b1-u4', order: 1, area: 'vocabulary', focus: ['vocabulary', 'reading'],
    vocabulary: [
      v('actually', 'na verdade', 'adverb', 'in fact; used to correct or add information', 'Actually, I\'m not hungry.', 2, { related: ['currently'] }),
      v('currently', 'atualmente', 'adverb', 'at the present time', 'I\'m currently in 9th grade.', 2, { synonyms: ['nowadays'] }),
      v('pretend', 'fingir', 'verb', 'to act as if something is true when it is not', 'He pretended to be sick.', 2, { related: ['intend'] }),
      v('intend', 'pretender, ter a intenção', 'verb', 'to plan to do something', 'I intend to study medicine.', 3),
      v('push', 'empurrar', 'verb', 'to move something away from you', 'Push the door.', 1, { antonyms: ['pull'] }),
      v('pull', 'puxar', 'verb', 'to move something toward you', 'Pull the rope.', 1, { antonyms: ['push'] }),
      v('realize', 'perceber', 'verb', 'to understand something suddenly', 'I realized I was late.', 2),
      v('eventually', 'finalmente, no fim', 'adverb', 'after a long time', 'We eventually found the keys.', 3),
      v('sensible', 'sensato', 'adjective', 'showing good judgment', 'That\'s a sensible decision.', 3, { related: ['sensitive'] }),
      v('sensitive', 'sensível', 'adjective', 'easily hurt or affected', 'My skin is very sensitive.', 3),
      v('college', 'faculdade', 'noun', 'a place for studies after high school', 'She goes to college in Porto Alegre.', 2),
      v('costume', 'fantasia', 'noun', 'clothes worn to look like someone else', 'He wore a pirate costume.', 3, { related: ['habit'] }),
      v('relatives', 'parentes', 'noun', 'people in your family', 'All my relatives came to the party.', 2),
      v('lecture', 'palestra', 'noun', 'a talk to teach people about a subject', 'We attended a lecture about space.', 3),
    ],
    reading: {
      title: 'Lost in translation', genre: 'relato',
      text: 'On my first day in London, I wanted to buy a book, so I asked for the library. A kind woman sent me to a building full of people reading quietly — I had to borrow a book instead of buying one! Later, I told my host family that I “pretended” to visit Oxford. They looked confused. Actually, I meant that I intended to go. Eventually, I realized that some words are traps.',
      questions: [
        mci(1, 'Aonde a mulher mandou o autor?', ['A uma livraria', 'A uma biblioteca', 'A uma faculdade', 'A um museu'], 1, 'Library = biblioteca.'),
        mci(2, 'Por que a família ficou confusa?', ['Porque ele disse que fingiu visitar Oxford', 'Porque ele não visitou Oxford', 'Porque ele falou português', 'Porque Oxford é longe'], 0, 'Pretend = fingir; ele queria dizer intend.'),
        mci(3, 'Qual é a ideia principal do texto?', ['Londres é cara', 'Falsos cognatos podem causar mal-entendidos', 'Bibliotecas são silenciosas', 'Oxford é uma cidade bonita'], 1, 'O autor conta os mal-entendidos causados por falsos cognatos.'),
      ],
    },
    challenge: 'Crie uma frase-armadilha para um colega: use um falso cognato e veja se ele descobre o sentido real.',
    tips: ['Desconfie das palavras que parecem fáceis demais.', 'Monte um caderno de “armadilhas” com a palavra, o sentido real e uma frase.'],
  },
  games: {
    blanks: [
      blank(1, '___ the door to open it. (empurre)', ['Push', 'Pull', 'Press', 'Put'], 0, 'Empurrar = push.'),
      blank(2, '___, I think you\'re right. (na verdade)', ['Actually', 'Currently', 'Eventually', 'Nowadays'], 0, 'Na verdade = actually.'),
      blank(2, 'I ___ to be a doctor one day. (pretendo)', ['intend', 'pretend', 'attend', 'realize'], 0, 'Pretender = intend.'),
      blank(3, 'She suddenly ___ that she had left her phone at home. (percebeu)', ['realized', 'realized out', 'achieved', 'pretended'], 0, 'Perceber = realize.'),
      blank(3, 'Be careful with your words: he\'s very ___. (sensível)', ['sensitive', 'sensible', 'sensual', 'sense'], 0, 'Sensível = sensitive.'),
    ],
    sequences: [words(2, 'Currently I live in Natal', 'Atualmente = currently.')],
  },
  sources: enSources(),
})

export const collocations = lesson({
  id: 'ing-b1-collocations', subject: 'ingles', title: 'Collocations', levels: [...LV], grade: '9º ano e Ensino Médio',
  topic: 'Inglês B1 — Inglês que soa natural', subtopic: 'Combinações naturais de palavras',
  aliases: ['collocations', 'colocacoes em ingles', 'make ou do', 'make a decision', 'do homework', 'take a photo', 'heavy rain', 'combinacoes de palavras'],
  summary: 'Descubra quais palavras “andam juntas” em inglês: make × do, take, pay, heavy, strong e highly.',
  intro: 'Por que “make a decision” e não “do a decision”? Vamos soar natural.',
  objective: 'Usar collocations frequentes com make, do, take e pay e combinações adjetivo + substantivo e advérbio + adjetivo, entendendo por que soam naturais.',
  prerequisites: ['ing-b1-false-friends'], next: ['ing-b1-past-perfect'],
  skills: { v_what: 'O que é collocation', v_makedo: 'Make × do', v_takepay: 'Take, pay, have', v_adj: 'Adjetivo + substantivo e advérbio + adjetivo' },
  blocks: [
    block('v_what', 'What is a collocation?',
      'Collocation é uma combinação de palavras que os falantes usam juntas com frequência. Não é uma regra lógica: é costume da língua. Dizemos heavy rain (chuva forte), e não “strong rain”, e make a mistake (cometer um erro), e não “do a mistake”. Conhecer collocations faz o inglês soar natural.',
      'fast food (e não “quick food”) · a quick shower (e não “a fast shower”)',
      'Palavras que “andam juntas”. É o jeito que o nativo fala.',
      'Em português falamos “tomar banho” e não “pegar banho”. Em inglês: take a shower.',
      '1. Aprenda a expressão inteira, não a palavra solta. 2. Anote em blocos: make a decision. 3. Repare nelas em textos e séries.',
      'Como no português “escovar os dentes” (e não “limpar os dentes com escova”): é o costume que decide.'),
    block('v_makedo', 'Make or do?',
      'Make costuma indicar criar, produzir: make a decision, make a mistake, make progress, make a plan, make noise, make friends, make money, make an effort. Do costuma indicar tarefas e atividades: do homework, do the dishes, do exercise, do a favor, do your best, do business, do research.',
      'I made a mistake on the test. · Can you do me a favor? · I do my homework after lunch.',
      'Make = criar/fazer algo novo. Do = realizar uma tarefa.',
      'Sábado em casa: “I did the dishes, made a cake and made plans with my friends.”',
      '1. É criar algo novo? make. 2. É cumprir uma tarefa/atividade? do. 3. Na dúvida, memorize a expressão.',
      'As duas viram “fazer” em português. A diferença está no tipo de ação: make a cake (criar) × do the cooking (tarefa).'),
    block('v_takepay', 'Take, pay and have',
      'Take: take a photo (tirar foto), take a shower, take a break (fazer uma pausa), take responsibility (assumir a responsabilidade), take notes, take a test. Pay: pay attention (prestar atenção), pay a visit (fazer uma visita), pay a compliment (fazer um elogio). Have: have lunch, have fun, have a good time.',
      'Please pay attention. · Let\'s take a break. · We had fun at the party.',
      'Take a photo = tirar foto. Pay attention = prestar atenção.',
      'Professor: “Take notes and pay attention to the examples.”',
      '1. Veja o substantivo. 2. Lembre o verbo que o acompanha. 3. Pratique em frases suas.',
      'Em português: “prestar atenção”; em inglês: PAY attention — como se a atenção fosse um pagamento.'),
    block('v_adj', 'Adjective + noun, adverb + adjective',
      'Adjetivo + substantivo: heavy rain / heavy traffic (forte, intenso), strong coffee / strong argument, high price, deep sleep, close friend (amigo próximo). Advérbio + adjetivo: highly recommended (altamente recomendado), deeply sorry, bitterly cold, fully aware (totalmente ciente).',
      'There was heavy traffic this morning. · This book is highly recommended.',
      'Heavy rain = chuva forte. Close friend = amigo próximo.',
      'Resenha: “The movie is highly recommended, with a strong story.”',
      '1. Para intensidade de fenômenos: heavy. 2. Para café/argumento: strong. 3. Para recomendação: highly.',
      '“Strong” e “heavy” podem ser “forte” em português, mas não são trocáveis: strong coffee × heavy rain.'),
  ],
  questions: [
    mc(1, 'v_makedo', 'I need to ___ a decision.', ['do', 'make', 'take', 'have'], 1, ['Decisão = algo que você cria.', 'Collocation fixa.', 'Make a decision.'], 'Make a decision.'),
    mc(1, 'v_makedo', 'Did you ___ your homework?', ['make', 'do', 'take', 'pay'], 1, ['Homework é uma tarefa.', 'Tarefas usam…', 'Do.'], 'Do your homework.'),
    fill(1, 'v_takepay', 'Complete: Please ___ attention to the teacher.', ['pay'], ['Prestar atenção.', 'É como pagar.', 'P-a-y.'], 'Pay attention.'),
    tf(1, 'v_adj', '“Strong rain” é a forma mais natural para “chuva forte”.', false, ['Para chuva usamos outro adjetivo.', 'O mesmo de heavy traffic.', 'Heavy rain.'], 'Falso: heavy rain.'),
    match(2, 'v_takepay', 'Ligue as collocations aos significados.', [['take a photo', 'tirar uma foto'], ['take a break', 'fazer uma pausa'], ['have fun', 'se divertir'], ['pay a visit', 'fazer uma visita']], ['Take = tirar/pegar.', 'Break = intervalo.', 'Fun = diversão.'], 'take a photo · take a break · have fun · pay a visit.'),
    mc(2, 'v_makedo', 'Qual está correta?', ['do a mistake', 'make a mistake', 'take a mistake', 'have a mistake'], 1, ['Erro = algo que você cria.', 'Make…', 'Make a mistake.'], 'Make a mistake.'),
    mc(2, 'v_adj', 'Hotel review: “The staff was friendly. Highly ___!”', ['recommended', 'recommend', 'good', 'cheap'], 0, ['Advérbio + adjetivo.', 'Altamente recomendado.', 'Recommended.'], 'Highly recommended.'),
    mc(2, 'v_takepay', 'The manager must ___ responsibility for the problem.', ['make', 'do', 'take', 'pay'], 2, ['Assumir a responsabilidade.', 'Take…', 'Take responsibility.'], 'Take responsibility.'),
    order(3, 'v_makedo', 'Organize: “Ela está progredindo muito no inglês.”', ['She', 'is', 'making', 'great', 'progress', 'in', 'English'], ['Progress usa make.', 'Present continuous.', 'Great antes de progress.'], 'She is making great progress in English.'),
    mc(3, 'v_adj', 'Escolha a combinação mais natural: “We had a ___ argument about the project, but we are still ___ friends.”', ['heavy / near', 'strong / close', 'high / deep', 'big / next'], 1, ['Argumento forte: strong.', 'Amigo próximo: close.', 'Strong / close.'], 'strong argument · close friends.'),
  ],
  review: ['Collocation = palavras que andam juntas (costume da língua)', 'make: decision, mistake, progress, friends · do: homework, the dishes, a favor', 'take a photo/break/responsibility · pay attention', 'heavy rain · strong coffee · close friend · highly recommended'],
  relatedQuestions: ['o que são collocations', 'diferença entre make e do', 'como falar inglês natural'],
  equivalentQuestions: eqs(['collocations', 'make e do'], ['quando usar make e quando usar do', 'como se diz tomar uma decisão em inglês', 'como dizer prestar atenção em inglês', 'por que é heavy rain', 'o que significa highly recommended', 'como se diz tirar foto em inglês', 'do homework ou make homework']),
  commonErrors: ['Do a mistake / make homework.', 'Strong rain / heavy coffee.', 'Traduzir “tirar foto” como “remove a photo”.'],
  english: {
    cefr: 'B1', unit: 'b1-u4', order: 2, area: 'vocabulary', focus: ['vocabulary', 'writing'],
    vocabulary: [
      v('make a decision', 'tomar uma decisão', 'phrase', 'to decide something', 'It\'s time to make a decision.', 1),
      v('make a mistake', 'cometer um erro', 'phrase', 'to do something wrong', 'Everybody makes mistakes.', 1),
      v('make progress', 'progredir', 'phrase', 'to improve over time', 'You\'re making progress!', 2),
      v('do homework', 'fazer a lição de casa', 'phrase', 'to complete school tasks at home', 'I do my homework at night.', 1),
      v('do a favor', 'fazer um favor', 'phrase', 'to help someone', 'Can you do me a favor?', 2),
      v('take a break', 'fazer uma pausa', 'phrase', 'to stop for a short rest', 'Let\'s take a break.', 1),
      v('take responsibility', 'assumir a responsabilidade', 'phrase', 'to accept that you must deal with something', 'He took responsibility for the error.', 3),
      v('pay attention', 'prestar atenção', 'phrase', 'to watch or listen carefully', 'Pay attention to the details.', 1),
      v('heavy rain', 'chuva forte', 'phrase', 'a lot of rain', 'Heavy rain is expected tonight.', 2),
      v('strong argument', 'argumento forte', 'phrase', 'a reason that convinces people', 'She has a strong argument.', 3),
      v('highly recommended', 'altamente recomendado', 'phrase', 'praised a lot', 'This book is highly recommended.', 2),
      v('close friend', 'amigo próximo', 'phrase', 'a friend you know very well', 'Lia is my close friend.', 2),
    ],
    writing: {
      prompt: 'Escreva uma resenha curta de um filme, série ou jogo usando pelo menos 4 collocations desta aula.', criteria: ['4 collocations corretas', 'Opinião clara', 'Recomendação no final'],
      model: 'I watched a series about a detective. He makes a lot of mistakes, but he takes responsibility and makes progress in every episode. Pay attention to the last episode! Highly recommended.', keywords: ['make', 'take', 'pay', 'highly'], minWords: 30,
    },
    challenge: 'Durante um dia, anote 5 collocations que você ouvir ou ler em inglês (música, jogo, série).',
    tips: ['Aprenda a combinação inteira: “make a decision”, não só “decision”.', 'Dicionários de collocations mostram quais palavras costumam andar juntas.'],
  },
  games: {
    blanks: [
      blank(1, 'Can you ___ me a favor?', ['do', 'make', 'take', 'pay'], 0, 'Do a favor.'),
      blank(1, 'Let\'s ___ a photo!', ['take', 'make', 'do', 'have'], 0, 'Take a photo.'),
      blank(2, 'There was ___ traffic on the way to school.', ['heavy', 'strong', 'big', 'high'], 0, 'Heavy traffic.'),
      blank(2, 'I always ___ the dishes after dinner.', ['do', 'make', 'take', 'have'], 0, 'Do the dishes.'),
      blank(3, 'We are ___ aware of the risks.', ['fully', 'heavily', 'strongly', 'highly done'], 0, 'Fully aware = totalmente ciente.'),
    ],
    pairs: [{ a: 'make', b: 'a decision', difficulty: 1 }, { a: 'do', b: 'homework', difficulty: 1 }, { a: 'take', b: 'a break', difficulty: 1 }, { a: 'pay', b: 'attention', difficulty: 1 }],
    sequences: [words(2, 'I made a mistake on the test', 'Make a mistake.')],
  },
  sources: enSources(),
})
