import { block, fill, lesson, mc, tf } from '../dsl'
const F: any[] = []

export const itA2 = lesson({id:'it-a2',subject:'italiano',title:'Italiano A2',levels:['medio'],grade:'7º',topic:'Italiano A2',subtopic:'Intermédiaire',aliases:['italiano','a2','intermédiaire'],summary:'A2: conversazioni semplici.',intro:'Parlare correntemente.',objective:'Italiano A2.',next:[],skills:{i:'It'},blocks:[block('i','A2','Passato prossimo. Imperfetto. Passato remoto. Futuro semplice. Descrizioni passate. Abitudini. Eventi.','-Tempi variati.','Narrativa.','Miglioramento.','1. Qual tempo?'),],questions:[mc(1,'i','Passato?',['prossimo','remoto','semplice'],0,['Avere/essere.','Participio.','Recente']),tf(1,'i','Imperfetto: abitudini',true,['Sì.','Ripetizione','Passato']),fill(1,'i','Futuro semplice: ___+azione.',['domani'],['Domani.','Futuro','Programmato']),],review:['Tempi variati','Narrativa','Conversazioni','Eventi'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const itB1 = lesson({id:'it-b1',subject:'italiano',title:'Italiano B1',levels:['medio'],grade:'8º',topic:'Italiano B1',subtopic:'Indipendente',aliases:['italiano','b1','indipendente'],summary:'B1: independent speaker.',intro:'Parlare con fiducia.',objective:'Italiano B1.',next:[],skills:{i:'It'},blocks:[block('i','B1','Congiuntivo. Condizionale. Discorso indiretto. Argomenti. Opinioni. Dibattiti. Sfumature.','-Strutture complesse.','Argomenti.','Dibattiti.','1. Che struttura?'),],questions:[mc(1,'i','Congiuntivo dopo?',['paura','credenza','desiderio'],2,['Credere.','Dubitare.','Volere']),tf(1,'i','Condizionale: ipotesi',true,['Sì.','Se.','Possibile']),fill(1,'i','Discorso indiretto: lei dice che ___.',['lei'],['Pronome.','Trasformazione','Indiretto']),],review:['Congiuntivo','Condizionale','Argomenti','Dibattiti'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const itB2 = lesson({id:'it-b2',subject:'italiano',title:'Italiano B2',levels:['avancado'],grade:'9º',topic:'Italiano B2',subtopic:'Avanzato',aliases:['italiano','b2','avanzato'],summary:'B2: fluent user.',intro:'Padroneggiare la lingua.',objective:'Italiano B2.',next:[],skills:{i:'It'},blocks:[block('i','B2','Congiuntivo passato. Condizionale passato. Gerundio. Participi. Registri formali. Testi complessi.','-Strutturati.','Formali.','Avanzato.','1. Qual registro?'),],questions:[mc(1,'i','Congiuntivo passato?',['avere/essere+pp','avere+participio','essere+pp'],0,['Anteriore.','Passato.','Composto']),tf(1,'i','Gerundio: simultaneità',true,['Sì.','Stesso tempo','Azione']),fill(1,'i','En ___ parliamo.',['gerundio'],['En+verb-ing.','Azione.','Simultanea']),],review:['Forme complesse','Registri','Testi','Fluidità'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const itC1 = lesson({id:'it-c1',subject:'italiano',title:'Italiano C1',levels:['avancado'],grade:'9º',topic:'Italiano C1',subtopic:'Padronanza',aliases:['italiano','c1','padronanza'],summary:'C1: mastery.',intro:'Expertise totale.',objective:'Italiano C1.',next:[],skills:{i:'It'},blocks:[block('i','C1','Sfumature semantiche. Registri altamente sofisticati. Testi critici. Retorica. Letteratura. Stile.','-Profondo.','Esperto.','Padronanza.','1. Cos\'è C1?'),],questions:[mc(1,'i','Livello C1?',['Fluente','Maestro','Esperto'],2,['Completo.','Eleganza.','Expertise']),tf(1,'i','C1: testi letterari',true,['Sì.','Complesso','Profondo']),fill(1,'i','Retorica: arte di ___.',['persuadere'],['Convincere.','Argomentare','Elegante']),],review:['Padronanza','Eleganza','Letteratura','Expertise'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})
