import type { Lesson } from '../../types'

const AUTORAL = { title: 'Conteúdo autoral LUMI', kind: 'autoral' } as const
const BNCC_LP = { title: 'Base Nacional Comum Curricular (BNCC) — Língua Portuguesa', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' } as const

export const verbos: Lesson = {
  id: 'por-verbos',
  subject: 'portugues',
  title: 'Verbos e tempos verbais',
  levels: ['fund1', 'fund2'],
  grade: '4º ao 7º ano',
  aliases: ['verbo', 'verbos', 'tempos verbais', 'presente passado futuro', 'preterito', 'conjugacao', 'modo indicativo', 'subjuntivo', 'imperativo'],
  summary: 'Reconheça verbos, os tempos presente, passado e futuro e os modos verbais.',
  intro: 'Os verbos contam o que acontece e quando acontece. Vamos conhecê-los!',
  skills: { conceito: 'O que é verbo', tempos: 'Presente, pretérito e futuro', modos: 'Modos verbais', conjugacao: 'Concordância do verbo com a pessoa' },
  blocks: [
    { id: 'b1', skill: 'conceito', title: 'Verbo indica ação, estado ou fenômeno', text: 'Verbo é a palavra que indica ação (correr, estudar), estado (ser, estar, ficar) ou fenômeno da natureza (chover, ventar). Ele muda conforme o tempo e a pessoa.', example: 'Ana corre. · Ana está feliz. · Choveu ontem.', variants: { simples: 'Verbo é a palavra que mostra o que alguém faz ou como está: pular, comer, ser, estar.' } },
    { id: 'b2', skill: 'tempos', title: 'Presente, passado e futuro', text: 'O presente indica o que acontece agora (eu estudo). O pretérito (passado) indica o que já aconteceu (eu estudei, eu estudava). O futuro indica o que ainda vai acontecer (eu estudarei).', example: 'Hoje eu jogo. Ontem eu joguei. Amanhã eu jogarei.', variants: { simples: 'Agora: eu brinco. Já passou: eu brinquei. Ainda vai acontecer: eu brincarei.' } },
    { id: 'b3', skill: 'modos', title: 'Os três modos', text: 'Indicativo expressa certeza (Ele viaja amanhã). Subjuntivo expressa dúvida ou desejo (Talvez ele viaje; Espero que ele viaje). Imperativo expressa ordem ou pedido (Viaje com cuidado!).', example: 'Estude! (imperativo) · Se eu estudasse… (subjuntivo) · Eu estudo. (indicativo)' },
    { id: 'b4', skill: 'conjugacao', title: 'O verbo acompanha a pessoa', text: 'O verbo muda de forma para concordar com quem faz a ação: eu canto, tu cantas, ele canta, nós cantamos, vós cantais, eles cantam.', example: '"Nós canta" está errado; o correto é "nós cantamos".', variants: { simples: 'Eu canto, ele canta, nós cantamos, eles cantam. O verbo muda junto com quem faz.' } },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'conceito', prompt: 'Na frase "O menino pulou o muro", qual palavra é o verbo?', options: ['menino', 'pulou', 'muro', 'o'], answer: 1, hints: ['Qual palavra mostra uma ação?', 'O que o menino fez?', 'Ele…'], explanation: '"Pulou" indica a ação.' },
    { id: 'q2', type: 'tf', difficulty: 1, skill: 'conceito', prompt: '"Chover" é um verbo.', answer: true, hints: ['Verbo pode indicar fenômeno da natureza.', 'Chuva acontece.', 'Choveu, choverá…'], explanation: 'Verdadeiro: indica um fenômeno da natureza.' },
    { id: 'q3', type: 'mc', difficulty: 1, skill: 'tempos', prompt: '"Eu estudei para a prova." O verbo está no:', options: ['Presente', 'Passado (pretérito)', 'Futuro', 'Imperativo'], answer: 1, hints: ['A ação já aconteceu ou vai acontecer?', 'Já aconteceu.', 'Passado também se chama pretérito.'], explanation: '"Estudei" está no pretérito (passado).' },
    { id: 'q4', type: 'fill', difficulty: 2, skill: 'tempos', prompt: 'Complete no futuro: "Amanhã eu ______ (viajar) para a praia."', answers: ['viajarei', 'vou viajar'], hints: ['Vai acontecer depois.', 'Futuro com "eu" termina em -rei.', 'Viaja + rei.'], explanation: '"Viajarei" (ou "vou viajar").' },
    { id: 'q5', type: 'match', difficulty: 2, skill: 'tempos', prompt: 'Ligue cada frase ao tempo do verbo.', pairs: [['Eu como maçã agora.', 'Presente'], ['Eu comi maçã ontem.', 'Pretérito'], ['Eu comerei maçã amanhã.', 'Futuro']], hints: ['Olhe as palavras "agora", "ontem" e "amanhã".', 'Ontem = passado.', 'Amanhã = futuro.'], explanation: 'Como → presente · comi → pretérito · comerei → futuro.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'conjugacao', prompt: 'Qual frase está correta?', options: ['Nós canta no coral.', 'Nós cantamos no coral.', 'Nós cantam no coral.', 'Nós canto no coral.'], answer: 1, hints: ['O verbo concorda com "nós".', 'Com "nós" o verbo termina em -mos.', 'Canta + mos.'], explanation: '"Nós cantamos".' },
    { id: 'q7', type: 'mc', difficulty: 2, skill: 'modos', prompt: '"Feche a porta, por favor!" O verbo está no modo:', options: ['Indicativo', 'Subjuntivo', 'Imperativo', 'Infinitivo'], answer: 2, hints: ['A frase é um pedido.', 'Pedido ou ordem.', 'Modo das ordens.'], explanation: 'Imperativo: ordem ou pedido.' },
    { id: 'q8', type: 'tf', difficulty: 3, skill: 'modos', prompt: 'Em "Talvez ele chegue cedo", o verbo está no modo subjuntivo.', answer: true, hints: ['"Talvez" indica certeza ou dúvida?', 'Dúvida.', 'Dúvida → subjuntivo.'], explanation: 'Verdadeiro: expressa dúvida.' },
    { id: 'q9', type: 'fill', difficulty: 3, skill: 'conjugacao', prompt: 'Complete: "Eles ______ (estudar) todos os dias."', answers: ['estudam'], hints: ['Presente, com "eles".', 'Com "eles" termina em -am.', 'Estud + am.'], explanation: '"Eles estudam".' },
    { id: 'q10', type: 'mc', difficulty: 3, skill: 'tempos', prompt: '"Quando eu era criança, eu brincava na rua." O verbo "brincava" indica:', options: ['Ação terminada num momento exato', 'Ação que se repetia no passado', 'Ação no futuro', 'Uma ordem'], answer: 1, hints: ['É passado.', 'Acontecia uma vez ou várias?', 'Era um costume.'], explanation: 'O pretérito imperfeito ("brincava") indica ação habitual no passado.' },
  ],
  review: ['Verbo = ação, estado ou fenômeno', 'Presente · pretérito · futuro', 'Indicativo (certeza) · subjuntivo (dúvida/desejo) · imperativo (ordem)', 'O verbo concorda com a pessoa'],
  sources: [BNCC_LP, AUTORAL],
}

export const sujeitoPredicado: Lesson = {
  id: 'por-sujeito-predicado',
  subject: 'portugues',
  title: 'Sujeito e predicado',
  levels: ['fund2', 'medio'],
  grade: '7º e 8º ano',
  aliases: ['sujeito', 'predicado', 'analise sintatica', 'termos essenciais da oracao', 'sujeito oculto', 'sujeito composto', 'oracao sem sujeito'],
  summary: 'Identifique o sujeito e o predicado e conheça os tipos de sujeito.',
  intro: 'Toda frase conta algo sobre alguém. Vamos descobrir quem é esse "alguém" e o que se diz dele.',
  skills: { conceito: 'Sujeito e predicado', identificar: 'Como encontrar o sujeito', tipos: 'Tipos de sujeito', sem_sujeito: 'Oração sem sujeito' },
  blocks: [
    { id: 'b1', skill: 'conceito', title: 'De quem se fala e o que se diz', text: 'Sujeito é o termo sobre o qual se declara algo. Predicado é tudo o que se declara sobre o sujeito — e nele sempre está o verbo.', example: '"Os alunos | fizeram a tarefa." Sujeito: os alunos. Predicado: fizeram a tarefa.' },
    { id: 'b2', skill: 'identificar', title: 'A pergunta mágica', text: 'Encontre o verbo e pergunte "quem?" ou "o quê?" antes dele. A resposta é o sujeito. O verbo concorda com o sujeito em número e pessoa.', example: '"Chegaram as encomendas." O que chegou? As encomendas → sujeito (mesmo vindo depois do verbo).' },
    { id: 'b3', skill: 'tipos', title: 'Tipos de sujeito', text: 'Simples: um núcleo (O cão latiu). Composto: dois ou mais núcleos (O cão e o gato brigaram). Oculto (desinencial): não aparece, mas é identificado pela terminação do verbo (Estudamos muito → nós). Indeterminado: não se sabe ou não se quer dizer quem é (Roubaram minha bicicleta).', example: '"Fomos ao cinema" → sujeito oculto: nós.' },
    { id: 'b4', skill: 'sem_sujeito', title: 'Orações sem sujeito', text: 'Algumas orações não têm sujeito: com verbos de fenômenos da natureza (Choveu muito), com "haver" no sentido de existir (Há dois alunos) e com "fazer" indicando tempo (Faz três anos).', example: '"Nevou na serra" não tem sujeito — ninguém "faz" a neve.' },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'conceito', prompt: 'Em "A professora explicou a matéria", qual é o sujeito?', options: ['explicou', 'a matéria', 'A professora', 'explicou a matéria'], answer: 2, hints: ['Ache o verbo: explicou.', 'Quem explicou?', 'A resposta é o sujeito.'], explanation: 'Quem explicou? A professora.' },
    { id: 'q2', type: 'tf', difficulty: 1, skill: 'conceito', prompt: 'O verbo faz parte do predicado.', answer: true, hints: ['O predicado é o que se diz do sujeito.', 'O verbo é o centro dessa informação.', 'Está sempre no predicado.'], explanation: 'Verdadeiro.' },
    { id: 'q3', type: 'mc', difficulty: 2, skill: 'identificar', prompt: 'Em "Chegaram as encomendas", qual é o sujeito?', options: ['Chegaram', 'as encomendas', 'Não há sujeito', 'Nós'], answer: 1, hints: ['O sujeito pode vir depois do verbo.', 'O que chegou?', 'O verbo está no plural por causa dele.'], explanation: '"As encomendas" chegaram.' },
    { id: 'q4', type: 'match', difficulty: 2, skill: 'tipos', prompt: 'Ligue cada frase ao tipo de sujeito.', pairs: [['O cão latiu.', 'Simples'], ['Ana e Pedro saíram.', 'Composto'], ['Estudamos muito.', 'Oculto'], ['Roubaram minha bicicleta.', 'Indeterminado']], hints: ['Conte os núcleos.', 'Em "Estudamos", quem é?', 'Em "Roubaram", sabemos quem foi?'], explanation: 'Simples · composto · oculto (nós) · indeterminado.' },
    { id: 'q5', type: 'fill', difficulty: 2, skill: 'tipos', prompt: 'Em "Fomos ao cinema", o sujeito oculto é: ______', answers: ['nos', 'nós'], hints: ['Olhe a terminação do verbo.', '"-mos" indica qual pessoa?', 'Primeira pessoa do plural.'], explanation: 'Nós (sujeito oculto).' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'sem_sujeito', prompt: 'Qual destas orações NÃO tem sujeito?', options: ['Maria cantou.', 'Choveu a noite toda.', 'Os meninos correram.', 'Eu li o livro.'], answer: 1, hints: ['Procure um fenômeno da natureza.', 'Quem "faz" a chuva?', 'Ninguém.'], explanation: '"Choveu a noite toda" é oração sem sujeito.' },
    { id: 'q7', type: 'tf', difficulty: 3, skill: 'sem_sujeito', prompt: 'Em "Há muitos alunos na sala", o sujeito é "muitos alunos".', answer: false, hints: ['"Haver" aqui significa existir.', 'Com esse sentido, o verbo é impessoal.', 'Impessoal = sem sujeito.'], explanation: 'Falso. "Haver" = existir é impessoal: oração sem sujeito ("muitos alunos" é objeto direto).' },
    { id: 'q8', type: 'mc', difficulty: 3, skill: 'identificar', prompt: 'Qual frase tem a concordância correta?', options: ['Faltou dois alunos.', 'Faltaram dois alunos.', 'Faltou os alunos.', 'Faltaram o aluno.'], answer: 1, hints: ['Quem faltou?', '"Dois alunos" é o sujeito, no plural.', 'O verbo vai para o plural.'], explanation: '"Faltaram dois alunos": o verbo concorda com o sujeito.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'tipos', prompt: '"Precisa-se de vendedores." O sujeito é:', options: ['Simples', 'Oculto', 'Indeterminado', 'Composto'], answer: 2, hints: ['Quem precisa?', 'A frase não diz.', 'Verbo + "se" + preposição.'], explanation: 'Sujeito indeterminado (índice de indeterminação do sujeito "se").' },
    { id: 'q10', type: 'open', difficulty: 3, skill: 'identificar', prompt: 'Explique como você descobre o sujeito de uma oração.', modelAnswer: 'Encontro o verbo e pergunto "quem?" ou "o quê?" fez a ação ou sobre quem se fala. A resposta é o sujeito. Depois confiro se o verbo concorda com ele.', keywords: ['verbo', 'quem', 'que', 'concorda', 'pergunta'], hints: ['Qual palavra você procura primeiro?', 'Que pergunta você faz?', 'Fale do verbo e da pergunta "quem?".'], explanation: 'Ache o verbo e pergunte "quem?/o quê?".' },
  ],
  review: ['Sujeito: de quem se fala · predicado: o que se diz', 'Ache o verbo e pergunte "quem?"', 'Simples, composto, oculto, indeterminado', 'Sem sujeito: fenômenos, haver = existir, fazer (tempo)'],
  sources: [BNCC_LP, AUTORAL],
}

export const tiposTextuais: Lesson = {
  id: 'por-tipos-generos-textuais',
  subject: 'portugues',
  title: 'Tipos e gêneros textuais',
  levels: ['fund2', 'medio'],
  grade: '6º ao 9º ano',
  aliases: ['interpretacao de texto', 'generos textuais', 'tipos textuais', 'texto narrativo', 'texto dissertativo', 'texto argumentativo', 'redacao', 'narracao descricao'],
  summary: 'Diferencie tipos textuais (narrar, descrever, argumentar…) de gêneros (notícia, crônica, receita…).',
  intro: 'Uma receita e uma notícia são textos bem diferentes. Por quê? Vamos entender.',
  skills: { tipos: 'Tipos textuais', generos: 'Gêneros textuais', diferenca: 'Tipo × gênero', interpretacao: 'Ler com objetivo' },
  blocks: [
    { id: 'b1', skill: 'tipos', title: 'Os tipos textuais', text: 'Tipo textual é o modo de organizar o texto. Narrativo conta fatos com personagens, tempo e lugar. Descritivo mostra como algo é. Dissertativo-argumentativo defende uma opinião com argumentos. Expositivo explica um assunto. Injuntivo dá instruções.', example: '"Era uma vez…" é narrativo. "Misture a farinha e o ovo" é injuntivo.' },
    { id: 'b2', skill: 'generos', title: 'Os gêneros textuais', text: 'Gênero textual é o "formato" que o texto tem no dia a dia, com uma função social: notícia, crônica, conto, receita, bula, carta, e-mail, anúncio, artigo de opinião.', example: 'A receita serve para ensinar a preparar um prato; a notícia, para informar um fato recente.' },
    { id: 'b3', skill: 'diferenca', title: 'Tipo × gênero', text: 'Os tipos são poucos e fixos; os gêneros são muitos e surgem novos com o tempo (como o post de rede social). Um mesmo gênero pode misturar tipos: um conto narra e também descreve.', example: 'Receita (gênero) usa principalmente o tipo injuntivo.' },
    { id: 'b4', skill: 'interpretacao', title: 'Ler com objetivo', text: 'Para interpretar, identifique o gênero e a finalidade do texto, quem escreveu e para quem, a ideia principal de cada parágrafo e as palavras que mostram opinião.', example: 'Num artigo de opinião, expressões como "é inaceitável" revelam a posição do autor.' },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'tipos', prompt: 'Um texto que começa com "Era uma vez uma menina que…" é do tipo:', options: ['Descritivo', 'Narrativo', 'Injuntivo', 'Argumentativo'], answer: 1, hints: ['Ele conta uma história?', 'Tem personagem e acontecimentos.', 'Contar = narrar.'], explanation: 'Narrativo: conta uma história.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'generos', prompt: 'Qual destes é um gênero textual?', options: ['Narração', 'Receita', 'Descrição', 'Injunção'], answer: 1, hints: ['Gênero é o formato do dia a dia.', 'Três opções são tipos.', 'Qual você encontra num livro de culinária?'], explanation: 'Receita é um gênero; as outras são tipos.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'tipos', prompt: 'O texto injuntivo dá instruções ou ordens.', answer: true, hints: ['Pense num manual.', '"Aperte o botão…"', 'Instrução = injunção.'], explanation: 'Verdadeiro.' },
    { id: 'q4', type: 'match', difficulty: 2, skill: 'generos', prompt: 'Ligue cada gênero à sua principal função.', pairs: [['Notícia', 'Informar um fato recente'], ['Receita', 'Ensinar a preparar algo'], ['Artigo de opinião', 'Defender um ponto de vista'], ['Anúncio', 'Convencer a comprar ou aderir']], hints: ['Qual quer vender?', 'Qual informa?', 'Qual defende uma ideia?'], explanation: 'Notícia informa, receita ensina, artigo opina, anúncio convence.' },
    { id: 'q5', type: 'mc', difficulty: 2, skill: 'tipos', prompt: '"A casa era pequena, com janelas azuis e um jardim florido." Esse trecho é predominantemente:', options: ['Narrativo', 'Descritivo', 'Argumentativo', 'Injuntivo'], answer: 1, hints: ['Acontece alguma ação?', 'Ele mostra como a casa é.', 'Mostrar características = descrever.'], explanation: 'Descritivo: apresenta características.' },
    { id: 'q6', type: 'tf', difficulty: 2, skill: 'diferenca', prompt: 'Existem muito mais gêneros textuais do que tipos textuais.', answer: true, hints: ['Os tipos são poucos.', 'Gêneros surgem com o tempo.', 'Ex.: post, meme, podcast…'], explanation: 'Verdadeiro.' },
    { id: 'q7', type: 'fill', difficulty: 2, skill: 'tipos', prompt: 'O tipo de texto que defende uma opinião com argumentos é o dissertativo-________.', answers: ['argumentativo'], hints: ['Usa argumentos.', 'Argument…', 'É o tipo da redação do ENEM.'], explanation: 'Dissertativo-argumentativo.' },
    { id: 'q8', type: 'mc', difficulty: 3, skill: 'interpretacao', prompt: 'Num artigo de opinião, qual expressão mostra mais claramente a posição do autor?', options: ['"Segundo o IBGE, a população cresceu."', '"É inaceitável que isso continue."', '"O evento ocorreu na segunda-feira."', '"A pesquisa ouviu 2 mil pessoas."'], answer: 1, hints: ['Procure uma avaliação, não um dado.', 'Palavras que julgam.', '"Inaceitável" é um julgamento.'], explanation: '"É inaceitável" expressa opinião; as outras apresentam fatos.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'diferenca', prompt: 'Um conto costuma ser:', options: ['Um tipo textual injuntivo', 'Um gênero em que predomina a narração', 'Um gênero sem descrição', 'Um tipo textual expositivo'], answer: 1, hints: ['Conto é tipo ou gênero?', 'É gênero.', 'Ele conta uma história.'], explanation: 'Conto é um gênero de tipo predominantemente narrativo.' },
    { id: 'q10', type: 'open', difficulty: 3, skill: 'diferenca', prompt: 'Explique a diferença entre tipo textual e gênero textual, dando um exemplo.', modelAnswer: 'Tipo textual é o modo de organização do texto, como narrar, descrever, argumentar, expor ou instruir. Gênero textual é o formato usado no dia a dia com uma função social, como notícia, receita ou carta. Por exemplo, a receita é um gênero que usa o tipo injuntivo.', keywords: ['tipo', 'genero', 'narrar', 'narrativo', 'funcao', 'formato', 'receita', 'noticia', 'injuntivo'], hints: ['Quais são os tipos?', 'Quais são alguns gêneros?', 'Dê o exemplo da receita.'], explanation: 'Tipo = modo de organizar; gênero = formato social.' },
  ],
  review: ['Tipos: narrativo, descritivo, argumentativo, expositivo, injuntivo', 'Gêneros: notícia, receita, crônica, carta…', 'Gêneros misturam tipos', 'Interpretar: finalidade, autor, ideia principal'],
  sources: [BNCC_LP, AUTORAL],
}

export const simplePresent: Lesson = {
  id: 'ing-simple-present',
  subject: 'ingles',
  title: 'Simple present',
  levels: ['fund2', 'medio'],
  grade: '6º e 7º ano',
  aliases: ['simple present', 'presente simples', 'do does', 'rotina em ingles', 'terceira pessoa ingles'],
  summary: 'Fale sobre rotinas e verdades em inglês usando o simple present, com do/does.',
  intro: 'I study, she studies… Vamos aprender o tempo verbal da rotina!',
  skills: { uso: 'Quando usar', terceira: 'Terceira pessoa (he/she/it)', negativa: 'Negativa com don\'t/doesn\'t', interrogativa: 'Perguntas com do/does' },
  blocks: [
    { id: 'b1', skill: 'uso', title: 'Rotinas e verdades', text: 'Usamos o simple present para hábitos, rotinas e fatos que são sempre verdadeiros. Palavras como always, usually, every day e never costumam aparecer.', example: 'I go to school every day. · Water boils at 100 °C.' },
    { id: 'b2', skill: 'terceira', title: 'He, she, it ganham -s', text: 'Com he, she e it, o verbo recebe -s (works). Verbos terminados em -o, -s, -sh, -ch, -x recebem -es (goes, watches). Consoante + y vira -ies (study → studies). Have vira has.', example: 'She plays guitar. · He watches TV. · It has four legs.' },
    { id: 'b3', skill: 'negativa', title: 'Negativa', text: 'Use don\'t (do not) com I, you, we, they e doesn\'t (does not) com he, she, it. Depois de doesn\'t, o verbo volta à forma base, sem -s.', example: 'I don\'t like coffee. · She doesn\'t like coffee (e não "doesn\'t likes").' },
    { id: 'b4', skill: 'interrogativa', title: 'Perguntas', text: 'Coloque Do ou Does no início. Does é para he, she, it — e o verbo também fica sem -s. Respostas curtas: Yes, I do. / No, she doesn\'t.', example: 'Do you speak English? — Yes, I do. · Does he work here? — No, he doesn\'t.' },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'terceira', prompt: 'Complete: She ___ guitar.', options: ['play', 'plays', 'playes', 'playing'], answer: 1, hints: ['"She" é terceira pessoa.', 'Terceira pessoa ganha uma letra.', 'Play + s.'], explanation: 'She plays.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'uso', prompt: 'O simple present é usado principalmente para:', options: ['Ações acontecendo neste exato momento', 'Rotinas e hábitos', 'Ações que já terminaram', 'Planos futuros certos'], answer: 1, hints: ['Pense em "every day".', 'Coisas que se repetem.', 'Hábitos.'], explanation: 'Rotinas, hábitos e verdades gerais.' },
    { id: 'q3', type: 'fill', difficulty: 1, skill: 'terceira', prompt: 'Complete: He ___ (go) to school by bus.', answers: ['goes'], hints: ['Terceira pessoa.', 'Go termina em -o.', '-o recebe -es.'], explanation: 'He goes.' },
    { id: 'q4', type: 'tf', difficulty: 1, skill: 'negativa', prompt: 'A frase "She doesn\'t likes pizza" está correta.', answer: false, hints: ['Depois de doesn\'t, o verbo muda?', 'Ele volta à forma base.', 'Sem -s.'], explanation: 'Falso. O correto é "She doesn\'t like pizza".' },
    { id: 'q5', type: 'match', difficulty: 2, skill: 'terceira', prompt: 'Ligue cada verbo à forma com he/she/it.', pairs: [['study', 'studies'], ['watch', 'watches'], ['have', 'has'], ['read', 'reads']], hints: ['Consoante + y vira -ies.', '-ch recebe -es.', 'Have é irregular.'], explanation: 'studies · watches · has · reads.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'negativa', prompt: 'Qual é a negativa de "They play soccer"?', options: ["They doesn't play soccer.", "They don't play soccer.", "They don't plays soccer.", 'They not play soccer.'], answer: 1, hints: ['"They" usa do ou does?', 'They → do.', 'Do + not = don\'t.'], explanation: "They don't play soccer." },
    { id: 'q7', type: 'mc', difficulty: 2, skill: 'interrogativa', prompt: 'Complete a pergunta: ___ she speak Spanish?', options: ['Do', 'Does', 'Is', 'Are'], answer: 1, hints: ['A pergunta usa um auxiliar.', '"She" é terceira pessoa.', 'Do → does.'], explanation: 'Does she speak Spanish?' },
    { id: 'q8', type: 'fill', difficulty: 2, skill: 'interrogativa', prompt: 'Responda curto (afirmativo): "Do you like music?" — Yes, I ___.', answers: ['do'], hints: ['Repita o auxiliar da pergunta.', 'A pergunta usa "Do".', 'Yes, I…'], explanation: 'Yes, I do.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'interrogativa', prompt: 'Qual pergunta está correta?', options: ['Does he works here?', 'Do he work here?', 'Does he work here?', 'He does work here?'], answer: 2, hints: ['He → does.', 'Depois de does, o verbo perde o -s.', 'Does + he + work.'], explanation: 'Does he work here?' },
    { id: 'q10', type: 'mc', difficulty: 3, skill: 'uso', prompt: 'Qual frase expressa uma verdade geral?', options: ['I am reading now.', 'The sun rises in the east.', 'I watched a movie.', 'I will travel tomorrow.'], answer: 1, hints: ['Procure algo que é sempre verdade.', 'Não depende do momento.', 'Um fato da natureza.'], explanation: '"The sun rises in the east" — verdade geral no simple present.' },
  ],
  review: ['Rotinas, hábitos e verdades', 'He/she/it: -s, -es, -ies; have → has', "Negativa: don't / doesn't + verbo base", 'Pergunta: Do/Does + sujeito + verbo base'],
  sources: [{ title: 'Base Nacional Comum Curricular (BNCC) — Língua Inglesa', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' }, AUTORAL],
}

export const cores: Lesson = {
  id: 'art-cores',
  subject: 'artes',
  title: 'Cores primárias, secundárias e complementares',
  levels: ['fund1', 'fund2'],
  grade: '2º ao 6º ano',
  aliases: ['cores primarias', 'cores secundarias', 'circulo cromatico', 'cores quentes e frias', 'cores complementares', 'misturar cores', 'teoria das cores'],
  summary: 'Descubra como as cores se misturam, o círculo cromático e as cores quentes e frias.',
  intro: 'Com só três cores de tinta dá para fazer muitas outras. Vamos misturar!',
  skills: { primarias: 'Cores primárias', secundarias: 'Cores secundárias', quentes_frias: 'Cores quentes e frias', complementares: 'Cores complementares' },
  blocks: [
    { id: 'b1', skill: 'primarias', title: 'As cores primárias', text: 'Nas tintas escolares, as cores primárias são vermelho, amarelo e azul. Elas não podem ser obtidas misturando outras cores de tinta — e a partir delas fazemos muitas outras.', example: 'Com uma caixinha de vermelho, amarelo e azul já dá para pintar um arco-íris inteiro.', variants: { simples: 'Vermelho, amarelo e azul são as cores "mães": misturando elas, nascem as outras.' } },
    { id: 'b2', skill: 'secundarias', title: 'As cores secundárias', text: 'Misturando duas primárias em partes iguais, obtemos as secundárias: vermelho + amarelo = laranja; amarelo + azul = verde; azul + vermelho = roxo (violeta).', example: 'Para pintar uma folha de árvore, misture amarelo com azul.', variants: { simples: 'Vermelho + amarelo = laranja. Amarelo + azul = verde. Azul + vermelho = roxo.' } },
    { id: 'b3', skill: 'quentes_frias', title: 'Quentes e frias', text: 'Cores quentes (vermelho, laranja, amarelo) lembram fogo e sol e passam sensação de calor e energia. Cores frias (azul, verde, roxo) lembram água e gelo e passam calma.', example: 'Um pôr do sol é pintado com cores quentes; o fundo do mar, com cores frias.', variants: { simples: 'Quentes lembram o sol: vermelho, laranja, amarelo. Frias lembram a água: azul, verde, roxo.' } },
    { id: 'b4', skill: 'complementares', title: 'Cores complementares', text: 'No círculo cromático, as cores que ficam uma de frente para a outra são complementares: vermelho e verde, azul e laranja, amarelo e roxo. Juntas, uma destaca a outra.', example: 'Muitos logotipos usam azul com laranja para chamar atenção.', variants: { simples: 'Algumas cores são "opostas" e combinam para chamar atenção: azul e laranja, vermelho e verde, amarelo e roxo.' } },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'primarias', prompt: 'Quais são as cores primárias das tintas escolares?', options: ['Verde, laranja e roxo', 'Vermelho, amarelo e azul', 'Preto, branco e cinza', 'Rosa, azul e verde'], answer: 1, hints: ['São as cores "mães".', 'Não dá para fazê-las misturando outras.', 'Uma delas é o amarelo.'], explanation: 'Vermelho, amarelo e azul.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'secundarias', prompt: 'Amarelo + azul dá:', options: ['Laranja', 'Roxo', 'Verde', 'Marrom'], answer: 2, hints: ['É a cor das folhas.', 'Também é cor da grama.', 'Começa com V.'], explanation: 'Amarelo + azul = verde.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'quentes_frias', prompt: 'O vermelho é uma cor quente.', answer: true, hints: ['Lembra fogo ou água?', 'Lembra fogo.', 'Fogo → quente.'], explanation: 'Verdadeiro.' },
    { id: 'q4', type: 'fill', difficulty: 1, skill: 'secundarias', prompt: 'Vermelho + amarelo dá a cor ________.', answers: ['laranja'], hints: ['É a cor de uma fruta.', 'Também é o nome da fruta.', 'Laran…'], explanation: 'Laranja.' },
    { id: 'q5', type: 'match', difficulty: 2, skill: 'secundarias', prompt: 'Ligue cada mistura à cor que ela forma.', pairs: [['Vermelho + amarelo', 'Laranja'], ['Amarelo + azul', 'Verde'], ['Azul + vermelho', 'Roxo']], hints: ['Pense no sol se pondo: vermelho e amarelo.', 'Folhas: amarelo e azul.', 'Uva: azul e vermelho.'], explanation: 'Laranja, verde e roxo.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'quentes_frias', prompt: 'Qual destas é uma cor fria?', options: ['Laranja', 'Amarelo', 'Azul', 'Vermelho'], answer: 2, hints: ['Cores frias lembram água.', 'Qual é a cor do mar?', 'Azul.'], explanation: 'Azul é fria.' },
    { id: 'q7', type: 'tf', difficulty: 2, skill: 'primarias', prompt: 'Dá para fazer tinta amarela misturando outras duas cores de tinta.', answer: false, hints: ['O amarelo é primário ou secundário?', 'Primário.', 'Primárias não são feitas por mistura.'], explanation: 'Falso. O amarelo é primário.' },
    { id: 'q8', type: 'mc', difficulty: 3, skill: 'complementares', prompt: 'Qual é a cor complementar do azul?', options: ['Verde', 'Roxo', 'Laranja', 'Amarelo'], answer: 2, hints: ['É a cor oposta no círculo.', 'Ela é quente.', 'É secundária, feita com vermelho e amarelo.'], explanation: 'Azul e laranja são complementares.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'quentes_frias', prompt: 'Para pintar um quadro que passe calma e tranquilidade, o mais indicado é usar:', options: ['Cores quentes', 'Cores frias', 'Só preto', 'Só vermelho'], answer: 1, hints: ['Pense no mar e no céu.', 'Essas cores acalmam.', 'São as frias.'], explanation: 'Cores frias passam calma.' },
    { id: 'q10', type: 'tf', difficulty: 3, skill: 'complementares', prompt: 'Vermelho e verde são cores complementares.', answer: true, hints: ['Verde é feito com amarelo e azul.', 'Falta qual primária?', 'A que falta é a complementar.'], explanation: 'Verdadeiro.' },
  ],
  review: ['Primárias: vermelho, amarelo, azul', 'Secundárias: laranja, verde, roxo', 'Quentes (sol) × frias (água)', 'Complementares ficam opostas no círculo'],
  sources: [{ title: 'Base Nacional Comum Curricular (BNCC) — Arte', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' }, AUTORAL],
}
