// LOTE 1 — MATEMÁTICA · Ensino Fundamental I (1º ao 5º ano)
import { block, fill, formula, lesson, match, mc, open, order, SRC, tf } from '../dsl'

const FONTES = [SRC.bncc('Matemática — Anos Iniciais'), SRC.obmep(), SRC.autoral()]

export const sistemaDecimal = lesson({
  id: 'mat-sistema-decimal', subject: 'matematica', title: 'Sistema de numeração decimal', levels: ['fund1'], grade: '1º ao 3º ano',
  topic: 'Números', subtopic: 'Valor posicional',
  aliases: ['sistema decimal', 'unidade dezena centena', 'valor posicional', 'valor do algarismo', 'ordens e classes', 'milhar', 'decompor numero', 'numeros naturais'],
  summary: 'Entenda unidades, dezenas, centenas e milhares e por que o lugar de cada algarismo muda o seu valor.',
  intro: 'Com apenas dez algarismos (0 a 9) escrevemos qualquer número. O segredo está no lugar de cada um!',
  objective: 'Ler, escrever e decompor números, identificando o valor de cada algarismo pela sua posição.',
  next: ['mat-adicao-subtracao'],
  skills: { agrupamento: 'Agrupar de 10 em 10', posicao: 'Valor posicional', decomposicao: 'Decompor números', leitura: 'Ler e escrever números' },
  blocks: [
    block('agrupamento', 'Grupos de 10', 'No nosso sistema, contamos em grupos de 10: 10 unidades formam 1 dezena, 10 dezenas formam 1 centena e 10 centenas formam 1 milhar.', 'Com 23 palitos você faz 2 montinhos de 10 (2 dezenas) e sobram 3 palitos soltos (3 unidades).',
      'Junte de 10 em 10. Cada montinho de 10 é uma dezena.', 'Pense em ovos: uma caixa com 10 ovos é uma dezena de ovos. Dez caixas cheias são 100 ovos: uma centena.', '1. Conte os objetos.\n2. Faça grupos de 10 — cada grupo é 1 dezena.\n3. Se juntar 10 grupos de 10, você tem 1 centena.\n4. O que sobrar sem grupo são as unidades.'),
    block('posicao', 'O lugar muda o valor', 'O valor de um algarismo depende da posição que ele ocupa. Da direita para a esquerda: unidades, dezenas, centenas, milhares.', 'Em 352, o 3 vale 300 (3 centenas), o 5 vale 50 (5 dezenas) e o 2 vale 2 unidades.',
      'O mesmo número vale mais quando está mais para a esquerda. O 3 de 352 vale 300!', 'Em 44, os dois algarismos são iguais, mas o da esquerda vale 40 e o da direita vale 4.', '1. Olhe o algarismo da direita: são as unidades.\n2. O do meio: dezenas (vale 10 vezes mais).\n3. O da esquerda: centenas (vale 100 vezes mais).\n4. Multiplique o algarismo pelo valor da casa.'),
    block('decomposicao', 'Decompor números', 'Decompor é separar o número em partes pelo valor de cada algarismo. Assim fica fácil ver quanto cada um vale.', '4.726 = 4.000 + 700 + 20 + 6.',
      'Decompor é "abrir" o número: 58 = 50 + 8.', 'Se você tem 1 nota de R$ 100, 2 notas de R$ 10 e 5 moedas de R$ 1, tem 100 + 20 + 5 = R$ 125.', '1. Separe cada algarismo.\n2. Escreva quanto ele vale pela posição.\n3. Some tudo com o sinal +.\n4. Confira: a soma tem que dar o número original.'),
    block('leitura', 'Ler e escrever números', 'Para ler um número grande, separamos em grupos de três algarismos a partir da direita (classes). Lemos cada grupo e dizemos o nome da classe: mil, milhão…', '12.305 lê-se "doze mil, trezentos e cinco". O zero indica que não há dezenas.',
      'O ponto separa os milhares: 3.200 é "três mil e duzentos".', 'No preço de uma bicicleta, R$ 1.250, lemos "mil duzentos e cinquenta reais".', '1. Separe de três em três algarismos, da direita para a esquerda.\n2. Leia o grupo da esquerda e diga "mil".\n3. Leia o grupo da direita.\n4. Se aparecer zero, é porque aquela casa está vazia.'),
  ],
  questions: [
    mc(1, 'agrupamento', 'Quantas unidades formam 1 dezena?', ['5', '10', '100', '12'], 1, ['Pense em grupos.', 'Uma dezena é um grupo de…', 'Dezena lembra "dez".'], '1 dezena = 10 unidades.'),
    mc(1, 'posicao', 'No número 352, quanto vale o algarismo 5?', ['5', '50', '500', '35'], 1, ['Em que posição está o 5?', 'Ele está na casa das dezenas.', '5 dezenas = 5 × 10.'], 'O 5 está nas dezenas: vale 50.'),
    tf(1, 'agrupamento', '10 dezenas formam 1 centena.', true, ['Quanto é 10 grupos de 10?', '10 × 10.', '= 100.'], 'Verdadeiro: 10 dezenas = 100 unidades = 1 centena.'),
    fill(1, 'decomposicao', 'Complete: 58 = 50 + ____', ['8'], ['Separe dezenas e unidades.', '58 tem 5 dezenas e algumas unidades.', 'Quantas unidades sobram depois do 50?'], '58 = 50 + 8.'),
    mc(2, 'decomposicao', 'Qual é a decomposição de 4.726?', ['4 + 7 + 2 + 6', '4.000 + 700 + 20 + 6', '400 + 70 + 26', '4.000 + 726 + 6'], 1, ['Cada algarismo vale conforme a posição.', 'O 4 está nos milhares.', 'Escreva quanto vale cada algarismo.'], '4.726 = 4.000 + 700 + 20 + 6.'),
    match(2, 'posicao', 'No número 2.839, ligue cada algarismo ao seu valor.', [['2', '2.000'], ['8', '800'], ['3', '30'], ['9', '9']], ['Comece pela direita: unidades.', 'Depois dezenas e centenas.', 'O da esquerda está nos milhares.'], '2 → 2.000 · 8 → 800 · 3 → 30 · 9 → 9.'),
    mc(2, 'leitura', 'Como se lê 12.305?', ['Doze mil, trezentos e cinco', 'Mil duzentos e trinta e cinco', 'Doze mil, trinta e cinco', 'Cento e vinte e três mil e cinco'], 0, ['Separe: 12 | 305.', 'O 12 é da classe dos milhares.', 'Depois leia 305.'], '12.305 = doze mil, trezentos e cinco.'),
    fill(2, 'leitura', 'Escreva com algarismos: "três mil e quarenta".', ['3040', '3.040'], ['São 3 milhares.', 'Não há centenas.', 'Há 4 dezenas e nenhuma unidade.'], '3.040: o zero ocupa a casa das centenas e a das unidades.'),
    order(2, 'posicao', 'Coloque os números do MENOR para o MAIOR.', ['209', '290', '902', '920'], ['Compare primeiro as centenas.', 'Com centenas iguais, compare as dezenas.', '2 centenas é menos que 9 centenas.'], '209 < 290 < 902 < 920.'),
    tf(3, 'posicao', 'Em 505, os dois algarismos 5 valem a mesma coisa.', false, ['Veja a posição de cada 5.', 'Um está nas centenas e outro nas unidades.', '500 é igual a 5?'], 'Falso: o da esquerda vale 500 e o da direita vale 5.'),
    mc(3, 'agrupamento', 'Ana tem 3 caixas com 10 lápis e 7 lápis soltos. Quantos lápis ela tem?', ['10', '37', '307', '73'], 1, ['Cada caixa é uma dezena.', '3 dezenas = 30.', 'Some os soltos.'], '3 dezenas + 7 unidades = 37 lápis.'),
    open(3, 'posicao', 'Explique por que o 7 em 70 vale mais do que o 7 em 17.', 'Porque no 70 o 7 está na casa das dezenas e vale 70, enquanto no 17 ele está na casa das unidades e vale apenas 7.', ['dezena', 'unidade', 'posicao', 'lugar', 'casa'], ['Onde está o 7 em cada número?', 'Um está nas dezenas, outro nas unidades.', 'Fale da posição (casa) do algarismo.'], 'O valor depende da posição: dezenas valem 10 vezes mais que unidades.'),
  ],
  review: ['10 unidades = 1 dezena · 10 dezenas = 1 centena · 10 centenas = 1 milhar', 'O valor do algarismo depende da posição', 'Decompor: 352 = 300 + 50 + 2', 'Leia separando de três em três algarismos'],
  relatedQuestions: ['O que é unidade, dezena e centena?', 'Como decompor um número?', 'O que é valor posicional?'],
  equivalentQuestions: ['o que é dezena', 'quanto vale uma centena', 'quantas dezenas tem uma centena', 'como saber o valor de um algarismo', 'por que o número muda de valor', 'como decompor 352', 'o que significa decompor um número', 'como escrever número por extenso', 'como ler números grandes', 'o que é milhar', 'quantas unidades tem um milhar', 'como separar unidade dezena e centena', 'o que é ordem e classe dos números', 'para que serve o ponto no número 1.000', 'como saber qual número é maior', 'me explica sistema decimal', 'por que contamos de 10 em 10', 'o que é algarismo', 'qual a diferença entre número e algarismo', 'como montar número com unidades e dezenas', 'o zero vale alguma coisa no número', 'como fazer quadro de ordens'],
  commonDoubts: [
    { q: 'Qual a diferença entre número e algarismo?', a: 'Algarismos são os símbolos 0 a 9. Números são formados por algarismos: 352 é um número com três algarismos.' },
    { q: 'Se o zero não vale nada, por que escrevê-lo?', a: 'O zero marca que aquela casa está vazia. Sem ele, 305 viraria 35 — outro número!' },
  ],
  commonErrors: ['Achar que um algarismo vale sempre o mesmo, em qualquer posição', 'Esquecer o zero ao escrever números como 3.040', 'Ler da esquerda para a direita sem separar as classes'],
  sources: FONTES,
})

export const adicaoSubtracao = lesson({
  id: 'mat-adicao-subtracao', subject: 'matematica', title: 'Adição e subtração', levels: ['fund1'], grade: '1º ao 4º ano',
  topic: 'Operações', subtopic: 'Adição e subtração',
  aliases: ['adicao', 'subtracao', 'soma', 'somar', 'conta de mais', 'conta de menos', 'subtrair', 'emprestar na subtracao', 'vai um', 'reserva', 'troco'],
  summary: 'Aprenda a somar e subtrair, inclusive com "vai um" e "empresta", e a usar essas contas no dia a dia.',
  intro: 'Somar é juntar. Subtrair é tirar ou comparar. Vamos ver como fazer as duas contas sem errar.',
  objective: 'Resolver adições e subtrações com e sem reagrupamento e aplicá-las em problemas.',
  prerequisites: ['mat-sistema-decimal'], next: ['mat-multiplicacao'],
  skills: { adicao: 'Adição', reagrupar: 'Vai um e empréstimo', subtracao: 'Subtração', problemas: 'Problemas com adição e subtração' },
  blocks: [
    block('adicao', 'Somar é juntar', 'Na adição juntamos quantidades. Os números somados são as parcelas e o resultado é a soma (ou total). A ordem das parcelas não muda a soma.', '12 + 5 = 17: 12 figurinhas mais 5 figurinhas dão 17.',
      'Somar é juntar tudo e contar quanto ficou.', 'Você tem 8 balas e ganha 4. Agora tem 8 + 4 = 12 balas.', '1. Escreva os números um embaixo do outro, unidade embaixo de unidade.\n2. Some a coluna das unidades.\n3. Some a coluna das dezenas.\n4. Escreva o resultado.'),
    block('reagrupar', 'Vai um e empresta', 'Quando a soma de uma coluna passa de 9, trocamos 10 unidades por 1 dezena ("vai um"). Na subtração, se não dá para tirar, pegamos 1 dezena emprestada, que vira 10 unidades.', '48 + 35: 8 + 5 = 13 → escreve 3, vai 1. Depois 4 + 3 + 1 = 8. Resultado: 83.',
      'Passou de 9? Fica o número da direita e o 1 "vai" para a próxima coluna.', 'É como trocar 10 moedas de R$ 1 por uma nota de R$ 10: a quantidade de dinheiro é a mesma.', '1. Some (ou subtraia) as unidades.\n2. Se na soma deu 10 ou mais, escreva só as unidades e leve 1 para as dezenas.\n3. Na subtração, se o de cima é menor, pegue 1 dezena emprestada: ela vale 10 unidades.\n4. Continue nas dezenas lembrando do que foi levado ou emprestado.'),
    block('subtracao', 'Subtrair é tirar ou comparar', 'Na subtração tiramos uma quantidade de outra ou descobrimos a diferença entre elas. O resultado se chama diferença (ou resto). Para conferir, somamos o resultado com o número tirado.', '52 − 17 = 35. Conferindo: 35 + 17 = 52 ✓.',
      'Subtrair é tirar e ver quanto sobra.', 'Tinha R$ 20 e gastei R$ 13. Sobraram 20 − 13 = R$ 7 de troco.', '1. Coloque o maior número em cima.\n2. Subtraia as unidades (empreste se precisar).\n3. Subtraia as dezenas.\n4. Confira somando o resultado com o número de baixo.'),
    block('problemas', 'Qual conta usar?', 'Palavras como "juntar", "ganhar", "total" indicam adição. "Tirar", "gastar", "sobrou", "quanto falta", "diferença" indicam subtração.', 'Pedro tem 15 anos e a irmã tem 9. A diferença de idade é 15 − 9 = 6 anos.',
      'Juntou? É mais. Tirou ou quer saber quanto falta? É menos.', 'No supermercado: somamos os preços para saber o total e subtraímos do dinheiro para saber o troco.', '1. Leia o problema com calma.\n2. Descubra o que ele pergunta.\n3. Veja se a situação é de juntar (mais) ou tirar/comparar (menos).\n4. Faça a conta e responda com a unidade (balas, reais…).'),
  ],
  questions: [
    mc(1, 'adicao', 'Quanto é 12 + 5?', ['7', '17', '15', '125'], 1, ['Comece pelo 12.', 'Conte mais 5.', '13, 14, 15, 16…'], '12 + 5 = 17.'),
    fill(1, 'subtracao', 'Quanto é 20 − 13?', ['7'], ['Pense no troco de 20.', 'Quanto falta de 13 para 20?', '13 + ? = 20.'], '20 − 13 = 7, porque 13 + 7 = 20.'),
    tf(1, 'adicao', '3 + 8 dá o mesmo resultado que 8 + 3.', true, ['A ordem muda a soma?', 'Faça as duas contas.', 'As duas dão 11.'], 'Verdadeiro: a ordem das parcelas não altera a soma.'),
    mc(2, 'reagrupar', 'Quanto é 48 + 35?', ['73', '83', '713', '82'], 1, ['8 + 5 passa de 9.', '8 + 5 = 13: escreve 3 e vai 1.', '4 + 3 + 1 = ?'], '8 + 5 = 13 (vai 1); 4 + 3 + 1 = 8. Total 83.'),
    mc(2, 'reagrupar', 'Quanto é 52 − 17?', ['45', '35', '25', '39'], 1, ['2 − 7 não dá: precisa emprestar.', '12 − 7 = 5.', 'Nas dezenas: 4 − 1.'], '12 − 7 = 5; 4 − 1 = 3. Resultado 35.'),
    fill(2, 'subtracao', 'Para conferir 52 − 17 = 35, somamos 35 + 17. O resultado deve ser ____.', ['52'], ['A conta de conferir desfaz a subtração.', 'Some 35 e 17.', 'Deve voltar ao número inicial.'], '35 + 17 = 52: a conta está certa.'),
    match(2, 'problemas', 'Ligue cada situação à conta certa.', [['Ganhei mais figurinhas', 'Adição'], ['Gastei parte do dinheiro', 'Subtração'], ['Quanto falta para chegar a 100?', 'Subtração (quanto falta)'], ['Qual o total de alunos das duas turmas?', 'Adição (total)']], ['Ganhar e total: juntar.', 'Gastar: tirar.', 'Quanto falta: diferença.'], 'Juntar/total → adição · tirar/quanto falta → subtração.'),
    mc(2, 'problemas', 'Pedro tem 15 anos e a irmã tem 9. Qual é a diferença de idade?', ['24 anos', '6 anos', '5 anos', '9 anos'], 1, ['Diferença indica qual conta?', 'Subtração.', '15 − 9.'], '15 − 9 = 6 anos.'),
    fill(3, 'reagrupar', 'Quanto é 305 − 128?', ['177'], ['5 − 8 não dá: empreste das dezenas.', 'As dezenas estão zeradas: empreste das centenas.', '305 = 2 centenas + 9 dezenas + 15 unidades.'], '15 − 8 = 7; 9 − 2 = 7; 2 − 1 = 1 → 177. Confira: 177 + 128 = 305.'),
    mc(3, 'problemas', 'Uma escola tem 238 alunos de manhã e 175 à tarde. Quantos alunos tem ao todo?', ['413', '313', '403', '63'], 0, ['"Ao todo" pede adição.', '8 + 5 = 13, vai 1.', '3 + 7 + 1 = 11, vai 1; 2 + 1 + 1 = 4.'], '238 + 175 = 413 alunos.'),
    tf(3, 'subtracao', 'Na subtração, a ordem dos números não importa: 9 − 4 é igual a 4 − 9.', false, ['Tente tirar 9 de 4 com objetos.', 'Não dá para tirar 9 de 4 em números naturais.', 'Na subtração a ordem importa.'], 'Falso: 9 − 4 = 5, mas 4 − 9 não é 5. Na subtração a ordem importa.'),
    open(3, 'problemas', 'Invente um problema de subtração sobre troco e resolva.', 'Exemplo: comprei um lanche de R$ 13 e paguei com R$ 20. O troco é 20 − 13 = R$ 7.', ['troco', 'paguei', 'custa', 'sobrou', 'menos', 'reais'], ['Pense numa compra.', 'Quanto custou e quanto você pagou?', 'O troco é a diferença.'], 'Troco = valor pago − preço.'),
  ],
  review: ['Adição junta: parcelas → soma', 'Passou de 9 na coluna: "vai um"', 'Subtração tira ou compara; empreste quando precisar', 'Confira a subtração somando'],
  relatedQuestions: ['Como fazer conta de mais com vai um?', 'Como fazer conta de menos emprestando?', 'Como saber se é conta de mais ou de menos?'],
  equivalentQuestions: ['como somar numeros', 'como fazer conta de mais', 'o que é vai um', 'como fazer conta de menos', 'como subtrair emprestando', 'por que emprestar na conta de menos', 'como fazer 52 menos 17', 'como calcular o troco', 'como saber quanto falta', 'o que é diferença na matematica', 'como conferir uma subtração', 'o que são parcelas', 'qual o nome do resultado da soma', 'como armar a conta de mais', 'como somar numeros grandes', 'problema de somar ou subtrair como saber', 'me explica adição', 'me explica subtração', 'nao sei fazer conta de menos', 'como fazer conta de menos com zero', 'como calcular o total de duas coisas', 'soma e subtração exemplo'],
  commonDoubts: [
    { q: 'Por que na conta de menos eu "empresto"?', a: 'Porque trocamos 1 dezena por 10 unidades. O número continua o mesmo, só está escrito de outra forma para dar para tirar.' },
    { q: 'Como sei se o problema é de mais ou de menos?', a: 'Juntar, ganhar, total → mais. Tirar, gastar, sobrar, quanto falta, diferença → menos.' },
  ],
  commonErrors: ['Esquecer de somar o "vai um" na coluna seguinte', 'Tirar o menor do maior dentro da coluna (fazer 7 − 2 em vez de 12 − 7)', 'Desalinhar unidades e dezenas ao armar a conta'],
  formulas: [formula('Prova da subtração', 'diferença + subtraendo = minuendo', [['minuendo', 'número de onde se tira'], ['subtraendo', 'número que se tira'], ['diferença', 'resultado']])],
  sources: FONTES,
})

export const multiplicacao = lesson({
  id: 'mat-multiplicacao', subject: 'matematica', title: 'Multiplicação e tabuada', levels: ['fund1'], grade: '2º ao 4º ano',
  topic: 'Operações', subtopic: 'Multiplicação',
  aliases: ['multiplicacao', 'tabuada', 'vezes', 'multiplicar', 'conta de vezes', 'produto', 'dobro', 'triplo'],
  summary: 'Entenda a multiplicação como soma de parcelas iguais e aprenda truques da tabuada.',
  intro: 'Multiplicar é um jeito rápido de somar números iguais. Vamos descobrir como!',
  objective: 'Compreender a multiplicação como adição de parcelas iguais, usar a tabuada e resolver problemas.',
  prerequisites: ['mat-adicao-subtracao'], next: ['mat-divisao'],
  skills: { conceito: 'Multiplicação como soma repetida', tabuada: 'Tabuada', propriedades: 'Propriedades da multiplicação', problemas: 'Problemas com multiplicação' },
  blocks: [
    block('conceito', 'Multiplicar é somar parcelas iguais', 'Quando somamos o mesmo número várias vezes, usamos a multiplicação. 3 × 4 quer dizer "3 grupos de 4": 4 + 4 + 4 = 12. Os números multiplicados são os fatores e o resultado é o produto.', 'Três pacotes com 4 figurinhas cada: 3 × 4 = 12 figurinhas.',
      'Vezes é contar grupos iguais. 2 × 5 são dois grupos de 5 coisas: 10 coisas.', 'Uma bicicleta tem 2 rodas. 5 bicicletas têm 5 × 2 = 10 rodas.', '1. Descubra quantos grupos existem.\n2. Descubra quantos há em cada grupo.\n3. Multiplique os dois números.\n4. Se quiser conferir, some o grupo tantas vezes quanto indicado.'),
    block('tabuada', 'Truques da tabuada', 'Na tabuada do 2, é só dobrar. Na do 10, coloque um zero no fim. Na do 5, os resultados terminam sempre em 0 ou 5. Na do 9, os algarismos do resultado somam 9 (até 9 × 10).', '7 × 2 = 14 · 6 × 10 = 60 · 5 × 3 = 15 · 9 × 4 = 36 (3 + 6 = 9).',
      '× 2 é o dobro. × 10 é pôr um zero no fim. × 5 termina em 0 ou 5.', 'Para saber quantos dedos há em 6 mãos: 6 × 5 = 30.', '1. Veja se o número é 2, 5, 9 ou 10 — use o truque.\n2. Se não souber, troque a ordem (7 × 3 = 3 × 7).\n3. Ou quebre: 7 × 6 = 7 × 5 + 7 = 35 + 7 = 42.\n4. Confira com a soma repetida.'),
    block('propriedades', 'Regras que ajudam', 'Trocar a ordem dos fatores não muda o produto: 3 × 4 = 4 × 3. Qualquer número vezes 1 é ele mesmo, e qualquer número vezes 0 é zero.', '8 × 1 = 8 · 8 × 0 = 0 · 2 × 9 = 9 × 2 = 18.',
      '3 × 4 e 4 × 3 dão o mesmo: 12. Vezes 1 não muda nada. Vezes 0 dá sempre 0.', '3 fileiras de 4 cadeiras ou 4 fileiras de 3: são 12 cadeiras do mesmo jeito.', '1. Se ficar mais fácil, troque a ordem dos fatores.\n2. Viu × 1? O resultado é o próprio número.\n3. Viu × 0? O resultado é 0.\n4. Use isso para conferir contas grandes.'),
    block('problemas', 'Usando no dia a dia', 'Para resolver um problema, procure grupos iguais: quantos grupos existem e quantas coisas há em cada grupo. "Dobro" é × 2 e "triplo" é × 3.', 'Uma caixa tem 6 ovos. Em 5 caixas há 5 × 6 = 30 ovos.',
      'Pergunte: quantos grupos? Quantos em cada grupo? Depois faça a conta de vezes.', 'Um ingresso custa R$ 8. Para 4 pessoas: 4 × 8 = R$ 32.', '1. Leia e encontre os grupos iguais.\n2. Anote quantos grupos e quantos por grupo.\n3. Multiplique.\n4. Responda com a unidade (ovos, reais…).'),
  ],
  questions: [
    mc(1, 'conceito', '4 + 4 + 4 é o mesmo que:', ['4 × 4', '3 × 4', '4 + 3', '12 × 4'], 1, ['Conte quantas vezes o 4 aparece.', 'O 4 aparece 3 vezes.', '3 grupos de 4.'], 'São 3 parcelas iguais a 4: 3 × 4 = 12.'),
    fill(1, 'tabuada', 'Quanto é 7 × 2?', ['14'], ['× 2 é o dobro.', 'Qual é o dobro de 7?', '7 + 7.'], '7 × 2 = 14, o dobro de 7.'),
    mc(1, 'tabuada', 'Quanto é 6 × 10?', ['16', '60', '600', '61'], 1, ['Na tabuada do 10 tem um truque.', 'Coloque um zero no fim.', '6 com um zero.'], '6 × 10 = 60.'),
    tf(1, 'propriedades', '3 × 5 dá o mesmo resultado que 5 × 3.', true, ['A ordem muda o resultado da multiplicação?', 'Faça as duas contas.', '15 e 15.'], 'Verdadeiro: a ordem dos fatores não altera o produto.'),
    mc(2, 'propriedades', 'Quanto é 9 × 0?', ['9', '0', '90', '1'], 1, ['Pense em 9 grupos com nada dentro.', 'Quantas coisas há no total?', 'Nenhuma.'], 'Qualquer número vezes 0 dá 0.'),
    fill(2, 'problemas', 'Uma caixa tem 6 ovos. Quantos ovos há em 5 caixas?', ['30'], ['Quantos grupos? Quantos em cada?', '5 caixas com 6 ovos.', '5 × 6.'], '5 × 6 = 30 ovos.'),
    match(2, 'tabuada', 'Ligue cada conta ao resultado.', [['2 × 8', '16'], ['5 × 4', '20'], ['3 × 3', '9'], ['10 × 7', '70']], ['Comece pela do 10.', '5 × 4 termina em 0.', '2 × 8 é o dobro de 8.'], '2 × 8 = 16 · 5 × 4 = 20 · 3 × 3 = 9 · 10 × 7 = 70.'),
    tf(2, 'tabuada', 'Todos os resultados da tabuada do 5 terminam em 0 ou 5.', true, ['Teste alguns: 5, 10, 15…', 'Veja o último algarismo.', 'Só aparecem 0 e 5.'], 'Verdadeiro: 5, 10, 15, 20, 25…'),
    mc(3, 'problemas', 'Uma sala tem 4 fileiras com 7 cadeiras cada. Quantas cadeiras há?', ['11', '28', '24', '47'], 1, ['São grupos iguais.', '4 grupos de 7.', '4 × 7.'], '4 × 7 = 28 cadeiras.'),
    fill(3, 'tabuada', 'Quanto é 8 × 7?', ['56'], ['Pense em 7 × 8.', '7 × 7 = 49.', '49 + 7.'], '8 × 7 = 56.'),
    mc(3, 'problemas', 'Ana tem 6 anos. Seu pai tem o quíntuplo da idade dela. Quantos anos tem o pai?', ['11', '30', '36', '25'], 1, ['Quíntuplo = 5 vezes.', 'Multiplique a idade de Ana por 5.', '6 × 5.'], 'Quíntuplo de 6 = 6 × 5 = 30 anos.'),
    open(3, 'conceito', 'Explique com suas palavras por que 3 × 4 = 12, sem usar a tabuada.', 'Porque 3 × 4 significa três grupos de 4 e, somando 4 + 4 + 4, obtemos 12.', ['grupos', 'soma', 'somar', '4 + 4', 'vezes'], ['O que "3 vezes 4" significa?', 'Três grupos de quê?', 'Some esses grupos.'], 'Multiplicar é somar parcelas iguais: 4 + 4 + 4 = 12.'),
  ],
  review: ['Multiplicar = somar parcelas iguais (fatores → produto)', '× 2 é o dobro · × 10 põe um zero', 'A ordem não muda o resultado', '× 1 não muda · × 0 dá zero'],
  relatedQuestions: ['Como aprender a tabuada?', 'O que é multiplicar?', 'Como fazer conta de vezes?'],
  equivalentQuestions: ['como decorar a tabuada', 'truque para tabuada', 'quanto é 7 vezes 8', 'como fazer conta de vezes', 'o que significa 3 vezes 4', 'o que é produto na matematica', 'o que são fatores da multiplicação', 'como multiplicar numeros grandes', 'qualquer numero vezes zero da quanto', 'a ordem muda na multiplicação', 'o que é dobro e triplo', 'como calcular o quíntuplo', 'tabuada do 9 truque', 'tabuada do 7 como aprender', 'como saber quantas coisas tem em varias caixas', 'problema de multiplicação exemplo', 'me explica multiplicação', 'multiplicação é soma repetida', 'por que 5 vezes 0 da zero', 'como fazer multiplicação de cabeça', 'quando usar conta de vezes no problema'],
  commonDoubts: [
    { q: 'Por que qualquer número vezes zero dá zero?', a: 'Porque são grupos vazios: 5 × 0 é "5 grupos de nada", que dá nada.' },
    { q: 'Não decorei a tabuada. E agora?', a: 'Use a soma repetida ou quebre a conta: 7 × 6 = 7 × 5 + 7 = 35 + 7 = 42.' },
  ],
  commonErrors: ['Confundir × 0 com × 1 (8 × 0 é 0, e 8 × 1 é 8)', 'Somar em vez de multiplicar: fazer 4 + 7 quando o problema pede 4 grupos de 7'],
  formulas: [formula('Multiplicação', 'a × b = produto', [['a', 'número de grupos'], ['b', 'quantidade em cada grupo'], ['produto', 'total']], 'quando os grupos têm o mesmo tamanho')],
  sources: FONTES,
})

export const divisao = lesson({
  id: 'mat-divisao', subject: 'matematica', title: 'Divisão', levels: ['fund1', 'fund2'], grade: '3º ao 5º ano',
  topic: 'Operações', subtopic: 'Divisão',
  aliases: ['divisao', 'dividir', 'conta de dividir', 'resto da divisao', 'dividendo divisor quociente', 'divisao exata', 'repartir', 'metade', 'terca parte'],
  summary: 'Aprenda a dividir em partes iguais, entenda o resto e confira a divisão com a multiplicação.',
  intro: 'Dividir é repartir em partes iguais ou descobrir quantas vezes uma quantidade cabe em outra.',
  objective: 'Resolver divisões exatas e não exatas, interpretar o resto e usar a divisão em problemas.',
  prerequisites: ['mat-multiplicacao'], next: ['mat-fracoes', 'mat-mmc-mdc'],
  skills: { conceito: 'Ideia de dividir', termos: 'Termos e resto', algoritmo: 'Conta de dividir', problemas: 'Problemas com divisão' },
  blocks: [
    block('conceito', 'Repartir em partes iguais', 'Dividir é repartir uma quantidade em partes iguais, ou descobrir quantas vezes um número cabe em outro. A divisão é a operação inversa da multiplicação.', '12 balas para 3 crianças: 12 ÷ 3 = 4 balas para cada uma, porque 3 × 4 = 12.',
      'Dividir é dar a mesma quantidade para todo mundo.', 'Uma pizza de 8 pedaços dividida entre 4 amigos: cada um come 8 ÷ 4 = 2 pedaços.', '1. Veja quanto há no total.\n2. Veja em quantas partes vai dividir.\n3. Pergunte: que número vezes as partes dá o total?\n4. Esse número é a resposta.'),
    block('termos', 'Dividendo, divisor, quociente e resto', 'Em 17 ÷ 5: 17 é o dividendo, 5 é o divisor, 3 é o quociente e 2 é o resto. Quando o resto é 0, a divisão é exata. O resto é sempre menor que o divisor.', '17 ÷ 5 = 3 e sobra 2, porque 5 × 3 + 2 = 17.',
      'O que sobra e não dá para repartir é o resto.', '17 figurinhas para 5 amigos: cada um ganha 3 e sobram 2 figurinhas.', '1. Veja quantas vezes o divisor cabe no dividendo.\n2. Multiplique para ver quanto foi usado.\n3. Subtraia: o que sobrar é o resto.\n4. Confira: divisor × quociente + resto = dividendo.'),
    block('algoritmo', 'A conta armada', 'Na conta armada dividimos parte por parte, da esquerda para a direita: dividimos, multiplicamos, subtraímos e "baixamos" o próximo algarismo.', '84 ÷ 4: 8 ÷ 4 = 2; baixa o 4; 4 ÷ 4 = 1. Resultado 21.',
      'Divida um algarismo de cada vez, começando pela esquerda.', 'Dividir R$ 96 entre 3 pessoas: 9 ÷ 3 = 3 e 6 ÷ 3 = 2 → R$ 32 para cada.', '1. Pegue o primeiro algarismo (ou os dois primeiros, se precisar).\n2. Divida e escreva no quociente.\n3. Multiplique e subtraia.\n4. Baixe o próximo algarismo e repita até acabar.'),
    block('problemas', 'Quando dividir', 'Use a divisão quando o problema fala em repartir igualmente, "cada um", "metade" (÷ 2), "terça parte" (÷ 3) ou "quantos grupos cabem".', 'Uma van leva 9 pessoas. Para 30 pessoas: 30 ÷ 9 = 3 e resto 3 → são necessárias 4 vans.',
      '"Cada um recebe quanto?" → divide.', 'Um livro de 60 páginas lido em 5 dias iguais: 60 ÷ 5 = 12 páginas por dia.', '1. Encontre o total e o número de partes.\n2. Divida.\n3. Pense no resto: ele sobra, ou exige mais um grupo?\n4. Responda à pergunta do problema.'),
  ],
  questions: [
    mc(1, 'conceito', '12 balas divididas igualmente entre 3 crianças. Quantas balas cada uma recebe?', ['3', '4', '9', '36'], 1, ['Que número vezes 3 dá 12?', '3 × ? = 12.', '3 × 4 = 12.'], '12 ÷ 3 = 4.'),
    fill(1, 'conceito', 'Quanto é 20 ÷ 5?', ['4'], ['5 × ? = 20.', 'Conte de 5 em 5 até 20.', '5, 10, 15, 20.'], '20 ÷ 5 = 4.'),
    tf(1, 'termos', 'Numa divisão exata, o resto é zero.', true, ['Exata = não sobra nada.', 'O que é o resto?', 'O que sobra.'], 'Verdadeiro.'),
    match(2, 'termos', 'Em 17 ÷ 5 = 3, resto 2, ligue cada número ao nome.', [['17', 'Dividendo'], ['5', 'Divisor'], ['3', 'Quociente'], ['2', 'Resto']], ['O que está sendo dividido é o dividendo.', 'O resultado é o quociente.', 'O que sobra é o resto.'], '17 dividendo · 5 divisor · 3 quociente · 2 resto.'),
    mc(2, 'algoritmo', 'Quanto é 84 ÷ 4?', ['12', '21', '24', '41'], 1, ['Comece pelo 8.', '8 ÷ 4 = 2; depois 4 ÷ 4.', 'Junte: 2 e 1.'], '84 ÷ 4 = 21. Confira: 4 × 21 = 84.'),
    fill(2, 'termos', 'Qual é o resto de 17 ÷ 5?', ['2'], ['Quantas vezes o 5 cabe no 17?', '3 vezes: 15.', '17 − 15.'], '5 × 3 = 15; 17 − 15 = 2.'),
    tf(2, 'termos', 'O resto pode ser maior que o divisor.', false, ['Se o resto fosse maior, caberia mais uma vez?', 'Sim, caberia.', 'Então a divisão não teria terminado.'], 'Falso: o resto é sempre menor que o divisor.'),
    mc(2, 'problemas', 'Um livro de 60 páginas será lido em 5 dias, a mesma quantidade por dia. Quantas páginas por dia?', ['55', '12', '15', '300'], 1, ['"A mesma quantidade por dia" é repartir.', '60 ÷ 5.', '5 × 12 = 60.'], '60 ÷ 5 = 12 páginas por dia.'),
    mc(3, 'problemas', 'Uma van leva 9 pessoas. Quantas vans são necessárias para 30 pessoas?', ['3', '4', '21', '270'], 1, ['30 ÷ 9 = 3 e sobra algo.', 'O resto é 3 pessoas.', 'Essas 3 pessoas também precisam ir!'], '30 ÷ 9 = 3 resto 3: as 3 pessoas que sobram precisam de mais uma van → 4 vans.'),
    fill(3, 'algoritmo', 'Quanto é 156 ÷ 12?', ['13'], ['12 cabe uma vez em 15.', '15 − 12 = 3; baixe o 6: 36.', '36 ÷ 12 = 3.'], '156 ÷ 12 = 13. Confira: 12 × 13 = 156.'),
    order(2, 'algoritmo', 'Coloque os passos da conta de dividir na ordem.', ['Dividir', 'Multiplicar', 'Subtrair', 'Baixar o próximo algarismo'], ['Primeiro vemos quantas vezes cabe.', 'Depois calculamos quanto foi usado.', 'Por fim, sobra algo e baixamos o próximo.'], 'Dividir → multiplicar → subtrair → baixar, e repetir.'),
    open(3, 'termos', 'Como você confere se 47 ÷ 6 = 7, resto 5, está certo?', 'Multiplico o divisor pelo quociente e somo o resto: 6 × 7 + 5 = 42 + 5 = 47. Como deu o dividendo, está certo.', ['multiplic', 'resto', 'soma', '47', 'dividendo'], ['A divisão é o contrário de qual conta?', 'Multiplique 6 × 7.', 'Some o resto.'], 'Divisor × quociente + resto = dividendo.'),
  ],
  review: ['Dividir = repartir igualmente (inverso da multiplicação)', 'Dividendo ÷ divisor = quociente (+ resto)', 'Resto é sempre menor que o divisor', 'Prova: divisor × quociente + resto = dividendo'],
  relatedQuestions: ['Como fazer conta de dividir?', 'O que é o resto da divisão?', 'Como conferir uma divisão?'],
  equivalentQuestions: ['como dividir numeros', 'como fazer conta de dividir armada', 'o que é quociente', 'o que é dividendo e divisor', 'o que fazer com o resto', 'o que é divisão exata', 'como dividir por 12', 'como saber quanto cada um recebe', 'como repartir igualmente', 'quanto é 84 dividido por 4', 'como fazer a prova real da divisão', 'o resto pode ser maior que o divisor', 'o que é metade de um número', 'como calcular a terça parte', 'divisão com resto exemplo', 'quantas vans preciso problema de divisão', 'me explica divisão', 'não sei dividir', 'dividir é o contrário de multiplicar', 'como baixar o numero na divisão', 'divisão com dois algarismos no divisor'],
  commonDoubts: [
    { q: 'Posso dividir por zero?', a: 'Não. Não existe número que multiplicado por 0 dê, por exemplo, 5 — por isso a divisão por zero não é definida.' },
    { q: 'O que faço com o resto no problema?', a: 'Depende da pergunta: às vezes ele sobra (figurinhas), às vezes exige mais um grupo (vans, ônibus).' },
  ],
  commonErrors: ['Esquecer de "baixar" um algarismo e pular um zero no quociente (ex.: 612 ÷ 6 = 102, não 12)', 'Deixar resto maior que o divisor', 'Ignorar o resto em problemas que precisam de mais um grupo'],
  formulas: [formula('Relação fundamental da divisão', 'D = d × q + r', [['D', 'dividendo'], ['d', 'divisor (diferente de zero)'], ['q', 'quociente'], ['r', 'resto (0 ≤ r < d)']])],
  sources: FONTES,
})

export const formasGeometricas = lesson({
  id: 'mat-formas-geometricas', subject: 'matematica', title: 'Figuras geométricas planas e espaciais', levels: ['fund1'], grade: '1º ao 5º ano',
  topic: 'Geometria', subtopic: 'Figuras planas e sólidos',
  aliases: ['figuras geometricas', 'formas geometricas', 'triangulo quadrado retangulo circulo', 'solidos geometricos', 'cubo esfera cilindro piramide', 'faces vertices arestas', 'poligonos', 'geometria espacial basica'],
  summary: 'Reconheça figuras planas (triângulo, quadrado…) e sólidos (cubo, esfera…), com seus lados, faces, vértices e arestas.',
  intro: 'Olhe ao redor: uma janela lembra um retângulo, uma bola é uma esfera. A geometria está em tudo!',
  objective: 'Identificar e classificar figuras planas e sólidos geométricos pelos seus elementos.',
  next: ['mat-area-perimetro', 'mat-angulos'],
  skills: { planas: 'Figuras planas', poligonos: 'Polígonos: lados e vértices', solidos: 'Sólidos geométricos', elementos: 'Faces, arestas e vértices' },
  blocks: [
    block('planas', 'Figuras planas', 'Figuras planas são "achatadas": têm comprimento e largura, mas não têm altura. Exemplos: triângulo, quadrado, retângulo e círculo.', 'O desenho de uma placa de trânsito no papel é uma figura plana.',
      'Plana é a figura que dá para desenhar inteira no papel.', 'Uma folha de sulfite lembra um retângulo; o fundo de um copo lembra um círculo.', '1. Veja se a figura é "achatada".\n2. Conte os lados.\n3. Veja se os lados são retos ou curvos.\n4. Dê o nome: 3 lados triângulo, 4 lados quadrilátero, sem lados retos círculo.'),
    block('poligonos', 'Polígonos: lados e vértices', 'Polígonos são figuras planas fechadas formadas só por segmentos de reta (lados). O ponto onde dois lados se encontram é um vértice. O círculo não é polígono, pois não tem lados retos.', 'Triângulo: 3 lados e 3 vértices. Quadrado: 4 lados iguais e 4 ângulos retos. Pentágono: 5 lados. Hexágono: 6 lados.',
      'Conte os lados: 3 é triângulo, 4 é quadrilátero, 5 é pentágono, 6 é hexágono.', 'Os favos de mel das abelhas têm formato de hexágono: 6 lados.', '1. Confira se a figura é fechada e tem só lados retos.\n2. Conte os lados.\n3. O número de vértices é igual ao de lados.\n4. Use o nome: tri (3), quadri (4), penta (5), hexa (6).'),
    block('solidos', 'Sólidos geométricos', 'Sólidos (figuras espaciais) têm comprimento, largura e altura: ocupam lugar no espaço. Os que têm só superfícies planas são poliedros (cubo, pirâmide, prisma). Os que têm parte arredondada são corpos redondos (esfera, cilindro, cone).', 'Um dado é um cubo; uma lata é um cilindro; uma casquinha de sorvete lembra um cone; uma bola é uma esfera.',
      'Sólido é o que dá para pegar na mão, como um dado ou uma bola.', 'Na cozinha: caixa de leite (prisma), lata de milho (cilindro), laranja (esfera).', '1. Veja se o objeto rola.\n2. Se rola, é corpo redondo (esfera, cilindro, cone).\n3. Se não rola e só tem partes planas, é poliedro.\n4. Compare com os modelos: cubo, prisma, pirâmide.'),
    block('elementos', 'Faces, arestas e vértices', 'Nos poliedros, cada superfície plana é uma face, cada "quina" onde duas faces se encontram é uma aresta e cada ponta é um vértice. O cubo tem 6 faces, 12 arestas e 8 vértices.', 'Um dado tem 6 faces (os lados com números), 12 arestas e 8 pontas (vértices).',
      'Face é o lado chato, aresta é a dobra, vértice é a ponta.', 'Numa caixa de sapato: as tampas e os lados são faces, as dobras são arestas e os cantos são vértices.', '1. Conte as superfícies planas: faces.\n2. Conte as "linhas" onde as faces se juntam: arestas.\n3. Conte as pontas: vértices.\n4. Confira no cubo: 6, 12 e 8.'),
  ],
  questions: [
    mc(1, 'poligonos', 'Quantos lados tem um triângulo?', ['2', '3', '4', '5'], 1, ['"Tri" quer dizer…', 'Triciclo tem 3 rodas.', 'Três.'], 'O triângulo tem 3 lados e 3 vértices.'),
    mc(1, 'solidos', 'Uma bola de futebol lembra qual sólido?', ['Cubo', 'Cilindro', 'Esfera', 'Pirâmide'], 2, ['Ela rola para todos os lados.', 'Não tem nenhuma parte plana.', 'É toda redonda.'], 'A bola lembra uma esfera.'),
    tf(1, 'poligonos', 'O círculo é um polígono.', false, ['Polígono tem lados retos.', 'O círculo tem lados retos?', 'Não, é todo curvo.'], 'Falso: o círculo não tem lados retos, então não é polígono.'),
    match(2, 'solidos', 'Ligue o objeto ao sólido que ele lembra.', [['Dado', 'Cubo'], ['Lata de refrigerante', 'Cilindro'], ['Casquinha de sorvete', 'Cone'], ['Laranja', 'Esfera']], ['O dado tem 6 faces iguais.', 'A lata tem duas bases redondas.', 'A casquinha tem uma ponta.'], 'Dado–cubo · lata–cilindro · casquinha–cone · laranja–esfera.'),
    fill(2, 'elementos', 'Quantas faces tem um cubo?', ['6', 'seis'], ['Pense num dado.', 'Os números vão de 1 a…', 'Cada número está numa face.'], 'O cubo tem 6 faces.'),
    mc(2, 'poligonos', 'Uma figura plana com 6 lados se chama:', ['Pentágono', 'Hexágono', 'Octógono', 'Quadrilátero'], 1, ['Pense nos favos de mel.', '"Hexa" significa 6.', 'Hexa + gono.'], 'Hexágono: 6 lados.'),
    tf(2, 'planas', 'Um quadrado tem 4 lados iguais.', true, ['Compare o quadrado com o retângulo.', 'No retângulo, os lados podem ser diferentes.', 'No quadrado, todos são iguais.'], 'Verdadeiro: 4 lados iguais e 4 ângulos retos.'),
    mc(2, 'solidos', 'Qual destes sólidos NÃO rola?', ['Esfera', 'Cilindro', 'Cone', 'Cubo'], 3, ['Corpos redondos rolam.', 'Quem só tem faces planas não rola.', 'O dado rola ou tomba?'], 'O cubo só tem faces planas: não rola.'),
    fill(3, 'elementos', 'Quantos vértices (pontas) tem um cubo?', ['8', 'oito'], ['Conte as pontas de cima.', 'São 4 em cima.', 'E mais 4 embaixo.'], '4 em cima + 4 embaixo = 8 vértices.'),
    mc(3, 'elementos', 'Quantas arestas tem um cubo?', ['6', '8', '12', '24'], 2, ['Aresta é a "dobra" entre duas faces.', 'Conte 4 em cima e 4 embaixo.', 'Mais as 4 que ligam cima e embaixo.'], '4 + 4 + 4 = 12 arestas.'),
    mc(3, 'poligonos', 'Quantos vértices tem um pentágono?', ['4', '5', '6', '10'], 1, ['Num polígono, vértices e lados são iguais em número.', '"Penta" = 5.', '5 lados → 5 vértices.'], 'Pentágono: 5 lados e 5 vértices.'),
    open(3, 'solidos', 'Qual é a diferença entre uma figura plana e um sólido geométrico?', 'A figura plana tem só comprimento e largura e pode ser desenhada inteira no papel. O sólido tem também altura: ocupa lugar no espaço, como um dado ou uma bola.', ['altura', 'espaco', 'papel', 'plana', 'tres dimens', 'ocupa'], ['Pense num quadrado e num cubo.', 'Qual deles dá para segurar?', 'Fale de altura ou de ocupar espaço.'], 'Plana: 2 dimensões. Sólido: 3 dimensões.'),
  ],
  review: ['Planas: triângulo, quadrado, retângulo, círculo', 'Polígonos têm lados retos; nº de lados = nº de vértices', 'Sólidos: poliedros (não rolam) e corpos redondos (rolam)', 'Cubo: 6 faces, 12 arestas, 8 vértices'],
  relatedQuestions: ['Quais são as figuras geométricas?', 'Quantas faces tem um cubo?', 'O que é aresta e vértice?'],
  equivalentQuestions: ['quais sao as formas geometricas', 'o que é figura plana', 'o que é solido geometrico', 'qual a diferença entre quadrado e retangulo', 'quantos lados tem um hexagono', 'o que é poligono', 'circulo é poligono', 'o que é vertice', 'o que é aresta', 'o que é face de um solido', 'quantas arestas tem o cubo', 'quantos vertices tem o cubo', 'quais objetos tem forma de cilindro', 'o que é um cone', 'o que é piramide na geometria', 'qual solido rola', 'nome das figuras com 5 lados', 'o que é corpo redondo', 'o que é poliedro', 'me explica figuras geometricas', 'como diferenciar prisma e piramide'],
  commonDoubts: [
    { q: 'O quadrado é um retângulo?', a: 'Sim! O retângulo tem 4 ângulos retos; o quadrado também tem, e ainda tem os 4 lados iguais. Todo quadrado é um retângulo especial.' },
    { q: 'Qual a diferença entre círculo e esfera?', a: 'O círculo é plano (desenho no papel). A esfera é um sólido (como uma bola).' },
  ],
  commonErrors: ['Chamar o cubo de quadrado (quadrado é plano, cubo é sólido)', 'Achar que o círculo é polígono', 'Contar arestas só de uma face do cubo'],
  sources: FONTES,
})

export const medidas = lesson({
  id: 'mat-medidas', subject: 'matematica', title: 'Medidas de comprimento, massa e capacidade', levels: ['fund1', 'fund2'], grade: '3º ao 6º ano',
  topic: 'Grandezas e medidas', subtopic: 'Unidades de medida',
  aliases: ['medidas', 'unidades de medida', 'metro centimetro quilometro', 'grama quilograma', 'litro mililitro', 'converter medidas', 'transformar unidades', 'comprimento massa capacidade'],
  summary: 'Conheça metro, grama e litro, seus múltiplos e submúltiplos, e aprenda a converter entre eles.',
  intro: 'Quanto você mede? Quanto pesa um pacote de arroz? Quanto cabe numa garrafa? Vamos medir!',
  objective: 'Usar unidades de comprimento, massa e capacidade e converter entre elas.',
  prerequisites: ['mat-multiplicacao', 'mat-divisao'], next: ['mat-area-perimetro', 'mat-numeros-decimais'],
  skills: { comprimento: 'Comprimento', massa: 'Massa', capacidade: 'Capacidade', conversao: 'Conversão de unidades' },
  blocks: [
    block('comprimento', 'Comprimento: metro', 'Comprimento é medido em metro (m). 1 m = 100 centímetros (cm) = 1.000 milímetros (mm). Para distâncias grandes, usamos o quilômetro: 1 km = 1.000 m.', 'Uma porta tem cerca de 2 m de altura. De uma cidade a outra podem ser 50 km.',
      'Régua mede em centímetros. Estrada mede em quilômetros.', 'Uma criança de 1,30 m tem 130 cm de altura.', '1. Escolha a unidade pelo tamanho: mm (muito pequeno), cm (objetos), m (salas, pessoas), km (estradas).\n2. Lembre: 1 km = 1.000 m.\n3. 1 m = 100 cm.\n4. 1 cm = 10 mm.'),
    block('massa', 'Massa: grama e quilograma', 'Massa (o que chamamos de "peso" no dia a dia) é medida em grama (g) e quilograma (kg). 1 kg = 1.000 g. Para coisas muito leves, usamos o miligrama (mg): 1 g = 1.000 mg.', 'Um pacote de arroz tem 5 kg; um pacote de biscoito, 200 g.',
      'Coisas leves em gramas, coisas pesadas em quilos.', 'Meio quilo de carne são 500 g.', '1. Veja se o objeto é leve ou pesado.\n2. Leve: gramas. Pesado: quilogramas.\n3. Para passar kg para g, multiplique por 1.000.\n4. Para passar g para kg, divida por 1.000.'),
    block('capacidade', 'Capacidade: litro', 'Capacidade é quanto cabe dentro de um recipiente. Usamos o litro (L) e o mililitro (mL): 1 L = 1.000 mL.', 'Uma garrafa de refrigerante pode ter 2 L; uma lata, 350 mL.',
      'Litro é para quanto cabe de líquido.', 'Um copo de 250 mL: quatro copos enchem 1 litro (4 × 250 = 1.000).', '1. Pergunte: quanto cabe?\n2. Muito líquido: litros.\n3. Pouco líquido: mililitros.\n4. 1 L = 1.000 mL.'),
    block('conversao', 'Convertendo unidades', 'Para passar de uma unidade maior para uma menor, multiplicamos; da menor para a maior, dividimos. Os prefixos ajudam: quilo = 1.000, centi = 1/100, mili = 1/1.000.', '3 km = 3 × 1.000 = 3.000 m. 2.500 g = 2.500 ÷ 1.000 = 2,5 kg.',
      'De grande para pequeno: multiplica. De pequeno para grande: divide.', 'Uma corrida de 5 km tem 5.000 m.', '1. Descubra a relação (ex.: 1 km = 1.000 m).\n2. Indo para uma unidade menor, multiplique.\n3. Indo para uma unidade maior, divida.\n4. Escreva o resultado com a nova unidade.'),
  ],
  questions: [
    mc(1, 'comprimento', 'Quantos centímetros há em 1 metro?', ['10', '100', '1.000', '12'], 1, ['"Centi" lembra cem.', 'Uma régua grande de 1 m tem…', '100 cm.'], '1 m = 100 cm.'),
    mc(1, 'massa', 'Qual unidade é melhor para medir a massa de um pacote de arroz?', ['Metro', 'Litro', 'Quilograma', 'Centímetro'], 2, ['Arroz não se mede pelo tamanho.', 'Queremos saber o "peso".', 'Massa: grama ou quilograma.'], 'Massa é medida em kg (quilograma).'),
    tf(1, 'capacidade', 'O litro é usado para medir capacidade.', true, ['Capacidade é quanto cabe.', 'Refrigerante vem em…', 'Litros!'], 'Verdadeiro.'),
    fill(2, 'conversao', 'Quantos metros há em 3 km?', ['3000', '3.000'], ['1 km = 1.000 m.', 'De km para m, multiplique.', '3 × 1.000.'], '3 km = 3.000 m.'),
    mc(2, 'conversao', '2.500 g equivalem a:', ['25 kg', '2,5 kg', '250 kg', '0,25 kg'], 1, ['1 kg = 1.000 g.', 'De g para kg, divida por 1.000.', '2.500 ÷ 1.000.'], '2.500 g = 2,5 kg.'),
    match(2, 'comprimento', 'Ligue cada medida à unidade mais adequada.', [['Distância entre cidades', 'Quilômetro'], ['Comprimento de um lápis', 'Centímetro'], ['Espessura de uma moeda', 'Milímetro'], ['Altura de uma porta', 'Metro']], ['Distâncias grandes: km.', 'Objetos pequenos: cm.', 'Coisas muito finas: mm.'], 'Cidades–km · lápis–cm · moeda–mm · porta–m.'),
    fill(2, 'capacidade', 'Quantos mililitros há em 1 litro?', ['1000', '1.000'], ['"Mili" = milésima parte.', 'São mil partes.', '1 L = … mL.'], '1 L = 1.000 mL.'),
    tf(2, 'massa', '1 kg de algodão tem a mesma massa que 1 kg de ferro.', true, ['Os dois têm 1 kg.', 'O volume é diferente, a massa não.', '1 kg é 1 kg.'], 'Verdadeiro: a massa é a mesma; o algodão só ocupa mais espaço.'),
    mc(3, 'capacidade', 'Quantos copos de 250 mL enchem uma jarra de 2 L?', ['4', '8', '10', '250'], 1, ['2 L = 2.000 mL.', 'Quantas vezes 250 cabe em 2.000?', '2.000 ÷ 250.'], '2.000 ÷ 250 = 8 copos.'),
    fill(3, 'conversao', 'Uma criança mede 1,35 m. Quantos centímetros ela tem?', ['135', '135 cm'], ['1 m = 100 cm.', 'Multiplique por 100.', '1,35 × 100.'], '1,35 × 100 = 135 cm.'),
    order(3, 'comprimento', 'Ordene do MENOR para o MAIOR.', ['8 mm', '5 cm', '2 m', '1 km'], ['Converta tudo para a mesma unidade.', '8 mm < 50 mm (5 cm).', '1 km = 1.000 m.'], '8 mm < 5 cm (50 mm) < 2 m < 1 km.'),
    open(3, 'conversao', 'Explique como transformar quilômetros em metros, com um exemplo.', 'Como 1 km tem 1.000 m, multiplico o número de quilômetros por 1.000. Por exemplo, 4 km = 4 × 1.000 = 4.000 m.', ['1000', 'multiplic', 'metros', 'quilometro'], ['Quantos metros tem 1 km?', 'De maior para menor: multiplica ou divide?', 'Dê um exemplo com números.'], 'km → m: multiplica por 1.000.'),
  ],
  review: ['Comprimento: 1 km = 1.000 m · 1 m = 100 cm · 1 cm = 10 mm', 'Massa: 1 kg = 1.000 g', 'Capacidade: 1 L = 1.000 mL', 'Maior → menor: multiplica · menor → maior: divide'],
  relatedQuestions: ['Como transformar km em metros?', 'Quantos gramas tem 1 kg?', 'Quantos mL tem 1 litro?'],
  equivalentQuestions: ['quantos cm tem um metro', 'como converter metros em centimetros', 'quantos metros tem um quilometro', 'como transformar gramas em quilos', 'quantas gramas tem meio quilo', 'quantos ml tem 1 litro', 'como converter litros em mililitros', 'qual unidade usar para medir peso', 'diferença entre massa e peso', 'o que significa quilo centi e mili', 'como saber se multiplico ou divido na conversão', '1,35 m em centimetros', 'quantos mm tem 1 cm', 'como medir capacidade', 'unidade de medida de comprimento', 'o que é capacidade na matematica', 'quantos copos de 250 ml tem 1 litro', 'me explica medidas', 'tabela de conversão de medidas', '2500 gramas em kg', 'como passar de km para m'],
  commonDoubts: [
    { q: 'Massa e peso são a mesma coisa?', a: 'No dia a dia usamos como sinônimos, mas na Física massa (kg) é a quantidade de matéria e peso é a força da gravidade sobre ela (em newtons).' },
    { q: 'Como lembrar se multiplico ou divido?', a: 'Indo para uma unidade menor, o número fica maior (multiplica). Indo para uma unidade maior, o número fica menor (divide).' },
  ],
  commonErrors: ['Dividir quando deveria multiplicar (3 km = 3.000 m, não 0,003 m)', 'Achar que 1 m = 10 cm', 'Comparar medidas em unidades diferentes sem converter'],
  formulas: [formula('Relações principais', '1 km = 1.000 m · 1 m = 100 cm · 1 kg = 1.000 g · 1 L = 1.000 mL', [['k (quilo)', '× 1.000'], ['c (centi)', '÷ 100'], ['m (mili)', '÷ 1.000']])],
  sources: FONTES,
})

export const sistemaMonetario = lesson({
  id: 'mat-sistema-monetario', subject: 'matematica', title: 'Sistema monetário: dinheiro e troco', levels: ['fund1'], grade: '2º ao 5º ano',
  topic: 'Grandezas e medidas', subtopic: 'Sistema monetário brasileiro',
  aliases: ['sistema monetario', 'dinheiro', 'real', 'moedas e cedulas', 'troco', 'centavos', 'reais e centavos', 'contar dinheiro', 'compras'],
  summary: 'Conheça o real, as moedas e cédulas, e aprenda a calcular preços, totais e troco.',
  intro: 'Ir à padaria, comprar um lanche, receber troco… Usamos matemática com dinheiro o tempo todo!',
  objective: 'Reconhecer cédulas e moedas do real, fazer trocas equivalentes e calcular totais e troco.',
  prerequisites: ['mat-adicao-subtracao'], next: ['mat-numeros-decimais'],
  skills: { real: 'Real e centavos', trocas: 'Trocas equivalentes', total: 'Calcular o total', troco: 'Calcular o troco' },
  blocks: [
    block('real', 'O real e os centavos', 'A moeda do Brasil é o real (R$). 1 real = 100 centavos. Há moedas de 5, 10, 25 e 50 centavos e de 1 real, e cédulas de 2, 5, 10, 20, 50, 100 e 200 reais.', 'R$ 3,50 lê-se "três reais e cinquenta centavos".',
      'Cem centavos fazem 1 real.', 'Duas moedas de 50 centavos valem R$ 1,00.', '1. Os números antes da vírgula são reais.\n2. Os dois números depois da vírgula são centavos.\n3. 100 centavos = R$ 1,00.\n4. Leia: "x reais e y centavos".'),
    block('trocas', 'Trocas que valem o mesmo', 'Podemos formar o mesmo valor com cédulas e moedas diferentes. Trocar uma nota de R$ 10 por duas de R$ 5 não muda o valor.', 'R$ 20 = 2 notas de R$ 10 = 4 notas de R$ 5 = 10 notas de R$ 2.',
      'O valor é o mesmo, só muda o jeito de juntar.', 'Para pagar R$ 1,00 você pode usar 4 moedas de 25 centavos.', '1. Veja o valor que quer formar.\n2. Escolha as cédulas maiores que cabem.\n3. Complete com as menores e moedas.\n4. Some para conferir.'),
    block('total', 'Quanto vou pagar?', 'Para saber o total de uma compra, somamos os preços. Com vírgula, alinhamos a vírgula: reais embaixo de reais e centavos embaixo de centavos.', 'Suco R$ 4,50 + pão R$ 2,30 = R$ 6,80.',
      'Some os preços de tudo que você comprou.', 'Um caderno de R$ 12,00 e um lápis de R$ 1,50 custam juntos R$ 13,50.', '1. Escreva os preços um embaixo do outro, vírgula embaixo de vírgula.\n2. Some os centavos.\n3. Se passar de 100 centavos, vira 1 real.\n4. Some os reais.'),
    block('troco', 'Quanto recebo de troco?', 'Troco é o dinheiro que volta: valor pago menos o preço. Dá para calcular "completando": do preço, conte até o valor pago.', 'Paguei R$ 10 por algo de R$ 6,80: 6,80 + 0,20 = 7,00; 7,00 + 3,00 = 10,00. Troco: R$ 3,20.',
      'Troco = o que eu dei − o que custou.', 'Com uma nota de R$ 20 para um lanche de R$ 15, o troco é R$ 5.', '1. Anote quanto você pagou.\n2. Anote o preço.\n3. Subtraia (ou complete a partir do preço).\n4. Confira: preço + troco = valor pago.'),
  ],
  questions: [
    mc(1, 'real', 'Quantos centavos formam 1 real?', ['10', '50', '100', '1.000'], 2, ['Pense em moedas de 50 centavos.', 'Duas delas formam 1 real.', '50 + 50.'], '1 real = 100 centavos.'),
    mc(1, 'trocas', 'Quantas moedas de 25 centavos formam R$ 1,00?', ['2', '4', '5', '25'], 1, ['R$ 1,00 = 100 centavos.', 'Quantas vezes 25 cabe em 100?', '25 + 25 + 25 + 25.'], '4 × 25 = 100 centavos = R$ 1,00.'),
    tf(1, 'trocas', 'Uma nota de R$ 10 vale o mesmo que duas notas de R$ 5.', true, ['Some as duas de R$ 5.', '5 + 5 = ?', '10.'], 'Verdadeiro.'),
    fill(2, 'total', 'Um suco custa R$ 4,50 e um pão R$ 2,30. Quanto custa tudo? (R$)', ['6,80', '6.80', '6,8'], ['Some os centavos: 50 + 30.', 'Some os reais: 4 + 2.', 'Junte reais e centavos.'], '4,50 + 2,30 = R$ 6,80.'),
    mc(2, 'troco', 'Paguei com R$ 10 algo que custou R$ 6,80. Qual o troco?', ['R$ 4,20', 'R$ 3,20', 'R$ 3,80', 'R$ 16,80'], 1, ['Troco = pago − preço.', 'De 6,80 até 7,00 faltam 0,20.', 'De 7,00 até 10,00 faltam 3,00.'], '10,00 − 6,80 = R$ 3,20.'),
    match(2, 'trocas', 'Ligue cada valor a uma forma de formá-lo.', [['R$ 20', '4 notas de R$ 5'], ['R$ 1', '2 moedas de 50 centavos'], ['R$ 50', '5 notas de R$ 10'], ['R$ 6', '3 notas de R$ 2']], ['Multiplique a quantidade pelo valor da nota.', '4 × 5 = 20.', '5 × 10 = 50.'], '20 = 4×5 · 1 = 2×0,50 · 50 = 5×10 · 6 = 3×2.'),
    fill(2, 'troco', 'Com uma nota de R$ 20, comprei um lanche de R$ 15. Qual é o troco em reais?', ['5', '5,00', 'R$ 5'], ['Troco = pago − preço.', '20 − 15.', 'Confira: 15 + ? = 20.'], '20 − 15 = R$ 5.'),
    tf(3, 'real', 'R$ 3,05 e R$ 3,50 são o mesmo valor.', false, ['Olhe os centavos.', '05 centavos e 50 centavos são iguais?', 'Não.'], 'Falso: R$ 3,05 tem 5 centavos; R$ 3,50 tem 50 centavos.'),
    mc(3, 'total', 'Comprei 3 cadernos de R$ 8,50. Quanto gastei?', ['R$ 24,50', 'R$ 25,50', 'R$ 11,50', 'R$ 26,00'], 1, ['São 3 vezes o mesmo preço.', '3 × 8 = 24 e 3 × 0,50 = 1,50.', 'Some as partes.'], '3 × 8,50 = 24 + 1,50 = R$ 25,50.'),
    order(2, 'real', 'Ordene do MENOR para o MAIOR valor.', ['R$ 0,75', 'R$ 1,20', 'R$ 2,05', 'R$ 2,50'], ['Compare primeiro os reais.', 'Com reais iguais, compare os centavos.', '05 centavos < 50 centavos.'], '0,75 < 1,20 < 2,05 < 2,50.'),
    mc(3, 'troco', 'Tenho R$ 50. Gastei R$ 12,40 e R$ 23,60. Quanto sobrou?', ['R$ 14,00', 'R$ 36,00', 'R$ 13,00', 'R$ 24,00'], 0, ['Some os gastos primeiro.', '12,40 + 23,60 = 36,00.', '50 − 36.'], 'Gastos: R$ 36,00. Sobra: 50 − 36 = R$ 14,00.'),
    open(3, 'troco', 'Explique como você confere se recebeu o troco certo.', 'Somo o preço da compra com o troco recebido. Se der o valor que eu paguei, o troco está certo.', ['preco', 'soma', 'somar', 'troco', 'paguei', 'igual'], ['O troco é o que volta do valor pago.', 'Preço + troco deve dar…', 'O valor que você entregou.'], 'Preço + troco = valor pago.'),
  ],
  review: ['1 real = 100 centavos', 'Valores iguais podem ser formados de jeitos diferentes', 'Total: some alinhando a vírgula', 'Troco = valor pago − preço (confira somando)'],
  relatedQuestions: ['Como calcular o troco?', 'Quantos centavos tem um real?', 'Como somar preços com vírgula?'],
  equivalentQuestions: ['como calcular troco', 'quanto de troco eu recebo', 'quantos centavos tem 1 real', 'como somar dinheiro com virgula', 'como ler preços em reais', 'quais sao as moedas do real', 'quais notas de dinheiro existem', 'como formar 1 real com moedas', 'como conferir o troco', 'como calcular o total da compra', 'o que significa R$', 'quanto é meio real', 'como contar dinheiro', 'problema de dinheiro e troco', 'como pagar com notas diferentes', 'como subtrair dinheiro', 'me explica sistema monetario', 'como saber se vai sobrar dinheiro', 'quantas moedas de 25 centavos fazem 1 real', 'diferença entre 3,05 e 3,50'],
  commonDoubts: [{ q: 'Por que R$ 0,50 é metade de 1 real?', a: 'Porque 1 real tem 100 centavos, e 50 é metade de 100.' }],
  commonErrors: ['Confundir R$ 3,05 com R$ 3,50', 'Somar sem alinhar a vírgula', 'Esquecer que 100 centavos viram 1 real na soma'],
  formulas: [formula('Troco', 'troco = valor pago − preço', [['valor pago', 'quanto você entregou'], ['preço', 'quanto custou'], ['troco', 'o que volta']])],
  sources: [...FONTES.slice(0, 1), SRC.web('Cédulas e moedas do Real', 'https://www.bcb.gov.br/cedulasemoedas', 'Banco Central do Brasil', 'instituicao'), SRC.autoral()],
})
