// LOTE 1 — MATEMÁTICA · Ensino Fundamental II (6º ao 9º ano). Conteúdo original do LUMI.
import { block, eqsPt, fill, formula, lesson, match, mc, open, order, SRC, tf } from '../dsl'

const FONTES = [SRC.bncc('Matemática — Anos Finais'), SRC.obmep(), SRC.autoral()]
const EF2 = ['fund2'] as const

export const numerosInteiros = lesson({
  id: 'mat-numeros-inteiros', subject: 'matematica', title: 'Números inteiros (positivos e negativos)', levels: [...EF2], grade: '6º e 7º ano',
  topic: 'Números', subtopic: 'Números inteiros e regra de sinais',
  aliases: ['numeros inteiros', 'numeros negativos', 'regra de sinais', 'menos com menos', 'reta numerica', 'modulo', 'numeros relativos', 'soma de negativos'],
  summary: 'Entenda os números negativos, compare inteiros na reta numérica e faça as quatro operações com a regra de sinais.',
  intro: 'Temperatura abaixo de zero, saldo negativo, andar do subsolo… Os números negativos estão por toda parte!',
  objective: 'Localizar e comparar números inteiros na reta, calcular o módulo e operar com inteiros usando corretamente a regra de sinais.',
  prerequisites: ['mat-adicao-subtracao'], next: ['mat-potenciacao-radiciacao', 'mat-expressoes-algebricas'],
  skills: { conceito: 'Números negativos e reta numérica', comparar: 'Comparar e calcular o módulo', somar: 'Adição e subtração de inteiros', sinais: 'Multiplicação e divisão (regra de sinais)' },
  blocks: [
    block('conceito', 'Abaixo de zero',
      'Os números inteiros reúnem os naturais (0, 1, 2, 3…) e seus opostos negativos (−1, −2, −3…). Na reta numérica, o zero fica no meio: à direita estão os positivos e à esquerda, os negativos.',
      'Uma temperatura de −5 °C está 5 graus abaixo de zero. O subsolo 2 de um prédio pode ser representado por −2.',
      'Negativo é “menos que zero”. Fica à esquerda do zero na reta.',
      'Numa conta bancária, ter R$ 30 é +30; dever R$ 30 é −30.',
      '1. Desenhe uma reta e marque o 0.\n2. À direita: 1, 2, 3…\n3. À esquerda, com a mesma distância: −1, −2, −3…',
      'O sinal de menos funciona como uma “direção”: +3 é andar 3 casas para a direita; −3 é andar 3 casas para a esquerda.'),
    block('comparar', 'Quem é maior? O que é módulo?',
      'Na reta, o número mais à direita é sempre o maior. Por isso −2 > −7 (−2 está mais perto do zero). O módulo (ou valor absoluto) é a distância do número até o zero, sempre positiva: |−7| = 7 e |7| = 7. Números opostos têm o mesmo módulo e sinais diferentes.',
      '−1 > −10 · |−15| = 15 · o oposto de −4 é 4.',
      'Mais à direita = maior. Módulo = distância até o zero (sem sinal).',
      'É mais frio −10 °C ou −2 °C? −10 °C: é o número menor.',
      '1. Coloque os números na reta.\n2. O da direita é o maior.\n3. Para o módulo, conte a distância até o zero e escreva sem sinal.',
      'Entre negativos a comparação “inverte” a intuição: dever R$ 10 (−10) é pior que dever R$ 2 (−2). Por isso −10 < −2.'),
    block('somar', 'Somando e subtraindo inteiros',
      'Sinais iguais: some os módulos e mantenha o sinal (−3 + (−5) = −8). Sinais diferentes: subtraia os módulos e fique com o sinal do maior módulo (−9 + 4 = −5). Subtrair é somar o oposto: 5 − (−3) = 5 + 3 = 8.',
      'Estava −4 °C e subiu 6 graus: −4 + 6 = 2 °C.',
      'Mesmo sinal: junta. Sinal diferente: tira e fica com o sinal de quem “ganhou”.',
      'Você devia R$ 9 (−9) e recebeu R$ 4: ainda deve R$ 5 (−5).',
      '1. Veja os sinais.\n2. Iguais: some os números e repita o sinal.\n3. Diferentes: faça maior − menor e use o sinal do maior.\n4. Subtração: troque por soma do oposto antes.',
      'Pense em dívidas e ganhos: somar negativos é juntar dívidas; somar um positivo a uma dívida é pagar parte dela.'),
    block('sinais', 'Regra de sinais na multiplicação e divisão',
      'Multiplique ou divida os módulos. Depois veja os sinais: iguais dão resultado positivo; diferentes dão negativo. (+)·(+) = +, (−)·(−) = +, (+)·(−) = −, (−)·(+) = −.',
      '(−4) · (−3) = 12 · (−20) ÷ 5 = −4 · 6 · (−2) = −12.',
      'Sinais iguais → positivo. Sinais diferentes → negativo.',
      'Perder 3 pontos (−3) em cada uma de 4 rodadas: 4 · (−3) = −12 pontos.',
      '1. Faça a conta sem os sinais.\n2. Compare os sinais: iguais ou diferentes?\n3. Iguais: resultado +. Diferentes: resultado −.',
      'Atenção: a regra “menos com menos dá mais” vale para multiplicação e divisão. Na soma, −3 + (−5) dá −8 (negativo)!'),
  ],
  questions: [
    mc(1, 'conceito', 'Qual número representa uma temperatura de 8 graus abaixo de zero?', ['8', '−8', '0,8', '80'], 1, ['Abaixo de zero é…', 'Usamos o sinal de menos.', 'Menos oito.'], 'Abaixo de zero: −8 °C.'),
    mc(1, 'comparar', 'Qual é o maior número?', ['−10', '−3', '−7', '−15'], 1, ['Pense na reta numérica.', 'O mais perto do zero é o maior entre negativos.', 'É o −3.'], '−3 está mais à direita na reta.'),
    fill(1, 'comparar', 'Qual é o módulo de −12?', ['12'], ['Módulo é distância.', 'Distância nunca é negativa.', 'Tire o sinal.'], '|−12| = 12.'),
    tf(1, 'sinais', '(−5) · (−2) = 10', true, ['Sinais iguais…', '…dão resultado positivo.', '5 · 2 = 10.'], 'Verdadeiro: sinais iguais → positivo.'),
    mc(2, 'somar', 'Quanto é −9 + 4?', ['−13', '13', '−5', '5'], 2, ['Sinais diferentes.', 'Subtraia: 9 − 4.', 'Fique com o sinal do maior módulo (9 é negativo).'], '9 − 4 = 5, com o sinal do 9: −5.'),
    mc(2, 'somar', 'Quanto é 5 − (−3)?', ['2', '8', '−8', '−2'], 1, ['Subtrair é somar o oposto.', 'O oposto de −3 é 3.', '5 + 3.'], '5 − (−3) = 5 + 3 = 8.'),
    match(2, 'sinais', 'Ligue cada conta ao resultado.', [['(−4) · 3', '−12'], ['(−4) · (−3)', '12'], ['(−20) ÷ (−5)', '4'], ['20 ÷ (−5)', '−4']], ['Primeiro faça sem sinais.', 'Iguais → +.', 'Diferentes → −.'], '−12 · 12 · 4 · −4.'),
    order(2, 'comparar', 'Coloque do MENOR para o MAIOR.', ['−8', '−3', '0', '2', '6'], ['Negativos vêm primeiro.', 'Entre negativos, o de maior módulo é menor.', 'O zero separa negativos de positivos.'], '−8 < −3 < 0 < 2 < 6.'),
    mc(3, 'somar', 'Às 6h a temperatura era −4 °C. Até o meio-dia subiu 9 °C e à noite caiu 7 °C. Qual a temperatura à noite?', ['−2 °C', '2 °C', '12 °C', '−20 °C'], 0, ['Comece em −4.', '−4 + 9 = 5.', '5 − 7 = ?'], '−4 + 9 − 7 = −2 °C.'),
    open(3, 'sinais', 'Explique por que (−3) + (−3) dá −6, mas (−3) · (−3) dá 9.', 'Na soma juntamos duas quantidades negativas, então o resultado continua negativo: −6. Na multiplicação vale a regra de sinais: sinais iguais dão resultado positivo, por isso (−3) · (−3) = 9.', ['soma', 'multiplicacao', 'sinais', 'iguais', 'positivo', 'negativo', 'regra'], ['Qual regra vale para a soma?', 'Qual vale para a multiplicação?', 'Fale da regra de sinais.'], 'A regra “sinais iguais dão +” é só da multiplicação e da divisão.'),
  ],
  review: ['Inteiros: …, −2, −1, 0, 1, 2, … · negativos à esquerda do zero', 'Mais à direita = maior · módulo = distância até o zero', 'Soma: sinais iguais somam; diferentes subtraem (sinal do maior)', 'Multiplicação/divisão: sinais iguais +, diferentes −'],
  relatedQuestions: ['o que são números inteiros', 'como funciona a regra de sinais', 'menos com menos dá mais'],
  equivalentQuestions: eqsPt(['números inteiros', 'números negativos', 'regra de sinais'], ['menos com menos dá mais na soma', 'como somar número negativo', 'quanto é -3 + -5', 'qual é maior -2 ou -7', 'o que é módulo de um número', 'o que é valor absoluto', 'como subtrair número negativo', 'multiplicação de negativos', 'divisão com sinais', 'reta numérica com negativos']),
  commonDoubts: [{ q: '“Menos com menos dá mais” sempre?', a: 'Só na multiplicação e na divisão. Na soma, −3 + (−5) = −8.' }],
  commonErrors: ['Aplicar a regra de sinais da multiplicação na soma.', 'Achar que −10 é maior que −2.', 'Esquecer de trocar o sinal ao subtrair um negativo.'],
  sources: FONTES,
})

export const potenciacao = lesson({
  id: 'mat-potenciacao-radiciacao', subject: 'matematica', title: 'Potenciação e radiciação', levels: [...EF2], grade: '6º ao 8º ano',
  topic: 'Números', subtopic: 'Potências, propriedades e raiz quadrada',
  aliases: ['potenciacao', 'potencia', 'expoente', 'elevado a', 'ao quadrado', 'ao cubo', 'raiz quadrada', 'radiciacao', 'propriedades da potencia', 'notacao cientifica'],
  summary: 'Aprenda o que é uma potência, os casos especiais, as propriedades principais e a raiz quadrada.',
  intro: '2 × 2 × 2 × 2 × 2 dá trabalho de escrever. Com potência, basta 2⁵!',
  objective: 'Calcular potências (incluindo expoente 0, 1 e base 10), aplicar as propriedades de produto e quociente de mesma base e calcular raízes quadradas exatas.',
  prerequisites: ['mat-multiplicacao', 'mat-numeros-inteiros'], next: ['mat-equacao-2-grau', 'mat-teorema-pitagoras'],
  formulas: [
    formula('Potência', 'aⁿ = a · a · … · a (n fatores)', [['a', 'base'], ['n', 'expoente']]),
    formula('Produto de mesma base', 'aᵐ · aⁿ = aᵐ⁺ⁿ', [['a', 'base'], ['m, n', 'expoentes']]),
    formula('Quociente de mesma base', 'aᵐ ÷ aⁿ = aᵐ⁻ⁿ', [['a', 'base (a ≠ 0)'], ['m, n', 'expoentes']]),
  ],
  skills: { conceito: 'Base e expoente', especiais: 'Casos especiais (0, 1, base 10)', propriedades: 'Propriedades das potências', raiz: 'Raiz quadrada' },
  blocks: [
    block('conceito', 'Base e expoente',
      'Potência é uma multiplicação de fatores iguais. Em 2⁵, o 2 é a base (o número que se repete) e o 5 é o expoente (quantas vezes ele se repete): 2⁵ = 2 · 2 · 2 · 2 · 2 = 32. Expoente 2 lê-se “ao quadrado”; expoente 3, “ao cubo”.',
      '3² = 3 · 3 = 9 · 4³ = 4 · 4 · 4 = 64.',
      'O número de cima diz quantas vezes multiplicar o de baixo por ele mesmo.',
      'Um cubo mágico tem 3 · 3 · 3 = 3³ = 27 pecinhas.',
      '1. Veja a base.\n2. Veja o expoente.\n3. Escreva a base repetida tantas vezes quanto o expoente.\n4. Multiplique.',
      'Cuidado: 2³ não é 2 · 3 = 6. É 2 · 2 · 2 = 8. O expoente conta repetições, não é um fator.'),
    block('especiais', 'Casos especiais',
      'Todo número (diferente de zero) elevado a 0 dá 1: 7⁰ = 1. Todo número elevado a 1 dá ele mesmo: 7¹ = 7. Potências de 10: o expoente diz quantos zeros: 10³ = 1.000. Base negativa: expoente par dá positivo, ímpar dá negativo: (−2)² = 4 e (−2)³ = −8.',
      '5⁰ = 1 · 9¹ = 9 · 10⁶ = 1.000.000 · (−3)² = 9.',
      'Expoente 0 → 1. Expoente 1 → o próprio número. 10ⁿ → 1 seguido de n zeros.',
      'Em notação científica, a distância Terra–Sol é cerca de 1,5 · 10⁸ km (150 milhões de km).',
      '1. Expoente 0? Resposta 1.\n2. Expoente 1? O próprio número.\n3. Base 10? Escreva 1 e o número de zeros.\n4. Base negativa? Conte se o expoente é par ou ímpar.',
      '(−3)² = 9, mas −3² = −9: sem parênteses, só o 3 é elevado ao quadrado, e o sinal fica de fora.'),
    block('propriedades', 'Propriedades principais',
      'Mesma base na multiplicação: mantenha a base e SOME os expoentes (2³ · 2⁴ = 2⁷). Mesma base na divisão: mantenha a base e SUBTRAIA os expoentes (5⁶ ÷ 5² = 5⁴). Potência de potência: MULTIPLIQUE os expoentes ((3²)³ = 3⁶).',
      '10² · 10³ = 10⁵ = 100.000 · 7⁵ ÷ 7³ = 7² = 49.',
      'Multiplicar: soma os expoentes. Dividir: subtrai. Potência de potência: multiplica.',
      'Um prédio tem 10 andares com 10 salas cada, e cada sala tem 10 mesas: 10 · 10 · 10 = 10¹ · 10¹ · 10¹ = 10³ mesas.',
      '1. Confira se as bases são iguais.\n2. Multiplicação → some os expoentes.\n3. Divisão → subtraia.\n4. Potência de potência → multiplique.',
      'As regras só valem com a MESMA base: 2³ · 3² não vira 6⁵. Nesse caso, calcule cada potência separadamente.'),
    block('raiz', 'Raiz quadrada',
      'A raiz quadrada é a operação inversa de elevar ao quadrado: √49 = 7 porque 7² = 49. Os quadrados perfeitos (1, 4, 9, 16, 25, 36, 49, 64, 81, 100…) têm raiz exata. Não existe raiz quadrada real de número negativo.',
      '√81 = 9 · √144 = 12 · √0 = 0.',
      'Raiz quadrada: qual número vezes ele mesmo dá esse resultado?',
      'Um terreno quadrado tem 64 m² de área. Cada lado mede √64 = 8 m.',
      '1. Pergunte: que número ao quadrado dá esse valor?\n2. Teste números: 7 · 7 = 49.\n3. Se nenhum inteiro der certo, a raiz não é exata.',
      'Elevar ao quadrado e tirar a raiz se desfazem, como somar 3 e subtrair 3.'),
  ],
  questions: [
    mc(1, 'conceito', 'Quanto é 2⁴?', ['8', '16', '6', '24'], 1, ['2 multiplicado por ele mesmo 4 vezes.', '2 · 2 · 2 · 2.', '4 · 4.'], '2⁴ = 16.'),
    mc(1, 'especiais', 'Quanto é 9⁰?', ['0', '1', '9', '90'], 1, ['Expoente zero…', 'É um caso especial.', 'Sempre dá 1 (base ≠ 0).'], '9⁰ = 1.'),
    fill(1, 'raiz', 'Qual é a raiz quadrada de 81?', ['9'], ['Que número vezes ele mesmo dá 81?', 'Está entre 8 e 10.', '9 · 9.'], '√81 = 9.'),
    tf(1, 'conceito', '2³ é igual a 6.', false, ['2³ = 2 · 2 · 2.', 'Não é 2 · 3.', 'Dá 8.'], 'Falso: 2³ = 8.'),
    match(2, 'especiais', 'Ligue cada potência ao valor.', [['10³', '1.000'], ['7¹', '7'], ['(−2)³', '−8'], ['(−2)²', '4']], ['10³: 1 seguido de 3 zeros.', 'Expoente 1: o próprio número.', 'Base negativa: par +, ímpar −.'], '1.000 · 7 · −8 · 4.'),
    mc(2, 'propriedades', 'Como fica 3⁴ · 3⁵ numa só potência?', ['3²⁰', '3⁹', '9⁹', '3¹'], 1, ['Mesma base, multiplicação.', 'Some os expoentes.', '4 + 5.'], '3⁴ · 3⁵ = 3⁹.'),
    mc(2, 'propriedades', 'Quanto é 5⁶ ÷ 5⁴?', ['5²', '5¹⁰', '1', '5²⁴'], 0, ['Mesma base, divisão.', 'Subtraia os expoentes.', '6 − 4.'], '5⁶ ÷ 5⁴ = 5² = 25.'),
    mc(2, 'raiz', 'Um terreno quadrado tem 100 m² de área. Quanto mede cada lado?', ['50 m', '25 m', '10 m', '1.000 m'], 2, ['Área do quadrado = lado².', 'Lado = √área.', '√100.'], '√100 = 10 m.'),
    order(3, 'conceito', 'Ordene do MENOR para o MAIOR.', ['2³', '3²', '4²', '2⁵'], ['Calcule cada um.', '2³ = 8, 3² = 9.', '4² = 16, 2⁵ = 32.'], '8 < 9 < 16 < 32.'),
    mc(3, 'especiais', 'Qual é o valor de −3² + (−3)²?', ['0', '18', '−18', '9'], 0, ['Sem parênteses, só o 3 é elevado.', '−3² = −9.', '(−3)² = 9.'], '−9 + 9 = 0.'),
  ],
  review: ['aⁿ: base a repetida n vezes', 'a⁰ = 1 · a¹ = a · 10ⁿ = 1 com n zeros', 'Mesma base: × soma expoentes, ÷ subtrai, potência de potência multiplica', '√ é o inverso de elevar ao quadrado'],
  relatedQuestions: ['o que é potenciação', 'como calcular raiz quadrada', 'propriedades das potências'],
  equivalentQuestions: eqsPt(['potenciação', 'potência', 'raiz quadrada'], ['quanto é 2 elevado a 5', 'por que todo número elevado a zero dá 1', 'o que é base e expoente', 'o que é ao quadrado e ao cubo', 'como multiplicar potências de mesma base', 'como dividir potências', 'potência de potência', 'potência de base negativa', 'o que é quadrado perfeito', 'raiz quadrada de 144', 'o que é notação científica']),
  commonErrors: ['Multiplicar base pelo expoente (2³ = 6).', 'Somar expoentes com bases diferentes.', 'Confundir −3² com (−3)².'],
  sources: FONTES,
})

export const mmcMdc = lesson({
  id: 'mat-mmc-mdc', subject: 'matematica', title: 'Múltiplos, divisores, MMC e MDC', levels: [...EF2], grade: '6º ano',
  topic: 'Números', subtopic: 'Divisibilidade, números primos, MMC e MDC',
  aliases: ['mmc', 'mdc', 'minimo multiplo comum', 'maximo divisor comum', 'multiplos e divisores', 'numeros primos', 'fatoracao', 'criterios de divisibilidade', 'decomposicao em fatores primos'],
  summary: 'Descubra múltiplos e divisores, use os critérios de divisibilidade, fatore em primos e calcule MMC e MDC.',
  intro: 'Quando dois ônibus vão sair juntos de novo? Quantos kits iguais dá para montar? MMC e MDC resolvem!',
  objective: 'Identificar múltiplos e divisores, aplicar critérios de divisibilidade, fatorar números em primos e calcular MMC e MDC em problemas.',
  prerequisites: ['mat-divisao', 'mat-multiplicacao'], next: ['mat-fracoes'],
  skills: { multiplos: 'Múltiplos e divisores', criterios: 'Critérios de divisibilidade', primos: 'Números primos e fatoração', mmcmdc: 'MMC e MDC em problemas' },
  blocks: [
    block('multiplos', 'Múltiplos e divisores',
      'Múltiplos de um número são os resultados da tabuada dele: múltiplos de 4 = 0, 4, 8, 12, 16… Um número é divisor de outro quando a divisão é exata (resto zero): 3 é divisor de 12 porque 12 ÷ 3 = 4.',
      'Divisores de 12: 1, 2, 3, 4, 6 e 12.',
      'Múltiplo = tabuada. Divisor = divide sem sobrar.',
      'Ovos vêm em caixas de 6: você pode ter 6, 12, 18… ovos (múltiplos de 6).',
      '1. Múltiplos: multiplique o número por 0, 1, 2, 3…\n2. Divisores: teste as divisões e guarde as que dão resto zero.',
      'Múltiplos são infinitos (a tabuada nunca acaba); divisores são poucos e o maior deles é o próprio número.'),
    block('criterios', 'Critérios de divisibilidade',
      'Por 2: o número é par. Por 3: a soma dos algarismos é divisível por 3. Por 5: termina em 0 ou 5. Por 10: termina em 0. Por 9: a soma dos algarismos é divisível por 9. Por 4: os dois últimos algarismos formam um número divisível por 4.',
      '123: 1 + 2 + 3 = 6 → divisível por 3. · 2.340 termina em 0 → divisível por 2, 5 e 10.',
      'Atalhos para saber se a conta vai dar exata sem fazer a divisão.',
      'Dá para dividir 135 balas igualmente entre 5 amigos? Termina em 5, então sim.',
      '1. Olhe o último algarismo (2, 5, 10).\n2. Some os algarismos (3, 9).\n3. Olhe os dois últimos (4).',
      'O critério do 3 e o do 9 são parecidos (soma dos algarismos); o do 2, 5 e 10 olham só o final.'),
    block('primos', 'Números primos e fatoração',
      'Número primo tem exatamente dois divisores: 1 e ele mesmo (2, 3, 5, 7, 11, 13, 17, 19, 23…). O 1 não é primo e o 2 é o único primo par. Todo número maior que 1 pode ser escrito como produto de primos: 60 = 2 · 2 · 3 · 5 = 2² · 3 · 5.',
      'Fatoração de 36: 36 ÷ 2 = 18 ÷ 2 = 9 ÷ 3 = 3 ÷ 3 = 1 → 36 = 2² · 3².',
      'Primo só divide por 1 e por ele mesmo. Fatorar é quebrar o número em primos.',
      'Como peças de Lego: 60 é “montado” com as peças 2, 2, 3 e 5.',
      '1. Divida pelo menor primo possível (2, 3, 5…).\n2. Continue com o resultado.\n3. Pare quando chegar a 1.\n4. Os divisores usados são os fatores primos.',
      '9 não é primo (tem o divisor 3); 11 é primo. Ser ímpar não garante ser primo.'),
    block('mmcmdc', 'MMC e MDC',
      'MMC (mínimo múltiplo comum) é o menor múltiplo, diferente de zero, comum a dois números: usado quando algo se repete e queremos saber quando coincide. MDC (máximo divisor comum) é o maior divisor comum: usado para dividir em partes iguais do maior tamanho possível. Pela fatoração: MMC = todos os fatores com os maiores expoentes; MDC = só os fatores comuns com os menores expoentes.',
      'MMC(4, 6) = 12 · MDC(12, 18) = 6.',
      'MMC: quando vai coincidir de novo? MDC: qual o maior tamanho de parte igual?',
      'Um ônibus passa a cada 4 min e outro a cada 6 min. Saíram juntos: voltam a coincidir em MMC(4, 6) = 12 min.',
      'MMC: 1. Liste múltiplos de cada número. 2. Ache o primeiro em comum.\nMDC: 1. Liste divisores de cada. 2. Ache o maior em comum.',
      'Dica para escolher: “repetir e coincidir” → MMC; “dividir em partes iguais, maiores possíveis” → MDC.'),
  ],
  questions: [
    mc(1, 'multiplos', 'Qual destes é múltiplo de 7?', ['27', '35', '44', '50'], 1, ['Pense na tabuada do 7.', '7 · 5 = ?', '35.'], '35 = 7 · 5.'),
    mc(1, 'primos', 'Qual destes números é primo?', ['9', '15', '13', '21'], 2, ['Primo só divide por 1 e por ele.', '9, 15 e 21 dividem por 3.', 'Sobra o 13.'], '13 só tem os divisores 1 e 13.'),
    tf(1, 'criterios', '312 é divisível por 3.', true, ['Some os algarismos.', '3 + 1 + 2 = 6.', '6 é divisível por 3?'], 'Verdadeiro: 3 + 1 + 2 = 6.'),
    fill(1, 'mmcmdc', 'Qual é o MMC de 4 e 6?', ['12'], ['Liste múltiplos de 4: 4, 8, 12…', 'Múltiplos de 6: 6, 12…', 'O primeiro comum.'], 'MMC(4, 6) = 12.'),
    match(2, 'criterios', 'Ligue cada número a um divisor garantido pelo critério.', [['2.340', '10'], ['135', '5'], ['918', '9'], ['316', '4']], ['Termina em 0 → 10.', 'Termina em 5 → 5.', 'Soma 18 → 9; final 16 → 4.'], '2.340 por 10 · 135 por 5 · 918 por 9 · 316 por 4.'),
    mc(2, 'primos', 'Qual é a fatoração de 60?', ['2 · 30', '2² · 3 · 5', '6 · 10', '2 · 3² · 5'], 1, ['Divida por primos.', '60 → 30 → 15 → 5 → 1.', 'Usou 2, 2, 3, 5.'], '60 = 2² · 3 · 5.'),
    mc(2, 'mmcmdc', 'Qual é o MDC de 12 e 18?', ['2', '3', '6', '36'], 2, ['Divisores de 12: 1, 2, 3, 4, 6, 12.', 'Divisores de 18: 1, 2, 3, 6, 9, 18.', 'O maior em comum.'], 'MDC(12, 18) = 6.'),
    mc(3, 'mmcmdc', 'Um farol pisca a cada 8 s e outro a cada 12 s. Piscaram juntos agora. Em quantos segundos piscam juntos de novo?', ['4 s', '20 s', '24 s', '96 s'], 2, ['“Coincidir de novo” → MMC.', 'Múltiplos de 8: 8, 16, 24…', 'Múltiplos de 12: 12, 24…'], 'MMC(8, 12) = 24 s.'),
    mc(3, 'mmcmdc', 'Há 24 lápis e 36 canetas para montar kits iguais, sem sobras, com o MAIOR número de itens possível por tipo. Quantos kits?', ['6', '12', '72', '4'], 1, ['“Partes iguais, maior possível” → MDC.', 'MDC(24, 36).', 'Divisores comuns: 1, 2, 3, 4, 6, 12.'], 'MDC(24, 36) = 12 kits (2 lápis e 3 canetas em cada).'),
    order(2, 'primos', 'Coloque em ordem os primeiros números primos.', ['2', '3', '5', '7', '11'], ['O menor primo é par.', 'Depois vêm 3 e 5.', '9 não é primo.'], '2, 3, 5, 7, 11.'),
  ],
  review: ['Múltiplo = tabuada · divisor = divisão exata', 'Critérios: 2 (par), 3 e 9 (soma dos algarismos), 5 (0 ou 5), 10 (0)', 'Primo: só 1 e ele mesmo · fatoração em primos', 'MMC: coincidir · MDC: dividir em partes iguais máximas'],
  relatedQuestions: ['como calcular mmc', 'como calcular mdc', 'o que são números primos'],
  equivalentQuestions: eqsPt(['MMC', 'MDC', 'números primos', 'múltiplos e divisores'], ['diferença entre mmc e mdc', 'quando usar mmc', 'quando usar mdc', 'como fatorar um número', '1 é número primo', 'como saber se um número é divisível por 3', 'critério de divisibilidade por 9', 'divisores de 12', 'mmc de 4 e 6', 'mdc de 12 e 18']),
  commonErrors: ['Achar que 1 é primo.', 'Confundir quando usar MMC e MDC.', 'Achar que todo número ímpar é primo.'],
  sources: FONTES,
})

export const numerosDecimais = lesson({
  id: 'mat-numeros-decimais', subject: 'matematica', title: 'Números decimais', levels: ['fund1', 'fund2'], grade: '5º e 6º ano',
  topic: 'Números', subtopic: 'Décimos, centésimos e operações com decimais',
  aliases: ['numeros decimais', 'decimais', 'virgula', 'decimos', 'centesimos', 'milesimos', 'conta com virgula', 'fracao decimal', 'multiplicar por 10 decimal'],
  summary: 'Leia décimos, centésimos e milésimos, transforme frações decimais e faça contas com vírgula.',
  intro: 'R$ 3,50, 1,75 m, 36,5 °C… A vírgula está em todo lugar. Vamos entender o que ela significa!',
  objective: 'Ler e escrever números decimais, relacioná-los a frações decimais, compará-los e realizar as quatro operações e as multiplicações e divisões por 10, 100 e 1.000.',
  prerequisites: ['mat-fracoes', 'mat-sistema-monetario'], next: ['mat-razao-proporcao', 'mat-porcentagem'],
  skills: { leitura: 'Décimos, centésimos e milésimos', fracao: 'Frações decimais e comparação', somar: 'Adição e subtração com vírgula', potencias10: 'Multiplicar e dividir (inclusive por 10, 100…)' },
  blocks: [
    block('leitura', 'Depois da vírgula',
      'A vírgula separa a parte inteira da parte decimal. Depois dela vêm os décimos (1/10), os centésimos (1/100) e os milésimos (1/1.000). 2,35 lê-se “dois inteiros e trinta e cinco centésimos”.',
      '0,7 = sete décimos · 0,07 = sete centésimos · 1,005 = um inteiro e cinco milésimos.',
      'Depois da vírgula, as casas valem cada vez menos: décimo, centésimo, milésimo.',
      'R$ 4,25 são 4 reais e 25 centavos — centavo é um centésimo do real.',
      '1. Leia a parte inteira.\n2. Conte as casas depois da vírgula (1 = décimos, 2 = centésimos, 3 = milésimos).\n3. Leia o número depois da vírgula com esse nome.',
      'É o sistema decimal continuando para a direita: cada casa vale 10 vezes menos que a anterior.'),
    block('fracao', 'Frações decimais e comparação',
      'Frações com denominador 10, 100, 1.000 viram decimais direto: 3/10 = 0,3 e 45/100 = 0,45. Para comparar decimais, iguale o número de casas com zeros à direita: 0,5 = 0,50 > 0,45. Zeros à direita depois da vírgula não mudam o valor.',
      '0,8 > 0,75 porque 0,80 > 0,75. · 7/100 = 0,07.',
      'Denominador 10 → uma casa; 100 → duas casas.',
      'Qual é mais alto: 1,6 m ou 1,58 m? 1,60 > 1,58.',
      '1. Iguale as casas decimais com zeros.\n2. Compare como números inteiros.\n3. Para fração decimal: número de zeros do denominador = número de casas.',
      'Mais algarismos não significa maior: 0,125 < 0,3, porque 0,125 < 0,300.'),
    block('somar', 'Somar e subtrair com vírgula',
      'Arme a conta com vírgula embaixo de vírgula (unidade embaixo de unidade, décimo embaixo de décimo). Complete com zeros as casas vazias e faça a conta como com números inteiros. A vírgula do resultado fica alinhada.',
      '12,5 + 3,75 = 12,50 + 3,75 = 16,25.',
      'Vírgula embaixo de vírgula. Depois, é conta normal.',
      'Compras: R$ 12,50 + R$ 3,75 = R$ 16,25. Pagando com R$ 20: troco de R$ 3,75.',
      '1. Alinhe as vírgulas.\n2. Complete com zeros.\n3. Some ou subtraia normalmente.\n4. Coloque a vírgula alinhada no resultado.',
      'Alinhar a vírgula é o mesmo cuidado de alinhar unidades com unidades nas contas de inteiros.'),
    block('potencias10', 'Multiplicar e dividir',
      'Multiplicação: multiplique como se não houvesse vírgula e, no resultado, conte tantas casas decimais quanto a soma das casas dos fatores (1,2 · 0,3 = 0,36). Por 10, 100, 1.000: a vírgula anda 1, 2 ou 3 casas para a DIREITA na multiplicação e para a ESQUERDA na divisão.',
      '3,45 · 100 = 345 · 72,5 ÷ 10 = 7,25 · 0,4 · 0,5 = 0,20.',
      '× 10 empurra a vírgula para a direita; ÷ 10 empurra para a esquerda.',
      'Um caderno custa R$ 8,90. Dez cadernos: 8,90 · 10 = R$ 89,00.',
      '1. Multiplique sem vírgula.\n2. Conte as casas decimais dos dois números.\n3. Coloque a vírgula com esse total de casas.\nPor 10/100/1.000: mova a vírgula pelo número de zeros.',
      'Multiplicar por 0,5 é o mesmo que dividir por 2: 0,5 = metade.'),
  ],
  questions: [
    mc(1, 'leitura', 'Como se lê 0,07?', ['Sete décimos', 'Sete centésimos', 'Sete milésimos', 'Setenta'], 1, ['Conte as casas depois da vírgula.', 'Duas casas.', 'Duas casas = centésimos.'], '0,07 = sete centésimos.'),
    mc(1, 'fracao', 'Qual decimal representa 3/10?', ['3,10', '0,3', '0,03', '30'], 1, ['Denominador 10.', 'Uma casa decimal.', 'Três décimos.'], '3/10 = 0,3.'),
    fill(1, 'somar', 'Quanto é 12,5 + 3,75?', ['16,25', '16.25'], ['Alinhe as vírgulas.', '12,50 + 3,75.', 'Some.'], '12,50 + 3,75 = 16,25.'),
    tf(1, 'fracao', '0,125 é maior que 0,3.', false, ['Iguale as casas.', '0,300 × 0,125.', 'Compare.'], 'Falso: 0,125 < 0,300.'),
    match(2, 'potencias10', 'Ligue cada conta ao resultado.', [['3,45 · 100', '345'], ['72,5 ÷ 10', '7,25'], ['0,6 · 1.000', '600'], ['5 ÷ 100', '0,05']], ['× 100: vírgula 2 casas à direita.', '÷ 10: 1 casa à esquerda.', 'Complete com zeros se faltar casa.'], '345 · 7,25 · 600 · 0,05.'),
    mc(2, 'potencias10', 'Quanto é 1,2 · 0,3?', ['3,6', '0,36', '0,036', '36'], 1, ['12 · 3 = 36.', 'Casas decimais: 1 + 1 = 2.', 'Coloque 2 casas.'], '1,2 · 0,3 = 0,36.'),
    mc(2, 'somar', 'Você comprou algo de R$ 16,25 e pagou com R$ 20. Qual o troco?', ['R$ 4,75', 'R$ 3,75', 'R$ 4,25', 'R$ 3,25'], 1, ['20,00 − 16,25.', 'Alinhe as vírgulas.', 'Faça a subtração.'], '20,00 − 16,25 = 3,75.'),
    order(2, 'fracao', 'Ordene do MENOR para o MAIOR.', ['0,05', '0,125', '0,3', '0,75', '1,2'], ['Iguale as casas decimais.', '0,050; 0,125; 0,300…', 'Por último o que tem parte inteira 1.'], '0,05 < 0,125 < 0,3 < 0,75 < 1,2.'),
    mc(3, 'potencias10', 'Um litro de suco custa R$ 6,40. Quanto custam 2,5 litros?', ['R$ 12,80', 'R$ 16,00', 'R$ 15,60', 'R$ 8,90'], 1, ['6,40 · 2,5.', '640 · 25 = 16.000.', 'Casas decimais: 2 + 1 = 3 → 16,000.'], '6,40 · 2,5 = 16,00.'),
    mc(3, 'leitura', 'Qual número tem 4 inteiros e 5 milésimos?', ['4,5', '4,05', '4,005', '4,500'], 2, ['Milésimos = 3 casas.', 'O 5 fica na 3ª casa.', 'Complete com zeros antes.'], '4,005.'),
  ],
  review: ['Décimos (1 casa), centésimos (2), milésimos (3)', 'Comparar: iguale as casas com zeros', 'Soma/subtração: vírgula embaixo de vírgula', 'Multiplicação: soma das casas · ×10 direita, ÷10 esquerda'],
  relatedQuestions: ['o que são números decimais', 'como fazer conta com vírgula', 'como transformar fração em decimal'],
  equivalentQuestions: eqsPt(['números decimais', 'decimais'], ['como somar números com vírgula', 'como multiplicar decimais', 'o que é décimo e centésimo', 'como ler 0,07', 'multiplicar por 10 com vírgula', 'dividir decimal por 100', 'qual é maior 0,5 ou 0,45', 'como transformar 3/10 em decimal', 'onde colocar a vírgula no resultado', 'conta de dinheiro com centavos']),
  commonErrors: ['Não alinhar as vírgulas na soma.', 'Achar que mais algarismos = número maior (0,125 > 0,3).', 'Mover a vírgula para o lado errado ao multiplicar por 10.'],
  sources: FONTES,
})

export const razaoProporcao = lesson({
  id: 'mat-razao-proporcao', subject: 'matematica', title: 'Razão e proporção', levels: [...EF2], grade: '7º ano',
  topic: 'Proporcionalidade', subtopic: 'Razão, proporção e escala',
  aliases: ['razao', 'proporcao', 'razao e proporcao', 'escala', 'propriedade fundamental da proporcao', 'produto dos meios e extremos', 'grandezas proporcionais', 'velocidade media razao'],
  summary: 'Compare grandezas com razões, reconheça proporções, use a propriedade fundamental e entenda escalas.',
  intro: 'Uma receita para 4 pessoas precisa virar receita para 8? Proporção resolve.',
  objective: 'Escrever e interpretar razões, verificar se duas razões formam uma proporção, usar a propriedade fundamental para achar termos desconhecidos e aplicar escalas.',
  prerequisites: ['mat-fracoes', 'mat-numeros-decimais'], next: ['mat-regra-de-tres'],
  formulas: [formula('Propriedade fundamental da proporção', 'a/b = c/d ⇔ a · d = b · c', [['a, d', 'extremos'], ['b, c', 'meios']], 'b e d diferentes de zero.'), formula('Escala', 'escala = medida no desenho ÷ medida real', [['medidas', 'na mesma unidade']])],
  skills: { razao: 'Razão entre grandezas', proporcao: 'Proporção', fundamental: 'Propriedade fundamental', escala: 'Escala e aplicações' },
  blocks: [
    block('razao', 'Razão: comparar por divisão',
      'Razão é a comparação entre dois números por meio da divisão: a razão de a para b é a/b (b ≠ 0). A ordem importa. Razões também comparam grandezas diferentes, como quilômetros por hora ou habitantes por km².',
      'Numa turma com 12 meninas e 18 meninos, a razão meninas/meninos é 12/18 = 2/3.',
      'Razão é uma fração que compara duas quantidades.',
      'Um carro fez 300 km com 25 L: razão 300/25 = 12 km por litro.',
      '1. Identifique as duas quantidades (na ordem pedida).\n2. Escreva a primeira sobre a segunda.\n3. Simplifique se possível.',
      'A razão 2/3 e a fração 2/3 se escrevem igual, mas a razão costuma comparar duas coisas diferentes (meninas e meninos), não parte de um todo.'),
    block('proporcao', 'Proporção: razões iguais',
      'Proporção é a igualdade entre duas razões: a/b = c/d. Lemos “a está para b assim como c está para d”. Duas razões formam proporção quando, simplificadas, dão o mesmo valor.',
      '2/3 = 4/6 = 10/15 (todas valem o mesmo).',
      'Proporção = duas razões que valem o mesmo.',
      'Receita: 2 xícaras de farinha para 3 ovos. Com 6 ovos, 4 xícaras: 2/3 = 4/6.',
      '1. Simplifique as duas razões.\n2. Se ficarem iguais, é proporção.\n3. Ou faça a divisão de cada uma e compare os resultados.',
      'Ampliar uma foto sem distorcer mantém a proporção entre largura e altura; esticar só um lado quebra a proporção.'),
    block('fundamental', 'Propriedade fundamental',
      'Numa proporção a/b = c/d, o produto dos extremos (a · d) é igual ao produto dos meios (b · c). Assim encontramos um termo desconhecido: em 3/5 = x/20, 5x = 60, então x = 12.',
      '2/7 = 6/x → 2x = 42 → x = 21.',
      'Multiplique em “X” (cruzado): os dois produtos são iguais.',
      'Se 3 cadernos custam R$ 15, quanto custam 7? 3/15 = 7/x → 3x = 105 → x = 35.',
      '1. Monte a proporção.\n2. Multiplique cruzado.\n3. Iguale os produtos.\n4. Resolva a equação.',
      'É a base da regra de três: “multiplicar cruzado” é usar a propriedade fundamental.'),
    block('escala', 'Escala',
      'Escala é a razão entre a medida no desenho (mapa, planta, maquete) e a medida real, na mesma unidade. Escala 1:100 significa que 1 cm no desenho corresponde a 100 cm (1 m) na realidade.',
      'Num mapa 1:50.000, 3 cm valem 150.000 cm = 1,5 km.',
      '1:100 → cada 1 no desenho vale 100 na vida real.',
      'Na planta de uma casa em 1:50, uma sala de 8 cm mede 8 · 50 = 400 cm = 4 m.',
      '1. Leia a escala (1:n).\n2. Multiplique a medida do desenho por n.\n3. Converta a unidade (cm → m → km).',
      'Quanto maior o segundo número da escala (1:1.000.000), menos detalhe o mapa mostra — ele representa uma área maior.'),
  ],
  questions: [
    mc(1, 'razao', 'Numa sala há 10 meninas e 15 meninos. Qual a razão meninas para meninos?', ['3/2', '2/3', '10/25', '15/10'], 1, ['Meninas em cima.', '10/15.', 'Simplifique por 5.'], '10/15 = 2/3.'),
    tf(1, 'proporcao', '2/3 e 8/12 formam uma proporção.', true, ['Simplifique 8/12.', 'Divida por 4.', 'Dá 2/3?'], 'Verdadeiro: 8/12 = 2/3.'),
    fill(1, 'fundamental', 'Encontre x: 3/5 = x/20', ['12'], ['Multiplique cruzado.', '5x = 3 · 20.', '5x = 60.'], 'x = 12.'),
    mc(1, 'escala', 'Na escala 1:100, 1 cm no desenho corresponde a quanto na realidade?', ['1 cm', '10 cm', '1 m', '100 m'], 2, ['1 cm vale 100 cm.', '100 cm = ?', '1 m.'], '100 cm = 1 m.'),
    match(2, 'razao', 'Ligue cada situação à razão correspondente.', [['300 km com 25 L', '12 km/L'], ['120 km em 2 h', '60 km/h'], ['R$ 18 por 3 kg', 'R$ 6/kg'], ['10.000 hab. em 50 km²', '200 hab./km²']], ['Divida a primeira pela segunda.', '300 ÷ 25.', '10.000 ÷ 50.'], '12 km/L · 60 km/h · R$ 6/kg · 200 hab./km².'),
    mc(2, 'fundamental', 'Se 3 cadernos custam R$ 15, quanto custam 7?', ['R$ 21', 'R$ 35', 'R$ 45', 'R$ 105'], 1, ['3/15 = 7/x.', '3x = 105.', 'x = 35.'], 'R$ 35.'),
    mc(2, 'escala', 'Num mapa 1:50.000, duas cidades estão a 4 cm. Qual a distância real?', ['2 km', '20 km', '200 m', '200 km'], 0, ['4 · 50.000 = 200.000 cm.', '200.000 cm = 2.000 m.', '= 2 km.'], '4 cm → 200.000 cm = 2 km.'),
    mc(3, 'proporcao', 'Uma receita usa 2 xícaras de farinha para 3 ovos. Com 9 ovos, quantas xícaras?', ['4', '5', '6', '9'], 2, ['Ovos triplicaram (3 → 9).', 'A farinha também triplica.', '2 · 3.'], '6 xícaras (2/3 = 6/9).'),
    order(2, 'fundamental', 'Coloque os passos para achar x em 2/7 = 6/x na ordem.', ['Multiplicar cruzado', 'Escrever 2 · x = 7 · 6', 'Calcular 2x = 42', 'Dividir: x = 21'], ['Primeiro a propriedade.', 'Depois a equação.', 'Por fim isole x.'], 'Cruzar → 2x = 42 → x = 21.'),
    open(3, 'proporcao', 'Uma foto de 10 cm × 15 cm foi ampliada para 20 cm × 25 cm. Ela manteve a proporção? Explique.', 'Não manteve. A largura dobrou (10 → 20), mas a altura não dobrou (15 → 25; para manter, seria 30). As razões 10/15 = 2/3 e 20/25 = 4/5 são diferentes.', ['nao', 'razao', 'dobrou', 'diferentes', '30', 'proporcao'], ['Compare quanto cada lado aumentou.', 'A largura dobrou; e a altura?', 'Compare as razões 10/15 e 20/25.'], 'Para manter a proporção, os dois lados precisam ser multiplicados pelo mesmo número.'),
  ],
  review: ['Razão: a/b compara duas quantidades (a ordem importa)', 'Proporção: duas razões iguais', 'Propriedade fundamental: a · d = b · c', 'Escala 1:n → medida real = desenho · n'],
  relatedQuestions: ['o que é razão e proporção', 'como calcular escala', 'propriedade fundamental da proporção'],
  equivalentQuestions: eqsPt(['razão e proporção', 'escala'], ['como calcular razão', 'o que é proporção', 'produto dos meios e dos extremos', 'como multiplicar cruzado', 'o que significa escala 1:100', 'como calcular distância no mapa', 'como aumentar uma receita', 'razão entre meninos e meninas', 'grandezas proporcionais', 'quilômetros por litro é razão']),
  commonErrors: ['Inverter a ordem da razão.', 'Esquecer de converter unidades na escala.', 'Somar em vez de multiplicar para manter a proporção.'],
  sources: FONTES,
})

export const regraDeTres = lesson({
  id: 'mat-regra-de-tres', subject: 'matematica', title: 'Regra de três', levels: [...EF2], grade: '7º ano',
  topic: 'Proporcionalidade', subtopic: 'Regra de três simples: direta e inversa',
  aliases: ['regra de tres', 'regra de 3', 'diretamente proporcional', 'inversamente proporcional', 'regra de tres inversa', 'regra de tres simples', 'grandezas inversamente proporcionais'],
  summary: 'Resolva problemas com grandezas diretamente e inversamente proporcionais usando a regra de três.',
  intro: 'Se 2 pedreiros levam 6 dias, quanto tempo levam 3? A regra de três responde — mas cuidado com a inversa!',
  objective: 'Identificar se duas grandezas são direta ou inversamente proporcionais e resolver problemas com a regra de três simples.',
  prerequisites: ['mat-razao-proporcao'], next: ['mat-porcentagem'],
  skills: { direta: 'Grandezas diretamente proporcionais', inversa: 'Grandezas inversamente proporcionais', montar: 'Montar a regra de três', problemas: 'Resolver problemas' },
  blocks: [
    block('direta', 'Diretamente proporcionais',
      'Duas grandezas são diretamente proporcionais quando, se uma dobra, a outra também dobra (se uma cai pela metade, a outra também). Exemplos: quantidade comprada e preço; distância e combustível (na mesma velocidade).',
      '1 kg custa R$ 8 → 3 kg custam R$ 24.',
      'Uma aumenta, a outra aumenta na mesma proporção.',
      'Mais convidados na festa → mais salgadinhos.',
      '1. Imagine dobrar uma grandeza.\n2. A outra dobra também? Então é direta.',
      'Nem toda grandeza que “aumenta junto” é proporcional: idade e altura crescem juntas, mas não na mesma proporção.'),
    block('inversa', 'Inversamente proporcionais',
      'São inversamente proporcionais quando, se uma dobra, a outra cai pela metade. Exemplos: número de trabalhadores e tempo para terminar uma obra; velocidade e tempo de viagem.',
      '2 pedreiros levam 6 dias → 4 pedreiros levam 3 dias.',
      'Uma aumenta, a outra diminui na mesma proporção.',
      'Quanto mais rápido o carro, menos tempo a viagem demora.',
      '1. Imagine dobrar uma grandeza.\n2. A outra cai pela metade? Então é inversa.',
      'Na inversa, o PRODUTO se mantém: 2 pedreiros · 6 dias = 12 = 4 · 3.'),
    block('montar', 'Montando a regra de três',
      'Organize uma tabela com as grandezas em colunas e os valores conhecidos nas linhas; coloque x no valor desconhecido. Se for direta, multiplique cruzado. Se for inversa, inverta uma das colunas antes de multiplicar cruzado (ou use que os produtos são iguais).',
      'Direta: 3 kg — R$ 24; 5 kg — x → 3x = 5 · 24 → x = 40.',
      'Tabela, x no que falta, decida direta ou inversa, cruze.',
      'Receita: 4 pessoas — 500 g; 10 pessoas — x → 4x = 5.000 → x = 1.250 g.',
      '1. Monte duas colunas (uma por grandeza).\n2. Coloque os valores e o x.\n3. Direta ou inversa?\n4. Direta: cruze. Inversa: inverta uma coluna e cruze.\n5. Resolva a equação.',
      'Errar se é direta ou inversa é o erro mais comum — pare e pergunte: “se uma dobra, o que acontece com a outra?”'),
    block('problemas', 'Resolvendo problemas',
      'Leia o problema, identifique as duas grandezas, verifique se são direta ou inversamente proporcionais, monte e resolva. No final, confira se a resposta faz sentido (mais trabalhadores → menos dias, por exemplo).',
      '6 torneiras enchem um tanque em 4 h. 8 torneiras: inversa → 6 · 4 = 8 · x → x = 3 h.',
      'Resolva e pergunte: a resposta tem lógica?',
      'Um carro a 60 km/h faz o trajeto em 2 h. A 80 km/h: 60 · 2 = 80 · x → x = 1,5 h.',
      '1. Ache as grandezas.\n2. Direta ou inversa?\n3. Monte.\n4. Resolva.\n5. Confira o sentido da resposta.',
      'A regra de três é um atalho da proporção: por trás dela está a propriedade fundamental a · d = b · c.'),
  ],
  questions: [
    mc(1, 'direta', 'Quantidade de pães comprados e valor pago são grandezas:', ['Diretamente proporcionais', 'Inversamente proporcionais', 'Não proporcionais', 'Iguais'], 0, ['Se compro o dobro, pago…', '…o dobro.', 'Direta.'], 'Direta: dobra a quantidade, dobra o preço.'),
    mc(1, 'inversa', 'Velocidade e tempo de viagem (mesmo trajeto) são:', ['Diretamente proporcionais', 'Inversamente proporcionais', 'Não têm relação', 'Iguais'], 1, ['Mais rápido → …', '…menos tempo.', 'Inversa.'], 'Inversa: dobra a velocidade, o tempo cai pela metade.'),
    fill(1, 'montar', '3 kg custam R$ 24. Quanto custam 5 kg? (só o número)', ['40'], ['Direta.', '3x = 5 · 24.', '3x = 120.'], 'x = 40.'),
    tf(1, 'inversa', 'Se 2 pedreiros fazem um muro em 6 dias, 4 pedreiros fazem em 12 dias.', false, ['Mais pedreiros → mais ou menos dias?', 'É inversa.', '2 · 6 = 4 · x.'], 'Falso: 4 pedreiros levam 3 dias.'),
    mc(2, 'problemas', 'Um carro a 60 km/h faz um trajeto em 2 h. A 80 km/h, quanto tempo leva?', ['2 h 40 min', '1,5 h', '2,5 h', '1 h'], 1, ['Inversa.', '60 · 2 = 80 · x.', '120 = 80x.'], 'x = 1,5 h (1 h 30 min).'),
    mc(2, 'montar', 'Uma receita para 4 pessoas usa 500 g de carne. Para 10 pessoas:', ['1.000 g', '1.250 g', '2.000 g', '1.500 g'], 1, ['Direta.', '4x = 10 · 500.', 'x = 5.000 ÷ 4.'], '1.250 g.'),
    match(2, 'direta', 'Classifique cada par de grandezas.', [['Nº de torneiras × tempo para encher', 'inversa'], ['Litros de gasolina × km rodados', 'direta']], ['Teste dobrar uma delas.', 'Mais torneiras → menos tempo.', 'Mais horas → mais salário.'], 'inversa · direta · inversa · direta.'),
    order(2, 'problemas', 'Ordene os passos para resolver uma regra de três.', ['Identificar as grandezas', 'Decidir se é direta ou inversa', 'Montar a tabela com o x', 'Resolver e conferir'], ['Primeiro entenda o problema.', 'Depois classifique.', 'Monte, resolva e confira.'], 'Grandezas → direta/inversa → montar → resolver.'),
    mc(3, 'problemas', '6 torneiras enchem um tanque em 4 horas. Quanto tempo levam 8 torneiras iguais?', ['5 h 20 min', '3 h', '2 h', '3 h 30 min'], 1, ['Inversa.', '6 · 4 = 8 · x.', '24 = 8x.'], 'x = 3 h.'),
    open(3, 'montar', 'Como você sabe se uma regra de três é direta ou inversa? Dê um exemplo.', 'Imagino que uma grandeza dobra. Se a outra também dobra, é direta (ex.: quantidade e preço). Se a outra cai pela metade, é inversa (ex.: número de trabalhadores e dias de obra).', ['dobra', 'direta', 'inversa', 'metade', 'exemplo', 'aumenta', 'diminui'], ['Use o teste de dobrar.', 'O que acontece com a outra grandeza?', 'Cite um exemplo de cada.'], 'O teste de dobrar resolve a dúvida.'),
  ],
  review: ['Direta: dobra uma, dobra a outra', 'Inversa: dobra uma, a outra cai pela metade (produto constante)', 'Monte colunas, x no desconhecido; direta cruza, inversa inverte antes', 'Confira se a resposta faz sentido'],
  relatedQuestions: ['como fazer regra de três', 'regra de três inversa', 'como saber se é direta ou inversa'],
  equivalentQuestions: eqsPt(['regra de três', 'regra de três inversa', 'grandezas proporcionais'], ['como montar regra de três', 'regra de três simples exemplo', 'o que é grandeza inversamente proporcional', 'o que é grandeza diretamente proporcional', 'regra de três com porcentagem', 'quantos pedreiros para terminar a obra', 'velocidade e tempo regra de três', 'por que inverter na regra de três', 'multiplicar cruzado', 'regra de três de receita']),
  commonErrors: ['Tratar grandezas inversas como diretas.', 'Esquecer de inverter uma coluna na inversa.', 'Não conferir se o resultado faz sentido.'],
  sources: FONTES, enem: 'Regra de três aparece em escalas, receitas, velocidade, consumo e porcentagem.',
})

export const angulos = lesson({
  id: 'mat-angulos', subject: 'matematica', title: 'Ângulos', levels: [...EF2], grade: '6º ao 8º ano',
  topic: 'Geometria', subtopic: 'Tipos de ângulo e soma dos ângulos do triângulo',
  aliases: ['angulos', 'angulo reto', 'angulo agudo', 'angulo obtuso', 'transferidor', 'angulos complementares', 'angulos suplementares', 'soma dos angulos do triangulo', 'medir angulo em graus'],
  summary: 'Meça e classifique ângulos, use complementares e suplementares e a soma 180° dos ângulos do triângulo.',
  intro: 'O ponteiro do relógio, a abertura de uma porta, a rampa de skate… tudo é ângulo!',
  objective: 'Medir e classificar ângulos, calcular complementos e suplementos e usar a soma dos ângulos internos de triângulos e quadriláteros.',
  prerequisites: ['mat-formas-geometricas'], next: ['mat-area-perimetro', 'mat-teorema-pitagoras'],
  formulas: [formula('Soma dos ângulos internos de um polígono', 'S = (n − 2) · 180°', [['n', 'número de lados']], 'Triângulo: 180° · quadrilátero: 360°.')],
  skills: { conceito: 'O que é ângulo e como medir', tipos: 'Agudo, reto, obtuso e raso', comp: 'Complementares e suplementares', triangulo: 'Soma dos ângulos internos' },
  blocks: [
    block('conceito', 'Abertura entre duas semirretas',
      'Ângulo é a abertura formada por duas semirretas que saem do mesmo ponto (o vértice). Medimos ângulos em graus (°) com o transferidor. Uma volta completa tem 360°.',
      'Meia-volta = 180° · um quarto de volta = 90°.',
      'Ângulo mede quanto algo “abriu” ou “girou”.',
      'Um skatista que dá uma volta inteira gira 360°; meia-volta, 180°.',
      '1. Coloque o centro do transferidor no vértice.\n2. Alinhe o zero com um dos lados.\n3. Leia a medida onde passa o outro lado.',
      'O tamanho dos lados desenhados não muda o ângulo: o que importa é a abertura entre eles.'),
    block('tipos', 'Tipos de ângulo',
      'Agudo: menor que 90°. Reto: exatamente 90° (marcado com um quadradinho). Obtuso: entre 90° e 180°. Raso: 180° (uma linha reta). Nulo: 0°.',
      'O canto de um caderno é reto (90°). A ponta de uma fatia fina de pizza é aguda.',
      'Menor que 90° = agudo. 90° = reto. Maior que 90° = obtuso.',
      'Ponteiros às 3h formam 90°; às 6h, 180°.',
      '1. Compare com o canto de uma folha (90°).\n2. Menor? Agudo. Igual? Reto. Maior? Obtuso.\n3. Uma linha reta é raso (180°).',
      'Pense no canto da folha de papel como uma “régua de ângulo”: ele separa agudos de obtusos.'),
    block('comp', 'Complementares e suplementares',
      'Dois ângulos são complementares quando somam 90° e suplementares quando somam 180°. O complemento de 30° é 60°; o suplemento de 30° é 150°. Ângulos opostos pelo vértice (formados por duas retas que se cruzam) são iguais.',
      'Complemento de 25° = 65° · suplemento de 110° = 70°.',
      'Complementar completa 90°. Suplementar completa 180°.',
      'Uma rampa inclinada 20° em relação ao chão forma 70° com a parede vertical (complementares).',
      '1. Complemento: 90° − ângulo.\n2. Suplemento: 180° − ângulo.',
      'Truque para lembrar: “C” de complementar vem antes de “S” no alfabeto, assim como 90° vem antes de 180°.'),
    block('triangulo', 'Soma dos ângulos internos',
      'Em qualquer triângulo, os três ângulos internos somam 180°. Num quadrilátero, somam 360°. Em geral, um polígono de n lados tem soma S = (n − 2) · 180°.',
      'Triângulo com ângulos 50° e 70°: o terceiro mede 180° − 120° = 60°.',
      'Triângulo: 180°. Quadrilátero: 360°.',
      'Recorte os três cantos de um triângulo de papel e junte: eles formam uma linha reta (180°).',
      '1. Some os ângulos conhecidos.\n2. Subtraia de 180° (triângulo) ou 360° (quadrilátero).\n3. O resultado é o ângulo que falta.',
      'Um quadrilátero pode ser dividido em dois triângulos por uma diagonal: 2 · 180° = 360°.'),
  ],
  questions: [
    mc(1, 'tipos', 'Um ângulo de 120° é:', ['agudo', 'reto', 'obtuso', 'raso'], 2, ['Compare com 90°.', 'É maior.', 'Maior que 90° e menor que 180°.'], 'Obtuso.'),
    mc(1, 'conceito', 'Quantos graus tem uma volta completa?', ['90°', '180°', '270°', '360°'], 3, ['Meia-volta tem 180°.', 'Dobre.', '360°.'], '360°.'),
    fill(1, 'comp', 'Qual é o complemento de 30°?', ['60', '60°'], ['Complementares somam 90°.', '90 − 30.', '= 60.'], '60°.'),
    tf(1, 'triangulo', 'A soma dos ângulos internos de um triângulo é 180°.', true, ['Vale para qualquer triângulo.', 'Os cantos juntos formam uma reta.', 'Uma reta tem 180°.'], 'Verdadeiro.'),
    mc(2, 'triangulo', 'Um triângulo tem ângulos de 50° e 70°. Quanto mede o terceiro?', ['60°', '80°', '120°', '90°'], 0, ['Soma = 180°.', '50 + 70 = 120.', '180 − 120.'], '60°.'),
    mc(2, 'comp', 'Qual é o suplemento de 110°?', ['70°', '250°', '20°', '90°'], 0, ['Suplementares somam 180°.', '180 − 110.', '= 70.'], '70°.'),
    match(2, 'tipos', 'Ligue cada ângulo à classificação.', [['35°', 'agudo'], ['90°', 'reto'], ['150°', 'obtuso'], ['180°', 'raso']], ['Menor que 90°: agudo.', 'Exatamente 90°: reto.', 'Entre 90 e 180: obtuso.'], 'agudo · reto · obtuso · raso.'),
    order(2, 'tipos', 'Ordene do MENOR para o MAIOR ângulo.', ['agudo de 30°', 'reto', 'obtuso de 130°', 'raso'], ['Agudo < 90°.', 'Reto = 90°.', 'Raso = 180°.'], '30° < 90° < 130° < 180°.'),
    mc(3, 'triangulo', 'Qual é a soma dos ângulos internos de um hexágono (6 lados)?', ['540°', '720°', '1.080°', '360°'], 1, ['S = (n − 2) · 180°.', 'n = 6.', '4 · 180°.'], '(6 − 2) · 180° = 720°.'),
    mc(3, 'comp', 'Dois ângulos são complementares e um é o dobro do outro. Quanto mede o maior?', ['30°', '45°', '60°', '120°'], 2, ['x + 2x = 90°.', '3x = 90°.', 'x = 30°; o maior é 2x.'], 'O maior mede 60°.'),
  ],
  review: ['Ângulo = abertura; volta = 360°', 'Agudo < 90° · reto = 90° · obtuso entre 90° e 180° · raso = 180°', 'Complementares somam 90°; suplementares, 180°', 'Triângulo: 180° · polígono: (n − 2) · 180°'],
  relatedQuestions: ['tipos de ângulos', 'o que são ângulos complementares', 'soma dos ângulos de um triângulo'],
  equivalentQuestions: eqsPt(['ângulos', 'ângulo reto', 'ângulos complementares'], ['como usar o transferidor', 'o que é ângulo agudo', 'o que é ângulo obtuso', 'diferença entre complementar e suplementar', 'quanto mede um ângulo raso', 'como calcular o terceiro ângulo do triângulo', 'soma dos ângulos de um quadrilátero', 'ângulos opostos pelo vértice', 'quantos graus tem uma volta', 'ângulo de 90 graus']),
  commonErrors: ['Confundir complementar (90°) com suplementar (180°).', 'Achar que lados maiores significam ângulo maior.', 'Ler a escala errada do transferidor.'],
  sources: FONTES,
})

export const areaPerimetro = lesson({
  id: 'mat-area-perimetro', subject: 'matematica', title: 'Área e perímetro', levels: [...EF2], grade: '6º e 7º ano',
  topic: 'Geometria', subtopic: 'Perímetro e área de figuras planas e do círculo',
  aliases: ['area', 'perimetro', 'area e perimetro', 'area do retangulo', 'area do triangulo', 'area do circulo', 'comprimento da circunferencia', 'metro quadrado', 'pi'],
  summary: 'Calcule perímetros e áreas de quadrados, retângulos, triângulos e círculos, com as unidades certas.',
  intro: 'Quanto de cerca para o jardim? Quanto de piso para a sala? Perímetro e área respondem.',
  objective: 'Diferenciar área de perímetro e calcular os dois para quadrado, retângulo, triângulo e círculo, usando as unidades corretas.',
  prerequisites: ['mat-angulos', 'mat-medidas'], next: ['mat-geometria-espacial'],
  formulas: [
    formula('Área do retângulo', 'A = b · h', [['b', 'base'], ['h', 'altura']]),
    formula('Área do triângulo', 'A = (b · h) ÷ 2', [['b', 'base'], ['h', 'altura relativa à base']]),
    formula('Círculo', 'A = π · r² · C = 2 · π · r', [['r', 'raio'], ['π', '≈ 3,14']]),
  ],
  skills: { perimetro: 'Perímetro', retangulo: 'Área de quadrado e retângulo', triangulo: 'Área do triângulo', circulo: 'Círculo: área e comprimento' },
  blocks: [
    block('perimetro', 'Perímetro: o contorno',
      'Perímetro é a medida do contorno de uma figura: a soma de todos os lados. É medido em unidades de comprimento (cm, m, km).',
      'Retângulo de 5 m × 3 m: perímetro = 5 + 3 + 5 + 3 = 16 m.',
      'Perímetro = andar em volta e somar os lados.',
      'Para cercar uma horta de 4 m × 2 m, você precisa de 12 m de tela.',
      '1. Anote a medida de cada lado.\n2. Some todos.\n3. Use unidade de comprimento (m, cm).',
      'Perímetro é o “fio” em volta; área é a “toalha” que cobre a figura.'),
    block('retangulo', 'Área do quadrado e do retângulo',
      'Área é a medida da superfície, em unidades quadradas (cm², m²). Retângulo: A = base · altura. Quadrado: A = lado · lado = lado².',
      'Sala de 5 m × 4 m: área = 20 m². Quadrado de 6 cm de lado: 36 cm².',
      'Área = quantos quadradinhos cabem dentro.',
      'Para trocar o piso de um quarto de 3 m × 4 m, você compra 12 m² de piso.',
      '1. Meça base e altura na mesma unidade.\n2. Multiplique.\n3. Escreva a unidade ao quadrado (m²).',
      'Duas figuras podem ter o mesmo perímetro e áreas diferentes: 1 × 5 e 3 × 3 têm perímetros 12, mas áreas 5 e 9.'),
    block('triangulo', 'Área do triângulo',
      'Todo triângulo é metade de um retângulo (ou paralelogramo) de mesma base e altura. Por isso, A = (base · altura) ÷ 2. A altura é perpendicular à base (forma 90° com ela).',
      'Base 8 cm e altura 5 cm: A = 40 ÷ 2 = 20 cm².',
      'Triângulo = metade do retângulo.',
      'Um canteiro triangular de base 6 m e altura 4 m precisa de 12 m² de grama.',
      '1. Identifique a base e a altura (perpendicular).\n2. Multiplique.\n3. Divida por 2.',
      'A altura nem sempre é um lado do triângulo: é a distância “em pé” até o vértice oposto.'),
    block('circulo', 'Círculo',
      'O raio (r) vai do centro até a borda; o diâmetro é o dobro do raio. O comprimento da circunferência é C = 2 · π · r e a área do círculo é A = π · r², com π ≈ 3,14.',
      'Raio 10 cm: C ≈ 2 · 3,14 · 10 = 62,8 cm; A ≈ 3,14 · 100 = 314 cm².',
      'C = 2 · π · raio (contorno). A = π · raio · raio (superfície).',
      'Uma pizza de 30 cm de diâmetro tem raio 15 cm e área ≈ 3,14 · 225 ≈ 706,5 cm².',
      '1. Encontre o raio (metade do diâmetro).\n2. Contorno: 2 · 3,14 · r.\n3. Área: 3,14 · r · r.',
      'Uma pizza com o dobro do diâmetro tem o QUÁDRUPLO da área, porque o raio entra ao quadrado.'),
  ],
  questions: [
    mc(1, 'perimetro', 'Qual é o perímetro de um quadrado de lado 7 cm?', ['14 cm', '28 cm', '49 cm', '21 cm'], 1, ['Quadrado tem 4 lados iguais.', '7 + 7 + 7 + 7.', '4 · 7.'], '28 cm.'),
    mc(1, 'retangulo', 'Qual é a área de um retângulo de 5 m por 4 m?', ['9 m²', '18 m²', '20 m²', '20 m'], 2, ['Área = base · altura.', '5 · 4.', 'Unidade ao quadrado.'], '20 m².'),
    fill(1, 'triangulo', 'Área de um triângulo de base 8 cm e altura 5 cm (só o número, em cm²).', ['20'], ['(b · h) ÷ 2.', '8 · 5 = 40.', '40 ÷ 2.'], '20 cm².'),
    tf(1, 'perimetro', 'Perímetro e área são medidos na mesma unidade.', false, ['Perímetro é comprimento.', 'Área é superfície.', 'm × m².'], 'Falso: perímetro em m; área em m².'),
    match(2, 'circulo', 'Ligue cada fórmula ao que ela calcula.', [['2 · π · r', 'comprimento da circunferência'], ['π · r²', 'área do círculo'], ['b · h', 'área do retângulo'], ['(b · h) ÷ 2', 'área do triângulo']], ['Contorno do círculo usa 2πr.', 'Área do círculo usa r².', 'O triângulo divide por 2.'], 'Cada fórmula com sua figura.'),
    mc(2, 'circulo', 'Qual é a área aproximada de um círculo de raio 10 cm? (π ≈ 3,14)', ['31,4 cm²', '62,8 cm²', '314 cm²', '628 cm²'], 2, ['A = π · r².', 'r² = 100.', '3,14 · 100.'], '314 cm².'),
    mc(2, 'retangulo', 'Um quarto de 3 m × 4 m vai receber piso. Quantos m² comprar (sem sobra)?', ['7 m²', '12 m²', '14 m²', '24 m²'], 1, ['Piso cobre a superfície: área.', '3 · 4.', '12.'], '12 m².'),
    order(2, 'retangulo', 'Ordene as figuras da MENOR para a MAIOR área.', ['Triângulo de base 4 e altura 3', 'Quadrado de lado 3', 'Retângulo 2 × 6', 'Quadrado de lado 4'], ['Triângulo: 6.', 'Quadrado 3: 9; retângulo: 12.', 'Quadrado 4: 16.'], '6 < 9 < 12 < 16.'),
    mc(3, 'retangulo', 'Um retângulo de 1 × 5 e um quadrado de 3 × 3 têm o mesmo perímetro (12). E as áreas?', ['São iguais', 'O retângulo tem mais área', 'O quadrado tem mais área', 'Não dá para saber'], 2, ['Calcule as duas áreas.', 'Retângulo: 5.', 'Quadrado: 9.'], 'Quadrado: 9; retângulo: 5.'),
    mc(3, 'circulo', 'Se o raio de um círculo dobra, a área fica:', ['igual', 'o dobro', 'o triplo', 'o quádruplo'], 3, ['A = π · r².', 'Raio 2r → (2r)² = 4r².', 'Quatro vezes.'], 'A área fica 4 vezes maior.'),
  ],
  review: ['Perímetro = soma dos lados (m) · área = superfície (m²)', 'Retângulo: b · h · quadrado: lado²', 'Triângulo: (b · h) ÷ 2', 'Círculo: C = 2πr · A = πr² (π ≈ 3,14)'],
  relatedQuestions: ['diferença entre área e perímetro', 'como calcular área do círculo', 'área do triângulo'],
  equivalentQuestions: eqsPt(['área', 'perímetro', 'área do círculo'], ['como calcular área de um retângulo', 'quantos metros quadrados tem minha sala', 'como calcular o perímetro', 'fórmula da área do triângulo', 'o que é pi', 'comprimento da circunferência', 'diferença entre raio e diâmetro', 'quanto de piso comprar', 'quanto de cerca para o terreno', 'área do quadrado']),
  commonErrors: ['Confundir área com perímetro.', 'Esquecer de dividir por 2 no triângulo.', 'Usar o diâmetro no lugar do raio no círculo.'],
  sources: FONTES,
})

export const expressoesAlgebricas = lesson({
  id: 'mat-expressoes-algebricas', subject: 'matematica', title: 'Expressões algébricas e produtos notáveis', levels: [...EF2], grade: '7º ao 9º ano',
  topic: 'Álgebra', subtopic: 'Variáveis, valor numérico, termos semelhantes e produtos notáveis',
  aliases: ['expressoes algebricas', 'algebra', 'valor numerico', 'termos semelhantes', 'monomio', 'polinomio', 'produtos notaveis', 'quadrado da soma', 'quadrado da diferenca'],
  summary: 'Use letras para representar números, calcule valores numéricos, simplifique expressões e aplique os produtos notáveis.',
  intro: 'Em matemática, uma letra pode guardar qualquer número. É assim que escrevemos regras gerais!',
  objective: 'Escrever expressões algébricas, calcular valor numérico, somar termos semelhantes e desenvolver os produtos notáveis principais.',
  prerequisites: ['mat-numeros-inteiros', 'mat-potenciacao-radiciacao'], next: ['mat-equacao-1-grau'],
  formulas: [
    formula('Quadrado da soma', '(a + b)² = a² + 2ab + b²', [['a, b', 'termos']]),
    formula('Quadrado da diferença', '(a − b)² = a² − 2ab + b²', [['a, b', 'termos']]),
    formula('Produto da soma pela diferença', '(a + b)(a − b) = a² − b²', [['a, b', 'termos']]),
  ],
  skills: { traduzir: 'Escrever expressões com letras', valor: 'Valor numérico', semelhantes: 'Termos semelhantes', notaveis: 'Produtos notáveis' },
  blocks: [
    block('traduzir', 'Letras no lugar de números',
      'Uma expressão algébrica usa letras (variáveis) para representar números. “O dobro de um número” é 2x; “um número mais 5” é x + 5; “a metade de um número” é x/2. Entre número e letra, a multiplicação fica subentendida: 3x = 3 · x.',
      'O perímetro de um quadrado de lado ℓ é 4ℓ.',
      'A letra é uma “caixa” onde cabe qualquer número.',
      'Se cada ingresso custa R$ 20, n ingressos custam 20n.',
      '1. Leia a frase.\n2. Chame o número desconhecido de x.\n3. Traduza: dobro = 2x, triplo = 3x, metade = x/2, somado = +.',
      'Uma expressão algébrica é como uma receita: escreve a regra uma vez e serve para qualquer valor.'),
    block('valor', 'Valor numérico',
      'Para calcular o valor numérico, substitua a letra pelo número e faça as contas respeitando a ordem: potências, depois multiplicações e divisões, depois somas e subtrações. Use parênteses ao substituir números negativos.',
      'Se x = 3, 2x² − 1 = 2 · 9 − 1 = 17. Se x = −2, x² = (−2)² = 4.',
      'Troque a letra pelo número e faça a conta.',
      'Custo = 20n + 5 (taxa). Para n = 4: 20 · 4 + 5 = R$ 85.',
      '1. Escreva a expressão.\n2. Troque cada letra pelo valor (entre parênteses).\n3. Resolva potências, depois × e ÷, depois + e −.',
      '2x² não é (2x)²: primeiro eleve x ao quadrado, depois multiplique por 2.'),
    block('semelhantes', 'Termos semelhantes',
      'Termos semelhantes têm a mesma parte literal (mesmas letras com mesmos expoentes): 3x e 5x; 2a² e −a². Só termos semelhantes podem ser somados, somando os coeficientes: 3x + 5x = 8x. Já 3x + 2y não se junta.',
      '4a + 3b − a + 2b = 3a + 5b.',
      'Só junta “x com x” e “y com y”.',
      '3 maçãs + 5 maçãs = 8 maçãs; mas 3 maçãs + 2 peras não viram 5 “maçãperas”.',
      '1. Agrupe os termos com as mesmas letras e expoentes.\n2. Some os coeficientes (números).\n3. Mantenha a parte literal.',
      'x e x² NÃO são semelhantes: o expoente diferente muda tudo.'),
    block('notaveis', 'Produtos notáveis',
      'São multiplicações que aparecem tanto que viraram atalhos: (a + b)² = a² + 2ab + b²; (a − b)² = a² − 2ab + b²; (a + b)(a − b) = a² − b². O erro mais comum é esquecer o termo do meio (2ab).',
      '(x + 3)² = x² + 6x + 9 · (x − 5)(x + 5) = x² − 25.',
      '(a + b)² = primeiro ao quadrado + duas vezes o primeiro vezes o segundo + segundo ao quadrado.',
      'Área de um quadrado de lado (x + 3): x² + 6x + 9 — desenhe e veja os 4 pedaços.',
      '1. Identifique a e b.\n2. Eleve o primeiro ao quadrado.\n3. Faça 2 · a · b (com o sinal).\n4. Eleve o segundo ao quadrado.\n5. Junte.',
      '(a + b)² NÃO é a² + b²: teste com a = 1 e b = 2 → (3)² = 9, mas 1 + 4 = 5.'),
  ],
  questions: [
    mc(1, 'traduzir', 'Como se escreve “o triplo de um número mais 4”?', ['3 + x + 4', '3x + 4', 'x³ + 4', '3(x + 4)'], 1, ['Triplo = 3 vezes.', '3x.', 'Depois some 4.'], '3x + 4.'),
    mc(1, 'valor', 'Qual o valor de 2x + 5 para x = 3?', ['10', '11', '16', '13'], 1, ['Troque x por 3.', '2 · 3 = 6.', '6 + 5.'], '11.'),
    fill(1, 'semelhantes', 'Simplifique: 3x + 5x', ['8x'], ['São semelhantes.', 'Some os coeficientes.', '3 + 5.'], '8x.'),
    tf(1, 'semelhantes', '3x + 2y = 5xy.', false, ['x e y são semelhantes?', 'Não.', 'Não dá para juntar.'], 'Falso: termos diferentes não se somam.'),
    match(2, 'notaveis', 'Ligue cada produto ao desenvolvimento.', [['(x + 3)²', 'x² + 6x + 9'], ['(x − 3)²', 'x² − 6x + 9'], ['(x + 3)(x − 3)', 'x² − 9'], ['(2x)²', '4x²']], ['Quadrado da soma tem +2ab.', 'Da diferença, −2ab.', 'Soma × diferença: a² − b².'], 'Cada um com seu desenvolvimento.'),
    mc(2, 'valor', 'Qual o valor de x² − 4 para x = −2?', ['−8', '0', '8', '−4'], 1, ['Use parênteses: (−2)².', '(−2)² = 4.', '4 − 4.'], '0.'),
    mc(2, 'semelhantes', 'Simplifique 4a + 3b − a + 2b:', ['8ab', '3a + 5b', '5a + 5b', '3a + b'], 1, ['Junte a com a: 4a − a.', 'Junte b com b: 3b + 2b.', '3a + 5b.'], '3a + 5b.'),
    mc(3, 'notaveis', 'Qual é o desenvolvimento de (x + 5)²?', ['x² + 25', 'x² + 5x + 25', 'x² + 10x + 25', '2x + 10'], 2, ['a² + 2ab + b².', '2 · x · 5 = 10x.', 'Não esqueça o termo do meio.'], 'x² + 10x + 25.'),
    order(2, 'notaveis', 'Ordene os passos para desenvolver (a + b)².', ['Identificar a e b', 'Calcular a²', 'Calcular 2ab', 'Calcular b²', 'Somar tudo'], ['Primeiro saiba quem é a e b.', 'Depois os três termos.', 'Some no fim.'], 'a e b → a² → 2ab → b² → somar.'),
    open(3, 'notaveis', 'Mostre com um exemplo numérico por que (a + b)² não é igual a a² + b².', 'Com a = 1 e b = 2: (1 + 2)² = 3² = 9, mas 1² + 2² = 1 + 4 = 5. Falta o termo 2ab = 2 · 1 · 2 = 4, e 5 + 4 = 9.', ['9', '5', '2ab', 'falta', 'termo', 'meio'], ['Escolha números pequenos.', 'Calcule os dois lados.', 'Qual termo explica a diferença?'], 'O termo do meio 2ab é o que falta.'),
  ],
  review: ['Letras representam números: dobro 2x, metade x/2', 'Valor numérico: substitua (com parênteses) e respeite a ordem', 'Só termos semelhantes se somam', '(a+b)² = a²+2ab+b² · (a−b)² = a²−2ab+b² · (a+b)(a−b) = a²−b²'],
  relatedQuestions: ['o que é expressão algébrica', 'o que são produtos notáveis', 'como calcular valor numérico'],
  equivalentQuestions: eqsPt(['expressões algébricas', 'produtos notáveis', 'álgebra'], ['o que são termos semelhantes', 'como somar termos com letras', 'quadrado da soma de dois termos', 'quadrado da diferença', 'produto da soma pela diferença', 'como desenvolver (x + 3)²', 'como calcular o valor de uma expressão com x', 'o que é monômio', 'o que é polinômio', 'por que usar letras na matemática']),
  commonErrors: ['Esquecer o termo 2ab.', 'Somar termos não semelhantes.', 'Não usar parênteses ao substituir negativos.'],
  sources: FONTES,
})

export const sistemasEquacoes = lesson({
  id: 'mat-sistemas-equacoes', subject: 'matematica', title: 'Sistemas de equações do 1º grau', levels: [...EF2], grade: '8º ano',
  topic: 'Álgebra', subtopic: 'Sistemas com duas incógnitas: substituição e adição',
  aliases: ['sistema de equacoes', 'sistemas lineares', 'metodo da substituicao', 'metodo da adicao', 'duas incognitas', 'sistema 2x2', 'x e y'],
  summary: 'Resolva problemas com duas incógnitas montando sistemas e usando os métodos da substituição e da adição.',
  intro: 'Numa garagem há carros e motos, 20 veículos e 60 rodas. Quantos de cada? Duas incógnitas pedem duas equações!',
  objective: 'Montar sistemas de duas equações do 1º grau a partir de problemas e resolvê-los pelos métodos da substituição e da adição, verificando a solução.',
  prerequisites: ['mat-equacao-1-grau'], next: ['mat-equacao-2-grau', 'mat-funcao-1-grau'],
  skills: { conceito: 'O que é um sistema', substituicao: 'Método da substituição', adicao: 'Método da adição', problemas: 'Montar e resolver problemas' },
  blocks: [
    block('conceito', 'Duas equações, duas incógnitas',
      'Um sistema reúne equações que devem ser verdadeiras ao mesmo tempo. Com duas incógnitas (x e y), precisamos de duas equações. A solução é o par (x, y) que satisfaz as duas.',
      '{ x + y = 10 ; x − y = 2 } tem solução (6, 4): 6 + 4 = 10 e 6 − 4 = 2.',
      'Duas pistas para descobrir dois números.',
      'A soma das idades de dois irmãos é 20 e a diferença é 4: dois números, duas informações.',
      '1. Dê nome às incógnitas (x e y).\n2. Escreva uma equação para cada informação.\n3. Resolva e confira nas duas.',
      'Com uma equação só (x + y = 10) existem infinitas respostas; a segunda equação “escolhe” a certa.'),
    block('substituicao', 'Método da substituição',
      'Isole uma incógnita em uma das equações e substitua na outra. Assim sobra uma equação com uma incógnita só. Depois volte para achar a outra.',
      'x + y = 10 → x = 10 − y. Em x − y = 2: 10 − y − y = 2 → y = 4 → x = 6.',
      'Isola uma letra, joga na outra equação.',
      'Bom quando uma das letras já está “sozinha” ou com coeficiente 1.',
      '1. Isole x (ou y) numa equação.\n2. Substitua na outra.\n3. Resolva a equação que sobrou.\n4. Volte e calcule a outra incógnita.\n5. Confira nas duas equações.',
      'Substituição é como trocar uma palavra por um sinônimo: você troca x por “10 − y” sem mudar o sentido.'),
    block('adicao', 'Método da adição',
      'Some as equações membro a membro para eliminar uma incógnita. Se nenhuma sumir direto, multiplique uma (ou as duas) equações por números que deixem coeficientes opostos.',
      '{ 2x + y = 11 ; x − y = 1 } somando: 3x = 12 → x = 4 → y = 3.',
      'Some as equações para uma letra sumir.',
      'Ótimo quando já há +y numa e −y na outra.',
      '1. Deixe as incógnitas alinhadas.\n2. Se preciso, multiplique para criar opostos (+3y e −3y).\n3. Some.\n4. Resolva e volte para achar a outra.',
      'Os dois métodos chegam à mesma resposta; escolha o que dá menos contas.'),
    block('problemas', 'Montando problemas',
      'Leia o problema, escolha x e y, e transforme cada informação numa equação. Resolva e responda com as unidades. Confira se a resposta faz sentido (quantidades não negativas, inteiras quando for o caso).',
      'Carros (x) e motos (y): x + y = 20 e 4x + 2y = 60 → x = 10, y = 10.',
      'Cada frase com número vira uma equação.',
      '2 cadernos e 1 caneta custam R$ 23; 1 caderno e 1 caneta, R$ 14. Caderno = R$ 9, caneta = R$ 5.',
      '1. Defina x e y.\n2. Escreva as duas equações.\n3. Resolva por substituição ou adição.\n4. Confira e responda.',
      'É como um detetive cruzando duas pistas para descobrir dois suspeitos.'),
  ],
  questions: [
    mc(1, 'conceito', 'Qual par (x, y) é solução de x + y = 10 e x − y = 2?', ['(5, 5)', '(6, 4)', '(8, 2)', '(4, 6)'], 1, ['Teste nas duas.', '6 + 4 = 10.', '6 − 4 = 2.'], '(6, 4).'),
    tf(1, 'conceito', 'Para achar duas incógnitas, normalmente precisamos de duas equações.', true, ['Uma equação só tem infinitas respostas.', 'A segunda restringe.', 'Duas.'], 'Verdadeiro.'),
    fill(1, 'substituicao', 'Se x = 10 − y e x − y = 2, quanto vale y?', ['4'], ['Substitua: 10 − y − y = 2.', '10 − 2y = 2.', '2y = 8.'], 'y = 4.'),
    mc(2, 'adicao', 'Somando 2x + y = 11 e x − y = 1, obtemos:', ['3x = 12', '3x = 10', 'x = 11', '2y = 10'], 0, ['y e −y se cancelam.', '2x + x = 3x.', '11 + 1 = 12.'], '3x = 12.'),
    mc(2, 'problemas', 'Numa garagem há carros e motos: 20 veículos e 60 rodas. Quantos carros?', ['5', '10', '15', '20'], 1, ['x + y = 20 e 4x + 2y = 60.', 'Substitua y = 20 − x.', '4x + 40 − 2x = 60.'], '2x = 20 → x = 10 carros.'),
    mc(2, 'problemas', 'A soma de dois números é 30 e a diferença é 6. Qual o maior?', ['12', '15', '18', '24'], 2, ['x + y = 30 e x − y = 6.', 'Some: 2x = 36.', 'x = 18.'], '18 (o outro é 12).'),
    match(2, 'problemas', 'Ligue cada frase à equação.', [['A soma de x e y é 20', 'x + y = 20'], ['x é o dobro de y', 'x = 2y'], ['A diferença entre x e y é 5', 'x − y = 5'], ['O triplo de x mais y é 14', '3x + y = 14']], ['Soma = +.', 'Dobro = 2 ·.', 'Triplo = 3 ·.'], 'Tradução direta de cada frase.'),
    order(2, 'substituicao', 'Ordene os passos do método da substituição.', ['Isolar uma incógnita', 'Substituir na outra equação', 'Resolver a equação com uma incógnita', 'Calcular a outra incógnita', 'Conferir nas duas equações'], ['Comece isolando.', 'Depois substitua.', 'Termine conferindo.'], 'Isolar → substituir → resolver → voltar → conferir.'),
    mc(3, 'adicao', 'No sistema { x + 2y = 8 ; 3x − 2y = 8 }, quanto vale x?', ['2', '3', '4', '8'], 2, ['2y e −2y se cancelam.', 'Some: 4x = 16.', 'x = 4.'], 'x = 4 (e y = 2).'),
    mc(3, 'problemas', '2 cadernos e 1 caneta custam R$ 23; 1 caderno e 1 caneta, R$ 14. Quanto custa o caderno?', ['R$ 5', 'R$ 9', 'R$ 7', 'R$ 11'], 1, ['2c + p = 23 e c + p = 14.', 'Subtraia as equações.', 'c = 23 − 14.'], 'c = 9 (caneta R$ 5).'),
  ],
  review: ['Sistema: equações verdadeiras ao mesmo tempo', 'Substituição: isola e substitui', 'Adição: soma para eliminar uma incógnita (multiplique se preciso)', 'Sempre confira o par nas duas equações'],
  relatedQuestions: ['como resolver sistema de equações', 'método da substituição', 'método da adição'],
  equivalentQuestions: eqsPt(['sistema de equações', 'sistemas lineares'], ['como resolver sistema com x e y', 'o que é método da substituição', 'o que é método da adição', 'problema de carros e motos', 'soma e diferença de dois números', 'sistema de duas equações e duas incógnitas', 'como montar sistema a partir de problema', 'quando usar substituição ou adição', 'como conferir solução de sistema', 'sistema 2x2']),
  commonErrors: ['Achar só uma incógnita e esquecer a outra.', 'Errar sinais ao somar as equações.', 'Não conferir a solução nas duas equações.'],
  sources: FONTES,
})

export const estatistica = lesson({
  id: 'mat-estatistica-basica', subject: 'matematica', title: 'Estatística: média, moda e mediana', levels: [...EF2, 'medio'], grade: '6º ano ao Ensino Médio',
  topic: 'Estatística', subtopic: 'Medidas de tendência central e gráficos',
  aliases: ['estatistica', 'media', 'moda', 'mediana', 'media aritmetica', 'tabela e grafico', 'grafico de barras', 'grafico de setores', 'media ponderada'],
  summary: 'Calcule média, moda e mediana, entenda quando usar cada uma e leia tabelas e gráficos com atenção.',
  intro: 'Qual a nota da turma? Qual o tamanho de sapato mais vendido? Estatística ajuda a resumir dados.',
  objective: 'Calcular e interpretar média, moda e mediana, escolher a medida mais adequada e interpretar tabelas e gráficos, incluindo gráficos enganosos.',
  prerequisites: ['mat-numeros-decimais', 'mat-divisao'], next: ['mat-probabilidade'],
  formulas: [formula('Média aritmética', 'média = soma dos valores ÷ quantidade de valores', [['valores', 'os dados observados']])],
  skills: { media: 'Média aritmética', moda: 'Moda', mediana: 'Mediana', graficos: 'Tabelas e gráficos' },
  blocks: [
    block('media', 'Média aritmética',
      'A média é a soma de todos os valores dividida pela quantidade de valores. Ela representa um “valor equilibrado” do conjunto, mas é influenciada por valores muito altos ou muito baixos (extremos).',
      'Notas 6, 7, 8 e 9: média = 30 ÷ 4 = 7,5.',
      'Some tudo e divida pela quantidade.',
      'Gastei R$ 10, R$ 20 e R$ 30 em três dias: média de R$ 20 por dia.',
      '1. Some todos os valores.\n2. Conte quantos são.\n3. Divida a soma pela quantidade.',
      'Se num grupo de 5 pessoas uma ganha muito mais que as outras, a média sobe e deixa de representar bem o grupo — aí a mediana ajuda.'),
    block('moda', 'Moda',
      'Moda é o valor que mais se repete. Um conjunto pode ter uma moda, várias (bimodal) ou nenhuma. É útil também para dados que não são números (cor preferida, tamanho de roupa).',
      'Tamanhos vendidos: 38, 39, 39, 40, 39, 41 → moda = 39.',
      'Moda = o que mais aparece.',
      'A loja quer saber qual tamanho repor primeiro: o da moda.',
      '1. Conte quantas vezes cada valor aparece.\n2. O mais frequente é a moda.\n3. Se todos aparecem igual, não há moda.',
      '“Estar na moda” = o que muita gente usa. Na estatística é a mesma ideia: o valor mais frequente.'),
    block('mediana', 'Mediana',
      'Mediana é o valor do meio quando os dados estão em ordem. Se a quantidade de dados for par, a mediana é a média dos dois valores centrais. Ela não é afetada por valores extremos.',
      '3, 5, 7, 9, 100 → mediana = 7 (a média seria 24,8).',
      'Coloque em ordem e pegue o do meio.',
      'Salários de 1.500, 1.800, 2.000, 2.200 e 30.000: a mediana (2.000) representa melhor o grupo que a média.',
      '1. Ordene os valores.\n2. Quantidade ímpar: pegue o do meio.\n3. Quantidade par: faça a média dos dois do meio.',
      'Média, moda e mediana resumem os dados de formas diferentes — escolha a que melhor descreve a situação.'),
    block('graficos', 'Tabelas e gráficos',
      'Tabelas organizam dados; gráficos mostram comparações e tendências. Barras comparam categorias; linhas mostram evolução no tempo; setores (pizza) mostram partes de um todo (100%). Sempre leia o título, os eixos e a escala — um eixo que não começa no zero pode exagerar diferenças.',
      'Num gráfico de setores, uma fatia de 25% corresponde a 1/4 do círculo (90°).',
      'Leia título, eixos e escala antes de concluir.',
      'Duas barras de 98 e 100 parecem muito diferentes se o eixo começar em 95.',
      '1. Leia o título e a fonte.\n2. Veja o que cada eixo mede e a escala.\n3. Compare os valores.\n4. Desconfie de eixos cortados.',
      'Gráfico de linha é como um filme (mostra mudança no tempo); gráfico de barras é como uma foto comparando grupos.'),
  ],
  questions: [
    mc(1, 'media', 'Qual é a média de 6, 7, 8 e 9?', ['7', '7,5', '8', '30'], 1, ['Some: 30.', 'São 4 valores.', '30 ÷ 4.'], '7,5.'),
    mc(1, 'moda', 'Qual é a moda de 2, 3, 3, 5, 3, 7?', ['2', '3', '5', '7'], 1, ['Qual aparece mais?', 'Conte o 3.', 'Aparece 3 vezes.'], '3.'),
    fill(1, 'mediana', 'Qual é a mediana de 3, 5, 7, 9, 100?', ['7'], ['Já estão em ordem.', 'São 5 valores.', 'O do meio é o 3º.'], '7.'),
    tf(1, 'media', 'A média é influenciada por valores muito altos ou muito baixos.', true, ['A média soma todos.', 'Um valor enorme pesa na soma.', 'Sim.'], 'Verdadeiro.'),
    mc(2, 'mediana', 'Qual é a mediana de 4, 8, 6, 2?', ['4', '5', '6', '8'], 1, ['Ordene: 2, 4, 6, 8.', 'São 4 valores (par).', 'Média de 4 e 6.'], '(4 + 6) ÷ 2 = 5.'),
    match(2, 'graficos', 'Ligue cada gráfico ao melhor uso.', [['barras', 'comparar categorias'], ['linha', 'evolução no tempo'], ['setores (pizza)', 'partes de um todo'], ['tabela', 'organizar valores exatos']], ['Linha mostra mudança.', 'Pizza mostra fatias do total.', 'Barras comparam grupos.'], 'barras · linha · setores · tabela.'),
    mc(2, 'mediana', 'Salários: 1.500, 1.800, 2.000, 2.200, 30.000. Qual medida representa melhor o grupo?', ['Média', 'Mediana', 'Moda', 'Soma'], 1, ['Há um valor extremo.', 'A média fica distorcida.', 'A mediana não sofre com extremos.'], 'Mediana (2.000).'),
    order(2, 'mediana', 'Ordene os passos para achar a mediana.', ['Ordenar os valores', 'Contar quantos são', 'Localizar o(s) valor(es) central(is)', 'Se forem dois, calcular a média deles'], ['Primeiro organize.', 'Depois conte.', 'Então ache o meio.'], 'Ordenar → contar → meio → média dos centrais (se par).'),
    mc(3, 'media', 'A média de 4 provas foi 7. Com a 5ª prova, a média virou 7,4. Qual a nota da 5ª?', ['7,4', '8', '9', '10'], 2, ['Soma das 4: 4 · 7 = 28.', 'Soma das 5: 5 · 7,4 = 37.', '37 − 28.'], '9.'),
    open(3, 'graficos', 'Um gráfico de barras mostra vendas de 98 e 100 com o eixo começando em 95. Por que ele pode enganar?', 'Porque, com o eixo começando em 95, a barra de 100 parece o dobro ou mais da de 98, quando a diferença real é pequena (2 unidades, cerca de 2%). A escala cortada exagera a diferença.', ['eixo', 'escala', 'zero', 'exagera', 'diferença', 'pequena'], ['Onde começa o eixo?', 'A diferença real é grande?', 'Fale da escala.'], 'Eixos que não começam no zero exageram diferenças.'),
  ],
  review: ['Média = soma ÷ quantidade (sofre com extremos)', 'Moda = valor mais frequente', 'Mediana = valor do meio (ordenado); par → média dos centrais', 'Gráficos: leia título, eixos e escala'],
  relatedQuestions: ['como calcular média moda e mediana', 'diferença entre média e mediana', 'como ler gráficos'],
  equivalentQuestions: eqsPt(['média', 'moda', 'mediana', 'estatística'], ['como calcular a média das notas', 'diferença entre média e mediana', 'o que é moda na estatística', 'mediana com número par de valores', 'quando usar mediana', 'como ler gráfico de barras', 'gráfico de pizza porcentagem', 'média ponderada', 'que nota preciso tirar para ficar com média 7', 'gráfico enganoso']),
  commonErrors: ['Calcular a mediana sem ordenar os dados.', 'Usar a média com valores extremos.', 'Ignorar a escala dos gráficos.'],
  sources: FONTES, enem: 'Leitura de gráficos e medidas de tendência central são cobradas todos os anos.',
})

export const probabilidade = lesson({
  id: 'mat-probabilidade', subject: 'matematica', title: 'Probabilidade', levels: [...EF2, 'medio'], grade: '7º ano ao Ensino Médio',
  topic: 'Estatística', subtopic: 'Espaço amostral, eventos e cálculo de probabilidade',
  aliases: ['probabilidade', 'chance', 'espaco amostral', 'evento', 'evento complementar', 'probabilidade de dado', 'probabilidade de moeda', 'casos favoraveis'],
  summary: 'Calcule chances com casos favoráveis sobre casos possíveis, use eventos complementares e interprete resultados.',
  intro: 'Qual a chance de sair 6 num dado? De chover amanhã? Probabilidade mede o quanto algo é provável.',
  objective: 'Identificar o espaço amostral de um experimento, calcular probabilidades como fração, decimal e porcentagem e usar o evento complementar.',
  prerequisites: ['mat-fracoes', 'mat-porcentagem'], next: ['mat-analise-combinatoria'],
  formulas: [formula('Probabilidade', 'P(A) = casos favoráveis ÷ casos possíveis', [['A', 'evento'], ['casos possíveis', 'elementos do espaço amostral (igualmente prováveis)']], '0 ≤ P ≤ 1 · P(não A) = 1 − P(A)')],
  skills: { conceito: 'Experimento aleatório e espaço amostral', calcular: 'Calcular a probabilidade', complementar: 'Evento complementar', interpretar: 'Interpretar resultados' },
  blocks: [
    block('conceito', 'Experimentos e espaço amostral',
      'Experimento aleatório é aquele cujo resultado não dá para prever com certeza (jogar um dado, sortear um nome). Espaço amostral é o conjunto de todos os resultados possíveis. Evento é o resultado (ou grupo de resultados) que nos interessa.',
      'Dado: espaço amostral {1, 2, 3, 4, 5, 6}. Evento “número par”: {2, 4, 6}.',
      'Espaço amostral = tudo que pode acontecer.',
      'Tirar uma bola de uma urna com 3 azuis e 2 vermelhas: 5 resultados possíveis.',
      '1. Liste todos os resultados possíveis.\n2. Marque os que formam o evento.',
      'Um jogo de cara ou coroa tem espaço amostral {cara, coroa}; uma roleta com 10 números, {1, …, 10}.'),
    block('calcular', 'Favoráveis sobre possíveis',
      'Quando todos os resultados têm a mesma chance, P = casos favoráveis ÷ casos possíveis. O resultado fica entre 0 (impossível) e 1 (certo) e pode ser escrito como fração, decimal ou porcentagem.',
      'Sair número par no dado: 3/6 = 1/2 = 0,5 = 50%.',
      'Chance = o que eu quero ÷ tudo que pode acontecer.',
      'Numa rifa de 100 números, quem comprou 5 tem 5/100 = 5% de chance.',
      '1. Conte os casos possíveis.\n2. Conte os favoráveis.\n3. Divida.\n4. Converta para % se pedirem.',
      'Probabilidade é uma fração do espaço amostral, como porcentagem é uma fração de 100.'),
    block('complementar', 'Evento complementar',
      'O complementar de A (“não A”) reúne tudo que não é A. Como algo sempre acontece, P(A) + P(não A) = 1. Às vezes é mais fácil calcular o complementar e subtrair de 1.',
      'P(sair 6) = 1/6 → P(não sair 6) = 5/6.',
      'A chance de NÃO acontecer = 1 − chance de acontecer.',
      'Previsão de 30% de chuva = 70% de chance de não chover.',
      '1. Calcule a probabilidade do evento contrário.\n2. Subtraia de 1 (ou de 100%).',
      'É como o troco: se a chance de acontecer é 30 de 100, o “restante” (70) é a chance de não acontecer.'),
    block('interpretar', 'Interpretando',
      'Probabilidade descreve o que tende a acontecer em muitas repetições, não garante o próximo resultado. Uma moeda que deu cara 5 vezes seguidas continua com 1/2 de chance de cara na próxima jogada (os lançamentos são independentes).',
      'Chance de 1/6 não quer dizer que o 6 sai exatamente uma vez a cada 6 jogadas.',
      'Probabilidade fala de tendência, não de certeza.',
      'Em 600 jogadas de dado, espera-se cerca de 100 “seis” — pode dar 92 ou 107.',
      '1. Lembre que cada jogada é independente.\n2. Pense em muitas repetições.\n3. Compare chances, não garantias.',
      'Achar que “agora tem que sair coroa” depois de muitas caras é um erro conhecido: a moeda não tem memória.'),
  ],
  questions: [
    mc(1, 'calcular', 'Qual a probabilidade de sair 4 num dado comum?', ['1/4', '1/6', '4/6', '1/2'], 1, ['6 resultados possíveis.', '1 favorável (o 4).', '1/6.'], '1/6.'),
    mc(1, 'conceito', 'Qual o espaço amostral de uma moeda?', ['{cara}', '{cara, coroa}', '{1, 2}', '{cara, coroa, em pé}'], 1, ['Quais resultados podem sair?', 'Dois lados.', 'Cara e coroa.'], '{cara, coroa}.'),
    fill(1, 'complementar', 'Se a chance de chover é 30%, qual a chance de NÃO chover? (em %)', ['70', '70%'], ['Tudo soma 100%.', '100 − 30.', '70.'], '70%.'),
    tf(1, 'interpretar', 'Depois de 5 caras seguidas, a chance de dar coroa na próxima é maior que 1/2.', false, ['A moeda tem memória?', 'Lançamentos são independentes.', 'Continua 1/2.'], 'Falso: continua 1/2.'),
    mc(2, 'calcular', 'Uma urna tem 3 bolas azuis e 2 vermelhas. Qual a chance de tirar azul?', ['3/2', '2/5', '3/5', '1/3'], 2, ['Total: 5 bolas.', 'Favoráveis: 3.', '3/5.'], '3/5 = 60%.'),
    mc(2, 'calcular', 'Qual a probabilidade de sair número par num dado?', ['1/6', '1/3', '1/2', '2/3'], 2, ['Pares: 2, 4, 6.', '3 favoráveis de 6.', '3/6.'], '1/2 = 50%.'),
    match(2, 'calcular', 'Ligue cada probabilidade à porcentagem.', [['1/2', '50%'], ['1/4', '25%'], ['1/5', '20%'], ['3/4', '75%']], ['Divida e multiplique por 100.', '1 ÷ 4 = 0,25.', '3 ÷ 4 = 0,75.'], '50% · 25% · 20% · 75%.'),
    order(2, 'calcular', 'Ordene os eventos do MENOS para o MAIS provável (um dado).', ['sair 7', 'sair 6', 'sair par', 'sair número de 1 a 6'], ['Impossível = 0.', '1/6 < 3/6.', 'Certeza = 1.'], '0 < 1/6 < 1/2 < 1.'),
    mc(3, 'complementar', 'Jogando um dado, qual a probabilidade de NÃO sair 6?', ['1/6', '5/6', '6/5', '1/5'], 1, ['P(6) = 1/6.', 'Complementar: 1 − 1/6.', '5/6.'], '5/6.'),
    mc(3, 'calcular', 'Numa rifa de 200 números, você comprou 8. Qual sua chance de ganhar?', ['8%', '4%', '2,5%', '0,4%'], 1, ['8/200.', '= 0,04.', '× 100.'], '8/200 = 4%.'),
  ],
  review: ['Espaço amostral = todos os resultados possíveis', 'P = favoráveis ÷ possíveis (entre 0 e 1)', 'P(não A) = 1 − P(A)', 'Cada lançamento é independente; probabilidade é tendência'],
  relatedQuestions: ['como calcular probabilidade', 'o que é espaço amostral', 'probabilidade de um dado'],
  equivalentQuestions: eqsPt(['probabilidade', 'espaço amostral'], ['qual a chance de sair 6 no dado', 'probabilidade de cara ou coroa', 'como calcular chance em porcentagem', 'o que é evento complementar', 'probabilidade de não acontecer', 'probabilidade com bolas na urna', 'chance de ganhar na rifa', 'a moeda tem memória', 'o que é experimento aleatório', 'casos favoráveis e possíveis']),
  commonErrors: ['Esquecer casos no espaço amostral.', 'Achar que resultados passados mudam a chance futura.', 'Dar probabilidade maior que 1.'],
  sources: FONTES,
})
