// LOTE 1 — MATEMÁTICA · Ensino Médio. Conteúdo original do LUMI.
import { block, eqsPt, fill, formula, lesson, match, mc, open, order, SRC, tf } from '../dsl'

const FONTES = [SRC.bncc('Matemática e suas Tecnologias — Ensino Médio'), SRC.obmep(), SRC.autoral()]
const EM = ['medio'] as const

export const funcao2grau = lesson({
  id: 'mat-funcao-2-grau', subject: 'matematica', title: 'Função do 2º grau (quadrática)', levels: [...EM], grade: '1ª série',
  topic: 'Funções', subtopic: 'Parábola, raízes, vértice, máximo e mínimo',
  aliases: ['funcao do segundo grau', 'funcao quadratica', 'parabola', 'vertice da parabola', 'concavidade', 'valor maximo', 'valor minimo', 'xv yv'],
  summary: 'Entenda a parábola: concavidade, raízes, vértice e como achar valores máximos e mínimos.',
  intro: 'A trajetória de uma bola chutada para cima desenha uma curva: a parábola da função do 2º grau.',
  objective: 'Reconhecer f(x) = ax² + bx + c, analisar concavidade e raízes, calcular o vértice e resolver problemas de máximo e mínimo.',
  prerequisites: ['mat-equacao-2-grau', 'mat-funcao-1-grau'], next: ['mat-logaritmo'],
  formulas: [
    formula('Função quadrática', 'f(x) = ax² + bx + c', [['a', 'coeficiente de x² (a ≠ 0)'], ['b', 'coeficiente de x'], ['c', 'onde a parábola corta o eixo y']]),
    formula('Vértice', 'xᵥ = −b ÷ 2a · yᵥ = −Δ ÷ 4a', [['Δ', 'b² − 4ac']]),
  ],
  skills: { forma: 'Forma e concavidade', raizes: 'Raízes e o eixo x', vertice: 'Vértice', maxmin: 'Máximo e mínimo em problemas' },
  blocks: [
    block('forma', 'A parábola e a concavidade',
      'A função do 2º grau é f(x) = ax² + bx + c, com a ≠ 0. Seu gráfico é uma parábola. Se a > 0, a concavidade é para cima (formato de “U”); se a < 0, para baixo (formato de “∩”). O valor c é onde a parábola corta o eixo y.',
      'f(x) = x² − 4x + 3: a = 1 > 0 → “U”; corta o eixo y em 3.',
      'a positivo: sorri (U). a negativo: fica triste (∩).',
      'A bola chutada para cima segue uma parábola com a < 0: sobe, chega ao ponto mais alto e desce.',
      '1. Olhe o sinal de a.\n2. Positivo: U; negativo: ∩.\n3. O c mostra onde corta o eixo y (x = 0).',
      'Na função do 1º grau o gráfico é uma reta; na do 2º, é uma curva simétrica, porque x está ao quadrado.'),
    block('raizes', 'Raízes: onde a parábola toca o eixo x',
      'As raízes são os valores de x com f(x) = 0 — são as soluções de ax² + bx + c = 0 (Bhaskara). O Δ indica quantas vezes a parábola toca o eixo x: Δ > 0 duas vezes, Δ = 0 uma (encosta), Δ < 0 nenhuma.',
      'f(x) = x² − 4x + 3: raízes 1 e 3 (a parábola corta o eixo x nesses pontos).',
      'Raiz = onde o gráfico encosta ou corta o eixo x.',
      'Na trajetória da bola, as raízes marcam onde ela sai do chão e onde volta a tocá-lo.',
      '1. Iguale f(x) a zero.\n2. Calcule Δ.\n3. Use Bhaskara.\n4. Marque as raízes no eixo x.',
      'Achar as raízes da função é o mesmo que resolver a equação do 2º grau que você já conhece.'),
    block('vertice', 'O vértice',
      'O vértice é o ponto de virada da parábola: o mais baixo (se a > 0) ou o mais alto (se a < 0). Suas coordenadas são xᵥ = −b/2a e yᵥ = −Δ/4a (ou basta calcular f(xᵥ)). A parábola é simétrica em relação à reta vertical que passa pelo vértice.',
      'f(x) = x² − 4x + 3: xᵥ = 4/2 = 2; yᵥ = f(2) = 4 − 8 + 3 = −1 → V(2, −1).',
      'Vértice = o “bico” da parábola.',
      'O ponto mais alto da trajetória de um salto é o vértice.',
      '1. Calcule xᵥ = −b ÷ 2a.\n2. Substitua na função para achar yᵥ.\n3. O vértice é (xᵥ, yᵥ).',
      'O xᵥ fica exatamente no meio das duas raízes: (1 + 3) ÷ 2 = 2.'),
    block('maxmin', 'Máximo e mínimo',
      'Se a < 0, yᵥ é o valor MÁXIMO da função; se a > 0, é o valor MÍNIMO. Isso resolve problemas como maior área, maior lucro, altura máxima ou menor custo.',
      'Lucro L(x) = −x² + 10x: xᵥ = 5 → lucro máximo L(5) = 25.',
      'a negativo → o vértice é o topo (máximo).',
      'Com 20 m de cerca, o retângulo de maior área é o quadrado de 5 m × 5 m: A(x) = x(10 − x) tem máximo em x = 5.',
      '1. Monte a função do problema.\n2. Veja o sinal de a.\n3. Calcule o vértice.\n4. xᵥ diz “quando”; yᵥ diz “quanto” (o máximo ou mínimo).',
      'É por isso que o Enem gosta da parábola: ela modela “o melhor ponto” de muitas situações.'),
  ],
  questions: [
    mc(1, 'forma', 'Em f(x) = −2x² + 3x + 1, a concavidade é:', ['para cima', 'para baixo', 'reta', 'não dá para saber'], 1, ['Olhe o sinal de a.', 'a = −2.', 'Negativo → ∩.'], 'a < 0: concavidade para baixo.'),
    mc(1, 'forma', 'Onde f(x) = x² − 5x + 6 corta o eixo y?', ['5', '−5', '6', '1'], 2, ['Eixo y: x = 0.', 'f(0) = c.', 'c = 6.'], '(0, 6).'),
    fill(1, 'vertice', 'Qual o xᵥ de f(x) = x² − 4x + 3?', ['2'], ['xᵥ = −b ÷ 2a.', 'b = −4, a = 1.', '4 ÷ 2.'], 'xᵥ = 2.'),
    tf(1, 'raizes', 'Se Δ < 0, a parábola não toca o eixo x.', true, ['Δ < 0 → sem raízes reais.', 'Raízes são onde toca o eixo x.', 'Então não toca.'], 'Verdadeiro.'),
    mc(2, 'raizes', 'Quais as raízes de f(x) = x² − 5x + 6?', ['2 e 3', '−2 e −3', '1 e 6', '5 e 6'], 0, ['Δ = 25 − 24 = 1.', 'x = (5 ± 1) ÷ 2.', '3 e 2.'], '2 e 3.'),
    mc(2, 'vertice', 'Qual é o vértice de f(x) = x² − 4x + 3?', ['(2, −1)', '(−2, 15)', '(2, 3)', '(4, 3)'], 0, ['xᵥ = 2.', 'f(2) = 4 − 8 + 3.', '= −1.'], 'V(2, −1).'),
    match(2, 'forma', 'Ligue cada condição ao que ela indica.', [['a > 0', 'concavidade para cima'], ['a < 0', 'concavidade para baixo'], ['Δ = 0', 'uma raiz (toca o eixo x)'], ['Δ > 0', 'duas raízes reais']], ['a define a concavidade.', 'Δ define as raízes.', 'Δ = 0 encosta no eixo.'], 'Cada condição com seu significado.'),
    mc(3, 'maxmin', 'O lucro de uma loja é L(x) = −x² + 10x (em mil reais). Qual o lucro máximo?', ['5 mil', '10 mil', '25 mil', '50 mil'], 2, ['a < 0: tem máximo.', 'xᵥ = −10 ÷ (−2) = 5.', 'L(5) = −25 + 50.'], 'L(5) = 25 mil reais.'),
    order(2, 'vertice', 'Ordene os passos para achar o valor máximo de uma função quadrática.', ['Conferir que a < 0', 'Calcular xᵥ = −b ÷ 2a', 'Calcular f(xᵥ)', 'Interpretar yᵥ como o máximo'], ['Primeiro confirme que existe máximo.', 'Depois o x do vértice.', 'Por fim o valor.'], 'a < 0 → xᵥ → f(xᵥ) → máximo.'),
    open(3, 'maxmin', 'Com 20 m de cerca, qual retângulo tem a maior área? Justifique com a função.', 'Se um lado mede x, o outro mede 10 − x (pois 2x + 2y = 20). A área é A(x) = x(10 − x) = −x² + 10x, que tem a < 0 e máximo no vértice xᵥ = 5. Então o retângulo de maior área é o quadrado de 5 m × 5 m, com 25 m².', ['10 - x', 'vertice', '5', 'quadrado', '25', 'maximo'], ['Chame um lado de x.', 'O outro lado é 10 − x.', 'Ache o vértice de A(x).'], 'A área máxima ocorre no vértice: quadrado 5 × 5.'),
  ],
  review: ['f(x) = ax² + bx + c · gráfico: parábola', 'a > 0 → U (mínimo) · a < 0 → ∩ (máximo)', 'Raízes: Bhaskara; Δ diz quantas', 'Vértice: xᵥ = −b/2a, yᵥ = f(xᵥ) = −Δ/4a'],
  relatedQuestions: ['o que é função do segundo grau', 'como calcular o vértice da parábola', 'como achar o valor máximo'],
  equivalentQuestions: eqsPt(['função do segundo grau', 'função quadrática', 'parábola'], ['como saber a concavidade da parábola', 'fórmula do vértice', 'xv e yv', 'valor máximo da função', 'valor mínimo da função', 'onde a parábola corta o eixo y', 'raízes da função quadrática', 'gráfico da função do segundo grau', 'lucro máximo com função', 'altura máxima da bola']),
  commonErrors: ['Confundir o sinal de a com o de c.', 'Esquecer o sinal de b em xᵥ = −b/2a.', 'Achar que toda parábola tem máximo.'],
  sources: FONTES, enem: 'Máximos e mínimos (lucro, área, altura) aparecem com frequência.',
})

export const progressoes = lesson({
  id: 'mat-progressoes', subject: 'matematica', title: 'Progressões: PA e PG', levels: [...EM], grade: '1ª série',
  topic: 'Sequências', subtopic: 'Progressão aritmética e progressão geométrica',
  aliases: ['progressao aritmetica', 'progressao geometrica', 'pa', 'pg', 'razao da pa', 'termo geral', 'soma dos termos da pa', 'sequencias numericas'],
  summary: 'Reconheça sequências que crescem somando (PA) ou multiplicando (PG) e use termo geral e soma.',
  intro: '2, 5, 8, 11… ou 2, 6, 18, 54…? Uma soma sempre o mesmo número; a outra multiplica.',
  objective: 'Identificar PA e PG, calcular razão, termo geral e soma dos termos e aplicar em problemas.',
  prerequisites: ['mat-funcao-1-grau', 'mat-potenciacao-radiciacao'], next: ['mat-juros'],
  formulas: [
    formula('Termo geral da PA', 'aₙ = a₁ + (n − 1) · r', [['a₁', 'primeiro termo'], ['r', 'razão'], ['n', 'posição do termo']]),
    formula('Soma da PA', 'Sₙ = (a₁ + aₙ) · n ÷ 2', [['n', 'quantidade de termos']]),
    formula('Termo geral da PG', 'aₙ = a₁ · qⁿ⁻¹', [['q', 'razão da PG']]),
    formula('Soma da PG finita', 'Sₙ = a₁ · (qⁿ − 1) ÷ (q − 1)', [['q', 'razão (q ≠ 1)']]),
  ],
  skills: { pa: 'Progressão aritmética', somapa: 'Soma da PA', pg: 'Progressão geométrica', aplicar: 'Aplicações e comparação' },
  blocks: [
    block('pa', 'PA: soma sempre o mesmo número',
      'Na progressão aritmética, cada termo é o anterior mais uma constante r (razão). Termo geral: aₙ = a₁ + (n − 1) · r. Se r > 0 a PA cresce; se r < 0, decresce.',
      '3, 7, 11, 15…: r = 4; o 10º termo é 3 + 9 · 4 = 39.',
      'PA = pulando de r em r.',
      'Uma poupança em que você guarda R$ 50 a mais a cada mês forma uma PA.',
      '1. Calcule r = segundo − primeiro.\n2. Confira se a diferença se repete.\n3. Use aₙ = a₁ + (n − 1) · r.',
      'Uma PA é como uma função do 1º grau: cresce sempre a mesma quantidade (seus pontos ficam sobre uma reta).'),
    block('somapa', 'Soma da PA',
      'A soma dos n primeiros termos é Sₙ = (a₁ + aₙ) · n ÷ 2. A ideia: o primeiro somado com o último dá o mesmo que o segundo com o penúltimo, e assim por diante.',
      'Soma de 1 a 100: (1 + 100) · 100 ÷ 2 = 5.050.',
      'Some o primeiro com o último, multiplique pela quantidade e divida por 2.',
      'Uma escada de blocos com 1, 2, 3, …, 20 blocos por degrau usa (1 + 20) · 20 ÷ 2 = 210 blocos.',
      '1. Descubra a₁ e aₙ.\n2. Conte os termos (n).\n3. Aplique Sₙ = (a₁ + aₙ) · n ÷ 2.',
      'É como emparelhar os extremos: 1 + 100, 2 + 99, 3 + 98… sempre 101, em 50 pares.'),
    block('pg', 'PG: multiplica sempre pelo mesmo número',
      'Na progressão geométrica, cada termo é o anterior multiplicado por uma constante q (razão). Termo geral: aₙ = a₁ · qⁿ⁻¹. Soma finita: Sₙ = a₁ · (qⁿ − 1) ÷ (q − 1).',
      '2, 6, 18, 54…: q = 3; o 6º termo é 2 · 3⁵ = 486.',
      'PG = multiplicando por q.',
      'Uma bactéria que se divide a cada hora dobra a população: 1, 2, 4, 8, 16… (q = 2).',
      '1. Calcule q = segundo ÷ primeiro.\n2. Confira se a divisão se repete.\n3. Use aₙ = a₁ · qⁿ⁻¹.',
      'PA cresce “em linha reta”; PG cresce cada vez mais rápido (crescimento exponencial).'),
    block('aplicar', 'Aplicações',
      'PA aparece em aumentos constantes (parcelas fixas, andares, filas). PG aparece em crescimento ou decrescimento percentual (juros compostos, população, depreciação, meia-vida). Em PG, uma taxa de i% ao período corresponde a q = 1 + i/100.',
      'Salário que aumenta R$ 100 por ano: PA. Investimento que rende 10% ao ano: PG com q = 1,1.',
      'Somar fixo → PA. Multiplicar (porcentagem) → PG.',
      'Um celular que perde 20% do valor por ano: PG com q = 0,8.',
      '1. A mudança é um valor fixo? PA.\n2. É uma porcentagem? PG (q = 1 ± taxa).\n3. Use as fórmulas.',
      'Juros simples formam uma PA; juros compostos formam uma PG.'),
  ],
  questions: [
    mc(1, 'pa', 'Qual é a razão da PA 3, 7, 11, 15?', ['3', '4', '7', '11'], 1, ['r = segundo − primeiro.', '7 − 3.', 'Confira: 11 − 7.'], 'r = 4.'),
    mc(1, 'pg', 'Qual é a razão da PG 2, 6, 18, 54?', ['3', '4', '6', '2'], 0, ['q = segundo ÷ primeiro.', '6 ÷ 2.', 'Confira: 18 ÷ 6.'], 'q = 3.'),
    fill(1, 'pa', 'Qual é o 10º termo da PA 3, 7, 11, …?', ['39'], ['aₙ = a₁ + (n − 1) · r.', '3 + 9 · 4.', '3 + 36.'], 'a₁₀ = 39.'),
    tf(1, 'aplicar', 'Um valor que aumenta 10% por período forma uma PG de razão 1,1.', true, ['Aumentar 10% = multiplicar por…', '1 + 0,10.', '1,1.'], 'Verdadeiro.'),
    mc(2, 'somapa', 'Qual é a soma dos números de 1 a 100?', ['5.000', '5.050', '10.100', '4.950'], 1, ['Sₙ = (a₁ + aₙ) · n ÷ 2.', '(1 + 100) · 100 ÷ 2.', '101 · 50.'], '5.050.'),
    mc(2, 'pg', 'Qual é o 6º termo da PG 2, 6, 18…?', ['162', '486', '1.458', '54'], 1, ['aₙ = a₁ · qⁿ⁻¹.', '2 · 3⁵.', '3⁵ = 243.'], '2 · 243 = 486.'),
    match(2, 'aplicar', 'Classifique cada situação.', [['Guardar R$ 50 a mais por mês', 'PA'], ['População que dobra a cada ano', 'PG']], ['Valor fixo → PA.', 'Multiplica → PG.', 'Porcentagem → PG.'], 'PA · PG · PA · PG.'),
    order(2, 'pa', 'Ordene os termos da PA de a₁ = 20 e r = −5.', ['20', '15', '10', '5', '0'], ['r negativo: decresce.', '20 − 5 = 15.', 'Continue.'], '20, 15, 10, 5, 0.'),
    mc(3, 'somapa', 'Uma pilha tem 1 lata no topo, 2 na fila seguinte, e assim até 20 latas na base. Quantas latas?', ['200', '210', '220', '400'], 1, ['PA de 1 a 20.', 'S = (1 + 20) · 20 ÷ 2.', '21 · 10.'], '210 latas.'),
    open(3, 'aplicar', 'Explique a diferença entre crescer por PA e crescer por PG, com um exemplo de cada.', 'Na PA o valor aumenta sempre a mesma quantidade (soma), como guardar R$ 100 a mais por mês. Na PG o valor é multiplicado sempre pelo mesmo fator, como uma aplicação que rende 10% ao mês; por isso a PG cresce cada vez mais rápido.', ['soma', 'multiplica', 'mesma', 'fator', 'razao', 'porcentagem', 'rapido'], ['PA: o que se repete?', 'PG: o que se repete?', 'Qual cresce mais rápido no longo prazo?'], 'PA soma uma constante; PG multiplica por uma constante.'),
  ],
  review: ['PA: aₙ = a₁ + (n − 1)r · Sₙ = (a₁ + aₙ)n/2', 'PG: aₙ = a₁ · qⁿ⁻¹ · Sₙ = a₁(qⁿ − 1)/(q − 1)', 'Aumento fixo → PA; porcentagem → PG (q = 1 ± i)', 'Juros simples ~ PA; compostos ~ PG'],
  relatedQuestions: ['o que é PA e PG', 'como calcular o termo geral da PA', 'soma dos termos da PA'],
  equivalentQuestions: eqsPt(['progressão aritmética', 'progressão geométrica', 'PA e PG'], ['como achar a razão da PA', 'como achar a razão da PG', 'fórmula do termo geral', 'soma de 1 a 100', 'diferença entre PA e PG', 'PG crescimento exponencial', 'soma da PG finita', 'como calcular o décimo termo', 'sequência que multiplica por 2', 'PA decrescente']),
  commonErrors: ['Usar n em vez de (n − 1) no termo geral.', 'Confundir PA (soma) com PG (multiplica).', 'Esquecer que aumento percentual vira q = 1 + taxa.'],
  sources: FONTES,
})

export const trigonometria = lesson({
  id: 'mat-trigonometria-triangulo', subject: 'matematica', title: 'Trigonometria no triângulo retângulo', levels: ['fund2', 'medio'], grade: '9º ano e 1ª série',
  topic: 'Geometria', subtopic: 'Seno, cosseno, tangente e ângulos notáveis',
  aliases: ['trigonometria', 'seno cosseno tangente', 'soh cah toa', 'angulos notaveis', 'seno de 30', 'seno de 30 graus', 'cosseno de 60 graus', 'tangente de 45 graus', 'tangente', 'razoes trigonometricas', 'cateto oposto', 'cateto adjacente'],
  summary: 'Use seno, cosseno e tangente para achar lados e ângulos de triângulos retângulos e resolva problemas de altura e distância.',
  intro: 'Como medir a altura de um prédio sem subir nele? Com um ângulo e a trigonometria!',
  objective: 'Identificar cateto oposto, adjacente e hipotenusa em relação a um ângulo, aplicar seno, cosseno e tangente, usar os ângulos notáveis e resolver problemas de altura e distância.',
  prerequisites: ['mat-teorema-pitagoras', 'mat-angulos'], next: ['mat-geometria-espacial'],
  formulas: [formula('Razões trigonométricas', 'sen θ = CO ÷ H · cos θ = CA ÷ H · tg θ = CO ÷ CA', [['CO', 'cateto oposto a θ'], ['CA', 'cateto adjacente a θ'], ['H', 'hipotenusa']], 'Só em triângulos retângulos; θ é um dos ângulos agudos.')],
  skills: { lados: 'Oposto, adjacente e hipotenusa', razoes: 'Seno, cosseno e tangente', notaveis: 'Ângulos notáveis (30°, 45°, 60°)', problemas: 'Altura e distância' },
  blocks: [
    block('lados', 'Nomes dos lados em relação ao ângulo',
      'Num triângulo retângulo, a hipotenusa é o lado oposto ao ângulo reto. Em relação a um ângulo agudo θ: o cateto oposto é o lado “à frente” de θ; o cateto adjacente é o cateto que forma θ junto com a hipotenusa.',
      'Numa rampa, se θ é o ângulo com o chão, a altura é o cateto oposto e o comprimento no chão é o adjacente.',
      'Oposto = de frente para o ângulo. Adjacente = do lado dele.',
      'Uma escada apoiada na parede: a escada é a hipotenusa; a altura na parede é oposta ao ângulo com o chão.',
      '1. Ache o ângulo reto → a hipotenusa está à frente dele.\n2. Escolha o ângulo θ.\n3. O lado à frente de θ é o oposto; o outro cateto é o adjacente.',
      'O mesmo cateto pode ser oposto para um ângulo e adjacente para o outro: tudo depende de qual ângulo você escolheu.'),
    block('razoes', 'Seno, cosseno e tangente',
      'sen θ = cateto oposto ÷ hipotenusa; cos θ = cateto adjacente ÷ hipotenusa; tg θ = cateto oposto ÷ cateto adjacente. Um jeito de lembrar: “SOH-CAH-TOA” (Seno = Oposto/Hipotenusa, Cosseno = Adjacente/Hipotenusa, Tangente = Oposto/Adjacente).',
      'Triângulo 3-4-5, com θ oposto ao lado 3: sen θ = 3/5, cos θ = 4/5, tg θ = 3/4.',
      'Cada razão divide dois lados escolhidos.',
      'A inclinação de uma rampa (subida ÷ distância no chão) é a tangente do ângulo.',
      '1. Veja quais lados você tem e qual quer.\n2. Escolha a razão que usa esses dois lados.\n3. Monte a equação e resolva.',
      'Seno e cosseno nunca passam de 1 (a hipotenusa é o maior lado); a tangente pode ser maior que 1.'),
    block('notaveis', 'Ângulos notáveis',
      'Valores que aparecem muito: sen 30° = 1/2, cos 30° = √3/2, tg 30° = √3/3; sen 45° = cos 45° = √2/2, tg 45° = 1; sen 60° = √3/2, cos 60° = 1/2, tg 60° = √3. (√2 ≈ 1,41 e √3 ≈ 1,73.)',
      'sen 30° = cos 60° = 1/2: ângulos complementares trocam seno e cosseno.',
      'Decore a tabela de 30°, 45° e 60°.',
      'Uma escada de 4 m apoiada formando 60° com o chão alcança 4 · sen 60° ≈ 3,46 m de altura.',
      '1. Monte a tabela: senos 1/2, √2/2, √3/2.\n2. Cossenos na ordem inversa.\n3. Tangente = seno ÷ cosseno.',
      'O seno de um ângulo é o cosseno do seu complemento: sen 30° = cos 60°.'),
    block('problemas', 'Problemas de altura e distância',
      'Com um ângulo e um lado conhecido, dá para descobrir os outros lados. É assim que se mede a altura de prédios e árvores a distância, ou a largura de um rio sem atravessá-lo.',
      'A 20 m de um prédio, você vê o topo sob 45°: altura = 20 · tg 45° = 20 m.',
      'Desenhe o triângulo e escolha a razão certa.',
      'Um avião decola num ângulo de 30° e percorre 1.000 m em linha reta: sobe 1.000 · sen 30° = 500 m.',
      '1. Desenhe o triângulo retângulo.\n2. Marque o ângulo e os lados conhecidos.\n3. Escolha seno, cosseno ou tangente.\n4. Resolva.',
      'Pitágoras usa os três lados; a trigonometria liga lados e ângulos — por isso ela resolve casos em que Pitágoras sozinho não resolve.'),
  ],
  questions: [
    mc(1, 'razoes', 'O seno de um ângulo é:', ['oposto ÷ adjacente', 'oposto ÷ hipotenusa', 'adjacente ÷ hipotenusa', 'hipotenusa ÷ oposto'], 1, ['SOH.', 'Seno = Oposto / Hipotenusa.', 'O ÷ H.'], 'sen = CO ÷ H.'),
    mc(1, 'notaveis', 'Quanto vale sen 30°?', ['√3/2', '1/2', '√2/2', '1'], 1, ['É um ângulo notável.', 'Metade.', '1/2.'], 'sen 30° = 1/2.'),
    fill(1, 'notaveis', 'Quanto vale tg 45°?', ['1'], ['tg = sen ÷ cos.', 'sen 45° = cos 45°.', 'Número dividido por ele mesmo.'], 'tg 45° = 1.'),
    tf(1, 'lados', 'A hipotenusa é o lado oposto ao ângulo reto.', true, ['Onde fica o ângulo de 90°?', 'O lado à frente dele…', '…é a hipotenusa.'], 'Verdadeiro.'),
    mc(2, 'razoes', 'No triângulo 3-4-5, com θ oposto ao lado 3, quanto vale cos θ?', ['3/5', '4/5', '3/4', '5/4'], 1, ['Cosseno = adjacente ÷ hipotenusa.', 'Adjacente = 4.', 'Hipotenusa = 5.'], 'cos θ = 4/5.'),
    match(2, 'razoes', 'Ligue cada razão à sua definição.', [['sen θ', 'oposto ÷ hipotenusa'], ['cos θ', 'adjacente ÷ hipotenusa'], ['tg θ', 'oposto ÷ adjacente']], ['SOH.', 'CAH.', 'TOA.'], 'SOH-CAH-TOA.'),
    mc(2, 'problemas', 'A 20 m de um prédio, você vê o topo sob 45°. Qual a altura do prédio (desconsiderando sua altura)?', ['10 m', '20 m', '28 m', '40 m'], 1, ['Oposto = altura; adjacente = 20.', 'tg 45° = h/20.', 'tg 45° = 1.'], 'h = 20 m.'),
    mc(3, 'problemas', 'Um avião decola em ângulo de 30° e percorre 1.000 m em linha reta. Quanto subiu?', ['500 m', '866 m', '1.000 m', '577 m'], 0, ['Altura = oposto; 1.000 m = hipotenusa.', 'sen 30° = h/1.000.', 'h = 1.000 · 1/2.'], '500 m.'),
    order(2, 'problemas', 'Ordene os passos para resolver um problema com trigonometria.', ['Desenhar o triângulo retângulo', 'Marcar o ângulo e os lados conhecidos', 'Escolher seno, cosseno ou tangente', 'Montar a equação e resolver'], ['Comece pelo desenho.', 'Depois identifique os dados.', 'Escolha a razão e calcule.'], 'Desenhar → marcar → escolher razão → resolver.'),
    mc(3, 'notaveis', 'Qual a relação entre sen 30° e cos 60°?', ['São iguais', 'Um é o dobro do outro', 'Somam 1', 'São opostos'], 0, ['sen 30° = 1/2.', 'cos 60° = 1/2.', 'Complementares trocam seno e cosseno.'], 'sen 30° = cos 60° = 1/2.'),
  ],
  review: ['Hipotenusa: oposta ao 90° · oposto e adjacente dependem do ângulo', 'SOH-CAH-TOA', 'Notáveis: sen 30° = 1/2, sen 45° = √2/2, sen 60° = √3/2; tg 45° = 1', 'Altura e distância: desenhe e escolha a razão'],
  relatedQuestions: ['o que é seno cosseno e tangente', 'tabela de ângulos notáveis', 'como calcular altura com trigonometria'],
  equivalentQuestions: eqsPt(['trigonometria', 'seno cosseno e tangente', 'ângulos notáveis'], ['o que é soh cah toa', 'quanto vale seno de 30', 'quanto vale cosseno de 60', 'tangente de 45 graus', 'o que é cateto oposto', 'o que é cateto adjacente', 'como calcular a altura de um prédio', 'como usar seno para achar um lado', 'diferença entre pitágoras e trigonometria', 'razões trigonométricas no triângulo retângulo']),
  commonErrors: ['Trocar cateto oposto por adjacente.', 'Usar o ângulo reto como θ.', 'Confundir os valores da tabela de ângulos notáveis.'],
  sources: FONTES,
})

export const logaritmo = lesson({
  id: 'mat-logaritmo', subject: 'matematica', title: 'Logaritmos', levels: [...EM], grade: '1ª série',
  topic: 'Funções', subtopic: 'Definição, propriedades e aplicações',
  aliases: ['logaritmo', 'log', 'propriedades do logaritmo', 'log na base 10', 'logaritmo natural', 'funcao logaritmica', 'equacao exponencial', 'log de 1000'],
  summary: 'Entenda o logaritmo como o expoente procurado, use suas propriedades e resolva equações exponenciais.',
  intro: '2 elevado a quê dá 32? A pergunta “qual é o expoente?” tem nome: logaritmo.',
  objective: 'Calcular logaritmos pela definição, respeitar as condições de existência, aplicar as propriedades principais e resolver equações exponenciais simples.',
  prerequisites: ['mat-potenciacao-radiciacao', 'mat-funcao-2-grau'], next: ['mat-juros'],
  formulas: [
    formula('Definição', 'logₐ b = x ⇔ aˣ = b', [['a', 'base (a > 0 e a ≠ 1)'], ['b', 'logaritmando (b > 0)'], ['x', 'logaritmo']]),
    formula('Propriedades', 'log(m·n) = log m + log n · log(m/n) = log m − log n · log(mᵏ) = k · log m', [['m, n', 'números positivos'], ['k', 'expoente']]),
  ],
  skills: { definicao: 'Definição e cálculo', condicoes: 'Condições de existência e casos especiais', propriedades: 'Propriedades', aplicacoes: 'Equações exponenciais e aplicações' },
  blocks: [
    block('definicao', 'O expoente procurado',
      'O logaritmo de b na base a é o expoente x ao qual se eleva a para obter b: logₐ b = x ⇔ aˣ = b. Sem base escrita, entende-se base 10.',
      'log₂ 32 = 5 porque 2⁵ = 32 · log 1.000 = 3 porque 10³ = 1.000.',
      'Logaritmo responde: “elevo a base a quanto para dar esse número?”',
      'Numa colônia de bactérias que dobra a cada hora, log₂ 1.024 = 10 diz que ela chega a 1.024 em 10 horas.',
      '1. Leia a base e o número.\n2. Pergunte: base elevada a quanto dá o número?\n3. Esse expoente é o logaritmo.',
      'Logaritmo é para a potência o que a subtração é para a soma: a operação que “desfaz”.'),
    block('condicoes', 'Condições e casos especiais',
      'Para existir: o logaritmando é positivo (b > 0) e a base é positiva e diferente de 1 (a > 0, a ≠ 1). Casos especiais: logₐ 1 = 0, logₐ a = 1 e logₐ aᵏ = k.',
      'log₅ 1 = 0 (5⁰ = 1) · log₇ 7 = 1 · log₃ 3⁴ = 4 · log(−10) não existe.',
      'Número positivo, base positiva e diferente de 1.',
      'Não há expoente que faça 10 virar um número negativo — por isso log(−10) não existe.',
      '1. Confira o logaritmando > 0.\n2. Confira a base > 0 e ≠ 1.\n3. Use os casos especiais quando aparecerem.',
      'Base 1 não serve porque 1 elevado a qualquer coisa continua 1.'),
    block('propriedades', 'Propriedades',
      'Log do produto = soma dos logs; log do quociente = diferença dos logs; log da potência = expoente vezes o log. Elas transformam multiplicações em somas, e foi por isso que os logaritmos facilitaram cálculos por séculos.',
      'log 200 = log 2 + log 100 ≈ 0,301 + 2 = 2,301 · log 2⁵ = 5 · log 2.',
      'Produto vira soma; divisão vira subtração; expoente “desce” multiplicando.',
      'Com log 2 ≈ 0,301 e log 3 ≈ 0,477: log 6 = log 2 + log 3 ≈ 0,778.',
      '1. Veja se há produto, quociente ou potência.\n2. Aplique a propriedade.\n3. Use os valores conhecidos (log 2, log 3…).',
      'São as mesmas regras das potências de mesma base, “vistas do lado dos expoentes”.'),
    block('aplicacoes', 'Equações exponenciais e aplicações',
      'Quando a incógnita está no expoente (3ˣ = 81), igualamos as bases (3ˣ = 3⁴ → x = 4) ou aplicamos log dos dois lados. Logaritmos aparecem em escalas como pH, decibéis e na escala de terremotos, em crescimento populacional e em juros compostos.',
      '2ˣ = 64 → 2ˣ = 2⁶ → x = 6.',
      'Incógnita no expoente → deixe as bases iguais ou use log.',
      'Em quanto tempo um capital dobra a 10% ao ano? 1,1ᵗ = 2 → t = log 2 ÷ log 1,1 ≈ 7,3 anos.',
      '1. Tente escrever os dois lados na mesma base.\n2. Iguale os expoentes.\n3. Se não der, aplique log e isole x.',
      'Nas escalas logarítmicas, subir 1 ponto significa multiplicar por 10: pH 3 é 10 vezes mais ácido que pH 4.'),
  ],
  questions: [
    mc(1, 'definicao', 'Quanto vale log₂ 32?', ['4', '5', '16', '6'], 1, ['2 elevado a quanto dá 32?', '2⁵ = 32.', '5.'], 'log₂ 32 = 5.'),
    mc(1, 'definicao', 'Quanto vale log 1.000 (base 10)?', ['2', '3', '100', '4'], 1, ['10 elevado a quanto?', '10³ = 1.000.', '3.'], 'log 1.000 = 3.'),
    fill(1, 'condicoes', 'Quanto vale log₅ 1?', ['0'], ['5 elevado a quanto dá 1?', 'Todo número (≠0) elevado a 0 dá 1.', '0.'], 'log₅ 1 = 0.'),
    tf(1, 'condicoes', 'log(−10) existe nos números reais.', false, ['O logaritmando precisa ser…', '…positivo.', 'Nenhuma potência de 10 é negativa.'], 'Falso.'),
    mc(2, 'propriedades', 'Sendo log 2 ≈ 0,301 e log 3 ≈ 0,477, quanto vale log 6?', ['0,176', '0,778', '1,431', '0,144'], 1, ['6 = 2 · 3.', 'log do produto = soma.', '0,301 + 0,477.'], '≈ 0,778.'),
    match(2, 'propriedades', 'Ligue cada expressão à propriedade.', [['log(m · n)', 'log m + log n'], ['log(m ÷ n)', 'log m − log n'], ['log(mᵏ)', 'k · log m'], ['logₐ a', '1']], ['Produto → soma.', 'Quociente → diferença.', 'Potência → multiplica.'], 'Cada propriedade no seu lugar.'),
    mc(2, 'aplicacoes', 'Resolva 3ˣ = 81.', ['3', '4', '27', '9'], 1, ['Escreva 81 como potência de 3.', '81 = 3⁴.', 'x = 4.'], 'x = 4.'),
    order(2, 'definicao', 'Ordene do MENOR para o MAIOR.', ['log 1', 'log 10', 'log 100', 'log 10.000'], ['log 1 = 0.', 'log 10 = 1; log 100 = 2.', 'log 10.000 = 4.'], '0 < 1 < 2 < 4.'),
    mc(3, 'aplicacoes', 'Qual o valor de x em 2ˣ = 64?', ['5', '6', '8', '32'], 1, ['64 = 2⁶.', 'Bases iguais.', 'x = 6.'], 'x = 6.'),
    open(3, 'aplicacoes', 'Explique por que uma solução de pH 3 é 10 vezes mais ácida que uma de pH 4.', 'O pH é uma escala logarítmica de base 10: cada unidade corresponde a multiplicar (ou dividir) a concentração por 10. Descer de pH 4 para pH 3 significa concentração 10 vezes maior, logo 10 vezes mais ácida.', ['logaritmica', 'base 10', '10 vezes', 'multiplicar', 'concentracao', 'escala'], ['Que tipo de escala é o pH?', 'Qual é a base?', 'O que significa 1 unidade a menos?'], 'Escala logarítmica: 1 unidade = fator 10.'),
  ],
  review: ['logₐ b = x ⇔ aˣ = b (base 10 quando não escrita)', 'b > 0, a > 0, a ≠ 1 · logₐ1 = 0, logₐa = 1', 'Produto → soma · quociente → diferença · potência → k · log', 'Exponenciais: iguale as bases ou aplique log'],
  relatedQuestions: ['o que é logaritmo', 'propriedades do logaritmo', 'como resolver equação exponencial'],
  equivalentQuestions: eqsPt(['logaritmo', 'log', 'equação exponencial'], ['como calcular logaritmo', 'quanto é log de 100', 'log na base 2', 'por que log de 1 é zero', 'condição de existência do logaritmo', 'log do produto', 'log de uma potência', 'como resolver 2 elevado a x igual a 64', 'para que serve logaritmo', 'escala logarítmica pH']),
  commonErrors: ['Confundir log(m + n) com log m + log n (não existe essa regra).', 'Usar base 1 ou logaritmando negativo.', 'Esquecer que sem base escrita a base é 10.'],
  sources: FONTES,
})

export const combinatoria = lesson({
  id: 'mat-analise-combinatoria', subject: 'matematica', title: 'Análise combinatória', levels: [...EM], grade: '2ª série',
  topic: 'Contagem', subtopic: 'Princípio fundamental, fatorial, permutação, arranjo e combinação',
  aliases: ['analise combinatoria', 'principio fundamental da contagem', 'fatorial', 'permutacao', 'arranjo', 'combinacao', 'arranjo ou combinacao', 'quantas maneiras', 'anagramas'],
  summary: 'Conte possibilidades sem listar todas: princípio multiplicativo, fatorial, permutação, arranjo e combinação.',
  intro: 'Quantas senhas de 4 dígitos existem? Quantos times dá para montar? Contar sem listar é o poder da combinatória.',
  objective: 'Aplicar o princípio fundamental da contagem, calcular fatoriais e permutações e diferenciar arranjo (a ordem importa) de combinação (a ordem não importa).',
  prerequisites: ['mat-probabilidade', 'mat-multiplicacao'], next: [],
  formulas: [
    formula('Fatorial', 'n! = n · (n − 1) · … · 2 · 1', [['n', 'número natural'], ['0!', 'vale 1']]),
    formula('Arranjo', 'A(n, p) = n! ÷ (n − p)!', [['n', 'total de elementos'], ['p', 'quantos são escolhidos (a ordem importa)']]),
    formula('Combinação', 'C(n, p) = n! ÷ [p! · (n − p)!]', [['n', 'total'], ['p', 'escolhidos (a ordem NÃO importa)']]),
  ],
  skills: { pfc: 'Princípio fundamental da contagem', permutacao: 'Fatorial e permutação', arranjo: 'Arranjo (ordem importa)', combinacao: 'Combinação (ordem não importa)' },
  blocks: [
    block('pfc', 'Princípio fundamental da contagem',
      'Se uma decisão tem m opções e, para cada uma, outra decisão tem n opções, há m · n maneiras de tomar as duas. Vale para qualquer número de etapas: multiplique as possibilidades de cada etapa.',
      '3 camisetas e 4 calças: 3 · 4 = 12 combinações de roupa.',
      'Etapas em sequência → multiplique as opções.',
      'Senha de 4 dígitos (0 a 9, pode repetir): 10 · 10 · 10 · 10 = 10.000 senhas.',
      '1. Divida o problema em etapas.\n2. Conte as opções de cada etapa.\n3. Multiplique.',
      'É como uma “árvore de possibilidades”: cada galho se divide de novo; o número de pontas é o produto.'),
    block('permutacao', 'Fatorial e permutação',
      'n! (lê-se “n fatorial”) é o produto de n até 1; por definição, 0! = 1. Permutação é o número de maneiras de ordenar n elementos distintos: Pₙ = n!. Anagramas de uma palavra com letras distintas são permutações.',
      '4! = 4 · 3 · 2 · 1 = 24 · anagramas de AMOR: 4! = 24.',
      'Ordenar n coisas = n!.',
      '5 amigos em fila para uma foto: 5! = 120 maneiras.',
      '1. Conte os elementos a ordenar.\n2. Calcule n! (multiplique até 1).',
      'Permutação é um caso do princípio fundamental: n opções para o 1º lugar, n − 1 para o 2º, e assim por diante.'),
    block('arranjo', 'Arranjo: a ordem importa',
      'Arranjo é escolher p elementos de n quando a ORDEM importa (posições, cargos, pódio): A(n, p) = n! ÷ (n − p)!. Também dá para fazer pelo princípio multiplicativo.',
      'Pódio (1º, 2º, 3º) entre 8 corredores: 8 · 7 · 6 = 336.',
      'Posições diferentes → arranjo.',
      'Eleger presidente e vice numa turma de 30: 30 · 29 = 870 maneiras.',
      '1. A ordem muda o resultado? Então é arranjo.\n2. Multiplique n · (n − 1) · … (p fatores).',
      'Trocar a ordem gera um resultado NOVO no arranjo: (Ana presidente, Bia vice) ≠ (Bia presidente, Ana vice).'),
    block('combinacao', 'Combinação: a ordem não importa',
      'Combinação é escolher p de n quando a ordem NÃO importa (grupos, comissões, sorteios de números): C(n, p) = n! ÷ [p! · (n − p)!]. É o arranjo dividido por p!, que “desconta” as reordenações.',
      'Escolher 2 de 4 amigos para um trabalho: C(4, 2) = 6.',
      'Grupo sem cargos → combinação.',
      'Na Mega-Sena, apostar 6 números de 60: C(60, 6) = 50.063.860 combinações.',
      '1. A ordem muda o resultado? Não → combinação.\n2. Calcule o arranjo.\n3. Divida por p!.',
      'Teste rápido: troque dois escolhidos de lugar. Se nada muda (continua o mesmo grupo), é combinação.'),
  ],
  questions: [
    mc(1, 'pfc', '3 camisetas e 4 bermudas: quantos looks diferentes?', ['7', '12', '34', '43'], 1, ['Duas etapas.', 'Multiplique as opções.', '3 · 4.'], '12 looks.'),
    mc(1, 'permutacao', 'Quanto é 4!?', ['4', '10', '16', '24'], 3, ['4 · 3 · 2 · 1.', '12 · 2.', '24.'], '4! = 24.'),
    fill(1, 'permutacao', 'Quantos anagramas tem a palavra SOL?', ['6'], ['3 letras distintas.', '3!.', '3 · 2 · 1.'], '3! = 6.'),
    tf(1, 'combinacao', 'Escolher 3 pessoas para uma comissão (sem cargos) é um problema de combinação.', true, ['A ordem muda o grupo?', 'Não.', 'Então é combinação.'], 'Verdadeiro.'),
    mc(2, 'arranjo', 'De quantas maneiras 8 corredores podem ocupar o pódio (1º, 2º, 3º)?', ['24', '56', '336', '512'], 2, ['A ordem importa.', '8 · 7 · 6.', '336.'], '336.'),
    mc(2, 'combinacao', 'De quantas maneiras escolher 2 de 4 amigos para um trabalho?', ['4', '6', '8', '12'], 1, ['Ordem não importa.', 'Arranjo: 4 · 3 = 12.', 'Divida por 2!.'], 'C(4, 2) = 6.'),
    match(2, 'arranjo', 'Classifique cada situação.', [['Presidente e vice de um grêmio', 'arranjo'], ['Comissão de 3 alunos', 'combinação'], ['Ordenar 5 livros na estante', 'permutação'], ['Senha de 3 dígitos com repetição', 'princípio multiplicativo']], ['Cargos diferentes → ordem importa.', 'Grupo → ordem não importa.', 'Ordenar todos → permutação.'], 'arranjo · combinação · permutação · PFC.'),
    order(2, 'permutacao', 'Ordene do MENOR para o MAIOR.', ['0!', '2!', '3!', '4!', '5!'], ['0! = 1.', '2! = 2; 3! = 6.', '4! = 24; 5! = 120.'], '1 < 2 < 6 < 24 < 120.'),
    mc(3, 'pfc', 'Quantas placas com 3 letras (26 opções) seguidas de 4 algarismos (10 opções) existem, com repetição?', ['26³ · 10⁴', '26 · 3 · 10 · 4', '26! · 10!', '(26 + 10)⁷'], 0, ['7 etapas.', '3 letras: 26 · 26 · 26.', '4 algarismos: 10 · 10 · 10 · 10.'], '26³ · 10⁴ = 175.760.000.'),
    open(3, 'combinacao', 'Explique a diferença entre arranjo e combinação com um exemplo.', 'No arranjo a ordem importa: escolher presidente e vice entre 5 pessoas dá 5 · 4 = 20 possibilidades, porque trocar os cargos gera outro resultado. Na combinação a ordem não importa: escolher 2 pessoas para um grupo dá 20 ÷ 2 = 10, porque trocar as duas de lugar continua sendo o mesmo grupo.', ['ordem', 'importa', 'arranjo', 'combinacao', 'grupo', 'cargo', 'dividir'], ['Pense em cargos x grupos.', 'Troque dois escolhidos de lugar.', 'Mostre com números.'], 'Arranjo: ordem importa · combinação: não importa (divide por p!).'),
  ],
  review: ['Princípio fundamental: multiplique as opções de cada etapa', 'n! = n · (n−1) · … · 1 · 0! = 1 · permutação = n!', 'Arranjo (ordem importa): n!/(n−p)!', 'Combinação (ordem não importa): n!/[p!(n−p)!]'],
  relatedQuestions: ['diferença entre arranjo e combinação', 'como calcular fatorial', 'princípio fundamental da contagem'],
  equivalentQuestions: eqsPt(['análise combinatória', 'arranjo e combinação', 'permutação'], ['quantas senhas de 4 dígitos existem', 'como calcular anagramas', 'o que é fatorial', 'por que 0 fatorial é 1', 'quando usar arranjo', 'quando usar combinação', 'quantas maneiras de formar um time', 'pódio com 8 corredores', 'chance de ganhar na mega sena', 'princípio multiplicativo']),
  commonErrors: ['Usar arranjo quando a ordem não importa.', 'Somar as opções das etapas em vez de multiplicar.', 'Esquecer que 0! = 1.'],
  sources: FONTES, enem: 'Contagem e combinatória aparecem em placas, senhas, cardápios e probabilidade.',
})

export const geometriaEspacial = lesson({
  id: 'mat-geometria-espacial', subject: 'matematica', title: 'Geometria espacial: volumes', levels: ['fund2', 'medio'], grade: '9º ano e 2ª série',
  topic: 'Geometria', subtopic: 'Prismas, cilindros, pirâmides, cones e esferas',
  aliases: ['geometria espacial', 'volume', 'volume do cubo', 'volume do cilindro', 'volume do cone', 'volume da piramide', 'volume da esfera', 'prisma', 'metro cubico litro'],
  summary: 'Calcule volumes de prismas, cilindros, pirâmides, cones e esferas e converta entre m³ e litros.',
  intro: 'Quantos litros cabem numa caixa-d’água? Quanta massa de bolo vai na forma? Volume responde.',
  objective: 'Reconhecer os principais sólidos e calcular seus volumes, relacionando cm³, dm³, m³ e litros.',
  prerequisites: ['mat-area-perimetro', 'mat-trigonometria-triangulo'], next: [],
  formulas: [
    formula('Prisma e cilindro', 'V = área da base · altura (cilindro: V = π · r² · h)', [['r', 'raio da base'], ['h', 'altura']]),
    formula('Pirâmide e cone', 'V = (área da base · altura) ÷ 3 (cone: V = π · r² · h ÷ 3)', [['h', 'altura']]),
    formula('Esfera', 'V = (4 · π · r³) ÷ 3', [['r', 'raio']]),
  ],
  skills: { solidos: 'Sólidos e unidades de volume', prismas: 'Prismas e cilindros', piramides: 'Pirâmides e cones', esfera: 'Esfera e aplicações' },
  blocks: [
    block('solidos', 'Sólidos e unidades',
      'Volume é o espaço que um sólido ocupa, medido em unidades cúbicas: cm³, dm³, m³. Relações importantes: 1 dm³ = 1 litro e 1 m³ = 1.000 litros; 1 cm³ = 1 mL.',
      'Uma caixa de 1 m × 1 m × 1 m tem 1 m³ = 1.000 L.',
      'Volume = quantos cubinhos cabem dentro.',
      'Uma caixa-d’água de 2 m³ guarda 2.000 litros.',
      '1. Deixe todas as medidas na mesma unidade.\n2. Calcule o volume.\n3. Converta para litros se preciso (1 m³ = 1.000 L).',
      'Perímetro é linha (m), área é superfície (m²), volume é espaço (m³): cada dimensão a mais soma um expoente.'),
    block('prismas', 'Prismas e cilindros',
      'Prismas e cilindros têm duas bases iguais e paralelas. Volume = área da base · altura. Paralelepípedo: V = comprimento · largura · altura; cubo: V = a³; cilindro: V = π · r² · h.',
      'Caixa 30 cm × 20 cm × 10 cm: 6.000 cm³ = 6 L. Cilindro de r = 1 m e h = 2 m: V ≈ 3,14 · 1 · 2 = 6,28 m³.',
      'Área da base vezes a altura.',
      'Uma lata de refrigerante é um cilindro: base circular × altura.',
      '1. Calcule a área da base.\n2. Multiplique pela altura.\n3. Use a unidade cúbica.',
      'Um cilindro é como uma pilha de moedas iguais: área de uma moeda × altura da pilha.'),
    block('piramides', 'Pirâmides e cones',
      'Pirâmides e cones terminam em ponta (vértice). Seu volume é um terço do prisma (ou cilindro) de mesma base e altura: V = (área da base · h) ÷ 3.',
      'Cone de raio 3 cm e altura 10 cm: V ≈ 3,14 · 9 · 10 ÷ 3 = 94,2 cm³.',
      'Tem ponta? Divide por 3.',
      'Três casquinhas de sorvete cheias (cones) enchem exatamente um copo cilíndrico de mesma base e altura.',
      '1. Calcule a área da base.\n2. Multiplique pela altura.\n3. Divida por 3.',
      'Cone = cilindro ÷ 3; pirâmide = prisma ÷ 3.'),
    block('esfera', 'Esfera',
      'A esfera tem todos os pontos da superfície à mesma distância do centro (o raio). Volume: V = 4πr³ ÷ 3. Como o raio está ao cubo, dobrar o raio multiplica o volume por 8.',
      'Bola de raio 10 cm: V ≈ 4 · 3,14 · 1.000 ÷ 3 ≈ 4.186,7 cm³ ≈ 4,19 L.',
      'Volume da esfera = 4 · π · raio³ ÷ 3.',
      'Uma bola de basquete tem raio de cerca de 12 cm: cabem uns 7 litros de ar nela.',
      '1. Ache o raio.\n2. Eleve ao cubo.\n3. Multiplique por 4π e divida por 3.',
      'Área cresce com r² e volume com r³: por isso bolhas pequenas ficam “mais superfície” proporcionalmente.'),
  ],
  questions: [
    mc(1, 'solidos', 'Quantos litros cabem em 1 m³?', ['10', '100', '1.000', '10.000'], 2, ['1 dm³ = 1 L.', '1 m³ = 1.000 dm³.', '1.000 L.'], '1.000 L.'),
    mc(1, 'prismas', 'Qual o volume de um cubo de aresta 3 cm?', ['9 cm³', '12 cm³', '27 cm³', '18 cm³'], 2, ['V = a³.', '3 · 3 · 3.', '27.'], '27 cm³.'),
    fill(1, 'prismas', 'Volume de uma caixa de 30 cm × 20 cm × 10 cm, em litros (só o número).', ['6'], ['30 · 20 · 10 = 6.000 cm³.', '1.000 cm³ = 1 L.', '6.000 ÷ 1.000.'], '6 L.'),
    tf(1, 'piramides', 'O volume de um cone é um terço do volume do cilindro de mesma base e altura.', true, ['Sólidos com ponta dividem por 3.', 'Cone vem do cilindro.', 'Sim.'], 'Verdadeiro.'),
    match(2, 'solidos', 'Ligue cada sólido à fórmula do volume.', [['cilindro', 'π · r² · h'], ['cone', 'π · r² · h ÷ 3'], ['esfera', '4 · π · r³ ÷ 3'], ['cubo', 'a³']], ['Com ponta: ÷ 3.', 'Esfera usa r³.', 'Cubo: aresta ao cubo.'], 'Cada sólido com sua fórmula.'),
    mc(2, 'prismas', 'Um cilindro tem raio 1 m e altura 2 m. Qual o volume aproximado? (π ≈ 3,14)', ['3,14 m³', '6,28 m³', '12,56 m³', '2 m³'], 1, ['V = π · r² · h.', 'r² = 1.', '3,14 · 2.'], '≈ 6,28 m³.'),
    mc(2, 'piramides', 'Uma pirâmide tem base de 12 m² e altura 5 m. Qual o volume?', ['60 m³', '20 m³', '30 m³', '17 m³'], 1, ['V = base · h ÷ 3.', '12 · 5 = 60.', '60 ÷ 3.'], '20 m³.'),
    mc(3, 'esfera', 'Se o raio de uma esfera dobra, o volume fica:', ['2 vezes maior', '4 vezes maior', '8 vezes maior', 'igual'], 2, ['V depende de r³.', '(2r)³ = 8r³.', '8 vezes.'], '8 vezes maior.'),
    order(2, 'solidos', 'Ordene as unidades da MENOR para a MAIOR.', ['1 cm³', '1 dm³', '1 m³', '1.000 m³'], ['1 cm³ = 1 mL.', '1 dm³ = 1 L.', '1 m³ = 1.000 L.'], 'cm³ < dm³ < m³ < 1.000 m³.'),
    mc(3, 'prismas', 'Uma piscina de 10 m × 5 m × 2 m está cheia. Quantos litros de água tem?', ['100 L', '10.000 L', '100.000 L', '1.000.000 L'], 2, ['V = 10 · 5 · 2 = 100 m³.', '1 m³ = 1.000 L.', '100 · 1.000.'], '100.000 L.'),
  ],
  review: ['Volume em unidades cúbicas · 1 dm³ = 1 L · 1 m³ = 1.000 L', 'Prisma/cilindro: área da base · altura', 'Pirâmide/cone: (base · altura) ÷ 3', 'Esfera: 4πr³ ÷ 3 (dobrar r → volume × 8)'],
  relatedQuestions: ['como calcular volume', 'volume do cilindro', 'quantos litros tem um metro cúbico'],
  equivalentQuestions: eqsPt(['volume', 'geometria espacial', 'volume do cilindro'], ['como calcular volume de uma caixa', 'fórmula do volume do cone', 'volume da pirâmide', 'volume da esfera', 'quantos litros cabem na caixa d água', 'metro cúbico em litros', 'volume do cubo', 'volume de uma piscina', 'diferença entre área e volume', 'por que o cone divide por 3']),
  commonErrors: ['Esquecer de dividir por 3 em pirâmides e cones.', 'Misturar unidades (cm com m).', 'Usar o diâmetro no lugar do raio.'],
  sources: FONTES,
})

export const juros = lesson({
  id: 'mat-juros', subject: 'matematica', title: 'Juros simples e compostos', levels: ['fund2', 'medio'], grade: '9º ano e Ensino Médio',
  topic: 'Matemática financeira', subtopic: 'Juros simples, compostos e decisões financeiras',
  aliases: ['juros simples', 'juros compostos', 'montante', 'capital', 'taxa de juros', 'matematica financeira', 'juros sobre juros', 'rendimento', 'emprestimo juros'],
  summary: 'Calcule juros simples e compostos, entenda o efeito “juros sobre juros” e use isso para decidir melhor sobre dinheiro.',
  intro: 'Poupar, investir, parcelar, pegar empréstimo… Entender juros protege o seu dinheiro.',
  objective: 'Calcular juros e montante nos regimes simples e composto, comparar os dois e interpretar situações reais de empréstimos, parcelamentos e investimentos.',
  prerequisites: ['mat-porcentagem', 'mat-progressoes'], next: [],
  formulas: [
    formula('Juros simples', 'J = C · i · t · M = C + J', [['C', 'capital (valor inicial)'], ['i', 'taxa por período (em decimal)'], ['t', 'tempo (mesma unidade da taxa)'], ['M', 'montante']]),
    formula('Juros compostos', 'M = C · (1 + i)ᵗ', [['C', 'capital'], ['i', 'taxa por período (decimal)'], ['t', 'número de períodos']]),
  ],
  skills: { conceito: 'Capital, taxa, tempo e montante', simples: 'Juros simples', compostos: 'Juros compostos', decisoes: 'Comparar e decidir' },
  blocks: [
    block('conceito', 'O vocabulário dos juros',
      'Capital (C) é o valor inicial; taxa (i) é a porcentagem cobrada ou paga por período; tempo (t) é a quantidade de períodos; juros (J) são o valor a mais; montante (M) é o total final (capital + juros). Taxa e tempo precisam estar na mesma unidade (mês com mês, ano com ano).',
      'Emprestar R$ 1.000 a 2% ao mês por 3 meses: C = 1.000, i = 0,02, t = 3.',
      'Juros = o “aluguel” do dinheiro.',
      'Quem pega emprestado paga juros; quem investe recebe juros.',
      '1. Identifique C, i e t.\n2. Converta a taxa para decimal (2% = 0,02).\n3. Confira se taxa e tempo estão na mesma unidade.',
      'Juros funcionam como aluguel: você usa algo que não é seu (o dinheiro) e paga pelo tempo de uso.'),
    block('simples', 'Juros simples',
      'Nos juros simples, a taxa incide sempre sobre o capital inicial: os juros de cada período são iguais. J = C · i · t e M = C + J. O montante cresce como uma PA.',
      'C = 1.000, i = 2% a.m., t = 3: J = 1.000 · 0,02 · 3 = 60 → M = 1.060.',
      'Juros simples: o mesmo valor de juros todo mês.',
      'Uma dívida de R$ 500 a 3% ao mês simples gera R$ 15 de juros por mês.',
      '1. Multiplique C · i · t.\n2. Some ao capital para ter o montante.',
      'É como uma mesada fixa: todo mês cai a mesma quantia.'),
    block('compostos', 'Juros compostos',
      'Nos juros compostos, os juros de cada período entram no capital e passam a render juros também (“juros sobre juros”). M = C · (1 + i)ᵗ. O montante cresce como uma PG. É o regime usado em investimentos, cartões de crédito e financiamentos.',
      'C = 1.000, i = 10% a.a., t = 2: M = 1.000 · 1,1² = 1.210 (no simples seriam 1.200).',
      'Juros compostos: os juros também rendem juros.',
      'Deixar R$ 100 rendendo 1% ao mês por 12 meses: 100 · 1,01¹² ≈ R$ 112,68.',
      '1. Some 1 à taxa: (1 + i).\n2. Eleve ao número de períodos.\n3. Multiplique pelo capital.',
      'Uma bola de neve rolando: quanto maior fica, mais neve junta a cada volta.'),
    block('decisoes', 'Comparar e decidir',
      'No curto prazo, simples e compostos dão valores parecidos; no longo prazo, os compostos crescem muito mais. Isso é ótimo para quem investe cedo e perigoso para quem deixa dívidas (como o rotativo do cartão) acumularem. Em compras, compare o preço à vista com o total parcelado.',
      'R$ 1.000 a 10% a.a. por 10 anos: simples → R$ 2.000; compostos → ≈ R$ 2.594.',
      'Tempo longo + juros compostos = diferença enorme.',
      'Uma dívida de cartão a 15% ao mês dobra em cerca de 5 meses.',
      '1. Descubra o regime (simples ou composto).\n2. Calcule o total em cada opção.\n3. Compare com o preço à vista.\n4. Evite juros altos por muito tempo.',
      'A mesma matemática que faz um investimento crescer faz uma dívida esquecida explodir.'),
  ],
  questions: [
    mc(1, 'conceito', 'Montante é:', ['só os juros', 'o capital mais os juros', 'a taxa', 'o tempo'], 1, ['É o total final.', 'M = C + J.', 'Capital + juros.'], 'M = C + J.'),
    mc(1, 'simples', 'Juros simples de R$ 1.000 a 2% ao mês por 3 meses:', ['R$ 20', 'R$ 60', 'R$ 600', 'R$ 1.060'], 1, ['J = C · i · t.', '1.000 · 0,02 · 3.', '60.'], 'R$ 60.'),
    fill(1, 'conceito', 'Escreva 5% em decimal.', ['0,05', '0.05'], ['Divida por 100.', '5 ÷ 100.', '0,05.'], '0,05.'),
    tf(1, 'compostos', 'Nos juros compostos, os juros de um período passam a render juros no período seguinte.', true, ['“Juros sobre juros”.', 'Os juros entram no capital.', 'Sim.'], 'Verdadeiro.'),
    mc(2, 'compostos', 'R$ 1.000 a 10% ao ano, juros compostos, por 2 anos. Montante?', ['R$ 1.200', 'R$ 1.210', 'R$ 1.100', 'R$ 2.000'], 1, ['M = C · (1 + i)ᵗ.', '1.000 · 1,1².', '1,1² = 1,21.'], 'R$ 1.210.'),
    match(2, 'decisoes', 'Ligue cada regime às características.', [['juros simples', 'juros iguais em todo período'], ['juros compostos', 'juros sobre juros'], ['montante simples', 'cresce como PA'], ['montante composto', 'cresce como PG']], ['Simples: mesma parcela.', 'Compostos: acumulam.', 'PA soma, PG multiplica.'], 'simples ~ PA · compostos ~ PG.'),
    mc(2, 'simples', 'Uma dívida de R$ 500 a 3% ao mês (simples). Quanto de juros em 4 meses?', ['R$ 15', 'R$ 60', 'R$ 120', 'R$ 560'], 1, ['J = 500 · 0,03 · 4.', '15 por mês.', '15 · 4.'], 'R$ 60.'),
    order(2, 'compostos', 'Ordene os passos para calcular juros compostos.', ['Converter a taxa para decimal', 'Calcular (1 + i)', 'Elevar ao número de períodos', 'Multiplicar pelo capital'], ['Primeiro a taxa.', 'Depois 1 + i e a potência.', 'Por fim × C.'], 'decimal → (1+i) → potência → × C.'),
    mc(3, 'decisoes', 'Uma TV custa R$ 1.000 à vista ou 10 × R$ 120. Quanto se paga a mais no parcelado?', ['R$ 20', 'R$ 120', 'R$ 200', 'R$ 1.200'], 2, ['Total parcelado: 10 · 120.', '= 1.200.', '1.200 − 1.000.'], 'R$ 200 a mais (20%).'),
    open(3, 'decisoes', 'Por que é arriscado deixar uma dívida de cartão de crédito rolando por muitos meses?', 'Porque o cartão cobra juros compostos com taxas altas: os juros de cada mês entram na dívida e também passam a gerar juros. Com o tempo, a dívida cresce como uma PG e pode dobrar em poucos meses.', ['juros compostos', 'juros sobre juros', 'taxa', 'alta', 'cresce', 'dobra', 'tempo'], ['Qual regime o cartão usa?', 'O que acontece com os juros não pagos?', 'Fale do crescimento com o tempo.'], 'Juros compostos altos fazem a dívida crescer muito rápido.'),
  ],
  review: ['C capital · i taxa (decimal) · t tempo · J juros · M = C + J', 'Simples: J = C · i · t (PA)', 'Compostos: M = C · (1 + i)ᵗ (PG)', 'Longo prazo: compostos crescem muito mais — ótimo para investir, perigoso em dívidas'],
  relatedQuestions: ['como calcular juros simples', 'como calcular juros compostos', 'diferença entre juros simples e compostos'],
  equivalentQuestions: eqsPt(['juros simples', 'juros compostos', 'matemática financeira'], ['fórmula dos juros simples', 'fórmula dos juros compostos', 'o que é montante', 'o que é capital nos juros', 'quanto rende 1000 reais', 'vale a pena parcelar', 'juros do cartão de crédito', 'como calcular rendimento da poupança', 'juros sobre juros', 'taxa de juros ao mês']),
  commonErrors: ['Usar a taxa em porcentagem sem converter (2 em vez de 0,02).', 'Misturar taxa anual com tempo em meses.', 'Aplicar a fórmula de juros simples em situações de juros compostos.'],
  sources: FONTES, enem: 'Juros, parcelamentos e comparação de propostas são temas recorrentes.',
})
