import type { Lesson } from '../../types'

const BNCC = { title: 'Base Nacional Comum Curricular (BNCC) — Matemática', url: 'http://basenacionalcomum.mec.gov.br/', kind: 'curriculo' } as const

export const fracoes: Lesson = {
  id: 'mat-fracoes',
  subject: 'matematica',
  title: 'Frações',
  levels: ['fund1', 'fund2'],
  grade: '4º ao 6º ano',
  aliases: ['fracao', 'fracoes', 'numerador', 'denominador', 'fracoes equivalentes', 'simplificar fracao', 'simplificacao de fracoes'],
  summary: 'Entenda o que é uma fração, como ler, encontrar frações equivalentes e simplificar.',
  intro: 'Vamos entender juntos. Fração é um jeito de mostrar pedaços de alguma coisa — de uma pizza, de uma barra de chocolate ou de um grupo de pessoas.',
  skills: { conceito: 'Conceito de fração', leitura: 'Leitura de frações', equivalentes: 'Frações equivalentes', simplificacao: 'Simplificação de frações' },
  blocks: [
    {
      id: 'b1', skill: 'conceito', title: 'O que é uma fração',
      text: 'A fração representa uma parte de um todo. O número de cima (numerador) indica quantas partes você está pegando. O número de baixo (denominador) indica em quantas partes iguais o todo foi dividido.',
      example: 'Uma pizza cortada em 8 pedaços iguais. Se você come 3, comeu 3/8 da pizza: 3 é o numerador e 8 é o denominador.',
      variants: {
        simples: 'Pense numa pizza. O número de baixo diz em quantos pedaços ela foi cortada. O número de cima diz quantos pedaços você pegou. Só isso!',
        exemplo: 'Uma barra de chocolate tem 4 quadradinhos iguais. Você deu 1 para seu amigo. Seu amigo ganhou 1/4 da barra: 1 pedaço de 4.',
        outra: 'Fração é uma divisão escrita de um jeito especial. 3/8 quer dizer "dividi em 8 partes iguais e fiquei com 3 delas". O traço do meio é como um "de": 3 de 8.',
        detalhado: 'Numa fração a/b, o denominador b (que nunca pode ser zero) diz em quantas partes IGUAIS o inteiro foi dividido — as partes precisam ter o mesmo tamanho. O numerador a conta quantas dessas partes estamos considerando. Se a = b, temos o inteiro (8/8 = 1). Se a > b, temos mais de um inteiro, como 9/8.',
      },
    },
    {
      id: 'b2', skill: 'leitura', title: 'Como ler uma fração',
      text: 'Lemos primeiro o numerador e depois o denominador com um nome especial: 2 = meio, 3 = terço, 4 = quarto, 5 = quinto… até 9 = nono, e 10 = décimo. Acima de 10, usamos a palavra "avos".',
      example: '1/2 = um meio · 2/3 = dois terços · 3/10 = três décimos · 5/12 = cinco doze avos.',
      variants: {
        simples: '1/2 é "um meio" (metade). 1/3 é "um terço". 1/4 é "um quarto". Quando o número de baixo passa de 10, falamos "avos": 1/12 é "um doze avos".',
        exemplo: 'Se um bolo foi cortado em 12 fatias e você comeu 5, você comeu "cinco doze avos" do bolo. Se foi cortado em 4 e você comeu 3, comeu "três quartos".',
        outra: 'O denominador vira um nome parecido com os números de ordem: quinto, sexto, sétimo, oitavo, nono, décimo. Exceções: 2 é "meio" e 3 é "terço". Depois do 10, é o número + "avos".',
        detalhado: 'Denominadores 100 e 1000 também têm nomes próprios: centésimo (1/100) e milésimo (1/1000). Por isso 25/100 se lê "vinte e cinco centésimos". Nos demais casos acima de 10 usamos "avos": 7/15 = sete quinze avos.',
      },
    },
    {
      id: 'b3', skill: 'equivalentes', title: 'Frações equivalentes',
      text: 'Frações equivalentes representam a mesma quantidade, mesmo com números diferentes. Para encontrar uma, multiplique (ou divida) o numerador e o denominador pelo mesmo número.',
      example: '1/2 = 2/4 = 4/8. Metade da pizza é sempre metade, esteja ela cortada em 2, 4 ou 8 pedaços.',
      variants: {
        simples: 'Metade de uma pizza é igual a 2 pedaços de 4, ou 4 pedaços de 8. Muda o número de pedaços, mas a quantidade de pizza é a mesma.',
        exemplo: 'Você tem 1/3 de uma barra. Se cortar cada pedaço ao meio, agora são 6 pedaços no total e você tem 2: 2/6. Continua sendo a mesma quantidade de chocolate.',
        outra: 'Multiplicar em cima e embaixo pelo mesmo número é como "cortar os pedaços em pedaços menores": aumenta a quantidade de pedaços, mas não a quantidade de pizza.',
        detalhado: 'a/b e c/d são equivalentes quando a·d = b·c (produto cruzado). Exemplo: 2/3 e 4/6 → 2·6 = 12 e 3·4 = 12, então são equivalentes. Isso funciona porque multiplicar numerador e denominador pelo mesmo número é o mesmo que multiplicar a fração por 1 (n/n = 1).',
      },
    },
    {
      id: 'b4', skill: 'simplificacao', title: 'Simplificar frações',
      text: 'Simplificar é escrever a fração com os menores números possíveis. Divida o numerador e o denominador pelo mesmo número até não ser mais possível. A fração final é chamada de irredutível.',
      example: '6/8 → dividindo os dois por 2 → 3/4. Como 3 e 4 não têm outro divisor comum, 3/4 é irredutível.',
      variants: {
        simples: 'Procure um número que divide o de cima e o de baixo ao mesmo tempo. Divida os dois. Repita até não dar mais.',
        exemplo: '12/18: os dois são pares, divide por 2 → 6/9. Os dois estão na tabuada do 3, divide por 3 → 2/3. Pronto: 2/3.',
        outra: 'Simplificar é o caminho contrário das equivalentes: em vez de cortar os pedaços em partes menores, você junta pedaços até ficarem do maior tamanho possível.',
        detalhado: 'O jeito mais rápido é dividir numerador e denominador pelo máximo divisor comum (MDC). MDC(12, 18) = 6, então 12/18 = (12÷6)/(18÷6) = 2/3 em um passo só. Uma fração é irredutível quando o MDC entre numerador e denominador é 1.',
      },
    },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'conceito', prompt: 'Se João comeu 3 de 8 pedaços de uma pizza, qual fração representa o que ele comeu?', options: ['3/5', '3/8', '5/8', '8/3'], answer: 1, hints: ['Quantos pedaços a pizza tinha no total?', 'O número de baixo é o total de pedaços; o de cima é quantos ele comeu.', 'Total = 8 (embaixo). Comeu = 3 (em cima).'], explanation: 'A pizza tinha 8 pedaços (denominador) e João comeu 3 (numerador): 3/8.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'conceito', prompt: 'Na fração 2/5, qual é o denominador?', options: ['2', '5', '7', '10'], answer: 1, hints: ['Denominador fica em uma posição específica da fração.', 'O denominador é o número de baixo: em quantas partes o todo foi dividido.', 'Olhe o número abaixo do traço.'], explanation: 'O denominador é o número de baixo, 5: o todo foi dividido em 5 partes iguais.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'leitura', prompt: 'A fração 1/4 se lê "um quarto".', answer: true, hints: ['Pense no nome especial do denominador 4.', '2 = meio, 3 = terço, 4 = …', '4 é "quarto", como em "um quarto de hora".'], explanation: 'Verdadeiro. O denominador 4 se lê "quarto": 1/4 = um quarto.' },
    { id: 'q4', type: 'mc', difficulty: 1, skill: 'leitura', prompt: 'Como se lê a fração 3/10?', options: ['Três dez avos', 'Três décimos', 'Três dezenas', 'Dez terços'], answer: 1, hints: ['O 10 tem um nome especial.', 'Até o 10, os denominadores têm nomes próprios.', '10 no denominador = décimo.'], explanation: 'Quando o denominador é 10, usamos "décimo(s)": três décimos.' },
    { id: 'q5', type: 'fill', difficulty: 2, skill: 'leitura', prompt: 'Complete: 5/12 se lê "cinco doze ____".', answers: ['avos'], hints: ['12 é maior que 10.', 'Acima de 10, os denominadores não têm nome especial.', 'Usamos a palavra que começa com "a" e termina com "s".'], explanation: 'Acima de 10 usamos "avos": cinco doze avos.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'equivalentes', prompt: 'Qual destas frações é equivalente a 1/2?', options: ['2/3', '4/8', '3/5', '1/4'], answer: 1, hints: ['Procure a fração que também representa "metade".', 'Multiplique o 1 e o 2 pelo mesmo número.', '1×4 = 4 e 2×4 = 8.'], explanation: '4/8 é metade de 8, igual a 1/2. Multiplicamos em cima e embaixo por 4.' },
    { id: 'q7', type: 'tf', difficulty: 2, skill: 'equivalentes', prompt: 'As frações 2/3 e 4/6 são equivalentes.', answer: true, hints: ['Compare como 2 virou 4 e como 3 virou 6.', 'Se os dois foram multiplicados pelo mesmo número, são equivalentes.', '2×2 = 4 e 3×2 = 6.'], explanation: 'Verdadeiro. Numerador e denominador de 2/3 foram multiplicados por 2, gerando 4/6.' },
    { id: 'q8', type: 'fill', difficulty: 2, skill: 'simplificacao', prompt: 'Simplifique a fração 6/8. (Escreva no formato a/b)', answers: ['3/4'], hints: ['6 e 8 são números pares.', 'Divida numerador e denominador pelo mesmo número.', '6÷2 = 3 e 8÷2 = 4.'], explanation: 'Dividindo os dois por 2: 6/8 = 3/4, que já é irredutível.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'simplificacao', prompt: 'Qual é a forma irredutível de 12/18?', options: ['6/9', '4/6', '2/3', '3/2'], answer: 2, hints: ['Irredutível = não dá mais para simplificar.', '6/9 e 4/6 ainda podem ser simplificadas.', 'Divida 12 e 18 por 6.'], explanation: 'O maior divisor comum de 12 e 18 é 6. 12÷6 = 2 e 18÷6 = 3, então 12/18 = 2/3.' },
    { id: 'q10', type: 'match', difficulty: 2, skill: 'leitura', prompt: 'Ligue cada fração ao seu nome.', pairs: [['1/2', 'Um meio'], ['1/3', 'Um terço'], ['1/4', 'Um quarto'], ['1/5', 'Um quinto']], hints: ['Comece pela mais conhecida: metade.', '2 = meio, 3 = terço.', '4 = quarto e 5 = quinto.'], explanation: '1/2 = um meio, 1/3 = um terço, 1/4 = um quarto, 1/5 = um quinto.' },
    { id: 'q11', type: 'mc', difficulty: 3, skill: 'equivalentes', prompt: 'Qual número deve ocupar o lugar do x em 3/5 = x/20?', options: ['8', '12', '15', '4'], answer: 1, hints: ['O que aconteceu com o denominador 5 para virar 20?', '5 foi multiplicado por 4.', 'Faça o mesmo com o numerador: 3 × 4.'], explanation: '5 × 4 = 20, então o numerador também é multiplicado por 4: 3 × 4 = 12.' },
    { id: 'q12', type: 'open', difficulty: 3, skill: 'equivalentes', prompt: 'Explique com suas palavras por que 2/4 e 1/2 representam a mesma quantidade.', modelAnswer: 'Porque 2/4 é a metade de 4 partes, e 1/2 também é metade. Se dividirmos o numerador e o denominador de 2/4 por 2, obtemos 1/2 — são frações equivalentes.', keywords: ['metade', 'mesma', 'equivalente', 'dividir', 'multiplicar', '2'], hints: ['Desenhe uma pizza cortada em 4 e outra em 2.', 'Pinte 2 pedaços de 4 e 1 pedaço de 2. O que você percebe?', 'Fale sobre "metade" ou sobre dividir em cima e embaixo por 2.'], explanation: 'As duas representam metade do todo. 2/4 simplificada (÷2) vira 1/2 — por isso são equivalentes.' },
  ],
  review: ['Numerador (em cima) = partes que pegamos', 'Denominador (embaixo) = em quantas partes iguais o todo foi dividido', 'Equivalentes: multiplique ou divida em cima e embaixo pelo mesmo número', 'Simplificar: divida até não dar mais (irredutível)'],
  sources: [BNCC, { title: 'Conteúdo autoral LUMI', kind: 'autoral' }],
}

export const porcentagem: Lesson = {
  id: 'mat-porcentagem',
  subject: 'matematica',
  title: 'Porcentagem',
  levels: ['fund2', 'medio'],
  grade: '6º e 7º ano',
  aliases: ['porcentagem', 'por cento', 'percentual', 'desconto', 'juros simples', 'aumento percentual'],
  summary: 'Aprenda o que significa "por cento", como calcular porcentagens, descontos e aumentos.',
  intro: 'Porcentagem está em todo lugar: promoções, bateria do celular, notas. Vamos descobrir como ela funciona.',
  skills: { conceito: 'O que é porcentagem', atalhos: 'Atalhos de cálculo', calculo: 'Calcular porcentagem de um valor', desconto: 'Descontos e aumentos' },
  blocks: [
    {
      id: 'b1', skill: 'conceito', title: 'O que é "por cento"',
      text: 'Porcentagem é uma fração com denominador 100. "25%" significa 25 de cada 100, ou seja, 25/100. O todo sempre vale 100%.',
      example: 'Se a bateria do celular está em 40%, sobrou 40 de 100 partes da carga total.',
      variants: {
        simples: 'Imagine algo dividido em 100 pedacinhos. 30% são 30 desses pedacinhos. 100% é tudo.',
        exemplo: 'Numa turma de 100 alunos, 60 gostam de futebol. Então 60% da turma gosta de futebol.',
        outra: 'O símbolo % é um jeito curto de escrever "dividido por 100". Então 7% = 7 ÷ 100 = 0,07.',
        detalhado: 'Porcentagem é uma razão centesimal. Toda porcentagem pode ser escrita como fração (15% = 15/100 = 3/20) ou como decimal (15% = 0,15). Valores acima de 100% indicam mais que o todo, como um aumento de 150%.',
      },
    },
    {
      id: 'b2', skill: 'atalhos', title: 'Atalhos que ajudam muito',
      text: '50% é a metade. 25% é um quarto (metade da metade). 10% é dividir por 10. A partir daí você monta outras: 20% = 2 × 10%, 5% = metade de 10%.',
      example: 'De R$ 80: 10% = R$ 8 · 5% = R$ 4 · 15% = R$ 8 + R$ 4 = R$ 12.',
      variants: {
        simples: 'Para achar 10%, tire o último zero ou divida por 10. Para 50%, pegue a metade.',
        exemplo: 'De 200 figurinhas: 50% = 100, 25% = 50, 10% = 20.',
        outra: 'Pense em "blocos de 10%". 30% são três blocos de 10%. Achou um bloco, é só somar.',
        detalhado: 'Os atalhos funcionam porque 10% = 1/10, 50% = 1/2, 25% = 1/4 e 20% = 1/5. Combinar porcentagens é somar as frações: 35% = 25% + 10% = 1/4 + 1/10.',
      },
    },
    {
      id: 'b3', skill: 'calculo', title: 'Calculando a porcentagem de um valor',
      text: 'Para calcular x% de um valor, multiplique o valor por x e divida por 100. Para saber quantos por cento uma parte representa, divida a parte pelo todo e multiplique por 100.',
      example: '20% de 150 = 150 × 20 ÷ 100 = 30. E 30 de 120 é: 30 ÷ 120 = 0,25 → 25%.',
      variants: {
        simples: 'x% de um número: número × x ÷ 100. Exemplo: 20% de 50 = 50 × 20 ÷ 100 = 10.',
        exemplo: 'Uma prova tem 40 questões e você acertou 30. 30 ÷ 40 = 0,75 → 75% de acerto.',
        outra: 'Transforme a porcentagem em decimal e multiplique: 20% = 0,2. Então 20% de 150 = 0,2 × 150 = 30.',
        detalhado: 'São duas perguntas diferentes: (1) "quanto é p% de V?" → p/100 × V; (2) "a parte P é quantos % de V?" → P/V × 100. Confundir qual é o todo (V) é o erro mais comum.',
      },
    },
    {
      id: 'b4', skill: 'desconto', title: 'Descontos e aumentos',
      text: 'No desconto, você calcula a porcentagem e subtrai do preço. No aumento, calcula e soma. Atalho: desconto de 10% = pagar 90% do preço.',
      example: 'Camiseta de R$ 60 com 10% de desconto: 10% de 60 = 6 → 60 − 6 = R$ 54.',
      variants: {
        simples: 'Desconto: acha a porcentagem e tira. Aumento: acha a porcentagem e soma.',
        exemplo: 'Um tênis de R$ 200 subiu 15%: 15% de 200 = 30. Novo preço: 200 + 30 = R$ 230.',
        outra: 'Use o fator: desconto de 20% → multiplica por 0,8. Aumento de 20% → multiplica por 1,2.',
        detalhado: 'Aumentos e descontos sucessivos não se cancelam: 100 com +20% vira 120; 120 com −20% vira 96. Isso acontece porque o segundo cálculo é feito sobre um valor diferente (1,2 × 0,8 = 0,96).',
      },
    },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'atalhos', prompt: '50% de alguma coisa é o mesmo que:', options: ['Um terço', 'A metade', 'Um quarto', 'O dobro'], answer: 1, hints: ['50 é que parte de 100?', '50 de 100 partes.', '50/100 simplificado dá 1/2.'], explanation: '50% = 50/100 = 1/2, ou seja, a metade.' },
    { id: 'q2', type: 'fill', difficulty: 1, skill: 'conceito', prompt: 'Escreva 25% como fração simplificada (a/b).', answers: ['1/4'], hints: ['Porcentagem é uma fração com denominador 100.', '25% = 25/100.', 'Simplifique 25/100 dividindo por 25.'], explanation: '25% = 25/100 = 1/4.' },
    { id: 'q3', type: 'mc', difficulty: 1, skill: 'atalhos', prompt: 'Quanto é 10% de 80?', options: ['8', '10', '18', '0,8'], answer: 0, hints: ['10% é um atalho fácil.', '10% = dividir por 10.', '80 ÷ 10.'], explanation: '10% de 80 = 80 ÷ 10 = 8.' },
    { id: 'q4', type: 'tf', difficulty: 1, skill: 'conceito', prompt: '100% representa o todo.', answer: true, hints: ['Porcentagem é "de cada 100".', '100 de 100 partes é quanto?', 'É tudo.'], explanation: 'Verdadeiro. 100% = 100/100 = 1 inteiro.' },
    { id: 'q5', type: 'fill', difficulty: 2, skill: 'calculo', prompt: 'Quanto é 20% de 150?', answers: ['30'], hints: ['Comece achando 10%.', '10% de 150 = 15.', '20% = 2 × 10%.'], explanation: '10% de 150 = 15, então 20% = 30. Ou: 150 × 20 ÷ 100 = 30.' },
    { id: 'q6', type: 'mc', difficulty: 2, skill: 'desconto', prompt: 'Uma camiseta custa R$ 60 e tem 10% de desconto. Quanto você paga?', options: ['R$ 50', 'R$ 54', 'R$ 56', 'R$ 66'], answer: 1, hints: ['Primeiro ache quanto é o desconto.', '10% de 60 = 6.', 'Desconto se subtrai: 60 − 6.'], explanation: 'O desconto é 10% de 60 = R$ 6. Você paga 60 − 6 = R$ 54.' },
    { id: 'q7', type: 'match', difficulty: 2, skill: 'atalhos', prompt: 'Ligue cada porcentagem à fração correspondente.', pairs: [['50%', 'A metade'], ['25%', 'Um quarto'], ['10%', 'Um décimo'], ['100%', 'O todo']], hints: ['Escreva cada uma sobre 100.', '25/100 = 1/4 e 10/100 = 1/10.', '100/100 = 1.'], explanation: '50% = 1/2, 25% = 1/4, 10% = 1/10, 100% = o todo.' },
    { id: 'q8', type: 'tf', difficulty: 2, skill: 'atalhos', prompt: 'Para calcular 10% de um número, basta dividi-lo por 10.', answer: true, hints: ['10% = 10/100.', '10/100 simplificado.', '= 1/10.'], explanation: 'Verdadeiro. 10% = 1/10, então é só dividir por 10.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'desconto', prompt: 'Um produto de R$ 200 teve aumento de 15%. Qual é o novo preço?', options: ['R$ 215', 'R$ 230', 'R$ 185', 'R$ 300'], answer: 1, hints: ['Calcule 15% de 200.', '10% = 20 e 5% = 10.', 'Aumento se soma: 200 + 30.'], explanation: '15% de 200 = 30. Novo preço = 200 + 30 = R$ 230.' },
    { id: 'q10', type: 'fill', difficulty: 3, skill: 'calculo', prompt: '30 é quantos por cento de 120? (só o número)', answers: ['25', '25%'], hints: ['Divida a parte pelo todo.', '30 ÷ 120 = 0,25.', 'Multiplique por 100.'], explanation: '30 ÷ 120 = 0,25 = 25%.' },
    { id: 'q11', type: 'mc', difficulty: 3, skill: 'desconto', prompt: 'Um valor de 100 sofre desconto de 20% e depois aumento de 20%. Qual o resultado final?', options: ['100', '96', '104', '120'], answer: 1, hints: ['Faça em duas etapas.', 'Depois do desconto: 80.', 'Agora calcule 20% de 80 e some.'], explanation: '100 − 20% = 80. 80 + 20% de 80 (16) = 96. O segundo cálculo é sobre um valor menor.' },
    { id: 'q12', type: 'mc', difficulty: 3, skill: 'calculo', prompt: 'Quanto é 15% de 40?', options: ['4', '6', '15', '5,5'], answer: 1, hints: ['Quebre 15% em 10% + 5%.', '10% de 40 = 4.', '5% é a metade de 10%: 2. Some.'], explanation: '10% de 40 = 4 e 5% = 2. Total: 4 + 2 = 6.' },
  ],
  review: ['% = dividido por 100', '10% = ÷10 · 50% = metade · 25% = um quarto', 'Desconto: subtrai · Aumento: soma', 'Parte ÷ todo × 100 = porcentagem'],
  sources: [BNCC, { title: 'Conteúdo autoral LUMI', kind: 'autoral' }],
}

export const equacao2grau: Lesson = {
  id: 'mat-equacao-2-grau',
  subject: 'matematica',
  title: 'Equação do 2º grau',
  levels: ['fund2', 'medio'],
  grade: '9º ano e 1ª série',
  aliases: ['equacao do segundo grau', 'equacao do 2 grau', 'bhaskara', 'baskara', 'delta', 'discriminante', 'equacao quadratica', 'raizes'],
  summary: 'Reconheça a equação do 2º grau, calcule o delta e encontre as raízes com a fórmula de Bhaskara.',
  intro: 'A equação do 2º grau aparece quando a incógnita está elevada ao quadrado. Vamos por partes, sem pressa.',
  skills: { forma: 'Forma geral e coeficientes', delta: 'Discriminante (Δ)', bhaskara: 'Fórmula de Bhaskara', incompletas: 'Equações incompletas' },
  blocks: [
    {
      id: 'b1', skill: 'forma', title: 'A forma geral',
      text: 'Toda equação do 2º grau pode ser escrita como ax² + bx + c = 0, em que a, b e c são números chamados coeficientes e a nunca é zero.',
      example: 'Em 2x² − 3x + 1 = 0: a = 2, b = −3 e c = 1. O sinal faz parte do coeficiente!',
      variants: {
        simples: 'Se o maior expoente do x é 2 (x²), é uma equação do 2º grau. O número na frente do x² é o a, na frente do x é o b, e o número sozinho é o c.',
        exemplo: 'x² − 5x + 6 = 0 → a = 1 (tem um "1" invisível na frente do x²), b = −5, c = 6.',
        outra: 'Pense como uma ficha com três espaços: [a]x² + [b]x + [c] = 0. Seu trabalho é preencher a ficha com os números da equação, sempre levando o sinal junto.',
        detalhado: 'Se a = 0, o termo x² desaparece e a equação passa a ser do 1º grau — por isso a ≠ 0. Antes de identificar os coeficientes, organize a equação: tudo de um lado e zero do outro. Ex.: x² = 5x − 6 vira x² − 5x + 6 = 0.',
      },
    },
    {
      id: 'b2', skill: 'delta', title: 'O discriminante (Δ)',
      text: 'O delta é calculado por Δ = b² − 4ac. Ele revela quantas raízes reais a equação tem: Δ > 0 → duas raízes diferentes; Δ = 0 → duas raízes iguais (uma só); Δ < 0 → nenhuma raiz real.',
      example: 'x² − 5x + 6 = 0 → Δ = (−5)² − 4·1·6 = 25 − 24 = 1. Como 1 > 0, há duas raízes diferentes.',
      variants: {
        simples: 'Delta é uma conta que vem antes da resposta: b vezes b, menos 4 vezes a vezes c. Se der positivo, tem duas respostas. Zero, uma. Negativo, nenhuma (nos números reais).',
        exemplo: 'x² + 2x + 5 = 0 → Δ = 4 − 20 = −16. Negativo: essa equação não tem raiz real.',
        outra: 'O delta é como um "detector": antes de fazer toda a conta, ele avisa se vale a pena continuar e quantas respostas vão sair.',
        detalhado: 'Na fórmula de Bhaskara aparece √Δ. Não existe raiz quadrada real de número negativo, por isso Δ < 0 não tem solução real. Quando Δ = 0, +√Δ e −√Δ dão o mesmo valor e as raízes coincidem: x = −b/2a.',
      },
    },
    {
      id: 'b3', skill: 'bhaskara', title: 'A fórmula de Bhaskara',
      text: 'Com o delta calculado, as raízes são x = (−b ± √Δ) ÷ 2a. O "±" gera duas contas: uma somando e outra subtraindo a raiz de delta.',
      example: 'x² − 5x + 6 = 0, Δ = 1 → x = (5 ± 1) ÷ 2 → x₁ = 6 ÷ 2 = 3 e x₂ = 4 ÷ 2 = 2.',
      variants: {
        simples: 'Receita: 1) ache a, b, c. 2) calcule delta. 3) faça (−b + √Δ) ÷ 2a e depois (−b − √Δ) ÷ 2a.',
        exemplo: 'x² + 2x − 8 = 0 → Δ = 4 + 32 = 36, √36 = 6 → x = (−2 ± 6) ÷ 2 → x₁ = 2 e x₂ = −4.',
        outra: 'Sempre confira: coloque a resposta no lugar do x. Se a conta der zero, acertou. Em x² − 5x + 6 com x = 3: 9 − 15 + 6 = 0 ✓.',
        detalhado: 'Cuidado com o −b: se b = −5, então −b = 5. Também vale a relação de soma e produto: x₁ + x₂ = −b/a e x₁ · x₂ = c/a — útil para conferir ou até resolver de cabeça.',
      },
    },
    {
      id: 'b4', skill: 'incompletas', title: 'Equações incompletas',
      text: 'Quando b = 0 ou c = 0 existe um caminho mais curto. Se c = 0, coloque x em evidência: x(ax + b) = 0. Se b = 0, isole o x² e tire a raiz.',
      example: 'x² − 4x = 0 → x(x − 4) = 0 → x = 0 ou x = 4. E x² − 9 = 0 → x² = 9 → x = 3 ou x = −3.',
      variants: {
        simples: 'Falta o número sozinho? Tire o x para fora. Falta o termo com x? Passe o número para o outro lado e tire a raiz.',
        exemplo: '2x² − 18 = 0 → 2x² = 18 → x² = 9 → x = ±3.',
        outra: 'Um produto só dá zero se um dos fatores for zero. Por isso x(x − 4) = 0 leva a x = 0 ou x − 4 = 0.',
        detalhado: 'Bhaskara também funciona nas incompletas, mas é mais lento. Quando c = 0, uma das raízes é sempre zero. Quando b = 0 e −c/a > 0, as raízes são simétricas (±√(−c/a)).',
      },
    },
  ],
  questions: [
    { id: 'q1', type: 'mc', difficulty: 1, skill: 'forma', prompt: 'Qual destas é uma equação do 2º grau?', options: ['3x + 2 = 0', 'x² − 5x + 6 = 0', 'x³ = 8', '2x = 10'], answer: 1, hints: ['Procure o maior expoente do x.', 'No 2º grau, o maior expoente é 2.', 'Qual tem x²?'], explanation: 'x² − 5x + 6 = 0 tem x² como maior potência: é do 2º grau.' },
    { id: 'q2', type: 'mc', difficulty: 1, skill: 'forma', prompt: 'Em 2x² − 3x + 1 = 0, quais são a, b e c?', options: ['a=2, b=3, c=1', 'a=2, b=−3, c=1', 'a=−3, b=2, c=1', 'a=1, b=−3, c=2'], answer: 1, hints: ['a acompanha x², b acompanha x.', 'O sinal faz parte do coeficiente.', 'O termo com x é −3x.'], explanation: 'a = 2 (x²), b = −3 (x, com o sinal) e c = 1.' },
    { id: 'q3', type: 'tf', difficulty: 1, skill: 'forma', prompt: 'Em uma equação do 2º grau, o coeficiente a pode ser zero.', answer: false, hints: ['O que acontece com ax² se a = 0?', '0 · x² = 0.', 'O x² desaparece.'], explanation: 'Falso. Se a = 0 o termo x² some e a equação vira do 1º grau.' },
    { id: 'q4', type: 'fill', difficulty: 2, skill: 'delta', prompt: 'Calcule o Δ da equação x² − 5x + 6 = 0.', answers: ['1'], hints: ['Δ = b² − 4ac.', 'a = 1, b = −5, c = 6.', '(−5)² = 25 e 4·1·6 = 24.'], explanation: 'Δ = 25 − 24 = 1.' },
    { id: 'q5', type: 'mc', difficulty: 2, skill: 'delta', prompt: 'Se Δ < 0, a equação:', options: ['Tem duas raízes reais diferentes', 'Tem uma raiz real', 'Não tem raízes reais', 'Tem infinitas raízes'], answer: 2, hints: ['Na fórmula aparece √Δ.', 'Existe raiz quadrada real de número negativo?', 'Não existe.'], explanation: 'Não existe raiz quadrada real de número negativo, então não há raízes reais.' },
    { id: 'q6', type: 'match', difficulty: 2, skill: 'delta', prompt: 'Ligue o valor do delta ao número de raízes reais.', pairs: [['Δ > 0', 'Duas raízes diferentes'], ['Δ = 0', 'Duas raízes iguais'], ['Δ < 0', 'Nenhuma raiz real']], hints: ['Pense no ± da fórmula.', 'Se √Δ = 0, somar e subtrair dá o mesmo.', 'Negativo não tem raiz real.'], explanation: 'Δ > 0: duas diferentes · Δ = 0: iguais · Δ < 0: nenhuma real.' },
    { id: 'q7', type: 'mc', difficulty: 2, skill: 'bhaskara', prompt: 'Quais são as raízes de x² − 5x + 6 = 0?', options: ['1 e 6', '2 e 3', '−2 e −3', '5 e 6'], answer: 1, hints: ['O Δ dessa equação é 1.', 'x = (5 ± 1) ÷ 2.', '6 ÷ 2 e 4 ÷ 2.'], explanation: 'x = (5 ± 1) ÷ 2 → 3 e 2. Conferindo: 9 − 15 + 6 = 0 ✓.' },
    { id: 'q8', type: 'fill', difficulty: 2, skill: 'incompletas', prompt: 'Qual é a raiz positiva de x² − 9 = 0?', answers: ['3', '+3'], hints: ['Não precisa de Bhaskara.', 'Passe o 9 para o outro lado.', 'x² = 9. Que número vezes ele mesmo dá 9?'], explanation: 'x² = 9 → x = ±3. A positiva é 3.' },
    { id: 'q9', type: 'mc', difficulty: 3, skill: 'incompletas', prompt: 'Quais são as raízes de x² − 4x = 0?', options: ['0 e 4', '2 e −2', '4 e −4', 'Só 4'], answer: 0, hints: ['Falta o c.', 'Coloque x em evidência.', 'x(x − 4) = 0.'], explanation: 'x(x − 4) = 0 → x = 0 ou x = 4.' },
    { id: 'q10', type: 'mc', difficulty: 3, skill: 'bhaskara', prompt: 'Quais são as raízes de x² + 2x − 8 = 0?', options: ['2 e −4', '−2 e 4', '4 e 8', '1 e −8'], answer: 0, hints: ['Δ = 4 − 4·1·(−8).', 'Δ = 36, √Δ = 6.', 'x = (−2 ± 6) ÷ 2.'], explanation: 'Δ = 36 → x = (−2 ± 6) ÷ 2 → 2 e −4.' },
    { id: 'q11', type: 'tf', difficulty: 2, skill: 'delta', prompt: 'Quando Δ = 0, a equação tem duas raízes reais iguais.', answer: true, hints: ['Quanto é √0?', '−b + 0 e −b − 0.', 'Dá o mesmo resultado.'], explanation: 'Verdadeiro. Com √Δ = 0, as duas contas dão o mesmo valor.' },
    { id: 'q12', type: 'mc', difficulty: 3, skill: 'bhaskara', prompt: 'Quais são as raízes de 2x² − 8x + 6 = 0?', options: ['1 e 3', '2 e 6', '−1 e −3', '4 e 2'], answer: 0, hints: ['a = 2, b = −8, c = 6.', 'Δ = 64 − 48 = 16.', 'x = (8 ± 4) ÷ 4.'], explanation: 'Δ = 16 → x = (8 ± 4) ÷ 4 → 3 e 1.' },
  ],
  review: ['Forma geral: ax² + bx + c = 0, com a ≠ 0', 'Δ = b² − 4ac', 'x = (−b ± √Δ) ÷ 2a', 'Incompletas: evidência (c = 0) ou isolar x² (b = 0)'],
  sources: [BNCC, { title: 'Conteúdo autoral LUMI', kind: 'autoral' }],
}
