// LOTE 2 — PORTUGUÊS · texto, sentido e linguagem. Conteúdo original do LUMI.
import { block, eqsPt, fill, lesson, match, mc, open, order, SRC, tf } from '../dsl'

const FONTES = [SRC.bncc('Língua Portuguesa — Anos Finais e Ensino Médio'), SRC.web('Matriz de Referência do ENEM — Linguagens, Códigos e suas Tecnologias', 'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem', 'INEP', 'instituicao'), SRC.autoral()]
const EF = ['fund2', 'medio'] as const

export const periodoComposto = lesson({
  id: 'por-periodo-composto', subject: 'portugues', title: 'Período composto: coordenação e subordinação', levels: [...EF], grade: '9º ano e Ensino Médio',
  topic: 'Gramática', subtopic: 'Orações coordenadas, subordinadas e conjunções',
  aliases: ['periodo composto', 'oracoes coordenadas', 'oracoes subordinadas', 'conjuncoes', 'conjuncao adversativa', 'conjuncao conclusiva', 'oracao subordinada adverbial', 'periodo simples'],
  summary: 'Diferencie período simples e composto, coordenação e subordinação, e reconheça o sentido das conjunções.',
  intro: '“Estudei, mas não passei” e “Passei porque estudei”: as conjunções mudam a relação entre as ideias.',
  objective: 'Identificar orações num período, diferenciar coordenação de subordinação e reconhecer o valor das conjunções (adição, oposição, alternância, conclusão, explicação, causa, condição, concessão…).',
  prerequisites: ['por-sujeito-predicado', 'por-classes-gramaticais'], next: ['por-coesao-coerencia'],
  skills: { oracoes: 'Período simples e composto', coordenadas: 'Orações coordenadas', subordinadas: 'Orações subordinadas', sentido: 'Sentido das conjunções' },
  blocks: [
    block('oracoes', 'Quantas orações?',
      'Oração é o enunciado organizado em torno de um verbo (ou locução verbal). Período simples tem uma oração só; período composto tem duas ou mais. Dica: conte os verbos.',
      '“Choveu.” (simples) · “Choveu e o jogo foi cancelado.” (composto: choveu / foi cancelado).',
      'Um verbo = uma oração.',
      '“Cheguei, vi e venci”: três verbos, três orações.',
      '1. Circule os verbos (locução conta como um).\n2. Conte.\n3. Um: período simples. Dois ou mais: composto.',
      'Locução verbal (vou estudar, tinha feito) forma UMA oração, apesar de ter dois verbos.'),
    block('coordenadas', 'Coordenação: orações independentes',
      'Nas coordenadas, as orações têm sentido completo sozinhas e se ligam por conjunções coordenativas: aditivas (e, nem), adversativas (mas, porém, contudo), alternativas (ou… ou), conclusivas (logo, portanto) e explicativas (pois, porque — antes de explicação).',
      'Estudei muito, portanto passei. · Estude, pois a prova é amanhã.',
      'Coordenadas “andam lado a lado”: nenhuma depende da outra.',
      '“Choveu, mas fomos à praia” — as duas partes fazem sentido separadas.',
      '1. Separe as orações.\n2. Cada uma faz sentido sozinha? Coordenação.\n3. Classifique pela conjunção (e, mas, ou, logo, pois).',
      'Coordenação é como vagões engatados: cada vagão existe sozinho, o engate só os une.'),
    block('subordinadas', 'Subordinação: uma depende da outra',
      'Na subordinação, uma oração (subordinada) completa o sentido de outra (principal), exercendo uma função dela. As substantivas funcionam como substantivo (“Espero que você venha”); as adjetivas, como adjetivo (“O livro que li é ótimo”); as adverbiais, como advérbio, indicando causa, condição, tempo, concessão, finalidade (“Se chover, fico em casa”).',
      'Principal: “fico em casa” · Subordinada adverbial condicional: “se chover”.',
      'Subordinada é “pendurada” na principal: sozinha, fica incompleta.',
      '“Quando o sinal tocar” não diz nada sozinho; precisa de “sairemos” para ter sentido.',
      '1. Ache a oração principal (a que tem sentido próprio).\n2. Veja qual oração completa ou modifica a principal.\n3. Classifique: substantiva, adjetiva ou adverbial.',
      'Coordenação soma ideias de mesmo nível; subordinação cria uma hierarquia: uma ideia principal e outra que a explica ou condiciona.'),
    block('sentido', 'O que cada conjunção diz',
      'Mais importante que o nome é o sentido: adição (e, além disso), oposição (mas, porém), concessão (embora, ainda que — admite algo e mantém a ideia), causa (porque, já que), consequência (tão… que), condição (se, caso), finalidade (para que), tempo (quando), conclusão (logo, portanto).',
      '“Embora estivesse cansado, continuou.” (concessão) · “Estava tão cansado que dormiu.” (consequência).',
      'Pergunte: que relação a conjunção cria entre as ideias?',
      'Em redação, trocar “mas” por “portanto” muda a lógica do argumento.',
      '1. Leia as duas partes.\n2. Pergunte: soma, opõe, explica, conclui, condiciona?\n3. Escolha a conjunção com esse sentido.',
      '“Mas” opõe dizendo que o segundo fato vence; “embora” começa admitindo o obstáculo: “Embora chovesse, fomos” = “Chovia, mas fomos”.'),
  ],
  questions: [
    mc(1, 'oracoes', 'Quantas orações há em “Cheguei, vi e venci”?', ['1', '2', '3', '4'], 2, ['Conte os verbos.', 'cheguei, vi, venci.', 'Três.'], 'Três orações.'),
    mc(1, 'coordenadas', 'Em “Estudei, mas não passei”, a conjunção “mas” indica:', ['adição', 'oposição', 'conclusão', 'condição'], 1, ['Esperava-se passar.', 'Houve contraste.', 'Adversativa.'], 'Oposição (adversativa).'),
    tf(1, 'oracoes', 'Uma locução verbal (vou estudar) forma uma única oração.', true, ['Locução = um núcleo verbal.', 'Conta como um verbo.', 'Uma oração.'], 'Verdadeiro.'),
    fill(1, 'coordenadas', 'Complete com uma conjunção conclusiva: “Estudei muito, ___ passei.”', ['portanto', 'logo', 'por isso'], ['Indica conclusão.', 'Consequência lógica.', 'p… ou l…'], 'Portanto / logo.'),
    match(2, 'sentido', 'Ligue cada conjunção ao sentido.', [['embora', 'concessão'], ['se', 'condição'], ['porque', 'causa'], ['para que', 'finalidade']], ['Embora admite algo.', 'Se condiciona.', 'Para que indica objetivo.'], 'concessão · condição · causa · finalidade.'),
    mc(2, 'subordinadas', 'Em “Se chover, fico em casa”, a oração principal é:', ['Se chover', 'fico em casa', 'as duas', 'nenhuma'], 1, ['Qual tem sentido sozinha?', '“fico em casa”.', 'A outra é condição.'], 'Fico em casa.'),
    mc(2, 'sentido', 'Qual frase expressa concessão?', ['Choveu e ficamos em casa.', 'Embora chovesse, fomos à praia.', 'Se chover, ficamos.', 'Fomos porque fazia sol.'], 1, ['Concessão admite um obstáculo.', 'E mantém a ação.', '“Embora”.'], 'Embora chovesse, fomos.'),
    mc(3, 'sentido', 'Reescrevendo “Chovia, mas fomos ao passeio” com o MESMO sentido:', ['Como chovia, fomos ao passeio.', 'Embora chovesse, fomos ao passeio.', 'Se chovesse, iríamos ao passeio.', 'Chovia, portanto fomos ao passeio.'], 1, ['“Mas” opõe.', 'Concessão equivale.', 'Embora.'], 'Embora chovesse, fomos.'),
    order(2, 'subordinadas', 'Ordene os passos para classificar um período composto.', ['Contar os verbos', 'Separar as orações', 'Ver se elas têm sentido sozinhas', 'Classificar em coordenação ou subordinação'], ['Comece pelos verbos.', 'Depois separe.', 'Teste a independência.'], 'verbos → separar → independência → classificar.'),
    open(3, 'sentido', 'Explique a diferença de sentido entre “Ele estudou, portanto passou” e “Ele estudou, mas passou”.', 'Em “portanto”, passar é a conclusão lógica de ter estudado (relação de conclusão). Em “mas”, passar aparece como algo inesperado em relação a estudar, o que não faz muito sentido: a conjunção adversativa cria uma oposição entre ideias que, na verdade, combinam.', ['conclusao', 'oposicao', 'inesperado', 'logica', 'conjuncao'], ['Que relação “portanto” cria?', 'E “mas”?', 'A oposição faz sentido aqui?'], 'Conjunções mudam a lógica: conclusão × oposição.'),
  ],
  review: ['Oração = verbo (locução conta como um)', 'Coordenadas: independentes (e, mas, ou, logo, pois)', 'Subordinadas: dependem da principal (substantivas, adjetivas, adverbiais)', 'O essencial é o sentido da conjunção'],
  relatedQuestions: ['o que é período composto', 'diferença entre coordenação e subordinação', 'sentido das conjunções'],
  equivalentQuestions: eqsPt(['período composto', 'orações coordenadas', 'orações subordinadas', 'conjunções'], ['diferença entre oração coordenada e subordinada', 'o que é conjunção adversativa', 'o que é conjunção concessiva', 'embora é conjunção de quê', 'o que é oração principal', 'como contar orações', 'período simples e composto', 'portanto é conjunção conclusiva', 'oração subordinada adverbial condicional', 'valor semântico das conjunções']),
  commonErrors: ['Contar locução verbal como duas orações.', 'Confundir concessão (embora) com causa (porque).', 'Decorar nomes sem entender o sentido.'],
  sources: FONTES,
})

export const figurasLinguagem = lesson({
  id: 'por-figuras-linguagem', subject: 'portugues', title: 'Figuras de linguagem', levels: [...EF], grade: '8º ano ao Ensino Médio',
  topic: 'Linguagem', subtopic: 'Metáfora, comparação, metonímia, hipérbole, ironia e outras',
  aliases: ['figuras de linguagem', 'metafora', 'comparacao', 'metonimia', 'hiperbole', 'ironia', 'personificacao', 'prosopopeia', 'antitese', 'eufemismo', 'onomatopeia', 'figura de linguagem enem'],
  summary: 'Reconheça as principais figuras de linguagem e o efeito de sentido que cada uma cria.',
  intro: '“Já te disse um milhão de vezes!” Ninguém contou — é uma hipérbole. As figuras dão força à linguagem.',
  objective: 'Identificar metáfora, comparação, metonímia, hipérbole, personificação, ironia, antítese, eufemismo e onomatopeia e explicar o efeito de sentido de cada uma.',
  prerequisites: ['por-classes-gramaticais'], next: ['por-funcoes-linguagem'],
  skills: { comparacao: 'Comparação e metáfora', metonimia: 'Metonímia e personificação', intensidade: 'Hipérbole, eufemismo e antítese', ironia: 'Ironia e onomatopeia' },
  blocks: [
    block('comparacao', 'Comparação e metáfora',
      'Comparação aproxima dois elementos usando um conectivo (como, feito, tal qual): “Ela é forte como um touro”. Metáfora faz essa aproximação sem o conectivo, transferindo o sentido: “Ela é um touro”. As duas criam imagens a partir de semelhanças.',
      '“Seus olhos brilhavam como estrelas” (comparação) · “Seus olhos são estrelas” (metáfora).',
      'Comparação tem “como”; metáfora não tem.',
      'Numa música: “Você é o sol da minha vida” — metáfora: a pessoa ilumina e aquece como o sol.',
      '1. Veja se há dois elementos aproximados.\n2. Há “como/feito/tal qual”? Comparação.\n3. Não há? Metáfora.',
      'A metáfora é uma comparação “encurtada”: tira o “como” e afirma diretamente.'),
    block('metonimia', 'Metonímia e personificação',
      'Metonímia troca uma palavra por outra com relação de proximidade: autor pela obra (“Li Machado”), marca pelo produto (“Comprei um Bombril”), parte pelo todo (“Não tenho um teto”), recipiente pelo conteúdo (“Bebi dois copos”). Personificação (prosopopeia) dá características humanas a seres não humanos: “O vento sussurrava”.',
      '“Ele tem boa cabeça” (metonímia: cabeça = inteligência) · “A cidade dormia” (personificação).',
      'Metonímia troca por algo relacionado; personificação dá “jeito de gente”.',
      '“Vamos tomar uma Coca?” (marca pelo produto) · “O sol sorria no céu” (personificação).',
      '1. Uma palavra foi usada no lugar de outra relacionada? Metonímia.\n2. Algo não humano age como gente? Personificação.',
      'Metáfora usa SEMELHANÇA (olhos = estrelas); metonímia usa PROXIMIDADE real (ler Machado = ler os livros dele).'),
    block('intensidade', 'Hipérbole, eufemismo e antítese',
      'Hipérbole é o exagero intencional para dar ênfase: “Chorei rios de lágrimas”. Eufemismo suaviza algo desagradável: “Ele partiu desta para melhor” (morreu). Antítese aproxima ideias opostas: “Nasce o sol e não dura mais que um dia”; “É um riso triste”.',
      '“Estou morrendo de fome” (hipérbole) · “Ele faltou com a verdade” (eufemismo para mentiu) · “Amor e ódio” (antítese).',
      'Hipérbole exagera; eufemismo suaviza; antítese junta opostos.',
      'Boletim: “O aluno precisa melhorar” (eufemismo para “foi mal”).',
      '1. Há exagero impossível? Hipérbole.\n2. Há suavização de algo ruim? Eufemismo.\n3. Há palavras opostas próximas? Antítese.',
      'Hipérbole e eufemismo são opostos: uma aumenta, a outra diminui a força do que se diz.'),
    block('ironia', 'Ironia e onomatopeia',
      'Ironia é dizer o contrário do que se pensa, geralmente para criticar ou fazer humor; o contexto revela a intenção: “Que ótimo! Choveu no dia do passeio”. Onomatopeia imita sons: “tic-tac”, “au-au”, “vrum”, “plaft”.',
      '“Parabéns pela pontualidade!” (para quem chegou 2 horas atrasado) · “O relógio fazia tique-taque.”',
      'Ironia = dizer o oposto; onomatopeia = imitar o som.',
      'Em quadrinhos, “POW!” e “BUM!” são onomatopeias.',
      '1. A frase diz o contrário do que a situação mostra? Ironia.\n2. A palavra imita um som? Onomatopeia.',
      'Na fala, a ironia vem no tom de voz; na escrita, o leitor precisa do contexto — por isso ela é muito cobrada em provas.'),
  ],
  questions: [
    mc(1, 'intensidade', '“Já te disse um milhão de vezes!” é um exemplo de:', ['metáfora', 'hipérbole', 'eufemismo', 'antítese'], 1, ['Alguém disse um milhão de vezes?', 'É exagero.', 'Hipérbole.'], 'Hipérbole.'),
    mc(1, 'comparacao', '“Ela é forte como um touro” é:', ['metáfora', 'comparação', 'ironia', 'metonímia'], 1, ['Há conectivo?', '“como”.', 'Comparação.'], 'Comparação.'),
    tf(1, 'ironia', '“Tique-taque” é uma onomatopeia.', true, ['Imita um som?', 'O som do relógio.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'metonimia', 'Qual figura dá características humanas a seres não humanos? (nome)', ['personificação', 'prosopopeia', 'personificacao'], ['“O vento sussurrava.”', 'Coisas agindo como gente.', 'Perso…'], 'Personificação (prosopopeia).'),
    match(2, 'intensidade', 'Ligue cada frase à figura.', [['Estou morrendo de fome.', 'hipérbole'], ['Ele partiu desta para melhor.', 'eufemismo'], ['É um riso triste.', 'antítese'], ['Li Machado nas férias.', 'metonímia']], ['Exagero.', 'Suavização da morte.', 'Opostos juntos; autor pela obra.'], 'hipérbole · eufemismo · antítese · metonímia.'),
    mc(2, 'comparacao', '“Seus olhos são duas estrelas” é:', ['comparação', 'metáfora', 'hipérbole', 'onomatopeia'], 1, ['Há “como”?', 'Não.', 'Aproximação direta.'], 'Metáfora.'),
    mc(2, 'ironia', 'Um aluno chega 2 horas atrasado e o professor diz: “Que pontualidade!”. A figura é:', ['eufemismo', 'ironia', 'metáfora', 'hipérbole'], 1, ['O professor elogia de verdade?', 'Diz o contrário.', 'Ironia.'], 'Ironia.'),
    mc(3, 'metonimia', 'Em “A cidade inteira foi ao estádio”, há:', ['metáfora', 'metonímia', 'onomatopeia', 'antítese'], 1, ['A cidade (lugar) foi?', 'Foram os moradores.', 'Lugar pelos habitantes.'], 'Metonímia (lugar pelos habitantes).'),
    order(2, 'comparacao', 'Ordene da imagem mais “explícita” para a mais “direta”.', ['Ela é forte como um touro.', 'Ela é forte feito touro.', 'Ela é um touro.'], ['Comparação completa primeiro.', 'Comparação com “feito”.', 'Por fim a metáfora.'], 'comparação → comparação → metáfora.'),
    open(3, 'metonimia', 'Explique a diferença entre metáfora e metonímia com um exemplo de cada.', 'Na metáfora, a troca se baseia numa semelhança: “Seus olhos são estrelas” (brilham como estrelas). Na metonímia, a troca se baseia numa relação real de proximidade: “Li Machado” (o autor no lugar da obra).', ['semelhanca', 'proximidade', 'relacao', 'metafora', 'metonimia'], ['Metáfora usa o quê?', 'Metonímia usa o quê?', 'Dê um exemplo de cada.'], 'Metáfora: semelhança · metonímia: proximidade.'),
  ],
  review: ['Comparação (com “como”) × metáfora (sem conectivo)', 'Metonímia: troca por proximidade (autor/obra, marca/produto) · personificação', 'Hipérbole (exagero) · eufemismo (suaviza) · antítese (opostos)', 'Ironia (diz o contrário) · onomatopeia (imita sons)'],
  relatedQuestions: ['o que são figuras de linguagem', 'diferença entre metáfora e comparação', 'exemplos de ironia'],
  equivalentQuestions: eqsPt(['figuras de linguagem', 'metáfora', 'hipérbole', 'ironia'], ['diferença entre metáfora e metonímia', 'o que é personificação', 'o que é prosopopeia', 'o que é eufemismo', 'o que é antítese', 'exemplos de onomatopeia', 'estou morrendo de fome é que figura', 'li machado é metonímia', 'figuras de linguagem no enem', 'como identificar ironia']),
  commonErrors: ['Confundir metáfora com metonímia.', 'Achar que toda comparação é metáfora.', 'Ler ironia ao pé da letra.'],
  sources: FONTES, enem: 'Figuras de linguagem e efeitos de sentido são cobrados em textos literários, anúncios e charges.',
})

export const interpretacaoTexto = lesson({
  id: 'por-interpretacao-texto', subject: 'portugues', title: 'Interpretação de texto', levels: [...EF], grade: '6º ano ao Ensino Médio',
  topic: 'Leitura', subtopic: 'Ideia principal, inferência, fato × opinião e intenção',
  aliases: ['interpretacao de texto', 'compreensao de texto', 'ideia principal', 'inferencia', 'fato e opiniao', 'intencao do autor', 'como interpretar texto', 'leitura e interpretacao', 'tese do texto'],
  summary: 'Encontre a ideia principal, faça inferências com base no texto, separe fato de opinião e descubra a intenção do autor.',
  intro: 'Ler não é só decifrar palavras: é entender o que o texto diz — e o que ele dá a entender.',
  objective: 'Identificar tema e ideia principal, localizar informações explícitas, fazer inferências sustentadas pelo texto, distinguir fato de opinião e reconhecer a intenção e o público do autor.',
  prerequisites: ['por-tipos-generos-textuais'], next: ['por-coesao-coerencia'],
  skills: { ideia: 'Tema e ideia principal', explicita: 'Informação explícita e inferência', fato: 'Fato × opinião', intencao: 'Intenção, público e efeitos' },
  blocks: [
    block('ideia', 'Tema e ideia principal',
      'Tema é o assunto geral (“poluição dos rios”); ideia principal é o que o texto afirma sobre o tema (“a poluição dos rios pode ser reduzida com saneamento”). Em textos argumentativos, a ideia principal é a tese. Títulos, a primeira e a última frase de cada parágrafo costumam dar pistas.',
      'Tema: celular na escola. Ideia principal: o uso deve ser orientado, e não proibido.',
      'Tema = do que fala. Ideia principal = o que diz sobre isso.',
      'Um artigo sobre sono: o tema é “sono dos adolescentes”; a tese é “escolas deveriam começar mais tarde”.',
      '1. Leia o título e o texto todo.\n2. Pergunte: de que fala? (tema)\n3. Pergunte: o que defende ou mostra? (ideia principal)\n4. Resuma numa frase.',
      'O tema cabe numa expressão; a ideia principal precisa de uma frase com verbo.'),
    block('explicita', 'O que está escrito e o que se deduz',
      'Informação explícita está escrita no texto. Inferência é uma conclusão que o texto não diz diretamente, mas que as pistas sustentam. Toda inferência precisa de uma evidência no texto; se não há pista, não é inferência, é suposição.',
      '“Ela pegou o guarda-chuva e suspirou ao olhar a janela” → infere-se que chove e que ela não está animada.',
      'Inferir = concluir usando pistas do texto.',
      'Em prova: “Pode-se inferir que…” — procure a frase do texto que PROVA a alternativa.',
      '1. Leia a pergunta.\n2. Volte ao texto e ache as pistas.\n3. Escolha a conclusão que as pistas sustentam.\n4. Descarte o que exige imaginar demais.',
      'Alternativas “verdadeiras no mundo real”, mas sem apoio no texto, são as armadilhas mais comuns.'),
    block('fato', 'Fato ou opinião?',
      'Fato pode ser comprovado (“A lei foi aprovada em 2020”). Opinião é um julgamento pessoal (“A lei é injusta”). Pistas de opinião: adjetivos avaliativos (melhor, péssimo, incrível), verbos como achar, acreditar, parecer, e expressões como “deveria”, “é preciso”.',
      'Fato: “O parque tem 3 km de trilhas.” Opinião: “É o parque mais bonito da cidade.”',
      'Fato dá para provar; opinião é o que alguém pensa.',
      'Numa resenha: “O filme tem 2 horas (fato) e é emocionante (opinião).”',
      '1. Dá para verificar em dados, documentos, medidas? Fato.\n2. Há julgamento, gosto ou sugestão? Opinião.\n3. Veja como o autor usa fatos para sustentar opiniões.',
      'Uma opinião dita com muita segurança continua sendo opinião: “Certamente é o melhor livro” não vira fato.'),
    block('intencao', 'Intenção, público e efeitos',
      'Pergunte: quem escreveu, para quem e para quê? O autor quer informar, convencer, emocionar, divertir, orientar? A escolha das palavras, a pontuação, as imagens e o gênero revelam a intenção e produzem efeitos de sentido (humor, crítica, urgência).',
      'Um cartaz “Cada gota conta!” com imagem de torneira pingando quer conscientizar sobre o desperdício de água.',
      'Descubra para que o texto foi feito.',
      'Uma charge exagera traços de um político para criticá-lo com humor.',
      '1. Identifique o gênero e onde circula.\n2. Pense no público.\n3. Pergunte o que o autor quer que o leitor pense ou faça.\n4. Observe palavras e imagens que reforçam isso.',
      'O mesmo tema pode ter intenções diferentes: a notícia sobre lixo informa; a campanha sobre lixo quer mudar comportamentos.'),
  ],
  questions: [
    mc(1, 'fato', 'Qual frase é uma OPINIÃO?', ['A escola tem 800 alunos.', 'A escola foi fundada em 1990.', 'É a melhor escola da cidade.', 'A escola fica na Rua A.'], 2, ['Qual não dá para provar?', 'Procure julgamento.', '“melhor”.'], 'É a melhor escola da cidade.'),
    mc(1, 'ideia', 'O tema de um texto é:', ['a opinião do autor', 'o assunto geral', 'o título sempre', 'a última frase'], 1, ['Tema = de que fala.', 'É o assunto.', 'Assunto geral.'], 'O assunto geral.'),
    tf(1, 'explicita', 'Uma inferência precisa ser sustentada por pistas do texto.', true, ['Inferir é concluir…', '…com base em evidências.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'ideia', 'Em textos argumentativos, a ideia principal defendida se chama ___.', ['tese'], ['É o ponto de vista do autor.', 'Começa com t.', 'T-e-s-e.'], 'Tese.'),
    match(2, 'intencao', 'Ligue cada gênero à intenção mais comum.', [['anúncio', 'convencer a comprar'], ['notícia', 'informar fatos'], ['manual', 'orientar/instruir'], ['charge', 'criticar com humor']], ['Anúncio vende.', 'Notícia relata.', 'Manual ensina; charge critica.'], 'anúncio · notícia · manual · charge.'),
    mc(2, 'explicita', '“Rafael olhou o relógio pela quinta vez e bateu o pé no chão.” Pode-se inferir que Rafael está:', ['tranquilo', 'impaciente', 'dormindo', 'feliz com a espera'], 1, ['O que ele repete?', 'Olhar o relógio e bater o pé.', 'Sinais de pressa.'], 'Impaciente.'),
    mc(2, 'fato', '“Apesar de apenas 30% dos moradores reciclarem, o programa certamente vai transformar a cidade.” A segunda parte é:', ['fato comprovado', 'opinião/previsão', 'dado estatístico', 'citação de lei'], 1, ['Dá para provar hoje?', 'É uma previsão.', 'Opinião.'], 'Opinião (previsão com certeza).'),
    order(2, 'explicita', 'Ordene os passos de uma boa inferência.', ['Ler a pergunta', 'Encontrar as pistas no texto', 'Formular a conclusão', 'Descartar alternativas sem evidência'], ['Primeiro entenda o que se pede.', 'Depois busque evidências.', 'Conclua e elimine.'], 'pergunta → pistas → conclusão → descartar.'),
    mc(3, 'intencao', 'Uma campanha mostra uma tartaruga presa num canudo com a frase “Vale a pena?”. A intenção é:', ['vender canudos', 'informar a temperatura do mar', 'levar o leitor a repensar o uso de plástico', 'divulgar um restaurante'], 2, ['Imagem + pergunta retórica.', 'Que comportamento quer mudar?', 'O uso de plástico.'], 'Conscientizar sobre o plástico.'),
    open(3, 'ideia', 'Qual a diferença entre tema e ideia principal? Dê um exemplo.', 'O tema é o assunto de que o texto trata, como “uso do celular na escola”. A ideia principal é o que o texto afirma sobre esse assunto, como “o celular deve ser usado com orientação dos professores, e não proibido”.', ['assunto', 'afirma', 'tema', 'ideia principal', 'exemplo'], ['Tema cabe numa expressão.', 'Ideia principal é uma frase.', 'Mostre com um mesmo assunto.'], 'Tema = assunto; ideia principal = afirmação sobre ele.'),
  ],
  review: ['Tema (assunto) × ideia principal (o que se afirma) · tese', 'Explícito (escrito) × inferência (deduzido com pistas)', 'Fato (comprovável) × opinião (julgamento)', 'Intenção: quem, para quem, para quê'],
  relatedQuestions: ['como interpretar texto', 'diferença entre fato e opinião', 'o que é inferência'],
  equivalentQuestions: eqsPt(['interpretação de texto', 'compreensão de texto', 'inferência'], ['como achar a ideia principal', 'o que é tema de um texto', 'o que é tese', 'como diferenciar fato de opinião', 'o que significa pode-se inferir', 'como descobrir a intenção do autor', 'dicas de interpretação para o enem', 'o que é informação explícita', 'como ler uma charge', 'como resumir um texto']),
  commonErrors: ['Escolher alternativas “verdadeiras” mas sem apoio no texto.', 'Confundir tema com ideia principal.', 'Tomar opinião segura por fato.'],
  sources: FONTES, enem: 'Interpretação é a base de toda a prova de Linguagens (e das demais áreas).',
})

export const coesaoCoerencia = lesson({
  id: 'por-coesao-coerencia', subject: 'portugues', title: 'Coesão e coerência', levels: [...EF], grade: '9º ano e Ensino Médio',
  topic: 'Produção de texto', subtopic: 'Mecanismos de coesão, conectivos e coerência',
  aliases: ['coesao', 'coerencia', 'coesao e coerencia', 'conectivos', 'elementos coesivos', 'coesao referencial', 'coesao sequencial', 'repeticao de palavras', 'conectivos para redacao'],
  summary: 'Ligue as ideias do texto com pronomes, sinônimos e conectivos e garanta que ele faça sentido.',
  intro: 'Um texto não é um amontoado de frases: elas precisam estar ligadas (coesão) e fazer sentido juntas (coerência).',
  objective: 'Usar mecanismos de coesão referencial (pronomes, sinônimos, elipse) e sequencial (conectivos) e avaliar a coerência de um texto, evitando repetições e contradições.',
  prerequisites: ['por-pronomes', 'por-periodo-composto'], next: ['por-variacao-linguistica'],
  skills: { referencial: 'Coesão referencial', sequencial: 'Coesão sequencial (conectivos)', coerencia: 'Coerência', revisar: 'Revisar o próprio texto' },
  blocks: [
    block('referencial', 'Retomar sem repetir',
      'Coesão referencial é retomar ou antecipar termos do texto usando pronomes (ele, isso, cujo), sinônimos ou expressões equivalentes (“Machado de Assis… o escritor… o autor de Dom Casmurro”) e elipse (omitir um termo que fica subentendido).',
      '“Ana chegou cedo. Ela abriu a sala e [Ana] ligou as luzes.” (pronome e elipse).',
      'Troque a palavra repetida por pronome ou sinônimo.',
      'Redação: em vez de repetir “internet” cinco vezes, use “a rede”, “esse meio”, “ela”.',
      '1. Ache palavras repetidas.\n2. Substitua por pronome, sinônimo ou expressão equivalente.\n3. Confira se fica claro a quem se refere.',
      'Cuidado com a ambiguidade: “Pedro falou com João e ele saiu” — quem saiu? Às vezes é melhor repetir o nome.'),
    block('sequencial', 'Conectivos: ligando as ideias',
      'Coesão sequencial usa conectivos para mostrar a relação entre as ideias: adição (além disso, também), oposição (no entanto, porém), causa (porque, visto que), consequência (por isso, de modo que), conclusão (portanto, logo), exemplificação (por exemplo), sequência (em primeiro lugar, em seguida, por fim).',
      '“O desmatamento cresce. Além disso, as queimadas aumentaram. Portanto, é urgente agir.”',
      'Conectivos são as “pontes” entre as frases.',
      'Nos parágrafos de uma redação: “Em primeiro lugar… Além disso… Dessa forma…”.',
      '1. Veja a relação entre duas ideias.\n2. Escolha o conectivo com esse sentido.\n3. Varie os conectivos ao longo do texto.',
      'Usar um conectivo com sentido errado quebra a lógica: “Choveu muito, portanto o rio secou” não faz sentido.'),
    block('coerencia', 'Coerência: fazer sentido',
      'Coerência é a lógica do texto: as ideias não se contradizem, seguem uma progressão e combinam com o que sabemos do mundo e com a situação comunicativa. Um texto pode ter frases bem ligadas e ainda assim ser incoerente.',
      'Incoerente: “Ele é vegetariano e seu prato preferido é churrasco de picanha.”',
      'O texto precisa ter lógica do começo ao fim.',
      'Se no 1º parágrafo você defende o uso de celular e no último diz que ele deve ser proibido sem explicar a mudança, há incoerência.',
      '1. Leia o texto inteiro.\n2. Veja se alguma ideia contradiz outra.\n3. Confira se há progressão (o texto avança, não gira em círculos).\n4. Veja se o conteúdo combina com o mundo real.',
      'Coesão é a “costura” entre as partes; coerência é o “desenho” fazer sentido. Dá para ter costura bonita num desenho sem pé nem cabeça.'),
    block('revisar', 'Revisando o próprio texto',
      'Ao revisar, procure repetições, pronomes ambíguos, conectivos mal escolhidos, frases muito longas e contradições. Leia em voz alta: onde você tropeça costuma haver um problema de coesão.',
      'Antes: “A escola é importante. A escola ensina. A escola forma cidadãos.” Depois: “A escola é importante, pois ensina e, além disso, forma cidadãos.”',
      'Revise procurando repetições e ligações fracas.',
      'Na redação do ENEM, a competência 4 avalia justamente os mecanismos de coesão.',
      '1. Marque repetições.\n2. Verifique se cada pronome tem referente claro.\n3. Confira o sentido dos conectivos.\n4. Leia em voz alta e ajuste.',
      'Revisar é como conferir uma receita pronta: você prova e corrige o tempero antes de servir.'),
  ],
  questions: [
    mc(1, 'referencial', 'Em “Ana chegou. Ela abriu a sala”, “ela” retoma:', ['a sala', 'Ana', 'nada', 'o verbo'], 1, ['A quem “ela” se refere?', 'Quem chegou?', 'Ana.'], '“Ela” retoma Ana.'),
    mc(1, 'sequencial', 'Qual conectivo indica conclusão?', ['porém', 'portanto', 'além disso', 'por exemplo'], 1, ['Conclusão fecha a ideia.', 'Logo, portanto…', 'Portanto.'], 'Portanto.'),
    tf(1, 'coerencia', 'Um texto bem conectado sempre é coerente.', false, ['Coesão garante lógica?', 'Não necessariamente.', 'Pode haver contradição.'], 'Falso: coesão não garante coerência.'),
    fill(1, 'sequencial', 'Complete com um conectivo de adição: “O projeto é barato. ___, é fácil de aplicar.”', ['Além disso', 'Também', 'Ademais'], ['Soma mais uma vantagem.', 'Adição.', '“Além…”.'], 'Além disso.'),
    match(2, 'sequencial', 'Ligue cada conectivo à relação.', [['no entanto', 'oposição'], ['visto que', 'causa'], ['de modo que', 'consequência'], ['por exemplo', 'exemplificação']], ['No entanto = porém.', 'Visto que = porque.', 'De modo que = por isso.'], 'oposição · causa · consequência · exemplificação.'),
    mc(2, 'coerencia', 'Qual frase é incoerente?', ['Estava com frio, então vesti um casaco.', 'Ele é vegetariano e ama churrasco de picanha.', 'Choveu, por isso a rua molhou.', 'Estudei e fui bem na prova.'], 1, ['Procure contradição.', 'Vegetariano não come carne.', 'Picanha é carne.'], 'Vegetariano e picanha se contradizem.'),
    mc(2, 'referencial', 'Qual reescrita evita a repetição de “escola”?', ['A escola é boa. A escola ensina.', 'A escola é boa e ensina bem.', 'A escola, a escola ensina.', 'Escola boa escola.'], 1, ['Junte as ideias.', 'Use elipse.', 'Uma só menção.'], 'A escola é boa e ensina bem.'),
    order(2, 'sequencial', 'Ordene os conectivos para organizar um parágrafo de três argumentos.', ['Em primeiro lugar', 'Além disso', 'Por fim', 'Portanto'], ['Abre a lista.', 'Soma.', 'Último argumento e conclusão.'], 'Em primeiro lugar → Além disso → Por fim → Portanto.'),
    mc(3, 'referencial', 'Em “Pedro falou com João e ele saiu”, o problema é:', ['falta de conectivo', 'ambiguidade do pronome', 'erro de concordância', 'nenhum'], 1, ['Quem saiu?', 'Pedro ou João?', 'O pronome é ambíguo.'], 'Ambiguidade: “ele” pode ser Pedro ou João.'),
    open(3, 'coerencia', 'Explique a diferença entre coesão e coerência.', 'Coesão são os mecanismos que ligam as partes do texto, como pronomes, sinônimos e conectivos. Coerência é a lógica do sentido: as ideias não se contradizem e fazem sentido juntas. Um texto pode ser coeso e incoerente.', ['coesao', 'coerencia', 'ligam', 'conectivos', 'sentido', 'logica', 'contradicao'], ['O que a coesão faz?', 'O que a coerência garante?', 'Um pode existir sem o outro?'], 'Coesão = ligação; coerência = sentido.'),
  ],
  review: ['Coesão referencial: pronomes, sinônimos, elipse', 'Coesão sequencial: conectivos com o sentido certo', 'Coerência: lógica, progressão, sem contradições', 'Revisar: repetições, pronomes ambíguos, conectivos'],
  relatedQuestions: ['o que é coesão e coerência', 'conectivos para redação', 'como evitar repetição no texto'],
  equivalentQuestions: eqsPt(['coesão', 'coerência', 'conectivos'], ['diferença entre coesão e coerência', 'lista de conectivos', 'conectivos de conclusão', 'conectivos de oposição', 'como não repetir palavras na redação', 'o que é coesão referencial', 'o que é coesão sequencial', 'o que é elipse', 'texto incoerente exemplo', 'competência 4 do enem']),
  commonErrors: ['Repetir a mesma palavra várias vezes.', 'Usar pronomes ambíguos.', 'Escolher conectivos com sentido errado.'],
  sources: FONTES, enem: 'A competência 4 da redação avalia os mecanismos de coesão.',
})

export const variacaoLinguistica = lesson({
  id: 'por-variacao-linguistica', subject: 'portugues', title: 'Variação linguística', levels: [...EF], grade: '6º ano ao Ensino Médio',
  topic: 'Linguagem', subtopic: 'Variedades regionais, sociais, situacionais e históricas',
  aliases: ['variacao linguistica', 'variedades linguisticas', 'preconceito linguistico', 'norma padrao', 'linguagem formal e informal', 'regionalismo', 'girias', 'variacao regional', 'variacao historica'],
  summary: 'Entenda por que falamos de jeitos diferentes, o que é norma-padrão, linguagem formal e informal e o preconceito linguístico.',
  intro: 'Mandioca, aipim ou macaxeira? Todas estão certas! A língua varia — e isso é natural.',
  objective: 'Reconhecer as variações regional, social, situacional e histórica, adequar a linguagem ao contexto e combater o preconceito linguístico.',
  prerequisites: ['por-tipos-generos-textuais'], next: ['por-funcoes-linguagem'],
  skills: { tipos: 'Tipos de variação', adequacao: 'Formal × informal e adequação', norma: 'Norma-padrão', preconceito: 'Preconceito linguístico' },
  blocks: [
    block('tipos', 'Por que a língua varia',
      'A língua muda conforme o lugar (variação regional: mandioca, aipim, macaxeira), o grupo social, a idade e a profissão (variação social: gírias, jargões), a situação (variação situacional: formal ou informal) e o tempo (variação histórica: “vossa mercê” → “vosmecê” → “você”).',
      '“Bergamota” (Sul) × “tangerina” × “mexerica”: a mesma fruta.',
      'Cada lugar, grupo e época fala de um jeito.',
      'Um médico usa termos técnicos com colegas e palavras simples com o paciente.',
      '1. A diferença vem do lugar? Regional.\n2. Do grupo ou idade? Social.\n3. Da situação? Situacional.\n4. Da época? Histórica.',
      'Variar não é “falar errado”: é a língua se adaptando às pessoas e às situações.'),
    block('adequacao', 'Formal, informal e adequação',
      'Linguagem formal é usada em situações públicas e oficiais (entrevista de emprego, redação, documento). Linguagem informal é usada entre pessoas próximas (amigos, família, mensagens). O importante é a adequação: usar a variedade certa para cada situação.',
      'Informal: “E aí, beleza?” · Formal: “Bom dia. Como vai o senhor?”',
      'Cada situação pede um jeito de falar.',
      'Usar gíria numa entrevista de emprego é inadequado; usar linguagem de ofício com os amigos também soa estranho.',
      '1. Pense no interlocutor (quem vai ler/ouvir).\n2. Pense na situação (pública ou íntima).\n3. Escolha formal ou informal.',
      'É como a roupa: terno numa festa na piscina é tão inadequado quanto chinelo num casamento.'),
    block('norma', 'O que é a norma-padrão',
      'Norma-padrão é o conjunto de regras da gramática normativa, usado como referência em textos formais, documentos oficiais, provas e na redação do ENEM. Ela é uma das variedades da língua, com prestígio social, mas não é a única “certa”.',
      'Norma-padrão: “Há muitos problemas.” · Variedade coloquial: “Tem muito problema.”',
      'Norma-padrão = a regra usada em textos formais.',
      'Na redação do ENEM, a competência 1 avalia o domínio da norma-padrão.',
      '1. A situação é formal ou avaliativa? Use a norma-padrão.\n2. Revise concordância, regência, pontuação e ortografia.',
      'Saber a norma-padrão amplia suas possibilidades; não significa desprezar as outras variedades.'),
    block('preconceito', 'Preconceito linguístico',
      'Preconceito linguístico é julgar ou discriminar alguém pelo seu modo de falar (sotaque, vocabulário, construções de sua região ou grupo). Todas as variedades têm regras próprias e permitem comunicar. Respeitar a fala do outro é também respeitar sua origem e sua história.',
      'Rir do sotaque de alguém ou chamar uma forma regional de “errada” são exemplos de preconceito linguístico.',
      'Ninguém fala “errado” por falar diferente.',
      'Um personagem nordestino ridicularizado numa novela só pelo sotaque reforça preconceito.',
      '1. Reconheça que existem várias variedades.\n2. Avalie a adequação à situação, não a pessoa.\n3. Evite piadas e julgamentos sobre sotaques.',
      'Assim como não há “jeito certo” de ser, não há “jeito certo” de falar — há jeitos adequados a cada situação.'),
  ],
  questions: [
    mc(1, 'tipos', '“Mandioca”, “aipim” e “macaxeira” são exemplos de variação:', ['histórica', 'regional', 'situacional', 'de erro'], 1, ['Depende de onde a pessoa mora.', 'Lugar.', 'Regional.'], 'Regional.'),
    mc(1, 'adequacao', 'Qual situação pede linguagem formal?', ['Conversa com amigos', 'Mensagem para a família', 'Entrevista de emprego', 'Grupo da turma'], 2, ['Situação pública e profissional.', 'Precisa de cuidado.', 'Entrevista.'], 'Entrevista de emprego.'),
    tf(1, 'preconceito', 'Falar com sotaque de outra região é falar errado.', false, ['Sotaque é variação.', 'Não é erro.', 'É natural.'], 'Falso: é variação regional.'),
    fill(1, 'norma', 'O conjunto de regras usado em textos formais e na redação do ENEM é a norma-___.', ['padrão', 'padrao'], ['Norma-…', 'Referência oficial.', 'p-a-d-r-ã-o.'], 'Norma-padrão.'),
    match(2, 'tipos', 'Ligue cada exemplo ao tipo de variação.', [['“Vossa mercê” virou “você”', 'histórica'], ['Gírias de adolescentes', 'social'], ['“Bergamota” no Sul', 'regional'], ['Falar diferente com o chefe e com amigos', 'situacional']], ['Mudança no tempo.', 'Grupo/idade.', 'Lugar; situação.'], 'histórica · social · regional · situacional.'),
    mc(2, 'adequacao', 'O que significa “adequação linguística”?', ['Falar sempre na norma-padrão', 'Usar a linguagem apropriada à situação', 'Evitar gírias sempre', 'Falar como os mais velhos'], 1, ['Depende do contexto.', 'Cada situação pede um registro.', 'Apropriado.'], 'Usar a linguagem apropriada à situação.'),
    mc(2, 'norma', 'Na norma-padrão, qual frase está adequada?', ['Tem muito problema.', 'Há muitos problemas.', 'Houveram muitos problemas.', 'Hão muitos problemas.'], 1, ['Haver = existir.', 'Singular.', 'Há.'], 'Há muitos problemas.'),
    mc(3, 'preconceito', 'Qual atitude combate o preconceito linguístico?', ['Corrigir o sotaque dos colegas', 'Rir de formas regionais', 'Respeitar as variedades e avaliar a adequação ao contexto', 'Proibir gírias em qualquer situação'], 2, ['Todas as variedades comunicam.', 'O foco é a situação.', 'Respeito.'], 'Respeitar e avaliar a adequação.'),
    order(2, 'adequacao', 'Ordene os passos para escolher o registro de um texto.', ['Identificar o interlocutor', 'Identificar a situação', 'Escolher formal ou informal', 'Revisar as escolhas de palavras'], ['Quem vai ler?', 'Qual a situação?', 'Escolha e revise.'], 'interlocutor → situação → registro → revisão.'),
    open(3, 'preconceito', 'Por que é um erro dizer que alguém “não sabe falar português” por usar uma variedade regional?', 'Porque a variedade regional é uma forma legítima da língua, com regras próprias, e permite a comunicação. A pessoa sabe falar português; ela usa outra variedade. Julgá-la por isso é preconceito linguístico. O que se pode discutir é a adequação à situação.', ['variedade', 'legitima', 'regras', 'preconceito', 'adequacao', 'comunicacao'], ['A variedade regional tem regras?', 'Ela comunica?', 'Que atitude é julgar a pessoa por isso?'], 'Variedades são legítimas; o critério é a adequação.'),
  ],
  review: ['Variação regional, social, situacional e histórica', 'Adequação: registro formal ou informal conforme a situação', 'Norma-padrão: referência para textos formais (não é a única variedade)', 'Preconceito linguístico: julgar alguém pela fala'],
  relatedQuestions: ['o que é variação linguística', 'o que é preconceito linguístico', 'linguagem formal e informal'],
  equivalentQuestions: eqsPt(['variação linguística', 'preconceito linguístico', 'norma-padrão'], ['tipos de variação linguística', 'o que é variação regional', 'o que é variação histórica', 'diferença entre linguagem formal e informal', 'gíria é errado', 'sotaque é errado', 'mandioca aipim macaxeira', 'o que é adequação linguística', 'variação linguística no enem', 'o que é norma culta']),
  commonErrors: ['Chamar variedades de “erro”.', 'Usar registro informal em textos formais.', 'Confundir norma-padrão com a “única língua certa”.'],
  sources: FONTES, enem: 'Variação linguística e preconceito linguístico são temas frequentes em Linguagens.',
})

export const funcoesLinguagem = lesson({
  id: 'por-funcoes-linguagem', subject: 'portugues', title: 'Funções da linguagem', levels: [...EF], grade: '9º ano e Ensino Médio',
  topic: 'Linguagem', subtopic: 'Referencial, emotiva, conativa, fática, metalinguística e poética',
  aliases: ['funcoes da linguagem', 'funcao referencial', 'funcao emotiva', 'funcao conativa', 'funcao apelativa', 'funcao fatica', 'funcao metalinguistica', 'funcao poetica', 'jakobson', 'elementos da comunicacao'],
  summary: 'Reconheça as seis funções da linguagem pelo elemento da comunicação que cada texto destaca.',
  intro: 'Uma notícia, um poema, um anúncio e um “alô?” ao telefone usam a linguagem de jeitos diferentes. Por quê?',
  objective: 'Relacionar os elementos da comunicação às seis funções da linguagem e identificar a função predominante em diferentes textos.',
  prerequisites: ['por-tipos-generos-textuais', 'por-figuras-linguagem'], next: [],
  skills: { elementos: 'Elementos da comunicação', informativas: 'Referencial e emotiva', relacao: 'Conativa e fática', codigo: 'Metalinguística e poética' },
  blocks: [
    block('elementos', 'Os elementos da comunicação',
      'Toda comunicação tem emissor (quem fala), receptor (quem recebe), mensagem (o que é dito), código (a língua usada), canal (o meio: voz, papel, celular) e referente (o assunto, o contexto). Cada função da linguagem destaca um desses elementos.',
      'Numa ligação: você (emissor), seu amigo (receptor), o recado (mensagem), o português (código), o telefone (canal), o encontro combinado (referente).',
      'Cada função “aponta o holofote” para um elemento.',
      'Um anúncio foca no receptor (você!); um diário foca no emissor (eu).',
      '1. Liste os elementos: emissor, receptor, mensagem, código, canal, referente.\n2. Veja em qual o texto se concentra.\n3. Esse foco indica a função.',
      'É como uma foto: todos estão na cena, mas o foco da câmera está em um deles.'),
    block('informativas', 'Referencial e emotiva',
      'Referencial (ou denotativa): foca no referente; informa de modo objetivo, em 3ª pessoa (notícias, textos científicos). Emotiva (ou expressiva): foca no emissor; expressa sentimentos e opiniões, com 1ª pessoa e exclamações (diários, cartas pessoais, desabafos).',
      'Referencial: “O dengue é transmitido pelo Aedes aegypti.” · Emotiva: “Que saudade eu sinto de você!”',
      'Informar = referencial. Desabafar = emotiva.',
      'Notícia do jornal: referencial. Post “Estou tão feliz hoje!”: emotiva.',
      '1. O texto informa com objetividade? Referencial.\n2. Expressa o que o autor sente? Emotiva (muito “eu”).',
      'A referencial “some com o autor”; a emotiva coloca o autor no centro.'),
    block('relacao', 'Conativa e fática',
      'Conativa (ou apelativa): foca no receptor; tenta convencer ou influenciar, com imperativos, vocativos e “você” (anúncios, discursos, campanhas). Fática: foca no canal; testa, inicia, mantém ou encerra o contato (“Alô?”, “Tá me ouvindo?”, “Oi, tudo bem?”).',
      'Conativa: “Beba mais água!” · Fática: “Alô? Alô? Está me ouvindo?”',
      'Convencer = conativa. Testar o contato = fática.',
      'Propaganda: “Compre já e ganhe desconto!” (conativa).',
      '1. O texto dá ordens ou tenta convencer você? Conativa.\n2. Só verifica se a comunicação está funcionando? Fática.',
      'Na fática a mensagem quase não importa; o que importa é o “canal aberto”, como o “hum-hum” ao telefone.'),
    block('codigo', 'Metalinguística e poética',
      'Metalinguística: foca no código; a linguagem fala dela mesma (dicionários, gramáticas, um poema sobre fazer poemas, um filme sobre cinema). Poética: foca na mensagem, em sua forma: ritmo, rima, sonoridade, figuras (poemas, letras de música, slogans criativos).',
      'Metalinguística: “Substantivo é a palavra que nomeia seres.” · Poética: “Batatinha quando nasce / espalha a rama pelo chão.”',
      'Linguagem falando da linguagem = metalinguística. Beleza da forma = poética.',
      'Um verbete de dicionário é metalinguístico; um trava-línguas brinca com a forma (poética).',
      '1. O texto explica ou comenta a própria linguagem/código? Metalinguística.\n2. Chama atenção para o som, o ritmo e a forma? Poética.',
      'Um texto pode ter várias funções; a questão é qual predomina. Um anúncio com rima pode ser poético e conativo ao mesmo tempo.'),
  ],
  questions: [
    mc(1, 'informativas', 'Uma notícia de jornal tem função predominante:', ['emotiva', 'referencial', 'fática', 'poética'], 1, ['Informa com objetividade.', 'Foca no assunto.', 'Referencial.'], 'Referencial.'),
    mc(1, 'relacao', '“Alô? Está me ouvindo?” é um exemplo de função:', ['conativa', 'fática', 'metalinguística', 'emotiva'], 1, ['Testa o contato.', 'Foca no canal.', 'Fática.'], 'Fática.'),
    tf(1, 'relacao', 'Anúncios publicitários costumam ter função conativa.', true, ['Querem convencer o leitor.', 'Foco no receptor.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'codigo', 'Um verbete de dicionário tem função ___ (a linguagem explicando a linguagem).', ['metalinguística', 'metalinguistica'], ['Fala do código.', 'Meta…', 'Metalinguística.'], 'Metalinguística.'),
    match(2, 'elementos', 'Ligue cada função ao elemento que ela destaca.', [['emotiva', 'emissor'], ['conativa', 'receptor'], ['fática', 'canal'], ['metalinguística', 'código']], ['Emotiva = eu.', 'Conativa = você.', 'Fática = contato; metalinguística = língua.'], 'emissor · receptor · canal · código.'),
    mc(2, 'informativas', '“Que tristeza! Hoje tudo deu errado para mim.” A função é:', ['referencial', 'emotiva', 'fática', 'conativa'], 1, ['Expressa sentimentos.', '1ª pessoa, exclamação.', 'Emotiva.'], 'Emotiva.'),
    mc(2, 'codigo', 'Um poema cheio de rimas e ritmo, que chama atenção para a própria forma, tem função:', ['poética', 'referencial', 'fática', 'conativa'], 0, ['Foco na forma da mensagem.', 'Ritmo, rima.', 'Poética.'], 'Poética.'),
    mc(3, 'codigo', 'Um poema cujo tema é “como escrever um poema” tem, além da poética, função:', ['fática', 'metalinguística', 'referencial', 'conativa'], 1, ['O poema fala de si.', 'Linguagem sobre linguagem.', 'Metalinguística.'], 'Metalinguística.'),
    order(2, 'elementos', 'Ordene os passos para identificar a função predominante.', ['Ler o texto e identificar o gênero', 'Listar os elementos da comunicação', 'Ver qual elemento está em destaque', 'Nomear a função correspondente'], ['Comece pelo gênero.', 'Depois os elementos.', 'O foco indica a função.'], 'gênero → elementos → foco → função.'),
    open(3, 'relacao', 'Por que uma campanha “Vacine-se! Proteja quem você ama” tem função conativa?', 'Porque ela se dirige diretamente ao receptor, usando verbos no imperativo (“vacine-se”, “proteja”) e o pronome “você”, com a intenção de convencê-lo a agir. O foco está no receptor.', ['receptor', 'imperativo', 'convencer', 'voce', 'foco'], ['Para quem a mensagem é dirigida?', 'Que modo verbal aparece?', 'Qual é o objetivo?'], 'Imperativo + “você” + intenção de convencer = conativa.'),
  ],
  review: ['Elementos: emissor, receptor, mensagem, código, canal, referente', 'Referencial (referente) · emotiva (emissor)', 'Conativa (receptor) · fática (canal)', 'Metalinguística (código) · poética (mensagem)'],
  relatedQuestions: ['quais são as funções da linguagem', 'o que é função conativa', 'o que é função metalinguística'],
  equivalentQuestions: eqsPt(['funções da linguagem', 'função conativa', 'função poética'], ['o que é função referencial', 'o que é função emotiva', 'o que é função fática', 'função apelativa exemplo', 'função da linguagem da propaganda', 'função da linguagem da notícia', 'elementos da comunicação', 'jakobson funções da linguagem', 'poema sobre poema é metalinguagem', 'como identificar a função predominante']),
  commonErrors: ['Confundir conativa (receptor) com emotiva (emissor).', 'Achar que um texto tem uma única função.', 'Confundir poética com “texto bonito” em geral.'],
  sources: FONTES, enem: 'Funções da linguagem aparecem em anúncios, poemas, tirinhas e textos informativos.',
})

export const semantica = lesson({
  id: 'por-semantica', subject: 'portugues', title: 'Sinônimos, antônimos, homônimos e parônimos', levels: ['fund1', 'fund2', 'medio'], grade: '5º ao 9º ano',
  topic: 'Linguagem', subtopic: 'Semântica: sentido das palavras, denotação e conotação',
  aliases: ['sinonimos', 'antonimos', 'homonimos', 'paronimos', 'homofonos', 'homografos', 'denotacao', 'conotacao', 'polissemia', 'comprimento ou cumprimento', 'sessao secao cessao'],
  summary: 'Use sinônimos e antônimos, diferencie homônimos e parônimos e entenda denotação, conotação e polissemia.',
  intro: 'Cumprimento ou comprimento? Sessão, seção ou cessão? Palavras parecidas, sentidos bem diferentes.',
  objective: 'Empregar sinônimos e antônimos, distinguir homônimos (homófonos e homógrafos) de parônimos, e reconhecer sentido denotativo, conotativo e polissemia.',
  prerequisites: ['por-classes-gramaticais'], next: ['por-figuras-linguagem'],
  skills: { sinonimos: 'Sinônimos e antônimos', homonimos: 'Homônimos', paronimos: 'Parônimos', sentido: 'Denotação, conotação e polissemia' },
  blocks: [
    block('sinonimos', 'Sinônimos e antônimos',
      'Sinônimos têm sentidos semelhantes (casa/lar, bonito/belo); antônimos têm sentidos opostos (alto/baixo, rico/pobre). Poucos sinônimos são totalmente iguais: o contexto decide o melhor (“lar” é mais afetivo que “casa”).',
      'Rápido × veloz (sinônimos) · rápido × lento (antônimos).',
      'Sinônimo = parecido. Antônimo = contrário.',
      'Na redação, sinônimos evitam repetir a mesma palavra.',
      '1. Ache a palavra.\n2. Pense em outra com sentido parecido (sinônimo) ou contrário (antônimo).\n3. Teste na frase: o sentido se mantém?',
      'Nem todo sinônimo cabe em qualquer frase: “Ele tem um grande coração” não vira “Ele tem um enorme coração” sem mudar um pouco o tom.'),
    block('homonimos', 'Homônimos: iguais no som ou na escrita',
      'Homófonos têm o mesmo som e escrita diferente: concerto (musical) × conserto (reparo); cela (prisão) × sela (do cavalo); sessão (reunião) × seção (departamento) × cessão (ato de ceder). Homógrafos têm a mesma escrita e pronúncia diferente: colher (verbo, “ê”) × colher (talher, “é”). Homônimos perfeitos são iguais na escrita e no som: são (sadio) × são (santo) × são (verbo ser).',
      'O conserto do piano atrasou o concerto.',
      'Mesmo som, sentidos diferentes → cuidado na escrita!',
      'Placa: “Seção de brinquedos” (setor da loja) × “Sessão de cinema” (horário).',
      '1. Veja o sentido que você quer.\n2. Escolha a grafia correspondente.\n3. Em dúvida, consulte o dicionário.',
      'Homônimos são como gêmeos idênticos com nomes diferentes: parecem iguais, mas são pessoas diferentes.'),
    block('paronimos', 'Parônimos: parecidos, mas diferentes',
      'Parônimos são palavras parecidas na escrita e na pronúncia, mas não iguais: comprimento (medida) × cumprimento (saudação); descrição (ato de descrever) × discrição (ser discreto); eminente (importante) × iminente (prestes a acontecer); emigrar (sair do país) × imigrar (entrar no país).',
      'O perigo é iminente. · Ele é um médico eminente. · Meça o comprimento da mesa.',
      'Parônimos se parecem, mas não são iguais — e trocam o sentido.',
      '“Os imigrantes chegaram ao Brasil” (entraram) × “emigraram da Itália” (saíram).',
      '1. Lembre de uma frase-âncora para cada par.\n2. Pense no sentido antes de escrever.\n3. Revise os pares clássicos.',
      'Dica: EMigrar = Exit (sair); IMigrar = In (entrar). CUMprimento = CUMprimentar alguém.'),
    block('sentido', 'Denotação, conotação e polissemia',
      'Denotação é o sentido literal, de dicionário (“O gato subiu no telhado”). Conotação é o sentido figurado, que depende do contexto (“Aquele ator é um gato” = bonito). Polissemia é quando uma palavra tem vários sentidos relacionados: “pé” de pessoa, pé da mesa, pé de alface.',
      '“Ele tem um coração de pedra” (conotação: insensível) · “A pedra rolou” (denotação).',
      'Literal = denotação. Figurado = conotação.',
      'Numa música: “Você é o meu sol” — conotação; ninguém é uma estrela de verdade.',
      '1. Leia a palavra na frase.\n2. O sentido é o do dicionário? Denotação.\n3. É figurado, criativo? Conotação.\n4. A palavra tem vários sentidos relacionados? Polissemia.',
      'Na polissemia os sentidos se relacionam (“pé” sempre sustenta algo); nos homônimos, não (“manga” fruta × manga da camisa).'),
  ],
  questions: [
    mc(1, 'sinonimos', 'Qual é o antônimo de “rápido”?', ['veloz', 'ligeiro', 'lento', 'ágil'], 2, ['Antônimo = contrário.', 'O oposto de rápido.', 'Lento.'], 'Lento.'),
    mc(1, 'paronimos', 'Qual frase está correta?', ['Meça o cumprimento da mesa.', 'Meça o comprimento da mesa.', 'Dê um comprimento ao professor.', 'O comprimento de bom dia.'], 1, ['Medida = comprimento.', 'Saudação = cumprimento.', 'Mesa → medida.'], 'Comprimento (medida).'),
    tf(1, 'homonimos', '“Concerto” (musical) e “conserto” (reparo) são homófonos.', true, ['Mesmo som?', 'Sim.', 'Escrita diferente.'], 'Verdadeiro.'),
    fill(1, 'sentido', 'O sentido literal, de dicionário, chama-se ___.', ['denotação', 'denotativo', 'denotacao'], ['Oposto de conotação.', 'D…', 'Denotação.'], 'Denotação.'),
    match(2, 'homonimos', 'Ligue cada palavra ao sentido.', [['sessão', 'reunião ou horário (de cinema)'], ['seção', 'departamento, setor'], ['cessão', 'ato de ceder'], ['cela', 'quarto de prisão']], ['Sessão de cinema.', 'Seção da loja.', 'Cessão de direitos.'], 'sessão · seção · cessão · cela.'),
    mc(2, 'paronimos', '“O perigo é ___: a ponte pode cair a qualquer momento.”', ['eminente', 'iminente', 'emigrante', 'imigrante'], 1, ['Prestes a acontecer.', 'Iminente.', 'Eminente = importante.'], 'Iminente.'),
    mc(2, 'sentido', 'Em “Ele tem um coração de pedra”, a palavra “pedra” está em sentido:', ['denotativo', 'conotativo', 'técnico', 'científico'], 1, ['O coração é de pedra de verdade?', 'Não.', 'Figurado.'], 'Conotativo (insensível).'),
    mc(3, 'paronimos', 'Sobre emigrar × imigrar, qual frase está correta?', ['Meus avós emigraram para o Brasil em 1950.', 'Meus avós imigraram para o Brasil em 1950.', 'Meus avós imigraram da Itália.', 'Meus avós emigraram no Brasil.'], 1, ['Chegaram ao Brasil.', 'Entrar = imigrar.', 'IMigrar = In.'], 'Imigraram para o Brasil (e emigraram da Itália).'),
    order(2, 'sentido', 'Ordene os sentidos de “pé” do mais literal para o mais distante.', ['pé da pessoa', 'pé da mesa', 'pé de alface', 'estar em pé de guerra'], ['Parte do corpo primeiro.', 'Depois objetos que “sustentam”.', 'Por fim a expressão figurada.'], 'corpo → mesa → planta → expressão.'),
    open(3, 'sentido', 'Explique a diferença entre polissemia e homonímia com exemplos.', 'Na polissemia, uma mesma palavra tem vários sentidos relacionados entre si, como “pé” (da pessoa, da mesa, de alface), sempre com a ideia de base. Na homonímia, as palavras coincidem no som e/ou na escrita, mas os sentidos não têm relação, como “manga” (fruta) e “manga” (da camisa).', ['relacionados', 'sem relacao', 'polissemia', 'homonimia', 'exemplo'], ['Os sentidos se relacionam?', 'Dê um exemplo de cada.', 'Pé × manga.'], 'Polissemia: sentidos relacionados · homonímia: sentidos independentes.'),
  ],
  review: ['Sinônimos (parecidos) × antônimos (opostos)', 'Homófonos (concerto/conserto) · homógrafos (colher/colher)', 'Parônimos: comprimento/cumprimento, eminente/iminente, emigrar/imigrar', 'Denotação (literal) × conotação (figurado) · polissemia'],
  relatedQuestions: ['o que são parônimos', 'comprimento ou cumprimento', 'diferença entre denotação e conotação'],
  equivalentQuestions: eqsPt(['sinônimos e antônimos', 'homônimos', 'parônimos', 'denotação e conotação'], ['sessão seção ou cessão', 'concerto ou conserto', 'eminente ou iminente', 'emigrar ou imigrar', 'descrição ou discrição', 'o que é polissemia', 'o que são homófonos', 'o que são homógrafos', 'sentido figurado', 'sentido literal']),
  commonErrors: ['Trocar comprimento por cumprimento.', 'Confundir sessão, seção e cessão.', 'Confundir polissemia com homonímia.'],
  sources: FONTES,
})
