// LOTE 2 — PORTUGUÊS · ortografia e gramática. Conteúdo original do LUMI (Novo Acordo Ortográfico).
import { block, eqsPt, fill, lesson, match, mc, open, order, SRC, tf } from '../dsl'

const FONTES = [SRC.bncc('Língua Portuguesa — Anos Finais'), SRC.web('Vocabulário Ortográfico da Língua Portuguesa (VOLP)', 'https://www.academia.org.br/nossa-lingua/busca-no-vocabulario', 'Academia Brasileira de Letras', 'instituicao'), SRC.autoral()]
const EF = ['fund2', 'medio'] as const

export const acentuacao = lesson({
  id: 'por-acentuacao', subject: 'portugues', title: 'Acentuação gráfica', levels: ['fund1', 'fund2'], grade: '5º ao 7º ano',
  topic: 'Ortografia', subtopic: 'Sílaba tônica e regras de acentuação',
  aliases: ['acentuacao', 'acento agudo', 'acento circunflexo', 'oxitona', 'paroxitona', 'proparoxitona', 'silaba tonica', 'regras de acentuacao', 'novo acordo ortografico acento'],
  summary: 'Descubra a sílaba tônica, classifique as palavras e aplique as principais regras de acentuação.',
  intro: 'Sábia, sabia e sabiá: três palavras diferentes só por causa da sílaba mais forte e do acento!',
  objective: 'Identificar a sílaba tônica, classificar palavras em oxítonas, paroxítonas e proparoxítonas e aplicar as regras de acentuação, incluindo mudanças do Novo Acordo.',
  prerequisites: [], next: ['por-ortografia-duvidas'],
  skills: { tonica: 'Sílaba tônica e classificação', oxitonas: 'Oxítonas e monossílabos', paroxitonas: 'Paroxítonas e proparoxítonas', acordo: 'Acentos diferenciais e Novo Acordo' },
  blocks: [
    block('tonica', 'A sílaba mais forte',
      'Toda palavra com mais de uma sílaba tem uma sílaba pronunciada com mais força: a sílaba tônica. Pela posição dela, a palavra é oxítona (última sílaba: ca-fé), paroxítona (penúltima: me-sa) ou proparoxítona (antepenúltima: lâm-pa-da).',
      'sa-bi-á (oxítona) · sa-bi-a (paroxítona) · sá-bi-a (proparoxítona).',
      'Fale a palavra devagar e descubra qual pedaço sai mais forte.',
      'Chame alguém do outro lado da rua: “Ma-RI-a!” — a sílaba que você grita é a tônica.',
      '1. Separe as sílabas.\n2. Fale a palavra e ache a sílaba mais forte.\n3. Conte de trás para frente: última = oxítona; penúltima = paroxítona; antepenúltima = proparoxítona.',
      'Nem toda sílaba tônica leva acento: “mesa” tem tônica em “me”, mas não é acentuada. O acento só aparece quando a regra manda.'),
    block('oxitonas', 'Oxítonas e monossílabos tônicos',
      'Acentuam-se as oxítonas terminadas em a(s), e(s), o(s), em e ens: sofá, café, cipó, também, parabéns. Também os monossílabos tônicos terminados em a(s), e(s), o(s): pá, pé, nó, três. Ditongos abertos éi, éu, ói em oxítonas e monossílabos continuam acentuados: papéis, chapéu, herói, céu.',
      'maracujá, você, avô, armazém · mas: caju, tatu, anel (não se acentuam).',
      'Oxítona terminada em a, e, o, em → leva acento.',
      'Compare “caqui” (sem acento, termina em i) com “jacaré” (acento, termina em e).',
      '1. A palavra é oxítona?\n2. Termina em a, e, o, em ou ens (com ou sem s)?\n3. Se sim, acentue a tônica.',
      'Nas oxítonas a regra é “acentua as terminadas em A, E, O, EM”; nas paroxítonas é quase o contrário: essas terminações NÃO recebem acento (mesa, bote).'),
    block('paroxitonas', 'Paroxítonas e proparoxítonas',
      'TODAS as proparoxítonas são acentuadas: lâmpada, música, pássaro, Matemática. Paroxítonas são acentuadas quando terminam em l, n, r, x, ps, ã(s), ão(s), i(s), us, um, uns ou ditongo: fácil, hífen, açúcar, tórax, bíceps, ímã, órfão, táxi, vírus, álbum, história.',
      'fácil, útil, caráter, pônei · mas: mesa, casa, jovem (sem acento).',
      'Proparoxítona sempre tem acento.',
      'Na aula de Geografia: “América”, “África” e “Ásia” são proparoxítonas — todas acentuadas.',
      '1. Proparoxítona? Acentue sempre.\n2. Paroxítona? Veja a terminação: l, n, r, x, ps, ã, ão, i, us, um, ditongo → acentue.\n3. Terminou em a, e, o, em? Não acentue.',
      'Por isso “jovem” (paroxítona em -em) não tem acento, mas “também” (oxítona em -em) tem.'),
    block('acordo', 'Acentos diferenciais e o Novo Acordo',
      'O Novo Acordo Ortográfico retirou alguns acentos: ideia, assembleia, heroico, jiboia (ditongos abertos ei/oi em paroxítonas) e voo, enjoo, leem, creem (vogais repetidas). Continuam alguns acentos diferenciais: pôr (verbo) × por (preposição) e pôde (passado) × pode (presente).',
      'Antes: idéia, vôo, lêem → Hoje: ideia, voo, leem.',
      'Ideia e voo não têm mais acento; pôr e pôde continuam com acento.',
      'Num texto: “Ontem ele não pôde vir; hoje ele pode.” O acento mostra o tempo verbal.',
      '1. É paroxítona com “ei” ou “oi” aberto? Sem acento (ideia).\n2. Tem “oo” ou “ee”? Sem acento (voo, leem).\n3. É “pôr” verbo ou “pôde” passado? Com acento.',
      'Atenção: “herói” (oxítona) ainda tem acento, mas “heroico” (paroxítona) não. A regra depende da posição da sílaba tônica.'),
  ],
  questions: [
    mc(1, 'tonica', 'Em “sabiá”, a sílaba tônica é:', ['sa', 'bi', 'á', 'não tem'], 2, ['Fale a palavra.', 'A força está no final.', 'Última sílaba.'], 'sa-bi-Á: oxítona.'),
    mc(1, 'paroxitonas', 'Qual palavra é proparoxítona?', ['cadeira', 'lâmpada', 'café', 'jovem'], 1, ['Tônica na antepenúltima.', 'LÂM-pa-da.', 'Proparoxítona sempre tem acento.'], 'Lâmpada.'),
    tf(1, 'paroxitonas', 'Todas as proparoxítonas são acentuadas.', true, ['É uma regra sem exceção.', 'música, pássaro, lâmpada…', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'acordo', 'Escreva “idéia” de acordo com o Novo Acordo.', ['ideia'], ['Paroxítona com ditongo “ei”.', 'O acento caiu.', 'Sem acento.'], 'Ideia (sem acento).'),
    match(2, 'tonica', 'Ligue cada palavra à classificação.', [['café', 'oxítona'], ['mesa', 'paroxítona'], ['música', 'proparoxítona']], ['Ache a sílaba forte.', 'ca-FÉ, ME-sa.', 'MÚ-si-ca.'], 'oxítona · paroxítona · proparoxítona.'),
    mc(2, 'oxitonas', 'Qual oxítona está escrita corretamente?', ['cajú', 'parabens', 'jacaré', 'anél'], 2, ['Oxítonas em a, e, o, em(s) levam acento.', 'Caju termina em u.', 'Jacaré termina em e.'], 'Jacaré. (caju, parabéns, anel)'),
    mc(2, 'paroxitonas', 'Qual paroxítona precisa de acento?', ['casa', 'facil', 'bote', 'jovem'], 1, ['Veja a terminação.', 'Termina em l.', 'Paroxítona em l → acento.'], 'Fácil.'),
    mc(3, 'acordo', 'Qual frase está correta?', ['Ele não pode vir ontem.', 'Ele não pôde vir ontem.', 'Ele não póde vir ontem.', 'Ele não podê vir ontem.'], 1, ['“Ontem” indica passado.', 'Passado de poder: pôde.', 'Acento diferencial.'], 'Pôde (passado) × pode (presente).'),
    order(2, 'tonica', 'Ordene os passos para decidir se uma palavra tem acento.', ['Separar as sílabas', 'Achar a sílaba tônica', 'Classificar (oxítona, paroxítona, proparoxítona)', 'Aplicar a regra da terminação'], ['Comece separando.', 'Depois ache a forte.', 'Por fim, a regra.'], 'Separar → tônica → classificar → regra.'),
    open(3, 'oxitonas', 'Explique por que “também” tem acento e “jovem” não.', 'Porque “também” é oxítona (a sílaba tônica é a última) terminada em -em, e as oxítonas em -em são acentuadas. Já “jovem” é paroxítona (JO-vem) terminada em -em, e paroxítonas com essa terminação não recebem acento.', ['oxitona', 'paroxitona', 'ultima', 'penultima', 'tonica', 'em'], ['Onde está a sílaba tônica em cada uma?', 'Qual é a classificação?', 'Qual regra vale para -em?'], 'A mesma terminação segue regras diferentes conforme a posição da tônica.'),
  ],
  review: ['Tônica: última (oxítona), penúltima (paroxítona), antepenúltima (proparoxítona)', 'Oxítonas em a, e, o, em(s) → acento (café, também)', 'Proparoxítonas: sempre · paroxítonas em l, n, r, x, i, us, ão, ditongo…', 'Novo Acordo: ideia, heroico, voo, leem · pôr, pôde mantêm acento'],
  relatedQuestions: ['regras de acentuação', 'o que é oxítona paroxítona e proparoxítona', 'ideia tem acento'],
  equivalentQuestions: eqsPt(['acentuação', 'sílaba tônica', 'oxítona e paroxítona'], ['quando usar acento agudo', 'quando usar acento circunflexo', 'ideia tem acento', 'voo tem acento', 'por que jovem não tem acento', 'pôde ou pode', 'pôr ou por', 'como achar a sílaba tônica', 'proparoxítona sempre tem acento', 'heroico tem acento', 'o que mudou com o novo acordo ortográfico']),
  commonErrors: ['Acentuar paroxítonas terminadas em a, e, o, em (jóvem).', 'Manter acentos que caíram no Novo Acordo (idéia, vôo).', 'Esquecer o acento de oxítonas em -em (tambem).'],
  sources: FONTES,
})

export const ortografiaDuvidas = lesson({
  id: 'por-ortografia-duvidas', subject: 'portugues', title: 'Porquês e dúvidas de ortografia', levels: [...EF], grade: '6º ao 9º ano',
  topic: 'Ortografia', subtopic: 'Por que, porque, por quê, porquê; mal × mau; há × a; mas × mais',
  aliases: ['porques', 'por que ou porque', 'uso dos porques', 'mal ou mau', 'ha ou a', 'mas ou mais', 'onde ou aonde', 'duvidas de portugues', 'ortografia'],
  summary: 'Acerte de uma vez os quatro porquês, mal × mau, há × a, mas × mais e onde × aonde.',
  intro: 'Por que é tão difícil saber qual porquê usar? Porque ninguém mostrou o truque! Vamos lá.',
  objective: 'Usar corretamente os quatro porquês e resolver dúvidas frequentes (mal/mau, há/a, mas/mais, onde/aonde) com testes práticos.',
  prerequisites: ['por-acentuacao'], next: ['por-pontuacao'],
  skills: { porques: 'Os quatro porquês', malmau: 'Mal × mau', haa: 'Há × a (tempo)', masmais: 'Mas × mais e onde × aonde' },
  blocks: [
    block('porques', 'Os quatro porquês',
      '“Por que” (separado, sem acento): perguntas e quando equivale a “pelo qual/pela qual” (Por que você chegou tarde?). “Porque” (junto): resposta, explicação — equivale a “pois” (Cheguei tarde porque choveu). “Por quê” (separado, com acento): no fim da frase, antes de ponto (Você chegou tarde por quê?). “Porquê” (junto, com acento): substantivo, “o motivo”, vem com artigo (Não sei o porquê do atraso).',
      'Por que você riu? · Ri porque a piada era boa. · Riu por quê? · Quero saber o porquê.',
      'Pergunta: por que. Resposta: porque. Final da frase: por quê. “O motivo”: o porquê.',
      'Numa conversa: — Por que você não veio? — Porque estava doente. — Doente por quê? — Não sei o porquê, mas melhorei.',
      '1. É pergunta (no início ou meio)? por que.\n2. Dá para trocar por “pois”? porque.\n3. Está antes do ponto final/interrogação? por quê.\n4. Vem com “o” (o motivo)? porquê.',
      'Teste do “pois”: se “pois” encaixa, é “porque” junto. Teste do artigo: se tem “o” antes, é “porquê” substantivo.'),
    block('malmau', 'Mal ou mau?',
      '“Mau” é o oposto de “bom” (adjetivo): lobo mau, mau humor. “Mal” é o oposto de “bem” (advérbio) ou um substantivo (o mal, uma doença): Dormi mal. O mal venceu? Também pode ser conjunção (“assim que”): Mal cheguei, começou a chover.',
      'Ele é um mau aluno? Não: ele está indo mal nas provas.',
      'Troque por bom/bem: “bom” → mau; “bem” → mal.',
      'Na fila do lanche: “Esse sanduíche é mau” (errado: o certo é “ruim”, oposto de bom) · “Esse sanduíche fez mal” (oposto de fez bem).',
      '1. Troque a palavra por “bom” ou “bem”.\n2. Encaixou “bom”? Use mau.\n3. Encaixou “bem”? Use mal.',
      'É o mesmo par de opostos: bom × mau, bem × mal. Lembrar do contrário resolve.'),
    block('haa', 'Há ou a (tempo)?',
      '“Há” (verbo haver) indica tempo passado — equivale a “faz”: Moro aqui há dois anos. “A” indica tempo futuro ou distância: Daqui a dois dias; A escola fica a 3 km.',
      'Há 5 anos comecei a estudar música. Daqui a 5 anos quero me formar.',
      'Passado → há. Futuro ou distância → a.',
      'Mensagem: “Cheguei há 10 minutos” (passado) · “Chego daqui a 10 minutos” (futuro).',
      '1. Troque por “faz”.\n2. Fez sentido? Use há.\n3. É futuro ou distância? Use a.',
      '“Há dois anos atrás” é redundante: “há” já indica passado. Diga “há dois anos” ou “dois anos atrás”.'),
    block('masmais', 'Mas × mais · onde × aonde',
      '“Mas” indica oposição, como “porém”: Estudei, mas não passei. “Mais” indica quantidade ou intensidade, oposto de “menos”: Quero mais suco. “Onde” indica lugar em que se está (verbos sem movimento): Onde você mora? “Aonde” indica lugar para onde se vai (verbos de movimento com “a”): Aonde você vai?',
      'Queria ir, mas choveu. · Ela é a mais alta. · Onde está a chave? · Aonde vamos no sábado?',
      'Mas = porém. Mais = oposto de menos. Aonde = para onde.',
      '“Aonde você vai?” (vai a algum lugar) × “Onde você está?” (está em algum lugar).',
      '1. Troque por “porém”: deu certo? mas.\n2. Troque por “menos”: faz sentido o oposto? mais.\n3. Tem ideia de movimento para um lugar? aonde; senão, onde.',
      'Quem vai, vai A algum lugar → A + onde = aonde. Quem está, está EM algum lugar → onde.'),
  ],
  questions: [
    mc(1, 'porques', '___ você não veio à aula?', ['Porque', 'Por que', 'Porquê', 'Por quê'], 1, ['É uma pergunta.', 'Está no início.', 'Separado e sem acento.'], 'Por que (pergunta).'),
    mc(1, 'porques', 'Não fui ___ estava doente.', ['por que', 'porque', 'por quê', 'porquê'], 1, ['É uma explicação.', 'Troque por “pois”.', 'Junto e sem acento.'], 'Porque (= pois).'),
    fill(1, 'malmau', 'Complete com mal ou mau: “O lobo ___ assustou a Chapeuzinho.”', ['mau'], ['Troque por bom ou bem.', '“O lobo bom”.', 'Oposto de bom = mau.'], 'Mau (oposto de bom).'),
    tf(1, 'haa', '“Moro aqui a dois anos” está correto.', false, ['É passado?', 'Troque por “faz”.', 'Passado → há.'], 'Falso: há dois anos.'),
    match(2, 'porques', 'Ligue cada frase ao porquê correto.', [['Você saiu ___?', 'por quê'], ['Saí ___ estava cansado.', 'porque'], ['Não entendi o ___ da briga.', 'porquê'], ['___ o céu é azul?', 'por que']], ['Final da frase: acento.', '“Pois”: junto.', 'Com artigo “o”: substantivo.'], 'por quê · porque · porquê · por que.'),
    mc(2, 'masmais', 'Qual frase está correta?', ['Queria ir, mais choveu.', 'Queria ir, mas choveu.', 'Quero mas suco.', 'Ele é o mas alto.'], 1, ['Oposição = porém.', 'Porém = mas.', 'Quantidade = mais.'], 'Queria ir, mas choveu.'),
    mc(2, 'masmais', '___ você vai no fim de semana?', ['Onde', 'Aonde', 'Donde', 'Adonde'], 1, ['Verbo ir = movimento.', 'Vai A algum lugar.', 'A + onde.'], 'Aonde você vai?'),
    mc(3, 'haa', 'Qual frase NÃO tem redundância?', ['Há dois anos atrás mudei.', 'Mudei há dois anos.', 'Há dois anos atrás que mudei.', 'A dois anos atrás mudei.'], 1, ['“Há” já indica passado.', '“Atrás” repete a ideia.', 'Use só um dos dois.'], 'Mudei há dois anos.'),
    order(2, 'porques', 'Ordene um diálogo usando os porquês corretamente.', ['— Por que você está rindo?', '— Porque lembrei de uma piada.', '— Qual piada? Você riu por quê?', '— Nem sei explicar o porquê!'], ['Começa a pergunta.', 'Depois a resposta com “pois”.', 'O substantivo vem por último.'], 'por que → porque → por quê → o porquê.'),
    open(3, 'malmau', 'Explique a diferença entre “Ele se comportou mal” e “Ele é um mau aluno”.', 'Em “se comportou mal”, “mal” é advérbio, oposto de “bem” (comportou bem × mal). Em “um mau aluno”, “mau” é adjetivo, oposto de “bom” (um bom aluno × um mau aluno).', ['bem', 'bom', 'adverbio', 'adjetivo', 'oposto'], ['Troque por bem ou bom.', 'Qual encaixa em cada frase?', 'Qual é a classe de cada palavra?'], 'mal ↔ bem · mau ↔ bom.'),
  ],
  review: ['Por que (pergunta) · porque (= pois) · por quê (fim de frase) · porquê (= o motivo)', 'mau ↔ bom · mal ↔ bem', 'há = faz (passado) · a = futuro/distância', 'mas = porém · mais ↔ menos · aonde = para onde'],
  relatedQuestions: ['uso dos porquês', 'mal ou mau', 'há ou a'],
  equivalentQuestions: eqsPt(['porquês', 'por que e porque', 'mal e mau'], ['quando usar por que separado', 'quando usar porque junto', 'quando usar por quê com acento', 'o que é porquê substantivo', 'diferença entre mal e mau', 'há dois anos ou a dois anos', 'daqui há ou daqui a', 'mas ou mais', 'onde ou aonde', 'há dois anos atrás está certo']),
  commonErrors: ['Usar “porque” em perguntas.', 'Escrever “daqui há” para futuro.', 'Trocar “mas” por “mais”.'],
  sources: FONTES,
})

export const pontuacao = lesson({
  id: 'por-pontuacao', subject: 'portugues', title: 'Pontuação e uso da vírgula', levels: [...EF], grade: '6º ao 9º ano',
  topic: 'Gramática', subtopic: 'Sinais de pontuação e regras da vírgula',
  aliases: ['pontuacao', 'virgula', 'uso da virgula', 'sinais de pontuacao', 'ponto final', 'dois pontos', 'travessao', 'vocativo virgula', 'aposto'],
  summary: 'Use ponto, interrogação, exclamação, dois-pontos, travessão e, principalmente, a vírgula no lugar certo.',
  intro: '“Vamos comer, crianças!” e “Vamos comer crianças!” — uma vírgula salva vidas.',
  objective: 'Empregar os sinais de pontuação conforme a intenção do texto e usar a vírgula nos casos principais, evitando separar sujeito de verbo.',
  prerequisites: ['por-sujeito-predicado'], next: ['por-classes-gramaticais'],
  skills: { sinais: 'Sinais de pontuação', virgula: 'Vírgula em enumerações, vocativo e aposto', proibida: 'Onde NÃO usar vírgula', sentido: 'Pontuação e sentido' },
  blocks: [
    block('sinais', 'Os principais sinais',
      'Ponto final (.) encerra frases declarativas. Interrogação (?) marca perguntas diretas. Exclamação (!) expressa emoção, surpresa ou ordem. Dois-pontos (:) anunciam uma explicação, enumeração ou fala. Travessão (—) marca fala em diálogos ou destaca uma explicação. Aspas (“ ”) indicam citação ou destaque.',
      'Ela disse: — Chegamos! · Levei três coisas: caderno, lápis e borracha.',
      'Cada sinal dá um “tom” diferente à frase.',
      'Numa história: — Quem está aí? — perguntou o menino.',
      '1. A frase afirma? Ponto.\n2. Pergunta? Interrogação.\n3. Emoção ou ordem? Exclamação.\n4. Vai explicar ou listar? Dois-pontos.',
      'A pontuação faz na escrita o que a entonação faz na fala: mostra pausas, perguntas e emoções.'),
    block('virgula', 'Quando usar a vírgula',
      'Use vírgula: para separar itens de uma enumeração (comprei arroz, feijão e ovos); para isolar o vocativo, isto é, quem é chamado (Maria, venha cá); para isolar o aposto, a explicação sobre um termo (Recife, capital de Pernambuco, é linda); e para marcar expressões de tempo ou lugar deslocadas para o início (Ontem à noite, fomos ao cinema).',
      'Pedro, você trouxe o livro? · Machado de Assis, escritor carioca, fundou a ABL.',
      'Vírgula separa listas, chamados e explicações.',
      'Mensagem: “Oi, mãe, cheguei!” — “mãe” é vocativo e fica entre vírgulas.',
      '1. É uma lista? Vírgulas entre os itens (antes do “e” final, não).\n2. Está chamando alguém? Isole o nome.\n3. É uma explicação sobre um termo? Isole entre vírgulas.',
      'Vocativo chama (Ana, venha!); sujeito pratica a ação (Ana veio.). Só o vocativo leva vírgula.'),
    block('proibida', 'Onde NÃO usar vírgula',
      'Não se separa o sujeito do verbo nem o verbo de seus complementos: “Os alunos da turma B, fizeram a prova” está errado. O correto é “Os alunos da turma B fizeram a prova”. Também não se usa vírgula antes do “e” que liga os últimos itens de uma lista simples.',
      'Errado: “A professora, explicou a matéria.” Certo: “A professora explicou a matéria.”',
      'Nunca coloque vírgula entre quem faz e o que faz.',
      'Sujeito longo tenta “pedir” vírgula, mas não pode: “Todos os estudantes que chegaram cedo ganharam brinde.”',
      '1. Ache o sujeito e o verbo.\n2. Se a vírgula estiver entre eles, tire.\n3. Confira se não separou o verbo do complemento.',
      'Pausa na fala não é sinônimo de vírgula: às vezes respiramos entre sujeito e verbo, mas na escrita não há vírgula ali.'),
    block('sentido', 'A pontuação muda o sentido',
      'Mudar a vírgula de lugar pode mudar completamente o sentido. “Não, quero sair” (recusa algo e quer sair) × “Não quero sair” (não quer sair). Por isso, pontuar bem é também comunicar bem.',
      '“Vamos comer, crianças!” (chamando as crianças) × “Vamos comer crianças!” (absurdo).',
      'Uma vírgula pode mudar o recado.',
      'Bilhete: “Se o homem soubesse o valor que tem, a mulher andaria de quatro à sua procura” — mude a pontuação e o sentido se inverte.',
      '1. Leia a frase em voz alta com cada pontuação.\n2. Pergunte: o que ela quer dizer?\n3. Escolha a pontuação que expressa sua intenção.',
      'Em questões de prova, observe se a vírgula isola um vocativo ou um aposto: é isso que decide o sentido.'),
  ],
  questions: [
    mc(1, 'sinais', 'Qual sinal usamos para uma pergunta direta?', ['.', '!', '?', ':'], 2, ['Pergunta direta.', 'Interrogação.', '?'], 'Ponto de interrogação.'),
    mc(1, 'virgula', 'Em “Maria, venha cá!”, a vírgula isola:', ['o sujeito', 'o vocativo', 'o aposto', 'o verbo'], 1, ['Maria está sendo chamada.', 'Quem é chamado é…', 'Vocativo.'], 'Vocativo.'),
    tf(1, 'proibida', '“Os alunos, fizeram a prova” está corretamente pontuada.', false, ['Há vírgula entre sujeito e verbo?', 'Sim.', 'Isso é proibido.'], 'Falso: não se separa sujeito do verbo.'),
    fill(1, 'sinais', 'Qual sinal anuncia uma enumeração? (escreva o nome)', ['dois-pontos', 'dois pontos'], ['Vem antes da lista.', 'São dois pontinhos.', 'Dois…'], 'Dois-pontos.'),
    match(2, 'virgula', 'Ligue cada vírgula à sua função.', [['Comprei arroz, feijão e ovos.', 'enumeração'], ['Ana, feche a porta.', 'vocativo'], ['Recife, capital de Pernambuco, é linda.', 'aposto'], ['Ontem à noite, saímos.', 'adjunto deslocado']], ['Lista de itens.', 'Chamado.', 'Explicação; expressão de tempo no início.'], 'enumeração · vocativo · aposto · adjunto.'),
    mc(2, 'proibida', 'Qual frase está corretamente pontuada?', ['A diretora, anunciou o passeio.', 'A diretora anunciou, o passeio.', 'A diretora anunciou o passeio.', 'A, diretora anunciou o passeio.'], 2, ['Sem vírgula entre sujeito e verbo.', 'Nem entre verbo e complemento.', 'Nenhuma vírgula é necessária.'], 'A diretora anunciou o passeio.'),
    mc(2, 'sentido', 'Qual frase expressa que a pessoa NÃO quer sair?', ['Não, quero sair.', 'Não quero sair.', 'Não quero, sair!', 'Não. Quero sair.'], 1, ['A vírgula muda o sentido.', '“Não, quero” = recusa outra coisa.', 'Sem vírgula.'], 'Não quero sair.'),
    order(2, 'virgula', 'Ordene os passos para revisar a pontuação de uma frase.', ['Encontrar sujeito e verbo', 'Retirar vírgulas entre eles', 'Isolar vocativos e apostos', 'Separar itens de listas'], ['Comece pela estrutura.', 'Depois o que é proibido.', 'Por fim, os usos obrigatórios.'], 'Estrutura → proibições → vocativo/aposto → listas.'),
    mc(3, 'sentido', 'Em “Machado de Assis, o autor de Dom Casmurro, nasceu no Rio”, o trecho entre vírgulas é:', ['vocativo', 'aposto', 'sujeito', 'predicado'], 1, ['Explica quem é Machado.', 'Não é um chamado.', 'Explicação = aposto.'], 'Aposto.'),
    open(3, 'sentido', 'Explique a diferença de sentido entre “Vamos comer, crianças!” e “Vamos comer crianças!”.', 'Na primeira frase, a vírgula isola “crianças” como vocativo: alguém chama as crianças para comer. Na segunda, sem vírgula, “crianças” vira o complemento do verbo comer, como se as crianças fossem a comida — um sentido absurdo.', ['vocativo', 'virgula', 'chamando', 'complemento', 'sentido'], ['O que a vírgula faz com “crianças”?', 'Quem é chamado na primeira?', 'O que acontece sem ela?'], 'A vírgula transforma “crianças” em vocativo.'),
  ],
  review: ['Ponto, interrogação, exclamação, dois-pontos, travessão, aspas', 'Vírgula: enumeração, vocativo, aposto, expressão deslocada', 'Nunca entre sujeito e verbo nem entre verbo e complemento', 'A pontuação muda o sentido'],
  relatedQuestions: ['quando usar vírgula', 'o que é vocativo', 'pode vírgula entre sujeito e verbo'],
  equivalentQuestions: eqsPt(['pontuação', 'uso da vírgula', 'vírgula'], ['pode vírgula antes do e', 'o que é aposto', 'vírgula no vocativo', 'quando usar dois pontos', 'quando usar travessão', 'vírgula entre sujeito e verbo', 'vamos comer crianças vírgula', 'sinais de pontuação e suas funções', 'como pontuar um diálogo', 'vírgula depois de expressão de tempo']),
  commonErrors: ['Separar sujeito e verbo com vírgula.', 'Esquecer a vírgula do vocativo.', 'Usar vírgula antes do “e” final de uma lista simples.'],
  sources: FONTES,
})

export const classesGramaticais = lesson({
  id: 'por-classes-gramaticais', subject: 'portugues', title: 'As dez classes gramaticais', levels: [...EF], grade: '6º ao 8º ano',
  topic: 'Gramática', subtopic: 'Classes de palavras: variáveis e invariáveis',
  aliases: ['classes gramaticais', 'classes de palavras', 'morfologia', 'artigo', 'numeral', 'preposicao', 'conjuncao', 'interjeicao', 'adverbio', 'palavras variaveis e invariaveis'],
  summary: 'Conheça as dez classes de palavras, separe as variáveis das invariáveis e descubra a classe pela função na frase.',
  intro: 'Toda palavra tem uma “profissão” na frase. Vamos conhecer as dez!',
  objective: 'Reconhecer as dez classes gramaticais, diferenciar palavras variáveis de invariáveis e identificar a classe de uma palavra pelo seu papel na frase.',
  prerequisites: ['por-substantivo-adjetivo', 'por-verbos'], next: ['por-pronomes', 'por-concordancia'],
  skills: { variaveis: 'Classes variáveis', invariaveis: 'Classes invariáveis', funcao: 'A classe depende da função', identificar: 'Identificar classes numa frase' },
  blocks: [
    block('variaveis', 'As seis classes variáveis',
      'Variáveis mudam de forma (gênero, número, pessoa, tempo): substantivo (nomeia: casa), artigo (acompanha o substantivo: o, a, um, uma), adjetivo (caracteriza: bonita), numeral (quantidade ou ordem: dois, segundo), pronome (substitui ou acompanha o nome: ela, meu, este) e verbo (ação, estado, fenômeno: correr).',
      'O menino alto → Os meninos altos (artigo, substantivo e adjetivo mudaram).',
      'Variáveis são as palavras que mudam de forma.',
      '“Meu primeiro gato” → “Minhas primeiras gatas”: pronome, numeral e substantivo se flexionaram.',
      '1. Tente colocar a palavra no plural ou no feminino.\n2. Ela mudou? É variável.\n3. Descubra qual das seis ela é pelo papel na frase.',
      'Substantivo, artigo, adjetivo, numeral e pronome formam a “turma do nome”; o verbo é a “turma da ação”.'),
    block('invariaveis', 'As quatro classes invariáveis',
      'Invariáveis não mudam de forma: advérbio (modifica verbo, adjetivo ou outro advérbio, indicando tempo, lugar, modo, intensidade: ontem, aqui, bem, muito), preposição (liga palavras: de, em, para, com), conjunção (liga orações ou termos: e, mas, porque, quando) e interjeição (exprime emoção: Oba! Ai! Ufa!).',
      'Ele chegou muito cedo (advérbios) · Livro de Maria (preposição) · Estudei e passei (conjunção).',
      'Invariáveis nunca mudam: advérbio, preposição, conjunção e interjeição.',
      '“Ufa! Cheguei cedo, mas cansado.” — ufa (interjeição), cedo (advérbio), mas (conjunção).',
      '1. A palavra muda de forma? Se não, é invariável.\n2. Modifica verbo/adjetivo? Advérbio.\n3. Liga palavras? Preposição.\n4. Liga orações? Conjunção.\n5. Expressa emoção? Interjeição.',
      'Advérbio está para o verbo como o adjetivo está para o substantivo: um caracteriza a ação; o outro, o nome.'),
    block('funcao', 'A classe depende da função',
      'Uma mesma palavra pode mudar de classe conforme o uso. “O jantar estava bom” (substantivo) × “Vamos jantar” (verbo). “Ela fala alto” (advérbio, modo) × “Ele é alto” (adjetivo). Por isso, analise sempre a palavra dentro da frase.',
      '“O andar de cima” (substantivo) × “Vou andar” (verbo).',
      'Olhe o que a palavra está fazendo na frase.',
      '“Ele é um bom amigo” (adjetivo) × “O bom da festa foi a música” (substantivo: vem com artigo).',
      '1. Leia a frase inteira.\n2. Veja se há artigo antes (indício de substantivo).\n3. Veja a quem a palavra se liga.\n4. Decida a classe pelo papel.',
      'É como uma pessoa que pode ser aluna na escola e treinadora no clube: a função muda conforme o lugar.'),
    block('identificar', 'Identificando numa frase',
      'Para classificar todas as palavras de uma frase, comece pelo verbo, depois ache o substantivo (núcleo do nome), veja o que o acompanha (artigo, adjetivo, pronome, numeral) e, por fim, as palavras de ligação e os advérbios.',
      '“Os dois gatos pretos dormiram tranquilamente no sofá.” → artigo, numeral, substantivo, adjetivo, verbo, advérbio, preposição + artigo (no = em + o), substantivo.',
      'Comece pelo verbo e pelo substantivo; o resto “gira em volta”.',
      'Em provas, a pergunta costuma ser “a palavra X pertence à mesma classe de…” — compare as funções.',
      '1. Marque o verbo.\n2. Marque os substantivos.\n3. Classifique o que acompanha os substantivos.\n4. Classifique advérbios, preposições e conjunções.',
      'Contrações como “no” (em + o) e “do” (de + o) juntam uma preposição e um artigo.'),
  ],
  questions: [
    mc(1, 'invariaveis', 'Qual destas classes é invariável?', ['adjetivo', 'advérbio', 'substantivo', 'pronome'], 1, ['Invariável não muda de forma.', 'Advérbios não vão para o plural.', 'Advérbio.'], 'Advérbio.'),
    mc(1, 'variaveis', 'Em “um gato”, a palavra “um” é:', ['numeral ou artigo, conforme o sentido', 'preposição', 'conjunção', 'advérbio'], 0, ['Acompanha o substantivo.', 'Pode indicar quantidade.', 'Artigo indefinido ou numeral.'], '“Um” pode ser artigo indefinido ou numeral (quantidade).'),
    tf(1, 'invariaveis', '“Oba!” é uma interjeição.', true, ['Expressa emoção.', 'Aparece com exclamação.', 'Sim.'], 'Verdadeiro.'),
    fill(1, 'variaveis', 'Quantas são as classes gramaticais?', ['10', 'dez'], ['Seis variáveis…', '…e quatro invariáveis.', '6 + 4.'], 'São dez.'),
    match(2, 'identificar', 'Ligue cada palavra de “Ontem Ana leu dois livros” à sua classe.', [['Ontem', 'advérbio'], ['Ana', 'substantivo'], ['leu', 'verbo'], ['dois', 'numeral']], ['Tempo → advérbio.', 'Nome próprio → substantivo.', 'Quantidade → numeral.'], 'advérbio · substantivo · verbo · numeral.'),
    mc(2, 'funcao', 'Em “O jantar estava delicioso”, a palavra “jantar” é:', ['verbo', 'substantivo', 'adjetivo', 'advérbio'], 1, ['Tem artigo antes: “o”.', 'Nomeia a refeição.', 'Substantivo.'], 'Substantivo (vem com artigo).'),
    mc(2, 'invariaveis', 'Em “Estudei muito, mas não passei”, a palavra “mas” é:', ['preposição', 'advérbio', 'conjunção', 'interjeição'], 2, ['Liga duas orações.', 'Indica oposição.', 'Conjunção adversativa.'], 'Conjunção.'),
    mc(3, 'funcao', 'Em qual frase “alto” é advérbio?', ['O prédio é alto.', 'Ele fala alto.', 'Um homem alto entrou.', 'O alto da montanha.'], 1, ['Advérbio modifica o verbo.', '“Fala alto” = fala de modo…', 'Modifica “fala”.'], 'Ele fala alto (modo).'),
    order(2, 'identificar', 'Ordene os passos para classificar as palavras de uma frase.', ['Marcar o verbo', 'Marcar os substantivos', 'Classificar o que acompanha os substantivos', 'Classificar as palavras de ligação e os advérbios'], ['Comece pelo verbo.', 'Depois os nomes.', 'Termine pelas invariáveis.'], 'verbo → substantivos → acompanhantes → ligação e advérbios.'),
    open(3, 'funcao', 'Mostre, com duas frases, que a palavra “bom” pode ser de classes diferentes.', 'Em “Ele é um bom aluno”, “bom” é adjetivo, pois caracteriza o substantivo “aluno”. Em “O bom da viagem foi a praia”, “bom” é substantivo, pois vem com o artigo “o” e funciona como núcleo.', ['adjetivo', 'substantivo', 'artigo', 'caracteriza', 'funcao'], ['Use “bom” caracterizando um nome.', 'Depois use com artigo antes.', 'Diga a classe de cada.'], 'A classe depende da função na frase.'),
  ],
  review: ['Variáveis: substantivo, artigo, adjetivo, numeral, pronome, verbo', 'Invariáveis: advérbio, preposição, conjunção, interjeição', 'A classe depende da função na frase', 'Contrações: no = em + o, do = de + o'],
  relatedQuestions: ['quais são as classes gramaticais', 'palavras variáveis e invariáveis', 'o que é advérbio'],
  equivalentQuestions: eqsPt(['classes gramaticais', 'classes de palavras', 'morfologia'], ['quais são as 10 classes gramaticais', 'o que é preposição', 'o que é conjunção', 'o que é interjeição', 'o que é artigo definido', 'o que é numeral', 'diferença entre adjetivo e advérbio', 'palavras invariáveis', 'como saber a classe de uma palavra', 'uma palavra pode mudar de classe']),
  commonErrors: ['Classificar a palavra fora do contexto.', 'Confundir adjetivo com advérbio.', 'Esquecer que “no/na/do/da” reúnem preposição e artigo.'],
  sources: FONTES,
})

export const pronomes = lesson({
  id: 'por-pronomes', subject: 'portugues', title: 'Pronomes', levels: [...EF], grade: '6º ao 8º ano',
  topic: 'Gramática', subtopic: 'Pessoais, possessivos, demonstrativos e de tratamento',
  aliases: ['pronomes', 'pronome pessoal', 'pronome obliquo', 'pronome possessivo', 'pronome demonstrativo', 'este esse aquele', 'para mim ou para eu', 'pronome de tratamento', 'vossa excelencia'],
  summary: 'Use pronomes pessoais, possessivos, demonstrativos e de tratamento e acerte “para mim” × “para eu”.',
  intro: 'Eu, mim, este, esse, Vossa Excelência… Os pronomes evitam repetições e organizam quem fala com quem.',
  objective: 'Reconhecer os principais tipos de pronome, usar retos e oblíquos corretamente (inclusive “para eu fazer”), empregar este/esse/aquele e os pronomes de tratamento.',
  prerequisites: ['por-classes-gramaticais'], next: ['por-concordancia', 'por-coesao-coerencia'],
  skills: { pessoais: 'Pessoais retos e oblíquos', eumim: 'Eu × mim', demonstrativos: 'Este, esse, aquele', tratamento: 'Possessivos e de tratamento' },
  blocks: [
    block('pessoais', 'Pessoais retos e oblíquos',
      'Retos funcionam como sujeito: eu, tu, ele/ela, nós, vós, eles/elas. Oblíquos funcionam como complemento: me, mim, comigo, te, ti, contigo, o, a, lhe, se, si, conosco, vos, os, as, lhes. Na norma-padrão, “Eu vi ela” vira “Eu a vi”.',
      'Ela me ajudou (me = oblíquo). · Nós saímos (nós = reto).',
      'Reto faz a ação; oblíquo recebe a ação.',
      'Convite: “Venha conosco!” (conosco = com nós).',
      '1. A palavra é quem pratica a ação? Pronome reto.\n2. É quem recebe? Pronome oblíquo.',
      'Na fala informal é comum “vi ela”; em textos formais e provas, prefira “vi-a” ou “a vi”.'),
    block('eumim', '“Para mim” ou “para eu”?',
      'Use “eu” quando o pronome for sujeito de um verbo no infinitivo: “Traga o livro para eu ler” (eu leio). Use “mim” depois de preposição quando não houver verbo em seguida para ele ser sujeito: “Traga o livro para mim”. “Entre mim e você” (nunca “entre eu e você”).',
      'Isso é para mim. · Isso é para eu fazer.',
      'Tem verbo depois e o pronome faz a ação? “eu”. Senão, “mim”.',
      'Bilhete: “Deixe a chave comigo para eu abrir a casa.”',
      '1. Veja se vem um verbo logo depois.\n2. O pronome pratica essa ação? Use “eu”.\n3. Não há verbo para ele? Use “mim”.',
      '“Mim não faz nada”: mim nunca é sujeito. Por isso “para mim fazer” está errado.'),
    block('demonstrativos', 'Este, esse, aquele',
      'Os demonstrativos situam no espaço, no tempo e no texto. Este (perto de quem fala; tempo presente; o que ainda vai ser dito). Esse (perto de quem ouve; passado próximo; o que já foi dito). Aquele (longe dos dois; passado distante).',
      'Este livro aqui é meu; esse aí é seu; aquele lá na estante é da biblioteca.',
      'Este = aqui · esse = aí · aquele = lá.',
      'Num texto: “O problema é este: falta tempo.” (vem depois) · “Falta tempo. Esse é o problema.” (já foi dito).',
      '1. Está perto de mim? Este.\n2. Perto de você? Esse.\n3. Longe de nós dois? Aquele.\n4. No texto: vai dizer? este; já disse? esse.',
      'É como os advérbios aqui, aí e lá: este/aqui, esse/aí, aquele/lá.'),
    block('tratamento', 'Possessivos e pronomes de tratamento',
      'Possessivos indicam posse: meu, teu, seu, nosso, vosso (e flexões). Pronomes de tratamento se referem a quem falamos, mas o verbo vai para a 3ª pessoa: você, senhor(a), Vossa Senhoria (autoridades em geral, ofícios), Vossa Excelência (altas autoridades), Vossa Majestade (reis). Use “Vossa” ao falar COM a pessoa e “Sua” ao falar DELA.',
      '“Vossa Excelência aprovou o projeto?” (falando com) · “Sua Excelência, o governador, chegou.” (falando dele).',
      'Tratamento formal usa o verbo como “ele”: Vossa Excelência está…',
      'Numa carta formal ao prefeito: “Solicito a Vossa Excelência que…”',
      '1. Escolha o tratamento pelo cargo.\n2. Fale com a pessoa: Vossa. Fale dela: Sua.\n3. Use o verbo na 3ª pessoa.',
      'Mesmo sendo “Vossa”, o verbo não vai para “vós”: “Vossa Majestade deseja” (e não “desejais”).'),
  ],
  questions: [
    mc(1, 'pessoais', 'Qual é um pronome pessoal reto?', ['me', 'nós', 'lhe', 'comigo'], 1, ['Reto é sujeito.', 'Eu, tu, ele, nós…', 'Nós.'], 'Nós.'),
    mc(1, 'eumim', 'Complete: “Isso é para ___.”', ['eu', 'mim', 'mi', 'meu'], 1, ['Há verbo depois?', 'Não.', 'Depois de preposição, sem verbo: mim.'], 'Para mim.'),
    fill(1, 'eumim', 'Complete: “Traga o livro para ___ ler.”', ['eu'], ['Quem vai ler?', 'O pronome é sujeito de “ler”.', 'Sujeito = eu.'], 'Para eu ler.'),
    tf(1, 'demonstrativos', '“Este” indica algo perto de quem fala.', true, ['Este = aqui.', 'Perto de mim.', 'Sim.'], 'Verdadeiro.'),
    match(2, 'demonstrativos', 'Ligue cada demonstrativo ao lugar.', [['este', 'perto de quem fala (aqui)'], ['esse', 'perto de quem ouve (aí)'], ['aquele', 'longe dos dois (lá)']], ['Este/aqui.', 'Esse/aí.', 'Aquele/lá.'], 'este-aqui · esse-aí · aquele-lá.'),
    mc(2, 'eumim', 'Qual frase está correta?', ['Entre eu e você não há segredos.', 'Entre mim e você não há segredos.', 'Entre mim e tu não há segredos.', 'Entre eu e tu não há segredos.'], 1, ['Depois de “entre” (preposição).', 'Sem verbo para o pronome.', 'Oblíquo: mim, ti.'], 'Entre mim e você.'),
    mc(2, 'tratamento', 'Ao falar diretamente com o prefeito num ofício, usa-se:', ['Sua Excelência', 'Vossa Excelência', 'Vossa Majestade', 'Tu'], 1, ['Falando COM a pessoa.', 'Com: Vossa.', 'Autoridade: Excelência.'], 'Vossa Excelência.'),
    mc(3, 'demonstrativos', 'Qual frase usa o demonstrativo corretamente no texto?', ['Falta tempo. Este é o problema.', 'O problema é esse: falta tempo.', 'Falta tempo. Esse é o problema.', 'O problema é aquele: falta tempo.'], 2, ['Já foi dito ou vai ser dito?', '“Falta tempo” já foi dito.', 'Já dito → esse.'], 'Falta tempo. Esse é o problema.'),
    order(2, 'eumim', 'Ordene o raciocínio para escolher entre “eu” e “mim”.', ['Olhar o que vem depois do pronome', 'Ver se há um verbo no infinitivo', 'Se o pronome pratica a ação, usar “eu”', 'Se não, usar “mim”'], ['Primeiro observe.', 'Procure o verbo.', 'Decida.'], 'Observar → verbo? → eu → mim.'),
    open(3, 'tratamento', 'Por que se diz “Vossa Excelência está cansada?” e não “Vossa Excelência estais cansada?”', 'Porque os pronomes de tratamento, embora tenham “Vossa”, levam o verbo para a 3ª pessoa, como “você” e “ele”. Assim, o correto é “Vossa Excelência está”, e não a forma de “vós”.', ['terceira pessoa', 'tratamento', 'verbo', 'voce', 'ele'], ['Com que pessoa o verbo concorda?', 'Pense em “você está”.', 'É 3ª pessoa.'], 'Pronomes de tratamento → verbo na 3ª pessoa.'),
  ],
  review: ['Retos (sujeito) × oblíquos (complemento)', '“Para eu + verbo” · “para mim” sem verbo · “entre mim e você”', 'Este (aqui), esse (aí), aquele (lá); no texto: este (vai dizer), esse (já disse)', 'Tratamento: Vossa (com) / Sua (sobre) + verbo na 3ª pessoa'],
  relatedQuestions: ['para mim ou para eu', 'diferença entre este e esse', 'tipos de pronomes'],
  equivalentQuestions: eqsPt(['pronomes', 'pronome pessoal', 'pronomes demonstrativos'], ['para mim fazer ou para eu fazer', 'entre eu e você ou entre mim e você', 'quando usar este e esse', 'o que é pronome oblíquo', 'o que é pronome reto', 'vossa excelência ou sua excelência', 'pronomes de tratamento', 'pronome possessivo exemplos', 'eu vi ela está certo', 'conosco ou com nós']),
  commonErrors: ['“Para mim fazer”.', '“Entre eu e você”.', 'Trocar este/esse no texto.'],
  sources: FONTES,
})

export const concordancia = lesson({
  id: 'por-concordancia', subject: 'portugues', title: 'Concordância verbal e nominal', levels: [...EF], grade: '8º e 9º ano e Ensino Médio',
  topic: 'Gramática', subtopic: 'Concordância do verbo e dos nomes',
  aliases: ['concordancia verbal', 'concordancia nominal', 'haver ou haverem', 'fazem dois anos', 'a maioria dos alunos', 'e proibido entrada', 'meio cansada', 'anexo', 'concordancia'],
  summary: 'Faça o verbo concordar com o sujeito e os nomes concordarem entre si, incluindo os casos que mais caem em prova.',
  intro: '“Houveram problemas” ou “houve problemas”? “Meio cansada” ou “meia cansada”? Vamos acabar com a dúvida.',
  objective: 'Aplicar a concordância verbal (sujeito simples, composto, verbos haver e fazer, expressões partitivas) e a concordância nominal (adjetivos, meio, anexo, é proibido).',
  prerequisites: ['por-sujeito-predicado', 'por-classes-gramaticais'], next: ['por-crase'],
  skills: { verbal: 'Concordância verbal: regra geral e sujeito composto', haver: 'Haver e fazer impessoais', partitivo: 'Expressões como “a maioria de”', nominal: 'Concordância nominal' },
  blocks: [
    block('verbal', 'Regra geral da concordância verbal',
      'O verbo concorda em número e pessoa com o sujeito: “O aluno chegou” / “Os alunos chegaram”. Com sujeito composto antes do verbo, o verbo vai para o plural: “Pedro e Ana viajaram”. Se o sujeito composto vier depois, o verbo pode concordar com o mais próximo ou ir ao plural: “Viajaram (ou viajou) Pedro e Ana”.',
      'Os livros da estante caíram (o núcleo é “livros”, plural).',
      'Verbo acompanha o sujeito: um → singular; vários → plural.',
      'Anúncio: “Vendem-se casas” (as casas são vendidas) — o verbo concorda com “casas”.',
      '1. Ache o núcleo do sujeito.\n2. Singular ou plural?\n3. Ajuste o verbo.',
      'Cuidado com sujeitos longos: em “O grupo de alunos das turmas A e B saiu”, o núcleo é “grupo” (singular).'),
    block('haver', 'Haver e fazer impessoais',
      '“Haver” no sentido de existir ou acontecer não tem sujeito e fica sempre no singular: “Houve muitos problemas”, “Há vagas”. “Fazer” e “haver” indicando tempo decorrido também ficam no singular: “Faz dois anos”, “Havia meses que não chovia”. Já “existir” concorda normalmente: “Existem vagas”.',
      'Houve (não “houveram”) reclamações. · Faz (não “fazem”) três dias.',
      'Haver = existir → sempre singular.',
      'Aviso na escola: “Haverá provas na sexta” (singular) × “Existirão provas na sexta” (plural).',
      '1. Troque “haver” por “existir”.\n2. Se o sentido for existir, deixe “haver” no singular.\n3. “Fazer” de tempo → singular.',
      '“Existir” e “haver” têm o mesmo sentido, mas regras diferentes: existir concorda; haver não.'),
    block('partitivo', '“A maioria de”, “parte de”, “um dos que”',
      'Com expressões como “a maioria de”, “grande parte de”, “metade de” + plural, o verbo pode ficar no singular (concordando com “maioria”) ou no plural (com o termo seguinte): “A maioria dos alunos aprovou/aprovaram”. Com porcentagem, costuma concordar com o número ou com o termo seguinte: “30% dos alunos faltaram”.',
      'Grande parte dos jogadores treinou (ou treinaram) cedo.',
      'Com “a maioria de”, singular e plural são aceitos.',
      'Pesquisa: “A maioria dos entrevistados prefere…” (forma mais comum em textos formais).',
      '1. Ache a expressão partitiva.\n2. Escolha: concordar com o núcleo (maioria → singular) ou com o especificador (alunos → plural).\n3. Mantenha a escolha no texto todo.',
      'É um dos poucos casos em que a gramática aceita duas concordâncias — por isso não precisa ter medo dele.'),
    block('nominal', 'Concordância nominal',
      'Artigos, adjetivos, numerais e pronomes concordam com o substantivo em gênero e número. Casos especiais: “meio” como advérbio (= um pouco) não varia: “Ela está meio cansada”; como numeral (metade) varia: “meia hora”. “Anexo” concorda: “Seguem anexas as fotos”. “É proibido entrada” (sem artigo, invariável) × “É proibida a entrada” (com artigo, concorda).',
      'Obrigada! (se quem agradece é mulher) · Muito obrigado! (homem).',
      'O adjetivo “se veste” igual ao substantivo.',
      'E-mail: “Seguem anexos os documentos e anexa a planilha.”',
      '1. Ache o substantivo.\n2. Veja gênero e número.\n3. Ajuste as palavras que o acompanham.\n4. Confira os casos especiais (meio, anexo, é proibido).',
      '“Meio cansada” = um pouco cansada (advérbio, não muda) · “meia xícara” = metade (numeral, concorda).'),
  ],
  questions: [
    mc(1, 'verbal', 'Complete: “Os meninos ___ cedo.”', ['chegou', 'chegaram', 'chegamos', 'chega'], 1, ['O sujeito é plural.', 'Os meninos = eles.', 'Eles chegaram.'], 'Chegaram.'),
    mc(1, 'haver', 'Qual frase está correta?', ['Houveram muitos problemas.', 'Houve muitos problemas.', 'Haviam muitos problemas.', 'Hão muitos problemas.'], 1, ['Haver = existir.', 'Sem sujeito.', 'Singular.'], 'Houve muitos problemas.'),
    fill(1, 'haver', 'Complete com o verbo fazer: “___ dois anos que me mudei.”', ['Faz'], ['Indica tempo decorrido.', 'Fica no singular.', 'F…'], 'Faz dois anos.'),
    tf(1, 'nominal', '“Ela está meia cansada” está correto.', false, ['Meio = um pouco?', 'É advérbio.', 'Advérbio não varia.'], 'Falso: meio cansada.'),
    match(2, 'nominal', 'Ligue cada frase à forma correta.', [['Seguem ___ as fotos. (anexo)', 'anexas'], ['Comi ___ pizza. (meio)', 'meia'], ['É ___ entrada. (proibido)', 'proibido'], ['É ___ a entrada. (proibido)', 'proibida']], ['Anexo concorda.', 'Metade = numeral.', 'Sem artigo: invariável; com artigo: concorda.'], 'anexas · meia · proibido · proibida.'),
    mc(2, 'verbal', 'Qual frase respeita a concordância verbal?', ['Pedro e Ana viajou ontem.', 'Pedro e Ana viajaram ontem.', 'Viajou Pedro e Ana, juntos, ontem, eles.', 'Pedro e Ana viajei ontem.'], 1, ['Sujeito composto antes do verbo.', 'Verbo no plural.', 'Viajaram.'], 'Pedro e Ana viajaram.'),
    mc(2, 'verbal', 'Complete: “O grupo de alunos ___ mais cedo.”', ['saiu', 'saíram', 'sairam', 'saímos'], 0, ['Qual é o núcleo do sujeito?', '“grupo”.', 'Singular.'], 'O grupo saiu.'),
    mc(3, 'partitivo', 'Sobre “A maioria dos alunos aprovou a proposta”, é correto dizer:', ['Só o singular é aceito.', 'Só o plural é aceito.', 'Singular e plural são aceitos.', 'A frase está errada.'], 2, ['Expressão partitiva.', 'Pode concordar com “maioria”…', '…ou com “alunos”.'], 'As duas concordâncias são aceitas.'),
    order(2, 'verbal', 'Ordene os passos para fazer a concordância verbal.', ['Encontrar o verbo', 'Encontrar o sujeito', 'Achar o núcleo do sujeito', 'Ajustar número e pessoa do verbo'], ['Comece pelo verbo.', 'Pergunte quem.', 'Núcleo decide.'], 'verbo → sujeito → núcleo → ajuste.'),
    open(3, 'haver', 'Explique por que se diz “Existem vagas” mas “Há vagas”.', '“Existir” é um verbo pessoal: “vagas” é o sujeito, então o verbo vai para o plural. “Haver” no sentido de existir é impessoal (não tem sujeito); “vagas” é objeto, e o verbo fica sempre no singular.', ['sujeito', 'impessoal', 'singular', 'plural', 'existir', 'haver'], ['Qual dos dois tem sujeito?', 'O que é verbo impessoal?', 'Como fica o verbo sem sujeito?'], 'Existir concorda com o sujeito; haver (existir) é impessoal.'),
  ],
  review: ['Verbo concorda com o núcleo do sujeito', 'Sujeito composto antes do verbo → plural', 'Haver (existir) e fazer (tempo): singular', 'Meio (um pouco) não varia · anexo concorda · é proibido entrada / é proibida a entrada'],
  relatedQuestions: ['houve ou houveram', 'faz dois anos ou fazem dois anos', 'meio cansada ou meia cansada'],
  equivalentQuestions: eqsPt(['concordância verbal', 'concordância nominal', 'concordância'], ['houve ou houveram problemas', 'fazem dois anos ou faz dois anos', 'a maioria dos alunos foi ou foram', 'é proibido entrada ou proibida', 'meio cansada', 'anexo ou anexa', 'obrigado ou obrigada', 'haviam muitas pessoas está certo', 'sujeito composto verbo no plural', 'vende-se casas ou vendem-se casas']),
  commonErrors: ['“Houveram problemas”.', '“Fazem dois anos”.', '“Meia cansada”.'],
  sources: FONTES, enem: 'Concordância aparece em questões de norma-padrão e em redação.',
})

export const crase = lesson({
  id: 'por-crase', subject: 'portugues', title: 'Crase', levels: [...EF], grade: '8º e 9º ano e Ensino Médio',
  topic: 'Gramática', subtopic: 'Quando usar e quando não usar o acento grave',
  aliases: ['crase', 'acento grave', 'a com crase', 'quando usar crase', 'crase antes de horas', 'crase antes de palavra masculina', 'as vezes crase', 'a moda de', 'regras da crase'],
  summary: 'Entenda a crase como a fusão de a + a, use o truque do “ao” e aprenda os casos proibidos e obrigatórios.',
  intro: '“Vou à escola” tem crase; “vou a pé” não tem. Por quê? Um truque simples resolve quase tudo.',
  objective: 'Explicar a crase como a fusão da preposição “a” com o artigo “a”, aplicar o teste do “ao” e identificar os casos obrigatórios e proibidos.',
  prerequisites: ['por-classes-gramaticais', 'por-concordancia'], next: ['por-periodo-composto'],
  skills: { conceito: 'A crase é a + a', truque: 'O teste do “ao”', proibida: 'Quando NÃO usar', obrigatoria: 'Casos obrigatórios (horas, à moda de…)' },
  blocks: [
    block('conceito', 'A + a = à',
      'Crase é a fusão da preposição “a” (exigida por um verbo ou nome: ir a, referir-se a) com o artigo feminino “a” (que acompanha um substantivo feminino). Essa fusão é marcada pelo acento grave: à.',
      'Vou a + a escola = Vou à escola.',
      'Crase = dois “a” que viraram um só com acento.',
      'Quem vai, vai A algum lugar; se o lugar é feminino e aceita “a” (a escola), junta: à escola.',
      '1. Veja se a palavra antes pede a preposição “a”.\n2. Veja se a palavra depois é feminina e aceita o artigo “a”.\n3. Se os dois acontecerem, há crase.',
      'Sem crase, “Vou a escola” estaria faltando o artigo que usamos naturalmente (“a escola é bonita”).'),
    block('truque', 'O teste do “ao”',
      'Troque a palavra feminina por uma masculina equivalente. Se aparecer “ao”, havia crase. Se aparecer só “a” ou “o”, não havia. “Vou à praia” → “Vou ao clube” (tem crase). “Conheço a praia” → “Conheço o clube” (não tem).',
      'Refiro-me à professora → refiro-me ao professor (crase).',
      'Trocou por masculino e deu “ao”? Então é à.',
      '“Entreguei o livro à diretora” → “ao diretor”: tem crase.',
      '1. Substitua a palavra feminina por uma masculina.\n2. Deu “ao”? Use à.\n3. Deu “o” ou “a”? Sem crase.',
      'Para lugares, outro truque: “vou a, volto da, crase há; vou a, volto de, crase pra quê?” (Vou à Bahia / volto da Bahia; vou a Roma / volto de Roma).'),
    block('proibida', 'Quando NÃO há crase',
      'Não há crase antes de palavras masculinas (a pé, a cavalo), antes de verbos (começou a chover), antes da maioria dos pronomes (a ela, a você, a esta, a Vossa Excelência), entre palavras repetidas (cara a cara, gota a gota) e antes de “a” no singular seguido de plural (a pessoas estranhas).',
      'Fui a pé. · Começou a estudar. · Falei a ela. · Frente a frente.',
      'Masculino, verbo e pronome não recebem crase.',
      'Placa: “Proibido estacionar a partir das 18h” — “partir” é verbo, não tem crase.',
      '1. A palavra depois é masculina? Sem crase.\n2. É verbo? Sem crase.\n3. É pronome pessoal ou de tratamento? Sem crase.\n4. Palavras repetidas? Sem crase.',
      'Se não cabe o artigo “a” antes da palavra, não pode haver crase: não dizemos “a ela” com artigo.'),
    block('obrigatoria', 'Casos obrigatórios e especiais',
      'Há crase na indicação de horas (às 8h, à meia-noite), na expressão “à moda de” (arroz à grega, bife à milanesa) e em locuções femininas (às vezes, à noite, à direita, às pressas). Antes de “casa” (lar) e “terra” (chão firme) só há crase se vierem especificadas: “Voltei à casa dos meus avós”.',
      'A aula começa às 7h. · Às vezes estudo à noite.',
      'Horas e “à moda de” sempre levam crase.',
      'Convite: “A festa começa às 20h, na casa da Bia” / “Fui à casa da Bia”.',
      '1. É indicação de hora? à / às.\n2. Dá para colocar “à moda de”? Crase.\n3. É locução feminina (às vezes, à noite)? Crase.',
      '“Às vezes” (locução, = de vez em quando) tem crase; “as vezes que eu fui” (artigo + substantivo) não tem.'),
  ],
  questions: [
    mc(1, 'truque', 'Complete: “Vou ___ escola.”', ['a', 'à', 'á', 'ha'], 1, ['Troque por masculino: vou ___ colégio.', 'Dá “ao”.', 'Então é crase.'], 'Vou à escola (vou ao colégio).'),
    mc(1, 'proibida', 'Qual frase NÃO deve ter crase?', ['Fui à praia.', 'Fui a pé.', 'Voltei às 8h.', 'Refiro-me à diretora.'], 1, ['Qual palavra é masculina?', '“pé”.', 'Antes de masculino não há crase.'], 'Fui a pé.'),
    tf(1, 'proibida', '“Começou à chover” está correto.', false, ['“chover” é o quê?', 'Verbo.', 'Antes de verbo não há crase.'], 'Falso: começou a chover.'),
    fill(1, 'obrigatoria', 'Complete: “A aula começa ___ 7 horas.”', ['às'], ['Indicação de horas.', 'Horas no plural.', 'à + as.'], 'Às 7 horas.'),
    match(2, 'truque', 'Ligue cada frase ao uso correto.', [['Entreguei o livro ___ professora.', 'à (ao professor)'], ['Conheço ___ professora.', 'a (o professor)'], ['Fomos ___ cavalo.', 'a (palavra masculina)'], ['Chegamos ___ meia-noite.', 'à (indicação de hora)']], ['Teste do “ao”.', 'Conheço o professor → sem crase.', 'Cavalo é masculino; meia-noite é hora.'], 'à · a · a · à.'),
    mc(2, 'obrigatoria', 'Qual frase está correta?', ['Comi bife a milanesa.', 'Comi bife à milanesa.', 'Comi bife á milanesa.', 'Comi bife há milanesa.'], 1, ['“à moda milanesa”.', 'Expressão “à moda de”.', 'Tem crase.'], 'Bife à milanesa.'),
    mc(2, 'proibida', 'Qual frase está correta (antes de pronome pessoal)?', ['Falei à ela.', 'Falei a ela.', 'Falei á ela.', 'Falei há ela.'], 1, ['“ela” é pronome pessoal.', 'Não aceita artigo.', 'Sem crase.'], 'Falei a ela.'),
    mc(3, 'truque', 'Qual está correta?', ['Vou à Roma.', 'Vou a Roma.', 'Voltei da Roma.', 'Vou há Roma.'], 1, ['Teste: volto de Roma ou da Roma?', '“Volto de Roma”.', 'Volto de → sem crase.'], 'Vou a Roma (volto de Roma).'),
    order(2, 'truque', 'Ordene o teste do “ao”.', ['Identificar a palavra feminina depois do “a”', 'Trocar por uma palavra masculina', 'Observar se aparece “ao”', 'Usar à se apareceu “ao”'], ['Ache a palavra.', 'Troque.', 'Observe e decida.'], 'identificar → trocar → observar → decidir.'),
    open(3, 'obrigatoria', 'Explique a diferença entre “Às vezes eu estudo” e “Lembro as vezes que estudei”.', 'Em “Às vezes eu estudo”, “às vezes” é locução adverbial feminina (= de vez em quando) e leva crase. Em “Lembro as vezes que estudei”, “as” é só artigo antes de “vezes”, complemento de “lembro”, sem preposição — por isso não há crase.', ['locucao', 'de vez em quando', 'artigo', 'preposicao', 'crase'], ['O que significa “às vezes”?', 'Em “lembro as vezes”, há preposição?', 'Compare as funções.'], 'Locução “às vezes” × artigo + substantivo.'),
  ],
  review: ['Crase = preposição a + artigo a → à', 'Teste do “ao”: trocou por masculino e deu “ao”? crase', 'Não há crase antes de masculino, verbo, pronome e entre palavras repetidas', 'Obrigatória em horas, à moda de e locuções femininas (às vezes, à noite)'],
  relatedQuestions: ['quando usar crase', 'crase antes de horas', 'crase antes de palavra masculina'],
  equivalentQuestions: eqsPt(['crase', 'acento grave', 'regras da crase'], ['vou a escola tem crase', 'crase antes de verbo', 'crase antes de pronome', 'às vezes tem crase', 'crase nas horas', 'a pé tem crase', 'bife à milanesa por que tem crase', 'vou a roma ou vou à roma', 'como saber se tem crase', 'teste do ao para crase']),
  commonErrors: ['Crase antes de verbo (começou à chover).', 'Crase antes de masculino (a pé).', 'Esquecer a crase nas horas (às 8h).'],
  sources: FONTES, enem: 'Crase aparece em questões de norma-padrão e na correção da redação.',
})
