import { block, fill, lesson, mc, tf } from '../dsl'
const F: any[] = []

export const gramatica = lesson({id:'por-gramatica',subject:'portugues',title:'Português: Gramática Essencial',levels:['fund1'],grade:'6º',topic:'Português',subtopic:'Gramática',aliases:['verbo','substantivo','adjetivo','classes palavras'],summary:'Classes de palavras.',intro:'Como funcionam as palavras?',objective:'Entender gramática.',next:[],skills:{c:'Classes',t:'Tempos'},blocks:[block('c','Classes','Substantivo: nome (pessoa, coisa, conceito). Adjetivo: descreve substantivo. Verbo: ação/estado. Advérbio: modifica verbo. Preposição: relação. Conjunção: conecta. Artigo: definição.','10 classes total.','Combinações infinitas.','Função sintática.','Qual classe?'),block('t','Tempos','Passado: o que foi. Presente: agora. Futuro: será. Conjugação: eu, tu, ele, nós, vós, eles. Modo: indicativo (certo), subjuntivo (possível), imperativo (ordem).','Tempo situação.','Concordância necessária.','Nuance meanings.','Qual tempo?'),],questions:[mc(1,'c','Palavra que descreve?',['substantivo','adjetivo','verbo'],1,['Qualidade.','Modificador.','Adorna.']),tf(1,'t','Futuro: ação que virá',true,['Sim.','Amanhã.','Será.']),fill(1,'c','___ é nome de tudo.',['Substantivo'],['Pessoa.','Coisa.','Conceito.']),mc(2,'t','Conjugação: eu ___ estudo.',['estudei','estudo','estudaria'],1,['Presente.','Agora.','Repouso.']),],review:['10 classes','Substantivo/Adjetivo/Verbo','Tempos verbais','Conjugação'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const leitura = lesson({id:'por-leitura',subject:'portugues',title:'Compreensão de Leitura',levels:['fund1'],grade:'7º',topic:'Português',subtopic:'Leitura',aliases:['interpretação','texto','contexto','mensagem','significado'],summary:'Entender o que se lê.',intro:'Ler com compreensão.',objective:'Interpretar textos.',next:[],skills:{i:'Interpretação',c:'Contexto'},blocks:[block('i','Interpretação','Leitura: passiva (só ler) vs ativa (questionar). Ideia principal vs detalhes. Inferência: deduzir não escrito. Propósito autor. Público alvo. Ton e estilo.','Pensamento crítico.','Além palavras.','Significado implícito.','O que autor quis?'),block('c','Contexto','Época texto escrito. Cultura autor. Referências históricas. Vocabulário: define significado. Coerência: ideias conectadas. Coesão: fluidez entre parágrafos.','Situação comunicativa.','Valores época.','Mudanças língua.','Quando escrito?'),],questions:[mc(1,'i','Leitura ativa: qual?',['passar olhos','questionar texto','ignorar','ler rápido'],1,['Crítica.','Profunda.','Interativa.']),tf(1,'c','Contexto afeta significado',true,['Sim.','Época.','Interpretação.']),fill(1,'i','Inferência: ___ do não escrito.',['deduzir'],['Subentender.','Implícito.','Raciocínio.']),mc(2,'c','Coesão: qual?',['ideias corretas','fluidez parágrafos','clareza','sem erros'],1,['Ligação.','Transição.','Ritmado.']),],review:['Interpretação','Inferência','Contexto','Coerência/Coesão'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const escrita = lesson({id:'por-escrita',subject:'portugues',title:'Técnicas de Escrita',levels:['fund1'],grade:'7º',topic:'Português',subtopic:'Produção',aliases:['redação','paragrafação','estrutura','clareza','coerência'],summary:'Escrever com clareza.',intro:'Do pensamento à página.',objective:'Produções textuais.',next:[],skills:{p:'Planejamento',e:'Estrutura'},blocks:[block('p','Planejamento','Brainstorm: ideias soltas. Outline: organização. Público: escreve para quem? Tom: formal/informal. Propósito: informar/persuadir/entreter. Revisão: reescrever quantas vezes necessário.','Preparação essencial.','Não sai pronto.','Iterativo.','Qual objetivo?'),block('e','Estrutura','Introdução: gancha + tese. Desenvolvimento: argumentos + exemplos. Conclusão: resumo + reflexão. Parágrafos: 1 ideia cada. Transições: conectam ideias. Variação: não repetir.','Forma importa.','Leitor segue.','Lógica fluxo.','Como organizar?'),],questions:[mc(1,'p','Brainstorm: fase?',['antes de escrever','ao escrever','depois de escrever'],0,['Ideação.','Criativo.','Solto.']),tf(1,'e','Cada parágrafo: 1 ideia',true,['Sim.','Foco.','Clareza.']),fill(1,'p','___ é reescrever até perfeição.',['Revisão'],['Polimento.','Essencial.','Qualidade.']),mc(2,'e','Conclusão: qual?',['nova ideia','resumo+reflexão','apenas repetir','questão sem resposta'],1,['Fechamento.','Síntese.','Pensamento.']),],review:['Planejamento','Outline','Estrutura','Revisão'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})

export const literatura = lesson({id:'por-literatura',subject:'portugues',title:'Literatura: Gêneros e Estilos',levels:['medio'],grade:'8º',topic:'Português',subtopic:'Literatura',aliases:['prosa','poesia','drama','romance','conto'],summary:'Formas de contar histórias.',intro:'Beleza das palavras.',objective:'Apreciar literatura.',next:[],skills:{g:'Gêneros',r:'Recursos'},blocks:[block('g','Gêneros','Prosa: narrativa natural (romance, conto, crônica). Poesia: forma + ritmo + rima (verso, estrofe, métrica). Drama: diálogo + conflito (peça, tragédia, comédia).','3 gêneros principais.','Hibridação moderna.','Evolução contínua.','Qual gênero?'),block('r','Recursos','Metáfora: comparação implícita. Metonímia: troca significados relacionados. Aliteração: repetição sons. Hipérbole: exagero. Símile: comparação com "como". Personificação: qualidade humana coisa.','Figuras linguagem.','Efeito poético.','Expressividade.','Qual recurso?'),],questions:[mc(1,'g','Romance é qual gênero?',['poesia','prosa','drama'],1,['Narrativo.','Extenso.','Prosa.']),tf(1,'r','Metáfora: comparação implícita',true,['Sim.','Figura.','Beleza.']),fill(1,'g','___ : forma + ritmo + verso.',['Poesia'],['Arte.','Métrica.','Musicalidade.']),mc(2,'r','Personificação: qual?',['compara com como','dá qualidade humana','exagera','compara direto'],1,['Humanizar.','Coisa→ser.','Figura.']),],review:['3 gêneros','Prosa/Poesia/Drama','Figuras linguagem','Recursos estilísticos'],relatedQuestions:[],equivalentQuestions:F,commonErrors:[],sources:F,
})
